### ISSUE TITLE
[OurBits] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8647] opened 2020-05-14 23:41 UTC
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.16.438

**Last Working Jackett Version**: 0.16.427

**Are you using a proxy or VPN?** No

### Description
I cannot configure OurBits. The website works fine; I can log out and back in normally.

### Logged Error Messages
I get the following error message when I try to configure OurBits:
`An error occurred while updating this indexer`
`Clearance failed after 10 attempt(s).` 

Enhanced log:
[log.txt](https://github.com/Jackett/Jackett/files/4631549/log.txt)

### Screenshots
Not needed

**Comment by garfield69** [comment] 2020-05-14 23:58
It is likely that the cloudflare challenge has changed again. Similar issue being reported for yggtorrent via #8635

**Comment by RoloSoze** [comment] 2020-05-15 00:02
Probably, might also be similar to the issue being reported in #8639 which is another major Chinese tracker.

**Comment by garfield69** [comment] 2020-05-15 22:03
Jackett 0.16.463

**Comment by RoloSoze** [comment] 2020-06-03 13:58
The issue is back again. Another Cloudflare change? @ngosang

**Comment by garfield69** [comment] 2020-06-03 23:35
related to cloudflare issue, duplicate of #8840

**Closed by garfield69** 2020-06-03 23:35 UTC
