### ISSUE TITLE
as of Pre-release v0.8.10 - 401.Unauthorized

### ISSUE THREAD

**Issue by PaintPauller** [Jackett/Jackett#1654] opened 2017-08-12 00:43 UTC
as of Pre-release v0.8.10 i am unable to change any settings in Jackett for some reason but more importantly sonarr is unable to connect with jackett. i keep on getting this in sonarr:

Unable to connect to indexer, check the log for more details
Log: 17-8-11 17:15:12.5|Warn|HttpClient|HTTP Error - Res: [GET] http://127.0.0.1:9117/torznab/thepiratebay/api?t=caps&apikey=(removed) 401.Unauthorized

Jackett version:  v0.8.10
Mono version (if not using Windows):  

-------------------------------

**Comment by flightlevel** [comment] 2017-08-12 01:03
Thanks for testing the pre-release and reporting @PaintPauller 
The settings issue will be fixed shortly

2nd issue:
Just to confirm the api key is correct?

Do you get the same thing if visiting http://127.0.0.1:9117/torznab/thepiratebay/api?t=caps&apikey=YOUR_API_KEY in your web brower

Can you post the full Jackett logs ie `mono --debug JackettConsole.exe -t -l`

I've tested here and it works for me

**Comment by PaintPauller** [comment] 2017-08-12 01:15
i can confirm that the api key is correct in sonarr and http://127.0.0.1:9117/torznab/thepiratebay/api?t=caps&apikey=YOUR_API_KEY does work for me so i have no idea whats going on. 

as for the logs nothing shows up in the normal log and i am unable to turn on Enhanced logging because of the settings bug. where would i put in the above command? sorry im somewhat new to all of this.

**Comment by flightlevel** [comment] 2017-08-12 01:19
v0.8.12 should fix the settings issue

Thats strange that it works in the browser
Are you running on Windows or Mono?

**Comment by PaintPauller** [comment] 2017-08-12 01:20
windows

**Comment by flightlevel** [comment] 2017-08-12 01:27
update version to latest
Turn on enhanced logging
Restart Jackett
simulate error again
Grab logs from C:\ProgramData\Jackett

**Comment by PaintPauller** [comment] 2017-08-12 01:28
here is the enhanced logging when I hit test in sonarr


Aug 11, 2017 06:24:53 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
-- | -- | --
Aug 11, 2017 06:24:53 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Aug 11, 2017 06:24:53 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Aug 11, 2017 06:24:53 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Aug 11, 2017 06:24:53 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 11, 2017 06:24:53 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 11, 2017 06:24:53 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 11, 2017 06:24:53 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 11, 2017 06:24:53 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Aug 11, 2017 06:24:53 PM | Info | ApiControllerActionSelector SelectAction
Aug 11, 2017 06:24:53 PM | Info | ServerConfigurationController ExecuteAsync
Aug 11, 2017 06:24:53 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Aug 11, 2017 06:24:53 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Aug 11, 2017 06:24:53 PM | Info | DefaultHttpControllerActivator Create
Aug 11, 2017 06:24:53 PM | Info | HttpControllerDescriptor CreateController
Aug 11, 2017 06:24:53 PM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Aug 11, 2017 06:24:53 PM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Aug 11, 2017 06:24:53 PM | Info | http://127.0.0.1:9117/api/v2.0/server/logs?_=1502501084604
Aug 11, 2017 06:24:48 PM | Info | ResultsController Dispose
Aug 11, 2017 06:24:48 PM | Info | ResultsController Dispose
Aug 11, 2017 06:24:48 PM | Info | Content-type='none', content-length=unknown
Aug 11, 2017 06:24:48 PM | Info | ResultsController ExecuteAsync
Aug 11, 2017 06:24:48 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 11, 2017 06:24:48 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 11, 2017 06:24:48 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Torznab(TorznabRequest request)'
Aug 11, 2017 06:24:48 PM | Info | ApiControllerActionSelector SelectAction
Aug 11, 2017 06:24:48 PM | Info | ResultsController ExecuteAsync
Aug 11, 2017 06:24:48 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ResultsController
Aug 11, 2017 06:24:48 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ResultsController
Aug 11, 2017 06:24:48 PM | Info | DefaultHttpControllerActivator Create
Aug 11, 2017 06:24:48 PM | Info | HttpControllerDescriptor CreateController
Aug 11, 2017 06:24:48 PM | Info | DefaultHttpControllerSelector SelectController Results
Aug 11, 2017 06:24:48 PM | Info | DefaultHttpControllerSelector SelectController Route='indexerId:thepiratebay,controller:Results,action:Torznab'
Aug 11, 2017 06:24:48 PM | Info | http://127.0.0.1:9117/torznab/thepiratebay/api?t=caps&apikey=7tzg8zjc8ctht6830ie41tcgi3lo45bo
Aug 11, 2017 06:24:45 PM | Info | IndexerApiController Dispose
Aug 11, 2017 06:24:45 PM | Info | IndexerApiController Dispose
Aug 11, 2017 06:24:45 PM | Info | JsonMediaTypeFormatter WriteToStreamAsync
Aug 11, 2017 06:24:45 PM | Info | JsonMediaTypeFormatter WriteToStreamAsync Value='System.Linq.Enumerable+WhereSelectEnumerableIterator`2[Jackett.Indexers.IIndexer,Jackett.Models.DTO.Indexer]', type='IEnumerable`1', content-type='application/json; charset=utf-8'
Aug 11, 2017 06:24:45 PM | Info | Content-type='application/json; charset=utf-8', content-length=unknown
Aug 11, 2017 06:24:45 PM | Info | IndexerApiController ExecuteAsync
Aug 11, 2017 06:24:45 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Aug 11, 2017 06:24:45 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Indexers()'
Aug 11, 2017 06:24:45 PM | Info | ApiControllerActionInvoker InvokeActionAsync
Aug 11, 2017 06:24:45 PM | Info | DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8'
Aug 11, 2017 06:24:45 PM | Info | JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter
Aug 11, 2017 06:24:45 PM | Info | JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='IEnumerable`1', mediaType='application/json; charset=utf-8'
Aug 11, 2017 06:24:45 PM | Info | DefaultContentNegotiator Negotiate Type='IEnumerable`1', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer]
Aug 11, 2017 06:24:45 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Linq.Enumerable+WhereSelectEnumerableIterator`2[Jackett.Indexers.IIndexer,Jackett.Models.DTO.Indexer]'
Aug 11, 2017 06:24:45 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Indexers()'
Aug 11, 2017 06:24:45 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Indexers()'

**Comment by PaintPauller** [comment] 2017-08-12 01:30
[log.txt](https://github.com/Jackett/Jackett/files/1219380/log.txt)
here is the log you requested

**Comment by flightlevel** [comment] 2017-08-12 01:39
Can you remove KickAssTorrent from both Jackett and Sonarr to see if thats the cause of the issue?
Are you adding each index individually in Sonarr?

**Comment by PaintPauller** [comment] 2017-08-12 01:42
i have already removed KickAssTorrent from both unless you are talking about KickAssTorrent (kat.how).
yes i am adding each index individually in sonarr but none of them work even the ones i have had working for months and the ones i added today before the update to v0.8.10 that i also had working.

**Comment by PaintPauller** [comment] 2017-08-12 01:47
removed KickAssTorrent (kat.how) from both jackett and sonarr. no change, every index is still gives 401 in sonarr.

**Comment by flightlevel** [comment] 2017-08-12 06:11
the logs should have more information...

Stop Jackett
From the cmd prompt run `JackettConsole.exe -t -l`
Reproduce the error
Upload logs

Otherwise, if not interested in getting your hands dirty, go back to the last released version v0.7.1644

**Comment by chibidev** [comment] 2017-08-12 08:47
@PaintPauller could you turn on Debug level logging in Sonarr and upload your logs? Thanks.

**Comment by D4rk56** [comment] 2017-08-12 15:13
Same Error
[http://imgur.com/NEVxHnw](http://imgur.com/NEVxHnw)

**Comment by mbush78** [comment] 2017-08-12 16:11
Same issue here for the past few days, just updated to 0.8.18 and still the same. Ran logs with the requested -t -l from above, here was the result

******@Ubuntu:/tmp$ wget 'http://192.***.***.100:9117/api/v2.0/indexers/******/results/torznab/api?t=caps&apikey=ekhg4ha*****************jn3qh'
--2017-08-12 11:05:04--  http://192.***.***.100:9117/api/v2.0/indexers/******/results/torznab/api?t=caps&apikey=ekhg4ha*****************jn3qh
Connecting to 192.***.***.100:9117... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.



08-12 11:05:04 Info   http://192.***.***.100:9117/api/v2.0/indexers/******/results/torznab/api?t=caps&apikey=ekhg4ha*****************jn3qh 
System.Web.Http.Request:   http://192.***.***.100:9117/api/v2.0/indexers/******/results/torznab/api?t=caps&apikey=ekhg4ha*****************jn3qh
08-12 11:05:04 Info WebAPIRequestLogger SendAsync  
System.Web.Http.MessageHandlers: WebAPIRequestLogger SendAsync 

08-12 11:05:04 Debug GET: http://192.***.***.100:9117/api/v2.0/indexers/******/results/torznab/api?t=caps&apikey=ekhg4ha*****************jn3qh 
08-12 11:05:04 Debug Body:  
08-12 11:05:04 Info DefaultHttpControllerSelector SelectController Route='indexerId:******,action:torznab,ignored:api,controller:Results' 
System.Web.Http.Controllers: DefaultHttpControllerSelector SelectController Route='indexerId:******,action:torznab,ignored:api,controller:Results'
08-12 11:05:04 Info DefaultHttpControllerSelector SelectController Results 
System.Web.Http.Controllers: DefaultHttpControllerSelector SelectController Results
08-12 11:05:04 Info HttpControllerDescriptor CreateController  
System.Web.Http.Controllers: HttpControllerDescriptor CreateController 
08-12 11:05:04 Info DefaultHttpControllerActivator Create  
System.Web.Http.Controllers: DefaultHttpControllerActivator Create 
08-12 11:05:04 Info DefaultHttpControllerActivator Create Jackett.Controllers.V20.ResultsController 
System.Web.Http.Controllers: DefaultHttpControllerActivator Create Jackett.Controllers.V20.ResultsController
08-12 11:05:04 Info HttpControllerDescriptor CreateController Jackett.Controllers.V20.ResultsController 
System.Web.Http.Controllers: HttpControllerDescriptor CreateController Jackett.Controllers.V20.ResultsController
08-12 11:05:04 Info ResultsController ExecuteAsync  
System.Web.Http.Controllers: ResultsController ExecuteAsync 
08-12 11:05:04 Info ApiControllerActionSelector SelectAction  
System.Web.Http.Action: ApiControllerActionSelector SelectAction 
08-12 11:05:04 Info ApiControllerActionSelector SelectAction Selected action 'Torznab(TorznabRequest request)' 
System.Web.Http.Action: ApiControllerActionSelector SelectAction Selected action 'Torznab(TorznabRequest request)'
08-12 11:05:04 Info JackettAuthorizedAttribute OnAuthorizationAsync  
System.Web.Http.Filters: JackettAuthorizedAttribute OnAuthorizationAsync 
08-12 11:05:04 Info JackettAuthorizedAttribute OnAuthorizationAsync  
System.Web.Http.Filters: JackettAuthorizedAttribute OnAuthorizationAsync 
08-12 11:05:04 Info ResultsController ExecuteAsync  
System.Web.Http.Controllers: ResultsController ExecuteAsync 
08-12 11:05:04 Info WebAPIRequestLogger SendAsync  
System.Web.Http.MessageHandlers: WebAPIRequestLogger SendAsync 
08-12 11:05:04 Info   Content-type='none', content-length=unknown 
System.Web.Http.Request:   Content-type='none', content-length=unknown
08-12 11:05:04 Info ResultsController Dispose  
System.Web.Http.Controllers: ResultsController Dispose 
08-12 11:05:04 Info ResultsController Dispose  
System.Web.Http.Controllers: ResultsController Dispose

**Comment by chibidev** [comment] 2017-08-12 18:21
@D4rk56 please post your enhanced Jackett logs as well

**Comment by D4rk56** [comment] 2017-08-12 18:29
`

When | Level | Message
-- | -- | --
Aug 12, 2017 08:28:05 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Logs()'
Aug 12, 2017 08:28:05 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Logs()'
Aug 12, 2017 08:28:05 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Aug 12, 2017 08:28:05 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Logs()'
Aug 12, 2017 08:28:05 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 12, 2017 08:28:05 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 12, 2017 08:28:05 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 12, 2017 08:28:05 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 12, 2017 08:28:05 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Logs()'
Aug 12, 2017 08:28:05 PM | Info | ApiControllerActionSelector SelectAction
Aug 12, 2017 08:28:05 PM | Info | ServerConfigurationController ExecuteAsync
Aug 12, 2017 08:28:05 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.ServerConfigurationController
Aug 12, 2017 08:28:05 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.ServerConfigurationController
Aug 12, 2017 08:28:05 PM | Info | DefaultHttpControllerActivator Create
Aug 12, 2017 08:28:05 PM | Info | HttpControllerDescriptor CreateController
Aug 12, 2017 08:28:05 PM | Info | DefaultHttpControllerSelector SelectController ServerConfiguration
Aug 12, 2017 08:28:05 PM | Info | DefaultHttpControllerSelector SelectController Route='action:logs,controller:ServerConfiguration'
Aug 12, 2017 08:28:05 PM | Info | http://176.31.255.40:9117/api/v2.0/server/logs?_=1502562488155
Aug 12, 2017 08:28:04 PM | Info | IndexerApiController Dispose
Aug 12, 2017 08:28:04 PM | Info | IndexerApiController Dispose
Aug 12, 2017 08:28:04 PM | Info | JsonMediaTypeFormatter WriteToStreamAsync
Aug 12, 2017 08:28:04 PM | Info | JsonMediaTypeFormatter WriteToStreamAsync Value='System.Linq.Enumerable+WhereSelectEnumerableIterator`2[Jackett.Indexers.IIndexer,Jackett.Models.DTO.Indexer]', type='IEnumerable`1', content-type='application/json; charset=utf-8'
Aug 12, 2017 08:28:04 PM | Info | Content-type='application/json; charset=utf-8', content-length=unknown
Aug 12, 2017 08:28:04 PM | Info | IndexerApiController ExecuteAsync
Aug 12, 2017 08:28:04 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Aug 12, 2017 08:28:04 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Indexers()'
Aug 12, 2017 08:28:04 PM | Info | ApiControllerActionInvoker InvokeActionAsync
Aug 12, 2017 08:28:04 PM | Info | DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8'
Aug 12, 2017 08:28:04 PM | Info | JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter
Aug 12, 2017 08:28:04 PM | Info | JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='IEnumerable`1', mediaType='application/json; charset=utf-8'
Aug 12, 2017 08:28:04 PM | Info | DefaultContentNegotiator Negotiate Type='IEnumerable`1', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer]
Aug 12, 2017 08:28:04 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Linq.Enumerable+WhereSelectEnumerableIterator`2[Jackett.Indexers.IIndexer,Jackett.Models.DTO.Indexer]'
Aug 12, 2017 08:28:04 PM | Info | ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Indexers()'
Aug 12, 2017 08:28:04 PM | Info | ApiControllerActionInvoker InvokeActionAsync Action='Indexers()'
Aug 12, 2017 08:28:04 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync
Aug 12, 2017 08:28:04 PM | Info | JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Indexers()'
Aug 12, 2017 08:28:04 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 12, 2017 08:28:04 PM | Info | HttpActionBinding ExecuteBindingAsync
Aug 12, 2017 08:28:04 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 12, 2017 08:28:04 PM | Info | JackettAuthorizedAttribute OnAuthorizationAsync
Aug 12, 2017 08:28:04 PM | Info | ApiControllerActionSelector SelectAction Selected action 'Indexers()'
Aug 12, 2017 08:28:04 PM | Info | ApiControllerActionSelector SelectAction
Aug 12, 2017 08:28:04 PM | Info | IndexerApiController ExecuteAsync
Aug 12, 2017 08:28:04 PM | Info | HttpControllerDescriptor CreateController Jackett.Controllers.V20.IndexerApiController
Aug 12, 2017 08:28:04 PM | Info | DefaultHttpControllerActivator Create Jackett.Controllers.V20.IndexerApiController
Aug 12, 2017 08:28:04 PM | Info | DefaultHttpControllerActivator Create
Aug 12, 2017 08:28:04 PM | Info | HttpControllerDescriptor CreateController
Aug 12, 2017 08:28:04 PM | Info | DefaultHttpControllerSelector SelectController IndexerApi
Aug 12, 2017 08:28:04 PM | Info | DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Aug 12, 2017 08:28:04 PM | Info | http://176.31.255.40:9117/api/v2.0/indexers?_=1502562488154

`

**Comment by PaintPauller** [comment] 2017-08-12 23:36
just got up and updated to Jackett Version 0.8.25.0. everything looks to be working again! thanks for all the help!

**Comment by bdorsey16** [comment] 2017-08-12 23:57
i'm on 0.8.25.0 and i'm still getting the error for both torznab and potato feed

**Comment by PaintPauller** [comment] 2017-08-13 00:02
ok take that back i was able to reproduce the problem but i may have narrowed it down for you. after i got all 10 of my indexers set up and working i went to add a Admin password to jackett and as soon as i did that sonarr stopped working and started producing the 401.Unauthorized

hope this helps you track it down!

**Comment by PaintPauller** [comment] 2017-08-13 00:06
just changed my password back to blank and it still does not work so i think it has something to do with a fresh install. i say this because before you make a password shows as "blank to disable" but when you add a password it changes to **** and even after changing it back to blank it shows as **** and will still produce the 401.Unauthorized error in sonarr

**Comment by chibidev** [comment] 2017-08-13 00:26
@PaintPauller that's actually very helpful, and I hope I've finally found the issue. v0.8.26 should resolve it, please give it a go.

**Comment by PaintPauller** [comment] 2017-08-13 00:30
i can confirm that v0.8.26 fixed it. even after adding back a password sonarr no longer gives the 401.Unauthorized error.

thanks for the fix and glad i was able to help you out!

**Comment by D4rk56** [comment] 2017-08-13 10:20
It works again for me, but only for Radar, not Sonarr.
What is the api path now? (/api) ?

**Comment by razlebol** [comment] 2017-08-13 15:28
Same issue as D4rk56, some don't work in Sonarr while they do work in Radarr. I have a few that do work in Sonarr but the majority don't.

**Comment by D4rk56** [comment] 2017-08-13 15:32
**400.BadRequest**

`NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [https://plex.noplay.fr/jackett/api/v2.0/indexers/yggtorrent/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=35xvfybszy0m5ptzaazqgaat58z3cpgs&offset=0&limit=100]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00129] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:98 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchIndexerResponse (NzbDrone.Core.Indexers.IndexerRequest request) [0x0004b] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:302 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00000] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:288 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0000e] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:316 
<Error><Message>yggtorrent does not support the requested query.</Message></Error>`

**Comment by bdorsey16** [comment] 2017-08-13 16:47
Torznab routes work for me within Sonarr now. Potatofeed routes return a `System.Runtime.Serialization.InvalidDataContractException`. Changing the route from `http://localhost:9117/api/v2.0/indexers/privatehd/results` to `http://localhost:9117/potato/privatehd` returned results however

**Comment by Eventyret** [comment] 2017-08-13 20:04
Just to confirm I still get this error as well 401.
I can post logs if it's wanted? But on latest 0.8.26.0 here.
Both Radarr and Sonarr Throwing errors and unable to connect to Jackett. (Ubuntu server)

**Comment by tv8tony** [comment] 2017-08-14 02:39
also  get failed test in sonarr  on eztv, sky torrents, torrent project, but the pirate bay works 
i have tried re installing  older versions and the setting the password blank 

i am on windows Jackett Version 0.8.48.0

i was getinging the 401 error now i am geting 
Unable to connect to indexer: HTTP request failed: [400:BadRequest] [GET] at [http://127.0.0.1:9117/torznab/skytorrents/api?t=tvsearch&cat=5030,5040&extended=1&apikey=xxxxxxxxxxxxx&offset=0&limit=100]

and

HTTP Error - Res: [GET] http://127.0.0.1:9117/torznab/skytorrents/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100: 400.BadRequest
<Error><Message>skytorrents does not support the requested query.</Message></Error>

i have to manually set Categories in sonarr to match the ones in jackett 
i did not have to do this befor is this intended ? 
if so the "Adding a Jackett indexer in Sonarr or Radarr" needs updating

**Comment by chibidev** [comment] 2017-08-14 08:47
Everyone getting HTTP error 400 and "xyz does not support the requested query", v0.8.49 probably fixes that. Please update and see if it's working.

**Comment by D4rk56** [comment] 2017-08-14 15:32
Fix v0.8.49 work for me !

**Comment by tv8tony** [comment] 2017-08-14 16:44
Jackett Version 0.8.55.0 all fixed for me

**Closed** 2017-08-14 17:41 UTC

**Comment by KennyVB** [comment] 2017-08-20 06:27
i have the error on latest pre-realse version  0.8.67.0
testing my apices here
http://10.0.1.36:9117/torznab/hounddawgs/api?t=caps&apikey=APIKEY
verify it works
how ever the link for potato feed http://10.0.1.36:9117/api/v2.0/indexers/hounddawgs/results/potato/
doesnt seem to work from couchpotato, and when I visit the link I get a error from couchpotato 
ERROR
[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.1.36:9117/api/v2.0/indexers/hounddawgs/results/potato/?imdbid=tt0103855&user=&passkey=xxx&user=&passkey=xxx

**Comment by Eventyret** [comment] 2017-08-20 13:11
@KennyVB that looks like its not passing the user and its doing user and the key twice
