### ISSUE TITLE
[kickasstorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Protektor-Desura** [Jackett/Jackett#2485] opened 2018-01-25 20:16 UTC
KickAssTorrent (https://katcr.co/)
Fails testing but the website is up and searchable.

Jackett version:  0.8.626.0
Mono version (if not using Windows):  4.6.2

-------------------------------

**Comment by garfield69** [comment] 2018-01-25 22:35
Duplicate of #2280

**Closed by garfield69** 2018-01-25 22:35 UTC
Labels: Duplicate
