### ISSUE TITLE
Cannot add IPTorrents. Tried the usual fixes.

### ISSUE THREAD

**Issue by davida72** [Jackett/Jackett#4596] opened 2019-02-03 10:27 UTC
When I click on the spanner to add IPTorrents I see

> Request to Jackett server failed

I am using privoxy, which goes through my VPN because my ISP blocks the site. I've had it working before and I'm not sure when it stopped - maybe after a reboot? Privoxy seems to be working. 

I've tried with and without privoxy. I've also tried my VPN's HTTP and SOCKS5 proxy. I've tried with and without a mirror URL provided in a iptorrents.json file as mentioned in [4424](https://github.com/Jackett/Jackett/issues/4424). I'm using binhex docker container, but have tried others and got the same result.

Advice appreciated!

UPDATE: I found another machine that it was working on. Worked perfectly using the same proxy. When I deleted IPTorrents and added it again the same error occurred. I'm fairly sure the problem is limited to **adding** the indexer, not in using it.

This is from within the docker container. Appears to be blocked, because the the Jackett container itself doesn't use the VPN, just the program.
```
*   Trying 104.23.203.30...
* TCP_NODELAY set
* Connected to iptorrents.com (104.23.203.30) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to iptorrents.com:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to iptorrents.com:443
```

This is from the Terminal on my mac, which is a different computer on the same network. Again, blocked.
```
*   Trying 104.23.202.30...
* TCP_NODELAY set
* Connected to iptorrents.com (104.23.202.30) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to iptorrents.com:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to iptorrents.com:443 
```

The Mono version from within the docker container.
```
Mono JIT compiler version 5.14.0 (makepkg/f3a2216b65a Fri Aug 17 18:51:18 CEST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

And the error log from Jackett.
```
System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: SecureChannelFailure (Unable to read data from the transport connection: Connection reset by peer.) ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
  at System.Net.Sockets.Socket.EndReceive (System.IAsyncResult asyncResult) [0x00012] in <b1198703583846f1be8a1683e1db86e6>:0 
  at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x00057] in <b1198703583846f1be8a1683e1db86e6>:0 
   --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x0009b] in <b1198703583846f1be8a1683e1db86e6>:0 
  at System.IO.Stream+<>c.<BeginEndReadAsync>b__47_1 (System.IO.Stream stream, System.IAsyncResult asyncResult) [0x00000] in <815942dd495d4ccc954b977c1d4bee11>:0 
  at System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[TResult,TInstance].Complete (TInstance thisRef, System.Func`3[T1,T2,TResult] endMethod, System.IAsyncResult asyncResult, System.Boolean requiresSynchronization) [0x00000] in <815942dd495d4ccc954b977c1d4bee11>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Mono.Net.Security.MobileAuthenticatedStream+<InnerRead>d__66.MoveNext () [0x00104] in <b1198703583846f1be8a1683e1db86e6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Mono.Net.Security.AsyncProtocolRequest+<InnerRead>d__25.MoveNext () [0x000ac] in <b1198703583846f1be8a1683e1db86e6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Mono.Net.Security.AsyncProtocolRequest+<ProcessOperation>d__24.MoveNext () [0x00093] in <b1198703583846f1be8a1683e1db86e6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Mono.Net.Security.AsyncProtocolRequest+<StartOperation>d__23.MoveNext () [0x0008b] in <b1198703583846f1be8a1683e1db86e6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Mono.Net.Security.MobileAuthenticatedStream+<ProcessAuthentication>d__47.MoveNext () [0x00254] in <b1198703583846f1be8a1683e1db86e6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Mono.Net.Security.MonoTlsStream+<CreateStream>d__17.MoveNext () [0x00126] in <b1198703583846f1be8a1683e1db86e6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebConnection+<CreateStream>d__18.MoveNext () [0x001ba] in <b1198703583846f1be8a1683e1db86e6>:0 
   --- End of inner exception stack trace ---
  at System.Net.WebConnection+<CreateStream>d__18.MoveNext () [0x0021a] in <b1198703583846f1be8a1683e1db86e6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebConnection+<InitConnection>d__19.MoveNext () [0x00141] in <b1198703583846f1be8a1683e1db86e6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebOperation+<Run>d__57.MoveNext () [0x0009a] in <b1198703583846f1be8a1683e1db86e6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebCompletionSource`1+<WaitForCompletion>d__15[T].MoveNext () [0x00094] in <b1198703583846f1be8a1683e1db86e6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__244`1[T].MoveNext () [0x000c5] in <b1198703583846f1be8a1683e1db86e6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <b1198703583846f1be8a1683e1db86e6>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <815942dd495d4ccc954b977c1d4bee11>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0041d] in <863261da85fa459daf42d16ece032f10>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <863261da85fa459daf42d16ece032f10>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <863261da85fa459daf42d16ece032f10>:0 
--- End of stack trace from previous location where exception was thrown ---
  at CloudFlareUtilities.ClearanceHandler+<PassClearance>d__24.MoveNext () [0x0023c] in <d0213015414e4bf286b46bc1ee77bd72>:0 
--- End of stack trace from previous location where exception was thrown ---
  at CloudFlareUtilities.ClearanceHandler+<SendAsync>d__20.MoveNext () [0x00193] in <d0213015414e4bf286b46bc1ee77bd72>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <863261da85fa459daf42d16ece032f10>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Utils.Clients.HttpWebClient+<Run>d__7.MoveNext () [0x00456] in <e4e98a2615484e8d811543a9c3ca48ae>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Utils.Clients.WebClient+<GetString>d__18.MoveNext () [0x0010b] in <e4e98a2615484e8d811543a9c3ca48ae>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.BaseWebIndexer+<RequestStringWithCookies>d__5.MoveNext () [0x000cb] in <e4e98a2615484e8d811543a9c3ca48ae>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.IPTorrents+<GetConfigurationForSetup>d__14.MoveNext () [0x00075] in <e4e98a2615484e8d811543a9c3ca48ae>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Server.Controllers.IndexerApiController+<Config>d__12.MoveNext () [0x0006a] in <adb52187bb21461bb4ee04f1697a2fba>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x0008a] in <adb52187bb21461bb4ee04f1697a2fba>:0 

```

**Comment by neiliid** [comment] 2019-02-05 09:52
I have the same issue. I have however noticed that IPT now uses Cloudflare when logging in and I wonder whether this isn't the cause of the issue. 

It might be similar to this issue: https://github.com/Jackett/Jackett/issues/2852

Any suggestions would be appreciated.

**Comment by davida72** [comment] 2019-02-05 10:41
I thought it might be that too. Is there a way that theory could be tested?

**Comment by davida72** [comment] 2019-02-05 20:14
Ack! Today IPTorrents is missing from my indexer list. I hadn't changed anything. How has that happened? Is it somehow related to #4594? My hack of just copying the files from the other computer no longer works.

it's still works okay on my other computer.

**Comment by davida72** [comment] 2019-02-06 08:10
For some reason one of the comments has disappeared. It suggested the problem is caused by IPTorrents recent use of Cloudflare.

**Comment by davida72** [comment] 2019-02-07 16:08
Okay. Having spent more hours than I care to admit on this (including attempting to debug from source) I have a few pieces of information which may help to narrow down the issue.

- The issue almost certainly relates to the fact that my ISP blocks connections to IPTorrents as everything works perfectly on an ISP that doesn't block it.
- There seem to be a lot more issues _adding_ the indexer than _using_ it.
- It probably has something to do with proxies. My proxy is with my VPN, which should avoid any blocking. I've tried different proxies, suggesting it isn't an issue with my proxy.
- It might have something to do with the fact that IPTorrents is using Cloudflare.
- I have had issues where it was listed in my indexer list but then disappeared without having changed anything.
- I have tried a number of docker containers. Each behaved similarly.

I'd really like to help fix this issue. Let me know what are useful things to try.

**Comment by mcmurray** [comment] 2019-02-09 13:53
Hello 

I am also having issues adding iptorrents to jackett. I am in the uk so its blocked by my ISP but i have found a link i can access without a VPN.

https://ip.findnemo.net

For me I could not get IPtorrents to show in my list but when I created a JSON file in the indexers folder called iptorrents.json with the follow text inside it appeared.

[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "http://kong.net-freaks.com/"
  },
]

I still could not connect even when i changed the URL to the working URL. I also noticed this URL is not in the list in the iptorrents config page.

Im pretty sure its either ISP blocking or Clouflare.

**Comment by davida72** [comment] 2019-02-09 20:31
So you are able to get IPTorrents to show on the list by using a non-blocked mirror, but you weren't able to connect to it and search?

I agree. It's likely to be linked to iSP blocking and/or Cloudflare. I don't know why it would be ISP blocking if I'm using a proxy though.

**Comment by Ar3na** [comment] 2019-02-17 12:05
I've had the same issue as you.  Using Socks5 proxy.
I got round it by adding a temp VPN connection while adding the tracker.  Worked perfectly.  Removed VPN and as expected Jackett/IPT now work correctly.

So this does point to Jackett not using the proxy while adding the tracker.
Hope this helps.

**Comment by davida72** [comment] 2019-02-17 13:18
Good spot. Thanks.

**Comment by ngosang** [comment] 2019-12-02 17:27
@davida72 maybe this help https://github.com/Jackett/Jackett/issues/6446#issuecomment-560093162

**Comment by davida72** [comment] 2019-12-02 21:08
Thanks for bringing that solution to my attention, which is to try the .NET Core version rather than the Mono version. 

It was a long time ago when I experienced the problem, which I think I resolved by going through a VPN rather than a proxy.

**Comment by dylanrjones** [comment] 2020-01-10 01:33
I copied a json from my windows computer to unraid and it didn't work, so I deleted everything except

[
{
"id": "sitelink",
"type": "inputstring",
"name": "Site Link",
"value": "http://ipt.lol/"
},
]

and it showed up on the list. After that I could edit it with my username and password and it seems to work.

**Comment by ngosang** [comment] 2020-02-08 11:48
We did some changes in IPTorrents code to improve the debug information. Please, could you update to the latest version (Jackett 0.12.1746 or newer) and provide feedback? If there is an exception, enable the `Enhanced logging` and post the logs. Thank you!

**Comment by davida72** [comment] 2020-02-08 21:26
Thanks so much for taking a look at this. 

Unfortunately (for you) since I reported this I somehow fixed it and now I'm unsure how to repeat the bug. If there's something specific you'd like me to try then I'd be happy to do it.

**Comment by ngosang** [comment] 2020-02-09 14:56
I'm closing then. We have more IPTorrents issues open to deal with.

**Closed by ngosang** 2020-02-09 14:56 UTC
