### ISSUE TITLE
Torrentday just needs a url edit..

### ISSUE THREAD

**Issue by seannmac** [Jackett/Jackett#6915] opened 2020-01-11 05:48 UTC
[torrentday] Exception (torrentday): The remote name could not be resolved: 'tday.love
Please update the url to torrentday.com

**Comment by junglebus** [comment] 2020-01-11 06:34
Duplicate of https://github.com/Jackett/Jackett/issues/6880
Download the latest release

**Closed** 2020-01-11 06:35 UTC
