### ISSUE TITLE
[gktorrent] Exception (gktorrent): Specified argument was out of the range of valid values.Parameter name: Unknown operator: : Specified argument was out of the range of valid values.Parameter name: Unknown operator:  (Test)

### ISSUE THREAD

**Issue by Jamyz** [Jackett/Jackett#5054] opened 2019-04-10 07:31 UTC
**Jackett version**:  Jackett Version 0.11.205.0 Docker
**Mono version**: Jackett Version 0.11.205.0 Docker

**Comment by garfield69** [comment] 2019-04-10 07:59
duplicate of #4982

**Comment by freMea** [comment] 2019-04-23 18:25
I guess it’s their ddos protection.

**Comment by Jamyz** [comment] 2019-04-23 19:32
I don’t try but check release 0.11.245

**Comment by garfield69** [comment] 2019-04-23 20:01
yes, its the cloudflare ddos protection. the issue will remain outstanding until either:
- the site drops their ddos protection, or
- the cloudflareutilities.dll that jackett uses to attempt to resolve the challenge is updated for the recent cloudflare ddos challenge. 

#4982 is the origin ticket which I've already posted earlier, and where you need to watch if you want updates on progress.

**Comment by garfield69** [comment] 2019-08-22 19:50
solved with Jackett 0.11.635

**Closed by garfield69** 2019-08-22 19:50 UTC
Labels: Duplicate
