### ISSUE TITLE
3 Tracker don't work anymore with Jackett

### ISSUE THREAD

**Issue by Gromak123** [Jackett/Jackett#1615] opened 2017-08-03 17:45 UTC
Hi !

Im on the latest (dev) version of Jackett and 3 big Public French tracker doesn't work anymore.
 The tracker are : cpasbien, Next Torrent and Torrent-Mania (now zetorrents). 
I have try to change to the correct domain on the 3 but this doesn't work either.

Would be good if this can be solve. This is the principal source of tracker for the French community since T411 is down. 

Thank's !

**Comment by flightlevel** [comment] 2017-08-05 01:27
Next time create a separate Issue for each tracker there is a problem with (after searching to make sure there isn't already an open issue) and add logs

@JigSawFr @ploufs @gprime44
Any thoughts on these, tricks, are they getting taken down like t411?

**Comment by ploufs** [comment] 2017-08-05 21:19
Pull request : https://github.com/Jackett/Jackett/pull/1619

**Comment by Gromak123** [comment] 2017-08-05 23:49
Hi, 

Woh ok sorry for the multiple tracker in one issue, i had think this would help. Will split next time.

I can give log if you need, also T411 is up again -> New domain is T411.si, not the original team but great tracker.

**Comment by flightlevel** [comment] 2017-08-06 01:36
@Gromak123 
Thanks to @ploufs  these are now present in the latest release
In regards to t411 https://github.com/Jackett/Jackett/issues/1601

Am I right in that we can now delete https://github.com/Jackett/Jackett/blob/master/src/Jackett/Definitions/maniatorrent.yml
replaced by zetorrent?

**Comment by ploufs** [comment] 2017-08-06 01:56
Beta version t411 : https://github.com/Jackett/Jackett/pull/1620

**Comment by Gromak123** [comment] 2017-08-06 13:15
Yeah thank's for your awesome work guy ! 

Yes maniatorrent is remplaced by zetorrents now.

**Comment by lrnv** [comment] 2017-08-08 20:20
So the new (not-same-but-better) T411.si is availiable in jacket now ?

**Comment by gprime44** [comment] 2017-08-09 07:51
@lrnv  Yes :-)

**Comment by hed0nist** [comment] 2017-08-10 10:09
Can you all confirm the nextorrent definition working fine in its actual state ? Because even with a correct url it doesn't pass internal test and can't retrieve torrent files.
I made a working version for my personnal use and wanted confirmation of non-working state before trying to pull corrections.

Edit : i just updated to latest pre-release, same test failure.

**Comment by ploufs** [comment] 2017-08-10 11:30
@hed0nist https request work on your jackett server? 

Check in log for error.

**Comment by hed0nist** [comment] 2017-08-11 05:40
@ploufs : indeed there are errors in my logs

Aug 11, 2017 07:30:30 AM | Error | Exception in test_indexer
Aug 11, 2017 07:30:30 AM | Info | Found 0 releases from NextTorrent
Aug 11, 2017 07:30:30 AM | Info | CardigannIndexer (nexttorrent): Relogin required
Could it be https ( ssl ) related ?

FYI i just made a few modifications , using https in the url setting, removing 2 lines and modifying the rows selector to make it work as intended.

**Comment by kaso17** [comment] 2017-08-11 16:47
next torrent needs an URL update
default fixed with 33a7db5ec41b0a0259cdf1b7a6d7b780fd92a059
the other two have been fixed already too
clsoing

**Closed by kaso17** 2017-08-11 16:47 UTC
