### ISSUE TITLE
[demonoid] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by lamahmud** [Jackett/Jackett#2467] opened 2018-01-24 02:05 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.618.0
Mono version (if not using Windows):  Mono JIT compiler version 5.4.0.201 (2017-06/71277e78f6e Thu Sep 21 19:22:55 EDT 2017)
[log.20180123.00002.txt](https://github.com/Jackett/Jackett/files/1658247/log.20180123.00002.txt)

-------------------------------

**Comment by garfield69** [comment] 2018-01-24 02:10
Duplicate of #2458 fix has been issued but pre(release) not yet published.

**Closed by garfield69** 2018-01-24 02:10 UTC
