### ISSUE TITLE
jackett wipes itself on update 

### ISSUE THREAD

**Issue by Commissar0617** [Jackett/Jackett#11313] opened 2021-03-14 03:19 UTC
### Environment

**OS**: debian 10.7

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
i don't honestly know. 
**.Net Version**:
how find? 
**Jackett Version**: 

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

no vpn/proxy
 
### Description

open sonarr, see many many indexers down for 6h+, go to jackett, see no indexers. happened last saturday  as well, but reverted to a backup. log looks like jackett restarted. will revert to a backup again, but will likely happen again. 

### Logged Error Messages

see screenshot

### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/5993529/111056008-1f6e6000-8441-11eb-8ef5-9f6eec219a01.png)

![image](https://user-images.githubusercontent.com/5993529/111056046-7c6a1600-8441-11eb-8060-df1121d5b809.png)

**Comment by Commissar0617** [comment] 2021-03-14 03:33
ill do an apt upgrade, see if that helps anything...

**Comment by garfield69** [comment] 2021-03-14 03:36
I cant help you with the vanishing stuff, its linux, so one of the other team members (@ilike2burnthing ?) will help.
But for the necessary version and other stuff, most of it you will find in the log, when you first start Jackett up.
So access the dashboard, view log, go to the bottom and you should see lines like
```
2021-03-14 16:33:46 Info Using HTTP Client: HttpWebClient2
2021-03-14 16:33:46 Info Using FlareSolverr: No
2021-03-14 16:33:46 Info Using proxy: Disabled
2021-03-14 16:33:46 Info App config/log directory: /home/garfield69/.config/Jackett
2021-03-14 16:33:46 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-03-14 16:33:46 Info Running in Docker: No
2021-03-14 16:33:46 Info File /etc/issue: Ubuntu 18.04.5 LTS \n \l
2021-03-14 16:33:46 Info Jackett variant: CoreLinuxAmdx64
2021-03-14 16:33:46 Info OS version: Unix 4.15.0.136 (64bit OS) (64bit process)
2021-03-14 16:33:46 Info Environment version: 5.0.4 (/opt/Jackett/)
2021-03-14 16:33:45 Info Starting Jackett v0.17.677
```
so cost copy paste that below and it will be helpful. Thanks.

**Comment by Commissar0617** [comment] 2021-03-14 03:40
> 
> 
> I cant help you with the vanishing stuff, its linux, so one of the other team members (@ilike2burnthing ?) will help.
> But for the necessary version and other stuff, most of it you will find in the log, when you first start Jackett up.
> So access the dashboard, view log, go to the bottom and you should see lines like
> 
> ```
> 2021-03-14 16:33:46 Info Using HTTP Client: HttpWebClient2
> 2021-03-14 16:33:46 Info Using FlareSolverr: No
> 2021-03-14 16:33:46 Info Using proxy: Disabled
> 2021-03-14 16:33:46 Info App config/log directory: /home/garfield69/.config/Jackett
> 2021-03-14 16:33:46 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
> 2021-03-14 16:33:46 Info Running in Docker: No
> 2021-03-14 16:33:46 Info File /etc/issue: Ubuntu 18.04.5 LTS \n \l
> 2021-03-14 16:33:46 Info Jackett variant: CoreLinuxAmdx64
> 2021-03-14 16:33:46 Info OS version: Unix 4.15.0.136 (64bit OS) (64bit process)
> 2021-03-14 16:33:46 Info Environment version: 5.0.4 (/opt/Jackett/)
> 2021-03-14 16:33:45 Info Starting Jackett v0.17.677
> ```
> 
> so just copy/paste that below and it will be helpful. Thanks.

ah, yeah. that's in that 2nd screenshot. currently restoring from a backup from february. it's a proxmox vm, so it's not suuper hard to restore, but it actually seems like perhaps jackett is doing uncommanded restarts...

**Comment by garfield69** [comment] 2021-03-14 03:41
Oh, you did that already, didn't see the screen dump, duh ;-D

**Comment by Commissar0617** [comment] 2021-03-14 03:42
also, the API key changed too. so it's like jackett reinstalled itself or something?

**Comment by Commissar0617** [comment] 2021-03-14 03:43
also, the version from the backup in 17.584. perhaps it's an issue with the auto update...

**Comment by garfield69** [comment] 2021-03-14 03:44
Jackett will auto-update daily if the dashboard option is enabled, and after updating it will restart the Jackett service to load any new/updated indexers that came with the package.
But that would not normally cause indexers to vanish, so I don't know what it going on there, hence the need for a volunteer with more linux experience.

**Comment by garfield69** [comment] 2021-03-14 03:45
if the key is changing then that suggests that the default config folder is not being found... wonder why that is happening?

**Comment by Commissar0617** [comment] 2021-03-14 03:45
> 
> 
> Jackett will auto-update daily if the dashboard option is enabled, and after updating it will restart the Jackett service to load any new/updated indexers that came with the package.
> But that would not normally cause indexers to vanish, so I don't know what it going on there, hence the need for a volunteer with more linux experience.

yup. im just collecting information that may or may not be helpful. FWIW, jackett has auto updated fine before. hell, i haven't had to touch it in months until it started doing this...

**Comment by Commissar0617** [comment] 2021-03-14 03:47
ok, so i manually updated to 17.677... and it happened again.

**Comment by garfield69** [comment] 2021-03-14 03:51
@ilike2burnthing  wonder if #11173 has anything to do with this?

**Comment by garfield69** [comment] 2021-03-14 03:57
@Commissar0617  when you look at the log for the new update jackett 0.17.677 is the `App config/log directory:` the same as what you posted at the beginning of this ticket (pay attention to upper/lower cases too) ?

**Comment by Commissar0617** [comment] 2021-03-14 03:58
![image](https://user-images.githubusercontent.com/5993529/111056755-3a43d300-8447-11eb-8e51-e6b89b2c4160.png)
very different

**Comment by garfield69** [comment] 2021-03-14 03:58
oh, actually the reverse, I meant the log for the restored 17.584 versus 17.677

**Comment by garfield69** [comment] 2021-03-14 03:59
Ok so there is the problem then. now how to fix...

**Comment by garfield69** [comment] 2021-03-14 04:04
so the old 17.584 was set up to store the configs in the main binary Jackett folder? 
very odd looking setup...
Possible circumvention would be to restore 17.584, find the config files in `Jackett` and copy them over to `/home/commissar/.config/Jackett

**Comment by Commissar0617** [comment] 2021-03-14 04:09
> 
> 
> so the old 17.584 was set up to store the configs in the main binary Jackett folder?
> very odd looking setup...
> Possible circumvention would be to restore 17.584, find the config files in `Jackett` and copy them over to `/home/commissar/.config/Jackett`

well, lets find out here.... be just a minute

**Comment by garfield69** [comment] 2021-03-14 04:15
my ubuntu config has a couple folders (dataprotection, Indexers) and some *.json and *.txt
```
garfield69@Ubuntu-VirtualBox:~/.config/Jackett$ ls
DataProtection  Indexers  log.txt  ServerConfig.json  updater.txt  updater.txt.20200911.00000.txt
```
so those are the ones to copy over

**Comment by ilike2burnthing** [comment] 2021-03-14 04:18
Was typing out a response and some troubleshooting without realising there were new comments (that's what I get for not paying attention). Is the current thinking that this is unique to this install (a config issue maybe), or are we still looking at #11173 potentially being the cause?

**Comment by Commissar0617** [comment] 2021-03-14 04:20
well, im gonna try and find out if his idea works here. assuming i can find the files he's talking about

**Comment by garfield69** [comment] 2021-03-14 04:21
@ilike2burnthing  wrote:
> Is the current thinking that this is unique to this install (a config issue maybe), or are we still looking at #11173 potentially being the cause?

probably a bit of both. We have a config that is not standard, but maybe now that 11173 creates a default config when its not found means that the old config is no longer being referenced?

**Comment by Commissar0617** [comment] 2021-03-14 04:22
working dir in the service file is /home.commissar/Jackett... i don't run it as root

**Comment by Commissar0617** [comment] 2021-03-14 04:31
yeah, for some reason, the configs are inside a folder inside the folder of the binary... but i copys them now

**Comment by Commissar0617** [comment] 2021-03-14 04:34
got em copied...
![image](https://user-images.githubusercontent.com/5993529/111057323-36667f80-844c-11eb-8783-18cf7ed05d4d.png)

**Comment by Commissar0617** [comment] 2021-03-14 04:38
that worked.... heh

**Comment by garfield69** [comment] 2021-03-14 04:41
\o/

**Comment by paul-chambers** [comment] 2021-03-14 07:27
I'm also affected by this issue. I have my configuration in `/var/lib/jackett` (which is the home directory of the `jackett` user), with the binaries installed in `/usr/share/jackett`. Version v0.17.684 no longer finds the existing configuration in `/var/lib/jackett`.

**Comment by ilike2burnthing** [comment] 2021-03-14 15:39
@NinjaLikesCheez could you have a look at this? Thanks.

**Comment by NinjaLikesCheez** [comment] 2021-03-14 20:33
Hm, I think I needed to update the `CreateOrMigrateSettings` function in `ConfigurationService.cs` to migrate config directories from the older versions... Should have thought about that. I'll try to replicate the issue read through `ConfigurationService.cs` this week.

@garfield69 hit it on the head.`~/.config/Jackett` is where the configuration was intended to be in previous versions too, but due to a bug (addressed in #11173) this would drop the `~/.config/` portion of the path if that folder didn't already exist, leading to some users having config directories in the working directory.

As a work around for now, you can either manually move your config to `~/.config/Jackett` or you can change your invocation of the jackett binary to add `-d`/`--DataFolder` to point to you existing config directory (I _think_).

**Comment by garfield69** [comment] 2021-03-31 06:27
v0.17.826

**Comment by tiomny** [comment] 2021-04-01 07:39
Issue persists

**Comment by tiomny** [comment] 2021-04-01 07:43
I have some concerns regarding the code in the \Jackett.Common\Services\ConfigurationService.cs
* Line 38 
`if (!Directory.Exists(GetAppDataFolder()))`
when OS==UNIX and CustomDataFolder is not set, this is always false since DataFolder is created in getter.
@NinjaLikesCheez
* Line 98
`if (!Directory.Exists(oldDirectory))`
This is always false when called from line 92 `PerformMigration("Jackett");` since Jackett folder was created before. 
It seems that the code below deletes Jackett configuration folder, please correct me if I'm wrong.

**Comment by tiomny** [comment] 2021-04-01 08:31
@NinjaLikesCheez correct - I'm using Jacket on top of DietPi (armv8 debian linux), and after each restart (even when Jacket is updated) it removes all the configuration files and creates new ones. 
Jacket folder is /opt/jackett.
Jacket config folder is /opt/jackett/Jackett.

**Comment by tiomny** [comment] 2021-04-01 08:41
It seems that PerformMigration copies config files from Jackett to Jackett (tries copying files to its selves). I'm not sure what goes next - does this operation throw an exception either completes successfully then removes config dir Jackett when CustomDataFolder not set.

**Comment by NinjaLikesCheez** [comment] 2021-04-01 08:49
@tiomny If I remember correctly, it will remove the 'old' folder after migrating which is why it's wiping the directory. GetApplicationData should be returning a folder that's not in the install directory (unless a custom location is set) so it seems odd it's returning ‘/opt/jackett/Jackett‘ so I'll look into that too as the documentation doesn't explicitly say what the path will be. 

A quick fix that should be made in addition is checking if the destination folder is that same as the AppData folder and not performing a migration, although this would break the original migration made ~6ish years ago that copied files with an updated file access controls

**Comment by tiomny** [comment] 2021-04-01 09:09
@NinjaLikesCheez because of /etc/passwd contents
```
...
jackett:x:994:992::/opt/jackett:/usr/sbin/nologin
...
```

**Comment by Arghh** [comment] 2021-04-02 05:05
Related issue on DietPi https://github.com/MichaIng/DietPi/issues/4237

**Comment by jspoonamore** [comment] 2021-04-02 05:43
> @NinjaLikesCheez correct - I'm using Jacket on top of DietPi (armv8 debian linux), and after each restart (even when Jacket is updated) it removes all the configuration files and creates new ones.
> Jacket folder is /opt/jackett.
> Jacket config folder is /opt/jackett/Jackett.

Having the same issues.  I am also using DietPi (but in a VM with a VPN).

**Comment by josh3003** [comment] 2021-04-02 06:52
Same issue as well dietpi on rpi4

**Comment by PrzemekSkw** [comment] 2021-04-02 09:35
Same here on Dietpi3 installed on mini pc. Indexers are gone and API is different. I set everything from beginning and after few hours

**Comment by manomaya90** [comment] 2021-04-02 09:49
Also happening to me in DietPi on RPi4.

**Comment by NinjaLikesCheez** [comment] 2021-04-02 09:59
@tiomny I've pushed a branch to https://github.com/NinjaLikesCheez/Jackett/tree/feature/fix_migrations would you be able to test this with your setup before I open a PR?

It does a check to ensure we don't migrate configs that are installed to `$HOME` as well as adding a guard check to the code that removes the 'migrated' configs if the paths are the same to hopefully stop this from happening in the future (I still am not quite sure how this hasn't been removing Windows configs for years - I'll put it down to my lack of understanding of the language & codebase 😜)

**Comment by jspoonamore** [comment] 2021-04-02 10:08
I think I'm fixed for now.  I modified /etc/systemd/system/jacket.service.
I pointed the config setting to a new folder.  I restarted Jackett and settings did not get wiped.

**Comment by tiomny** [comment] 2021-04-02 10:15
@jspoonamore this is not a fix - this is a workaround. DietPi has a tool called dietpi_software which installs jackett and does necessary changes. This is unlikely that users will be manually edit something after automatic installation.
It is possible that DietPi developers will make an effort to change the installation script but I wouldn't be so sure that the only DietPi has such script - a lot of other installation scripts might be broken because of this bug.

**Comment by jspoonamore** [comment] 2021-04-02 10:25
> @jspoonamore this is not a fix - this is a workaround. DietPi has a tool called dietpi_software which installs jackett and does necessary changes. This is unlikely that users will manually edit something after automatic installation.
> It is possible that DietPi developers will make an effort to change the installation script but I wouldn't be so sure that the only DietPi has such script - a lot of other installation scripts might be broken because of this bug.

Last I checked.... The DietPI people are pointing fingers here for the solution.  In any case....  I know this a work-around.  But, it's a fix for me.  I will continue to monitor the issue.  If this gets fixed, I've only modified the config file location.  A no-brainer to fix later.

**Comment by flyg100** [comment] 2021-04-02 14:32
As a dietpi user with all settings lost - is my original config still there just in a different location? dont really understand how to apply the work around tiher.

**Comment by Joulinar** [comment] 2021-04-02 21:26
basically a workaround could be this one until a permanent solution has been found https://github.com/MichaIng/DietPi/issues/4237#issuecomment-812694920

**Comment by NinjaLikesCheez** [comment] 2021-04-03 09:58
If a DietPi user could try the #11465 and see if that addresses their issues that would be great - I don't have a pi to test on.

**Comment by Joulinar** [comment] 2021-04-03 10:02
@NinjaLikesCheez 
It's off-topic but no need for a RPi device. DietPi can be setup on a VM as well 😉

**Comment by NinjaLikesCheez** [comment] 2021-04-03 10:03
> @NinjaLikesCheez
> It's off-topic but no need for a RPi device. DietPi can be setup on a VM as well 😉

In that case - I'll set up a VM :D

**Closed** 2021-04-03 18:24 UTC
Labels: OS Linux / Mono / *nix

**Comment by ilike2burnthing** [comment] 2021-04-04 04:49
[v0.17.841](https://github.com/Jackett/Jackett/releases/tag/)

**Comment by garfield69** [comment] 2021-04-04 21:56
@NinjaLikesCheez  I don't know if the code covers this, but essentially, IMO, if the user has coded a home directory with https://github.com/Jackett/Jackett#home-directory-1 then we should be bypassing any migration processing.
