### ISSUE TITLE
[rutracker] Пожалуйста, введите код подтверждения (символы, изображенные на картинке) (Config)

### ISSUE THREAD

**Issue by darioristic** [Jackett/Jackett#2516] opened 2018-01-30 23:54 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment] 2018-01-31 00:48
Looks like rutorrent is challenging you with a captcha image and want you to enter the captcha text, which you will need to enter in the captcha-box of the rutorrent config on your jackett dashboard.  Is there a problem completing this task?

**Comment by alxlaxv** [comment] 2018-03-19 12:55
@garfield69 I guess you can close it

**Comment by Cromm** [comment] 2018-06-21 14:34
I came across this problem too. It only triggers following a failed login. However, once it has triggered you cannot register the tracker without copying the captcha image contents into the captcha text box (as you say @garfield69). However, the problem is, is that you cannot see the capture image as only the error message itself is produced in the Jackett dashboard. see image here: 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/776702/41725722-698a08aa-7568-11e8-9682-b00d1e59d1ac.png">

So, is there a way to remove the (presumably) cookie that indicates that a failed login has taken place and thereby avoid the problem occurring in the first place. Or, a way to see the entire error message/page so that the catcha message may be seen?

**Comment by garfield69** [comment] 2018-06-21 19:05
@kaso17 any thoughts on what cromm has  asked in the previous post ?

**Comment by kaso17** [comment] 2018-06-22 14:56
@Cromm the captcha is not refreshed on a failed login. You've to close/reopen the configuration dialog to refresh it after a failed login. It's a generic problem/limitation of jackett.

**Closed by kaso17** 2018-06-22 14:56 UTC
