### ISSUE TITLE
AvistaZ not fetching with Sonarr

### ISSUE THREAD

**Issue by tylerhammer** [Jackett/Jackett#806] opened 2016-12-05 13:48 UTC
Re-opening from https://github.com/Jackett/Jackett/issues/382

Finally had time to look back at this. 

This issue is still relevant. I can search and find in Jackett Webui but when plugged into Sonarr it does not find any shows.

**Comment by savahu** [comment] 2016-12-05 13:58
Just tested AvistaZ with CouchPotato, this works fine..

**Comment by tylerhammer** [comment] 2016-12-05 13:59
So that means it would be something between Sonarr and Jackett specifically.

**Comment by kaso17** [comment] 2016-12-05 14:17
Please provide an example+log. Click on automatic search in sonarr for the episode and provide us with the jackett log during that time.

**Comment by tylerhammer** [comment] 2016-12-05 14:30
So the example that I'm trying to find is Running Man E 328. Sonarr returns nothing for both Automatic and Manual. 

Jackett Logs show

`Dec 05, 2016 09:27:03 AM 	Info 	

Found 0 releases from Avistaz for: Running Man S2016E328

Dec 05, 2016 09:25:29 AM 	Info 	

Found 50 (0 new) releases from Avistaz

Dec 05, 2016 09:24:19 AM 	Info 	

Found 0 releases from Avistaz for: Running Man S2016E328

Dec 05, 2016 09:18:12 AM 	Info 	

redirecting to /Admin/Dashboard

Dec 05, 2016 09:15:01 AM 	Info 	

Found 50 (1 new) releases from Avistaz

Dec 05, 2016 09:13:46 AM 	Info 	

Service started

Dec 05, 2016 09:13:44 AM 	Info 	

Starting web server at http://127.0.0.1:9117/`

It looks like it may have to do with the way Jackett and Sonarr are searching for these Variety shows that dont really have Seasons. It searching S2016E328. When you do a manual search in Jackett, you see Running Man E328 . Nothing about season.

**Comment by kaso17** [comment] 2016-12-05 15:02
duplicate of #569
Can't fix this properly with jackett.
A workaround might be to add absolute episode numbers on thetvdb.com, wait until Sonarr picks them up and set series type to anime in sonarr. That might work.

**Closed by kaso17** 2016-12-05 15:02 UTC
Labels: Needs Investigations
