### ISSUE TITLE
[avistaz] Verification required (Config)

### ISSUE THREAD

**Issue by thegreyfox** [Jackett/Jackett#8739] opened 2020-05-22 06:07 UTC
### Environment

**OS**:  Gentoo/Linux

**.Net Runtime**: [Mono]

**.Net Version**: 5.20.1.19

**Jackett Version**: latest 

**Last Working Jackett Version**: v0.16.227

**Are you using a proxy or VPN?** [no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

Received an alert from sonarr indicating that the indexer for Avistasz is unable to connect. Logged into my jackett GUI and found that the indexer was missing. Attempted to add it back but received an error message: 

```
An error occurred while updating this indexer
Verification required
Click here to open an issue on GitHub for this indexer.
```

I am able to login to my profile under Avistaz.to and am positively sure that I have entered the correct credentials as well. 

### Logged Error Messages

2020-05-22 13:39:25 | Error | Jackett.Common.ExceptionWithConfigData: Verification required    at Jackett.Common.Indexers.Abstract.AvistazTracker.<>c__DisplayClass12_0.<ApplyConfiguration>b__0()    at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError)    at Jackett.Common.Indexers.Abstract.AvistazTracker.ApplyConfiguration(JToken configJson)    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config)    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext)
-- | -- | --

**Comment by garfield69** [comment] 2020-05-22 06:17
closing as duplicate of #8727

**Closed by garfield69** 2020-05-22 06:17 UTC
