### ISSUE TITLE
[Linkomanija] Configuration failed: Only http or https scheme is allowed

### ISSUE THREAD

**Issue by Giantdouche33** [Jackett/Jackett#1200] opened 2017-03-26 11:32 UTC
when adding speed.cd tracker i get the error Configuration failed: Only http or https scheme is allowed

[log.txt](https://github.com/Jackett/Jackett/files/870705/log.txt)

Jackett version:  Jackett Version 0.7.1176.0
Mono version:Mono JIT compiler version 4.8.0 (Stable 4.8.0.495/e4a3cf3 Wed Feb 22 18:30:58 UT
-------------------------------

**Comment by adamwinn** [comment] 2017-03-27 05:41
I saw this also with x264 trying to add the indexer using 127.0.0.1 and recaptcha.  Using the full cookie header method allowed me to add it without error tho.

I'm guessing it's because of this line in the log file.  Maybe a base url variable hasn't been specified?
```
Returning Redirect => file:///login.php
```

**Comment by Giantdouche33** [comment] 2017-03-27 07:31
how do you do the cookie method please?

**Comment by kaso17** [comment] 2017-03-28 18:27
I believe this might be a potential mono bug (mono httpclient not handling relative redirects correctly )

**Comment by kaso17** [comment] 2017-03-28 18:29
will have to look into this, but it shouldn't redirect you back to login.php anyway. check your login details too.

**Comment by Giantdouche33** [comment] 2017-03-30 13:32
checked login details and they are correct. same error.

**Comment by aka-charos** [comment] 2017-05-07 23:16
This issue is not tracker specific. I have the same issue with greek-team tracker with Jackett's latest version (0.7.1340.0) and Mono JIT compiler version 4.8.0

**Comment by jazzgott** [comment] 2017-06-05 19:04
Hi guys, 
v0.7.1469 here.

I can't use Linkomanija.net as well. Same issue - Configuration failed: Only http or https scheme is allowed.

Has anyone got a fix for this yet?

**Comment by flightlevel** [comment] 2017-06-08 08:41
I can add speed.cd perfectly

What Mono version, OS and CPU are people running with this issue?

**Comment by xtrmr** [comment] 2017-06-08 14:29
I'm having the same problem with Linkomanija.
It works fine on when running Windows 10, however doesn't work on Ubuntu 16.04.

I've tried running Jackett versions v0.7.1469 and v0.7.1477 - made no difference.
Tested with Mono versions 4.8.1 and 5.0.1.1, also made no difference.

Like someone mentioned before, logs look like it's not properly redirecting:
Jun 08, 2017 05:26:17 PM 	Error 	Exception in Configure
Jun 08, 2017 05:26:17 PM 	Debug 	IWebClient.GetBytes(Url:file:///index.php)
Jun 08, 2017 05:26:17 PM 	Debug 	IWebClient: Returning Redirect => file:///index.php 
Jun 08, 2017 05:26:16 PM 	Debug 	IWebClient.GetString(Url:https://www.linkomanija.net/takelogin.php)

**Comment by kaso17** [comment] 2017-06-08 18:48
please try to reconfigure and post the complete log.

**Comment by xtrmr** [comment] 2017-06-08 20:56
Here's the log:
[log.txt](https://github.com/Jackett/Jackett/files/1062392/log.txt)

**Comment by jazzgott** [comment] 2017-06-28 18:10
...any luck?

**Comment by Dhs92** [comment] 2017-07-21 06:22
Still receiving error. Is this on mono's end?

**Comment by flightlevel** [comment] 2017-07-23 01:52
This works perfectly for me, just tried it
@xtrmr Are you changing the url (Jun 08, 2017 05:26:16 PM Debug IWebClient.GetString(Url:https://www.linkomanija.net/takelogin.php))

@jazzgott @Dhs92 Please provide FULL log using `mono --debug JackettConsole.exe -t -l`

**Comment by Dhs92** [comment] 2017-07-23 02:07
@flightlevel I managed to fix the issue somehow, don't know how to recreate.

**Comment by flightlevel** [comment] 2017-07-23 02:08
Even better if its working!

**Comment by jazzgott** [comment] 2017-07-23 16:42
@Dhs92 How did you fix it, mate?

@flightlevel please find the log attached

[jackett.txt](https://github.com/Jackett/Jackett/files/1168212/jackett.txt)

**Comment by JMLT85** [comment] 2017-07-29 13:50
Have same thing with linkomanija. Can't login. Other trackers I've tried works with no problems.
Using ubuntu 14.04 trusty tahr on Kimsufi server.
Did someone found solution I'm bit new on Ubuntu, been setting everything with help of Google ;/

**Comment by Dhs92** [comment] 2017-07-30 19:24
@jazzgott Just remembered, I downgraded mono to the recommended version in the README. Might want to start there.

**Comment by flightlevel** [comment] 2017-08-05 01:49
@jazzgott 
That error is coming from linkomanija

Are you having a problem with Speed cd or or linkomanija ?

**Comment by JMLT85** [comment] 2017-08-05 08:12
I don't have account with speed cd.
Only problem with logging in with Linkomanija. 
Also some problems with Bit-HDTV I can login but cannot perform search, test fails as well.

**Comment by flightlevel** [comment] 2017-08-05 08:44
I can't reproduce this on Speed.cd using Mono and all recent reports and logs are from Linkomanija so am going to change to the title of this issue to focus on Linkomanija

`
07-23 17:37:28 Debug IWebClient.GetString(Url:https://www.linkomanija.net/takelogin.php) 
07-23 17:37:28 Debug IWebClient: Returning Redirect => file:///index.php  
07-23 17:37:28 Debug IWebClient.GetBytes(Url:file:///index.php) 
`

Clearly its going wrong on the redirect and looking at the file system instead

Am wondering if this is a Mono bug or more like the issue described here https://stackoverflow.com/questions/23438416/why-is-httpclient-baseaddress-not-working with a leading forward slash ????

Can someone please test Linkomanija and see if this happens on Windows as well?

**Comment by xtrmr** [comment] 2017-08-06 18:34
Hi, It works fine on Windows.
I've been using Windows 10 instead of Ubuntu.
I've tried Mono 4.8, 4.8.1 and 5.0.1.1 on Ubuntu - same error.

**Comment by jfeulner** [comment] 2017-08-27 06:51
Version 5.2 of Mono here, having issues.
On another Ubuntu box, it has verzion 4.6.2 installed.

**Comment by kaso17** [comment] 2017-08-28 09:03
It's definitely a mono bug.
Added a workaround for it via 7423e3f5bcdfc2d3c691641683579cc02473ad28
That should "fix" it.

**Comment by jazzgott** [comment] 2017-08-28 11:49
Forgive me a lame question - what do I do with it?

**Comment by kaso17** [comment] 2017-08-28 11:51
wait for the next pre release (later today) which will include the fix.

**Comment by jazzgott** [comment] 2017-08-28 11:52
Thank you!

**Comment by JMLT85** [comment] 2017-08-29 12:02
It works for LinkoManija with new update!
Just checked on Ubuntu 14.04 mono 5
Big thanks

**Closed** 2017-08-29 12:19 UTC
Labels: Needs Investigations, Provider

**Comment by megamorphf** [comment] 2018-02-15 10:22
Same issue for me. What can I add is that mono does not like "let's encrypt" certificates every single time I encountered issues were due to the fact the server on the other end was using LE certificates. 

I am currently running mono 5.8.0.108

**Comment by kaso17** [comment] 2018-02-16 18:39
@megamorphf please provide a full log, might be a new mono 5.8 bug
