### ISSUE TITLE
Manual search working, Sonarr not working for PrivateHD

### ISSUE THREAD

**Issue by terids** [Jackett/Jackett#13051] opened 2022-03-14 01:47 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-03-14 01:34:40	Info	Using HTTP Client: HttpWebClient2
2022-03-14 01:34:40	Info	Using FlareSolverr: No
2022-03-14 01:34:40	Info	Using proxy: Disabled
2022-03-14 01:34:40	Info	App config/log directory: C:\ProgramData\Jackett
2022-03-14 01:34:40	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-03-14 01:34:40	Info	Running in Docker: No
2022-03-14 01:34:40	Info	Jackett variant: CoreWindows
2022-03-14 01:34:40	Info	OS version: Microsoft Windows NT 10.0.17763.0 (64bit OS)
2022-03-14 01:34:40	Info	Environment version: 6.0.3 (C:\ProgramData\Jackett\)
2022-03-14 01:34:31	Info	Starting Jackett v0.20.703
```

### Description

If I search manually on PrivateHD or in Jackett, I get results back.

When searching through Sonarr, 0 results are returned for PrivateHD.

I have another tracker added, Nebulance, which does return results, so it is specific to PrivateHD.

I found the same issue in a closed ticket here [](https://github.com/Jackett/Jackett/issues/11991) however I have already got the categories added correctly. I tried to delete and re-add PrivateHD to no avail.

I have not had PrivateHD ever working through Jackett.

### Logged Error Messages

```text
2022-03-14 01:18:19	Info	
Torznab search in PrivateHD for Expanse S05 => Found 0 releases (from cache)
2022-03-14 01:18:19	Debug	
CACHE Search Hit / Indexer: privatehd / Found: 0 releases
2022-03-14 01:18:19	Debug	
CACHE Search / Indexer: privatehd / CacheHit: True / Query: {"QueryType":"tvsearch","Categories":[5000,5030,5040,5045,2000,2030,2040,2045],"Extended":1,"ApiKey":null,"Limit":100,"Offset":0,"RageID":null,"TvdbID":null,"ImdbID":null,"TmdbID":null,"Cache":true,"Season":5,"Episode":null,"SearchTerm":"Expanse","Album":null,"Artist":null,"Label":null,"Track":null,"Year":null,"Genre":null,"Author":null,"Title":null,"IsTest":false,"ImdbIDShort":null,"IsSearch":false,"IsTVSearch":true,"IsMovieSearch":false,"IsMusicSearch":false,"IsBookSearch":false,"IsTVRageSearch":false,"IsTvdbSearch":false,"IsImdbQuery":false,"IsTmdbQuery":false,"HasSpecifiedCategories":true,"SanitizedSearchTerm":"Expanse"}
```

**Comment by garfield69** [comment] 2022-03-14 02:35
The indexer with Sonarr works for me
![image](https://user-images.githubusercontent.com/6933240/158094686-c4ff818c-c054-4f4c-bdb5-4862f264585f.png)
which suggests the issue is at your end someplace.

When you say that you have `tried to delete and re-add PrivateHD to no avail.`,
are you taking about Jackett or Sonarr?

If you are deleting on Sonarr, then after deletion, shutdown and restart Sonarr, then define a new Sonarr indexer, which ensures you are not getting tricked by caching.
Shutdown is not closing the browser page, its right clicking on the Sonarr system tray task and selecting Exit.

**Comment by terids** [comment] 2022-03-14 10:22
So in Sonarr I have deleted PrivateHD tracker, restarted the service, and created PrivateHD again. Still no results returned.

PrivateHD does work with Radarr no problem.

**Comment by ilike2burnthing** [comment] 2022-03-14 12:02
Please provide an enhanced Jackett log of the issue (ensure cache is disabled) - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by terids** [comment] 2022-03-14 13:14
Here is the full log, it seems to start around line 350.

[log.txt](https://github.com/Jackett/Jackett/files/8245063/log.txt)

**Comment by terids** [comment] 2022-03-14 14:45
So I deleted from Jackett and Sonarr, stopped both services and restarted them, and added PrivateHD again to both. Still not working for me sadly :(

I added all the categories as the related ticket mentioned in the first post here (#11991) said that fixed it for them.

**Comment by terids** [comment] 2022-03-14 17:51
Ah this works actually, maybe this combined with a complete removal / add of the PrivateHD gave it a nudge. Thanks so much :)

**Comment by garfield69** [comment] 2022-03-14 17:54
\o/

**Closed by garfield69** 2022-03-14 17:54 UTC
