### ISSUE TITLE
Jackett fails to update with a (SOCKS5) proxy configured

### ISSUE THREAD

**Issue by n1nj4888** [Jackett/Jackett#2143] opened 2017-11-14 01:24 UTC
Jackett fails to update to new version with a proxy server configured (SOCKS5). The update is found as expected but the update fails to perform. Removing the configured (SOCKS5) proxy finds and performs the update as expected.

Saw this issue when upgrading to both the previous v0.8.396 (resolved by removing proxy) and the new v0.8.416... The error in the log is as follows...

-------------------------------
Jackett version:  v0.8.396
Mono version (if not using Windows):  Mono JIT compiler version 5.2.0.224 (tarball Tue Oct  3 19:49:47 UTC 2017) 
-------------------------------

Extract from Jackett log file:
------------------------------------------------------------------------------------------------------------------
2017-11-14 09:07:13.4949 Info New release found.  Current: v0.8.396 New: v0.8.416
...
2017-11-14 09:07:29.2237 Error Error performing update. ICSharpCode.SharpZipLib.SharpZipBaseException: Unexpected EOF
  at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Fill () [0x00031] in <8e8fa28d216a43ec8dcb2258d1f7bf00>:0 
  at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x0004f] in <8e8fa28d216a43ec8dcb2258d1f7bf00>:0 
  at ICSharpCode.SharpZipLib.GZip.GZipInputStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00012] in <8e8fa28d216a43ec8dcb2258d1f7bf00>:0 
  at ICSharpCode.SharpZipLib.Tar.TarBuffer.ReadRecord () [0x00025] in <8e8fa28d216a43ec8dcb2258d1f7bf00>:0 
  at ICSharpCode.SharpZipLib.Tar.TarBuffer.ReadBlock () [0x00021] in <8e8fa28d216a43ec8dcb2258d1f7bf00>:0 
  at ICSharpCode.SharpZipLib.Tar.TarInputStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x000c6] in <8e8fa28d216a43ec8dcb2258d1f7bf00>:0 
  at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractEntry (System.String destDir, ICSharpCode.SharpZipLib.Tar.TarEntry entry) [0x000df] in <8e8fa28d216a43ec8dcb2258d1f7bf00>:0 
  at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractContents (System.String destinationDirectory) [0x00023] in <8e8fa28d216a43ec8dcb2258d1f7bf00>:0 
  at Jackett.Services.UpdateService+<DownloadRelease>d__16.MoveNext () [0x00264] in <c8cf6dfd377e4bf7a3fd27158dffd98f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <77c9551943624fd18301ba6f78a841e5>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <77c9551943624fd18301ba6f78a841e5>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <77c9551943624fd18301ba6f78a841e5>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <77c9551943624fd18301ba6f78a841e5>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <77c9551943624fd18301ba6f78a841e5>:0 
  at Jackett.Services.UpdateService+<CheckForUpdates>d__12.MoveNext () [0x002ad] in <c8cf6dfd377e4bf7a3fd27158dffd98f>:0 

-------------------------------

**Comment by kaso17** [comment] 2017-11-15 17:47
@sv01a can you help with this?

**Comment by sv01a** [comment] 2017-11-15 18:03
Same issue with another proxy types? And what OS do you use?

**Comment by n1nj4888** [comment] 2017-11-16 09:45
I’m running linuxserver.io/jackett in Docker. 

Just tried update to 0.8.423 with a HTTP proxy and this works as expected so will wait for a new release and try again with SOCKS5 Proxy...

**Comment by sv01a** [comment] 2017-11-16 14:26
Seems that jackett can't extract downloaded update. Can you try to find update file(JackettUpdate-*)?

**Comment by kaso17** [comment] 2017-11-16 15:05
I can reproduce this using putty/SSH as a proxy server. Neither SOCKS 4 or 5 works at all (no updates, no indexers, ...)

**Comment by sv01a** [comment] 2017-11-16 15:37
Do you have absolutely same error?

I can't repeat issue because have't well configured socks proxy. I debug with free socks but seems it drops binary download. 

But in issue seems that jackett can't extract downloaded archive.

Indexers also tested with free proxies(all types) and all works fine.

**Comment by kaso17** [comment] 2017-11-16 17:07
race condition is fixed via 968a7729c302f8de7fe476fa4c87d0af5c139e2f
still needs some work (changing proxy settings now requires a restart of the jackett process, httpwebclient2 was already affected by this, not sure about libcurl.
@n1nj4888

**Comment by n1nj4888** [comment] 2017-11-17 02:58
Tried again to update 423 to 434 but think there was a general issue with my SOCKS5 proxy since couldn’t access any indexers either. Manually removed proxy and it updated fine to 434 and indexers now working with SOCKS5 proxy so guess I’ll have to wait to test a further update with the proxy configured unless there is a way of forcing an update back and then forward again?

**Comment by evilvibes** [comment] 2017-11-17 05:23
Also was having this issue the update seems to fix it.

**Comment by kaso17** [comment] 2017-11-17 13:53
@n1nj4888 does your proxy work with other applications (e.g. firefox?)

**Comment by kaso17** [comment] 2017-11-17 15:54
v0.8.436 now supports proxy reconfiguration without restarting jackett (httpwebclient/httpwebclient2, legacy libcurl untested)

**Comment by n1nj4888** [comment] 2017-11-17 21:27
Just upgraded 0.8.434 -> 0.8.436 with a working SOCKS5 proxy and the upgrade went through successfully! Thanks guys!

**Closed** 2017-11-19 06:26 UTC
