### ISSUE TITLE
HDTorrent.it

### ISSUE THREAD

**Issue by bubez81** [Jackett/Jackett#2655] opened 2018-03-01 09:32 UTC
Hello, no results when i search on hdtorrent.it

`
Mar 01, 2018 10:31:11 AM | Error | CardigannIndexer (hdtorrentsit): Error while parsing row '<tr> <td align="center" style="padding: 0px"> 		<a href="browse.php?cat=4"> 			<img border="0" src="./pic//cats/HDDVDBD720Rip.gif" alt="BDRip 720p">			 		</a> 	</td> <td align="left" onmousemove="dialog_tor('img_tor',Xmouse,Ymouse,'http://s26.postimg.org/43x6cph55/2_V1_T2_42_T.jpg')" onmouseout="dialog_torc('img_tor')"> 		<a href="details.php?id=8976"> 			<b>SUITS (2014) Stagione 4 / Episodio 06</b> 		</a>  <a href="download.php?id=8976&amp;name=Suits.S04E06.Al%20diavolo.DLMux.720p.H264.mkv.torrent"> 			<img src="pic/download.gif" border="0" alt="Scaricare" title="Scaricare">			 		</a> <br> 		 		<i>2015-06-19 19:24:48</i> 	</td> <td align="center">1.40<br>		GB</td> </tr>':  System.Exception: Error while parsing field=seeders, selector=td:nth-child(4), value=<null>: Selector "td:nth-child(4)" didn't match <tr> <td align="center" style="padding: 0px"> 		<a href="browse.php?cat=4"> 			<img border="0" src="./pic//cats/HDDVDBD720Rip.gif" alt="BDRip 720p">			 		</a> 	</td> <td align="left" onmousemove="dialog_tor('img_tor',Xmouse,Ymouse,'http://s26.postimg.org/43x6cph55/2_V1_T2_42_T.jpg')" onmouseout="dialog_torc('img_tor')"> 		<a href="details.php?id=8976"> 			<b>SUITS (2014) Stagione 4 / Episodio 06</b> 		</a>  <a href="download.php?id=8976&amp;name=Suits.S04E06.Al%20diavolo.DLMux.720p.H264.mkv.torrent"> 			<img src="pic/download.gif" border="0" alt="Scaricare" title="Scaricare">			 		</a> <br> 		 		<i>2015-06-19 19:24:48</i> 	</td> <td align="center">1.40<br>		GB</td> </tr>   at Jackett.Indexers.CardigannIndexer+<PerformQuery>d__28.MoveNext () [0x015c8] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:1409
-- | -- | --
`

**Comment by kaso17** [comment] 2018-03-01 11:08
@EffeF can you have a look at this?

**Comment by EffeF** [comment] 2018-03-02 13:10
Everything works correctly for me... manual search, Sonarr and Radarr.

Could it have been a temporary error caused by the tracker?

**Comment by bubez81** [comment] 2018-03-13 08:28
sadly hdtorrent at the moment is down ;(

**Comment by garfield69** [comment] 2018-04-05 20:30
24 days and site is still broken, returning 
![image](https://user-images.githubusercontent.com/6933240/38390122-7a06d936-3974-11e8-8c50-9f06031a8d5d.png)
wait or delete indexer?

**Comment by EffeF** [comment] 2018-04-05 20:42
@garfield69, the site is online and functioning correctly at the moment.

Where are you visiting it from? It works only from Italy, for this you see the error 404.

**Comment by garfield69** [comment] 2018-04-05 20:47
@EffeF  Oh, good to know.
@bubez81 are you still getting the row parsing error?
If we don't get a reply soon we will close this ticket.

**Closed** 2018-08-30 06:00 UTC
