### ISSUE TITLE
Update to 11.356 Failed.

### ISSUE THREAD

**Issue by neuman1812** [Jackett/Jackett#5308] opened 2019-05-21 20:21 UTC
hastebin link contains terminal output from log and Update.log during upgrade. Jacket not starting after attempting to update to pre-release.

https://hastebin.com/ecefanitop.sql
Running Raspberry Pi, Debian stretch

**Comment by flightlevel** [comment] 2019-05-22 10:08
Duplicate of #5208

**Closed by flightlevel** 2019-05-22 10:08 UTC

**Comment by garfield69** [comment] 2019-10-30 02:28
fix is available with stable jackett 0.12.898. but you will need to install manually and run the systemd install script anew.

1. open a terminal and shutdown the jackett service using `systemctl stop jackett.service`
2. download and extract the linux package that applies to your platform from https://github.com/Jackett/Jackett/releases/tag/v0.12.898
3. copy or move/replace all the files from the Jackett folder in the downloaded/extracted package to where ever you have previously put the jackett binaries. Typical locations are `/opt/Jackett` or `~/Jackett`
4. cd to your Jackett binary folder and install the service with `sudo ./install_service_systemd.sh` 
this will start the service (if it ran successfully)
5. access your jackett dashboard with your browser and untick the Disable auto Update check box and press the Apply Server Settings button.

**Comment by neuman1812** [comment] 2019-11-01 18:12
installed 12.898 and autoupdated to 12.907  working great.  Thank you!
