### ISSUE TITLE
[kickasstorrent] Exception (kickasstorrent): Could not load file or assembly 'AutoMapper, Version=6.2.2.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040): Could not load file or assembly 'AutoMapper, Version=6.2.2.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) (Test)

### ISSUE THREAD

**Issue by Gurt89** [Jackett/Jackett#3508] opened 2018-08-01 23:03 UTC
[jackett_error.txt](https://github.com/Jackett/Jackett/files/2251399/jackett_error.txt)

Jackett Version 0.8.1162.0

Windows Server 2016 Standard

**Comment by Gurt89** [comment] 2018-08-01 23:07
Ah, also: 

Error checking for updates.
--

**Comment by flightlevel** [comment] 2018-08-02 10:55
Duplicate of #3383 

To resolve this issue

- Stop the Jackett service
- Close the Jackett tray
- Kill every Jackett process in task manager
- From Windows Add/Remove programs Uninstall Jackett (you won't lose your trackers)
- Go to `C:\ProgramData\Jackett` and make sure there is no exe or dll files present, only config and log files should remain after uninstalling
- Download the latest Jackett release and install via the Windows installer

**Closed by flightlevel** 2018-08-02 10:55 UTC
