### ISSUE TITLE
[REQ] New Indexer - Loucos-Share

### ISSUE THREAD

**Issue by tnascif** [Jackett/Jackett#4646] opened 2019-02-11 17:45 UTC
Tracker Name : Loucos-Share
Type : Movie, TV, Music, Anime, Games, Software, Other
Private Tracker (open sign-up until 02/15/2019).
Indexer URL : http://www.loucos-share.org/
Indexer language : Portuguese (Brazil)

**Comment by garfield69** [comment] 2019-02-11 18:24
duplicate of #4640

**Closed by garfield69** 2019-02-11 18:24 UTC
