### ISSUE TITLE
[req]: BT之家

### ISSUE THREAD

**Issue by lainiaobb** [Jackett/Jackett#15776] opened 2024-12-24 14:47 UTC
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: BT之家
- URL: https://www.1lou.info
- Description: Movie  TV series
```

**Comment by garfield69** [comment] 2024-12-24 18:40
duplicate of #15708, same site alternate domain

**Closed by garfield69** 2024-12-24 18:40 UTC
