### ISSUE TITLE
[Request] Private tracker - SceneHD

### ISSUE THREAD

**Issue by topdollar3** [Jackett/Jackett#1891] opened 2017-09-24 09:33 UTC
Requesting support for Private Tracker SceneHD

Tracker Name: SceneHD
Tracker Content: HD Movies
Tracker URL : https://scenehd.org
Tracker Language : English

Thank you

**Comment by garfield69** [comment] 2017-09-24 23:26
This should be closed as a duplicate of #3

**Closed** 2017-10-03 12:52 UTC

**Comment by kaso17** [comment] 2018-11-09 15:30
fixed via 10473c6bd306fa098a2fe1ab57a1ebd8268019a7
