### ISSUE TITLE
[cinemaz] [avistaz](testing) Exception (cinemaz): Invalid status code 503 (ServiceUnavailable) received from indexer: Invalid status code 503 (ServiceUnavailable) received from indexer

### ISSUE THREAD

**Issue by ericvlog** [Jackett/Jackett#15739] opened 2024-12-01 04:03 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
docker compose jackett,
```

### Description

avistaz & cinemaz can manual browse but testing in jackett fail.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (cinemaz): Invalid status code 503 (ServiceUnavailable) received from indexer: Invalid status code 503 (ServiceUnavailable) received from indexer
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

![image](https://github.com/user-attachments/assets/885e79ed-efa1-473c-a0ce-8369bd0d02a5)

manual browse no problem
![image](https://github.com/user-attachments/assets/8ecf0029-69aa-4660-be15-94ec78417f5f)

**Comment by garfield69** [comment] 2024-12-01 04:13
On the Avistaz forum is a post that states that:  API is down temporarily for maintenance. Thanks for your patience!
This will likely also apply to other family sites, CinemaZ, PrivateHD, ExoticaZ etc

**Comment by ericvlog** [comment] 2024-12-01 04:29
> On the Avistaz forum is a post that states that: API is down temporarily for maintenance. Thanks for your patience! This will likely also apply to other family sites, CinemaZ, PrivateHD, ExoticaZ etc

wow, thanks for let us know !! appreciate your work!!

**Comment by garfield69** [comment] 2024-12-01 05:30
closing as a duplicate of #13817

**Closed by garfield69** 2024-12-01 05:30 UTC
Labels: Confirmed, Down / Waiting for removal

**Comment by garfield69** [comment] 2024-12-01 06:23
online

**Comment by ericvlog** [comment] 2024-12-01 08:09
> online

Tq so much!!
