### ISSUE TITLE
no indexers seem to work when proxies are enabled in versions > 0.11

### ISSUE THREAD

**Issue by Ashkaan** [Jackett/Jackett#4862] opened 2019-03-11 15:38 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

RARBG fails the index test.

**Jackett version**:  0.11.8.0
**Mono version** (if not using Windows):  Whatever comes in Docker

-------------------------------

**Comment by putneyj** [comment] 2019-03-11 16:41
I'm seeing this as well, all of my indexers are failing all of a sudden. Using latest Docker release.

**Comment by putneyj** [comment] 2019-03-11 16:55
Turns out PIA's SOCKS5 proxy seems to be refusing connections

**Comment by snusy123** [comment] 2019-03-11 17:12
Anybody got a fix?

**Comment by Ashkaan** [comment] 2019-03-11 18:17
I don't think this has to do with proxies because I don't use a proxy.

**Comment by garfield69** [comment] 2019-03-11 18:24
the jackett rarbg indexer uses the rarbg api at https://torrentapi.org/pubapi_v2.php which on my win10 was  returning ERR_CONNECTION_REFUSED
I solved it by opening a cmd terminal and using the ipconfig /flushdns command

I dont know what the equivalent is on linux or even if it applies to docker images... @flightlevel  or @kaso17  can you assist please? thanks.

**Comment by n1nj4888** [comment] 2019-03-12 02:15
I'm seeing the same issue on Jackett (Docker on Synology) with ALL indexers... The error for RARBG is as follows but all indexers show the same type of error...

Jackett.Common.IndexerException: Exception (rarbg): Connection refused ---> System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 465
   at Jackett.Common.Indexers.Rarbg.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Rarbg.cs:line 191
   at Jackett.Common.Indexers.Rarbg.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Rarbg.cs:line 142
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

The error seems to be when using a proxy (I'm using a socks5 proxy)... If I disable the proxy settings temporarily, the indexers all test successfully...

**Comment by Ton-O** [comment] 2019-03-13 18:53
Problem for me was solved by restarting Docker Host, removing container and recreate with new image. Dropped indexer in Jackett and recreated, now working fine.

**Comment by Ashkaan** [comment] 2019-03-13 21:41
@Ton-O, me too!  Thank you!

**Comment by mRaRn** [comment] 2019-03-15 00:21
This is happening to me too on Docker/Synology. Sometimes 1 tracker works but the rest fail, sometimes they all fail instantly. I have tried deleting the container and recreating, stopping docker completely and restarting, upgraded the docker spk and none of these have fixed the issue. Running on 0.11.46.0. I'm also using PIA SOCKS5. Removing the SOCKS5 url fixed the issue but this is not an acceptable fix.

**Comment by d2dyno** [comment] 2019-03-15 04:12
I am having issues with both Nord and PIA proxies. Tried multiple servers/countries for each. Without fail, 1 test would work after changing servers, then any subsequent tests immediately get connection refused. Sadly disabling proxy until this is resolved.

**Comment by Ton-O** [comment] 2019-03-15 08:06
For your info: I'm NOT using proxies on the jacket-connection (only on the transmission-connection later in the chain).

**Comment by n1nj4888** [comment] 2019-03-15 11:16
Agree with @mRaRn that removing the proxy fixes the issue so our particular issue appears to be with the SOCKS5 Proxy... for the time being, I rolled my jackett image back to “linuxserver/jackett:amd64-v0.10.861-ls10” and it works with the socks5 proxy again...

Keen to hear from the jackett devs on whether this will be fixed in a future release before I test future updates!

**Comment by mRaRn** [comment] 2019-03-15 12:25
Created a new container as @n1nj4888 said with “linuxserver/jackett:amd64-v0.10.861-ls10” and it worked correctly.

**Comment by daddyboo** [comment] 2019-03-16 01:13
I have the same problem with socks5 proxy, so there is definitely a bug.

**Comment by n1nj4888** [comment] 2019-03-16 04:04
Not sure which release introducted this proxy bug but it must have been one between v0.10.861 and v0.11.8. 

Hopefully the devs can take a look and fix this issue since I won’t be able to upgrade to the latest jackett until this is fixed as don’t want to remove my proxies.

**Comment by marmot74** [comment] 2019-03-16 17:18
Same issue here. Using Sock5 and Connection Refused on all indexers.

**Comment by n1nj4888** [comment] 2019-03-17 00:10
Hi @sv01a - Are you able to take a look at this issue given I recall you developed the initial proxy support in Jackett?

**Comment by flightlevel** [comment] 2019-03-17 09:09
Can someone with SOCKS issue please try v0.11.1 and see if that works? Confirming its impacting every indexer and not just some?

**Comment by n1nj4888** [comment] 2019-03-17 10:42
Hi @flightlevel. I spun up a new container "linuxserver/jackett:amd64-v0.11.1-ls13 and Jackett GUI shows v0.11.1. When hitting the "Test All" icon, all Indexers (5 configured), fail almost immediately... All with the same form of error:

Jackett.Common.IndexerException: Exception (rarbg): Connection refused ---> System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 465
   at Jackett.Common.Indexers.Rarbg.CheckToken() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Rarbg.cs:line 120
   at Jackett.Common.Indexers.Rarbg.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Rarbg.cs:line 148
   at Jackett.Common.Indexers.Rarbg.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Rarbg.cs:line 142
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

**Comment by sv01a** [comment] 2019-03-17 12:21
@n1nj4888 I'll take a look. are you sure that your proxy are alive?

**Comment by n1nj4888** [comment] 2019-03-17 12:50
Thanks guys! The proxy settings work on 0.10.861, just not on 0.11.1 or above...

**Comment by PoshSparks** [comment] 2019-03-17 14:34
Shew,
  So, I'm not the only experiencing this?
Currently running Jackett Version 0.11.58.0 (docker version)
All indexers fail with the PIA socks5 proxy enabled... "Connection Refused" (fails immediately, no delay)

I can confirm the socks5 proxy is up and working without issue on all other applications... 

Jackett.Common.IndexerException: Exception (1337x): Connection refused ---> System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudFlareUtilities.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClientNetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs:line 214
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1229
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

**Comment by n1nj4888** [comment] 2019-03-20 10:35
Hi @sv01a, did you manage to take a look and figure out the issue with the socks proxy?

**Comment by jspoonamore** [comment] 2019-03-24 04:40
I just update to 0.11.115.0 today.  I started having this problem.  If I disable proxy, it works just fine.  I hope the Jackett Team fixes this soon.  I want proxy to work.

**Comment by n1nj4888** [comment] 2019-03-24 09:43
@sv01a was going to look into this as they were involved in the initial implementation of the proxies on Jackett. Not sure if they managed to take a look?

Also - I think we should rename this issue / create a new one that is clearer that the issue is that no indexers seem to work when proxies are enabled in versions > 0.11

**Comment by n1nj4888** [comment] 2019-03-31 08:35
Hi @sv01a - Any update on this please? Actually both this and #2602. @Flightlevel indicates that if no-one will support proxy in jackett it maybe removed.

I’m sure there’s a number of us that would like to prevent that happening!

**Comment by n1nj4888** [comment] 2019-04-08 21:15
Hi @sv01a, Any progress with this? I don’t mind testing out some builds if this helps?

**Comment by kjbweb** [comment] 2019-04-11 11:31
Don't mind helping test either, rolled back to latest 10.x release in the mean time.

**Comment by PrisonMike2** [comment] 2019-04-15 04:37
For anyone else wondering i am using HTTP proxy and all my indexers work fine. They fail when I shut off my Privoxy container though. Not sure if this is fixed or not yet.

**Comment by sv01a** [comment] 2019-04-16 12:25
try to switch jackett client in command line by passing `-c httpclient2` parameter

**Comment by n1nj4888** [comment] 2019-04-18 12:22
Hi sv01a. I will try and test over the next few days but some questions I have:

(A) What version of Jackett should be used?
(B) What proxy type should be used? If I use socks5 currently, so I have to change to another type?
(C) Does the “http” proxy type support https? If not assume it’s not a secure type and shouldn’t be used?

**Comment by sv01a** [comment] 2019-04-18 13:27
Hi @n1nj4888.
 a) latest
 b) nope. try it with current socks5
 c) have to, but i didn't test it

**Comment by n1nj4888** [comment] 2019-04-19 06:04
@sv01a - Here's what I did:

(1) Updated Jackett docker (linuxserver/jackett) to latest version (v0.11.230.0)
(2) Added "RUN_OPTS" environment variable in jackettdocker configuration and set the value to "-c httpclient2"
(3) Started Jackett docker and checked logs - Jackett refuses to start since "Client overide" is a deprecated runtime option - The following two log entries are repeated constantly and jackett does not start.

```
04-19 14:02:26 Info Starting Jackett v0.11.230.0
04-19 14:02:26 Error Client override ( httpclient2) has been deprecated, please remove it from your start arguments
```

Thanks!

**Comment by garfield69** [comment] 2019-04-19 06:13
check your run_opts again, it looks from the error message that  you may have added an extra space between the `-c` and `httpclient2`, there should be only one blank between the two keys ?

**Comment by n1nj4888** [comment] 2019-04-19 06:33
Double checked and the environment variable "RUN_OPTS" is set as: `-c httpclient2` - Only a single space between `-c` and `httpclient2`.

The following error does seem to indicate an extra space before `httpclient2 `but the variable is set correctly:

`Error Client override ( httpclient2) has been deprecated, please remove it from your start arguments`

**Comment by daddyboo** [comment] 2019-04-20 14:11
I can confirm that there is no problem with `socks5` proxy if I start Jackett client with`httpclient2` option.
```
-------------------------------------
          _         ()

         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/
         
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1004
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
04-20 16:48:11 Info Starting Jackett v0.11.232.0 
04-20 16:48:14 Info Environment version: 4.0.30319.42000 (/app/Jackett/) 
04-20 16:48:14 Info OS version: Unix 4.15.0.47 (64bit OS) (64bit process) 
04-20 16:48:14 Info Jackett variant: CoreLinuxAmdx64 
04-20 16:48:14 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
04-20 16:48:14 Info App config/log directory: /config/Jackett 
04-20 16:48:14 Info issue: Ubuntu 18.04.2 LTS \n \l 
04-20 16:48:14 Info Using HTTP Client: HttpWebClient2 
04-20 16:48:15 Info Loading Cardigann definitions from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions 
....
```

**Comment by garfield69** [comment] 2019-04-20 21:57
@daddyboo  on behalf of other docker users that want to use this, could you tell us how you passed the httpclient2 run time parm to start jackett with this method? thanks.

**Comment by daddyboo** [comment] 2019-04-20 22:10
I use Portainer (https://www.portainer.io) to work with my docker containers. I did a couple of experiments and find out that it works if I pass parameter without any spaces. Here is a screenshot https://imgur.com/GlEni4S

**Comment by garfield69** [comment] 2019-04-20 22:24
@n1nj4888  so have you tried using `-chttpclient2` ?

**Comment by d2dyno** [comment] 2019-04-20 22:47
On unRAID, I put this in 'extra parameters':
`-e RUN_OPTS="-chttpclient2"`

**Comment by n1nj4888** [comment] 2019-04-21 03:02
Ok so I’ve changed the docker RUN_OPTS environment variable to simply -chttpclient2 (no spaces) and Jackett now runs and indicates it is using the different HTTP client. 

Running a “Test all” on the indexers passes on every single indexer now. I also tried changing the configured proxy port to something I know to be wrong and it then failed all the index tests (as expected)... So it would appear that this fix fixes proxy settings in the newer versions of Jackett !!!

I think there are two outstanding questions:

(A) If httpclient2 works and the standard one doesn’t, wouldn’t it make sense to make httpclient2 the default client for any configured proxies (so that the user doesn’t need to pass additional env variables?

(B) Passing the docker env “-chttpclient2” works so there is presumably a bug in the parsing of this so that is is passed to the jackett executable as “-c httpclient2” (with space)

Thanks for all your help with this!

**Comment by jsheradin** [comment] 2019-04-21 03:25
Adding 

    -e RUN_OPTS="-chttpclient2"

to the docker run command fixes the issue on my setup.

Thanks!

**Comment by flightlevel** [comment] 2019-04-23 12:15
Can someone using SOCKS please try using `--UseClient=httpclient` instead and see if that works as well?
Also, can someone test the 'TorrentHeaven' indexer and see if it works with SOCKS, not sure if certificate override will work or not? @garfield69 @kaso17 Can you think of any indexers were the certificate hash is needed due to incomplete CA chain. I think we've had a few in the past eg. ilcorsaro but looks some of them could have it removed now
@kaso17 Any idea why httpclient2 was never the default and we stuck with httpclient?

**Comment by n1nj4888** [comment] 2019-04-23 13:27
Hi @flightlevel,

Using SOCKS5 on v0.11.230.0, changed docker RUN_OPTS to “--UseClient=httpclient“.

Jacket docker starts and I’m able to login to the Web GUI... However, running the “Test All” results in the same errors to the jackett log:

System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at ...

Also tried adding “TorrentHeaven” as a new indexer but it fails to add with the following notification error (to the GUI):

“Request to Jackett server failed.”


And the corresponding jackett log error:

System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudFlareUtilities.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient.cs:line 223
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445
   at Jackett.Common.Indexers.TorrentHeaven.GetConfigurationForSetup() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/TorrentHeaven.cs:line 103
   at Jackett.Server.Controllers.IndexerApiController.Config() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

**Comment by garfield69** [comment] 2019-04-23 19:52
@flightlevel  indexers with certificates: shokweb, trancetraffic, frozenlayer, takeabyte, ilcorsaroblu, nyaasi, ilcorsaronero, nnm-club.

**Comment by garfield69** [comment] 2019-04-23 19:56
@flightlevel  oops, forgot c#. psytorrents, scenehd, elitetracker, torrentheaven.

**Comment by keerio** [comment] 2019-04-26 12:24
Adding 
- RUN_OPTS=-chttpclient2

```
version: "3"
  jackett:
    container_name: jackett
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TIMEZONE}
    - RUN_OPTS=-chttpclient2
```

to the docker-compose worked for me

**Comment by flightlevel** [comment] 2019-04-27 11:20
Can someone using httpclient2 and SOCKS test ilcorsaronero and see if that works

**Comment by flightlevel** [comment] 2019-04-28 02:37
Can someone also try the latest release and use `--UseClient=httpclient2netcore` as your RUN_OPTS

**Comment by jsheradin** [comment] 2019-04-28 04:22
@flightlevel 

All indexer tests pass with `--UseClient=httpclient2netcore`. 

ilcorsaronero passes on both httpclient2 and httpclient2netcore.

**Comment by keerio** [comment] 2019-04-29 07:54
@flightlevel 
--UseClient=httpclient2netcore as your RUN_OPTS
Does not work for my environment or I just can not figure out how to wrap it for docker-compose.
`- RUN_OPTS=-chttpclient2`
this option still works fine

**Comment by garfield69** [comment] 2019-04-29 07:57
@keerio  `- RUN_OPTS=-chttpclient2netcore` with jackett v0.11.256 or newer

**Comment by keerio** [comment] 2019-04-29 08:00
@garfield69 
this works fine.

**Comment by d2dyno** [comment] 2019-04-29 09:30
-e RUN_OPTS="-chttpclient2netcore" also works for me

**Comment by flightlevel** [comment] 2019-04-29 10:39
The latest pre-release has httpclient2netcore as the default client. If no regressions are found in the next few days, it will go to general release

**Comment by mRaRn** [comment] 2019-04-29 10:56
-chttpclient2netcore = good for me on 0.11.256.0 with Synology/Docker.
-chttpclient2 = also fine.
Will run overnight and see how it goes. 
Good work @flightlevel

**Comment by n1nj4888** [comment] 2019-05-01 02:37
Great work @flightlevel, @garfield69 and all others involved for sorting this!

**Comment by flightlevel** [comment] 2019-05-01 10:13
Good to hear, you can all remove your RUN_OPTS now

**Closed by flightlevel** 2019-05-01 10:13 UTC

**Comment by n1nj4888** [comment] 2019-05-02 01:58
Hi @flightlevel - Presumably the red Proxy warning text will be removed from the GUI in a future release if there are no further major issues reported with the proxy functionality?

**Comment by flightlevel** [comment] 2019-05-04 05:58
Dashboard message now updated
Still have concerns with regards to leaks https://github.com/Jackett/Jackett/issues/4626 , if someone here could test that it would be great as I assume most people are using SOCKS for privacy reasons

**Comment by taschmidt** [comment] 2019-05-23 17:12
Question: I'm getting this same error using a socks5 proxy when running as a Windows service. Is there a fix for that?
