### ISSUE TITLE
[passthepopcorn] Exception (passthepopcorn): Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.: Parse error (Test)

### ISSUE THREAD

**Issue by rourke** [Jackett/Jackett#9223] opened 2020-07-24 13:11 UTC
I checked the (closed) issues and only found #8706, but that one got closed because OP didn't provide enough information.

### Environment

**OS**: Ubuntu Server 20.04 but running the linuxserver docker container.

**.Net Runtime**: I don't know. It's all provided through the container.

**.Net Version**: I don't know. It's all provided through the container.

**Jackett Version**: 0.16.896.0

**Last Working Jackett Version**: Not sure. It could be 1 or 2 versions ago.

**Are you using a proxy or VPN?** No

### Description

Whenever I send a request to PTP it fails with the error `Exception (passthepopcorn): Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.: Parse error`.

### Logged Error Messages

```
2020-07-24T12:58:45.480815733Z
2020-07-24T12:58:45.480823033Z -------------------------------------
2020-07-24T12:58:45.480827003Z           _         ()
2020-07-24T12:58:45.480830693Z          | |  ___   _    __
2020-07-24T12:58:45.480834203Z          | | / __| | |  /  \
2020-07-24T12:58:45.480837913Z          | | \__ \ | | | () |
2020-07-24T12:58:45.480841763Z          |_| |___/ |_|  \__/
2020-07-24T12:58:45.480850673Z
2020-07-24T12:58:45.480854053Z
2020-07-24T12:58:45.480857413Z Brought to you by linuxserver.io
2020-07-24T12:58:45.480860953Z -------------------------------------
2020-07-24T12:58:45.480864463Z
2020-07-24T12:58:45.480867763Z To support LSIO projects visit:
2020-07-24T12:58:45.480881483Z https://www.linuxserver.io/donate/
2020-07-24T12:58:45.480885313Z -------------------------------------
2020-07-24T12:58:45.480888833Z GID/UID
2020-07-24T12:58:45.480892233Z -------------------------------------
2020-07-24T12:58:45.483571675Z
2020-07-24T12:58:45.483586355Z User uid:    1000
2020-07-24T12:58:45.483590905Z User gid:    1000
2020-07-24T12:58:45.483595425Z -------------------------------------
2020-07-24T12:58:45.483598975Z
2020-07-24T12:58:45.486208045Z [cont-init.d] 10-adduser: exited 0.
2020-07-24T12:58:45.486671189Z [cont-init.d] 30-config: executing...
2020-07-24T12:58:45.496028333Z [cont-init.d] 30-config: exited 0.
2020-07-24T12:58:45.496630748Z [cont-init.d] 99-custom-scripts: executing...
2020-07-24T12:58:45.501630748Z [custom-init] no custom files found exiting...
2020-07-24T12:58:45.502142741Z [cont-init.d] 99-custom-scripts: exited 0.
2020-07-24T12:58:45.502711386Z [cont-init.d] done.
2020-07-24T12:58:45.503440472Z [services.d] starting services
2020-07-24T12:58:45.507959388Z [services.d] done.
2020-07-24T12:58:45.759873686Z 07-24 12:58:45 Info Starting Jackett v0.16.896.0
2020-07-24T12:58:46.167996584Z 07-24 12:58:46 Info Environment version: 3.1.6 (/app/Jackett/)
2020-07-24T12:58:46.168048345Z 07-24 12:58:46 Info OS version: Unix 5.4.0.40 (64bit OS) (64bit process)
2020-07-24T12:58:46.168112935Z 07-24 12:58:46 Info Jackett variant: CoreLinuxAmdx64
2020-07-24T12:58:46.168191616Z 07-24 12:58:46 Info File /etc/issue: Ubuntu 18.04.4 LTS \n \l
2020-07-24T12:58:46.168272346Z 07-24 12:58:46 Info Running in Docker: Yes
2020-07-24T12:58:46.168333637Z 07-24 12:58:46 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2020-07-24T12:58:46.168398267Z 07-24 12:58:46 Info App config/log directory: /config/Jackett
2020-07-24T12:58:46.168462988Z 07-24 12:58:46 Info Using Proxy: No
2020-07-24T12:58:46.171834605Z 07-24 12:58:46 Info Using HTTP Client: HttpWebClient2NetCore
2020-07-24T12:58:46.307851924Z 07-24 12:58:46 Info Loading Cardigann definitions from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
2020-07-24T12:58:47.658587100Z 07-24 12:58:47 Info Cardigann definitions loaded: abnormal, alpharatio, anidex, anidub, animebytes, animetorrents, anthelion, avistaz, awesomehd, bakabt, bb, bitcityreloaded, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, corsarored, danishbits, dicmusic, digitalcore, digitalhive, divxtotal, elitetracker, epublibre, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdonly, hdspace, hdtorrents, hebits, horriblesubs, icetorrent, immortalseed, internetarchive, iptorrents, lostfilm, mejortorrent, milkie, morethantv, myamity, myanonamouse, ncore, nebulance, newpct, newrealworld, norbits, nordicbits, notwhatcd, orpheus, partis, passthepopcorn, pier720, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, psytorrents, rarbg, redacted, revolutiontt, rutracker, scenefz, scenehd, scenetime, secretcinema, shazbat, showrss, solidtorrents, speedcd, superbits, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentleech, torrentnetwork, torrentscsv, torrentseeds, torrentsyndikat, tvstore, tvvault, xspeeds, xthor, xtremezone, yts, animetosho, unlimitz, uniondht, ibit, theoccult, nyaasi, nbtorrents, muziekfabriek, noname-club, xxxtorrents, netlab, pornorip, gay-torrentsorg, thehorrorcharnel, booktracker, rapidzona, onlyscene, hon3yhd, academictorrents, documentarytorrents, casstudiotv, bteye, majomparade, vhstapes, arabp2p, darktracker, ehentai, xwtclassics, greekteam, concertos, erzsebet, empornium, chdbits, sporthd, extremlymtorrents, newstudiol, legittorrents, yingk, fantasticheaven, haidan, classix, trezzor, eniahd, piratbitl, linkomanija, 0daykiev, hdturk, 3dtorrents, torrent-pirat, aniRena, btdb, bwtorrents, torrentccf, teamos, aftershock, sukebeinyaasi, hdcity, leporno, lastfiles, dragonworldreloaded, toros, torrentdownloads, crnaberza, totheglory, rustorka, vizuk, seedfile, tapochek, acgrip, esharenet, shareuniversity, ztracker, parnuxi, hamsterstudio, mvgroupforum, torrentslocal, gktorrent, yourbittorrent, shareisland, tenyardtracker, galeriens, itorrent, torrent-explosiv, xwtorrents, newretro, filmsclub, liaorencili, torrentview, cinemamovies, gfxpeers, immortuos, bitru, thegeeks, peersfm, datascene, pornbay, ptmsg, ccfbits, riperam, sexypics, backups, p2pelite, xiteme, nyaa-pantsu, u2, broadcity, kapaki, metaltracker, bigtorrent, film-paleis, hdc, darmowetorenty, pornforall, theplace, tribalmixes, rainbowtracker, theaudioscene, torrentseed, ilcorsaroblu, 3changtrai, turknova, dmhy, ebooks-shares, iv-torrents, pterclub, rutor, hdolimpo, cinematik, selezen, firebit, cooltorrent, theempire, finelite, cpasbienclone, hdtorrentsit, bibliotik, lesaloon, speedtorrentreloaded, anisource, takeabyte, gaytorrentru, torrentparadise, torrent4you, linuxtracker, microbit, dxdhd, legacyhd, racingforme, monova, hdme, Channelx, magnetdl, underversel, twilight, movcr, hddolby, oshenpt, underverse, p2pbg, sukebei-pantsu, magico, torrentv, torrentfunk, zamundanet, cartoonchaos, hachede, glodls, torrentgalaxyorg, hdu, eztv, hd4fans, hdreactor, idope, netcosmo, fouducinema, elitetorrent-biz, ourbits, arabafenice, tokyotosho, sdbits, purovicio, zooqle, hdstreet, thepiratebay, demonoid, torrentoyunindir, baibako, torrent9clone, thevault, pornotor, kinorun, beitai, xtremefile, torrentlt, Das-Unerwartete, pixelcove, hdcenter, casatorrent, marinetracker, cztorrent, unionfansub, tekno3d, keepfriends, bigtower, gamestorrents, torrentz2, amigosshare, isohunt2, torrentz2k, diablotorrent, desitorrents, sktorrent, pwtorrents, zetorrents, sportscult, soundpark, tvchaosuk, magnet4you, sktorrent-org, ebookparadijs, beyond-hd, uhdbits, horrorsite, yggcookie, bitspyder, karagarga, btsow, bit-titan, girotorrent, mononokebt, acidlounge, torrentproject2, hdarea, insanetracker, torrentbomb, freetorrent, Bittorrentfiles, puntorrent, theshinning, hddisk, lechaudron, 4thd, hdspain, bithorlo, tlfbits, audiobooktorrents, retroflix, hdroute, torrentfactory, sharewood, 32pages, turktorrent, 1337x, generationfree, asgaard, torrentleech-pl, ydypt, snowpt, torrenthr, nitro, desireleasers, bitturk, torlock, onejav, bluebirdhd, spiritofrevolution, hdbits, beyond-hd-oneurl, downloadville, rintor, scenepalace, alexfilm, hqsource, hdzone, torrent-turk, exttorrents, pornbits, ast4u, mvgroupmain, kinonavse100, brobits, turkseed, btnext, pctorrent, ptfiles, hdforever, finvip, 3evils, crazyhd, empornium2fa, redstartorrent, rptorrents, extremebits, tasmanit, frozenlayer, sosulki, bigfangroup, bithumen, xfsub, femdomcult, ttsweb, pthome, kaztorka, korsar, nntt, uniongang, aither, rutracker-ru, gigatorrents, hdbitscom, zelkaorg, teamhd, witchhunter, kickasstorrent, concen, blutopia, ethor, torrentquest, tjupt, theshow, totallykids, yggtorrent, torrentdb, deildu, dark-shadow, polishsource, hush, btetree, pornolive, arenabg, springsunday, torrentdownload, prostylex, skytorrentsclone, 52pt, moviesdvdr, thefallingangels, focusx, shokweb, libranet, gay-torrents, omgwtftrackr, oxtorrent, mactorrents, nethd, dxp, 2fast4you, asiancinema, limetorrents, dimeadozen, torrentbd, myspleen, piratbit, pt99, mteamtp, fanoin, kinozal, onlineselfeducation, jpopsuki, btgigs, 7torrents, wihd, exkinoray, btschool, divteam, world-of-tomorrow, mteamtp2fa, topnow, scenerush, pleasuredome, efectodoppler, crazyspirits, shellife, torrentkitty, hdsky, hdhome, wdt, btdigg, pirateiro, torrent9, pornleech, RockBox, romanianmetaltorrents, losslessclub, cpasbien, siambit, r3vwtf, boxingtorrents, torrentsectorcrew, tellytorrent, fullmixmusic, leaguehd, newstudio, torrenting, audionews, pussytorrents, ilcorsaronero, acgsou, torrentland, twilightszoom, xbytesv2, estone, erzsebetpl, mypornclub, trancetraffic, ptsbao, xxxtor, soulvoice, epizod, audiobookbay, funkytorrents, filebase, racing4everyone, carpathians, ettv, learnflakes, rus-media, hdtime, hdchina, uniotaku, moecat, badasstorrents, chilebt, extremetorrents, kickasstorrent-kathow, proaudiotorrents, speedmasterhd, mma-torrents, extratorrent-cd, cinemageddon, brasiltracker, spacetorrent
2020-07-24T12:58:47.658954453Z 07-24 12:58:47 Info Adding aggregate indexer
2020-07-24T12:58:47.746205205Z 07-24 12:58:47 Info Jackett startup finished in 3.015 s
2020-07-24T12:58:47.746284866Z Hosting environment: Production
2020-07-24T12:58:47.746311676Z Content root path: /app/Jackett/Content
2020-07-24T12:58:47.746320166Z Now listening on: http://[::]:9117
2020-07-24T12:58:47.746326096Z Application started. Press Ctrl+C to shut down.
2020-07-24T12:58:57.941394350Z 07-24 12:58:57 Error Error on 20200724125857 for PassThePopcorn.txtNewtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.
2020-07-24T12:58:57.941422070Z    at Newtonsoft.Json.JsonTextReader.ParseValue()
2020-07-24T12:58:57.941427190Z    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
2020-07-24T12:58:57.941430450Z    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
2020-07-24T12:58:57.941433630Z    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 120
2020-07-24T12:58:57.941436750Z
2020-07-24T12:58:57.941439630Z
2020-07-24T12:58:57.941442390Z
2020-07-24T12:58:57.941445240Z
2020-07-24T12:58:57.941448130Z Your popcorn quota has been reached, come back later!
2020-07-24T12:58:57.941452960Z
2020-07-24T12:58:57.953464656Z 07-24 12:58:57 Error Jackett.Common.IndexerException: Exception (passthepopcorn): Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.
2020-07-24T12:58:57.953478936Z  ---> System.Exception: Parse error
2020-07-24T12:58:57.953483046Z  ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.
2020-07-24T12:58:57.953486396Z    at Newtonsoft.Json.JsonTextReader.ParseValue()
2020-07-24T12:58:57.953489306Z    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
2020-07-24T12:58:57.953500716Z    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
2020-07-24T12:58:57.953504616Z    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 120
2020-07-24T12:58:57.953508906Z    --- End of inner exception stack trace ---
2020-07-24T12:58:57.953512126Z    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 831
2020-07-24T12:58:57.953515186Z    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 250
2020-07-24T12:58:57.953517976Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 325
2020-07-24T12:58:57.953520696Z    --- End of inner exception stack trace ---
2020-07-24T12:58:57.953523206Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
2020-07-24T12:58:57.953525916Z    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
2020-07-24T12:58:57.953528677Z    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 274
2020-07-24T12:58:57.953531437Z    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
2020-07-24T12:58:57.953535327Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2020-07-24T12:58:57.953538217Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2020-07-24T12:58:57.953541267Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-07-24T12:58:57.953544247Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2020-07-24T12:58:57.953546867Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2020-07-24T12:58:57.953549867Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-07-24T12:58:57.953552887Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-07-24T12:58:57.953555857Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2020-07-24T12:58:57.953561547Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2020-07-24T12:58:57.953564477Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2020-07-24T12:58:57.953567387Z    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.IndexerException: Exception (passthepopcorn): Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.
2020-07-24T12:58:57.953570557Z  ---> System.Exception: Parse error
2020-07-24T12:58:57.953573107Z  ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.
2020-07-24T12:58:57.953575967Z    at Newtonsoft.Json.JsonTextReader.ParseValue()
2020-07-24T12:58:57.953580457Z    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
2020-07-24T12:58:57.953584527Z    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
2020-07-24T12:58:57.953587337Z    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 120
2020-07-24T12:58:57.953590127Z    --- End of inner exception stack trace ---
2020-07-24T12:58:57.953592707Z    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 831
2020-07-24T12:58:57.953595487Z    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 250
2020-07-24T12:58:57.953598257Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 325
2020-07-24T12:58:57.953601247Z    --- End of inner exception stack trace ---
2020-07-24T12:58:57.953603807Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
2020-07-24T12:58:57.953606577Z    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
2020-07-24T12:58:57.953609407Z    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 274
2020-07-24T12:58:57.953612147Z    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
2020-07-24T12:58:57.953614877Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2020-07-24T12:58:57.953617937Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2020-07-24T12:58:57.953624247Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-07-24T12:58:57.953627357Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2020-07-24T12:58:57.953630007Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2020-07-24T12:58:57.953632887Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-07-24T12:58:57.953635987Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-07-24T12:58:57.953638947Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2020-07-24T12:58:57.953641777Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2020-07-24T12:58:57.953644607Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2020-07-24T12:58:57.953647237Z    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2020-07-24T12:59:09.698589958Z 07-24 12:59:09 Error Error on 20200724125909 for PassThePopcorn.txtNewtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.
2020-07-24T12:59:09.698626329Z    at Newtonsoft.Json.JsonTextReader.ParseValue()
2020-07-24T12:59:09.698635109Z    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
2020-07-24T12:59:09.698641169Z    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
2020-07-24T12:59:09.698646719Z    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 120
2020-07-24T12:59:09.698653229Z
2020-07-24T12:59:09.698657969Z
2020-07-24T12:59:09.698663069Z
2020-07-24T12:59:09.698668059Z
2020-07-24T12:59:09.698673579Z Your popcorn quota has been reached, come back later!
2020-07-24T12:59:09.698678959Z
2020-07-24T12:59:09.700308252Z 07-24 12:59:09 Error Jackett.Common.IndexerException: Exception (passthepopcorn): Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.
2020-07-24T12:59:09.700330392Z  ---> System.Exception: Parse error
2020-07-24T12:59:09.700342252Z  ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.
2020-07-24T12:59:09.700345392Z    at Newtonsoft.Json.JsonTextReader.ParseValue()
2020-07-24T12:59:09.700348772Z    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
2020-07-24T12:59:09.700351802Z    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
2020-07-24T12:59:09.700354642Z    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 120
2020-07-24T12:59:09.700356582Z    --- End of inner exception stack trace ---
2020-07-24T12:59:09.700359922Z    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 831
2020-07-24T12:59:09.700364262Z    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 250
2020-07-24T12:59:09.700367292Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 325
2020-07-24T12:59:09.700369712Z    --- End of inner exception stack trace ---
2020-07-24T12:59:09.700372092Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
2020-07-24T12:59:09.700374552Z    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
2020-07-24T12:59:09.700377452Z    at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 224 Jackett.Common.IndexerException: Exception (passthepopcorn): Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.
2020-07-24T12:59:09.700380642Z  ---> System.Exception: Parse error
2020-07-24T12:59:09.700383872Z  ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.
2020-07-24T12:59:09.700386652Z    at Newtonsoft.Json.JsonTextReader.ParseValue()
2020-07-24T12:59:09.700389193Z    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
2020-07-24T12:59:09.700391743Z    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
2020-07-24T12:59:09.700395073Z    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 120
2020-07-24T12:59:09.700397953Z    --- End of inner exception stack trace ---
2020-07-24T12:59:09.700400383Z    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 831
2020-07-24T12:59:09.700403083Z    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 250
2020-07-24T12:59:09.700409283Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 325
2020-07-24T12:59:09.700411953Z    --- End of inner exception stack trace ---
2020-07-24T12:59:09.700414413Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
2020-07-24T12:59:09.700417063Z    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
2020-07-24T12:59:09.700419873Z    at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 224
2020-07-24T12:59:09.703765769Z 07-24 12:59:09 Info Manual search for "Matrix" on passthepopcorn with 0 results.
```

### Screenshots

N/A

**Comment by garfield69** [comment] 2020-07-24 19:10
closing as a duplicate of #8927

**Closed by garfield69** 2020-07-24 19:10 UTC
