### ISSUE TITLE
[BUG] NoNameClub RSS error

### ISSUE THREAD

**Issue by dm3ch** [Jackett/Jackett#5405] opened 2019-06-04 18:55 UTC
**Jackett version**:   Jackett Version 0.11.385.0

-------------------------------
When I'm trying to open RSS feed formed by NoNameClub indexer - i'm getting error.
```
<error code="900" description="System.ArgumentNullException: Value cannot be null. Parameter name: value at System.Xml.Linq.XAttribute..ctor(XName name, Object value) at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63 at System.Linq.Enumerable.SelectListIterator`2.MoveNext() at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content) at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content) at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39 at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417"/>
```

At same time searching works on this tracker works great.

**Comment by garfield69** [comment] 2019-06-12 01:31
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by Dm3Ch** [comment] 2019-06-12 19:00
@garfield69 I have rechecked and NNMClub RSS feed works fine if query parameter passed.
If there query parameter is empty then I got logs listed below.

The behaviour with empty query string is different for some other indexers (Lostfilm for example).
```
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417 System.ArgumentNullException: Value cannot be null.
```

**Comment by Dm3Ch** [comment] 2019-06-12 19:00
So now I'm not sure does this problem need fix.

**Comment by garfield69** [comment] 2019-06-13 05:27
enabling the enhanced logging I see
```
Jun 13, 2019 05:15:59 PM Error System.ArgumentNullException: Value cannot be null. Parameter name: value
    at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
    at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r)
    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
    at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
    at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
    at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom)
    at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext()
Jun 13, 2019 05:15:59 PM Info Found 200 (0 new) releases from NoName Club
```
so jackett fetched 200 results.  but something determined that there were 0 new. so that lead to the error.

I know nothing about the rss side of jackett to I invite @kaso17  or @flightlevel  to take a look.

**Comment by garfield69** [comment] 2019-08-11 20:23
I recently solved a similar problem with marine tracker tripping up the default rss (that is, one without a search query or categories).
turns out that marine tracker was displaying torrents without download links (because they had been subjected to DMCA) and the RSS processor does not like null dl links.
its possible nnmclub is doing the same although i cannot test it right now as i am getting 502 bad gateways whenever i try to get the next page of results from the web site 
i'll try again another day.

**Comment by garfield69** [comment] 2019-08-14 03:31
confirming that the download link is the cause of the problem you reported with RSS code 900.
fixed by ensuring only torrents with a dl link are returned.
jackett pre-release 0.11.598 is the first to have the fix.

**Closed** 2019-08-14 03:30 UTC
