### ISSUE TITLE
uakino indexer request. UA public torrent

### ISSUE THREAD

**Issue by kroshkamedved** [Jackett/Jackett#14023] opened 2023-02-15 09:34 UTC
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: uakino
- URL: https://uakino.club/
- Description: uakino is a public torrent tracker for Movies and Series in Ukrainian language/UA 
- Minimum Seeding Time and Minimum Ratio (if Private): --
- Additional Comments: also tracker has open registration which allow to skip waiting time before torrent download.
```

**Comment by garfield69** [comment] 2023-02-15 19:18
closing as a duplicate of #13833

**Closed by garfield69** 2023-02-15 19:18 UTC
