### ISSUE TITLE
MejorTorrent problem with some titles with year

### ISSUE THREAD

**Issue by diegargon** [Jackett/Jackett#10916] opened 2021-01-24 18:10 UTC
Version: Latest.

When search example "Wonder woman" give this results
![wonderwoman](https://user-images.githubusercontent.com/6043996/105639331-fe918180-5e77-11eb-9be4-e51ed483c9ad.png)

That ok, but if you search for "Wonder Woman 1984"

![wonderwoman1984](https://user-images.githubusercontent.com/6043996/105639280-95aa0980-5e77-11eb-9815-9ef87eb639bf.png)

Seems jackett add to the same results the words 1984 instead of show only one match (except to the first results)

**Comment by diegargon** [comment] 2021-01-24 18:19
I don't known C# but seems in

https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/MejorTorrent.cs
Line 368:
title = query.Year != null ? title + " " + query.Year : title;

Seems if query the year is added here (don't known why in the first result not added)

**Comment by ngosang** [comment] 2021-01-25 18:24
This is a known problem and it can't be fixed without breaking other searches.
The problem is in the site, the search is a shit. For example, if you search "Harry Potter Y El Cáliz De Fuego" you will find results because it's a exact match but if you search "Harry Potter El Cáliz De Fuego" you get 0 results. To fix that issue we are doing nasty things in Jackett like searching just "Potter" and filter the results later. Similar thing with the year.

**Closed by ngosang** 2021-01-25 18:24 UTC

**Comment by diegargon** [comment] 2021-01-25 19:14
Since years are incorrect always IMO probably is better filter from search the year  than adding to the search result the year searched.

Search for wonder woman 1900 and get all results with 1900 added have not sense from my point of view. 
Of course i don't known in detail that problem. It's ok then

**Comment by ngosang** [comment] 2021-01-25 19:26
> Search for wonder woman 1900 and get all results with 1900 added have not sense from my point of view.

It's another hack to solve another problem. Radarr/Sonarr software uses the year to validate the torrent name. They use the year of the original release date (in some cases is different from the release year in Spain). The hack is to remove the year in the search and add it back later. In manual search is rare to use the year so it's working fine in most cases.

**Comment by diegargon** [comment] 2021-01-25 21:25
hmm ugg i see... I will have to take that into account in my application
