### ISSUE TITLE
Tracker Request: DigitalHive

### ISSUE THREAD

**Issue by slamanna212** [Jackett/Jackett#164] opened 2016-01-07 22:13 UTC
Would love to add this tracker

**Comment by JigSawFr** [comment] 2016-01-08 08:42
@slamanna212 Please read https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker

**Comment by ipsq** [comment] 2016-01-08 17:27
#104

**Comment by ipsq** [comment] 2016-01-08 20:56
#171

**Comment by JigSawFr** [comment] 2016-05-13 23:20
Duplicate of #104

**Closed by JigSawFr** 2016-05-13 23:20 UTC
Labels: New tracker
