### ISSUE TITLE
Can't start Jackett

### ISSUE THREAD

**Issue by gers1978** [Jackett/Jackett#515] opened 2016-09-16 16:15 UTC
Get this error:

`09-16 17:14:16 Error Top level exception Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(IIndexerManagerService, Logger, IWebClient, IProtectionService)' on type 'TorrentSyndikat'. ---> Exception of type 'System.TimeZoneNotFoundException' was thrown. (See inner exception for details.) ---> System.TimeZoneNotFoundException: Exception of type 'System.TimeZoneNotFoundException' was thrown.
  at System.TimeZoneInfo.FindSystemTimeZoneByFileName (System.String id, System.String filepath) <0x2179e80 + 0x000a2> in <filename unknown>:0 
  at System.TimeZoneInfo.FindSystemTimeZoneByIdCore (System.String id) <0x21783a0 + 0x00035> in <filename unknown>:0 
  at System.TimeZoneInfo.FindSystemTimeZoneById (System.String id) <0x2179d90 + 0x000a6> in <filename unknown>:0 
  at Jackett.Indexers.TorrentSyndikat..ctor (IIndexerManagerService i, NLog.Logger l, IWebClient w, IProtectionService ps) <0x3e65098 + 0x00017> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object[])
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () <0x35b7bd0 + 0x00117> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () <0x35b7bd0 + 0x00323> in <filename unknown>:0 
  at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance (IComponentContext context, IEnumerable`1 parameters) <0x35b69e8 + 0x0010f> in <filename unknown>:0 
  at Autofac.Core.Resolving.InstanceLookup.Activate (IEnumerable`1 parameters) <0x35b6788 + 0x0004e> in <filename unknown>:0 
  at Autofac.Core.Resolving.InstanceLookup.<Execute>b__0 () <0x35b6768 + 0x00017> in <filename unknown>:0 
  at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare (Guid id, System.Func`1 creator) <0x35b6310 + 0x000ba> in <filename unknown>:0 
  at Autofac.Core.Resolving.InstanceLookup.Execute () <0x35b60c8 + 0x000f9> in <filename unknown>:0 
  at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance (ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) <0x35b5608 + 0x000d7> in <filename unknown>:0 
  at Autofac.Core.Resolving.InstanceLookup.ResolveComponent (IComponentRegistration registration, IEnumerable`1 parameters) <0x35b7fa0 + 0x0002d> in <filename unknown>:0 
  at Autofac.Features.Collections.CollectionRegistrationSource+<>c__DisplayClass4+<>c__DisplayClass6.<RegistrationsFor>b__1 (IComponentRegistration cr) <0x3e53f28 + 0x00026> in <filename unknown>:0 
  at System.Linq.Enumerable+WhereSelectArrayIterator`2[TSource,TResult].MoveNext () <0xef65f8 + 0x00085> in <filename unknown>:0 
  at System.Linq.Buffer`1[TElement]..ctor (IEnumerable`1 source) <0xef4168 + 0x001a8> in <filename unknown>:0 
  at System.Linq.Enumerable.ToArray[TSource] (IEnumerable`1 source) <0xef40b8 + 0x00047> in <filename unknown>:0 
  at Autofac.Features.Collections.CollectionRegistrationSource+<>c__DisplayClass4.<RegistrationsFor>b__0 (IComponentContext c, IEnumerable`1 p) <0x3e53ad0 + 0x0017f> in <filename unknown>:0 
  at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance (IComponentContext context, IEnumerable`1 parameters) <0x3e53970 + 0x00033> in <filename unknown>:0 
  at Autofac.Core.Resolving.InstanceLookup.Activate (IEnumerable`1 parameters) <0x35b6788 + 0x0004e> in <filename unknown>:0 
  at Autofac.Core.Resolving.InstanceLookup.Execute () <0x35b60c8 + 0x0003f> in <filename unknown>:0 
  at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance (ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) <0x35b5608 + 0x000d7> in <filename unknown>:0 
  at Autofac.Core.Resolving.ResolveOperation.ResolveComponent (IComponentRegistration registration, IEnumerable`1 parameters) <0x35b55d0 + 0x00027> in <filename unknown>:0 
  at Autofac.Core.Resolving.ResolveOperation.Execute (IComponentRegistration registration, IEnumerable`1 parameters) <0x35b54c8 + 0x0002f> in <filename unknown>:0 
`

**Comment by kaso17** [comment] 2016-09-16 17:14
duplicate of #494

**Closed** 2016-10-01 02:35 UTC
