### ISSUE TITLE
[AniDex] Error when searching with categories

### ISSUE THREAD

**Issue by anthonybriand** [Jackett/Jackett#6017] opened 2019-09-20 07:44 UTC
When searching on AniDex with categories selected an error is thrown concerning CloudflareSolverRe

The search was made with the following query : 
terms : one piece
categories : 5070 and 100001

**Exception :**
```
09-20 08:57:59 Error Jackett.Common.IndexerException: Exception (anidex): Clearance failed after 30 attempt(s). ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 241
at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445
at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1230
at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
--- End of inner exception stack trace ---
at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 227 Jackett.Common.IndexerException: Exception (anidex): Clearance failed after 30 attempt(s). ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 241
at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445
at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1230
at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
--- End of inner exception stack trace ---
at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 227
```

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.11.703.0 (net-core)

**Comment by garfield69** [comment] 2019-09-20 08:31
the error comes as a result of the anidex indexer trying https://anidex.info/?page=search&id=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,&group_id=0&q=one%20piece
which yields this page
![image](https://user-images.githubusercontent.com/6933240/65311502-8f04e580-dbe4-11e9-990b-e54ec2ebc80f.png)
which the cloundflareSolverRe library obviously cannot solve and hence the failure after 30 attempts error message.
the problem is with the last comma in the id list. 
I will take a look at the yaml and see if there is anything I can do to fix this.

**Comment by garfield69** [comment] 2019-09-20 09:06
nothing I can do about this, it is a limitation of the cardigann yaml processor in combination with the anidex web site restrictions.

the cardigann processor needs the comma to separate the categories, and does not allow for an exception if you use all 16 categories, which is what happens when you select category 5070 (essentially you are say you want all categories).
the anidex website is happy to handle up to 15 categories comma delimited, with a trailing comma, 
https://anidex.info/?page=search&id=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,&group_id=0&q=one%20piece 
but the moment you ask for all 16 categories, it insists that there not be a trailing comma
https://anidex.info/?page=search&id=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16&group_id=0&q=one%20piece 
the only way to properly prevent this error it to rewrite this indexer in c# which will require a c# developer to volunteer to code.
in the mean time, avoid using category 5070, or selecting all 16 individual categories at once, when you do your searches.
note that the indexers' default search is to use id=0 , which is in effect a search using cat=5070

**Comment by anthonybriand** [comment] 2019-09-20 09:17
Ok thanks for this explanation and workaround

**Comment by 6cUbi57z** [comment] 2019-10-13 20:33
I think I've found a fix for this but I'm not too familiar with cardigann and don't have a development environment set up to test, but it seems that Anidex will accept the categories if you prefix the comma instead of postfix.

**Invalid:**
```url
https://anidex.info/?page=search&id=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,&lang_id=1&group_id=0&q=
```
**Valid:**
```url
https://anidex.info/?page=search&id=,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16&lang_id=1&group_id=0&q=
```

I believe this means that https://github.com/Jackett/Jackett/blob/2ffbedc2faaed33e8f4788d7bb6c4fe99b1236af/src/Jackett.Common/Definitions/anidex.yml#L45 just needs changing to:
```yaml
- path: "?page=search&id={{if .Categories}}{{range .Categories}},{{.}}{{end}}{{else}}0{{end}}{{if .Config.lang-id}}&lang_id={{.Config.lang-id}}{{else}}{{end}}&group_id=0&q={{if .Keywords}}{{.Keywords}}{{else}}{{end}}"
```
but as I said, I don't have a dev environment set up so it would take a while for me to test such a small change.

**Comment by garfield69** [comment] 2019-10-14 00:21
@6cUbi57z  nice find. I've tested and it looks good so I've implemented the change. Thanks.

**Closed** 2019-10-14 00:21 UTC
Labels: Help wanted, needs c#

**Comment by 6cUbi57z** [comment] 2019-10-19 22:32
It seems the Cloudflare configuration has been updated for Anidex. It now doesn't support supplying all categories (even with the comma prefix). Interestingly, this is also an issue when browsing through the website. If you select all categories and try to search, you get the same Cloudflare error.

**Comment by fryfrog** [comment] 2019-12-12 18:25
I stumbled on this trying to fix Anidex in Sonarr, where I use `5070` as is standard. Since I only care about TV, I've just changed this to `100001,100002,100003` and it works.
