### ISSUE TITLE
[mejortorrent] The sequence contains no elements

### ISSUE THREAD

**Issue by TheRayoX** [Jackett/Jackett#5787] opened 2019-08-04 22:26 UTC
Hi,
I'm trying to add the MejorTorrentindexer but I get the error: "The sequence contains no elements"

Is there any way to fix it?

Site: http://www.mejortorrentt.org/

Indexer: MejorTorrent

**Comment by garfield69** [comment] 2019-08-05 01:39
duplicate of #5587

**Closed by garfield69** 2019-08-05 01:39 UTC
