### ISSUE TITLE
[opensharing] (testing) Exception (opensharing): Got redirected to another domain. Try changing the indexer URL to http://traht.org/.: Parse error

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#13612] opened 2022-09-30 17:46 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-09-29 22:18:52	Info	
Using HTTP Client: HttpWebClient2
2022-09-29 22:18:52	Info	
Using FlareSolverr: http://127.0.0.1:8191
2022-09-29 22:18:52	Info	
Using proxy: Disabled
2022-09-29 22:18:52	Info	
App config/log directory: C:\ProgramData\Jackett
2022-09-29 22:18:51	Info	
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-09-29 22:18:51	Info	
Running in Docker: No
2022-09-29 22:18:51	Info	
Jackett variant: CoreWindows
2022-09-29 22:18:51	Info	
OS version: Microsoft Windows NT 10.0.22621.0 (64bit OS)
2022-09-29 22:18:50	Info	
Environment version: 6.0.9 (C:\ProgramData\Jackett\)
2022-09-29 22:18:48	Info	
Starting Jackett v0.20.2013
```

### Description

change domain to http://traht.org/

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (opensharing): Got redirected to another domain. Try changing the indexer URL to http://traht.org/.: Parse error
Click here to open an issue on GitHub for this indexer.
```

**Comment by garfield69** [comment] 2022-09-30 18:27
closing as a duplicate of #12477

**Closed by garfield69** 2022-09-30 18:27 UTC
