### ISSUE TITLE
[cpasbien] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by NunoVilhenaSantos** [Jackett/Jackett#2567] opened 2018-02-10 01:19 UTC
**Jackett version**:  0.8.676.0
-------------------------------
https://www.cpasbiens.net/
https://pastebin.com/T5jSDEyD

**Comment by garfield69** [comment] 2018-02-10 03:46
Duplicate of #2564

**Closed by garfield69** 2018-02-10 03:46 UTC
Labels: Duplicate
