### ISSUE TITLE
[rarbg] Exception (rarbg): Error parsing Infinity value. Path '', line 1, position 2.: Error parsing Infinity value. Path '', line 1, position 2. (Test)

### ISSUE THREAD

**Issue by simeon4110** [Jackett/Jackett#2758] opened 2018-03-21 00:35 UTC
**Jackett version**:  0.8.770.0
**Mono version** (if not using Windows):  Mono JIT compiler version 5.10.0.160 (tarball Wed Mar  7 15:14:33 UTC 2018)

**Comment by garfield69** [comment] 2018-03-21 00:36
Duplicate of #2753

**Closed by garfield69** 2018-03-21 00:36 UTC
