### ISSUE TITLE
[privatehd] (updating) Unknown error: <title>Error 503: Down for Maintenance</title>

### ISSUE THREAD

**Issue by fcmircea** [Jackett/Jackett#14479] opened 2023-06-19 10:20 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: Disabled
Using proxy: Disabled
App config/log directory: /var/lib/deluge/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 22.04.2 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.15.0.75 (64bit OS) (64bit process)
Environment version: 6.0.18 (/media/jackett/)
Starting Jackett v0.21.245
```

### Description

Cannot add indexer from jackett page, long error thrown.

### Logged Error Messages

```text
Unknown error: <!doctype html> <html class="no-js" lang=""> <head> <meta charset="utf-8"> <meta http-equiv="x-ua-compatible" content="ie=edge"> <title>Error 503: Down for Maintenance</title> <meta name="viewport" content="width=device-width, initial-scale=1"> <meta name="_token" content=""> <meta name="_base_url" content="https://privatehd.to"> <link rel="shortcut icon" href="https://privatehd.to/images/privatehd-favicon.png"> <link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400,700|Roboto+Mono:300,400|Roboto:300,400,500,700" rel="stylesheet"> <link href="https://privatehd.to/css/style.css?v=1682496363" rel="stylesheet"> <!--[if lte IE 8]> <script src="https://privatehd.to/js/html5shiv.respond.min.js"></script><![endif]--> </head> <body> <header> <nav class="navbar navbar-default navbar-fixed-top"> <div class="container"> <div class="navbar-header"> <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button> <a class="navbar-brand hidden-md" href="/"><img src="https://privatehd.to/images/privatehd-logo-dark.png" alt="PrivateHD"></a> </div> <div id="navbar" class="navbar-collapse collapse"> <ul class="nav navbar-nav "> <li class="" title="Home"> <a href="https://privatehd.to">Home</a> </li> <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse
```

**Comment by garfield69** [comment] 2023-06-19 10:42
Duplicate of #13817 and #13573 

the error `Error 503: Down for Maintenance` should give you the clue that this is a problem at the web site and not jackett ;-)

**Closed by garfield69** 2023-06-19 10:42 UTC
