### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Error parsing JS challenge html: Error parsing JS challenge html (Test)

### ISSUE THREAD

**Issue by RaphaelDucay** [Jackett/Jackett#8464] opened 2020-05-01 12:07 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Win10
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
0.16.227.0

**Last Working Jackett Version**:
0.16.185.0

**Are you using a proxy or VPN?** [yes/no]
no
### Description
Tried to upgrade from 0.16.185.0 to 0.16.227.0 to solve my issue #8463 
Still getting an error but different on yggtorrent indexer test (failing)

### Logged Error Messages

Exception (yggtorrent): Error parsing JS challenge html: Error parsing JS challenge html (Test)
### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/9933141/80804192-b6795300-8bb4-11ea-9ce2-1380543d7b28.png)

**Comment by guicha910** [comment] 2020-05-01 12:21
Same here, I either have this error message or this one : "Exception (yggtorrent): Input string was not in a correct format.: Input string was not in a correct format.".

Updated jackett, but still same error.

**Comment by aguillem** [comment] 2020-05-01 12:26
Same here. Try to configure YggCookie indexer instead and still have the same error.

**Comment by MartnIV** [comment] 2020-05-01 12:37
Same error

**Comment by Atheros33** [comment] 2020-05-01 12:50
Same here, the error is now "Exception (yggcookie): Input string was not in a correct format.: Input string was not in a correct format."

**Comment by MartnIV** [comment] 2020-05-01 13:14
Yes, i now have the same error: "Exception (yggcookie): Input string was not in a correct format.: Input string was not in a correct format." on Yggtorrent.

Non-related question: is there any advantage to use Yggcookie over Yggtorrent?

**Comment by Miko2708** [comment] 2020-05-01 14:38
hello same for me i'm using docker-compose on ubuntu 18.04
[logJackett.txt](https://github.com/Jackett/Jackett/files/4564734/logJackett.txt)

**Comment by bossovitch** [comment] 2020-05-01 16:26
same here, yggtorrent cause lot of trouble this time...

**Comment by loulich** [comment] 2020-05-01 17:21
same here:  Input string was not in a correct format

**Comment by sam37git** [comment] 2020-05-01 17:23
same here: Input string was not in a correct format

**Comment by navycrow** [comment] 2020-05-01 17:31
+1

**Comment by ngosang** [comment] 2020-05-01 17:33
This issues is caused by Cloudflare. They changed the JS challenge again and the library that we use to solve the challenge is abandoned. https://github.com/RyuzakiH/CloudflareSolverRe/issues
I will fix it soon, but we have to find a long term solution or more developers...

**Comment by 0xAcid** [comment] 2020-05-01 18:13
As already stated here : https://github.com/Jackett/Jackett/issues/8056#issuecomment-609989148
Using selenium to get those token is doable. I am doing it on my private yggtorrent scraper, and no issue so far.
Using selenium is not an elegant solution for sure, but it would be pretty hard for cloudflare to break it. 
Just my 2 cents

**Comment by jonozzz** [comment] 2020-05-01 18:53
`torrentz2.eu` is also affected by this.

**Comment by CyberPoison** [comment] 2020-05-01 19:27
Same Issue here, Thanks if will be a fix for this.

**Comment by garfield69** [comment] 2020-05-01 19:35
@MartnIV  wrote:
>Non-related question: is there any advantage to use Yggcookie over Yggtorrent?

YGGCokie has advantages and disadvantages
- the advantage is that when YGGTorrent's login method does not work then YGGCookie can usually provide an alternate method of access
- the disadvantage is that the cookie method is temporary as the cookie expires regularly and so needs fetching frequently. Also, some users on seedboxes or VPN find the cookie method does not work for them.

and right now, neither method works for me. so you will just have to use your browser for now, as Jackett cannot access the web site until the Cloudflare library is updated to handle the new challenge (hopefully).

**Comment by CyberPoison** [comment] 2020-05-01 19:49
@garfield69 do you have any date for when the CloudFlare Library will be updated ?

**Comment by ngosang** [comment] 2020-05-01 20:06
Update: The new challenge is more complex. They have raised the bar...

At this moment none of the CloudFlare resolvers that I know are working, the only fix is to use Selenium (It's a full web browser) to solve the challenge, but it can't be integrated into Jackett easily and I'm against anyway.
You can follow advances here:
* https://github.com/RyuzakiH/CloudflareSolverRe/issues
* https://github.com/VeNoMouS/cloudscraper/issues/209
When there is a fix it will be implemented in Jackett but I think this is going to take a while...

**Comment by fabwardo** [comment] 2020-05-02 05:06
Also affecting 1337x

**Comment by foux** [comment] 2020-05-02 06:31
> As already stated here : [#8056 (comment)](https://github.com/Jackett/Jackett/issues/8056#issuecomment-609989148)
> Using selenium to get those token is doable. I am doing it on my private yggtorrent scraper, and no issue so far.
> Using selenium is not an elegant solution for sure, but it would be pretty hard for cloudflare to break it.
> Just my 2 cents

Any possibility to share your scraper?

**Comment by ilike2burnthing** [comment] 2020-05-02 08:41
In terms of public indexers, it will affect all of these - https://github.com/Jackett/Jackett/issues/7325#issuecomment-603887196

@ngosang I take it this would also cause `Input string was not in a correct format.`?
Both shown here:
[log - input string.txt](https://github.com/Jackett/Jackett/files/4567335/log.-.input.string.txt)
[log - js challenge.txt](https://github.com/Jackett/Jackett/files/4567336/log.-.js.challenge.txt)

**Comment by garfield69** [comment] 2020-05-02 09:05
@ilike2burnthing  wrote:
>I take it this would also cause `Input string was not in a correct format.`?

yes.

**Comment by tchirou** [comment] 2020-05-02 09:50
Any possibility to use this ?https://github.com/RyuzakiH/CloudflareSolverRe/issues/28#issuecomment-622799060

**Comment by darkcattz** [comment] 2020-05-02 13:27
same here: Input string was not in a correct format

**Comment by minitoaster** [comment] 2020-05-02 13:40
same here

**Comment by ngosang** [comment] 2020-05-02 16:08
I just cracked Cloudflare again. I think this time will last more.
Code and package => https://github.com/RyuzakiH/CloudflareSolverRe/pull/29

Fixes all sites with Cloudflare JS: YggTorrent, Limetorrents, Torrentz2, BTDB, BTEye..
This change will be included included in the next Jackett release (when @garfield69 has time)

**Comment by tchirou** [comment] 2020-05-02 16:09
You are the man 💪🏻
Thanks a lot !

**Closed** 2020-05-02 16:21 UTC
Labels: Confirmed

**Comment by ilike2burnthing** [comment] 2020-05-02 16:36
Confirmed working. Nicely done! ;)

**Comment by guicha910** [comment] 2020-05-02 16:41
Does not work yet on docker.

**Comment by Sebclem** [comment] 2020-05-02 16:53
> Does not work yet on docker.

Docker as not been updated yet, juste be patient 😉

**Comment by guicha910** [comment] 2020-05-02 16:56
> > Does not work yet on docker.
> 
> Docker as not been updated yet, just be patient 😉

D'accord Seb

**Comment by garfield69** [comment] 2020-05-02 21:51
Jackett 0.16.256

**Comment by angoody** [comment] 2020-05-03 09:30
I still have "Exception (yggtorrent): Input string was not in a correct format.: Input string was not in a correct format." in a docker with Jackett 0.16.256

Would you like the full log?

**Comment by garfield69** [comment] 2020-05-03 09:38
@angoody
>  Would you like the full log?

yes thanks. the **enhanced** log. see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by angoody** [comment] 2020-05-03 10:17
Here it is:
2020-05-03 11:09:09.4665 Debug Connection id "0HLVEJI4FMD4B" received FIN. 
2020-05-03 11:09:09.4685 Info Request starting HTTP/1.1 POST http://domo:1083/api/v2.0/indexers/yggtorrent/test  0 
2020-05-03 11:09:09.4877 Debug Connection id "0HLVEJI4FMD4B" disconnecting. 
2020-05-03 11:09:09.4877 Debug Request is continuing in applying rules. Current url is http://domo:1083/api/v2.0/indexers/yggtorrent/test 
2020-05-03 11:09:09.4877 Debug Connection id "0HLVEJI4FMD4B" sending FIN because: "The client closed the connection." 
2020-05-03 11:09:09.4988 Debug Request is continuing in applying rules. Current url is http://domo:1083/api/v2.0/indexers/yggtorrent/test 
2020-05-03 11:09:09.4988 Debug Request is continuing in applying rules. Current url is http://domo:1083/api/v2.0/indexers/yggtorrent/test 
2020-05-03 11:09:09.4988 Debug Connection id "0HLVEJI4FMD4B" stopped. 
2020-05-03 11:09:09.5083 Debug POST requests are not supported 
2020-05-03 11:09:09.5083 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2020-05-03 11:09:09.5177 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/yggtorrent/test' 
2020-05-03 11:09:09.5177 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/yggtorrent/test' 
2020-05-03 11:09:09.5177 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' 
2020-05-03 11:09:09.5177 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' 
2020-05-03 11:09:09.5177 Info Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
2020-05-03 11:09:09.5292 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2020-05-03 11:09:09.5292 Debug Execution plan of resource filters (in the following order): None 
2020-05-03 11:09:09.5292 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2020-05-03 11:09:09.5292 Debug Execution plan of exception filters (in the following order): None 
2020-05-03 11:09:09.5292 Debug Execution plan of result filters (in the following order): None 
2020-05-03 11:09:09.5404 Info Authorization was successful. 
2020-05-03 11:09:09.5404 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2020-05-03 11:09:09.5404 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2020-05-03 11:09:09.5519 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://www2.yggtorrent.se/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date) 
2020-05-03 11:09:10.1599 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 620.6149ms 
2020-05-03 11:09:10.1599 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' 
2020-05-03 11:09:10.1712 Error Jackett.Common.IndexerException: Exception (yggtorrent): Input string was not in a correct format.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Double.Parse(String s)
   at CloudflareSolverRe.Types.Javascript.JsFuck.DecodeNumber(String encodedNumber)
   at CloudflareSolverRe.Types.Javascript.JsCalculation.Solve()
   at CloudflareSolverRe.Types.Javascript.JsCalculation.get_Result()
   at CloudflareSolverRe.Types.Javascript.JsChallenge.ApplyCalculation(Double number, IJsCalculation calculation)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at CloudflareSolverRe.Types.Javascript.JsChallenge.Solve()
   at CloudflareSolverRe.Solvers.JsChallengeSolver.SolveChallenge(String html)
   at CloudflareSolverRe.Solvers.JsChallengeSolver.Solve()
   at CloudflareSolverRe.CloudflareSolver.SolveJavascriptChallenge(Nullable`1 jsDetectResult)
   at CloudflareSolverRe.CloudflareSolver.SolveWithJavascript(Int32 tries)
   at CloudflareSolverRe.CloudflareSolver.Solve()
   at CloudflareSolverRe.CloudflareSolver.Solve(HttpClient httpClient, CloudflareHandler cloudflareHandler, Uri siteUrl, CancellationToken cancellationToken)
   at CloudflareSolverRe.CloudflareSolver.<>c__DisplayClass30_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at CloudflareSolverRe.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at CloudflareSolverRe.CloudflareSolver.Solve(HttpClient httpClient, HttpClientHandler httpClientHandler, Uri siteUrl, CancellationToken cancellationToken, Boolean randomUserAgent)
   at CloudflareSolverRe.ClearanceHandler.GetClearance(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1341
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 799
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 223
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.IndexerException: Exception (yggtorrent): Input string was not in a correct format.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Double.Parse(String s)
   at CloudflareSolverRe.Types.Javascript.JsFuck.DecodeNumber(String encodedNumber)
   at CloudflareSolverRe.Types.Javascript.JsCalculation.Solve()
   at CloudflareSolverRe.Types.Javascript.JsCalculation.get_Result()
   at CloudflareSolverRe.Types.Javascript.JsChallenge.ApplyCalculation(Double number, IJsCalculation calculation)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at CloudflareSolverRe.Types.Javascript.JsChallenge.Solve()
   at CloudflareSolverRe.Solvers.JsChallengeSolver.SolveChallenge(String html)
   at CloudflareSolverRe.Solvers.JsChallengeSolver.Solve()
   at CloudflareSolverRe.CloudflareSolver.SolveJavascriptChallenge(Nullable`1 jsDetectResult)
   at CloudflareSolverRe.CloudflareSolver.SolveWithJavascript(Int32 tries)
   at CloudflareSolverRe.CloudflareSolver.Solve()
   at CloudflareSolverRe.CloudflareSolver.Solve(HttpClient httpClient, CloudflareHandler cloudflareHandler, Uri siteUrl, CancellationToken cancellationToken)
   at CloudflareSolverRe.CloudflareSolver.<>c__DisplayClass30_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at CloudflareSolverRe.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at CloudflareSolverRe.CloudflareSolver.Solve(HttpClient httpClient, HttpClientHandler httpClientHandler, Uri siteUrl, CancellationToken cancellationToken, Boolean randomUserAgent)
   at CloudflareSolverRe.ClearanceHandler.GetClearance(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1341
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 799
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 223
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2020-05-03 11:09:10.2484 Debug The response will be compressed with 'gzip'. 
2020-05-03 11:09:10.2579 Debug Connection id "0HLVEJI4FMD49" completed keep alive response. 
2020-05-03 11:09:10.2579 Info Request finished in 794.7042ms 500 application/json 
2020-05-03 11:09:20.2282 Info Request starting HTTP/1.1 GET http://domo:1083/api/v2.0/server/logs?_=1588500510633   
2020-05-03 11:09:20.2282 Debug Request is continuing in applying rules. Current url is http://domo:1083/api/v2.0/server/logs?_=1588500510633 
2020-05-03 11:09:20.2413 Debug Request is continuing in applying rules. Current url is http://domo:1083/api/v2.0/server/logs?_=1588500510633 
2020-05-03 11:09:20.2413 Debug Request is continuing in applying rules. Current url is http://domo:1083/api/v2.0/server/logs?_=1588500510633 
2020-05-03 11:09:20.2494 Debug The request path /api/v2.0/server/logs does not match a supported file type 
2020-05-03 11:09:20.2594 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2020-05-03 11:09:20.2594 Debug 1 candidate(s) found for the request path '/api/v2.0/server/logs' 
2020-05-03 11:09:20.2677 Debug Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)' with route pattern 'api/v2.0/server/Logs' is valid for the request path '/api/v2.0/server/logs' 
2020-05-03 11:09:20.2677 Debug Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)' 
2020-05-03 11:09:20.2677 Info Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)' 
2020-05-03 11:09:20.2803 Info Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing controller action with signature System.Collections.Generic.List`1[Jackett.Common.Models.CachedLog] Logs() on controller Jackett.Server.Controllers.ServerConfigurationController (jackett). 
2020-05-03 11:09:20.2803 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2020-05-03 11:09:20.2885 Debug Execution plan of resource filters (in the following order): None 
2020-05-03 11:09:20.2988 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter 
2020-05-03 11:09:20.2988 Debug Execution plan of exception filters (in the following order): None 
2020-05-03 11:09:20.2988 Debug Execution plan of result filters (in the following order): None 
2020-05-03 11:09:20.3126 Info Authorization was successful. 
2020-05-03 11:09:20.3126 Debug Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett) 
2020-05-03 11:09:20.3207 Debug Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett) 
2020-05-03 11:09:20.3207 Debug List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter 
2020-05-03 11:09:20.3300 Debug No information found on request to perform content negotiation. 
2020-05-03 11:09:20.3300 Debug Attempting to select an output formatter without using a content type as no explicit content types were specified for the response. 
2020-05-03 11:09:20.3300 Debug Attempting to select the first formatter in the output formatters list which can write the result. 
2020-05-03 11:09:20.3410 Debug Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response. 
2020-05-03 11:09:20.3410 Info Executing ObjectResult, writing value of type 'System.Collections.Generic.List`1[[Jackett.Common.Models.CachedLog, Jackett.Common, Version=0.16.252.0, Culture=neutral, PublicKeyToken=null]]'. 
2020-05-03 11:09:20.3541 Debug The response will be compressed with 'gzip'. 
2020-05-03 11:09:20.3681 Info Executed action Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett) in 58.0036ms 
2020-05-03 11:09:20.3681 Info Executed endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)' 
2020-05-03 11:09:20.3681 Debug Connection id "0HLVEJI4FMD49" completed keep alive response. 
2020-05-03 11:09:20.3681 Info Request finished in 147.9089ms 200 application/json; charset=utf-8 

Tell me if you want more test.

**Comment by LordBilbon** [comment] 2020-05-03 10:30
Hello, i'm still in .252 after docker update, i'm use the linuxserver.io image, another way to update docker jackett ??

**Comment by lukjod** [comment] 2020-05-03 10:41
just wait I guess...

**Comment by angoody** [comment] 2020-05-03 10:58
I have to create an other one issue for the error "Exception (yggtorrent): Input string was not in a correct format.: Input string was not in a correct format." ?

Tell your preference about that.

**Comment by Sebclem** [comment] 2020-05-03 11:52
> Hello, i'm still in .252 after docker update, i'm use the linuxserver.io image, another way to update docker jackett ??

For docker switch to development tag.

And worked for me with .256

**Comment by MartnIV** [comment] 2020-05-03 12:09
How do you change the branch on docker?

**Comment by lukjod** [comment] 2020-05-03 12:57
like this:
`docker pull linuxserver/jackett:development`

**Comment by MartnIV** [comment] 2020-05-03 13:29
Thanks, i added :development to :development into docker -compose and it worked aswell.

**Comment by angoody** [comment] 2020-05-03 13:52
Sorry, I guess I was in 0.16.252

I tried to pull linuxserver/jackett:development and it works, good work

**Comment by LordBilbon** [comment] 2020-05-03 18:36
Yep it’s works with 256 !!

**Comment by minitoaster** [comment] 2020-05-03 18:43
It works again with develop branch !! Thanks

**Comment by RaphaelDucay** [comment] 2020-05-03 21:48
Confirmed fix with 0.16.256 thanx ;)

**Comment by guicha910** [comment] 2020-05-04 08:13
When will it be available on latest release on docker ? I cannot manage to change it to dev branch, too much troubles on a nas to configure everything.

**Comment by garfield69** [comment] 2020-05-04 08:18
we are not responsible for the docker images. 
the [LinuxServer.io](https://linuxserver.io/) team take our builds we publish on this GitHub repo and do what ever it is that they do to create their docker images at [LinuxServer.io Jackett Docker](https://hub.docker.com/r/linuxserver/jackett/).

But if you are saying that our official stable releases are only being tagged as **development** by docker then that is odd because usually it gets tagged as **latest** 
wonder what they doing when we publish a pre-release ... black hole?

you may want to contact the team via [discord](https://discord.gg/YWrKVTn) or [discourse](https://discourse.linuxserver.io/) and follow that up.

we don't have an vested interest in chasing this and any questions you have about docker are best directed to them directly.

**Comment by ilike2burnthing** [comment] 2020-05-04 09:51
.284 is out for :latest Docker users as of 2hrs ago, not sure why .256 never got released
