### ISSUE TITLE
[REQ] TorrentDB

### ISSUE THREAD

**Issue by EvilHidden** [Jackett/Jackett#8112] opened 2020-04-09 22:45 UTC
If possible, please add private tracker TorrentDB. Open signups currently.
https://torrentdb.net

**Comment by garfield69** [comment] 2020-04-09 23:03
This indexer was added to Jacket back in Nov 2016

closing as a duplicate of #7660 

Please check before posting requests, use your Jackett Dashboard add-indexer page !

**Comment by EvilHidden** [comment] 2020-04-09 23:13
It's literally a brand new tracker made yesterday and it does not exist in the Indexer list.

**Comment by garfield69** [comment] 2020-04-09 23:16
Oh, my apologies.
got torrent**DB** and torrent**BD** looking the same to my dyslexic eyes :-D

**Comment by garfield69** [comment] 2020-04-15 07:16
Jackett 0.16.18

**Comment by garfield69** [comment] 2020-04-18 19:04
note: switched from using a login form to a cookie as a results of #8243

**Comment by ilike2burnthing** [comment] 2021-01-14 12:34
https://torrentdb.net/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment] 2021-01-14 18:43
back up

**Comment by ilike2burnthing** [comment] 2021-04-14 11:07
> https://torrentdb.net/ - Error 522 - Connection timed out

**Comment by ilike2burnthing** [comment] 2021-04-14 12:00
back up

**Comment by garfield69** [comment] 2022-07-06 03:09
https://torrentdb.net/ returns fwrite(): Write of 2116 bytes failed with errno=28 No space left on device

**Comment by ilike2burnthing** [comment] 2022-07-06 09:08
back up

**Comment by garfield69** [comment] 2022-10-09 19:36
https://torrentdb.net/ returns DNS_PROBE_FINISHED_NXDOMAIN (DNS domain not found)

**Comment by garfield69** [comment] 2022-10-25 18:00
@EvilHidden  do you have any news on the state of torrentDB, is the site gone, moved to a new domain or just broken?

**Comment by ilike2burnthing** [comment] 2022-10-26 13:01
Unconfirmed explanation about the drama behind the scenes - https://torrentinvites.org/f23/sorry-see-torrentdb-go-what-happened-what-should-u-do-next-610473/

Post from a mod 2wks ago - https://i.imgur.com/oDw6E0Z.png

If it gets to 30 days and there's no signs of life, it's probably not coming back.

**Closed** 2022-11-08 18:58 UTC
Labels: Removed

**Comment by garfield69** [comment] 2022-11-09 06:00
v0.20.2225
