### ISSUE TITLE
[ettv] Exception (ettv): Connection reset by peer: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by zainulhasan** [Jackett/Jackett#12920] opened 2022-02-06 16:34 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-02-06 21:15:43	Info	
Loading Native indexers ...
2022-02-06 21:15:43	Info	
Using HTTP Client: HttpWebClient
2022-02-06 21:15:43	Info	
Mono version: 6.12.0.122 (tarball Mon Feb 22 17:35:18 UTC 2021)
2022-02-06 21:15:43	Info	
Using FlareSolverr: No
2022-02-06 21:15:43	Info	
Using proxy: Disabled
2022-02-06 21:15:43	Info	
App config/log directory: /config
2022-02-06 21:15:43	Info	
ThreadPool MaxThreads: 400 workerThreads, 200 completionPortThreads
2022-02-06 21:15:43	Info	
Running in Docker: Yes (image build: unknown)
2022-02-06 21:15:43	Info	
File /etc/issue: Debian GNU/Linux 11 \n \l
2022-02-06 21:15:43	Info	
Jackett variant: Mono
2022-02-06 21:15:43	Info	
OS version: Unix 5.11.0.1022 (64bit OS) (64bit process)
2022-02-06 21:15:43	Info	
Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5)
2022-02-06 21:15:42	Info	
Jackett Data will be stored in: /config
2022-02-06 21:15:42	Info	
Starting Jackett v0.20.504
×
```

### Description

1. Add new Indexer
2. Click on the test

### Logged Error Messages

```text
02-06 16:15:45 Info Adding aggregate indexer ('all' indexer) ... 

02-06 16:15:45 Info Adding filter indexer ('type:public' indexer) ... 

02-06 16:15:45 Info Adding filter indexer ('type:private' indexer) ... 

02-06 16:15:45 Info Adding filter indexer ('type:semi-public' indexer) ... 

02-06 16:15:46 Info Jackett startup finished in 4.097 s 

Hosting environment: Production

Content root path: /jackett/Content

Now listening on: http://[::]:9117

Application started. Press Ctrl+C to shut down.

02-06 16:16:01 Error Jackett.Common.IndexerException: Exception (ettv): Connection reset by peer ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer

   --- End of inner exception stack trace ---

  at System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException (System.Net.Sockets.SocketError error) [0x00007] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 

  at System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult (System.Int16 token) [0x00022] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 

  at System.Threading.Tasks.ValueTask`1+ValueTaskSourceAsTask+<>c[TResult].<.cctor>b__4_0 (System.Object state) [0x00030] in <533173d24dae460899d2b10975534bb0>:0 

--- End of stack trace from previous location where exception was thrown ---


  at Mono.Net.Security.MobileAuthenticatedStream.InnerRead (System.Boolean sync, System.Int32 requestedSize, System.Threading.CancellationToken cancellationToken) [0x00104] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 

  at Mono.Net.Security.AsyncProtocolRequest.InnerRead (System.Threading.CancellationToken cancellationToken) [0x000ac] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 

  at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x00093] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 

  at Mono.Net.Security.AsyncProtocolRequest.StartOperation (System.Threading.CancellationToken cancellationToken) [0x0008b] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 
\00\00\00\00\00

o.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x00262] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 

  at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x000c3] in <bc3bbe811b4e46778316cb51d004cd96>:0 

   --- End of inner exception stack trace ---

  at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x00102] in <bc3bbe811b4e46778316cb51d004cd96>:0 

  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00322] in <bc3bbe811b4e46778316cb51d004cd96>:0 

  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <bc3bbe811b4e46778316cb51d004cd96>:0 

  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <bc3bbe811b4e46778316cb51d004cd96>:0 

  at System.Net.Http.DecompressionHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ca] in <bc3bbe811b4e46778316cb51d004cd96>:0 

  at FlareSolverrSharp.ClearanceHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000d7] in <568d05b487a84ed38a659cf457341a27>:0 

  at System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x0017e] in <bc3bbe811b4e46778316cb51d004cd96>:0 

  at Jackett.Common.Utils.Clients.HttpWebClient.Run (Jackett.Common.Utils.Clients.WebRequest webRequest) [0x00461] in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient.cs:152 

  at Jackett.Common.Utils.Clients.WebClient.GetResultAsync (Jackett.Common.Utils.Clients.WebRequest request) [0x00178] in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:186 

  at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync (System.String url, System.String cookieOverride, Jackett.Common.Utils.Clients.RequestType method, System.String referer, System.Collections.Generic.IEnumerable`1[T] data, System.Collections.Generic.Dictionary`2[TKey,TValue] headers, System.String rawbody, System.Nullable`1[T] emulateBrowser) [0x000ba] in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:603 

  at Jackett.Common.Indexers.CardigannIndexer.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00837] in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:1375 

  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query, System.Boolean isMetaIndexer) [0x0008e] in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:401 

   --- End of inner exception stack trace ---

  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query, System.Boolean isMetaIndexer) [0x001a9] in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:413 

  at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query, System.Boolean isMetaIndexer) [0x0002a] in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:768 

  at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x0005a] in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:305 

  at Jackett.Server.Controllers.IndexerApiController.Test () [0x000e1] in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:145 

  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 

  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 

  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 

  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x00042] in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:26  Jackett.Common.IndexerException: Exception (ettv): Connection reset by peer ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer

   --- End of inner exception stack trace ---

  at System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException (System.Net.Sockets.SocketError error) [0x00007] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 

  at System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult (System.Int16 token) [0x00022] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 

  at System.Threading.Tasks.ValueTask`1+ValueTaskSourceAsTask+<>c[TResult].<.cctor>b__4_0 (System.Object state) [0x00030] in <533173d24dae460899d2b10975534bb0>:0 

--- End of stack trace from previous location where exception was thrown ---


  at Mono.Net.Security.MobileAuthenticatedStream.InnerRead (System.Boolean sync, System.Int32 requestedSize, System.Threading.CancellationToken cancellationToken) [0x00104] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 

  at Mono.Net.Security.AsyncProtocolRequest.InnerRead (System.Threading.CancellationToken cancellationToken) [0x000ac] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 

  at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x00093] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 

  at Mono.Net.Security.AsyncProtocolRequest.StartOperation (System.Threading.CancellationToken cancellationToken) [0x0008b] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 
\00\00\00\00\00

o.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x00262] in <9c6e2cb7ddd8473fa420642ddcf7ce48>:0 

  at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x000c3] in <bc3bbe811b4e46778316cb51d004cd96>:0 

   --- End of inner exception stack trace ---

  at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x00102] in <bc3bbe811b4e46778316cb51d004cd96>:0 

  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00322] in <bc3bbe811b4e46778316cb51d004cd96>:0 

  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <bc3bbe811b4e46778316cb51d004cd96>:0 

  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <bc3bbe811b4e46778316cb51d004cd96>:0 

  at System.Net.Http.DecompressionHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ca] in <bc3bbe811b4e46778316cb51d004cd96>:0 

  at FlareSolverrSharp.ClearanceHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000d7] in <568d05b487a84ed38a659cf457341a27>:0 

  at System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x0017e] in <bc3bbe811b4e46778316cb51d004cd96>:0 

  at Jackett.Common.Utils.Clients.HttpWebClient.Run (Jackett.Common.Utils.Clients.WebRequest webRequest) [0x00461] in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient.cs:152 

  at Jackett.Common.Utils.Clients.WebClient.GetResultAsync (Jackett.Common.Utils.Clients.WebRequest request) [0x00178] in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:186 

  at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync (System.String url, System.String cookieOverride, Jackett.Common.Utils.Clients.RequestType method, System.String referer, System.Collections.Generic.IEnumerable`1[T] data, System.Collections.Generic.Dictionary`2[TKey,TValue] headers, System.String rawbody, System.Nullable`1[T] emulateBrowser) [0x000ba] in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:603 

  at Jackett.Common.Indexers.CardigannIndexer.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00837] in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:1375 

  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query, System.Boolean isMetaIndexer) [0x0008e] in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:401 

   --- End of inner exception stack trace ---

  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query, System.Boolean isMetaIndexer) [0x001a9] in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:413 

  at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query, System.Boolean isMetaIndexer) [0x0002a] in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:768 

  at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x0005a] in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:305 

  at Jackett.Server.Controllers.IndexerApiController.Test () [0x000e1] in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:145 

  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 

  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 

  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 

  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 

  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x00042] in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:26
```

### Screenshots

![image](https://user-images.githubusercontent.com/10378868/152690886-867720cb-0fec-4d99-a999-6d3b9c3954aa.png)

**Comment by garfield69** [comment] 2022-02-06 17:33
ETTV is offline, and unlikely to return. 
#2052 will be used to track if the site comes back online or if we remove the indexer withing the next two weeks.
Closing as a duplicate of #2052

**Closed by garfield69** 2022-02-06 17:33 UTC
