### ISSUE TITLE
[blutopia] Exception (blutopia): Login Failed, got redirected.: Parse error (Test)

### ISSUE THREAD

**Issue by killerqueen619** [Jackett/Jackett#6965] opened 2020-01-16 15:35 UTC
error always failed

**Comment by HDVinnie** [comment] 2020-01-16 16:06
update your `jackett to v0.12.1574`
We switched the blutopia indexer to using the cookie method in this release to resolve this issue.

Duplicate of #6941 #6961 Please search opened and closed issues before opening one.

**Closed** 2020-01-16 18:24 UTC
Labels: Duplicate
