### ISSUE TITLE
[New Tracker REQ] AsianDVDClub (ADC)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#890] opened 2016-12-26 11:41 UTC
**Indexer Name**
AsianDVDClub

**Type**
Movies

**Indexer URL**
http://asiandvdclub.org/

**Indexer Language**
English

**Invite**
Now open for application signups, probably for a limited time:
http://asiandvdclub.org/invite_application.php

**Comment by kaso17** [comment] 2016-12-26 14:07
Seems like they don't like my IP:
```
You are currently not allowed to register on ADC because of persistent abusive behavior in your area.

To join the ADC community, you will need to be invited by a friend.
```

**Comment by armani316** [comment] 2016-12-26 14:10
@kaso17 Strange! They're not known for banning certain countries or regions!

**Comment by armani316** [comment] 2017-01-11 01:07
It turns out that opening the application form to the public was, and still is, an error. There was no intention to receive applications in the first places, and all submitted applications have not been received. We may need to shelve this until proper applications signups are open, or until a current member sends an invite.

**Comment by kaso17** [comment] 2017-01-11 14:02
That would explain why I didn't get any response to my application yet.
I guess a real invite is needed.

**Comment by ShahadatRD** [comment] 2017-01-16 12:19
there application option is a real shit :/ i am sure that, they are not gonna reply to filled up applicants. all you need is just a real invite.

**Comment by armani316** [comment] 2017-01-16 12:25
@ShahadatRD Yeah unfortunately you're right. I logged in to their IRC channel and checked with them regarding the status of my application; they said the whole thing was a mistake. They never intended to open application signups anyways. All submitted applications are basically in limbo.

**Comment by ShahadatRD** [comment] 2017-01-16 12:29
are they joking dude ! if that was a mistake then what about this page, http://asiandvdclub.org/invite_application.php ? which exists yet ! @armani316

**Comment by armani316** [comment] 2017-01-16 12:32
@ShahadatRD I asked that same question. They said the staff, "Don't know how to close it." 

I'm not buying it, but I didn't ask any further questions.

**Comment by ShahadatRD** [comment] 2017-01-16 12:37
@armani316  What!!! they don't even know how to close or remove a page??? then how they got the encourage to start managing a tracker !!  by the way, i am going through their IRC. i have to ask a lot of stuff to them...

**Comment by armani316** [comment] 2017-01-16 12:42
@ShahadatRD That will be an interesting conversation :) Feel free to let us know how it goes, I'm keen to hear their rationale :)

**Comment by ShahadatRD** [comment] 2017-01-16 13:08
@armani316  have a look to my conversation with these shitty people [AndroUser2 is me].

![screenshot_2017-01-16-18-45-58](https://cloud.githubusercontent.com/assets/13619077/21984180/e99c5ae6-dc1e-11e6-95a3-d5beb18a653b.png)

**Comment by armani316** [comment] 2017-01-16 13:12
@ShahadatRD Thanks for the update. I would remove the screenshot if I were you, just to be on the safe side :) What they're saying here is different from what I was told last week. I guess we'll never know for sure... 

Their application signup had been closed for months due to staff shortages. When they reopened, I assumed they hired more people.

**Comment by ShahadatRD** [comment] 2017-01-16 13:27
@armani316 don't worry i will never go for a invitation for that tracker. 

and, they are not well trained about maintaining a tracker smoothly...

**Comment by armani316** [comment] 2017-02-03 19:41
@kaso17 Invite sent :) Please confirm.

**Comment by kaso17** [comment] 2017-02-03 19:49
got it

**Comment by kaso17** [comment] 2017-02-06 18:28
added with 34e14a2a9984493f784ce4f6d5a842b840b1e9ae

**Comment by armani316** [comment] 2017-02-06 18:33
@kaso17 I think the latest release has the wrong version number. 0.7.1001 should probably be 0.8.1001.

**Comment by kaso17** [comment] 2017-02-06 18:40
The automatic build system takes care of the versioning. I'll leave the 0.8 bump for some bigger change.

**Comment by armani316** [comment] 2017-02-11 13:11
@kaso17 I think ADC needs an andmatch. Try searching for 'Hell or High Water 2016' in Jackett - lots of irrelevant or partially relevant results.

**Comment by kaso17** [comment] 2017-02-13 14:08
seem like they default to "latest releases" if they don't find anything.
fixed with 054a7f8c9c7d5c5d0b78f582f4342ea37bfaf57e

**Comment by RoloSoze** [comment] 2017-03-21 12:01
@kaso17 Could you please double check the category mapping? I believe Jackett omits some results.

E.g. Search for Office 2015 on ADC's website - 4 results vs. In Jackett - 3 results - The BD50 is missing. I've noticed this a number of times.

**Comment by kaso17** [comment] 2017-11-06 18:14
Can't reproduce the missing results issue, please provide the full torznab query URL

**Closed by kaso17** 2017-11-06 18:14 UTC
Labels: New tracker

**Comment by garfield69** [comment] 2019-10-20 23:29
https://asiandvdclub.org/ returning cloudflare 520 Web server is down
just me, or is site broken, gone or on a new domain?

**Comment by garfield69** [comment] 2019-11-02 06:05
currently getting cloudflare 522 Connection timed out
anyone have any news?
