### ISSUE TITLE
TorrentDay indexer failed

### ISSUE THREAD

**Issue by GazzaHazza** [Jackett/Jackett#3796] opened 2018-09-13 07:20 UTC
Tried adding Torrentday to my jacket and i get `Request to Jackett server failed` error and the logs show:

![screen shot 2018-09-13 at 8 17 13 am](https://user-images.githubusercontent.com/8090094/45472900-750d0900-b72d-11e8-9399-2ad745ae8b5c.png)
(sorry for superwide screenshot, the only way to get the full/most of the error in one go)

Using DSM for my OS.

**Jackett version**:  0.10.164.0
**Mono version** (if not using Windows):  5.8.0.108-11

-------------------------------

**Comment by Swainoo** [comment] 2018-09-13 13:35
Same issue.

Apparently https://td.getcrazy.me works for RSS but Jackett will need to be updated to include that link.

**Comment by garfield69** [comment] 2018-09-14 19:52
I've add those four links to the alternate site links list, which will be included in the next (pre)release when ever that gets published.

**Comment by GazzaHazza** [comment] 2018-09-16 16:43
https://github.com/Jackett/Jackett/commit/5d4e0c41d6db6efcd9617dd923b639fce9 - didnt fix my issue! I still get the same error so can this be reopened?

**Comment by Swainoo** [comment] 2018-09-16 17:11
Yep same error for me. I have noticed that the .it address is still present when trying to configure Jackett.

**Comment by rtho782** [comment] 2018-09-16 17:40
Same for me, it won't let me add the indexer or get to the settings so I can't change the domain.

**Comment by garfield69** [comment] 2018-09-16 20:13
the original OP's error looks similar to #3731 
Please post the output of `csharp -e 'Console.WriteLine (new System.Net.WebClient ().DownloadString ("https://www.howsmyssl.com/").IndexOf ("1.2"))'`

**Comment by Swainoo** [comment] 2018-09-17 02:38
> the original OP's error looks similar to #3731
> Please post the output of `csharp -e 'Console.WriteLine (new System.Net.WebClient ().DownloadString ("https://www.howsmyssl.com/").IndexOf ("1.2"))'`

I cant find any string related to that in the logs.

However what I can tell you is that I am able to setup Jackett with no issues while on a VPN outside of the UK.

I think the issue is simply the torrentday.it address, it seems like Jackett isn't taking into consideration the alternate links and is just relying on the main .it

**Comment by garfield69** [comment] 2018-09-17 02:45
Ah, 
I believe you are under the impression that the alternate links is a list where Jackett automatically picks one when the primary link fails.
But this is not the case. 

you choose which alternate link you want to use to replace the default link by using your jackett dashboard and editing the indexer's config. 

And the request for the output of the csharp is performed by you opening a terminal and pasting the command ;-)

**Comment by garfield69** [comment] 2018-09-17 02:47
@GazzaHazza  Please post the output of `csharp -e 'Console.WriteLine (new System.Net.WebClient ().DownloadString ("https://www.howsmyssl.com/").IndexOf ("1.2"))'`

**Comment by Swainoo** [comment] 2018-09-17 03:06
> Ah,
> I believe you are under the impression that the alternate links is a list where Jackett automatically picks one when the primary link fails.
> But this is not the case.
> 
> you choose which alternate link you want to use to replace the default link by using your jackett dashboard and editing the indexer's config.
> 
> And the request for the output of the csharp is performed by you opening a terminal and pasting the command ;-)

I understand. The issue I and others are facing is that once our ISP blocked the .it domain, we are unable to edit the indexer config from the Jackett dashboard, we get the error "Request to Jackett server failed".

Then even if delete the the indexer from jackett and attempt to re-add it, you get the same error.

Now I have managed to fix the issue by doing this;

1) Loading up a VPN and adding torrentday in the jacket dashboard
2) Changing the Site Link to https://td.getcrazy.me/ and finishing the config
3) Now the issue is resolved and with or without the VPN i'm able to edit the config and the test button gives a positive result.

Unfortunately as i've now resolved the issue for myself I don't know if the output would be of any use......also the command isn't working, i get "'csharp' is not recognized as an internal or external command, operable program or batch file." Likely because this is recent fresh Windows OS which probably doesn't have the correct frameworks installed to get a result :(

**Comment by garfield69** [comment] 2018-09-17 03:15
@Swainoo  thanks for the feedback. 
Maybe this is something @kaso17  and @flightlevel  can look at, because this will require some deep level c# coding changes to sort out this catch 22 situation.
as for the csharp output request,  the request was directed at the OP since they are running a linux system.
as a windows user you and I don't get the *OpenSSL: wront_version_number* error that the OP reported in his first post.

**Comment by garfield69** [comment] 2018-09-17 03:28
just thought of a manual circumvention that might allow you to bypass the catch22 you are currently in.
1. first you will need to shutdown your Jackett service or exit your jackettConsole task.
2. Then access your jackett/*Indexers* folder, and with a plain text editor open the *torrentday.json* file 
3. and edit the *value* under the *site link* near the top and replace the address with one of the alternate links that you think works in your region.
```json
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://torrentday.com/"
  },
```
4. save and startup Jackett again.

**Comment by GazzaHazza** [comment] 2018-09-17 08:26
@garfield69  - within DSM do so you know how to do this?

**Comment by garfield69** [comment] 2018-09-17 08:35
Is your dms a linux flavour? How did you install jackett?

**Comment by GazzaHazza** [comment] 2018-09-17 08:37
Not 100% what flavour it is! Sorry i'm not helping much! 

Installed via package manager

**Comment by garfield69** [comment] 2018-09-17 08:43
So you are using a gui for everything or can you open a terminal for command line control?

**Comment by GazzaHazza** [comment] 2018-09-17 08:43
GUI for everything.

**Comment by garfield69** [comment] 2018-09-17 08:54
Do you have an app search function, can you find *terminal* ?

**Comment by GazzaHazza** [comment] 2018-09-17 09:31
I can ssh into the server but not sure what now

**Comment by garfield69** [comment] 2018-09-17 09:38
Try pasting the following at the command prompt and see what you get back:
`csharp -e 'Console.WriteLine (new System.Net.WebClient ().DownloadString ("https://www.howsmyssl.com/").IndexOf ("1.2"))'`

**Comment by GazzaHazza** [comment] 2018-09-17 09:39
It doesnt recognise the `csharp` command.

**Comment by kaso17** [comment] 2018-09-17 13:51
Changed the default URL to https://td.getcrazy.me/ via 1325fc6391291636bc6d02e99d720f7c69d9dcee 

The issue with the default site links is tracked in #1473

**Closed by kaso17** 2018-09-17 13:51 UTC
