### ISSUE TITLE
Demonoid indexer: No results found - Jackett 0.8.1039.0

### ISSUE THREAD

**Issue by kurankat** [Jackett/Jackett#3194] opened 2018-06-02 23:50 UTC
After upgrading to version 0.8.1039, Demonoid Indexer is not returning any results. 

**Jackett version**:  0.8.1039
**Mono version** (if not using Windows):  5.12.0.226
Other info: Using Linuxserver's Jackett Docker container image

-------------------------------
[Jackett-logs-2018-06-03.log](https://github.com/Jackett/Jackett/files/2065510/Jackett-logs-2018-06-03.log)

**Comment by Samsonait** [comment] 2018-06-03 06:51
+1 this, still having this issue.

OP: https://github.com/Jackett/Jackett/issues/3141

**Comment by flightlevel** [comment] 2018-06-03 11:33
Duplicate of #3141

**Closed by flightlevel** 2018-06-03 11:33 UTC
