### ISSUE TITLE
nebulance: Episode is not found when searching via Sonarr using NEB indexer

### ISSUE THREAD

**Issue by adamwinn** [Jackett/Jackett#6413] opened 2019-11-22 04:14 UTC
I have the show "Pardon the Interruption" set up in Sonarr.  No episodes are found on the tracker NEB, but are found on other trackers.  If I do a manual search in Jackett for "Pardon the Interruption 2019 11 21", results are found on NEB.  I dont know if Sonarr is passing the wrong info to Jackett or what.  Sonarr finds the 2019-11-21 episode on MTV and IPT but not NEB.

(At the bottom of your Jackett Dashboard page) **Jackett version**:  Jackett Version 0.12.1000.0
-------------------------------

sonarr:
```
19-11-21 21:02:54.8|Info|NzbSearchService|Searching 1 indexers for [Pardon the Interruption : 2019-11-21]
19-11-21 21:02:54.8|Debug|Torznab|Downloading Feed http://172.17.0.1:9117/api/v2.0/indexers/transmithenet/results/torznab/api?t=tvsearch&cat=5000,5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Pardon%20the%20Interruption&season=2019&ep=11/21
19-11-21 21:02:55.8|Debug|NzbSearchService|Total of 0 reports were found for [Pardon the Interruption : 2019-11-21] from 1 indexers
19-11-21 21:02:55.8|Debug|NzbSearchService|Setting last search time to: 11/22/2019 4:02:55 AM
19-11-21 21:02:55.8|Info|DownloadDecisionMaker|No results found
19-11-21 21:02:55.8|Debug|Api|[GET] /api/v3/release?episodeId=56292: 200.OK (1077 ms)
```

Jackett:
```
2019-11-21 21:03:20.0956 Debug Connection id "0HLRBEGSQOOCT" accepted.
2019-11-21 21:03:20.0956 Debug Connection id "0HLRBEGSQOOCT" started.
2019-11-21 21:03:20.0965 Info Request starting HTTP/1.1 GET http://172.17.0.1:9117/api/v2.0/indexers/transmithenet/results/torznab/api?t=tvsearch&cat=5000,5030,5040&extended=1&apikey=xxxxx&offset=0&limit=100&q=Pardon%20the%20Interruption&season=2019&ep=11/21
2019-11-21 21:03:20.0965 Debug Request is continuing in applying rules. Current url is http://172.17.0.1:9117/api/v2.0/indexers/transmithenet/results/torznab/api?t=tvsearch&cat=5000,5030,5040&extended=1&apikey=xxxxx&offset=0&limit=100&q=Pardon%20the%20Interruption&season=2019&ep=11/21
2019-11-21 21:03:20.0974 Debug Request is continuing in applying rules. Current url is http://172.17.0.1:9117/api/v2.0/indexers/transmithenet/results/torznab/api?t=tvsearch&cat=5000,5030,5040&extended=1&apikey=xxxxx&offset=0&limit=100&q=Pardon%20the%20Interruption&season=2019&ep=11/21
2019-11-21 21:03:20.0974 Debug Request is continuing in applying rules. Current url is http://172.17.0.1:9117/api/v2.0/indexers/transmithenet/results/torznab/api?t=tvsearch&cat=5000,5030,5040&extended=1&apikey=xxxxx&offset=0&limit=100&q=Pardon%20the%20Interruption&season=2019&ep=11/21
2019-11-21 21:03:20.0974 Debug The request path /api/v2.0/indexers/transmithenet/results/torznab/api does not match a supported file type
2019-11-21 21:03:20.0988 Debug AuthenticationScheme: Cookies was not authenticated.
2019-11-21 21:03:20.0988 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/transmithenet/results/torznab/api'
2019-11-21 21:03:20.0997 Debug Endpoint 'Jackett.Server.Controllers.ResultsController.Torznab (jackett)' with route pattern 'api/v2.0/indexers/{indexerId}/results/Torznab/{ignored?}' is valid for the request path '/api/v2.0/indexers/transmithenet/results/torznab/api'
2019-11-21 21:03:20.0997 Debug Request matched endpoint 'Jackett.Server.Controllers.ResultsController.Torznab (jackett)'
2019-11-21 21:03:20.1006 Info Executing endpoint 'Jackett.Server.Controllers.ResultsController.Torznab (jackett)'
2019-11-21 21:03:20.1006 Info Route matched with {action = "Torznab", controller = "Results"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Torznab(Jackett.Common.Models.DTO.TorznabRequest) on controller Jackett.Server.Controllers.ResultsController (jackett).
2019-11-21 21:03:20.1016 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2019-11-21 21:03:20.1016 Debug Execution plan of resource filters (in the following order): None
2019-11-21 21:03:20.1016 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresApiKey, Jackett.Server.Controllers.RequiresConfiguredIndexer, Jackett.Server.Controllers.RequiresValidQuery
2019-11-21 21:03:20.1028 Debug Execution plan of exception filters (in the following order): None
2019-11-21 21:03:20.1028 Debug Execution plan of result filters (in the following order): None
2019-11-21 21:03:20.1039 Debug Executing controller factory for controller Jackett.Server.Controllers.ResultsController (jackett)
2019-11-21 21:03:20.1044 Debug Executed controller factory for controller Jackett.Server.Controllers.ResultsController (jackett)
2019-11-21 21:03:20.1044 Debug Attempting to bind parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest' ...
2019-11-21 21:03:20.1054 Debug Attempting to bind parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest' using the name '' in request data ...
2019-11-21 21:03:20.1054 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.t' of type 'System.String' using the name 't' in request data ...
2019-11-21 21:03:20.1054 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.t' of type 'System.String'.
2019-11-21 21:03:20.1066 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.q' of type 'System.String' using the name 'q' in request data ...
2019-11-21 21:03:20.1066 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.q' of type 'System.String'.
2019-11-21 21:03:20.1171 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.cat' of type 'System.String' using the name 'cat' in request data ...
2019-11-21 21:03:20.1175 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.cat' of type 'System.String'.
2019-11-21 21:03:20.1175 Debug Could not find a value in the request with name 'imdbid' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.imdbid' of type 'System.String'.
2019-11-21 21:03:20.1175 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.imdbid' of type 'System.String'.
2019-11-21 21:03:20.1188 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.extended' of type 'System.String' using the name 'extended' in request data ...
2019-11-21 21:03:20.1188 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.extended' of type 'System.String'.
2019-11-21 21:03:20.1212 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.limit' of type 'System.String' using the name 'limit' in request data ...
2019-11-21 21:03:20.1216 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.limit' of type 'System.String'.
2019-11-21 21:03:20.1216 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.offset' of type 'System.String' using the name 'offset' in request data ...
2019-11-21 21:03:20.1216 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.offset' of type 'System.String'.
2019-11-21 21:03:20.1216 Debug Could not find a value in the request with name 'rid' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.rid' of type 'System.String'.
2019-11-21 21:03:20.1216 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.rid' of type 'System.String'.
2019-11-21 21:03:20.1216 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.season' of type 'System.String' using the name 'season' in request data ...
2019-11-21 21:03:20.1226 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.season' of type 'System.String'.
2019-11-21 21:03:20.1226 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.ep' of type 'System.String' using the name 'ep' in request data ...
2019-11-21 21:03:20.1226 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.ep' of type 'System.String'.
2019-11-21 21:03:20.1226 Debug Could not find a value in the request with name 'album' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.album' of type 'System.String'.
2019-11-21 21:03:20.1226 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.album' of type 'System.String'.
2019-11-21 21:03:20.1235 Debug Could not find a value in the request with name 'artist' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.artist' of type 'System.String'.
2019-11-21 21:03:20.1235 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.artist' of type 'System.String'.
2019-11-21 21:03:20.1235 Debug Could not find a value in the request with name 'label' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.label' of type 'System.String'.
2019-11-21 21:03:20.1235 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.label' of type 'System.String'.
2019-11-21 21:03:20.1235 Debug Could not find a value in the request with name 'track' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.track' of type 'System.String'.
2019-11-21 21:03:20.1235 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.track' of type 'System.String'.
2019-11-21 21:03:20.1245 Debug Could not find a value in the request with name 'year' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.year' of type 'System.String'.
2019-11-21 21:03:20.1245 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.year' of type 'System.String'.
2019-11-21 21:03:20.1245 Debug Could not find a value in the request with name 'genre' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.genre' of type 'System.String'.
2019-11-21 21:03:20.1245 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.genre' of type 'System.String'.
2019-11-21 21:03:20.1245 Debug Could not find a value in the request with name 'configured' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.configured' of type 'System.String'.
2019-11-21 21:03:20.1245 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.configured' of type 'System.String'.
2019-11-21 21:03:20.1255 Debug Done attempting to bind parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest'.
2019-11-21 21:03:20.1255 Debug Done attempting to bind parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest'.
2019-11-21 21:03:20.1255 Debug Attempting to validate the bound parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest' ...
2019-11-21 21:03:20.1255 Debug Done attempting to validate the bound parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest'.
2019-11-21 21:03:20.1266 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://nebulance.io/torrents.php?action=basic&order_by=time&order_way=desc&search_type=0&taglist=&tags_type=0)
```

I noticed the NEB url string is `https://nebulance.io/torrents.php?action=basic&order_by=time&order_way=desc&search_type=0&taglist=&tags_type=0` and I saw when I used IPT, it had `https://iptorrents.com/t?q=Pardon+the+Interruption+2019.11.21&23=&24=&25=&65=&22=&5=&99=&55=&26=)`.  So it's almost like when searching via NEB, the query string (show and episode) is missing

![image](https://user-images.githubusercontent.com/3028964/69397654-52b53a80-0ca4-11ea-8940-e1f772eef615.png)

![image](https://user-images.githubusercontent.com/3028964/69397680-70829f80-0ca4-11ea-84d4-aefdf5b0edc3.png)

**Comment by garfield69** [comment] 2019-11-22 05:57
the c# developers that have maintained this c# indexer in the past are no longer available. (flightlevel has left github, and NathanNZ has not  contributed for some time).
we are going to need a c# volunteer who has an a/c on nebulance to help with this one.
I can manage simple changes, but this indexer is far too complex for me and I don't have a clue what is going on.

**Comment by ThatNerdyPikachu** [comment] 2019-11-25 02:35
https://github.com/Jackett/Jackett/blob/d4e776e23a363516df5dde0d73f9a51afea882dc/src/Jackett.Common/Indexers/TransmitheNet.cs#L90

Am on mobile at the moment, but I would try removing the conditional around this, so this is always the case, to see where we get with Sonarr.

**Comment by ThatNerdyPikachu** [comment] 2019-11-25 02:41
@adamwinn Do other shows, specifically non-daily shows, work with NEB and Sonarr?

**Comment by adamwinn** [comment] 2019-11-25 17:50
@ThatNerdyPikachu   Here's what I've found after more testing:

Standard format - All were found
Survivor, South Park, Real Time with Bill Maher, Last Week Tonight

Daily format - None were found
The Daily Show, The Late Show with Stephen Colbert, Pardon the Interruption

So it seems there's an issue with daily format shows and NEB and Sonarr

**Comment by garfield69** [comment] 2019-11-28 19:43
jackett 0.12.1041

**Comment by adamwinn** [comment] 2019-11-30 03:18
Unfortunately, this fix didn't work. The URL that Jackett says it's fetching is still `https://nebulance.io/torrents.php?action=basic&order_by=time&order_way=desc&search_type=0&taglist=&tags_type=0`

Jackett Version `0.12.1042.0`

**Comment by garfield69** [comment] 2019-11-30 03:25
Well you wrote the code... did you not test it before submitting the PR?
I suppose now you want to reverse it?

**Comment by adamwinn** [comment] 2019-11-30 03:27
No, I didn't.  I dont have a box with .net on it.  I did what @ThatNerdyPikachu said to do

**Comment by ThatNerdyPikachu** [comment] 2019-12-01 18:57
I didn't say that this would work -- I said we can use it to debug and test, see where we're getting.

> but I would try removing the conditional around this, so this is always the case, **to see where we get with Sonarr**.

Anyways, I have an account now, might take a crack at fixing this, no promises though as I really don't watch any shows other than standard ones.

**Comment by RoloSoze** [comment] 2020-09-30 23:05
@ngosang One last Nebulance issue :)

**Comment by EvanGrote** [comment] 2020-11-03 20:24
Not sure if this warrants a new issue or not, but I'm seeing issues using jackett with Nebulance which I believe are caused by sanitizing search queries that should not be sanitized.

I have Bob's Burgers set up to be tracked by sonarr using Nebulance via jackett as an indexer, but I have not been pulling in new episodes lately and I believe this is being caused by the search logic implemented in jackett. ([search parameter code link](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Nebulance.cs#L92-L98))
When searching on Nebulance, I receive results from the torrents.php page when including an apostrophe in my search text (`Bob's Burgers`) but I do not receive results when not including an apostrophe (`Bobs Burgers`):
* [search with apostrophe](https://nebulance.io/torrents.php?action=basic&order_by=time&order_way=desc&searchtext=bob%27s+burgers)
* [search without apostrophe](https://nebulance.io/torrents.php?action=basic&order_by=time&order_way=desc&searchtext=bobs+burgers)

I also tested this by performing manual searches on Nebulance via the jackett UI:
![manualSearchResults](https://user-images.githubusercontent.com/9055987/98036571-e01f6b00-1ddf-11eb-9515-52827b604dd3.png)

**Comment by JamesDAdams** [comment] 2021-01-20 19:52
@ngosang For resolve the probleme with the apostroph, this option is a good idea for everyone 

![image](https://user-images.githubusercontent.com/20860324/105227294-689ce480-5b61-11eb-84bf-c30141b545a7.png)

**Comment by ngosang** [comment] 2021-01-31 12:23
I did several tests:

* Saturday Night Live S46E10 => OK
* Pardon the Interruption 2020.10.16 => Fixed in #10980
* Bob's Burgers S11E10 => Not working in Sonarr because it's sending "Bobs Burgers S11E10". We can't fix that.

**Comment by ilike2burnthing** [comment] 2021-02-01 05:35
[v0.17.437](https://github.com/Jackett/Jackett/releases/tag/v0.17.437)

**Comment by Neoakb** [comment] 2023-02-26 04:01
Sonarr Version 3.0.9.1549
Jackett Version v0.20.3340

Apostrophes are not working on Nebulance. If I manual search in Jackett with Bob's Burgers the search populates, but it appears that the rawsearch isn't working. I don't see an ability to enable it when I hit the Nebulance indexer setting wrench.

**Comment by ilike2burnthing** [comment] 2023-02-26 04:31
`SupportsRawSearch` was never added to Nebulance. Have you tested using `'`, `:`, and other punctuation on their API (not the site)?

**Comment by Neoakb** [comment] 2023-02-26 05:14
![image](https://user-images.githubusercontent.com/6175742/221393613-62dccab7-e7da-40ce-bbcf-9019c76de572.png)


![image](https://user-images.githubusercontent.com/6175742/221393623-d1e80d5f-ed23-4afc-b3ae-0b4a8c557a7c.png)

**Comment by Neoakb** [comment] 2023-02-26 05:15
Sonarr is providing "Bobs Burgers" I guess, I don't know how to check

**Comment by ilike2burnthing** [comment] 2023-02-26 05:46
@garfield69 can you check?

**Comment by garfield69** [comment] 2023-02-26 05:53
sorry, what is it you want me to check?

**Comment by ilike2burnthing** [comment] 2023-02-26 06:04
Whether the indexer is suitable to use with `SupportsRawSearch`. Basically just see if you can search with punctuation and accents (assuming they actually have anything beyond `.`, `-`, and `'`) and still get accurate result.

The ones I think most likely to screw anything up would be `?` and `:`.

**Comment by garfield69** [comment] 2023-02-26 06:36
ok. the indexer already replaces dot and dash with percent in the name search 
https://github.com/Jackett/Jackett/blob/c0dbf39cf63df97c613b9fb6214059c7e6ae3516/src/Jackett.Common/Indexers/NebulanceAPI.cs#L163
so that would need to be bypassed if rawsearch was enabled

and while the search uses the show name, the returned results are the torrent filename so that might complicate things?

anyway, I searched for `Star Trek: Picard - S03E02` and got 5 results
searched for `WHAT / IF - S01` and got the 5 results
searched for `Soredemo Ai wo Chikaimasu ka? - S01` and got a result

so it seems the api can support rawsearch and we would need to alter the code to stop it replacing dots and dashes in that option was enabled.

**Comment by garfield69** [comment] 2023-02-26 07:10
Oh, I don't understand. I've not been involved in the supportsrawsearch development.
So all the indexers that have supportsRawSearch have it as a mandatory torznab capability.
So its not an option in the indexer config that the user can switched on.
So what do I do about that replace that's in the code at L163, take out the dot dash underscore and just replace the space with percent?
Or is there a torznab parm that indicates rawsearch and I have to check if that is in the query and then only replace the space with percent in that case? Or even leave the space unreplaced?

**Comment by garfield69** [comment] 2023-02-26 09:13
I've done some testing with Sonarr vs Jackett manual search with L163 left as is, and just adding the supportsRawSearch torznab capability.
I seem to be able to get the same results using both apps looking for `what / if S01` , `Bob's Burgers S13E12` , `Pardon the Interruption - 2020-07-22`  and `Star Trek: Picard-S03E02` so I'm calling it good and merging my commit.

**Closed by garfield69** 2023-02-26 09:13 UTC
Labels: Needs C#

**Comment by garfield69** [comment] 2023-02-27 06:03
v0.20.3392

**Comment by EvanGrote** [comment] 2023-02-27 16:48
My apologies if this is a bad question but I'm unfamiliar with the "supportsRawSearch torznab capability". I'm currently running jackett `v0.20.3392` and sonarr `3.0.9.1549` but I'm still not seeing results from nebulance when manually searching for Bob's Burgers episodes. Do I need to enable anything in jackett or sonarr or is this a wholly "behind the curtain" change?

In my jackett container logs I'm seeing queries for `Bobs Burger S13E12` (rather than `Bob's Burger S13E12`) coming when manually searching from sonarr. When searching in Nebulance `Bobs Burger S13E12` returns 0 results whereas `Bob's Burger S13E12` returns 2 results.

**Comment by EvanGrote** [comment] 2023-02-27 17:07
That did the trick. Thanks!
