### ISSUE TITLE
Crash on Socket Exception

### ISSUE THREAD

**Issue by Megagator** [Jackett/Jackett#252] opened 2016-02-19 22:40 UTC
Running on v. 0.6.45.0
with unRAID docker: https://github.com/sdesbure/arch-jackett

```
02-19 21:49:52 Error Unhandled exception: InnerException = System.Net.Sockets.SocketException: The socket has been shut down
at System.Net.Sockets.Socket.Send (System.Byte[] buf, Int32 offset, Int32 size, SocketFlags flags) [0x0005c] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/mcs/class/System/System.Net.Sockets/Socket.cs:1841 
at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, Int32 offset, Int32 size) [0x0006e] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/mcs/class/System/System.Net.Sockets/NetworkStream.cs:415 
HelpLink = 
HResult = -2146233087
Message = Write failure
Source = mscorlib
StackTrace = at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, Int32 offset, Int32 size) [0x0008e] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/mcs/class/System/System.Net.Sockets/NetworkStream.cs:418 
at System.Net.ResponseStream.EndWrite (IAsyncResult ares) [0x00081] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/mcs/class/System/System.Net/ResponseStream.cs:212 
at System.IO.Stream.m__8 (System.IO.Stream stream, IAsyncResult asyncResult) [0x00000] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/external/referencesource/mscorlib/system/io/stream.cs:729 
at (wrapper delegate-invoke) System.Func`3:invoke_TResult_T1_T2 (System.IO.Stream,System.IAsyncResult)
at System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[System.Threading.Tasks.VoidTaskResult,System.IO.Stream].Complete (System.IO.Stream thisRef, System.Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization) [0x00002] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/external/referencesource/mscorlib/system/threading/Tasks/FutureFactory.cs:1460 
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:201 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170 
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:124 
at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream+d__6.MoveNext () [0x00000] in :0 
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:201 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170 
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /home/buildozer/aports/testing/mono/src/mono-4.0.4/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:124 
at System.Web.Http.Owin.HttpMessageHandlerAdapter+d__20.MoveNext () [0x00000] in :0 
TargetSite = Void Throw()
Data = System.Collections.Generic.Dictionary`2[System.Object,System.Object] 
02-19 21:49:52 Error Unhandled exception url: http://10.0.1.5:9117/torznab/[provider]/api?t=tvsearch&cat=5030,5040&extended=1&apikey=[apikey]&offset=0&limit=100 
```

Edit: Just realized this build is over 3 months old, good chance this has since been resolved.

**Comment by Azerelat** [comment] 2016-02-24 18:06
Duplicate of #185

**Comment by flightlevel** [comment] 2016-02-27 10:13
@Megagator 
I'd give one of the other dockers a go https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=jackett&starCount=0

**Comment by flightlevel** [comment] 2017-01-21 04:45
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting

**Comment by flightlevel** [comment] 2017-01-21 04:45
This issue hasn't had activity for a while. If the issue still exists, please reopen and include full logs. https://github.com/Jackett/Jackett#troubleshooting

**Closed by flightlevel** 2017-01-21 04:45 UTC
Labels: Core
