### ISSUE TITLE
[kickasstorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#2504] opened 2018-01-29 21:13 UTC
Hi

my system is a Qnap
Jackett at the latest version (0.8.637.0)
mono version mono-5.4.1.6

since few days I've this error from this traker, here the log:
https://pastebin.com/xmJCqjZ0

Let me know if you need more data or tests

Tnx, Jo

**Comment by garfield69** [comment] 2018-01-29 21:51
Duplicate of #2280

**Closed by garfield69** 2018-01-29 21:51 UTC
Labels: Duplicate
