### ISSUE TITLE
[rutracker-ru] (testing) Test search in RuTracker.RU => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by nuttapillar** [Jackett/Jackett#15764] opened 2024-12-23 06:37 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-12-23 16:51:02	Info	Using HTTP Client: HttpWebClient2
2024-12-23 16:51:02	Info	Using FlareSolverr: http://localhost:8191
2024-12-23 16:51:02	Info	Using proxy: Disabled
2024-12-23 16:51:02	Info	App config/log directory: C:\ProgramData\Jackett
2024-12-23 16:51:02	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2024-12-23 16:51:02	Info	Running in Docker: No
2024-12-23 16:51:02	Info	Jackett variant: CoreWindows
2024-12-23 16:51:02	Info	OS version: Microsoft Windows NT 10.0.22631.0 (64bit OS)
2024-12-23 16:51:02	Info	Environment version: 8.0.11 (C:\ProgramData\Jackett\)
2024-12-23 16:51:01	Info	Starting Jackett v0.22.1111
```

### Description

I try testing this search site in the Jackett

### Logged Error Messages

```text
System.Exception: Test search in RuTracker.RU => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.22.1111.0] System.Exception: Test search in RuTracker.RU => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 332
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment] 2024-12-23 06:41
The rutracker.ru web site has been down for at least a week, currently returning an HTTP 500 (Internal Server Error).
Closing as a duplicate of #7526

**Closed by garfield69** 2024-12-23 06:41 UTC
