### ISSUE TITLE
[blutopia] Exception (blutopia): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Parse error (Test)

### ISSUE THREAD

**Issue by endriu0** [Jackett/Jackett#3355] opened 2018-07-06 20:40 UTC
Blutopia not working - giving error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Parse error (Test) 

Log entry:

07-06 21:37:05 Debug Response: {
  "result": "error",
  "error": "Exception (blutopia): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Parse error",
  "stacktrace": "  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x0016c] in <e683e6fbb825451b9948c2019123f304>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x00072] in <e683e6fbb825451b9948c2019123f304>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x000c6] in <e683e6fbb825451b9948c2019123f304>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at Jackett.Controllers.IndexerApiController+<Test>d__12.MoveNext () [0x00134] in <b796a8126353416b84cc35441cf56ee9>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Threading.Tasks.TaskHelpersExtensions+<CastToObject>d__0.MoveNext () [0x0005b] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__17`1[TResult].MoveNext () [0x001a7] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Web.Http.Controllers.ApiControllerActionInvoker+<InvokeActionAsyncCore>d__1.MoveNext () [0x000ab] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__17`1[TResult].MoveNext () [0x001a7] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x00091] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x001ad] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__5.MoveNext () [0x00103] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x00091] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x001ad] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__5.MoveNext () [0x00103] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Web.Http.Controllers.ActionFilterResult+<ExecuteAsync>d__5.MoveNext () [0x001af] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Web.Http.Filters.AuthorizationFilterAttribute+<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext () [0x000f3] in <69abafc3d8434ab584330d77cc8d6da3>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__6.MoveNext () [0x00087] in <69abafc3d8434ab584330d77cc8d6da3>:0 ",
  "innerstacktrace": "  at Jackett.Common.Indexers.BaseWebIndexer.OnParseError (System.String results, System.Exception ex) [0x00066] in <e683e6fbb825451b9948c2019123f304>:0 \n  at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__29.MoveNext () [0x02667] in <e683e6fbb825451b9948c2019123f304>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 \n  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x000ab] in <e683e6fbb825451b9948c2019123f304>:0 "
} 
07-06 21:37:05 Info WebAPIRequestLogger SendAsync  
System.Web.Http.MessageHandlers: WebAPIRequestLogger SendAsync 
07-06 21:37:05 Info   Content-type='application/json; charset=utf-8', content-length=13414 
System.Web.Http.Request:   Content-type='application/json; charset=utf-8', content-length=13414
07-06 21:37:05 Info IndexerApiController Dispose  
System.Web.Http.Controllers: IndexerApiController Dispose 
07-06 21:37:05 Info IndexerApiController Dispose  
System.Web.Http.Controllers: IndexerApiController Dispose 

**Jackett version**:   0.8.1243.0
**Mono version** (if not using Windows): 5.12.0.233

-------------------------------

**Comment by endriu0** [comment] 2018-07-06 20:41
The attached is closed with more info needed. This one has debug info,

**Comment by HDVinnie** [comment] 2018-07-09 12:49
@flightlevel does the Blutopia test pass for you? I didn't think my PR fixed the mail underlying problem for this reported issue. Why I made note in the PR,

"This doesn't fix #3355 . Im not sure what the issue is. Maybe @kaso17 can check it out. I believe you still have a account there. If not let me know."

**Comment by thekogut** [comment] 2018-07-09 20:34
Chiming in here to keep track, as I'm having the issue as well.

**Comment by HDVinnie** [comment] 2018-07-10 12:37
Can this be reopened? @jackettbot @flightlevel @kaso17

**Comment by flightlevel** [comment] 2018-07-10 12:45
@HDVinnie not a member, so can't test, wouldn't think your change would have fixed it anyway

**Comment by flightlevel** [comment] 2018-07-10 12:47
Issue got closed because you had the text fix #3355 so github closes it automatically 
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by HDVinnie** [comment] 2018-07-10 13:07
@flightlevel if you have a email address let me know and I can invite you or you can email me at unit3d@protonmail.com

**Comment by kaso17** [comment] 2018-07-10 16:10
fixed via 471d494b3b8b3e4f1133033dcdec621d40baf682

**Closed by kaso17** 2018-07-10 16:10 UTC

**Comment by HDVinnie** [comment] 2018-07-10 17:59
cheers
