### ISSUE TITLE
[bb] Specified argument was out of the range of valid values. (Parameter 'index') (Config)

### ISSUE THREAD

**Issue by fejjj** [Jackett/Jackett#11230] opened 2021-03-03 23:01 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
4.5

**.Net Version**:
4.5

**Jackett Version**:
0.17.611

**Last Working Jackett Version**:
unknown

**Are you using a proxy or VPN?** [yes/no]
no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Added my login info to the bB tracker setup

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at AngleSharp.Common.ObjectExtensions.GetItemByIndex[T](IEnumerable`1 items, Int32 index)
   at AngleSharp.Dom.HtmlCollection`1.get_Item(Int32 index)
   at Jackett.Common.Indexers.BB.<>c__DisplayClass12_0.<ApplyConfiguration>b__0() in D:\a\1\s\src\Jackett.Common\Indexers\BB.cs:line 111
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 240
   at Jackett.Common.Indexers.BB.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\BB.cs:line 103
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment] 2021-03-04 02:15
@janot  are you able to use your bb indexer?

**Comment by fejjj** [comment] 2021-03-04 02:17
When I try to login I get this error and login fails.

**Comment by garfield69** [comment] 2021-03-04 02:47
@feffes  yes, I read your report. I'm asking @janot because he is the only one I know who has an account on bb, and I wanted to get a second report.

**Comment by garfield69** [comment] 2021-03-04 02:49
@feffes oops, sorry, wrong users, similar names.

@fejjj yes, I read your report. I'm asking @janot because he is the only one I know who has an account on bb, and I wanted to get a second report.

**Comment by janot** [comment] 2021-03-04 15:59
@garfield69 worked until i tried to delete and re-add configuration. now I'm getting same error

**Comment by garfield69** [comment] 2021-03-04 17:12
It would be helpful if either one of you could provide a full enhanced log so we have something to work with, as the stack trace provided by @fejjj is not enough data. see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Thanks.

**Comment by fejjj** [comment] 2021-03-04 17:14
I'll be able to later today.

**Comment by fejjj** [comment] 2021-03-04 20:49
[bB.log](https://github.com/Jackett/Jackett/files/6086540/bB.log)

**Comment by garfield69** [comment] 2021-03-04 23:43
Thanks.
The indexer is written in C# and I'm not a C# dev specialist. At first glance I cannot see anything obvious or simple so we are going to need @ngosang  or another C# dev that can make sense of this log compare to the code.

I take it you have used your browser to access BB and everything is looking normal on the site?

**Comment by fejjj** [comment] 2021-03-04 23:55
Yes, working normally in Chrome 88.0.4324.190

**Comment by katameru** [comment] 2021-03-09 10:28
Duplicate of https://github.com/Jackett/Jackett/issues/11002

**Comment by ilike2burnthing** [comment] 2021-03-11 13:30
@fejjj & @janot can you check if this has been resolved for you? See https://github.com/Jackett/Jackett/issues/11002#issuecomment-796553114

**Comment by janot** [comment] 2021-03-11 14:25
works for me

**Comment by fejjj** [comment] 2021-03-11 21:02
Works for me as well.

**Comment by ilike2burnthing** [comment] 2021-03-11 21:46
thanks

**Closed by ilike2burnthing** 2021-03-11 21:46 UTC
