### ISSUE TITLE
[Channelx] Exception (Channelx): Got redirected to another domain. Try changing the indexer URL to https://channelx.xyz/.: Parse error (Test)

### ISSUE THREAD

**Issue by lukewowo** [Jackett/Jackett#7162] opened 2020-02-09 14:58 UTC
ChannelX have changed their domain from .online to .xyz

**Comment by garfield69** [comment] 2020-02-09 21:33
update to jackett v0.12.1765
duplicate of #7150

**Closed by garfield69** 2020-02-09 21:33 UTC
