### ISSUE TITLE
[pterclub] Exception (pterclub): Relogin failed: Parse error (Test)

### ISSUE THREAD

**Issue by JayXon** [Jackett/Jackett#8710] opened 2020-05-19 08:32 UTC
### Environment

**OS**: windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] ?

**.Net Version**: ?

**Jackett Version**: 0.16.488.0

**Last Working Jackett Version**: ?

**Are you using a proxy or VPN?** no

### Description

1. Add pterclub indexer, enter username, password and captcha
2. test works for now
3. wait one day
4. test fails with this error, have to go to settings page to enter captcha every single day

### Logged Error Messages

```
2020-05-19 01:23:01.0471 Info CardigannIndexer (pterclub): Relogin required 
2020-05-19 01:23:01.2181 Error CardigannIndexer (pterclub): Found captcha during automatic login, aborting 
2020-05-19 01:23:01.2453 Error Error on 20200519012301 for PTerClub.txtSystem.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1361




 
2020-05-19 01:23:01.2577 Error Jackett.Common.IndexerException: Exception (pterclub): Relogin failed
 ---> System.Exception: Parse error
 ---> System.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1361
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 831
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1682
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 325
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 804
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 259
   at Jackett.Server.Controllers.IndexerApiController.Test() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26 Jackett.Common.IndexerException: Exception (pterclub): Relogin failed
 ---> System.Exception: Parse error
 ---> System.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1361
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 831
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1682
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 325
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 804
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 259
   at Jackett.Server.Controllers.IndexerApiController.Test() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26

```

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by Curtis-L** [comment] 2020-05-19 10:32
this is likely to be that your ip changed and pter found your ip and cookie don't match, so you cookie is invalid and you have to re-login, jackett can't do anything about it becasue jackett can't enter captcha code for you.

you should try to get a static ip or maybe pter changes their policy, it's not an jackett issue.

**Comment by JayXon** [comment] 2020-05-19 10:34
But I never have to enter any captcha in chrome

**Comment by Curtis-L** [comment] 2020-05-19 10:41
hmm this is weird, i set up jackett on my vps and i didn't need to re-login, i'll leave this issue to the professionals.

**Comment by RoloSoze** [comment] 2020-05-19 13:12
I raised this exact same point e few months ago regarding TorrentCCF: #6876 and I also have it with PTer. It's strange that I don't need to re-login with my browser but I do need to do so with Jackett every time my IP changes.

**Comment by RoloSoze** [comment] 2020-05-20 12:47
@garfield69 Any thoughts on why re-login upon IP change for the likes of PTer and TorrentCCF is only necessary in Jackett but not in the browsers?

**Comment by garfield69** [comment] 2020-05-20 19:33
Probably because Jackett is not a browser. Some additional environment signature that a browser provides is enough to satisfy the web site that this is the same session that accessed it last time, while the Jackett indexers attempt to access clearly did not meed the same criteria and was asked to login again.
But as to what that difference might be I have no idea, its a question best directed to a network specialist or someone who can analyse network packets and traces and can recognise what the web site is looking for when determining if a login is required.

**Comment by RoloSoze** [comment] 2020-05-20 19:53
@garfield69 Got it. Thanks for the clarification. I'll go ahead and close this issue then since there's nothing that can be done about it from our side.

**Comment by JayXon** [comment] 2020-05-21 02:15
I think I know why, in the login page, there's a setting to restrict cookies to current ip, and Jackett does not send that field and it default to yes.
![image](https://user-images.githubusercontent.com/1552641/82512936-66602300-9ac6-11ea-95c8-3a2bed88c724.png)

So adding `securelogin: no` to `login: inputs:` in `pterclub.yml` probably will fix this.
I just made the change locally, and I'll wait for the next time my ip changes and see if it works and I'll send a PR.

**Comment by garfield69** [comment] 2020-05-21 03:52
The default for the `securelogin` checkbox on this form is for it not to be ticked, therefore the value when posted will be `value=""`.
If that checkbox had `checked="checked"` or just had the attribute `checked` present, or if the user ticked the checkbox on the form, then `value="yes"` would be posted when the form is submitted.
So unless the takelogin.php code on this web site is incredibly badly written, `securelogin` will not be interpreted as being set to `yes` by not coding it on the indexer.
But if we wanted to have belt and braces for this site we could add a `securelogin: ""` although this seems overkill to me.

**Comment by JayXon** [comment] 2020-05-21 04:16
I noticed this because I saw the cookies in Chrome has `c_secure_login=bm9wZQ%3D%3D` while the cookie in Jackett has `c_secure_login=eWVhaA%3D%3D`, those are base64 encoded `nope` and `yeah`, and I've verified that after adding `securelogin: no` and relogin, the cookie in Jackett now has `c_secure_login=bm9wZQ%3D%3D`, and it doesn't ask me to relogin after my ip changed, so I think this is indeed the issue. So here's a PR: #8724

No idea why the default in html is also not sending `securelogin` though, maybe the website changed recently and broke it, and I logged in chrome before that change and the cookies never expire.

**Comment by garfield69** [comment] 2020-05-21 04:30
good work.
I will check the other sites that use the same web engine and explicitly code the  empty values.

**Comment by garfield69** [comment] 2020-05-21 07:00
Jackett 0.16.515

**Comment by RoloSoze** [comment] 2020-05-21 11:15
@JayXon @garfield69 Thank you both. The issue is solved for PTer, but TCCF still has the same issue #6876

**Comment by JayXon** [comment] 2020-05-21 17:41
@RoloSoze 189109f didn't change `torrentccf.yml`

**Comment by RoloSoze** [comment] 2020-05-21 17:46
> 
> 
> @RoloSoze [189109f](https://github.com/Jackett/Jackett/commit/189109f491dbc805fad22346f6f6b1de94c925ac) didn't change `torrentccf.yml`

Ah, that explains it.

**Comment by RoloSoze** [comment] 2020-05-21 17:49
@garfield69 Here's a list of all Chinese trackers currently supported by Jackett, just in case you need to double check whether you've missed anything:

- [ ] 52PT
- [ ] BeiTai
- [ ] BRObits
- [ ] BTSCHOOL
- [x] CCFBits
- [ ] CHDBits
- [ ] HaiDan
- [ ] HD4FANS
- [x] HDArea
- [x] HDChina
- [ ] HDDisk
- [ ] HDDolby
- [x] HDHome
- [ ] HDRoute
- [x] HDSky
- [x] HDStreet
- [ ] HDtime
- [ ] HDU 
- [ ] HDZone
- [x] KeepFRDS
- [x] LeagueHD
- [x] M-Team - TP
- [ ] MoeCat
- [x] Ourbits
- [x] OshenPT
- [x] PT99
- [x] PTMSG
- [x] PTerClub
- [x] PThome
- [x] PTSBAO
- [ ] SnowPT
- [x] SoulVoice
- [x] SpringSunday
- [x] TJUPT
- [ ] TLFBits
- [x] TorrentCCF
- [x] ToTheGlory
- [ ] U2
- [ ] YDYPT

@JayXon @Curtis-L Please let me know if I missed any.

**Closed** 2020-05-21 21:00 UTC
