### ISSUE TITLE
The Anilibria tracker does not search for titles with filtered out punctuation signs.

### ISSUE THREAD

**Issue by kekal** [Jackett/Jackett#10931] opened 2021-01-25 23:17 UTC
I don't know if this is expected behaviour, but it is different from, for example, Anidub.

### Sonarr generates a query (I cleaned it up to make it easier to read):
|Query|Human readable result&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |Result|
|-|------|-----------------|
|ht<span>tp://ds718:9117/api/v2.0/indexers/AniLibria/results?apikey=(removed)&Query=Kumo%20Desu%20ga%2C%20Nani%20ka&Tracker%5B%5D=AniLibria|Manual search for "Kumo Desu ga Nani ka" on AniLibria **with 0 results**.|{"Results":[],"Indexers":[{"ID":"AniLibria","Name":"AniLibria","Status":2,"Results":0,"Error":null}]}|

&nbsp;

### But if I add missed question mark manually, I will get the correct search:
|Query|Human readable result&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |Result|
|-|-|-|
|ht<span>tp://ds718:9117/api/v2.0/indexers/AniLibria/results?apikey=(removed)&Query=Kumo%20Desu%20ga%2C%20Nani%20ka%3F&Tracker%5B%5D=AniLibria|Manual search for "Kumo Desu ga Nani ka" on AniLibria **with 2 results**.|{"Results":[{"FirstSeen":"0001-01-01T00:00:00","Tracker":"AniLibria","TrackerId":"AniLibria","CategoryDesc":"TV/Anime","BlackholeLink":null,"Title":"Да, я паук, и что? / Kumo desu ga, Nani ka? 2021 [WEBRip 1080p HEVC] - 1-3","Guid":"https://www.anilibria.tv//upload/torrents/13579.torrent","Link":"http://ds718:9117/dl/AniLibria/?jackett_apikey=didhp6534xfctqcmt4d20wvou4bdl4w3&path=Q2ZESjhLUUtXRUtfMWN0SGt3QUNpQzExLXJqd0FvM1FDdFpLbUxtTVc1ZWYxRXRyS2E1TXdwVjRsaVdqcE0zR25lc1d5MXpYMTdFeUY2Mk5tT3IxX0VjaUpjX1V1RGU4TWkxeGFaS0hudVI3ZXRzVS1GTXlDRms3eWxlYU5DOHNfLXNqY0xMRE9KTzJ3bDQ5cWlvVWlqTGFUb1cyM3AyV0pOakg0ek0wVlZ6V3pDYy1EQXpvVGQ4bjFRanV5S3d2QUw2MGp3&file=%D0%94%D0%B0%2C+%D1%8F+%D0%BF%D0%B0%D1%83%D0%BA%2C+%D0%B8+%D1%87%D1%82%D0%BE%3F+_+Kumo+desu+ga%2C+Nani+ka%3F+2021+%5BWEBRip+1080p+HEVC%5D+-+1-3","Comments":"https://www.anilibria.tv//release/kumo-desu-ga-nani-ka.html","PublishDate":"2021-01-23T18:48:33+00:00","Category":[5070],"Size":893179656,"Files":null,"Grabs":1771,"Description":null,"RageID":null,"TVDBId":null,"Imdb":null,"TMDb":null,"Author":null,"BookTitle":null,"Seeders":91,"Peers":19,"BannerUrl":"https://static.anilibria.tv//upload/release/350x500/8871.jpg","InfoHash":null,"MagnetUri":null,"MinimumRatio":null,"MinimumSeedTime":null,"DownloadVolumeFactor":0.0,"UploadVolumeFactor":1.0,"Gain":75.69729229062796},{"FirstSeen":"0001-01-01T00:00:00","Tracker":"AniLibria","TrackerId":"AniLibria","CategoryDesc":"TV/Anime","BlackholeLink":null,"Title":"Да, я паук, и что? / Kumo desu ga, Nani ka? 2021 [WEBRip 1080p] - 1-3","Guid":"https://www.anilibria.tv//upload/torrents/13577.torrent","Link":"http://ds718:9117/dl/AniLibria/?jackett_apikey=didhp6534xfctqcmt4d20wvou4bdl4w3&path=Q2ZESjhLUUtXRUtfMWN0SGt3QUNpQzExLXJnalFFWmJCdlBkTVYyejY3WG96REw0azE5RmdjVXZ4Z044cDBTR0JUR3A2WW9lZlFZRkJiOUlTdXVpd3ZIZE5TR2E1bGpCMGlQSWtYdmMxdXc2TFRlYkRXUFd1N1NnV3ZfcWxCcER3eEVuTHpsS3pzSkoyeU5vRTRBV3FBTGYydTJfTlY4OFdvRDRpUXpTMDRZMEhIVXBIaDFLLW1xWG1idkloZE1ydFV5WE1R&file=%D0%94%D0%B0%2C+%D1%8F+%D0%BF%D0%B0%D1%83%D0%BA%2C+%D0%B8+%D1%87%D1%82%D0%BE%3F+_+Kumo+desu+ga%2C+Nani+ka%3F+2021+%5BWEBRip+1080p%5D+-+1-3","Comments":"https://www.anilibria.tv//release/kumo-desu-ga-nani-ka.html","PublishDate":"2021-01-23T18:09:00+00:00","Category":[5070],"Size":4424109224,"Files":null,"Grabs":1939,"Description":null,"RageID":null,"TVDBId":null,"Imdb":null,"TMDb":null,"Author":null,"BookTitle":null,"Seeders":96,"Peers":30,"BannerUrl":"https://static.anilibria.tv//upload/release/350x500/8871.jpg","InfoHash":null,"MagnetUri":null,"MinimumRatio":null,"MinimumSeedTime":null,"DownloadVolumeFactor":0.0,"UploadVolumeFactor":1.0,"Gain":395.5461881160736}],"Indexers":[{"ID":"AniLibria","Name":"AniLibria","Status":2,"Results":2,"Error":null}]}|

&nbsp;

### It should be emphasized that the log value and the actual manual query via Jackett are different:
![image](https://user-images.githubusercontent.com/13663141/105776634-9b841580-5f71-11eb-856e-95789ad596ee.png)
# ↓
![image](https://user-images.githubusercontent.com/13663141/105776848-003f7000-5f72-11eb-8f62-12c1dad6979b.png)

#### This exact search rule does not allow the Sonarr to search for titles.
The original problem looks like a Sonarr issue but seems this is a too literal approach to building a query. Search engines generally ignore punctuation.

Jackett Version 0.16.1819.0

**Comment by ilike2burnthing** [comment] 2021-01-26 00:13
This won't resolve your issue, but your Jackett is out of date - https://github.com/Jackett/Jackett/releases (current release at time of writing being v0.17.354)

**Comment by kekal** [comment] 2021-01-29 00:40
> This won't resolve your issue, but your Jackett is out of date - https://github.com/Jackett/Jackett/releases (current release at time of writing being v0.17.354)

Thanks but I'm waiting for https://github.com/Jackett/Jackett/issues/8962#issuecomment-753014318

**Comment by kekal** [comment] 2021-02-07 12:23
Hi,
Are there any updates?

**Comment by ilike2burnthing** [comment] 2021-02-07 14:51
@dm3ch you're currently working on Anilibria in #10979, could you have a look at this?

Or @XYZJR if you want to have a try?

Either way, comment here so the other person knows.

**Comment by XYZJR** [comment] 2021-02-08 12:00
I just did a manual search on master branch for indexer AniLibria, query "Kumo Desu ga, Nani ka?"

- The AniLibria indexer seems to use the unsanitized query, so it includes all characters as is.
- The url contains the question mark as %3F
- I get 2 results, both have the question mark in their title.
- The manual search log shows the sanitized query, which is not the one that AniLibria actually used to search with. Minor bug in my opinion.

Based on this, I think the problem is fixed, but I might be misunderstanding the question.

**Comment by ilike2burnthing** [comment] 2021-02-08 13:22
Thanks. Same result here.

Search for `Kumo Desu ga, Nani ka?`, get 2 results, same as https://api.anilibria.tv/v2/searchTitles?search=Kumo+Desu+ga%2C+Nani+ka%3F&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year

Search for `Kumo Desu ga, Nani ka` (no question mark), get 0 results, same as https://api.anilibria.tv/v2/searchTitles?search=Kumo+Desu+ga%2C+Nani+ka&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year

So the question mark is definitely being used, just encoded as `%3F` as @XYZJR said, just like the comma is encoded as `%2C`.

The info for the search term strips all punctuation, no matter what indexer you use (not sure why).

OK to close this issue?

**Comment by ilike2burnthing** [comment] 2021-02-08 20:54
Just realised something, how are you getting Sonarr to search for `Kumo Desu ga, Nani ka`? Sonarr only supports English titles, and therefore the series is `So I'm a Spider, So What?` (which won't find any results on Anilibiria).

The search URL is:
- http://127.0.0.1:9117/api/v2.0/indexers/AniLibria/results/torznab/api?t=search&cat=5070&extended=1&apikey=APIKEY&offset=0&limit=100&q=So%20Im%20a%20Spider%20So%20What+01
- https://api.anilibria.tv/v2//searchTitles?search=So+Im+a+Spider+So+What+01&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year

That also made me realise that the query in your OP is a manual search in Jackett, not from Sonarr.

**Comment by kekal** [comment] 2021-02-11 22:11
> Just realised something, how are you getting Sonarr to search for `Kumo Desu ga, Nani ka`? 

Maybe we have different Sonarrs?
Non-edited Sonarr log for the first episode:

```21-2-11 22:09:15.4|Debug|Torznab|Downloading Feed http://172.17.0.1:9117/api/v2.0/indexers/AniLibria/results/torznab/api?t=search&cat=5070,100001&extended=1&apikey=(removed)&offset=0&limit=100&q=Kumo%20desu%20ga%20Nani%20ka+01
21-2-11 22:09:15.4|Debug|Torznab|Downloading Feed http://172.17.0.1:9117/api/v2.0/indexers/Animedia/results/torznab/api?t=search&cat=5070,100001&extended=1&apikey=(removed)&offset=0&limit=100&q=Kumo%20desu%20ga%20Nani%20ka+01
21-2-11 22:09:17.9|Debug|Torznab|Downloading Feed http://172.17.0.1:9117/api/v2.0/indexers/noname-club/results/torznab/api?t=search&cat=5070&extended=1&apikey=(removed)&offset=0&limit=100&q=Kumo%20Desu%20ga%20Nanika+01

**Comment by ilike2burnthing** [comment] 2021-02-11 23:56
Huh, weird. I tried v2 and v3 and only get the single search, not sure what I'm missing in the settings. I should have recognised that behaviour though (https://github.com/Jackett/Jackett/issues/8962#issuecomment-752958576). Anyways, that's not the issue here.

What Jackett currently uses:
[Kumo+Desu+ga%2C+Nani+ka%3F](https://api.anilibria.tv/v2/searchTitles?search=Kumo+Desu+ga%2C+Nani+ka%3F&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year) gives 2 results in browser
[Kumo+Desu+ga%2C+Nani+ka](https://api.anilibria.tv/v2/searchTitles?search=Kumo+Desu+ga%2C+Nani+ka&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year) (Sonarr's search) gives 0 results in browser 
[Kumo+Desu+ga+Nani+ka%3F](https://api.anilibria.tv/v2/searchTitles?search=Kumo+Desu+ga+Nani+ka%3F&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year) gives 2 results in browser
[Kumo+Desu+ga+Nani+ka](https://api.anilibria.tv/v2/searchTitles?search=Kumo+Desu+ga+Nani+ka&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year) gives 2 results in browser

Replacing `+` with `%20` (space):
[Kumo%20Desu%20ga%2C%20Nani%20ka%3F](https://api.anilibria.tv/v2/searchTitles?search=Kumo%20Desu%20ga%2C%20Nani%20ka%3F&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year) gives 2 results in browser
[Kumo%20Desu%20ga%2C%20Nani%20ka](https://api.anilibria.tv/v2/searchTitles?search=Kumo%20Desu%20ga%2C%20Nani%20ka&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year) gives 2 results in browser
[Kumo%20Desu%20ga%20Nani%20ka%3F](https://api.anilibria.tv/v2/searchTitles?search=Kumo%20Desu%20ga%20Nani%20ka%3F&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year) gives 2 results in browser
[Kumo%20Desu%20ga%20Nani%20ka](https://api.anilibria.tv/v2/searchTitles?search=Kumo%20Desu%20ga%20Nani%20ka&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year) gives 2 results in browser

Using `Nanika` (one of Sonarr's searches) instead of `Nani ka` fails for all `+` variations, but works (2 results) for all `%20` variations. Thanks for this discovery @kekal.

So using spaces looks to be more flexible. @XYZJR / @dm3ch can either of you make this change? Thanks.

**Comment by dm3ch** [comment] 2021-02-12 02:11
@ilike2burnthing You requested change in the Anilibria indexer, but suddenly I didn't understood what exactly. Do you mean replacing + to space in title before search?

**Comment by ilike2burnthing** [comment] 2021-02-12 04:11
Yes please.

**Comment by dm3ch** [comment] 2021-02-16 15:41
@ilike2burnthing @kekal Please test https://github.com/Jackett/Jackett/pull/10979 for now it works fine for the show in example.

So I'm not sure If we actually need change proposed by @ilike2burnthing

**Comment by dm3ch** [comment] 2021-02-16 16:03
@ilike2burnthing I tried to understand why we get + instead of %20 in search parameter and found that it happens inside https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Utils/StringUtil.cs#L151

So it would be better to ask someone more familiar with code, why it acts that way

**Comment by ilike2burnthing** [comment] 2021-02-16 16:34
Thanks. `Kumo Desu ga, Nani ka` still fails however.

Given that `Kumo Desu ga Nani ka` (no comma) does work, perhaps the better approach is just to remove all punctuation (not sure if that would negatively affect other results)? Searches using `Nanika` instead of `Nani ka` will still fail, but at least we get something the first time round.

@ngosang can the `+` between keywords in the request URL be changed to `%20` for a single indexer?

**Comment by XYZJR** [comment] 2021-02-16 18:08
[Discussion on StackOverflow.](https://stackoverflow.com/a/47188851/7601691)

We could try if other indexers can handle `%20` and then move everything over to it. If not, we can write a new ToQueryString method in StringUtil that asks which one you want to use.

**Comment by dm3ch** [comment] 2021-02-16 18:52
> [Discussion on StackOverflow.](https://stackoverflow.com/a/47188851/7601691)
> 
> We could try if other indexers can handle `%20` and then move everything over to it. If not, we can write a new ToQueryString method in StringUtil that asks which one you want to use.

Maybe we can add a new argument (that would be + by default) to current implementation, to be able to control that per indexer

**Comment by dm3ch** [comment] 2021-02-16 19:09
@ilike2burnthing Workaround that issue.
Now `Kumo Desu ga, Nani ka` request works fine for me.

As far as i found at https://stackoverflow.com/questions/32484829/how-to-force-20-instead-of-in-system-net-webutility-urlencode space is encoded as + by system function.

**Comment by ilike2burnthing** [comment] 2021-02-16 20:30
Core changes are beyond my knowledgebase, so I'll leave ngosang to comment on that.

Fix is working, all variations are returning the same 2 results, although when searching for `Kumo Desu ga Nanika` (instead of `Nani ka`) the API returns those two results but Jackett doesn't pick them up (I'm assuming because the title doesn't match). Can we lose the title match (or whatever is causing that issue)?

Thanks @dm3ch and @XYZJR

**Comment by dm3ch** [comment] 2021-02-16 20:32
@ilike2burnthing This PR does not changes core. I just not using core function of forming URL params for search parameter

**Comment by ilike2burnthing** [comment] 2021-02-16 20:37
Oh sorry, I was talking about https://github.com/Jackett/Jackett/issues/10931#issuecomment-780020776 and https://github.com/Jackett/Jackett/issues/10931#issuecomment-780046513 in the first sentence. There rest is in reference to your PR.

**Comment by kekal** [comment] 2021-02-16 21:35
> @ilike2burnthing @kekal Please test #10979 for now it works fine for the show in example.
> 
> So I'm not sure If we actually need change proposed by @ilike2burnthing

@dm3ch , my use case based on docker, so I don't know how to run up the PR.

I want to test code without binaries, but I'm not familiar with mono and only have expertise in desktop applications.
Is there any small manual/wiki for setting up the dev environment to debug this project?
Code review on GitHub has no luck.

**Comment by ilike2burnthing** [comment] 2021-02-17 00:07
https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md#setting-up-your-environment

**Comment by dm3ch** [comment] 2021-02-20 20:35
> Core changes are beyond my knowledgebase, so I'll leave ngosang to comment on that.
> 
> Fix is working, all variations are returning the same 2 results, although when searching for `Kumo Desu ga Nanika` (instead of `Nani ka`) the API returns those two results but Jackett doesn't pick them up (I'm assuming because the title doesn't match). Can we lose the title match (or whatever is causing that issue)?
> 
> Thanks @dm3ch and @XYZJR

So yes we are loosing some results cause of https://github.com/Jackett/Jackett/pull/10979/files#diff-629a117a093f2b427c8cd810afcff7fcd666cf9963f2953ebd83ce548b451697R83 .
Without this filtering `Nanika` search would work, but suddenly I had some requests where api results wasn't relative, so that's why I have added this filtering.

As far as i understood `Nanika` case shouldn't be a blocker, cause as far as i understood official name is `Nani ka` and cause Sonarr when performs search trying both `Nani ka` and `Nanika`.

**Comment by ilike2burnthing** [comment] 2021-02-20 21:16
Ah ok, that's fine then. Will merge shortly. Thanks again!

**Closed** 2021-02-20 21:17 UTC
Labels: Needs C#

**Comment by ilike2burnthing** [comment] 2021-02-21 00:00
[v0.17.570](https://github.com/Jackett/Jackett/releases/tag/v0.17.570)

**Comment by kekal** [comment] 2021-02-25 23:33
Tested succesfully
![image](https://user-images.githubusercontent.com/13663141/109233396-800b6500-77d2-11eb-8c28-079acaec5469.png)

Jackett Version v0.17.584
