### ISSUE TITLE
Errors with Sonarr and Jackett after Jackett auto-update...

### ISSUE THREAD

**Issue by D3000A** [Jackett/Jackett#7343] opened 2020-02-27 03:16 UTC
Hello,
I have an issue with Sonarr after a recent Jackett update. Sonarr is now providing an error message: 
Indexers unavailable due to failures: Jacket - All

When viewing the log in Sonarr:
Message
Unable to connect to indexer: Torznab error detected: System.ArgumentNullException: Value cannot be null. (Parameter 'second')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Intersect[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Jackett.Common.Indexers.BaseIndexer.<>c__DisplayClass65_0.<FilterResults>b__0(ReleaseInfo result) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 268
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.EnumerablePartition`1.MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator(Int32 minIdx, Int32 maxIdx)+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at Jackett.Common.Services.CacheService.GetNewItemCount(IIndexer indexer, IEnumerable`1 releases) in d:\a\1\s\src\Jackett.Common\Services\CacheService.cs:line 60
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 378

Exception
NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: System.ArgumentNullException: Value cannot be null. (Parameter 'second')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Intersect[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Jackett.Common.Indexers.BaseIndexer.<>c__DisplayClass65_0.<FilterResults>b__0(ReleaseInfo result) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 268
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.EnumerablePartition`1.MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator(Int32 minIdx, Int32 maxIdx)+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at Jackett.Common.Services.CacheService.GetNewItemCount(IIndexer indexer, IEnumerable`1 releases) in d:\a\1\s\src\Jackett.Common\Services\CacheService.cs:line 60
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 378
   at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess(IndexerResponse indexerResponse) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:line 42
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 308
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 334

Log in Jackett:

Error | System.ArgumentNullException: Value cannot be null. (Parameter 'second')    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)    at System.Linq.Enumerable.Intersect[TSource](IEnumerable`1 first, IEnumerable`1 second)    at Jackett.Common.Indexers.BaseIndexer.<>c__DisplayClass65_0.<FilterResults>b__0(ReleaseInfo result) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 268    at System.Linq.Enumerable.WhereListIterator`1.MoveNext()    at System.Linq.Enumerable.EnumerablePartition`1.MoveNext()    at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()    at System.Linq.Set`1.UnionWith(IEnumerable`1 other)    at System.Linq.Enumerable.DistinctIterator`1.FillSet()    at System.Linq.Enumerable.DistinctIterator`1.ToArray()    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)    at System.Linq.OrderedEnumerable`1.GetEnumerator(Int32 minIdx, Int32 maxIdx)+MoveNext()    at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()    at Jackett.Common.Services.CacheService.GetNewItemCount(IIndexer indexer, IEnumerable`1 releases) in d:\a\1\s\src\Jackett.Common\Services\CacheService.cs:line 60    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 378
-- | --

How can this be fixed?  Everything was working fine before the update.... This is on a Windows 10 PC if that helps?

Thanks in advance

**Comment by thebadwolf79** [comment] 2020-02-27 03:33
Having the exact same issue with Jackett on Windows 10.

**Comment by ilike2burnthing** [comment] 2020-02-27 03:57
https://github.com/Jackett/Jackett/pull/7338

**Comment by D3000A** [comment] 2020-02-27 04:06
Just re-installed an earlier version and working again on the old version...

**Comment by cadatoiva** [comment] 2020-02-27 04:26
Duplicate of #7333

Fixed in #7338 and will be in an update soon

**Closed by cadatoiva** 2020-02-27 04:26 UTC
