### ISSUE TITLE
TorrentDay URL (tday.love) Can't Be Resolved

### ISSUE THREAD

**Issue by quixote23** [Jackett/Jackett#6909] opened 2020-01-10 22:37 UTC
Noticed TorrentDay wasn't working in Sonarr - tested in Jackett and received the error "Request to Jackett server failed". Tried removing and adding it back, same error. Looking further it appears the host tday.love cannot be resolved. Jackett Version 0.12.1494.0.

I can provide a log if needed but it just looks like TD updated their URLs and tday.love no longer exists.

**Comment by garfield69** [comment] 2020-01-10 23:38
duplicate of #6880 
fixed in Jackett pre-release 0.12.1525
a Full release is not due for a while yet.

**Closed by garfield69** 2020-01-10 23:38 UTC
