### ISSUE TITLE
Duplicated rows in YGGtorrent search

### ISSUE THREAD

**Issue by BartoX360** [Jackett/Jackett#13546] opened 2022-09-13 19:15 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://flaresolverr:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.1796-ls74)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.0.9 (64bit OS) (64bit process)
Environment version: 6.0.8 (/app/Jackett/)
Starting Jackett v0.20.1892
```

### Description

I'm running Jackett in Docker connected to YGGtorrent indexer, all the result when I make a search was duplicated.
I have tried another tracker and I don't have the problem.
If I make a search without query all the results were ok but when I put a query all results are duplicated.
See the screenshot for example.
Thanks in advance.
Bartox

### Logged Error Messages

```text
No error in log file
```

### Screenshots

![Capture d’écran 2022-09-13 211051](https://user-images.githubusercontent.com/10219349/189989401-404010b5-3811-479d-8efd-6fcdcae73acb.png)
![Capture d’écran 2022-09-13 211122](https://user-images.githubusercontent.com/10219349/189989406-f7c18468-c272-4f2c-b789-701abc65b931.png)

**Comment by garfield69** [comment] 2022-09-13 19:34
duplicate of #12850
explanation https://github.com/Jackett/Jackett/issues/12850#issuecomment-1015445197

**Closed by garfield69** 2022-09-13 19:34 UTC
