### ISSUE TITLE
[kickasstorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Daptonic** [Jackett/Jackett#2472] opened 2018-01-24 15:12 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.618.0
Mono version (if not using Windows):  

-------------------------------

Jan 24, 2018 07:11:09 AM | Error | {0}
-- | -- | --
Jan 24, 2018 07:11:09 AM | Info | Found 0 releases from KickAssTorrent

**Comment by garfield69** [comment] 2018-01-24 18:51
Duplicate of #2280

**Closed by garfield69** 2018-01-24 18:51 UTC
Labels: Duplicate
