### ISSUE TITLE
PTFiles and TreZzoR cookie issues

### ISSUE THREAD

**Issue by Smexhy** [Jackett/Jackett#14376] opened 2023-05-25 22:50 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://flaresolverr:8191	
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads	
Running in Docker: Yes (image build: v0.21.20-ls107)
File /etc/issue: Welcome to Alpine Linux 3.17	
Jackett variant: CoreLinuxMuslAmdx64	
OS version: Unix 5.15.0.72 (64bit OS) (64bit process)
Environment version: 6.0.16 (/app/Jackett/)
Starting Jackett v0.21.20
```

### Description

I am primarily using prowlarr, but I was told to contact you guys first. I have noticed that with those 2 indexers, every few hours / days, I need to periodically re-enter cookie for them to work properly. I also need to log in with the same IP that the jackett/prowlarr is on, to be able to use that cookie at all. Otherwise it wouldn't work, since they are checking if the cookie is being used with the same IP like the browser it was taken from, so unless you have access to a browser from that same IP, you are screwed. Same goes for both indexers, PTFiles and TreZzoR. I imagine they aren't as popular as other trackers, but they have it's specific use and it would be great to actually be able to use them without this much hassle.

They don't use any captcha or 2fa, just simple login form to get in.

If it's needed, I have invites ready for both, so this could be resolved with another approach than the cookie one which isn't really stable for these indexers.

### Logged Error Messages

```text
PTFiles: Unable to connect to indexer. Redirected to https://ptfiles.net/loginproc/index.php?ts=1685054847 from indexer request

TreZzoR: Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc.
```

**Comment by ilike2burnthing** [comment] 2023-05-25 23:27
Trezzor was shifted to cookies as a result of being unable to run multiple sessions - https://github.com/Jackett/Jackett/commit/2c890d2a1fcf276e7373dc1fe4415bc4c30f45d3. Unless there's a tracker setting which disables this limitation, there's not much we can do.

PTFiles was changed in https://github.com/Jackett/Jackett/commit/2c890d2a1fcf276e7373dc1fe4415bc4c30f45d3 but I'm not sure why. @garfield69?

**Comment by ilike2burnthing** [comment] 2023-05-26 00:23
Can you used a single specific Mullvad server so that the IP doesn't change?

**Comment by garfield69** [comment] 2023-05-26 02:57
>PTFiles was changed in 2c890d2 but I'm not sure why.

No idea, cant remember. Clearly the login method stopped working at that time and cookie was the way around.
Might be able to return to login method if some ones want to try.

**Comment by ilike2burnthing** [comment] 2023-05-26 04:24
PTFiles credentials login should work in Jackett's next release (~2hrs) and when Prowlarr's indexers are next merged from here.

**Comment by garfield69** [comment] 2023-05-26 06:01
v0.21.42

**Comment by ilike2burnthing** [comment] 2023-05-26 20:30
> The only alternative I see as mildly possible is giving user an option to choose to either use cookie or the login method

We do basically that for `GazelleTracker` indexers which use 2FA -

https://github.com/Jackett/Jackett/blob/abbf37060d13f582dc74da3dc52286391353968a/src/Jackett.Common/Models/IndexerConfig/Bespoke/ConfigurationDataGazelleTracker.cs#L26-L34

https://github.com/Jackett/Jackett/blob/abbf37060d13f582dc74da3dc52286391353968a/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs#L112-L121

However, as you can see that's written in C#, where we can take and use whichever is provided. To my knowledge, we can't do that with the current Cardigann YAML definitions. What we do have though, for several trackers, are separate credentials and cookie definitions, typically for 2FA.

> Could you link me commit with TreZzoR where this was changed? Noticed that you only linked ptfiles twice above.

Oh crap, my bad, I actually meant to link the issue (fixed above now). Here's the commit - https://github.com/Jackett/Jackett/commit/f17b9dbc215c1b308ba27c03e3dc38657949eda7.

> Also - PTFiles is currently having issue with their SSL certificate and website is not available with https so I can't test the change - only http works as of now. It was working yesterday, so I hope it's only temporary issue which will be solved soon.

That was fixed in https://github.com/Jackett/Jackett/commit/4944aef0392950367a2f92b2992b7f8e4e630411, so v0.21.42 currently works with HTTPS by trusting the certificate's thumbprint.

**Comment by ilike2burnthing** [comment] 2023-05-26 20:41
> I found some of the old trezzor's commit before the change to cookie style login and tried to just use the login form part in my custom definition, but it's not working for some reason.

Remove the `settings` block completely and change the `login` block to either of the following, restarting Jackett after saving any changes:

```yml
login:
  path: prihlasenie.php
  method: form
  form: form[action^="prihlasenie.php"]
  inputs:
    uid: "{{ .Config.username }}"
    pwd: "{{ .Config.password }}"
  error:
    - selector: div > font:contains("V pripade problemov kontaktujte")
  test:
    path: torrents.php
```

```yml
login:
  path: prihlasenie.php
  method: post
  inputs:
    uid: "{{ .Config.username }}"
    pwd: "{{ .Config.password }}"
  error:
    - selector: div > font:contains("V pripade problemov kontaktujte")
  test:
    path: torrents.php
```

If neither works, an invite will be the easiest option.

**Comment by IHateIssues** [comment] 2023-05-26 20:57
> > I found some of the old trezzor's commit before the change to cookie style login and tried to just use the login form part in my custom definition, but it's not working for some reason.
> 
> Remove the `settings` block completely and change the `login` block to either of the following, restarting Jackett after saving any changes:
> 
> ```yaml
> login:
>   path: prihlasenie.php
>   method: form
>   form: form[action^="prihlasenie.php"]
>   inputs:
>     uid: "{{ .Config.username }}"
>     pwd: "{{ .Config.password }}"
>   error:
>     - selector: div > font:contains("V pripade problemov kontaktujte")
>   test:
>     path: torrents.php
> ```
> 
>  ```yaml
> login:
>   path: prihlasenie.php
>   method: post
>   inputs:
>     uid: "{{ .Config.username }}"
>     pwd: "{{ .Config.password }}"
>   error:
>     - selector: div > font:contains("V pripade problemov kontaktujte")
>   test:
>     path: torrents.php
> ```
> 
> If neither works, an invite will be the easiest option.

yeah I managed to do that first one you posted (with settings part deleted) by copying the older version before the transition to cookie, but that didn't work, and the post method is giving the same error:

`Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc.`

By looking at the logs I see HTML page loaded with access error (as if I was accessing their site not logged in) - so something must have changed since the last time it worked, but couldn't figure it out, most obvious like login site, id of fields etc. is the same. I can shoot you an invite, but I think account would be better since they require phone number for registrations and I am not sure if they accept non czech / slovak phone numbers, never tried it and some people dont like giving phone numbers to random websites for obvious reasons. I have clean new unused account too though.


Also just a side note, pretty sure that error check isn't working as intended either, since once cookie expire after some time it's still showing that test passed, it just returns no results when searching. So I never really know when the cookie expire without manually checking, unlike other trackers where test reports right back that there is an issue.

**Comment by IHateIssues** [comment] 2023-05-26 21:36
I have account ready anytime, I know that the phone number verification sucks. Let me know if it's better that way, or if you want me to provide logs etc. instead, whichever suits you better. I have multiple accs and their rules are not so strict regarding accounts like on other trackers, so it shouldn't be a problem.

**Comment by ilike2burnthing** [comment] 2023-05-26 21:48
@IHateIssues sign out of the tracker's site, disable the indexer if configured with any automation software (e.g. Sonarr et al.), and then send your credentials to: `jacketttest [AT] gmail [DOT] com`

**Comment by IHateIssues** [comment] 2023-05-26 22:04
> @IHateIssues sign out of the tracker's site, disable the indexer if configured with any automation software (e.g. Sonarr et al.), and then send your credentials to: `jacketttest [AT] gmail [DOT] com`

sent, that specific account was never used or configured with anything before, so it might be used freely

**Closed** 2023-05-27 02:47 UTC
Labels: Needs Investigations

**Comment by ilike2burnthing** [comment] 2023-05-27 03:00
Thanks @IHateIssues, you can reset the password now.

Default indexer will use credentials; new separate indexer uses cookies.

Took the opportunity to update the indexer as well:
- updated categories
- can filter by freeleech (basically useless on that tracker, but hey)
- can search by year
- can sort and order results
- notes about the number of results and 3X results
- also return dead results
- title fixes, including improved Sonarr compatibility
- added description with trimmed but otherwise unedited title

If there are any issues or any further improvements you think could be added, let me know.

Available in Jackett in ~3hrs and in Prowlarr when they next merge indexers from here.

**Comment by garfield69** [comment] 2023-05-27 06:02
v0.21.52

**Comment by IHateIssues** [comment] 2023-05-27 09:32
> Thanks @IHateIssues, you can reset the password now.
> 
> Default indexer will use credentials; new separate indexer uses cookies.
> 
> Took the opportunity to update the indexer as well:
> 
> * updated categories
> * can filter by freeleech (basically useless on that tracker, but hey)
> * can search by year
> * can sort and order results
> * notes about the number of results and 3X results
> * also return dead results
> * title fixes, including improved Sonarr compatibility
> * added description with trimmed but otherwise unedited title
> 
> If there are any issues or any further improvements you think could be added, let me know.
> 
> Available in Jackett in ~3hrs and in Prowlarr when they next merge indexers from here.

Glad to hear, anytime you need to fix something woth trezzor feel free to use that account since it won’t be used, compatibility with jackett prowlarr and other ares takes the biggest priority for me since I wouldn’t be using otherwise.

From what I remember on prowlarr error reporting didn’t work well, so I didn’t really know when there was an issue with tracker, only when I tried to search manually and it returned no results. I will try the new updated definitions though, might have been fixed - or it’s just something with prowlarr, because I didn’t really test it with jackett fuy yet.

**Comment by ilike2burnthing** [comment] 2023-05-27 15:59
> From what I remember on prowlarr error reporting didn’t work well, so I didn’t really know when there was an issue with tracker, only when I tried to search manually and it returned no results.

Oh yes, the login test path and selector was also updated, so this should be fixed as well, i.e. if it doesn't see the logout link, it knows you're not logged in, and will re-login on the credentials indexer (or just throw an error on the cookie indexer).

**Comment by ilike2burnthing** [comment] 2023-05-27 16:07
> Glad to hear, anytime you need to fix something woth trezzor feel free to use that account since it won’t be used

Are you fine with me adding the current credentials to my Jackett? It will be accessed about once a week (usually at the weekend) as a test to make sure no updates need to be made.

**Comment by IHateIssues** [comment] 2023-05-27 17:26
> > Glad to hear, anytime you need to fix something woth trezzor feel free to use that account since it won’t be used
> 
> Are you fine with me adding the current credentials to my Jackett? It will be accessed about once a week (usually at the weekend) as a test to make sure no updates need to be made.

That would be really cool, so we can always have it updated if needed :) so more than fine by me.
