### ISSUE TITLE
Newpct [req]: 

### ISSUE THREAD

**Issue by elvisaloha** [Jackett/Jackett#13062] opened 2022-03-18 11:30 UTC
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Newpct
- URL: https://www.newpct.net/
- Description: Movies and series
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: Public, spanish and English. Open again as newpct.net THANK UUUUU
```

**Comment by garfield69** [comment] 2022-03-18 18:47
this request is a duplicate of #12284
Use your Jackett dashboard add-indexer button and you should find NewPCT.me, assuming you have a version of Jackett that is at or newer than v0.18.729

**Closed by garfield69** 2022-03-18 18:47 UTC
