### ISSUE TITLE
[cpasbien] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Koxx3** [Jackett/Jackett#2720] opened 2018-03-15 17:22 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  Version 0.8.763.0
**Mono version** (if not using Windows):  N/A (docker)

-------------------------------

Cpasbien doesn't work anymore.
I tried many proxies, same result.

**Comment by garfield69** [comment] 2018-03-16 18:14
Duplicate of #2725 
read it for fix details.

**Closed by garfield69** 2018-03-16 18:14 UTC
