### ISSUE TITLE
Crash and start loop with v0.11.751

### ISSUE THREAD

**Issue by pbosch** [Jackett/Jackett#6069] opened 2019-09-30 19:52 UTC
Hi

Since the last update ( v0.11.751) Jackett is stuck in a start loop. The log of one start attempt is attached. I do use the aggregated indexer, but I don't think that's the issue here. I'm not very familiar with C#, but it seems to me that a configuration for a module is missing. I'm not sure if it got lost in the update, or if the update doesn't contain it. If you need any more information, just ask.

Kind regards

(At the bottom of your Jackett Dashboard page) **Jackett version**:   v0.11.751
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/3672982/log.txt)

**Comment by garfield69** [comment] 2019-09-30 22:35
duplicate of #5208

Auto update on Linux is broken for many people. 
You may want to Disable auto update, and do a manual update for any upgrades you want until this is resolved.

**Closed by garfield69** 2019-09-30 22:35 UTC

**Comment by garfield69** [comment] 2019-10-30 02:27
fix is available with stable jackett 0.12.898. but you will need to install manually and run the systemd install script anew.

1. open a terminal and shutdown the jackett service using `systemctl stop jackett.service`
2. download and extract the linux package that applies to your platform from https://github.com/Jackett/Jackett/releases/tag/v0.12.898
3. copy or move/replace all the files from the Jackett folder in the downloaded/extracted package to where ever you have previously put the jackett binaries. Typical locations are `/opt/Jackett` or `~/Jackett`
4. cd to your Jackett binary folder and install the service with `sudo ./install_service_systemd.sh` 
this will start the service (if it ran successfully)
5. access your jackett dashboard with your browser and untick the Disable auto Update check box and press the Apply Server Settings button.
