### ISSUE TITLE
[xwtorrents] Challenge detected but FlareSolverr is not configured (Config)

### ISSUE THREAD

**Issue by dRuEFFECT** [Jackett/Jackett#12239] opened 2021-08-31 01:14 UTC
### Environment

**OS**:
Unraid Version: 6.9.1

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
Version v0.18.632

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]
NO

### Description
Trying to add configuration for XtremeWrestlingTorrents, Jackett says there's a cloudflare challenge detected, but all tests have shown that there's no challenge being presented. This issue is not present on the sister site XWT-Classics, where I can connect in Jackett without Flaresolverr.

see here.
https://github.com/FlareSolverr/FlareSolverr/issues/169#issuecomment-890560099

and here.
https://github.com/Jackett/Jackett/issues/12051#issuecomment-890324093

meanwhile I get this....
![image](https://user-images.githubusercontent.com/7904175/131424952-0c4e5aed-0f10-4828-90a6-a8116966cb56.png)

### Logged Error Messages
```
2021-08-30 21:08:09 | Debug | Connection id "0HMBC370IP5EP" stopped.
-- | -- | --
2021-08-30 21:08:09 | Debug | Connection id "0HMBC370IP5EP" disconnecting.
2021-08-30 21:08:09 | Debug | Connection id "0HMBC370IP5EP" sending FIN because: "The client closed the connection."
2021-08-30 21:08:09 | Info | Request finished HTTP/1.1 POST http://jackett.REDACTED.org/jackett/api/v2.0/indexers/xwtorrents/config application/json 347 - 500 - application/json 117.3820ms
2021-08-30 21:08:09 | Debug | Connection id "0HMBC370IP5EP" received FIN.
2021-08-30 21:08:09 | Debug | Connection id "0HMBC370IP5EP" completed keep alive response.
2021-08-30 21:08:09 | Debug | No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps.
2021-08-30 21:08:09 | Error | FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208    at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 609    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 541    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 965    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2021-08-30 21:08:09 | Info | Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2021-08-30 21:08:09 | Info | Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 93.7152ms
2021-08-30 21:08:09 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: POST Url: https://xtremewrestlingtorrents.net/takelogin.php PostData: {username=REDACTED, password=REDACTED, returnto=/} RawBody: )
2021-08-30 21:08:09 | Debug | CACHE IsCacheEnabled => false
2021-08-30 21:08:09 | Debug | Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
2021-08-30 21:08:09 | Debug | Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...
2021-08-30 21:08:09 | Debug | Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
2021-08-30 21:08:09 | Debug | Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
2021-08-30 21:08:09 | Debug | Connection id "0HMBC370IP5EP", Request id "0HMBC370IP5EP:00000002": done reading request body.
2021-08-30 21:08:09 | Debug | Connection id "0HMBC370IP5EP", Request id "0HMBC370IP5EP:00000002": started reading request body.
2021-08-30 21:08:09 | Debug | Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'.
2021-08-30 21:08:09 | Debug | Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'.
2021-08-30 21:08:09 | Debug | Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ...
2021-08-30 21:08:09 | Debug | Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...
2021-08-30 21:08:09 | Debug | Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2021-08-30 21:08:09 | Debug | Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2021-08-30 21:08:09 | Info | Authorization was successful.
2021-08-30 21:08:09 | Debug | Execution plan of result filters (in the following order): None
2021-08-30 21:08:09 | Debug | Execution plan of exception filters (in the following order): None
2021-08-30 21:08:09 | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2021-08-30 21:08:09 | Debug | Execution plan of resource filters (in the following order): None
2021-08-30 21:08:09 | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2021-08-30 21:08:09 | Info | Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett).
2021-08-30 21:08:09 | Info | Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2021-08-30 21:08:09 | Debug | Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2021-08-30 21:08:09 | Debug | Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/xwtorrents/config'
2021-08-30 21:08:09 | Debug | 1 candidate(s) found for the request path '/api/v2.0/indexers/xwtorrents/config'
2021-08-30 21:08:09 | Debug | AuthenticationScheme: Cookies was successfully authenticated.
2021-08-30 21:08:09 | Debug | POST requests are not supported
2021-08-30 21:08:09 | Debug | Request is continuing in applying rules. Current url is https://jackett.REDACTED.org/jackett/api/v2.0/indexers/xwtorrents/config
2021-08-30 21:08:09 | Debug | Request is continuing in applying rules. Current url is https://jackett.REDACTED.org/jackett/api/v2.0/indexers/xwtorrents/config
2021-08-30 21:08:09 | Debug | Request is continuing in applying rules. Current url is https://jackett.REDACTED.org/jackett/api/v2.0/indexers/xwtorrents/config
2021-08-30 21:08:09 | Info | Request starting HTTP/1.1 POST http://jackett.REDACTED.org/jackett/api/v2.0/indexers/xwtorrents/config application/json 347
2021-08-30 21:08:09 | Debug | Connection id "0HMBC370IP5EP" started.
2021-08-30 21:08:09 | Debug | Connection id "0HMBC370IP5EP" accepted.
```

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment] 2021-08-31 01:51
very odd. 
I'm using Jackett on my win10 and can use the indexer without issues. As you have reported, I do not see any evidence that cloudflare is required, and my Jackett does not reach out to the configured flaresolverr.
I even tested my Jackett with the flaresolverr disabled, and I could define and use the indexer without issues.

So the question is, what is it about your set up that is tricking Jackett into thinking that flaresolverr is required?

this is effectively a duplicate of https://github.com/FlareSolverr/FlareSolverr/issues/169#issuecomment-890560099
and a continuation of #12051 

3 different team members have tried to replicate your issue and cannot do so :-( 
I don't have the skills to help you further with this one, but maybe this fresh ticket will inspire some volunteer familiar with your platform and networks to help?

**Comment by dRuEFFECT** [comment] 2021-09-01 00:32
well i installed jackett on my windows machine and it works as it used to, so i'm just glad i can get my workflow back in order.

still tho, there's something about the unraid/linux environment going awry. an XWT mod shed some light that "We've increased our firewall and security settings on cloud flare due to DDoS attacks. So there are more captcha and challenges for anything which may look like a bot."

i'm still hoping we can resolve this somehow, i'd prefer to not have my desktop running 24/7

let me know if there's anything at all I can provide to help investigate

**Comment by chazaroo1980** [comment] 2021-09-05 01:38
Change the url to http://www.xtremewrestlingtorrents.net/

**Comment by dRuEFFECT** [comment] 2021-09-05 06:48
> Change the url to http://www.xtremewrestlingtorrents.net/

tried, still no
![image](https://user-images.githubusercontent.com/7904175/132118128-e36edc00-cb0e-4081-83e9-3311e532dd14.png)

**Comment by chazaroo1980** [comment] 2021-09-05 12:48
![E9AE689D-69DC-467F-B9A3-2454ECE64BC1](https://user-images.githubusercontent.com/87774075/132127353-7deed5e0-2218-4ae9-b37d-f8e707011754.png)
![BB2E65CB-B437-4B55-835D-661DF9C45F78](https://user-images.githubusercontent.com/87774075/132127354-e37f4505-920d-467c-8ee2-5338ad9218dc.jpeg)

**Comment by chazaroo1980** [comment] 2021-09-05 14:01
![06209C98-D77C-4F29-B03F-0B3CA9AED0A4](https://user-images.githubusercontent.com/87774075/132129673-b6b57d24-5963-43f5-bbf6-1cc599fac042.jpeg)
![F8A4008D-23CE-49B6-AEAA-7BFBCBAF04C8](https://user-images.githubusercontent.com/87774075/132129677-e90f1407-1101-4e1d-b300-e05209aff497.png)

**Comment by fsign** [comment] 2021-12-03 00:29
> http://www.xtremewrestlingtorrents.net

This actually worked for me.

**Comment by ilike2burnthing** [comment] 2021-12-11 19:41
Posting this here after closing https://github.com/Jackett/Jackett/issues/12696, as there's not anything more we can do to help resolve this issue. As the site admins have said (https://github.com/Jackett/Jackett/issues/12239#issuecomment-909758795), it's a result of changes they've made.

> You could try testing in browser to see if you can replicate the issue using the following method - https://github.com/FlareSolverr/FlareSolverr/issues/234#issuecomment-986101962 (see https://github.com/FlareSolverr/FlareSolverr/issues/234#issuecomment-986158494 for both UAs). However, all that will confirm is that the site is blocking you or presenting a challenge, and other than possibly changing IP with a proxy or VPN, or switching from Windows to Linux or vice versa, there's not much you can do.

**Closed by ilike2burnthing** 2021-12-11 19:41 UTC
Labels: OS Linux / Mono / *nix
