### ISSUE TITLE
[torrentbytes] The SSL connection could not be established, see inner exception.: Authentication failed, see inner exception. (Config)

### ISSUE THREAD

**Issue by danyboy666** [Jackett/Jackett#9044] opened 2020-06-25 00:07 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux a****x 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Jackett v0.16.760.0

**Last Working Jackett Version**: Jackett v0.16.760.0

**Are you using a proxy or VPN?** [yes/no] no

OpenSSL 1.1.1f  31 Mar 2020

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

Add new indexer and configure user password for (Torrentbytes) from the web interface.

Expected to add new indexer to my list.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

 ` An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: Authentication failed, see inner exception.
Click here to open an issue on GitHub for this indexer.`

[https://pastebin.com/VvdJ6T4z](url)

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by danyboy666** [comment] 2020-06-25 00:37
I've seen this before but i, don't want to have to downgrade my openssl version.

https://github.com/Jackett/Jackett/issues/6359

Also i've tried this 

https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level

to no avail

**Comment by garfield69** [comment] 2020-06-25 01:15
The log you provided shows
```
2020-06-24 23:46:11.3841 Error System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
```
**process key too small** is not an error that can be fixed within Jackett. This is a failure to negotiate a security protocol, handled by openssl. Its exactly a duplicate of 6359 as you previously reported, and clearly the only solution available is to find a version of openssl either newer, beta, or older, that can handle the certificate that torrentbytes is using.
I do not believe there is anything that can be done from the Jackett side of the fence.
@ngosang  @cadatoiva  do you concur?

**Comment by ngosang** [comment] 2020-07-06 21:50
Yes, the server was using an insecure certificate.
They updated the certificate on 6/24/2020 and should be fine now. @danyboy666 could you test again?

**Comment by danyboy666** [comment] 2020-07-07 16:04
![image](https://user-images.githubusercontent.com/8345498/86809083-78cbf700-c049-11ea-8909-42d5909a8a28.png)

`Jul 07 11:59:53 altseedbox jackett[892329]: 07-07 11:59:53 Info Found 15 releases from TorrentBytes`

Yes it's working now thank you.

**Closed** 2020-07-07 19:41 UTC
Labels: OS Linux / Mono / *nix
