### ISSUE TITLE
[feature] Add a disable button for each indexer

### ISSUE THREAD

**Issue by nydave69** [Jackett/Jackett#6883] opened 2020-01-09 13:02 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

Add in the indexer line near configure icon/button a disable icon/button that would disable that indexer. This would stop any queries that that indexer attempt to make. So if you start seeing errors from the indexer you could disable it, and re-enable it later once the issue has been fixed. Any external attempts (couchpotato, sickchill) to access that indexer would fail with a specific code letting the external process know it's disabled.  
 
If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment] 2020-01-09 18:47
duplicate of #661

**Closed by garfield69** 2020-01-09 18:47 UTC
