### ISSUE TITLE
[kickasstorrents-to] (testing) Exception (kickasstorrents-to): Error: 403 Forbidden: Parse error

### ISSUE THREAD

**Issue by ghagiel** [Jackett/Jackett#15743] opened 2024-12-07 16:58 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-12-07 09:44:47 	Info 	Using HTTP Client: HttpWebClient2
2024-12-07 09:44:47 	Info 	Using FlareSolverr: No
2024-12-07 09:44:47 	Info 	Using proxy: Disabled
2024-12-07 09:44:47 	Info 	App config/log directory: /home/jimmy/.config/Jackett
2024-12-07 09:44:47 	Info 	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-12-07 09:44:47 	Info 	Running in Docker: No
2024-12-07 09:44:47 	Info 	File /etc/issue: Ubuntu 24.10 \n \l
2024-12-07 09:44:47 	Info 	Jackett variant: CoreLinuxAmdx64
2024-12-07 09:44:47 	Info 	OS version: Unix 6.11.0.9 (64bit OS) (64bit process)
2024-12-07 09:44:47 	Info 	Environment version: 8.0.11 (/home/jimmy/Downloads/Jackett.Binaries.LinuxAMDx64/Jackett/)
2024-12-07 09:44:47 	Info 	Starting Jackett v0.22.1055
```

### Description

Add kickasstorrents.to and test, received below error

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (kickasstorrents-to): Error: 403 Forbidden

[v0.22.1055.0] Jackett.Common.IndexerException: Exception (kickasstorrents-to): Error: 403 Forbidden
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Error: 403 Forbidden
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 556
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1793
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 838
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1934
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 378
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 399
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 812
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 324
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment] 2024-12-08 02:28
I've been getting this since Nov 26 but since no one else has reported until now, I've been holding off implementing a possible solution because it required the use of a useragent cookie, and I though it was just impacting me.
But now that someone else has reported \o/ I can implement.
Closing this as a duplicate of #9966

**Closed by garfield69** 2024-12-08 02:28 UTC

**Comment by ghagiel** [comment] 2024-12-08 15:38
Awesome, thanks!!
