### ISSUE TITLE
[REQ] https://dirtytorrents.com 

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#12292] opened 2021-09-12 09:46 UTC
Mix torrent search engine.

![89879](https://user-images.githubusercontent.com/36575395/132982944-fdd7e906-c4fa-4ba9-9b56-e529f3948325.JPG)

**Comment by garfield69** [comment] 2021-09-12 10:02
duplicate of #7918

**Closed by garfield69** 2021-09-12 10:02 UTC
