### ISSUE TITLE
[REQ] videolenta.biz

### ISSUE THREAD

**Issue by Lonli-Lokli** [Jackett/Jackett#6637] opened 2019-12-18 06:27 UTC
New Russian tracker https://videolenta.biz/

**Comment by garfield69** [comment] 2019-12-18 06:44
this public site is not suitable for the cardigann processor which expects search results to contain a one to one relation between the title and a torrent/magnet.
Since this site presents results where one title leads to multiple torrents listed in the details page, the indexer for this site will need to be written in C#.

**Comment by garfield69** [comment] 2022-05-08 07:10
this redirects to https://t.lafa.site/
closing as a duplicate of #12594

**Closed by garfield69** 2022-05-08 07:10 UTC
Labels: PR Welcome!, New Public Tracker, Needs C#, Returns one-title-many-torrents
