### ISSUE TITLE
[animebytes] Exception (animebytes): Can not convert Object to String.: Parse error (Test)

### ISSUE THREAD

**Issue by Dhs92** [Jackett/Jackett#6203] opened 2019-10-18 15:58 UTC
https://paste.dhs92.me/zurobetajo.js

**Jackett version**: 0.11.817.0 
**Mono version**: Mono JIT compiler version 6.0.0 (makepkg/6256b82d62f Fri 20 Sep 2019 11:18:59 PM -03)

-------------------------------
..edit: already reset my passkey :p

**Comment by garfield69** [comment] 2019-10-18 18:19
duplicate of #6186 
fixed beginning with jackett pre-release 0.12.833

**Closed by garfield69** 2019-10-18 18:19 UTC
