### ISSUE TITLE
Can't access Jackett dashboard

### ISSUE THREAD

**Issue by tasesmuemils** [Jackett/Jackett#13824] opened 2022-12-29 13:51 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
DietPi version:
G_DIETPI_VERSION_CORE=8 G_DIETPI_VERSION_SUB=12 G_DIETPI_VERSION_RC=1 G_GITBRANCH='master' G_GITOWNER='MichaIng' G_LIVE_PATCH_STATUS[0]='applied'

Distro version: bullseye 0

Kernel version | Linux DietPi 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux

SBC model: RPi 3 Model B (aarch64)

Power supply used | 5V 1A
SD card used | Kingston 16GB

Software title | Jackett

Was the software title installed freshly or updated/migrated? Just installed freshly
```

### Description

Hello,

Already tried to find bug in DietPi forums, the suggested to ask here:
_Probably the Jackett developers have a clue what reason a segmentation fault at this stage could have!_
[strace.txt](https://github.com/Jackett/Jackett/files/10319742/strace.txt)

[From DietPi forum](https://dietpi.com/forum/t/cant-access-jackett/15366/17)

I installed Sonarr (following tutorial) and I could not add indexer Rarbg, test goes through, on save “Unable to connect to indexer, check the log for more details”.
Found out about Jackett, but after install I try to access IP:9117, but cant reach the page: This site can’t be reached
IP refused to connect.

Other services (Plex, qBittorrent, Sonarr) works just fine.
I rebooted the server, uninstall/install Jackett, sudo dietpi-software reinstall 147 - still not working.

### Logged Error Messages

```text
/opt/jackett/jackett --version
Segmentation fault

journalctl -u jackett
The command returns too many rows (restart counter till 3040), but the last 3 counters looks like this:

Dec 27 11:05:20 DietPi systemd[1]: jackett.service: Scheduled restart job, restart counter is at 3038.
Dec 27 11:05:20 DietPi systemd[1]: Stopped Jackett (DietPi).
Dec 27 11:05:20 DietPi systemd[1]: Started Jackett (DietPi).
Dec 27 11:05:21 DietPi Jackett[225353]: Segmentation fault
Dec 27 11:05:21 DietPi systemd[1]: jackett.service: Succeeded.
Dec 27 11:05:26 DietPi systemd[1]: jackett.service: Scheduled restart job, restart counter is at 3039.
Dec 27 11:05:26 DietPi systemd[1]: Stopped Jackett (DietPi).
Dec 27 11:05:26 DietPi systemd[1]: Started Jackett (DietPi).
Dec 27 11:05:26 DietPi Jackett[225364]: Segmentation fault
Dec 27 11:05:26 DietPi systemd[1]: jackett.service: Succeeded.
Dec 27 11:05:32 DietPi systemd[1]: jackett.service: Scheduled restart job, restart counter is at 3040.
Dec 27 11:05:32 DietPi systemd[1]: Stopped Jackett (DietPi).
Dec 27 11:05:32 DietPi systemd[1]: Started Jackett (DietPi).
Dec 27 11:05:32 DietPi Jackett[225376]: Segmentation fault
Dec 27 11:05:32 DietPi systemd[1]: jackett.service: Succeeded.
```

**Comment by ilike2burnthing** [comment] 2022-12-29 15:25
Try installing [v0.20.2369](https://github.com/Jackett/Jackett/releases/v0.20.2369) and see if it works. If so, try updating and see if it fails.

If so, we have a duplicate of https://github.com/Jackett/Jackett/issues/13806, and you should have a look at the steps we went through there.

**Comment by jprokos** [comment] 2022-12-29 23:38
I had a similar issue. Jackett was working perfectly this morning, then after the update to v0.20.2451 from v0.20.2447 the dashboard wasn't finding my .config file. There was no API string in the API field and no settings in any other field. Uninstalling and reinstalling v0.20.2447 solved this issue for me.

MacOS

**Comment by tasesmuemils** [comment] 2022-12-30 09:53
How I can install specific Jackett version via terminal (using DietPi - lightweight Debian OS)?

**Comment by ilike2burnthing** [comment] 2022-12-30 10:12
Download https://github.com/Jackett/Jackett/releases/download/v0.20.2369/Jackett.Binaries.LinuxARM64.tar.gz and install https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above.

Not sure if there's something specific about DietPi which would change or prevent that.

**Comment by MichaIng** [comment] 2022-12-30 12:20
Looks exactly like the other issue. Not a Mono issue since in our case it's ARM64 .NET core build.

Mysterious is that it worked well on a different aarch64 board with otherwise same Debian version. But probably there is/was a difference between the latest version offered on GitHub vs the one offered via internal updater (which seems to be newer by times).

On DietPi, the archive needs to be extractrd to `/opt/jackett`, then:
```sh
chown -R jackett:jackett /opt/jackett
systemctl restart jackett
sleep 3
systemctl status jackett
```
to check whether it works.

**Comment by tasesmuemils** [comment] 2022-12-30 13:08
So I did this:
```
wget --content-disposition 'https://github.com/Jackett/Jackett/releases/download/v0.20.2369/Jackett.Binaries.LinuxARM64.tar.gz'
tar -xvf Jackett*
sudo mkdir /opt/jackett
sudo mv Jackett/* /opt/jackett 
chown -R dietpi:dietpi /opt/jackett
cd opt
cd jackett
sudo ./install_service_systemd.sh
systemctl restart jackett
sleep 3
systemctl status jackett
```


And it works. I can access IP:9117/UI/Dashboard.
I guess now only problem is that I run older release (v0.20.2369)?
<img width="700" alt="Screenshot 2022-12-30 150800" src="https://user-images.githubusercontent.com/18176025/210073420-ae39cbbc-f5a3-46f2-94f6-224f9eb2c6da.png">

**Comment by ilike2burnthing** [comment] 2022-12-30 13:19
If you click the `Check for updates` button, does it fail?

**Comment by tasesmuemils** [comment] 2022-12-30 14:07
No, it shows 'Update triggered. See the logs'.
Then I click on `View logs`:

```

Date | Level | Message
-- | -- | --
2022-12-30 16:03:03 | Info | Torznab search in FANO.IN => Found 50 releases (from cache)
2022-12-30 16:03:01 | Info | Torznab search in FANO.IN => Found 50 releases (from cache)
2022-12-30 16:02:58 | Info | Torznab search in FANO.IN => Found 50 releases (from cache)
2022-12-30 16:02:55 | Info | Torznab search in FANO.IN => Found 50 releases
2022-12-30 16:02:31 | Info | Updater started process id: 107127
2022-12-30 16:02:31 | Info | Starting updater: /tmp/JackettUpdate-v0.20.2459-638080055202119835/Jackett/JackettUpdater --Path "/opt/jackett" --Type "Console" --Args " --NoRestart" --KillPids "106480" --NoRestart
2022-12-30 16:01:58 | Warn | As of "12/30/2022 14:00:27 +00:00", the heartbeat has been running for "00:01:02.3829853" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 16:01:58 | Warn | As of "12/30/2022 14:00:27 +00:00", the heartbeat has been running for "00:01:02.3829853" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:58:06 | Info | Downloading release v0.20.2459 It could take a while...
2022-12-30 15:58:06 | Info | New release found. Current version: v0.20.2369 New version: v0.20.2459
2022-12-30 15:58:04 | Info | Checking for updates... Jackett variant: CoreLinuxArm64
2022-12-30 15:54:16 | Info | Updater started process id: 107018
2022-12-30 15:54:16 | Info | Starting updater: /tmp/JackettUpdate-v0.20.2459-638080048816660503/Jackett/JackettUpdater --Path "/opt/jackett" --Type "Console" --Args " --NoRestart" --KillPids "106480" --NoRestart
2022-12-30 15:51:49 | Warn | As of "12/30/2022 13:51:35 +00:00", the heartbeat has been running for "00:00:01.2885883" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:51:49 | Warn | As of "12/30/2022 13:51:35 +00:00", the heartbeat has been running for "00:00:01.2885883" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:51:23 | Info | Torznab search in FANO.IN => Found 50 releases (from cache)
2022-12-30 15:51:23 | Info | Torznab search in FANO.IN => Found 50 releases (from cache)
2022-12-30 15:48:58 | Warn | As of "12/30/2022 13:48:47 +00:00", the heartbeat has been running for "00:00:03.7222555" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:48:58 | Warn | As of "12/30/2022 13:48:47 +00:00", the heartbeat has been running for "00:00:03.7222555" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:45:50 | Info | Downloading release v0.20.2459 It could take a while...
2022-12-30 15:45:50 | Info | New release found. Current version: v0.20.2369 New version: v0.20.2459
2022-12-30 15:45:46 | Info | Checking for updates... Jackett variant: CoreLinuxArm64
2022-12-30 15:40:13 | Warn | As of "12/30/2022 13:40:02 +00:00", the heartbeat has been running for "00:00:08.9084238" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:40:13 | Warn | As of "12/30/2022 13:40:02 +00:00", the heartbeat has been running for "00:00:08.9084238" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:38:46 | Warn | As of "12/30/2022 13:38:44 +00:00", the heartbeat has been running for "00:00:01.8242974" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:38:46 | Warn | As of "12/30/2022 13:38:44 +00:00", the heartbeat has been running for "00:00:01.8242974" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:38:34 | Warn | As of "12/30/2022 13:38:30 +00:00", the heartbeat has been running for "00:00:04.3143483" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:38:34 | Warn | As of "12/30/2022 13:38:30 +00:00", the heartbeat has been running for "00:00:04.3143483" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:37:46 | Warn | As of "12/30/2022 13:37:35 +00:00", the heartbeat has been running for "00:00:04.5791009" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:37:46 | Warn | As of "12/30/2022 13:37:35 +00:00", the heartbeat has been running for "00:00:04.5791009" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:33:37 | Info | Torznab search in FANO.IN => Found 50 releases (from cache)
2022-12-30 15:33:37 | Info | Torznab search in FANO.IN => Found 50 releases (from cache)
2022-12-30 15:26:53 | Warn | As of "12/30/2022 13:26:49 +00:00", the heartbeat has been running for "00:00:01.0810066" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:26:53 | Warn | As of "12/30/2022 13:26:49 +00:00", the heartbeat has been running for "00:00:01.0810066" which is longer than "00:00:01". This could be caused by thread pool starvation.
2022-12-30 15:23:24 | Info | Torznab search in FANO.IN => Found 50 releases (from cache)
2022-12-30 15:23:22 | Info | Torznab search in FANO.IN => Found 50 releases (from cache)
2022-12-30 15:20:57 | Info | Torznab search in FANO.IN => Found 50 releases (from cache)
2022-12-30 15:20:50 | Info | Torznab search in FANO.IN => Found 50 releases
2022-12-30 14:56:39 | Info | Jackett startup finished in 31.509 s
2022-12-30 14:56:37 | Info | Adding filter indexer ('type:semi-public' indexer) ...
2022-12-30 14:56:37 | Info | Adding filter indexer ('type:private' indexer) ...
2022-12-30 14:56:37 | Info | Adding filter indexer ('type:public' indexer) ...
2022-12-30 14:56:37 | Info | Adding aggregate indexer ('all' indexer) ...
2022-12-30 14:56:37 | Info | Loaded 571 indexers in total
2022-12-30 14:56:37 | Info | Loaded 494 Cardigann indexers: exkinoray, milkie, anthelion-api, torrentdownload, trancetraffic, ccfbits, thegeeks, haidan, mixtapetorrent, moviesite, selezen, gamestorrents, funkytorrents, boxingtorrents, pttime, comicat, torrentsectorcrew, xxxtorrents, whiteangel, animelayer, eztv, acidlounge, world-of-tomorrow, ptsbao, mousebits, torrentz2eu, torrentsir, catorrent, acrossthetasman, rintornet, torrent-turk, danishbytes-api, mnv, nntt, fanoin, yggcookie, mononokebt, teamhd, torrenting, hd4fans, thefallingangels, digitalcore, linkomanija, springsunday, exttorrents, fantastiko, extremlymtorrents, xwtclassics, rptorrents, genesismovement, bitcityreloaded, leech24, newstudio, thepiratebay, btmet, madsrevolution, metaltracker, desitorrents-api, pthome, gktorrent, pixelcove2fa, huntorrent, hebits, reelflix-api, docspedia, solidtorrents, totheglorycookie, pornotorrent, btnext, spiritofrevolution, totallykids, torrentleech, byrbt, torrentfunk, pixelados-html, oshenpt, the-crazy-ones, kickasstorrents-to, nipponsei, miobt, dmhy, xwtorrents, woot, limetorrentsclone, bitsearch, shareisland-api, ehentai, badasstorrents, hdatmos, hellashut, audiences, ptfiles, 1337x, opencd, concertos, romanianmetaltorrents, torrentqq, turkseed, resurrectthenet, mojblink, hd-unit3d-api, brsociety-api, redbits-api, pixelados, unionfansub, hdtime, p2pelite, tvroad, isohunt2, ztracker, idope, torrent9, torrentcore, magico, seedfile, trupornolabs, 52pt, zelkaorg, parnuxi, finelite, tokyotosho, zetorrents, satclubbing, hdforever, rus-media, glodls, megapeer, mircrew, firebit, kufirc, hdsky, tmghub, cpasbienclone, acervos, ihdbits, xbytesv2, tasmanit, racingforme, eniahd, tribalmixes, torrent9clone, arabp2p, karagarga, yts, sosulki, aussierules, cloudtorrents, thevault, hdzone, lepornoinfo, torrentdownloads, beyond-hd, portugas-api, torrentwhiz, torrentslocal, pornbay, extratorrent-st, theleachzone, sportscult, femdomcult, bithorlo, swarmazon-api, gigatorrents, pier720, keepfriends, tjupt, tellytorrent-api, carpt, filelisting, insanetracker, zamundanet, shanaproject, linuxtracker, haitang, teamctgame, legittorrents, lesaloon, hdtorrentsit, rustorka, rainbowtracker, locadora, tvchaosuk, bulltorrent, rutor, beitai, pixelcove, sporthd, rutracker-ru, trezzor, puntotorrent, crazyhd, learnbits, losslessclub, arabafenice, empornium2fa, polishsource, jme-reunit3d-api, theshinning-api, torrentv, pctorrent, empornium, skipthecommercials-api, torrentland, rapidzona, immortuos, 3changtrai, bestcore, putao, tlfbits, mteamtp2fa, soulvoice, krazyzone, gtorrentpro, kickasstorrents-ws, mactorrentsdownload, megamixtracker, diablotorrent, theshow, animeworld-api, torrentccf, showrss, pussytorrents, speedtorrentreloaded, magicheaven, estone, dodder, bitspyder, nyaasi, racing4everyone-api, bitturk, teamos, audiobookbay, mikan, vsthouse, torrent-explosiv, internetarchive, dark-shadow, animetracker, ceskeforum, skipthetrailers, xxxadulttorrent, acgsou, mypornclub, ebooks-shares, mvgroupforum, torrenthr, piratbit, hdc, 1ptbar, datatalli, hddolby, abnormal, rintor, divteam, muziekfabriek, uniongang, cinemamovies, torlook, pornforall, anisource, hawke-uno, discfan, blutopia-api, totheglory, gfxpeers, redstartorrent, asiancinema, mma-torrents, pornotor, carpathians, xxxtor, fuzer, houseofdevil, dariustracker, crackingpatching, 3evils, jpopsuki, rgfootball, peersfm, scenepalace, pornoslab, greekdiamond, theempire, torrentby, happyfappy, xtremebytes, turktorrent, torrentleech-pl, cartoonchaos, pterclub, bithumen, knaben, file-tracker, kinorun, 0daykiev, bangumi-moe, amigosshare, hdarea, anime-free, torrentview, pwtorrents, btetree, deildu, torrentoyunindir, bt4g, lat-team-api, torrentgalaxy, theaudioscene, unlimitz, thesceneplace, btsow, gaytorrentru, oldtoonsworld, frozenlayer, lemonhd, hdcztorrent, wdt, majomparade, crnaberza, ydypt, theoccult, anilibria, 2fast4you, yourbittorrent, torlock, scenerush, superbits, onejav, hdgalaktik, nethd, dreamtracker, torrentlt, torrentproject2, elitetorrent-biz, girotorrent, extremetorrents, greekteam, learnflakes, potuk, bluebirdhd, twilight, indietorrents, hdai, kinozal, pignetwork, hdbits, carphunter, hdspain, siambit, spidertk, mteamtp, dxp, bitbazis, 3dtorrents, newretro, falkonvisionteam, aidoruonline, dimeadozen, tapochek, zomb, datascene-api, torrent-pirat, fenyarnyek-tracker, esharenet, hdolimpo-api, moviesdvdr, purovicio, limetorrents, chilebt, movietorrentz, uniondht, twilightszoom, tekno3d, hhanclub, RockBox, sktorrent, Bittorrentfiles, arenabg, mazepa, ibit, themixingbowl, yggtorrent, btdigg, xiteme, ourbits, hdfans, demonoid, audionews, teracod, itorrent, hdturk, ilcorsaroblu, acgrip, bwtorrents, hdhome, aftershock, fouducinema, sukebeinyaasi, torrentz2nz, sugoimusic, torrentseeds-api, p2pbg, generationfree-api, cpasbien, libranet, theoldschool-api, gay-torrentsorg, speedmasterhd, mvgroupmain, proporno, korsar, hdchina, 4thd, seedoff, finvip, backups, sexypics, bitru, hdmonkey, ptmsg, lastfiles, 0magnet, freshmeat, concen, torrent911, uhdbits, broadcity, punkshorror, u2, gimmepeers, snowpt, hdonly, proaudiotorrents, borgzelle, extremebits, crazyspirits, r3vwtf, piratbitl, myspleen, classix, hdu, peeratiko, vsttorrents, sharewood, bootytape, noname-club, aniRena, nbtorrents-api, coastalcrew, ftuapps, cathoderaytube, riperam, mesevilag, movietorrent, xthor-api, pornleech, sktorrent-org, wihd, marinetracker, gay-torrents, torrentmasters, sdbits, aither-api, bitded, noname-clubl, underversel, byrutor, bitnova, bitsexy, abtorrents, ilcorsaronero, animeclipse, torrentbd, bigfangroup, newstudiol, chdbits, rudub, traht, thenewfun, bibliotik, swarmazon, booktracker, crt2fa, jptv, hdroute, torrentkitty, cinemageddon, theplace, cinematik, jav-torrent, lst, polishtracker-api, fantasticheaven, btschool
2022-12-30 14:56:21 | Info | Loading Cardigann indexers from: /home/dietpi/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /opt/jackett/Definitions
2022-12-30 14:56:21 | Info | Loaded 77 Native indexers: alpharatio, anidex, anidub, animebytes, Animedia, animetorrents, aro, avistaz, bakabt, beyond-hd-api, bithdtv, bjshare, brasiltracker, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, darmowetorenty, divxtotal, dontorrent, epublibre, erai-raws, exoticaz, filelist, funfile, gazellegames, gazellegamesapi, greatposterwall, hdbitsapi, hdspace, hdtorrents, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, myanonamouse, ncore, nebulance, nebulanceapi, norbits, orpheus, partis, passthepopcorn, piratethenet, pixelhd, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, secretcinema, sharewoodapi, shazbat, ShizaProject, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentheaven, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, xspeeds, zonaq, animetosho, morethantv-api
2022-12-30 14:56:19 | Info | Loading Native indexers ...
2022-12-30 14:56:19 | Info | Using HTTP Client: HttpWebClient2
2022-12-30 14:56:19 | Info | Using FlareSolverr: No
2022-12-30 14:56:19 | Info | Using proxy: Disabled
2022-12-30 14:56:19 | Info | App config/log directory: /home/dietpi/.config/Jackett
2022-12-30 14:56:19 | Info | ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-12-30 14:56:19 | Info | Running in Docker: No
2022-12-30 14:56:19 | Info | File /etc/issue: Debian GNU/Linux 11 \n \l
2022-12-30 14:56:19 | Info | Jackett variant: CoreLinuxArm64
2022-12-30 14:56:19 | Info | OS version: Unix 5.15.76.8 (64bit OS) (64bit process)
2022-12-30 14:56:17 | Info | Environment version: 6.0.11 (/opt/jackett/)
2022-12-30 14:56:11 | Info | Starting Jackett v0.20.2369

```

**Comment by ilike2burnthing** [comment] 2022-12-30 14:43
Sorry, should have been clearer, the updated version (v0.20.2459) is successfully found and downloaded, but it fails to actually install, and v0.20.2369 continues to run.

If you want to stay up to date, then according to https://github.com/Jackett/Jackett/issues/13806 you can install the ARM32 version.

**Closed by ilike2burnthing** 2022-12-30 14:43 UTC
Labels: OS Linux / Mono / *nix

**Comment by MichaIng** [comment] 2022-12-31 08:40
I guess the 32-bit Jackett version also means 32-bit libicu and other dependencies? Wouldn't be trivially to achieve with APT package manager 🤔.

**Comment by ilike2burnthing** [comment] 2022-12-31 10:04
Not sure. @draakuns didn't mention having to install additional dependencies, but perhaps they can clarify.

**Comment by draakuns** [comment] 2022-12-31 15:03
Nothing really needed for me, just the .NET version for ARM32.

Libicu for instance is only 64bit (ARM64)

```
casablanca@pine64:~$ dpkg -l | grep -i libic
ii  libicu-dev:arm64
ii  libicu66:arm64
ii  libicu67:arm64
```

Best regards
Draakuns
