### ISSUE TITLE
[speedtorrentreloaded] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by mizz141** [Jackett/Jackett#7540] opened 2020-03-06 22:48 UTC
### Environment

**OS**: Unraid v6.8.1

**.Net Runtime**: unkown

**.Net Version**: unkown

**Jackett Version**: 0.13.280.0

**Last Working Jackett Version**: 0.13.280.0

**Are you using a proxy or VPN?** No

### Description

Speedtorrentreloaded switched over to st-tracker.eu, which is unknown to jackett and thus wont work.
How do I tell jackett that it switched over?

**Comment by garfield69** [comment] 2020-03-06 23:25
Duplicate of #7517 
STL have moved to a new domain with a new engine.
upgrade your Jackett to 0.13.483 for the updated indexer.

**Closed by garfield69** 2020-03-06 23:25 UTC
