### ISSUE TITLE
The Pirate Bay Indexer is not Working

### ISSUE THREAD

**Issue by aaronth07** [Jackett/Jackett#1743] opened 2017-08-28 21:01 UTC
The Pirate Bay indexer isn't working. I try to test it on Jackett, Radarr, and Sonarr, but it says it is not working.

Logs:
https://pastebin.com/h2gpy9Ce

Jackett version:  
0.7.1644.0

-------------------------------

**Comment by thebluepotato** [comment] 2017-08-28 21:54
Dupe of #1733

**Closed** 2017-08-29 09:00 UTC
