### ISSUE TITLE
[Feature suggestion] Include a button that adds all public trackers at once instead of adding them one by one

### ISSUE THREAD

**Issue by poll-cardioidy** [Jackett/Jackett#3274] opened 2018-06-23 09:42 UTC
I did a search and sorry if this will be considered a duplicate of https://github.com/Jackett/Jackett/issues/1576
The feature. 
You click "+ Add indexer" on the main page.
There could be a button on the popup page that says "Add all public trackers" 
that adds all public trackers at once instead of adding them one by one.
Example placement of the button https://i.imgur.com/yCbLW32.png

**Comment by kaso17** [comment] 2018-06-23 22:53
yes it's a dupe :)

**Comment by allanlaal** [comment] 2019-12-24 07:28
can we reopen #1576 or #3274 ?
Adding all public trackers in one go was the first idea I got when setting up Jackett first time in my life

**Comment by cadatoiva** [comment] 2020-02-24 02:35
This one has a better description of the feature request being made.

**Comment by Vitorvlv** [comment] 2020-03-14 19:35
+1 for this one

**Comment by JustSomeGuyNZ** [comment] 2020-04-19 10:37
+1 Just installed Jackett for the first time ever and having to add the public trackers 1 by 1 damn near made me rage uninstall it. Thankfully in the mean time  a top bloke has posted a console script to automate this over here: https://github.com/Jackett/Jackett/issues/1576#issuecomment-453656413

**Comment by ngosang** [comment] 2020-05-16 07:59
Duplicate of #4493

**Closed by ngosang** 2020-05-16 07:59 UTC
Labels: Duplicate, Enhancement, Web UI

**Comment by garfield69** [comment] 2021-05-17 07:04
v0.18.88
