### ISSUE TITLE
[rarbg] Doesn't work half the times (no results, test fails). Then it works again, then fails...

### ISSUE THREAD

**Issue by AlawamiAZ** [Jackett/Jackett#8999] opened 2020-06-17 22:24 UTC
### Environment

**OS**: Windows 10 2004

**.Net Version**: 4.8 (528209)

**Jackett Version**: v0.16.728 

**Last Working Jackett Version**:  v0.16.728 is the only version I've ever used

**Are you using a proxy or VPN?** NO

### Description

Rarbg indexer works intermittently, one minute I can search and it works fine then one minute later it doesn't show any result and clicking test fails, but then one minute later it works fine and the test sucessful.

pinging torrentapi.org in cmd for 30 minutes, packet loss 0%
"rarbg.to" is blocked in my country. but pinging it works fine (185.37.100.122)

### Logged Error Messages

2020-06-18 01:03:49 | Debug | Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole)
-- | -- | --
2020-06-18 01:03:49 | Debug | Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole)
2020-06-18 01:03:49 | Info | Authorization was successful.
2020-06-18 01:03:49 | Debug | Execution plan of result filters (in the following order): None
2020-06-18 01:03:49 | Debug | Execution plan of exception filters (in the following order): None
2020-06-18 01:03:49 | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
2020-06-18 01:03:49 | Debug | Execution plan of resource filters (in the following order): None
2020-06-18 01:03:49 | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2020-06-18 01:03:49 | Info | Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing controller action with signature System.Collections.Generic.List`1[Jackett.Common.Models.CachedLog] Logs() on controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole).
2020-06-18 01:03:49 | Info | Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)'
2020-06-18 01:03:49 | Debug | Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)'
2020-06-18 01:03:49 | Debug | Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)' with route pattern 'api/v2.0/server/Logs' is valid for the request path '/api/v2.0/server/logs'
2020-06-18 01:03:49 | Debug | 1 candidate(s) found for the request path '/api/v2.0/server/logs'
2020-06-18 01:03:49 | Debug | AuthenticationScheme: Cookies was successfully authenticated.
2020-06-18 01:03:49 | Debug | The request path /api/v2.0/server/logs does not match a supported file type
2020-06-18 01:03:49 | Debug | Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/server/logs?_=1592431260470
2020-06-18 01:03:49 | Debug | Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/server/logs?_=1592431260470
2020-06-18 01:03:49 | Debug | Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/server/logs?_=1592431260470
2020-06-18 01:03:49 | Info | Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/server/logs?_=1592431260470
2020-06-18 01:03:46 | Info | Request finished in 253.8977ms 500 application/json
2020-06-18 01:03:46 | Debug | Connection id "0HM0J08PPRDB0" completed keep alive response.
2020-06-18 01:03:46 | Debug | The response will be compressed with 'gzip'.
2020-06-18 01:03:46 | Error | System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 279    at Jackett.Server.Controllers.IndexerApiController.Test() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 144    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70
2020-06-18 01:03:46 | Info | Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)'
2020-06-18 01:03:46 | Info | Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 175.1199ms
2020-06-18 01:03:46 | Info | Found 0 releases from RARBG
2020-06-18 01:03:46 | Debug | WebClient(HttpWebClient2NetCore): Returning OK => {"error":"No results found","error_code":20}
2020-06-18 01:03:46 | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://torrentapi.org/pubapi_v2.php?token=w2jai4f1vx&format=json_extended&app_id=jackett_v0.16.728.0&limit=100&ranked=0&mode=list&category=4%3B14%3B17%3B18%3B23%3B25%3B27%3B28%3B32%3B33%3B35%3B40%3B41%3B42%3B44%3B45%3B46%3B47%3B48%3B49%3B49%3B50%3B51%3B52%3B53%3B54)
2020-06-18 01:03:46 | Debug | Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole)
2020-06-18 01:03:46 | Debug | Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole)
2020-06-18 01:03:46 | Info | Authorization was successful.
2020-06-18 01:03:46 | Debug | Execution plan of result filters (in the following order): None
2020-06-18 01:03:46 | Debug | Execution plan of exception filters (in the following order): None
2020-06-18 01:03:46 | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2020-06-18 01:03:46 | Debug | Execution plan of resource filters (in the following order): None
2020-06-18 01:03:46 | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2020-06-18 01:03:46 | Info | Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (JackettConsole).
2020-06-18 01:03:46 | Info | Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)'
2020-06-18 01:03:46 | Debug | Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)'
2020-06-18 01:03:46 | Debug | Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/rarbg/test'
2020-06-18 01:03:46 | Debug | 1 candidate(s) found for the request path '/api/v2.0/indexers/rarbg/test'
2020-06-18 01:03:46 | Debug | AuthenticationScheme: Cookies was successfully authenticated.
2020-06-18 01:03:46 | Debug | POST requests are not supported
2020-06-18 01:03:46 | Debug | Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/rarbg/test
2020-06-18 01:03:46 | Debug | Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/rarbg/test
2020-06-18 01:03:46 | Debug | Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/rarbg/test
2020-06-18 01:03:46 | Info | Request starting HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/rarbg/test  0

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment] 2020-06-17 22:33
its an issue with the RarBG API server at https://torrentapi.org/ which Jackett is obliged to use because RarBG does not want us scraping the HTML from their Web Site at https://rarbg.to/.
There is nothing can be done from the Jackett end. Just have to hope they sort it at the server side.
Duplicate of #8221

**Closed by garfield69** 2020-06-17 22:33 UTC
