### ISSUE TITLE
[req]: Add Demonoid back as it has been brought back from the dead again.

### ISSUE THREAD

**Issue by 1ColdAssHonkey** [Jackett/Jackett#15425] opened 2024-06-18 02:09 UTC
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: Demonoid
- URL: https://www.demonoid.is
- Description: Semi-private general tracker.
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): None
- Additional Comments: The site still has a screwed up logging in process.
```

**Comment by garfield69** [comment] 2024-06-18 03:14
Thanks for the heads up. I will reinstate.
closing as a duplicate of #5678

**Closed by garfield69** 2024-06-18 03:14 UTC

**Comment by garfield69** [comment] 2024-06-18 06:02
v0.22.164
