### ISSUE TITLE
[torrentsyndikat] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by Minds3t** [Jackett/Jackett#9733] opened 2020-10-03 20:36 UTC
Torrent-Syndikat recently updated their backend which seems to break jackett's current version. The new API documentation can be found here: https://torrent-syndikat.org/tsdocs/api.php

**Comment by garfield69** [comment] 2020-10-03 21:11
duplicate of #9543

**Closed by garfield69** 2020-10-03 21:11 UTC
