### ISSUE TITLE
u-Torrents.ro

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7626] opened 2020-03-11 19:19 UTC
Jackett currently lists SceneFZ and u-Torrents.ro as two domains for the same tracker. This is not true anymore as they have split into two separate trackers. 

SceneFZ is currently supported but cannot be configured #7625 

u-Torrents.ro is not supported. It would be great if it could be added. Signup is currently open (go to the second tab):
http://www.u-torrents.ro/login.php?returnto=%2F

Please note: I never received the confirmation email but signing through Google Chrome allowed me to log in automatically. Firefox didn't do so. After logging in, I was able to verify my account by clicking on a link on the homepage despite having not received the confirmation email. Only then was I able to log in through Firefox.

**Comment by garfield69** [comment] 2020-03-13 06:42
Jackett  0.13.633

**Comment by garfield69** [comment] 2020-07-12 22:20
https://www.u-torrents.ro/ returning Error 522 Connection timed out

**Comment by ilike2burnthing** [comment] 2020-07-13 10:36
Is this not already covered by - https://github.com/Jackett/Jackett/issues/868#issuecomment-649192064

**Comment by garfield69** [comment] 2020-07-13 19:16
closing as duplicate of #868

**Closed by garfield69** 2020-07-13 19:16 UTC
Labels: Down / Waiting for removal

**Comment by garfield69** [comment] 2020-07-18 03:23
@RoloSoze  do you have nay news on https://www.u-torrents.ro/
is the site gone, crashed or moved to a new domain?

**Comment by RoloSoze** [comment] 2020-07-18 10:35
@garfield69 I haven't read anything about it but it's been down for weeks. I'm not sure if it closed permanently. It might be a good idea to remove the indexer without deleting the source code so it can be reinstated if it ever comes back.
