### ISSUE TITLE
[thepiratebay] Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error 521)

### ISSUE THREAD

**Issue by JeeDeWee** [Jackett/Jackett#9829] opened 2020-10-13 14:00 UTC
### Environment

**OS**: Synology DSM 6.2.3-25426 Update 2

**.Net Runtime**:  Mono version: 5.20.1.34

**Jackett Version**: v0.16.1709.0

**Last Working Jackett Version**: n/a

**Are you using a proxy or VPN?** [yes] a TOR socks5 proxy

### Description

When adding the the provider The Piratebay the operation always fails with the error message as in the subject. Regardless of the alternative URL you enter there always appears to be a request to https://apibay.org.

### Logged Error Messages

System.Exception: Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error 521) - The tracker seems to be down.
  at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown (Jackett.Common.Utils.Clients.WebResult response) [0x00089] in <19e1b7d4eb3440759981d8397ba03c2e>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync (System.String url, System.String cookieOverride, Jackett.Common.Utils.Clients.RequestType method, System.String referer, System.Collections.Generic.IEnumerable`1[T] data, System.Collections.Generic.Dictionary`2[TKey,TValue] headers, System.String rawbody, System.Nullable`1[T] emulateBrowser) [0x0010a] in <19e1b7d4eb3440759981d8397ba03c2e>:0 
  at Jackett.Common.Indexers.ThePirateBay.GetRecentTorrents () [0x00081] in <19e1b7d4eb3440759981d8397ba03c2e>:0 
  at Jackett.Common.Indexers.ThePirateBay.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00081] in <19e1b7d4eb3440759981d8397ba03c2e>:0 
  at Jackett.Common.Indexers.ThePirateBay.ApplyConfiguration (Newtonsoft.Json.Linq.JToken configJson) [0x00081] in <19e1b7d4eb3440759981d8397ba03c2e>:0 
  at Jackett.Server.Controllers.IndexerApiController.UpdateConfig (Jackett.Common.Models.DTO.ConfigItem[] config) [0x0012d] in <a2e79973e3d24e9e98dac18ce3904db2>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <a2e79973e3d24e9e98dac18ce3904db2>:0

**Comment by mightyneek** [comment] 2020-10-13 15:18
Same issue here.  Windows 10. Started this morning. ver 0.16.1684.0

**Comment by bduijnhouwer** [comment] 2020-10-13 15:41
Also using version 0.16.1684.0 and Windows 10

**Comment by sh1der** [comment] 2020-10-13 16:12
Same here but linux, Jackett Version 0.16.1684.0. Like @bduijnhouwer said, https://apibay.org is down

**Comment by garfield69** [comment] 2020-10-13 17:13
duplicate of issue #9447 
https://github.com/Jackett/Jackett/issues/9447#issuecomment-707494060

**Closed by garfield69** 2020-10-13 17:13 UTC
