### ISSUE TITLE
Windows Taskbar Shortcut Not Getting Restarted.

### ISSUE THREAD

**Issue by purevertigo** [Jackett/Jackett#9139] opened 2020-07-12 09:37 UTC
### Environment
Windows 10

### Description
When Jackett gets auto-updated in the background, the taskbar icon exits and never gets restarted or put back after the update. Meaning you have to manually click the shortcut to put it back.

**Comment by garfield69** [comment] 2020-07-12 17:57
closing as duplicate of #8398

**Closed by garfield69** 2020-07-12 17:57 UTC
