### ISSUE TITLE
Lidarr Torznab not working

### ISSUE THREAD

**Issue by afmiller** [Jackett/Jackett#3472] opened 2018-07-26 01:34 UTC
I just installed Jackett and set up several sites for lidarr to use. I've verified that the sites are work and the content is there that I am looking for. Once I've successfully added them to Lidarr and search I do not have any search hits for the content. I verified the categories on lidarr for the indexer against what Jackett has listed. I have no issue with normal nzbs.
 Any help would be appreciated

**Comment by afmiller** [comment] 2018-07-26 01:41
Some amplifying info, the sites are kat.li , katcr.co , and piratebay.org

**Comment by Qstick** [comment] 2018-07-26 01:57
Piratebay issue is right here https://github.com/Jackett/Jackett/issues/2822

@kaso17 looks like neither of the kat indexers user categories (maybe its not possible to search by category with those?)

**Comment by kaso17** [comment] 2018-08-06 15:11
yes, it's the same problem as describes in #2822 
the trackers unfortunately don't allow limiting the "most recent torrents" view to specific categories.
Due to that it often happens that the most recent torrents don't contain any audio torrents resulting in zero results causing the lidarr test to fail.
Can't be fixed by jackett.

**Closed by kaso17** 2018-08-06 15:11 UTC

**Comment by petwri** [comment] 2019-01-13 14:36
I also tried adding torznab via jackett, but the adding fails, logfile entry is as follows:

`[v0.5.0.583] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (1337x): Error: NameResolutionFailure ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: NameResolutionFailure
  at System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x00044] in <eeec8e88b1fc462e84ade7bf334d0c97>:0 
  at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x000cc] in <eeec8e88b1fc462e84ade7bf334d0c97>:0 
  at System.Net.WebOperation.Run () [0x0009a] in <eeec8e88b1fc462e84ade7bf334d0c97>:0 
  at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x00094] in <eeec8e88b1fc462e84ade7bf334d0c97>:0 
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <eeec8e88b1fc462e84ade7bf334d0c97>:0 
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <eeec8e88b1fc462e84ade7bf334d0c97>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <7b0d87324cab49bf96eac679025e77d1>:0 
--- End of stack trace from previous location where exception was thrown ---

  at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x0041d] in <2d05f0f19f034ad09a31288b810590d5>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00478] in <2d05f0f19f034ad09a31288b810590d5>:0 
  at CloudFlareUtilities.ClearanceHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x0010c] in <d0213015414e4bf286b46bc1ee77bd72>:0 
  at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x000ca] in <2d05f0f19f034ad09a31288b810590d5>:0 
  at Jackett.Common.Utils.Clients.HttpWebClient.Run (Jackett.Common.Utils.Clients.WebRequest webRequest) [0x00456] in <0911bd35ebb74b53a337d97fe8ea2bd6>:0 
  at Jackett.Common.Utils.Clients.WebClient.GetString (Jackett.Common.Utils.Clients.WebRequest request) [0x0010b] in <0911bd35ebb74b53a337d97fe8ea2bd6>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies (System.String url, System.String cookieOverride, System.String referer, System.Collections.Generic.Dictionary`2[TKey,TValue] headers) [0x000cb] in <0911bd35ebb74b53a337d97fe8ea2bd6>:0 
  at Jackett.Common.Indexers.CardigannIndexer.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x0085e] in <0911bd35ebb74b53a337d97fe8ea2bd6>:0 
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x00091] in <0911bd35ebb74b53a337d97fe8ea2bd6>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x000ee] in <0911bd35ebb74b53a337d97fe8ea2bd6>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x0006b] in <0911bd35ebb74b53a337d97fe8ea2bd6>:0 
  at Jackett.Server.Controllers.ResultsController.Torznab (Jackett.Common.Models.DTO.TorznabRequest request) [0x00335] in <f07dbe408466448e9de1a607da8671d3>:0 
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000ca] in <7baa80505835458894a4cf0043864b14>:0 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in <7baa80505835458894a4cf0043864b14>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00050] in <7baa80505835458894a4cf0043864b14>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00024] in <7baa80505835458894a4cf0043864b14>:0 `

**Comment by kaso17** [comment] 2019-01-15 12:46
this error is caused by non working DNS, make sure your DNS is working.

**Comment by petwri** [comment] 2019-01-15 13:56
> this error is caused by non working DNS, make sure your DNS is working.

I added it via localhost, how should there be a DNS problem? The same setup works in radarr and sonarr.

**Comment by petwri** [comment] 2019-01-15 14:03
Ok, seems as if it was an jackett-internal problem. When one of the providers in jackett fails, the test from Lidarr fails too.
Working now.

**Comment by Diego31** [comment] 2023-04-04 05:24
Having the same problem in 2023... :/
