### ISSUE TITLE
[generationfree] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by stringer44** [Jackett/Jackett#5869] opened 2019-08-17 11:42 UTC
test failed
all settings by default
can't find forum settings

**Comment by garfield69** [comment] 2019-08-17 19:08
duplicate of #5469
login to the site directly with your browser. the first page is a reminder that you have to provide a presentation.
follow the link to post an introduction in that forum. admin will approve or post a request for more details.

**Closed by garfield69** 2019-08-17 19:08 UTC
