### ISSUE TITLE
BeyondHD unable to add to configured indexers

### ISSUE THREAD

**Issue by absintheboy** [Jackett/Jackett#497] opened 2016-09-09 08:55 UTC
I have previously not had any issues downloading from this tracker, but I noticed there were some releases not downloading.

I removed the indexer and then tried to re add it.  Jackett is showing a popup with "Error: Object reference not set to an instance of an object."

And the log shows "Exception in GetConfigForm"

**Comment by kaso17** [comment] 2016-09-09 09:59
Seems to be a duplicate of #434
If you can sent me an invite to kaso1717 -at- gmail.com I can have a look at it.

**Comment by absintheboy** [comment] 2016-09-09 11:30
I'm too new to the tracker to provide an invite I am afraid.  Hopefully another user can provide you with one.

**Comment by 1josh13** [comment] 2016-10-16 02:22
I started having this issue appx a month or so ago, maybe longer. Jackett just stopped pulling from beyond-hd and gives the error that @absintheboy mentioned above. I've attempted uninstalling and re installing jackett but that does not work either.

**Comment by kaso17** [comment] 2016-10-30 16:34
shoud be fixed

**Comment by absintheboy** [comment] 2016-10-30 17:52
I'm still getting the error.  Thanks for looking at it though.

**Comment by kaso17** [comment] 2016-11-01 08:35
Please post a full log (run jackett with -t option)

**Comment by kaso17** [comment] 2016-11-02 05:20
most likely the cloudflare bug too, fixed with the latest release

**Closed by kaso17** 2016-11-02 05:20 UTC
Labels: Needs Investigations, Provider
