### ISSUE TITLE
Jackett fails to start on Linux

### ISSUE THREAD

**Issue by dshanks01** [Jackett/Jackett#5765] opened 2019-08-01 16:58 UTC
After upgrading to v0.11.542, Jackett no longer starts on my Linux system. Manual start shows
```
$ sudo ./jackett
Failed to initialize CoreCLR, HRESULT: 0x80004005
```
Normally, I run Jackett as a service. Status shows
```
$ systemctl status jackett
● jackett.service - Jackett Daemon
   Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-08-01 09:35:38 PDT; 381ms ago
  Process: 9186 ExecStart=/opt/Jackett/jackett --NoRestart (code=exited, status=137)
 Main PID: 9186 (code=exited, status=137)
```

System information:
Linux is Mint 19.1 (Ubuntu 18.04)
Kernel is 4.15.0-55-generic
Mono is 6.0.0.313

**Comment by dshanks01** [comment] 2019-08-01 19:48
Pre-Release v0.11.551 appears to resolve this problem.

**Comment by garfield69** [comment] 2019-08-01 21:33
most likely duplicate of  #5208 
if it occurs too frequently for you after an auto-update, then you might want to consider disabling auto-updates until the problem is fixes by the c# devs.
the switch is on the jackett dashboard near the bottom, **disable auto-update**, followed by clicking on the **apply server settings** button.

**Closed by garfield69** 2019-08-01 21:33 UTC
