### ISSUE TITLE
[torrent9] Exception (torrent9): Specified argument was out of the range of valid values.Parameter name: Unknown operator: : Specified argument was out of the range of valid values.Parameter name: Unknown operator:  (Test)

### ISSUE THREAD

**Issue by Jamyz** [Jackett/Jackett#4985] opened 2019-03-29 09:24 UTC
**Jackett version**:  linuxserver/jackett (Docker) 23.03.19

**Comment by garfield69** [comment] 2019-03-29 17:31
duplicate of  #4982

**Comment by garfield69** [comment] 2019-08-22 19:51
solved with Jackett 0.11.635

**Closed by garfield69** 2019-08-22 19:51 UTC
Labels: Duplicate
