### ISSUE TITLE
[hdtorrents] Exception (hdtorrents): Accessing InnerText is not valid for this element type.: Accessing InnerText is not valid for this element type. (Test)

### ISSUE THREAD

**Issue by tigger29900** [Jackett/Jackett#1779] opened 2017-09-04 20:34 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment] 2017-09-05 16:38
fixed via e7b9f8c5ecc3268bf807fa4dc5ef2e5c2b4147bd
caused by a missing uploader column for some releases

**Closed by kaso17** 2017-09-05 16:38 UTC
