### ISSUE TITLE
Autoupdater fails on v20.2369 without log or trace. Manually starting newer jackett produces segmentation fault 

### ISSUE THREAD

**Issue by draakuns** [Jackett/Jackett#13806] opened 2022-12-24 00:12 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Environment version: 6.0.11 (/home/apps/jackett/Jackett/)
OS version: Unix 5.15.74.64 (64bit OS) (64bit process)
Jackett variant: CoreLinuxArm64
File /etc/issue: Armbian 22.11.1 Focal \l
Running in Docker: No
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
App config/log directory: /home/apps/.config/Jackett
Using proxy: Disabled
Using FlareSolverr: No
Using HTTP Client: HttpWebClient2
```

### Description

Hi,

auto-updater was killing my jackett instance with no traces nor log, so I manually installed and started any released version newer than .20.2369 and they all fail with segmentation fault. Even adding -t or -l doesn't really help as it seems that the binary is not even executing.

My platform is ARM64 running Armbian.

Rolling back to v20.2369 works again, but I had to disable autoupdate due to the recent versions not updating anymore.
I will stay on 2369 until you need any help on the topic, but obviously feel free to ask for any info you might need.

I tried to delete .config/jackett dir, but it fails on the same way (segfault)

Thanks in advance!

### Logged Error Messages

```text
As I said, no logs get in log.txt nor update.txt
```

**Comment by garfield69** [comment] 2022-12-24 05:51
Hmmm. we have an open ticket https://github.com/Jackett/Jackett/issues/12648 for a segmentation fault similar to yours but its for an ARM32 platform, and the suspect is thought to be .NET6 https://github.com/Jackett/Jackett/issues/12648#issuecomment-999536899
Unfortunately there is no solve yet, and given its been a year since it was opened, it does not look like there has been any progress since.
Perhaps you should explore using the Docker Jackett from https://github.com/Jackett/Jackett/issues/12648#issuecomment-999536899 instead?
@ilike2burnthing  anything to add?

**Comment by ilike2burnthing** [comment] 2022-12-24 06:36
Bit of a weird one, as there's nothing in [v0.20.2384](https://github.com/Jackett/Jackett/releases/tag/v0.20.2384) which would seem to cause this, but Docker is worth a shot.

**Comment by draakuns** [comment] 2022-12-26 21:37
Hi,

The point is that is seems it's something that broke right after that version... Otherwise a clean install of the latest available version would work... 
It's weird because it also isnt using standard mono, as it uses the core.net packaged on it.
I saw the ARM32 version but as I am using ARM64/aarch64, I don't see the common point... Even more as 32bit failed a year ago, but this build on 64bit started failing a week ago.
I will try the docker version, but even if it works, it would be nice if you can provide a mean to debug this.

Thanks!

**Comment by draakuns** [comment] 2022-12-26 22:04
Hmmmm... I bring news about it... docker Linuxserver img is not working.

container logs are basically empty, as it is a segfault just on the bin execution.

**docker logs:** 

`[custom-init] No custom services found, skipping...
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun jackett (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started`

**Attaching to the container and starting Jackett:**
`root@1bc9e5cfc6f1:/# /app/Jackett/jackett -t -l --NoUpdates
Segmentation fault (core dumped)
root@1bc9e5cfc6f1:/# `

Performing some "ps -ef" you can read between lines that S6 overlay is re-trying Jacket exec but it is failing.

Hope that helps 

Thanks!

**Comment by ilike2burnthing** [comment] 2022-12-27 06:36
Does the v0.20.2369 Docker image work?

Do the mono builds after v0.20.2369 work?

Like I said, there's nothing in [v0.20.2384](https://github.com/Jackett/Jackett/releases/tag/v0.20.2384) which would explain why Jackett suddenly stopped working, and as far as I can see we have [pipelines](https://github.com/Jackett/Jackett/blob/master/azure-pipelines.yml) set to use fixed versions (same as our project files, e.g. [Jackett.Common.csproj](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Jackett.Common.csproj)), so there's no 'latest' of something which has been silently updated.

**Comment by draakuns** [comment] 2022-12-27 12:12
Hi,

docker 2369 works as expected. Comparing to the previous S6 logs, it just executes the binary and "just" run.

> s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
12-27 13:08:31 Info Starting Jackett v0.20.2369 
12-27 13:08:31 Info Logging enabled. 
12-27 13:08:31 Info Tracing enabled. 
12-27 13:08:31 Debug Config file does not exist: /config/Jackett/ServerConfig.json 
12-27 13:08:33 Debug Creating web host... 
12-27 13:08:33 Debug Content root path is: /app/Jackett/Content 
12-27 13:08:37 Debug Autofac container built 
12-27 13:08:39 Info Environment version: 6.0.11 (/app/Jackett/) 
12-27 13:08:39 Info OS version: Unix 5.15.80.64 (64bit OS) (64bit process)

**Comment by draakuns** [comment] 2022-12-27 12:22
Mono version also fails, hope that my mono version is ok and the trace gives you some hint:

```
myprompt:~/Jackett$ mono ./JackettConsole.exe
12-27 13:20:53 Info Starting Jackett v0.20.2444
12-27 13:20:54 Error System.TypeLoadException: Could not resolve type with token 010000a1 from typeref (expected class 'System.Runtime.InteropServices.OSPlatform' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
  at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder (System.String[] args) [0x000d3] in <96ee8d1b889d4f26b7bd4cc3f07ca395>:0
  at Jackett.Server.Program.CreateWebHostBuilder (System.String[] args, System.String[] urls, System.String contentRoot) [0x00000] in <7fb70a666c614c63a7844a95a4e8eeea>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x002b2] in <7fb70a666c614c63a7844a95a4e8eeea>:0  System.TypeLoadException: Could not resolve type with token 010000a1 from typeref (expected class 'System.Runtime.InteropServices.OSPlatform' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
  at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder (System.String[] args) [0x000d3] in <96ee8d1b889d4f26b7bd4cc3f07ca395>:0
  at Jackett.Server.Program.CreateWebHostBuilder (System.String[] args, System.String[] urls, System.String contentRoot) [0x00000] in <7fb70a666c614c63a7844a95a4e8eeea>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x002b2] in <7fb70a666c614c63a7844a95a4e8eeea>:0

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 010000a1 from typeref (expected class 'System.Runtime.InteropServices.OSPlatform' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
  at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder (System.String[] args) [0x000d3] in <96ee8d1b889d4f26b7bd4cc3f07ca395>:0
  at Jackett.Server.Program.CreateWebHostBuilder (System.String[] args, System.String[] urls, System.String contentRoot) [0x00000] in <7fb70a666c614c63a7844a95a4e8eeea>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x002fd] in <7fb70a666c614c63a7844a95a4e8eeea>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 010000a1 from typeref (expected class 'System.Runtime.InteropServices.OSPlatform' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
  at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder (System.String[] args) [0x000d3] in <96ee8d1b889d4f26b7bd4cc3f07ca395>:0
  at Jackett.Server.Program.CreateWebHostBuilder (System.String[] args, System.String[] urls, System.String contentRoot) [0x00000] in <7fb70a666c614c63a7844a95a4e8eeea>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x002fd] in <7fb70a666c614c63a7844a95a4e8eeea>:0
myprompt:~/Jackett$ mono --version
Mono JIT compiler version 6.12.0.182 (tarball Tue Jun 14 22:41:13 UTC 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  arm64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

**Comment by draakuns** [comment] 2022-12-27 12:58
Hi,

I have more info: as ARM32 is binary compatible with ARM64 procs, I tried the docker version and it started just fine. It is something related with the ARM64 build, it seems.

```
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
12-27 13:40:07 Info Starting Jackett v0.20.2444 
12-27 13:40:07 Info Logging enabled. 
12-27 13:40:07 Info Tracing enabled. 
12-27 13:40:09 Debug Creating web host... 
12-27 13:40:09 Debug Content root path is: /app/Jackett/Content 
12-27 13:40:12 Debug Autofac container built 
12-27 13:40:13 Info Environment version: 6.0.12 (/app/Jackett/) 
12-27 13:40:13 Info OS version: Unix 5.15.80.64 
12-27 13:40:13 Info Jackett variant: CoreLinuxArm32 
12-27 13:40:13 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l 
12-27 13:40:13 Info Running in Docker: Yes (image build: v0.20.2444-ls87) 
12-27 13:40:13 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
12-27 13:40:13 Info App config/log directory: /config/Jackett 
12-27 13:40:13 Info Using proxy: Disabled 
12-27 13:40:13 Info Using FlareSolverr: No 
12-27 13:40:13 Info Using HTTP Client: HttpWebClient2 
12-27 13:40:13 Info Loading Native indexers ... 

```

Hope that helps!

**Comment by ilike2burnthing** [comment] 2022-12-27 16:12
Re: mono, are you using `mono-complete`? https://github.com/Jackett/Jackett/issues/4503#issuecomment-456815485

**Comment by draakuns** [comment] 2022-12-28 01:19
Hi,
my source is 

`deb https://download.mono-project.com/repo/ubuntu stable-focal main`

I have only runtimes, as they are needed for Sonarr. Not Radarr, jackett, etc are supposed to need them anymore, bc they use Core.NET ...

mono-4.0-gac
mono-gac
mono-runtime
mono-runtime-common
mono-runtime-sgen

All the other mono packages installed are "libmono*" which are installed as prereq for this runtime.

Cheers

**Comment by ilike2burnthing** [comment] 2022-12-28 08:13
This is purely to rule out the mono errors as being part of the problem. You could try [bionic-updates](https://github.com/Jackett/Jackett/issues/4732#issuecomment-465515405) if you're unable to install `mono-complete` on Ubuntu.

Also, complete aside, if you're up for trying a beta, [Sonarr v4](https://forums.sonarr.tv/t/sonarr-v4-beta/31078) no longer uses mono.

**Comment by draakuns** [comment] 2022-12-28 11:38
Hi!

Sonarr v4, I didn't noticed... it's nice to let go of mono once and for all, I'll give it a try, thanks!

On the other hand, as this is a "small" arm sbc I usually don't install stuff I don't really need, hope that you understand that.
I'll try creating a dockerfile if I have a bit of time, or if you already have one with it it would be great. Once finished, docker rm and we are good to go :D.
¿Any preference of ubuntu distro? bionic, focal, etc....

Regards!

**Comment by ilike2burnthing** [comment] 2022-12-28 11:44
Sorry, no, I rely on LS.io as well. Feel free to try your own, and there's no preference here when it comes to distro.

**Comment by draakuns** [comment] 2022-12-29 13:13
OK, I'll keep you posted after using a mono-complete... expect high response times, as I am facing right now with a bad blocks issue on the docker hd  on the ARM64 :(

**Comment by MichaIng** [comment] 2022-12-30 12:44
Is v0.20.2384 really the first which fails? Since I also do not see any change in it which could cause this, it then must be in the build environment. If I'm not mistaken, not all patch versions are frozen but only at least minor versions in all cases.

**Comment by draakuns** [comment] 2022-12-31 15:07
Hi @MichaIng, 

I tried 2369 which was the last working version. Then the next one 2384, which failed. Also the latest one available, which also fails. and I tried some in the middle, which also failed...

That is why I told you that the offending change was in that 2384, even if I don't see any relevant changes on the code to blame... Maybe sth on the build process pipeline changed?

Thanks and enjoy Christmas if available ;)
Draakuns

**Comment by draakuns** [comment] 2022-12-31 15:10
BTW, @ilike2burnthing I haven't forgotten what we have pending, It's just that I have the SBC busy on the badblock scan on the broken docker disk :( 
Will come back ASAP

Enjoy holidays, 
Draakuns

**Comment by ilike2burnthing** [comment] 2022-12-31 15:22
No rush, enjoy the holidays. Hope you get it sorted.

**Comment by ilike2burnthing** [comment] 2023-01-04 15:11
Thanks, so we've narrowed the issue down to definitely being with the ARM64 builds after v0.20.2369 for certain devices, just like in https://github.com/Jackett/Jackett/issues/12648 there was an issues with ARM32 builds after v0.20.10 for certain devices.

As a bit of a sanity check, I compared the ARM64 files from v0.20.2365 to v0.20.2369. There were only 10 non-definition files which had different hashes, and they were all the same size, so I'm putting that solely down to a change in version number.

I then compared v0.20.2369 to v0.20.2384, and 324 non-definition files had different hashes; something obviously changed, but it wasn't on our end.

**Comment by MichaIng** [comment] 2023-01-06 06:06
In our case it was a Raspberry Pi with Debian Bullseye arm64. For reference: https://dietpi.com/forum/t/cant-access-jackett/15366

I'll be able to test with some more boards (including QEMU container) and Debian versions the next days. Quite possible that it has do with some library since Debian and Ubuntu share mostly the same package sources.

**Comment by draakuns** [comment] 2023-01-07 01:07
Hi,

I decided to upgrade the SBC to 22.04 in order to check if that was the "simple" solution, but it still segfaults... (I needed to do it one of these days, anyways...)

Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

During the upgrade libicu67 upgraded to libicu70, just in case you were still wondering.
Latest version of Jackett, by the way: 20.2495

Jackett_upgrader binary works as a executable (on all versions), but the Jackett binary doesn't. Maybe that gives the devs a clue...

Regards, 
Draakuns

**Comment by ilike2burnthing** [comment] 2023-01-07 01:24
Shouldn't be necessary, but can you check these dependencies - https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies

**Comment by draakuns** [comment] 2023-01-07 02:16
Hey,

I was missing only a new lib required on ubuntu 22.x, liblttng1, which makes sense as I just updated to it. All the others were there, and given that I was on 20.x it should make no difference.

```
:~# dpkg -l | egrep "libc6|libgcc1|libgcc-s1|libgssapi-krb5|libicu|liblttng|libssl1|libssl3|libstdc|libunwind|zlib1g"
ii  libc6:arm64                                                 2.35-0ubuntu3.1
  arm64        GNU C Library: Shared libraries
ii  libc6-dev:arm64                                             2.35-0ubuntu3.1
  arm64        GNU C Library: Development Libraries and Header Files
ii  libgcc-s1:arm64                                             12.1.0-2ubuntu1~22.04
  arm64        GCC support library
ii  libgssapi-krb5-2:arm64                                      1.19.2-2
  arm64        MIT Kerberos runtime libraries - krb5 GSS-API Mechanism
ii  libicu-dev:arm64                                            70.1-2
  arm64        Development files for International Components for Unicode
ii  libicu70:arm64                                              70.1-2
  arm64        International Components for Unicode
ii  liblttng-ust-common1:arm64                                  2.13.1-1ubuntu1
  arm64        LTTng 2.0 Userspace Tracer (common library)
ii  liblttng-ust-ctl5:arm64                                     2.13.1-1ubuntu1
  arm64        LTTng 2.0 Userspace Tracer (trace control library)
ii  liblttng-ust1:arm64                                         2.13.1-1ubuntu1
  arm64        LTTng 2.0 Userspace Tracer (tracing libraries)
ii  libssl1.1:arm64                                             1.1.1f-1ubuntu2.16
  arm64        Secure Sockets Layer toolkit - shared libraries
ii  libssl3:arm64                                               3.0.2-0ubuntu1.7
  arm64        Secure Sockets Layer toolkit - shared libraries
ii  libstdc++-11-dev:arm64                                      11.3.0-1ubuntu1~22.04
  arm64        GNU Standard C++ Library v3 (development files)
ii  libstdc++6:arm64                                            12.1.0-2ubuntu1~22.04
  arm64        GNU Standard C++ Library v3
ii  libunwind8:arm64                                            1.3.2-2build2
  arm64        library to determine the call-chain of a program - runtime
ii  zlib1g:arm64                                                1:1.2.11.dfsg-2ubuntu9.2
  arm64        compression library - runtime
ii  zlib1g-dev:arm64                                            1:1.2.11.dfsg-2ubuntu9.2
  arm64        compression library - development
```

it is now installed too, but same segfault.

To be honest, I also read @MichaIng post on dietpi and... out of curiosity I checked Prowlarr (I didnt use that tool): Same error with recent versions, no error with old (+3 months), so not sure if code reuse between apps, build process issue or just plain corenet issue.

Thanks in advance,
Draakuns

**Comment by draakuns** [comment] 2023-01-07 02:26
I was also worried because of the mono apt repo installed (mono-runtime in use for sonarr), but I just remembered that is failing also on docker which is completely isolated, so makes absolutely no sense... unless something requires a new library since 2369 and it is also lacking on docker versions.

Just a late thought, sorry for the double post,
Draakuns

**Comment by draakuns** [comment] 2023-01-07 02:36
Can you please trigger a build (latest Jackett version, for instance) with the last good known NET version? Maybe 6.0.12 broke something and using 6.0.11 is ok...

```
16c16
<           "Jackett.Common": "0.20.2423",
---
>           "Jackett.Common": "0.20.2369",
25,26c25,26
<           "runtimepack.Microsoft.NETCore.App.Runtime.linux-arm64": "6.0.12",
<           "runtimepack.Microsoft.AspNetCore.App.Runtime.linux-arm64": "6.0.12"
---
>           "runtimepack.Microsoft.NETCore.App.Runtime.linux-arm64": "6.0.11",
>           "runtimepack.Microsoft.AspNetCore.App.Runtime.linux-arm64": "6.0.11"
```

night night!

**Comment by draakuns** [comment] 2023-01-07 02:52
net runtime 6.0.12 seems to be the culprit of the issue on both pieces of software (at least, I hope it is...)

Jackett works well until 2423 (first 6.0.12 coming from 6.0.11)
Prowlarr works well until 1.0.0.2171, first to bump to 6.0.12 from 6.0.6

Regards

**Comment by draakuns** [comment] 2023-01-07 02:58
Sorry, it's very late here... no more brainstorming for today, but it seems to be THIS: 

#https://github.com/dotnet/runtime/issues/79796

BR,
Draakuns

**Comment by MichaIng** [comment] 2023-01-07 03:23
@draakuns 
Great find! Which exact RPi model was it which fails? In our case it was RPi 3B+ and on the .NET issue you linked it's the same. One of our team couldn't replicate the issue on RPi 4 and some other SBCs, ARM VPS' and Apple M1 seem to be not affected as well.

**Comment by ilike2burnthing** [comment] 2023-01-07 03:30
You can get the test build of https://github.com/Jackett/Jackett/pull/13857 from [here](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/7313/artifacts?artifactName=drop&api-version=7.0&%24format=zip). See if that resolves your issue.

**Comment by draakuns** [comment] 2023-01-07 14:10
> @draakuns Great find! Which exact RPi model was it which fails? In our case it was RPi 3B+ and on the .NET issue you linked it's the same. One of our team couldn't replicate the issue on RPi 4 and some other SBCs, ARM VPS' and Apple M1 seem to be not affected as well.

It's not a raspi, but a pine64 A64+, quad core allwinner AARCH64 and 2Gb of ram. 


> You can get the test build of #13857 from [here](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/7313/artifacts?artifactName=drop&api-version=7.0&%24format=zip). See if that resolves your issue.

Yep @ilike2burnthing , this version works as expected... so .404 is the black sheep...

```
userrrr@mysbc:~/jackett/Jackett$ ./jackett
01-07 15:08:33 Info Starting Jackett v0.20.2511
01-07 15:08:39 Info Environment version: 6.0.11 (/home/xxxx/jackett/Jackett/)
01-07 15:08:39 Info OS version: Unix 5.15.80.64 (64bit OS) (64bit process)
01-07 15:08:39 Info Jackett variant: CoreLinuxArm64
01-07 15:08:39 Info File /etc/issue: Ubuntu 22.04.1 LTS \n \l
01-07 15:08:39 Info Running in Docker: No
01-07 15:08:39 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
01-07 15:08:39 Info App config/log directory: /home/xxxxx/.config/Jackett
01-07 15:08:39 Info Using proxy: Disabled
01-07 15:08:39 Info Using FlareSolverr: No
01-07 15:08:39 Info Using HTTP Client: HttpWebClient2
01-07 15:08:40 Info Loading Native indexers ...
```

;)

**Comment by ilike2burnthing** [comment] 2023-01-07 14:23
Will need to review when fixed by dotnet/runtime.

**Comment by draakuns** [comment] 2023-01-07 16:30
@ilike2burnthing when should we expect an "official" version using .403 instead of .404?

**Comment by ilike2burnthing** [comment] 2023-01-07 16:41
~14hrs

**Comment by ilike2burnthing** [comment] 2023-01-07 21:00
Another build for you to try - https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/7377/artifacts?artifactName=drop&api-version=7.0&%24format=zip

Updated to .net 7.0 which apparently works as well, according to https://github.com/dotnet/runtime/issues/79796.

**Comment by ilike2burnthing** [comment] 2023-01-08 06:09
[v0.20.2593](https://github.com/Jackett/Jackett/releases/v0.20.2593) (the official .403 build) is now out

**Comment by draakuns** [comment] 2023-01-08 15:55
Hi,

using the latest release you provided with net7 it seems to work.

```
:~/jackett/drop/Jackett$ ./jackett
01-08 16:51:12 Info Starting Jackett v0.21.1
01-08 16:51:18 Info Environment version: 7.0.1 (/home/xxxx/jackett/drop/Jackett/)
01-08 16:51:18 Info OS version: Unix 5.15.80.64 (64bit OS) (64bit process)
01-08 16:51:18 Info Jackett variant: CoreLinuxArm64
01-08 16:51:18 Info File /etc/issue: Ubuntu 22.04.1 LTS \n \l
01-08 16:51:18 Info Running in Docker: No
01-08 16:51:18 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
01-08 16:51:18 Info App config/log directory: /home/xxxx/.config/Jackett
01-08 16:51:18 Info Using proxy: Disabled
01-08 16:51:18 Info Using FlareSolverr: No
01-08 16:51:18 Info Using HTTP Client: HttpWebClient2
01-08 16:51:18 Info Loading Native indexers ...
```

Thanks,
Draakuns

**Comment by draakuns** [comment] 2023-01-08 16:17
An I went back to the latest stable build, now with the corrected corenet version


```
Jan 07 01:51:49 pine64 jackett[39644]: 01-07 01:51:49 Info Starting Jackett v0.20.2369
Jan 07 01:51:56 pine64 jackett[39644]: 01-07 01:51:56 Info Environment version: 6.0.11 (/home/apps/jackett/Jackett/)
Jan 07 01:51:56 pine64 jackett[39644]: 01-07 01:51:56 Info OS version: Unix 5.15.80.64 (64bit OS) (64bit process)
Jan 07 01:51:56 pine64 jackett[39644]: 01-07 01:51:56 Info Jackett variant: CoreLinuxArm64
Jan 07 01:51:56 pine64 jackett[39644]: 01-07 01:51:56 Info File /etc/issue: Ubuntu 22.04.1 LTS \n \l
Jan 07 01:51:56 pine64 jackett[39644]: 01-07 01:51:56 Info Running in Docker: No
Jan 07 01:51:56 pine64 jackett[39644]: 01-07 01:51:56 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Jan 07 01:51:56 pine64 jackett[39644]: 01-07 01:51:56 Info App config/log directory: /home/apps/.config/Jackett
Jan 07 01:51:56 pine64 jackett[39644]: 01-07 01:51:56 Info Using proxy: Disabled
Jan 07 01:51:56 pine64 jackett[39644]: 01-07 01:51:56 Info Using FlareSolverr: No
Jan 07 01:51:56 pine64 jackett[39644]: 01-07 01:51:56 Info Using HTTP Client: HttpWebClient2
Jan 07 01:51:56 pine64 jackett[39644]: 01-07 01:51:56 Info Loading Native indexers ...
```

Regards,
Draakuns

**Comment by MichaIng** [comment] 2023-01-14 13:31
> It's not a raspi, but a pine64 A64+, quad core allwinner AARCH64 and 2Gb of ram.

Very strange, on my NanoPi R2S with RK3328 which has Cortex-A53, same CPU like Allwinner A64 (PINE A64) and Broadcom BCM2710 (Raspberry Pi 3 variants). Tested on Debian Bullseye (where it failed for others), and with other Rockchip SoCs on Bullseye and Bookworm. So it's not the ARM CPU itself making the difference here, and not the OS alone 🤔.

**Comment by MichaIng** [comment] 2023-01-25 16:46
It seems to be fixed in SDK v6.0.405/runtime v6.0.13 btw. While I can now reproduce the segfault with SDK v6.0.405 `dotnet --version/--info` commands, as fast as `shared/Microsoft.NETCore.App/6.0.13` is added, the same commands succeed.

But I can test a v7 based Jackett as well, which sounds like the better path, going further forward?

**Comment by ilike2burnthing** [comment] 2023-01-25 17:11
@MichaIng and @draakuns if you can both test the latest build using [v6.0.405](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/7507/artifacts?artifactName=drop&api-version=7.0&%24format=zip), then we can close this issue (as v7 won't be happening any time soon).

**Comment by MichaIng** [comment] 2023-01-25 18:39
The contained `Jackett.Binaries.LinuxARM64.tar.gz` works here 👍.

**Closed** 2023-01-29 01:08 UTC
Labels: OS Linux / Mono / *nix, Ongoing

**Comment by ilike2burnthing** [comment] 2023-01-29 01:09
Merged. Next release will be out in ~5hrs. Worst case scenario, we re-revert it.

**Comment by garfield69** [comment] 2023-01-29 06:01
v0.20.2741

**Comment by MichaIng** [comment] 2023-01-29 13:39
The latest release works very well, many thanks!

**Comment by draakuns** [comment] 2023-01-29 17:25
Jackett Version v0.20.2741 working flawlessly... thanks a lot guys!

I hope net bug doesn't reproduce on new versions again
