### ISSUE TITLE
[yggtorrent] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by jyremar** [Jackett/Jackett#2289] opened 2017-12-16 07:38 UTC
Hello :) 

Failed testing tracker YggTorrent since this day (16/12/2017). It seems they changed back the tracker URL about this time (from https://ww1.yggtorrent.com to https://yggtorrent.com ). It used to work perfectly fine. 
Can anyone help? :)

Jackett version:  0.8.509.0

-------------------------------
Below are the logs :

2017-12-16 08:36:04.9123 Info   http://127.0.0.1:9118/api/v2.0/indexers/yggtorrent/config 
2017-12-16 08:36:04.9123 Info DefaultHttpControllerSelector SelectController Route='indexerId:yggtorrent,action:config,controller:IndexerApi' 
2017-12-16 08:36:04.9123 Info DefaultHttpControllerSelector SelectController IndexerApi 
2017-12-16 08:36:04.9123 Info HttpControllerDescriptor CreateController  
2017-12-16 08:36:04.9123 Info DefaultHttpControllerActivator Create  
2017-12-16 08:36:04.9123 Info DefaultHttpControllerActivator Create Jackett.Controllers.V20.IndexerApiController 
2017-12-16 08:36:04.9123 Info HttpControllerDescriptor CreateController Jackett.Controllers.V20.IndexerApiController 
2017-12-16 08:36:04.9123 Info IndexerApiController ExecuteAsync  
2017-12-16 08:36:04.9123 Info ApiControllerActionSelector SelectAction  
2017-12-16 08:36:04.9123 Info ApiControllerActionSelector SelectAction Selected action 'Config(ConfigItem[] config)' 
2017-12-16 08:36:04.9123 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-12-16 08:36:04.9123 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-12-16 08:36:04.9123 Info HttpActionBinding ExecuteBindingAsync  
2017-12-16 08:36:04.9123 Info FormatterParameterBinding ExecuteBindingAsync Binding parameter 'config' 
2017-12-16 08:36:04.9123 Info JsonMediaTypeFormatter ReadFromStreamAsync Type='ConfigItem[]', content-type='application/json' 
2017-12-16 08:36:04.9123 Info JsonMediaTypeFormatter ReadFromStreamAsync Value read='Jackett.Models.DTO.ConfigItem[]' 
2017-12-16 08:36:04.9123 Info FormatterParameterBinding ExecuteBindingAsync Parameter 'config' bound to the value 'Jackett.Models.DTO.ConfigItem[]' 
2017-12-16 08:36:04.9123 Info HttpActionBinding ExecuteBindingAsync Model state is valid. Values: config=Jackett.Models.DTO.ConfigItem[] 
2017-12-16 08:36:04.9123 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)' 
2017-12-16 08:36:04.9123 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2017-12-16 08:36:04.9123 Info RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)' 
2017-12-16 08:36:04.9123 Info RequiresIndexerAttribute OnActionExecutingAsync  
2017-12-16 08:36:04.9123 Info ApiControllerActionInvoker InvokeActionAsync Action='Config(config=Jackett.Models.DTO.ConfigItem[])' 
2017-12-16 08:36:04.9123 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Config(config=Jackett.Models.DTO.ConfigItem[])' 
2017-12-16 08:36:04.9123 Debug WebClient(HttpWebClient).GetString(Url:https://ww1.yggtorrent.com/user/login) 
2017-12-16 08:36:05.0414 Debug WebClient(HttpWebClient): Returning MovedPermanently => https://yggtorrent.com/user/login  
2017-12-16 08:36:05.0414 Debug WebClient(HttpWebClient).GetBytes(Url:https://yggtorrent.com/user/login) 
2017-12-16 08:36:05.1126 Debug WebClient(HttpWebClient): Returning OK => 13004 bytes 
2017-12-16 08:36:05.1146 Debug CardigannIndexer (yggtorrent): Cookies after login: __cfduid=d5abd0c2d4e762c7601cfb8ff8faa3d611513409754; ygg_sess=f7udcu3ev57uajdma000q8c30vie2d9i 
2017-12-16 08:36:05.1146 Debug WebClient(HttpWebClient).GetString(Url:https://ww1.yggtorrent.com/) 
2017-12-16 08:36:05.1628 Debug WebClient(HttpWebClient): Returning MovedPermanently => https://yggtorrent.com/  
2017-12-16 08:36:05.1628 Error ReflectedHttpActionDescriptor ExecuteAsync  
2017-12-16 08:36:05.1628 Error ApiControllerActionInvoker InvokeActionAsync  
2017-12-16 08:36:05.1628 Info RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)' 
2017-12-16 08:36:05.1628 Info RequiresIndexerAttribute OnActionExecutedAsync  
2017-12-16 08:36:05.1628 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)' 
2017-12-16 08:36:05.1628 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2017-12-16 08:36:05.1628 Info ApiExceptionHandler ExecuteExceptionFilterAsync  
2017-12-16 08:36:05.1628 Error Jackett.ExceptionWithConfigData: Login Failed, got redirected
   à Jackett.Indexers.CardigannIndexer.<TestLogin>d__16.MoveNext() dans C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:ligne 639
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Jackett.Indexers.CardigannIndexer.<ApplyConfiguration>d__20.MoveNext() dans C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:ligne 760
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Jackett.Controllers.V20.IndexerApiController.<UpdateConfig>d__10.MoveNext() dans C:\projects\jackett\src\Jackett\Controllers\IndexerApiController.cs:ligne 99
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() Jackett.ExceptionWithConfigData: Login Failed, got redirected
   à Jackett.Indexers.CardigannIndexer.<TestLogin>d__16.MoveNext() dans C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:ligne 639
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Jackett.Indexers.CardigannIndexer.<ApplyConfiguration>d__20.MoveNext() dans C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:ligne 760
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Jackett.Controllers.V20.IndexerApiController.<UpdateConfig>d__10.MoveNext() dans C:\projects\jackett\src\Jackett\Controllers\IndexerApiController.cs:ligne 99
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2017-12-16 08:36:05.1908 Info ApiExceptionHandler ExecuteExceptionFilterAsync  
2017-12-16 08:36:05.1908 Info IndexerApiController ExecuteAsync  
2017-12-16 08:36:05.1938 Info   Content-type='application/json; charset=utf-8', content-length=7437 
2017-12-16 08:36:05.1938 Info IndexerApiController Dispose  
2017-12-16 08:36:05.1938 Info IndexerApiController Dispose

**Comment by garfield69** [comment] 2017-12-16 07:39
upgrade Jackett to v0.8.514
Duplicate of #2283

**Closed by garfield69** 2017-12-16 07:39 UTC
