### ISSUE TITLE
demonoid: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13579] opened 2022-09-24 18:16 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett: v0.20.1951
Arch Linux
Docker: Yes
```

### Description

![image](https://user-images.githubusercontent.com/10577978/192112790-d11d4510-8864-4409-90fc-28fa0447991b.png)
![image](https://user-images.githubusercontent.com/10577978/192112810-38931e18-dbc2-4020-ade2-093a239f0d71.png)
![image](https://user-images.githubusercontent.com/10577978/192112831-a92190d9-e2b1-49ef-874e-88e61d7f8a22.png)

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment] 2022-09-24 18:18
you have raised this before.
closing as a duplicate of #13168

**Closed by garfield69** 2022-09-24 18:18 UTC
