### ISSUE TITLE
[horriblesubs] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by Ektorus** [Jackett/Jackett#3543] opened 2018-08-06 19:26 UTC
**Jackett version**:  0.9.41.0
**Mono version** (if not using Windows):  5.12.0.301
Mono JIT compiler version 5.12.0.301 (tarball Wed Jul 25 15:47:18 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

-------------------------------

Exception is "Found no results while trying to browse this tracker" when using HorribleSubs as tracker.
Full log is given here:
[log.txt](https://github.com/Jackett/Jackett/files/2263834/log.txt)

**Comment by Laniax** [comment] 2018-08-18 08:14
same issue here, any update on this?

**Comment by flightlevel** [comment] 2018-08-18 08:28
Duplicate of #3318

**Closed by flightlevel** 2018-08-18 08:28 UTC
