### ISSUE TITLE
[torrentdownloads] (testing) Exception (torrentdownloads): A task was canceled.: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

### ISSUE THREAD

**Issue by nickm324** [Jackett/Jackett#14188] opened 2023-03-24 06:16 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    998
User GID:    100
───────────────────────────────────────
[custom-init] No custom files found, skipping...
03-24 01:08:27 Info Starting Jackett v0.20.3671 
03-24 01:08:30 Info Environment version: 6.0.15 (/app/Jackett/) 
03-24 01:08:30 Info OS version: Unix 6.1.19.8 (64bit OS) (64bit process) 
03-24 01:08:30 Info Jackett variant: CoreLinuxMuslArm64 
03-24 01:08:30 Info File /etc/issue: Welcome to Alpine Linux 3.17 
03-24 01:08:30 Info Running in Docker: Yes (image build: v0.20.3671-ls98) 
03-24 01:08:30 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
03-24 01:08:30 Info App config/log directory: /config/Jackett 
03-24 01:08:30 Info Using proxy: Disabled 
03-24 01:08:30 Info Using FlareSolverr: No 
03-24 01:08:30 Info Using HTTP Client: HttpWebClient2 
03-24 01:08:30 Info Loading Native indexers ... 
03-24 01:08:30 Info Loaded 76 Native indexers: alpharatio, anidex, anidub, animebytes, animetorrents, aro, audiobookbay, avistaz, bakabt, beyond-hd-api, bithdtv, bjshare, brasiltracker, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, darmowetorenty, dicmusic, divxtotal, dontorrent, epublibre, erai-raws, exoticaz, filelist, funfile, gazellegames, gazellegamesapi, greatposterwall, hdbitsapi, hdspace, hdtorrents, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, myanonamouse, ncore, nebulanceapi, norbits, orpheus, passthepopcorn, piratethenet, pixelhd, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, secretcinema, sharewoodapi, shazbat, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentheaven, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, uniotaku, xspeeds, zonaq, animetosho, morethantv-api 
03-24 01:08:30 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions 
03-24 01:08:38 Info Loaded 494 Cardigann indexers: satclubbing, fuzer, gamestorrents, theempire, linkomanija, mnv, pixelcove2fa, teracod, peersfm, bulltorrent, generationfree-api, boxingtorrents, unionfansub, devil-torrents, pthome, 0magnet, crackingpatching, ilcorsaroblu, divteam, tvroad, RockBox, torrentkitty, puntotorrent, hdarea, majomparade, ebookbay, bluebirdhd, trupornolabs, anthelion-api, hdfans, torrent-pirat, nipponsei, soulvoice, mteamtp, u2, theshinning-api, femdomcult, bitded, 3changtrai, ebooks-shares, carpathians, crazyspirits, spidertk, peeratiko, sukebeinyaasi, xxxadulttorrent, brsociety-api, immortuos, siambit, estone, torrent9, asiandvdclub, torrentdownloads, torrentsir, torrentfunk, ydypt, bwtorrents, ilcorsaronero, xthor-api, animelayer, sktorrent, greekteam, theleachzone, backups, nethd, sugoimusic, mvgroupmain, torrentv, partis, punkshorror, p2pbg, extremebits, bitsearch, racing4everyone-api, elitetorrent-pl, pterclub, falkonvisionteam, moviesite, houseofdevil, firebit, finvip, knaben, bitru, digitalcore, torrent911, arabafenice, xxxtor, cpasbiensi, fantasticheaven, traht, hellashut, torrentproject2, cinemamovies, file-tracker, aniRena, hhanclub, blutopia-api, Bittorrentfiles, movietorrent, internetarchive, kickasstorrents-to, bitsexy, racingforme, libranet, aither-api, amigosshare, hdc, catorrent, eztv, glodls, uniongang, unleashthecartoons, hdgalaktik, bangumi-moe, sdbits, hdmayi, funkytorrents, concen, haitang, fenyarnyek-tracker, bt4g, miobt, rgfootball, hdforever, torrent-turk, concertos, broadcity, sharewood, dxp, bestcore, torrenthr, theoccult, diablotorrent, totheglory, arenabg, lepornoinfo, oshenpt, slosoul, torrentqq, hdatmos, hdzone, chilebt, torrentbd, gktorrent, bitturk, pornoslab, yggcookie, beitai, hd4fans, trancetraffic, ftuapps, resurrectthenet, limetorrents, btdigg, pignetwork, bitnova, xtorrenty, torrentgalaxy, selezen, empornium, jme-reunit3d-api, movietorrentz, torrentland, magicheaven, hdmonkey, pixelcove, rus-media, electro-torrent, speedtorrentreloaded, leech24, korsar, seedoff, abnormal, yggtorrent, itorrent, torrentccf, rainbowtracker, speedmasterhd, mteamtp2fa, tribalmixes, torrenting, reelflix-api, tapochek, xbytesv2, gay-torrentsorg, cpasbienclone, kickasstorrents-ws, datatalli, sexypics, jpopsuki, kinorun, bitspyder, pctorrent, solidtorrents, hdturk, badasstorrents, hdsky, sportscult, swarmazon-api, shareisland-api, pttime, esharenet, hqmusic, lat-team-api, 52pt, gtorrentpro, audionews, torrentsectorcrew, karagarga, puurhollands, dreamtracker, acgrip, totallykids, gimmepeers, 1ptbar, fantastiko, huntorrent, rustorka, torrentby, gaytorrentru, cartoonchaos, world-of-tomorrow, rintornet, seedfile, borgzelle, genesismovement, acidlounge, magico, 0daykiev, torrentz2eu, ourbits, tvchaosuk, mousebits, xiteme, ptchina, beyond-hd, moviesdvdr, torrent-explosiv, mma-torrents, torrentslocal, ehentai, les-cinephiles, anime-free, mikan, teamctgame, tasmanit, xwtclassics, newstudiol, finelite, wihd, joyhd, unlimitz, sosulki, losslessclub, hdtorrentsit, dariustracker, madsrevolution, hdchina, potuk, torlock, dimeadozen, piratbit, teamos, btmet, fanoin, turktorrent, rutor, learnbits, redstartorrent, newstudio, girotorrent, themixingbowl, lemonhd, xtremebytes, riperam, extratorrent-st, tjupt, torrent9clone, sktorrent-org, yourbittorrent, cinematik, showrss, crnaberza, torrentdownload, classix, thepiratebay, noname-clubl, sharkpt, thedarkcommunity, acervos, jav-torrent, indietorrents, zomb, lastfiles, rutracker-ru, uhdbits, thevault, hd-unit3d-api, lst, newretro, lightning-tor, hdolimpo-api, springsunday, ccfbits, learnflakes, animetracker, polishtracker-api, ihdbits, redbits-api, mactorrentsdownload, 3dtorrents, docspedia, danishbytes-api, mypornclub, keepfriends, mvgroupforum, demonoid, krazyzone, torrentlt, ptsbao, skipthecommercials-api, extremlymtorrents, romanianmetaltorrents, vsthouse, twilight, greekdiamond, byrbt, icc2022, aussierules, booktracker, zamundanet, kufirc, arabtorrents, theoldschool-api, pussytorrents, putao, exkinoray, freshmeat, bithumen, totheglorycookie, frozenlayer, happyfappy, the-crazy-ones, nicept, vsttorrents, megamixtracker, bigfangroup, pier720, muziekfabriek, rintor, oldtoonsworld, opencd, portugas-api, sporthd, bitofvalor, skipthetrailers, mixtapetorrent, bithorlo, polishsource, 1337x, rudub, 4thd, crazyhd, pornotorrent, mojblink, zelkaorg, animeworld-api, insanetracker, rapidzona, theplace, locadora, ceskeforum, bitbazis, vtorrent, audiences, 2xfree, gay-torrents, torrentcore, thegeeks, thenewfun, whiteangel, aftershock, hddolby, chdbits, acgsou, megapeer, torrentwhiz, thefallingangels, isohunt2, thesceneplace, limetorrentsclone, comicat, mesevilag, ptfiles, mircrew, carphunter, xxxtorrents, xwtorrents, filelisting, gainbound, abtorrents, hebits, turkseed, scenerush, asiancinema, coastalcrew, theshow, torrentleech-pl, desitorrents-api, pornbay, dmhy, hawke-uno, pwtorrents, jptv, linuxtracker, hdtime, byrutor, gigatorrents, torrentmasters, spiritofrevolution, discfan, anisource, uniondht, extremetorrents, marinetracker, empornium2fa, crt2fa, aidoruonline, proporno, trezzor, lesaloon, proaudiotorrents, tornado, 2fast4you, myspleen, hdonly, onejav, superbits, carpt, tellytorrent-api, deildu, cinemageddon, torrentseeds-api, torrentoyunindir, torrentz2nz, idope, tlfbits, cpasbien, rptorrents, tmghub, piratbitl, ex-torrenty, bootytape, anilibria, torrentview, mazepa, eniahd, ztracker, arabp2p, kamept, metaltracker, nyaasi, bibliotik, btetree, btnext, fluxzone, nntt, haidan, snowpt, zmpt, noname-club, hdu, hdroute, hdcztorrent, yts, dodder, kinozal, btschool, exttorrents, milkie, teamhd, helltorrents, acrossthetasman, tokyotosho, parnuxi, zetorrents, cathoderaytube, r3vwtf, shanaproject, tekno3d, btsow, torrentleech, hdhome, datascene-api 
03-24 01:08:38 Info Loaded 570 indexers in total 
03-24 01:08:38 Info Adding aggregate indexer ('all' indexer) ... 
03-24 01:08:38 Info Adding filter indexer ('type:public' indexer) ... 
03-24 01:08:38 Info Adding filter indexer ('type:private' indexer) ... 
03-24 01:08:38 Info Adding filter indexer ('type:semi-public' indexer) ... 
03-24 01:08:39 Info Jackett startup finished in 13.615 s 
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
[ls.io-init] done.
03-24 01:10:28 Error Jackett.Common.IndexerException: Exception (torrentdownloads): A task was canceled. Jackett.Common.IndexerException: Exception (torrentdownloads): A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 531
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1428
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 701
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 315
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Description

Indexer fails test. Have rebuilt the container, restarted the container. Was working at one point and nothing has changed, all other indexers pass the tests.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (torrentdownloads): A task was canceled.: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

![image](https://user-images.githubusercontent.com/6774571/227440248-c6a8f05b-c8c5-4d3f-8096-40576627046c.png)

**Comment by garfield69** [comment] 2023-03-24 06:35
Yes, the torrentdownloads web site is offline. 
Closing as a duplicate of #13291

**Closed by garfield69** 2023-03-24 06:35 UTC
