### ISSUE TITLE
[teamhd] Problems searching for seasons with brackets in the name

### ISSUE THREAD

**Issue by SoiledBrush** [Jackett/Jackett#9081] opened 2020-07-01 08:39 UTC
Theres is some problems parsing titles with brackets in it's season naming.
It is okay when i have to find the show only by name.
![firefox_15ANKsW49X](https://user-images.githubusercontent.com/43366389/86222805-89dbba80-bba8-11ea-95bc-9792bd968ff2.png)
But when i am searching through sonarr season has to be specified.
![firefox_xOhJAjq0V6](https://user-images.githubusercontent.com/43366389/86222850-9a8c3080-bba8-11ea-93c4-d36d58f41a68.png)
![firefox_nwq2FKthne](https://user-images.githubusercontent.com/43366389/86222864-9eb84e00-bba8-11ea-9a75-b76171defcb3.png)

 Jackett Version 0.16.771.0

**Comment by garfield69** [comment] 2020-07-01 19:14
none of the team have an account on this site so we cannot research independently.
If you send an invite to garfieldsixtynine -at- gmail.com we can work on this.

**Comment by garfield69** [comment] 2020-09-09 07:55
registration and login successful. thank you.

**Comment by garfield69** [comment] 2020-09-09 09:49
the issue is that the teamhd website search engine is looking for **exact** strings.
but the site does support searching with wildcards, using the percent symbol.

I've added this support to the indexer, which you can test when the next Jackett is released in about 22 hours.

**Closed** 2020-09-09 09:52 UTC

**Comment by garfield69** [comment] 2020-09-10 07:01
Jackett 0.16.1121
