### ISSUE TITLE
[noname-club] (testing) Exception (noname-club): The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by dshkoda32** [Jackett/Jackett#13416] opened 2022-07-30 08:19 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
2022-07-30 11:13:28	Info	
Using FlareSolverr: http://185.5.251.231:8191
2022-07-30 11:13:28	Info	
Using proxy: Disabled
2022-07-30 11:13:28	Info	
App config/log directory: /config/Jackett
2022-07-30 11:13:28	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-07-30 11:13:28	Info	
Running in Docker: Yes (image build: v0.20.1326-ls74)
2022-07-30 11:13:28	Info	
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-07-30 11:13:28	Info	
Jackett variant: CoreLinuxAmdx64
2022-07-30 11:13:28	Info	
OS version: Unix 5.4.0.122 (64bit OS) (64bit process)
2022-07-30 11:13:28	Info	
Environment version: 6.0.7 (/app/Jackett/
```

### Description

No test nonameclub

### Logged Error Messages

```text
---> FlareSolverrSharp.Exceptions.FlareSolverrException: Unsupported POST Content-Type: application/x-www-form-urlencoded
   at FlareSolverrSharp.Solvers.FlareSolverr.GenerateFlareSolverrRequest(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 516
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1406
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 680
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 315
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 147
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment] 2022-07-30 08:24
duplicate of #13304

**Comment by ilike2burnthing** [comment] 2022-07-31 16:33
[v0.20.1518](https://github.com/Jackett/Jackett/releases/v0.20.1518)

**Comment by dshkoda32** [comment] 2022-08-05 05:54
Until today, the nnmclub public worked and passed the test, now it asks to put flaresolverr, which I did, but an error still pops up with it
Exception (noname-club): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: No challenge selectors found, unable to proceed

**Comment by garfield69** [comment] 2022-08-05 06:01
please state the version of flaresolverr you are using, and the version of Jackett you are using.
It should be noted I have no issues using nnmclub public with jackett 0.20.1575 and flaresolverr v2.2.6

**Comment by dshkoda32** [comment] 2022-08-05 06:44
{"msg":"FlareSolverr is ready!","version":"v2.2.4","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"}

And how do I upgrade the version, I put it according to the instructions through docker

**Comment by garfield69** [comment] 2022-08-05 06:50
https://github.com/FlareSolverr/FlareSolverr#docker

**Comment by garfield69** [comment] 2022-08-05 06:51
`docker pull ghcr.io/flaresolverr/flaresolverr:v2.2.6`

**Comment by dshkoda32** [comment] 2022-08-05 07:12
Something is not updated, still version 2.2.4

**Comment by garfield69** [comment] 2022-08-05 07:14
@ilike2burnthing  docker, linux, flaresolverr, not my cup of tea. Help? ;-)

**Comment by dshkoda32** [comment] 2022-08-05 07:30
Yes

**Comment by ilike2burnthing** [comment] 2022-08-05 11:55
If you've specified `:v2.2.6` and it's still not updating then something is very wrong. Remove the FlareSolverr container and image and start from scratch using `:latest`.

**Comment by dshkoda32** [comment] 2022-08-05 12:26
Exception (noname-club): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

**Comment by ilike2burnthing** [comment] 2022-08-05 12:35
Do your Jackett and FlareSolverr share the same public IP address?

Are either using a proxy or VPN?

Disable IPv6 for both containers - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

Are you using a seedbox or VPS?

**Comment by dshkoda32** [comment] 2022-08-05 12:40
I use a vps. It has jackett and flaresolverr installed on the same ip. I don't use vpn and proxy

**Comment by ilike2burnthing** [comment] 2022-08-05 12:43
Have you disabled IPv6 for both containers? If not, do so following the instructions above.

**Comment by dshkoda32** [comment] 2022-08-05 14:51
Something still doesn't want to

**Comment by ilike2burnthing** [comment] 2022-08-05 21:55
Did you disable IPv6 for both containers?

**Comment by dshkoda32** [comment] 2022-08-06 09:02
Yes, of course

**Comment by ilike2burnthing** [comment] 2022-08-06 10:46
Add the indexer Badass Torrents and perform a search for `720p`. Do you get the same error?

**Comment by dshkoda32** [comment] 2022-08-06 19:46
No, test successful

**Comment by ilike2burnthing** [comment] 2022-08-06 20:48
FlareSolverr is working. I have gotten a few cases of invalid cookies, retrying multiple times tends to resolve it.

**Closed by ilike2burnthing** 2022-08-06 20:48 UTC
