### ISSUE TITLE
[torrent9] Exception (torrent9): Error: NameResolutionFailure: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by JoeSophia** [Jackett/Jackett#3581] opened 2018-08-13 08:04 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.9.41.0
**Mono version** (if not using Windows):  5.12.0.266
-------------------------------

**Comment by JoeSophia** [comment] 2018-08-13 08:09
So I create another one with the informations and you put as duplicate ....

**Comment by flightlevel** [comment] 2018-08-13 10:09
Duplicate of https://github.com/Jackett/Jackett/issues/3569

**Closed by flightlevel** 2018-08-13 10:09 UTC

**Comment by JoeSophia** [comment] 2018-08-21 07:52
Hi,
You say duplicate of #3569
But I already change the adress from www to www2.
I also try to delet the indexer and add it again but same issue.
Can you help me.

**Comment by flightlevel** [comment] 2018-08-21 10:32
@JoeSophia Are you running the latest version of Jackett?

**Comment by JoeSophia** [comment] 2018-08-21 12:27
Aug 21, 2018 02:25:13 PM | Info | New release found.  Current: v0.10.69 New: v0.10.97
-- | -- | --

Jackett.Common.IndexerException: Exception (torrent9): Error: NameResolutionFailure ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: NameResolutionFailure
  at System.Net.WebConnection+<Connect>d__16.MoveNext () [0x00044] in <8ee4894d1ff9491db5d213c2533abdee>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Net.WebConnection+<InitConnection>d__19.MoveNext () [0x000cc] in <8ee4894d1ff9491db5d213c2533abdee>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Net.WebOperation+<Run>d__57.MoveNext () [0x0009a] in <8ee4894d1ff9491db5d213c2533abdee>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebCompletionSource`1+<WaitForCompletion>d__15[T].MoveNext () [0x00094] in <8ee4894d1ff9491db5d213c2533abdee>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__244`1[T].MoveNext () [0x000ba] in <8ee4894d1ff9491db5d213c2533abdee>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x0001d] in <8ee4894d1ff9491db5d213c2533abdee>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <aaba9438a7604d738ea58a98d226c34b>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0041d] in <e848d4876d77418ea71de3499883d28d>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <e848d4876d77418ea71de3499883d28d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at CloudFlareUtilities.ClearanceHandler+<SendAsync>d__20.MoveNext () [0x0010c] in <d0213015414e4bf286b46bc1ee77bd72>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <e848d4876d77418ea71de3499883d28d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Jackett.Common.Utils.Clients.HttpWebClient+<Run>d__7.MoveNext () [0x00458] in <a6dd72e40d134dbe814896cc051dd01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Jackett.Common.Utils.Clients.WebClient+<GetString>d__18.MoveNext () [0x0010b] in <a6dd72e40d134dbe814896cc051dd01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Jackett.Common.Indexers.BaseWebIndexer+<RequestStringWithCookies>d__5.MoveNext () [0x000cb] in <a6dd72e40d134dbe814896cc051dd01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__29.MoveNext () [0x00827] in <a6dd72e40d134dbe814896cc051dd01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x00091] in <a6dd72e40d134dbe814896cc051dd01c>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x000ee] in <a6dd72e40d134dbe814896cc051dd01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x0006b] in <a6dd72e40d134dbe814896cc051dd01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x000a3] in <a6dd72e40d134dbe814896cc051dd01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Jackett.Server.Controllers.IndexerApiController+<Test>d__15.MoveNext () [0x000e1] in <ea54ad4f51d94d02ad6420ca62627196>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <51f5e57c3b1641ff921c58f55f777af6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <aaba9438a7604d738ea58a98d226c34b>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x0008a] in <ea54ad4f51d94d02ad6420ca62627196>:0
