### ISSUE TITLE
[hdtorrents] Object reference not set to an instance of an object. (Test)

### ISSUE THREAD

**Issue by stanilovic** [Jackett/Jackett#7871] opened 2020-03-27 07:41 UTC
### Environment

**OS**: Docker on Synology

**.Net Runtime**: whatever comes with Jackett docker

**.Net Version**: whatever comes with Jackett docker

**Jackett Version**: 0.14.297.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

With hd-torrents added (in the same way that has always worked previously), clicking "Test" results in a failure with error message. Similarly, clients such as Sonarr and Radarr cannot use hd-torrents via Jackett, when they have been working fine up until recently.

### Logged Error Messages

```
An error occured while testing this indexer
Object reference not set to an instance of an object.
```

```
Date | Level | Message
-- | -- | --
2020-03-27 08:33:49 | Error | System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Services.CacheService.<>c__DisplayClass3_1.<CacheRssResults>b__2(CachedResult i) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 35    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)    at Jackett.Common.Services.CacheService.CacheRssResults(IIndexer indexer, IEnumerable`1 releases) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 35    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 228    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2020-03-27 08:33:49 | Info | Found 15 releases from HD-Torrents
2020-03-27 08:32:41 | Error | System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Services.CacheService.<>c__DisplayClass4_1.<GetNewItemCount>b__1(CachedResult i) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 65    at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)    at Jackett.Common.Services.CacheService.GetNewItemCount(IIndexer indexer, IEnumerable`1 releases) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 65    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 378
2020-03-27 08:26:30 | Error | System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Services.CacheService.<>c__DisplayClass4_1.<GetNewItemCount>b__1(CachedResult i) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 65    at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)    at Jackett.Common.Services.CacheService.GetNewItemCount(IIndexer indexer, IEnumerable`1 releases) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 65    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 378
2020-03-27 08:15:47 | Info | Updates are disabled via --NoUpdates.
2020-03-27 07:56:13 | Error | System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Services.CacheService.<>c__DisplayClass4_1.<GetNewItemCount>b__1(CachedResult i) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 65    at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)    at Jackett.Common.Services.CacheService.GetNewItemCount(IIndexer indexer, IEnumerable`1 releases) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 65    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 378
2020-03-27 07:55:52 | Error | System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Services.CacheService.<>c__DisplayClass4_1.<GetNewItemCount>b__1(CachedResult i) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 65    at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)    at Jackett.Common.Services.CacheService.GetNewItemCount(IIndexer indexer, IEnumerable`1 releases) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 65    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 378
2020-03-27 07:40:42 | Error | System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Services.CacheService.<>c__DisplayClass4_1.<GetNewItemCount>b__1(CachedResult i) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 65    at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)    at Jackett.Common.Services.CacheService.GetNewItemCount(IIndexer indexer, IEnumerable`1 releases) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 65    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 378
2020-03-27 07:25:09 | Error | System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Services.CacheService.<>c__DisplayClass3_1.<CacheRssResults>b__2(CachedResult i) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 35    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)    at Jackett.Common.Services.CacheService.CacheRssResults(IIndexer indexer, IEnumerable`1 releases) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 35    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 379
```

**Comment by lepinkainen** [comment] 2020-03-27 07:45
Duplicate of #7870

**Closed** 2020-03-27 07:46 UTC

**Comment by garfield69** [comment] 2020-03-27 09:02
Jackett 0.14.299
