### ISSUE TITLE
FitGirl Repacks

### ISSUE THREAD

**Issue by HowFortuitous** [Jackett/Jackett#15681] opened 2024-10-31 20:41 UTC
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: FitGirl
- URL: https://fitgirl-repacks.site/
- Description: Video Games
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): None
- Additional Comments: There are a lot of scammers impersonating her content. I always feel like I'm gambling when I download from another site.
```

**Comment by garfield69** [comment] 2024-10-31 23:39
Duplicate of #6862

**Closed by garfield69** 2024-10-31 23:39 UTC
Labels: Duplicate
