### ISSUE TITLE
Feature request - allow disabling individual indexers

### ISSUE THREAD

**Issue by 07416** [Jackett/Jackett#7240] opened 2020-02-18 14:50 UTC
I mainly want to deselect specific indexers by default from the global search — some trackers are so specific that it makes no sense in using them for any general search term.

The only option at the time is removing indexers entirely, to my knowledge.

**Comment by ngosang** [comment] 2020-02-29 20:49
Duplicate of #661

**Closed by ngosang** 2020-02-29 20:49 UTC
