### ISSUE TITLE
[hdolimpo] There is a new tracker in the Spanish scene

### ISSUE THREAD

**Issue by skttbv** [Jackett/Jackett#6005] opened 2019-09-17 18:51 UTC
Hi recently a new tracker called hdolimpo has appeared with lots of movie premieres and it would be nice to add it to jackett.

The site name is https://hdolimpo.co/

Thanks a lot for your attention!

**Comment by garfield69** [comment] 2019-09-17 18:53
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment] 2019-10-03 05:58
duplicate of #5142

**Closed by garfield69** 2019-10-03 05:58 UTC
Labels: Invite needed, Private New Tracker

**Comment by killer1595** [comment] 2020-01-18 00:35
Can i get invite please ?

**Comment by garfield69** [comment] 2020-01-18 01:12
I'm sorry but I don't have any.
Also, this is a support site for the Jackett application and not a forum for invites.
There are dedicated sites for such requests, this is not one of them. Looks elsewhere.

**Comment by killer1595** [comment] 2020-01-18 01:14
ok thanx
i had account but when i try to login it says 403 error
any idea why ? and how tod download torrents

**Comment by garfield69** [comment] 2020-01-18 01:19
>i had account but when i try to login it says 403 error any idea why ? 

https://github.com/Jackett/Jackett/pull/6828#issuecomment-570904094

**Comment by killer1595** [comment] 2020-01-18 01:26
Actually i do not know what is this :/
so sad

**Comment by dorukhan84** [comment] 2020-01-19 08:41
Can i get invite please ?

**Comment by garfield69** [comment] 2020-01-19 09:33
@durukhan84 I'm sorry but I don't have any.
Also, this is a support site for the Jackett application and not a forum for invites.
There are dedicated sites for such requests, this is not one of them. Look elsewhere.

**Comment by garfield69** [comment] 2020-01-19 09:34
@dorukhan84 I'm sorry but I don't have any.
Also, this is a support site for the Jackett application and not a forum for invites.
There are dedicated sites for such requests, this is not one of them. Look elsewhere.
