### ISSUE TITLE
[isohunt2] (testing) Exception (isohunt2): Name or service not known: Name or service not known (isohunt.nz:443)

### ISSUE THREAD

**Issue by slrslr** [Jackett/Jackett#15693] opened 2024-11-07 06:03 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
-
```

### Description

The uptime service https://www.uptrends.com/tools/uptime reports down from everywhere.

### Logged Error Messages

```text
-
```

**Comment by garfield69** [comment] 2024-11-07 06:04
Duplicate of https://github.com/Jackett/Jackett/issues/2023#issuecomment-2438385006

**Closed by garfield69** 2024-11-07 06:04 UTC

**Comment by garfield69** [comment] 2024-11-07 06:06
FYI There is little point in reporting Public trackers as offline, I run a daily test on all public indexers and track their availability.

**Comment by slrslr** [comment] 2024-11-07 06:20
> little point in reporting Public trackers as offline

I hope that I will remember it, sorry for that.
The app suggested reporting and the https://github.com/Jackett/Jackett/wiki/Troubleshooting/#exception-indexer-no-such-host-is-known did not told me otherwise.

It may be handy if the indexer would be automatically disabled after it is down for lets say 14 days and if user can see in the indexers overview, how long each indexer has been unavailable during how many attempts. Based on that I can better decide whether I remove the indexer.

**Comment by garfield69** [comment] 2024-11-07 06:23
I flag the relevant creating ticket for an indexer that is offline with the label `down/waiting for removal`, and after 30 days in that state the indexer is deleted from Jackett.
