### ISSUE TITLE
[xspeeds] Exception (xspeeds): The method or operation is not implemented.: The method or operation is not implemented. (Test)

### ISSUE THREAD

**Issue by ab17182** [Jackett/Jackett#9602] opened 2020-09-22 14:04 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Synology DSM 6.2.3-25426 Update 2

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

{0} Jackett.Common.IndexerException: Exception (xspeeds): The method or operation is not implemented. ---> System.NotImplementedException: The method or operation is not implemented.
  at Jackett.Common.Utils.Clients.HttpWebClient.Run (Jackett.Common.Utils.Clients.WebRequest webRequest) [0x0015d] in <935832f0a63d41d8b450987970b9da42>:0 
  at Jackett.Common.Utils.Clients.WebClient.GetResultAsync (Jackett.Common.Utils.Clients.WebRequest request) [0x0010b] in <935832f0a63d41d8b450987970b9da42>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.WebRequestWithCookiesAsync (System.String url, System.String cookieOverride, Jackett.Common.Utils.Clients.RequestType method, System.String referer, System.Collections.Generic.IEnumerable`1[T] data, System.Collections.Generic.Dictionary`2[TKey,TValue] headers, System.String rawbody, System.Nullable`1[T] emulateBrowser) [0x00101] in <935832f0a63d41d8b450987970b9da42>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync (System.String url, System.String cookieOverride, Jackett.Common.Utils.Clients.RequestType method, System.String referer, System.Collections.Generic.IEnumerable`1[T] data, System.Collections.Generic.Dictionary`2[TKey,TValue] headers, System.String rawbody, System.Nullable`1[T] emulateBrowser) [0x0017d] in <935832f0a63d41d8b450987970b9da42>:0 
  at Jackett.Common.Indexers.XSpeeds.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00163] in <935832f0a63d41d8b450987970b9da42>:0 
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x00091] in <935832f0a63d41d8b450987970b9da42>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x000ee] in <935832f0a63d41d8b450987970b9da42>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x0006b] in <935832f0a63d41d8b450987970b9da42>:0 
  at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x000a3] in <935832f0a63d41d8b450987970b9da42>:0 
  at Jackett.Server.Controllers.IndexerApiController.Test () [0x000e1] in <fb51ba0f49e14c3f8f117f9cb0a4dcee>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <fb51ba0f49e14c3f8f117f9cb0a4dcee>:0

### Screenshots

![image](https://user-images.githubusercontent.com/46659262/93892827-f43d5c00-fcba-11ea-9db5-d8598f39d04c.png)

**Comment by ab17182** [comment] 2020-09-22 14:04
Jackett Version 0.16.1260.0

**Comment by DFW-Noob** [comment] 2020-09-22 14:17
i'm also having the same problem

**Comment by Skyphox42** [comment] 2020-09-22 14:32
Having the same problem here... all torrent sites. Also generates the same error in the logs when attempting an update.

FreeNAS version here.

**Comment by cezarq** [comment] 2020-09-22 14:58
Some Problem. Using FreeNAS

**Comment by tigger29900** [comment] 2020-09-22 15:31
Same here on FreeNAS

**Comment by ab17182** [comment] 2020-09-22 15:41
Glad I wasn't the only one.  Thought I was going crazy and was going to
uninstall/reinstall but then held off thinking that there weren't any
changes to the system (hence the post here).

**Comment by h0m35t4r** [comment] 2020-09-22 17:00
This may have to do with an outdated Mono version. The FreeNAS package for Mono is woefully outdated and stuck at 5.10

**Comment by cezarq** [comment] 2020-09-22 17:04
> This may have to do with an outdated Mono version. The FreeNAS package for Mono is woefully outdated and stuck at 5.10

Do you have any suggestion to fix it?

**Comment by h0m35t4r** [comment] 2020-09-22 17:08
I just tried the following on my FreeNAS installation and Jackett seems to be working again. I am also using Sonarr and Radarr and they appear to be working

pkg install libiconv
wget https://github.com/jailmanager/jailmanager.github.io/releases/download/v0.0.1/mono-6.8.0.105.txz
pkg install -y mono-6.8.0.105.txz

https://www.ixsystems.com/community/threads/how-to-manually-upgrade-mono-from-5-10-to-5-20-in-a-freenas-jail.78871/post-597815

**Comment by ab17182** [comment] 2020-09-22 17:12
https://www.reddit.com/r/synology/comments/iugcbu/synology_sonarrradarrnzbgetindexers_tls_issue/
<-- looks similar to the issues we have been having.  Synology's Mono
release for myself is 5.20.1.34-13.

**Comment by ab17182** [comment] 2020-09-22 17:23
https://synocommunity.com/package/mono -  as a follow-up, I can see a "-14
release" as per here:

Version 5.20.1.34-14Update to version 5.20.1.34Date2020-09-20
22:11:45.727145Architectures6.1 apollolake
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 avoton
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 braswell
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 broadwell
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 broadwellnk
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 bromolow
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 cedarview
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 denverton
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 dockerx64
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 geminilake
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 grantley
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 purley
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 kvmx64
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 x86
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>
 6.1 x86_64
<https://packages.synocommunity.com/mono/14/mono.v14.f15047[apollolake-avoton-braswell-broadwell-broadwellnk-bromolow-cedarview-denverton-dockerx64-geminilake-grantley-purley-kvmx64-x86-x86_64].spk>

The issue is that they don't have a "evansport" release which is for my
chipset (I have a DS214play).  I assume if there was a port for my model,
I'd be good to go by just downloading and installing over SSH but am stuck
since there's no port yet.

**Comment by cezarq** [comment] 2020-09-22 17:50
> I just tried the following on my FreeNAS installation and Jackett seems to be working again. I am also using Sonarr and Radarr and they appear to be working. You may be able to omit the first command on your particular installation
> 
> **pkg install libiconv wget https://github.com/jailmanager/jailmanager.github.io/releases/download/v0.0.1/mono-6.8.0.105.txz pkg install -y mono-6.8.0.105.txz**
> 
> https://www.ixsystems.com/community/threads/how-to-manually-upgrade-mono-from-5-10-to-5-20-in-a-freenas-jail.78871/post-597815


root@Jackett:~ # pkg install mono-6.8.0.105.txz
Updating iocage-plugins repository catalogue...
iocage-plugins repository is up to date.
All repositories are up to date.
Checking integrity

The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        mono: 6.8.0.105

Number of packages to be installed: 1

The process will require 267 MiB more space.

Proceed with this action? [y/N]: y
[Jackett] [1/1] Installing mono-6.8.0.105...
[Jackett] Extracting mono-6.8.0.105: 100%
=====
Message from mono-6.8.0.105:

--
If you have build/runtime errors with Mono and Gtk# apps please try the
following first:

* Build Mono and gtk+ (x11-toolkits/gtk20) without CPUTYPE and with the
  default FreeBSD CFLAGS ('-O2 -fno-strict-aliasing -pipe') as Mono has
  been known to expose compiler bugs.

* Try building and running Mono with the GENERIC kernel.
  - Mono requires SYSVSHM, SYSVMSG, and SYSVSEM which are part of the
    GENERIC kernel.
  - Removing kernel options or changing defaults to use experimental
    options can adversely affect Mono's ability to build and run.

* Remove leftover semaphores / increase semaphore limits.
  - Close apps which use Mono and run `ipcs -sbt`.  Remove the
    semaphores with MODE "--rw-------" and NSEMS "8" using ipcrm (1)
  - _OR_ simply reboot which is the safest method.
  - On multi-user systems the semaphore limits may need to be increased
    from the defaults. The following should comfortably support 30 users.

    # echo "kern.ipc.semmni=40" >> /boot/loader.conf
    # echo "kern.ipc.semmns=300" >> /boot/loader.conf

**Comment by Skyphox42** [comment] 2020-09-22 18:09
The above method worked for me too. Just had to install wget first in the jail with **pkg install wget**

**Comment by cezarq** [comment] 2020-09-22 18:18
> The above method worked for me too. Just had to install wget first in the jail with **pkg install wget**

Are you running the Jackett on a FreeNAS jail?

**Comment by ab17182** [comment] 2020-09-22 18:21
FreeNAS +1 - Synology (Evansport chipset) 0
;-)
I'm stuck as this would need to be compiled for this platform
unfortunately.  Wish I did FreeNAS years ago.  Good news though and good
find Riccardo.  Thanks for the info as it'll get a majority of people going.

**Comment by nhsqr** [comment] 2020-09-22 18:29
I also have Synology and I have the same problem.
I really don't want to migrate Jackett to Docker so I hope this will be fixed

**Comment by Skyphox42** [comment] 2020-09-22 18:35
> > The above method worked for me too. Just had to install wget first in the jail with **pkg install wget**
> 
> Are you running the Jackett on a FreeNAS jail?

Yes, that was within a FreeNAS jail.

**Comment by cezarq** [comment] 2020-09-22 18:37
> > > The above method worked for me too. Just had to install wget first in the jail with **pkg install wget**
> > 
> > 
> > Are you running the Jackett on a FreeNAS jail?
> 
> Yes, that was within a FreeNAS jail.

Did you have to enable something to install the mono 6.8.0.15? I am asking because, I am also running on the FreeNAS jail and I am getting errors to install

**Comment by garfield69** [comment] 2020-09-22 18:45
Guys, this is a duplicate of #9569 which was resolved 20 hours ago.
For those who cannot update their mono, manually upgrade Jackett to 0.16.1307 to resolve the problem.
For those on Syno see https://github.com/Jackett/Jackett/issues/9569#issuecomment-696438169
For those on Qnap NAS see https://github.com/Jackett/Jackett/issues/9569#issuecomment-696409682

**Closed by garfield69** 2020-09-22 18:45 UTC

**Comment by Skyphox42** [comment] 2020-09-22 18:53
> > > > The above method worked for me too. Just had to install wget first in the jail with **pkg install wget**
> > > 
> > > 
> > > Are you running the Jackett on a FreeNAS jail?
> > 
> > 
> > Yes, that was within a FreeNAS jail.
> 
> Did you have to enable something to install the mono 6.8.0.15? I am asking because, I am also running on the FreeNAS jail and I am getting errors to install

No error that i recall. 
From within the jail just did the follow based on what was said above.:

pkg install libiconv
pkg install wget
wget https://github.com/jailmanager/jailmanager.github.io/releases/download/v0.0.1/mono-6.8.0.105.txz
pkg install mono-6.8.0.105.txz

What error you seeing?

**Comment by cezarq** [comment] 2020-09-22 19:02
> pkg install libiconv
> pkg install wget
> wget https://github.com/jailmanager/jailmanager.github.io/releases/download/v0.0.1/mono-6.8.0.105.txz
> pkg install mono-6.8.0.105.txz
> 
> What error you seeing?

root@Jackett:~ # pkg install mono-6.8.0.105.txz
Updating iocage-plugins repository catalogue...
iocage-plugins repository is up to date.
All repositories are up to date.
Checking integrity

The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
mono: 6.8.0.105

Number of packages to be installed: 1

The process will require 267 MiB more space.

Proceed with this action? [y/N]: y
[Jackett] [1/1] Installing mono-6.8.0.105...
[Jackett] Extracting mono-6.8.0.105: 100%
Message from mono-6.8.0.105:

--
If you have build/runtime errors with Mono and Gtk# apps please try the
following first:

Build Mono and gtk+ (x11-toolkits/gtk20) without CPUTYPE and with the
default FreeBSD CFLAGS ('-O2 -fno-strict-aliasing -pipe') as Mono has
been known to expose compiler bugs.

Try building and running Mono with the GENERIC kernel.

Mono requires SYSVSHM, SYSVMSG, and SYSVSEM which are part of the
GENERIC kernel.
Removing kernel options or changing defaults to use experimental
options can adversely affect Mono's ability to build and run.
Remove leftover semaphores / increase semaphore limits.

Close apps which use Mono and run ipcs -sbt. Remove the
semaphores with MODE "--rw-------" and NSEMS "8" using ipcrm (1)

OR simply reboot which is the safest method.

On multi-user systems the semaphore limits may need to be increased
from the defaults. The following should comfortably support 30 users.

echo "kern.ipc.semmni=40" >> /boot/loader.conf
echo "kern.ipc.semmns=300" >> /boot/loader.conf

**Comment by Skyphox42** [comment] 2020-09-22 19:07
That looks like it has worked to me. The end part is a 'notice' I think. Reboot the jail and see if it works.
