### ISSUE TITLE
[ncore] Exception (ncore): Object reference not set to an instance of an object: Parse error (Test)

### ISSUE THREAD

**Issue by felho001** [Jackett/Jackett#7462] opened 2020-03-02 18:32 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.
ncore.cc not working can you tell me why?
Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Synology

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:v0.13.405

**Last Working Jackett Version**:pass

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]
Jackett.Common.IndexerException: Exception (ncore): Object reference not set to an instance of an object ---> System.Exception: Parse error ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Jackett.Common.Indexers.NCore.parseTorrents (Jackett.Common.Utils.Clients.WebClientStringResult results, System.String seasonep, Jackett.Common.Models.TorznabQuery query, System.Int32 already_founded, System.Int32 limit, System.Int32 previously_parsed_on_page) [0x00295] in <71a3ea8ca7e34649b5f1361911eb9552>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseWebIndexer.OnParseError (System.String results, System.Exception ex) [0x00064] in <71a3ea8ca7e34649b5f1361911eb9552>:0 
  at Jackett.Common.Indexers.NCore.parseTorrents (Jackett.Common.Utils.Clients.WebClientStringResult results, System.String seasonep, Jackett.Common.Models.TorznabQuery query, System.Int32 already_founded, System.Int32 limit, System.Int32 previously_parsed_on_page) [0x005d9] in <71a3ea8ca7e34649b5f1361911eb9552>:0 
  at Jackett.Common.Indexers.NCore.PerformQuery (Jackett.Common.Models.TorznabQuery query, System.String seasonep) [0x00496] in <71a3ea8ca7e34649b5f1361911eb9552>:0 
  at Jackett.Common.Indexers.NCore.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00076] in <71a3ea8ca7e34649b5f1361911eb9552>:0 
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x00091] in <71a3ea8ca7e34649b5f1361911eb9552>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x000ee] in <71a3ea8ca7e34649b5f1361911eb9552>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x0006b] in <71a3ea8ca7e34649b5f1361911eb9552>:0 
  at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x000a3] in <71a3ea8ca7e34649b5f1361911eb9552>:0 
  at Jackett.Server.Controllers.IndexerApiController.Test () [0x000e1] in <c8ef74bd2aa4425d9c96f31d588926df>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <c8ef74bd2aa4425d9c96f31d588926df>:0

**Comment by ngosang** [comment] 2020-03-02 18:34
Duplicate of #7444

Could you help me with that https://github.com/Jackett/Jackett/issues/7444#issuecomment-593549898 ?

**Closed by ngosang** 2020-03-02 18:34 UTC
