### ISSUE TITLE
Cannot connect to Xspeeds

### ISSUE THREAD

**Issue by antigravity83** [Jackett/Jackett#1839] opened 2017-09-16 08:39 UTC
Jackett version: 0.8.199.0
Logs: https://pastebin.com/DJ3CA79M

Can't login to Xspeeds. 

Get "Login Locked! (the maximum number of failed Login attempts is reached during reauthentication)" error, and then:
"We come to believe you are trying to cheat our system, therefore we've banned your ip!"

This only happens with Xspeeds.

When logging in directly on website, login details work fine.

**Comment by kaso17** [comment] 2017-09-17 13:15
dupe of #1746
It's working fine for me, is there anything special about your account? Any special characters in the password/username?

**Comment by antigravity83** [comment] 2017-09-17 21:14
Nope, just letters and numbers. 

I've had Xspeeds unblock my IP 3 times

**Comment by antigravity83** [comment] 2017-09-17 21:15
Can I send you my username and password and see if it works on your end?

**Comment by kaso17** [comment] 2017-09-19 09:41
Please send it to kaso1717 -at- gmail.com

**Comment by antigravity83** [comment] 2017-10-09 02:47
Still getting blocked by Jackett.

Spoke to Xspeeds and they said:

Hey there,
Checked and that IP is not on our list. Try clearing your cache and cookies, maybe restart your router/modem.

I've reset my machine. Unsure how to reset cookies/cache for Jackett?

**Comment by garfield69** [comment] 2017-11-15 19:52
>Unsure how to reset cookies/cache for Jackett?     

Try this, it will remove what info Jackett has about XSpeeds and you will need to add the indexer anew:

- Shutdown the Jackett service
- Navigate to `%ProgramData%\Jackett\Indexers` on Windows or `~/.config/Jackett/Indexers` for MacOs/Linux and delete the `XSpeeds.json` and `XSpeeds.json.bak` files if present.
- Startup the Jackett Service
- Add the XSpeeds indexer and try to login

**Comment by garfield69** [comment] 2017-12-09 19:01
No feedback presumes its resolved. Closing.

**Closed by garfield69** 2017-12-09 19:01 UTC
