### ISSUE TITLE
[Bug] Cannot configure BIGTorrent

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#4782] opened 2019-02-27 11:54 UTC
I get the following error when trying to configure BigTorrent in Jackett:

An error occurred while testing this indexer
Found no results while trying to browse this tracker

Enhanced log attached. Thanks!
[log.txt](https://github.com/Jackett/Jackett/files/2910128/log.txt)

**Jackett version**: Jackett Version 0.10.842.0 
**Mono version** (if not using Windows): N/A

-------------------------------

**Comment by garfield69** [comment] 2019-02-27 19:47
closing as dupe of #1219 which has been reopened.

**Closed by garfield69** 2019-02-27 19:47 UTC
