### ISSUE TITLE
[katcr.co] incapsula blocking test request

### ISSUE THREAD

**Issue by kaysond** [Jackett/Jackett#2447] opened 2018-01-20 09:17 UTC
Did a quick test on 0.8.602.0 w/ mono 4.6.2.7 and it looks like incapusla is blocking the request
```
2018-01-20 01:12:20.6644 Info   http://192.168.1.2:9117/api/v2.0/indexers/kickasstorrent/test
2018-01-20 01:12:20.6644 Info DefaultHttpControllerSelector SelectController Route='indexerId:kickasstorrent,action:test,controller:IndexerApi'
2018-01-20 01:12:20.6650 Info DefaultHttpControllerSelector SelectController IndexerApi
2018-01-20 01:12:20.6650 Info HttpControllerDescriptor CreateController
2018-01-20 01:12:20.6650 Info DefaultHttpControllerActivator Create
2018-01-20 01:12:20.6650 Info DefaultHttpControllerActivator Create Jackett.Controllers.V20.IndexerApiController
2018-01-20 01:12:20.6650 Info HttpControllerDescriptor CreateController Jackett.Controllers.V20.IndexerApiController
2018-01-20 01:12:20.6660 Info IndexerApiController ExecuteAsync
2018-01-20 01:12:20.6660 Info ApiControllerActionSelector SelectAction
2018-01-20 01:12:20.6660 Info ApiControllerActionSelector SelectAction Selected action 'Test()'
2018-01-20 01:12:20.6660 Info JackettAuthorizedAttribute OnAuthorizationAsync
2018-01-20 01:12:20.6670 Info JackettAuthorizedAttribute OnAuthorizationAsync
2018-01-20 01:12:20.6670 Info HttpActionBinding ExecuteBindingAsync
2018-01-20 01:12:20.6670 Info HttpActionBinding ExecuteBindingAsync
2018-01-20 01:12:20.6670 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
2018-01-20 01:12:20.6670 Info JackettAPINoCacheAttribute OnActionExecutingAsync
2018-01-20 01:12:20.6680 Info RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Test()'
2018-01-20 01:12:20.6680 Info RequiresIndexerAttribute OnActionExecutingAsync
2018-01-20 01:12:20.6680 Info ApiControllerActionInvoker InvokeActionAsync Action='Test()'
2018-01-20 01:12:20.6680 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
2018-01-20 01:12:20.6691 Debug WebClient(UnixLibCurlWebClient).GetString(Url:https://katcr.co/torrents/top-100-latest-uploads.html)
2018-01-20 01:12:21.3001 Debug WebClient(UnixLibCurlWebClient): Returning Forbidden => <html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3"></script></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?CWUDNSAI=18&xinfo=9-820319302-0%200NNN%20RT%281516439540192%20327%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B15%284%2c200%2c0%29%20U12&incident_id=453000201089461527-3124114242832499017&edet=15&cinfo=04000000" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 453000201089461527-3124114242832499017</iframe></body></html>
2018-01-20 01:12:21.3013 Info Found 0 releases from KickAssTorrent
```

**Comment by garfield69** [comment] 2018-01-20 20:15
Duplicate of #2280

**Closed by garfield69** 2018-01-20 20:15 UTC

**Comment by kaysond** [comment] 2018-01-20 20:57
whoops sorry. i did search for this but i mustve fat fingered it
