### ISSUE TITLE
[yggtorrent] Test search in YGGtorrent => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Pollu0x** [Jackett/Jackett#13135] opened 2022-04-10 18:40 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-04-10 20:17:35	Info	
Jackett startup finished in 9.375 s
2022-04-10 20:17:35	Info	
Adding filter indexer ('type:semi-public' indexer) ...
2022-04-10 20:17:35	Info	
Adding filter indexer ('type:private' indexer) ...
2022-04-10 20:17:35	Info	
Adding filter indexer ('type:public' indexer) ...
2022-04-10 20:17:35	Info	
Adding aggregate indexer ('all' indexer) ...
2022-04-10 20:17:35	Info	
Loaded 580 indexers in total
2022-04-10 20:17:35	Info	
Loaded 496 Cardigann indexers: 0daykiev, 0magnet, 1337x, 1ptbar, 24rolika, 2fast4you, 3changtrai, 3dtorrents, 4thd, 52pt, Bittorrentfiles, abtorrents, acgrip, acgsou, acidlounge, acrossthetasman, aftershock, aidoruonline, aither-api, alleenretail, amigosshare, anaschcc, anilibria, anime-free, animeclipse, animeitalia, animelayer, animeworld-api, aniRena, anisource, arabafenice, arabp2p, arenabg, asiancinema, audiobookbay, audionews, aussierules, backups, badasstorrents, bangumi-moe, beitai, bestcore, beyond-hd, bibliotik, bigfangroup, bitbazis, bitbr, bitcityreloaded, bitded, bithorlo, bithumen, bitru, bitsearch, bitsexy, bitspyder, bitturk, bluebirdhd, bluesbrothers, blutopia-api, booktracker, bootytape, borgzelle, boxingtorrents, brasiltracker, broadcity, brsociety-api, bt4g, btdigg, btetree, btnext, btschool, btsow, bwtorrents, byrbt, byrutor, carpathians, carphunter, cartoonchaos, cathoderaytube, catorrent, ccfbits, ceskeforum, chdbits, chilebt, cinemageddon, cinemamovies, cinematik, classix, coastalcrew, comicat, concen, concertos, cpasbien, cpasbienclone, crackingpatching, crazyhd, crazyspirits, crnaberza, crt2fa, cryptichaven, danishbytes-api, dariustracker, dark-shadow, datascene-api, datatalli, deildu, demonoid, desitorrents-api, diablotorrent, digitalcore, dimeadozen, discfan, divteam, dmhy, docspedia, dragonworldreloaded, dxp, ebookparadijs, ebooks-shares, ehentai, elitetorrent-biz, empornium, empornium2fa, eniahd, esharenet, estone, exkinoray, extratorrent-st, extremebits, extremetorrents, extremlymtorrents, exttorrents, eztv, falkonvisionteam, fanoin, fantasticheaven, fantastiko, femdomcult, fenyarnyek-tracker, filelisting, film-paleis, finelite, finvip, firebit, fouducinema, freshmeat, frozenlayer, ftuapps, funkytorrents, gamestorrents, gay-torrents, gay-torrentsorg, gaytorrentru, generationfree-api, genesismovement, gfxpeers, gigatorrents, girotorrent, gktorrent, glodls, greekdiamond, greekteam, gtorrentpro, haidan, haitang, hamsterstudio, happyfappy, hawke-uno, hd4fans, hdai, hdarea, hdatmos, hdbits, hdbitscom, hdc, hdcenter, hdchina, hdcity, hdcztorrent, hddolby, hdforever, hdhome, hdme, hdmonkey, hdolimpo-api, hdonly, hdroute, hdsky, hdspain, hdtime, hdtorrentsit, hdturk, hdu, hdzone, hellastz, hidden-palace, houseofdevil, hqsource, huntorrent, ibit, idope, ilcorsaroblu, ilcorsaronero, ilcorsaroverde, immortuos, indietorrents, insanetracker, internetarchive, isohunt2, itorrent, iv-torrents, jav-torrent, jme-reunit3d-api, jpopsuki, jptv, karagarga, keepfriends, kickasstorrents-to, kickasstorrents-ws, kinonavse100, kinorun, kinozal, korsar, krazyzone, lastfiles, lat-team-api, learnbits, learnflakes, leech24, legittorrents, lemonhd, lepornoinfo, lesaloon, libranet, limetorrents, limetorrentsclone, linkomanija, linuxtracker, losslessclub, mactorrentsdownload, madsrevolution, magicheaven, magico, majomparade, marinetracker, mediamaatjes, megamixtracker, megapeer, mesevilag, metaltracker, microbit, mikan, milkie, miobt, mircrew, mixtapetorrent, mma-torrents, mnv, mononokebt, mousebits, moviesdvdr, moviesite, movietorrent, movietorrentz, mteamtp, mteamtp2fa, muziekfabriek, mvgroupforum, mvgroupmain, mypornclub, myspleen, nbtorrents, netcosmo, nethd, netlab, newpct-me, newretro, newstudio, newstudiol, nipponsei, nitro, nntt, noname-club, noname-clubl, nyaasi, omgwtftrackr, onejav, opencd, opensharing, oshenpt, ourbits, oxtorrent, p2pbg, p2pelite, parnuxi, pctorrent, peeratiko, peerjunkies, peersfm, pier720, piratadigital, piratbit, piratbitl, pixelcove, polishsource, pornbay, pornbits, pornforall, pornleech, pornolive, pornoslab, pornotor, pornotorrent, portugas, potuk, proaudiotorrents, proporno, prostylex, pterclub, ptfiles, pthome, ptmsg, ptsbao, pttime, punkshorror, puntotorrent, purovicio, pussytorrents, putao, puurhollands, pwtorrents, r3vwtf, racing4everyone-api, racingforme, rainbowtracker, rapidzona, redbits-api, redstartorrent, reelflix-api, resurrectthenet, rgfootball, rintor, rintornet, riperam, RockBox, romanianmetaltorrents, rptorrents, rudub, rus-media, rustorka, rutor, rutracker-ru, scenepalace, scenerush, sdbits, seedfile, selezen, sexypics, shareisland-api, sharewood, showrss, siambit, skipthecommercials-api, skipthetrailers, sktorrent-org, sktorrent, slosoul, snowpt, solidtorrents, sosulki, soulvoice, soundpark, speedmasterhd, speedtorrentreloaded, spidertk, spiritofrevolution, sporthd, sportscult, springsunday, sugoimusic, sukebeinyaasi, superbits, swarmazon, tapochek, tasmanit, teamctgame, teamhd, teamos, tekno3d, tellytorrent-api, teracod, the-crazy-ones, theaudioscene, theempire, thefallingangels, thegeeks, thehorrorcharnel, theleachzone, themixingbowl, thenewfun, theoccult, thepiratebay, theplace, thesceneplace, theshinning, theshow, thevault, tjupt, tlfbits, tokyotosho, torlock, torlook, torrent-explosiv, torrent-pirat, torrent-turk, torrent9, torrent9clone, torrentbd, torrentby, torrentccf, torrentdb, torrentdownload, torrentdownloads, torrentfunk, torrentgalaxy, torrenthr, torrenting, torrentkitty, torrentland-api, torrentleech-pl, torrentleech, torrentlt, torrentmasters, torrentoyunindir, torrentparadise, torrentproject2, torrentqq, torrentsectorcrew, torrentseeds-api, torrentsir, torrentslocal, torrentsurf, torrentv, torrentview, torrentwhiz, torrentz2eu, totallykids, totheglory, totheglorycookie, trackeros-api, trancetraffic, trezzor, tribalmixes, trupornolabs, turkseed, turktorrent, turktracker, tvchaosuk, tvroad, twilight, twilightszoom, u2, uhdbits, underverse, underversel, uniondht, unionfansub, uniongang, unlimitz, vizuk, vsthouse, vsttorrents, wdt, whiteangel, wihd, woot, xiteme, xbit, xbytesv2, xthor-api, xwtclassics, xwtorrents, xxxadulttorrent, xxxtor, xxxtorrents, ydypt, yggcookie, yggtorrent, yourbittorrent, yts, zamundanet, zelkaorg, zetorrents, zomb, zooqle, ztracker
2022-04-10 20:17:31	Info	
Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
2022-04-10 20:17:31	Info	
Loaded 84 Native indexers: abnormal, alpharatio, anidex, anidub, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, beyond-hd-api, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, darmowetorenty, divxtotal, dontorrent, epublibre, erai-raws, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, greatposterwall, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, morethantv, myanonamouse, ncore, nebulance, norbits, oppaitime, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, secretcinema, sharewoodapi, shazbat, ShizaProject, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentmafya, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, xspeeds, zonaq, animetosho, morethantv-api
2022-04-10 20:17:31	Info	
Loading Native indexers ...
2022-04-10 20:17:31	Info	
Using HTTP Client: HttpWebClient2
2022-04-10 20:17:31	Info	
Using FlareSolverr: http://127.0.0.1:49155
2022-04-10 20:17:31	Info	
Using proxy: Disabled
2022-04-10 20:17:31	Info	
App config/log directory: /config/Jackett
2022-04-10 20:17:31	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-04-10 20:17:31	Info	
Running in Docker: Yes (image build: v0.20.834-ls60)
2022-04-10 20:17:31	Info	
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2022-04-10 20:17:31	Info	
Jackett variant: CoreLinuxAmdx64
2022-04-10 20:17:31	Info	
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
2022-04-10 20:17:31	Info	
Environment version: 6.0.3 (/app/Jackett/)
2022-04-10 20:17:28	Info	
Starting Jackett v0.20.834
```

### Description

Test connection YGGTorrent.
Results : [yggtorrent] Test search in YGGtorrent => Found no results while trying to browse this tracker (Test)

### Logged Error Messages

```text
System.Exception: Test search in YGGtorrent => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 313
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment] 2022-04-10 18:44
use your jackett dashboard to edit the yggtorrent indexer config and
change the sitelink to `https://www3.yggtorrent.la/` and save.
closing as a duplicate of #13128

**Closed by garfield69** 2022-04-10 18:44 UTC
