### ISSUE TITLE
UBUNTU - Error loading Jackett settings, request to Jackett server failed

### ISSUE THREAD

**Issue by toshi24** [Jackett/Jackett#1675] opened 2017-08-15 20:58 UTC
Hello,
I just update my jackett v0.7.1644 (stable) to v0.8.55 (pre-release) by checking ''Update to pre-release'' then ''apply server setting'' and finally ''check for update''.
The log show :
`Aug 15, 2017 10:42:39 PM | Info | New release found.  Current: v0.7.1644 New: v0.8.55`
And after this, all my indexers disappear and I have the following error :
`Error loading Jackett settings, request to Jackett server failed`
Someone else had this issue but in windows.
Do you have any idea ?

Ubuntu 16.04 on Esxi
Jackett 0.8.55

**Comment by thebluepotato** [comment] 2017-08-15 21:43
Hi! Your issue is a duplicate of #1656. Solution: force refresh using Shift+F5 or Ctrl+Shift+R.

**Closed** 2017-08-16 15:25 UTC
