### ISSUE TITLE
[REQ] Add semi-private french tracker ShareWood

### ISSUE THREAD

**Issue by cadavor** [Jackett/Jackett#6972] opened 2020-01-18 14:29 UTC
Semi-Private French Tracker
https://www.sharewood.tv

No invitation needed, just register and validate your account with link in received mail

**Comment by garfield69** [comment] 2020-01-18 19:30
the sharewood indexer has been available on Jackett since March 2019.
Can you not find it in the Jackett Dashboard's add-indexer page?
Duplicate of #4898

**Closed by garfield69** 2020-01-18 19:30 UTC

**Comment by cadavor** [comment] 2020-01-18 21:28
My bad, sorry for inconvenience
