### ISSUE TITLE
[torrentseeds] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by BluePhire94** [Jackett/Jackett#5242] opened 2019-05-10 17:05 UTC
CardigannIndexer (torrentseeds): Error while parsing row '
<tr class="browse_color">
	<td class="text-center">
		<a href="browse.php?cat=18">
			<img border="0" src="./pic/caticons/1/cat_tveps.png" alt="TV/SD">
		</a>
	</td>
	<td align="left">
		<a href="details.php?id=784641&amp;hit=1">
			<b>Lost.And.Found.S04E08.HDTV.x264-FiHTV</b>
		</a><img src="./pic/scene.gif" title="Scene" alt="Scene" style="border:none"><img src="./pic/freedownload.gif" border="0" alt="Free Torrent" title="Free Torrent"><br></td>
	<td class="text-center">
		<a href="download.php?torrent=784641">
			<img src="./pic/zip.gif" border="0" alt="Download This Torrent!" title="Download This Torrent!">
		</a>
	</td>
	<td align="right">
		<span id="bookmark784641" style="display:inline;">
			<a href="bookmark.php?torrent=784641&amp;action=add" class="bookmark" name="784641">
				<span title="Bookmark it!" class="add_bookmark_b">
					<img src="./pic/aff_tick.gif" align="top" width="14px" alt="Bookmark it!" title="Bookmark it!">
				</span>
			</a>
		</span>
		<span id="remove784641" style="display:none;">
			<a href="bookmark.php?torrent=784641&amp;action=delete" class="remove" name="784641">
				<span class="remove_bookmark_b">
					<img src="./pic/aff_cross.gif" align="top" width="14px" alt="Delete Bookmark!" title="Delete Bookmark!">
				</span>
			</a>
		</span>
	</td>
	<td class="text-right">
		<b>
			<a href="filelist.php?id=784641">19</a>
		</b>
	</td>
	<td class="text-right">0</td>
	<td class="text-center">
		<span style="white-space: nowrap;">Today<br>
			04:15 AM</span>
	</td>
	<td class="text-center">279.14<br>MB</td>
	<td class="text-center">
		<a href="snatches_xbt.php?id=784641">3<br>Times</a>
	</td>
	<td class="text-right">
		<b>
			<a href="peerlist_xbt.php?id=784641#seeders">
				<font color="#006600">3</font>
			</a>
		</b>
	</td>
	<td class="text-right">0</td>
	<td class="text-center">
		<i>Anonymous</i>
	</td>
	<td class="text-center">
		<span>
			<img src=" https://www.torrentseeds.org/images/health/health_10.gif" alt="Torrent health" title="Torrent health">
		</span>
	</td>
	<td width="100%" colspan="14">Forever Immortal Hosts Television Division<br>
		Proudly Presents<br>
		<br>
		Lost.And.Found.S04E08.HDTV.x264-FiHTV<br>
		<br>
		Video: &nbsp; &nbsp;729 Kbps CRF21 x264 @ 720 pixels x 404 pixels<br>
		Audio: &nbsp; &nbsp;126 Kbps AAC 48.0 KHz<br>
		Duration: 44mn 39s @ 25.000 fps<br>
		Size: &nbsp; &nbsp; 274 MiB, 15x20mb<br>
		<br>
		Showdate: May 7th 2019<br>
		Predate: &nbsp;May 7th 2019<br>
		URL:<a href="http://nullrefer.com/?http://threenow.co.nz/lostandfound" target="_blank">http://threenow.co.nz/lostandfound</a>
		<br>
		<br>
		Release I...<br>
		<a href="details.php?id=784641&amp;hit=1">Read more...</a>
	</td>
</tr>':

System.Exception: Error while parsing field=title, selector=td:nth-of-type(2) a, value=<null>: Attribute "onmouseover" is not set for element 
<a href="details.php?id=784641&amp;hit=1">
	<b>Lost.And.Found.S04E08.HDTV.x264-FiHTV</b>
</a>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1480

**Comment by garfield69** [comment] 2019-05-12 23:54
update to jackett v0.11.325
 duplicate of #5244

**Closed by garfield69** 2019-05-12 23:54 UTC
