### ISSUE TITLE
Season packs with sonarr

### ISSUE THREAD

**Issue by king8084** [Jackett/Jackett#1796] opened 2017-09-08 18:52 UTC
jackett do not return season pack results to sonarr for many indexers such as MTV, can this be someone resolved?

**Comment by kaso17** [comment] 2017-09-09 06:40
http://127.0.0.1:9117/torznab/morethantv/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&q=simpsons&season=24
Is returning the correct results.

Probably a dupe of #1566

**Closed by kaso17** 2017-09-09 06:40 UTC
