### ISSUE TITLE
[REQ] New Tracker – Torrent Downloads

### ISSUE THREAD

**Issue by zero77** [Jackett/Jackett#1387] opened 2017-05-16 09:30 UTC
This tracker has been added but there’s a problem: #1629

Can you please add support for https://torrentdownloads.cc.
thanks.

Tracker Name : Torrent Download
Type : Movie, TV, XXX, Games, Music, Software, Anime, Books and Other
Public tracker.
Indexer URL : https://torrentdownloads.cc
Indexer language : English

**Comment by raspdealer** [comment] 2017-05-16 16:03
Hi @zero77, do you have an invit to provide?

**Comment by zero77** [comment] 2017-05-16 16:11
No, there's no invite needed.

**Comment by raspdealer** [comment] 2017-05-16 16:33
Members Registration is closed at the moment

**Comment by zero77** [comment] 2017-05-16 16:49
It's the same as RARBG where you can't sign up but you can download without an account.

**Comment by zero77** [comment] 2017-08-11 12:47
This tracker has been added but there’s a problem: #1629

**Comment by kaso17** [comment] 2017-08-11 14:08
dupe of #1559, added via #1563

**Closed by kaso17** 2017-08-11 14:08 UTC
Labels: New tracker
