### ISSUE TITLE
Auto Update fails on latest v0.22.xxxx packaged for QNAP

### ISSUE THREAD

**Issue by Gaudi111** [Jackett/Jackett#15492] opened 2024-07-11 12:13 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-07-10 19:42:50	Info	Using HTTP Client: HttpWebClient2
2024-07-10 19:42:50	Info	Using FlareSolverr: No
2024-07-10 19:42:50	Info	Using proxy: Disabled
2024-07-10 19:42:50	Info	App config/log directory: /share/CACHEDEV1_DATA/.qpkg/JackettdotNET81/home/.config/Jackett
2024-07-10 19:42:50	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-07-10 19:42:50	Info	Running in Docker: No
2024-07-10 19:42:50	Info	File /etc/issue: 
2024-07-10 19:42:50	Info	Jackett variant: CoreLinuxAmdx64
2024-07-10 19:42:50	Info	OS version: Unix 3.4.6.0 (64bit OS) (64bit process)
2024-07-10 19:42:49	Info	Environment version: 8.0.6 (/share/CACHEDEV1_DATA/.qpkg/JackettdotNET81/Jackett/)
2024-07-10 19:42:47	Info	Ignore SSL errors enabled.
2024-07-10 19:42:46	Info	Starting Jackett v0.22.281
```

### Description

I am currently using Jacket on my QNAP TS-469 Pro, running x64 firmware.
The app has been packaged by Qnap_Stephane from www.MyQNAP.org, who kindle administers and provides a very useful repo for all of us QNAP users.

So far, I have been using Jackett since a long time, and even though the built packages do not update as frequently as the releases in Github, I have managed to get the autoupdate feature working without issues until about a month or so, when it stopped working.
Qnap_Stephane has been very helpful in trying to debug and fix the issue, to no avail.
Starting from latest v0.21.2658 I have been unable to update to v0.22.xxxx (either manually nor automatically). Discussion on the issue can be found here at Discord Channel: https://discord.com/channels/1037035252792709130/1253388798566600735

The issue is libc related, as it tries to use an updated version that is not present in the NAS (system). Qnap_Stephane has prepared and built a special updater that uses a with libc wrapper, but the update scripts keeps using the downloaded and uncompressed version.

Would it be possible to iron out this issue to enable auto update?
(porting back libc version, or resorting to the externally provided updater?)

### Logged Error Messages

I have tested further. This is the log output while manually forcing the update:

```text
07-10 19:40:24 Info Checking for updates... Jackett variant: CoreLinuxAmdx64
07-10 19:40:25 Info New release found. Current version: v0.22.281 New version: v0.22.311
07-10 19:40:25 Info Downloading release v0.22.311 It could take a while...
07-10 19:40:37 Info Starting updater: /share/CACHEDEV1_DATA/.qpkg/JackettdotNET81/tmp/JackettUpdate-v0.22.311-638562372292531815/Jackett/JackettUpdater --Path "/share/CACHEDEV1_DATA/.qpkg/JackettdotNET81/Jackett" --Type "Console" --Args " --IgnoreSslErrors true --Port 25633" --KillPids "4511"
07-10 19:40:37 Info Updater started process id: 5814
07-10 19:40:37 Info Exiting Jackett..
/share/CACHEDEV1_DATA/.qpkg/JackettdotNET81/tmp/JackettUpdate-v0.22.311-638562372292531815/Jackett/JackettUpdater: /lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /share/CACHEDEV1_DATA/.qpkg/JackettdotNET81/tmp/JackettUpdate-v0.22.311-638562372292531815/Jackett/JackettUpdater)
Application is shutting down...
07-10 19:40:37 Info Jackett stopped
```

After Jackett stops, it will not start again. If I manually start it, then an excerpt of the log output follows:

```text
[~] # /share/CACHEDEV1_DATA/.qpkg/JackettdotNET81/JackettdotNET81.sh start
File JackettUpdater does not exist or is not larger than 50KB
other ELF already added to QPKG
07-10 19:42:46 Info Starting Jackett v0.22.281
07-10 19:42:47 Info Ignore SSL errors enabled.
07-10 19:42:49 Info Environment version: 8.0.6 (/share/CACHEDEV1_DATA/.qpkg/JackettdotNET81/Jackett/)
07-10 19:42:50 Info OS version: Unix 3.4.6.0 (64bit OS) (64bit process)
07-10 19:42:50 Info Jackett variant: CoreLinuxAmdx64
07-10 19:42:50 Info File /etc/issue:
07-10 19:42:50 Info Running in Docker: No
07-10 19:42:50 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
07-10 19:42:50 Info App config/log directory: /share/CACHEDEV1_DATA/.qpkg/JackettdotNET81/home/.config/Jackett
07-10 19:42:50 Info Using proxy: Disabled
07-10 19:42:50 Info Using FlareSolverr: No
07-10 19:42:50 Info Using HTTP Client: HttpWebClient2
07-10 19:42:50 Info Loading Native indexers ...
07-10 19:42:50 Info Loaded 72 Native indexers.
07-10 19:43:06 Info Deleting JackettUpdate temp files from /share/CACHEDEV1_DATA/.qpkg/JackettdotNET81/tmp/JackettUpdate-v0.22.311-638562372292531815
07-10 19:43:06 Error An error occurred during the last update. If this error occurs again, you need to reinstall Jackett following the documentation. If the problem continues after reinstalling, report the issue and attach the Jackett and Updater logs.
07-10 19:43:07 Info Jackett startup finished in 22.128 s
Hosting environment: Production
Content root path: /share/CACHEDEV1_DATA/.qpkg/JackettdotNET81/Jackett/Content
Now listening on: http://[::]:25633/
It seems that your updated updater is not called properly, and it encounters an error:
File JackettUpdater does not exist or is not larger than 50KB
```

**Comment by garfield69** [comment] 2024-07-11 23:16
Need more data. 
Please enable enhanced logging ( see https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket ) and then ( without using any indexers beforehand to avoid filling log with spurious entries ), click in the dashboard check-for-updates button.
Provide the enhanced log, as well as the updater logs (which you will find in the same place as the regular log.txt*, but with a filename starting with updater.txt*
Hopefully this will give the C# dev team something more to look at.

**Comment by Gaudi111** [comment] 2024-07-12 00:53
Find attached the generated logs:
[log.txt](https://github.com/user-attachments/files/16185767/log.txt)

Date for updater.txt is 2-jun-2024 (it has not updated today's failed update attempt).
[updater.txt](https://github.com/user-attachments/files/16185753/updater.txt)

Below is the bash output from SSH session, it may provide some other information not included in the log file:
[Jackett bash output.txt](https://github.com/user-attachments/files/16185795/Jackett.bash.output.txt)

Let me know if there is any there information I can provide.

**Comment by ilike2burnthing** [comment] 2024-07-12 21:06
How did you get v0.22.281? Fresh install?

Whatever Discord channel that is, I'm not able to access it. However, this comment on their forum says the issue has been resolved - https://www.forum-nas.fr/threads/jackett-0-20-3546-use-just-about-any-tracker-with-sonarr-or-couchpotato.2759/post-153150. Is that not the case?

**Comment by ilike2burnthing** [comment] 2024-07-12 21:31
Ok, got into the Discord server. The change from v0.21 to v0.22 was to .NET 8.0, from 6.0 - https://github.com/Jackett/Jackett/commit/06ee63e0ceb2532a9a2ea6d6a70c011d2be142d3

You can see in the Azure Pipelines file that this is the only change to how our binaries are built. So is the issue that .NET 8.0 isn't fully supported on some/all QNAP devices? If so, we can't really do anything about that, and won't be downgrading to .NET 6.0, or providing 6.0 versions.

Yes, Jackett uses the freshly downloaded updater to install the update, rather than using existing files which then couldn't be overwritten, as they're in use updating.

If your device supports Docker, I suggest just switching to that and saving yourself a lot of headaches.

**Comment by Gaudi111** [comment] 2024-07-12 23:27
> How did you get v0.22.281? Fresh install?
> 
> Whatever Discord channel that is, I'm not able to access it. However, this comment on their forum says the issue has been resolved - https://www.forum-nas.fr/threads/jackett-0-20-3546-use-just-about-any-tracker-with-sonarr-or-couchpotato.2759/post-153150. Is that not the case?

I have updated the packaged app in a .qpkg format, which is precompiled to work on my unit.
Developer is Qnap_Stephane from MyQNAP.org web page. He is quite proficient and has a lot of built packages.
I have copied your reply for him to address and understand if there is anything else that can be done to fix it/enable auto updater.

Strange thing is that tha packaged version does work, it is only AutoUpdate that does not.

**Comment by Gaudi111** [comment] 2024-07-14 14:51
I am quoting QNAP_Stephane reply here:

> It is wrong dotnet8  runs if you change ELF  on run time , that allow you to start DOTNet8 Package ...actually the package is natively running under an Ubuntu 2204 ELF Libs, i force binary using this ELF into a wrapper ex : 
> 
> exec $TRGT/ld-qnap --library-path "$TRGT" ./JackettUpdater.bin "$@"
> 
> where $TRGT is the path where the Unbutu2204 libs are uncompress on first install.... and as you can see all start well... it is just the downloaded file on update which are not warpped then creating this behavior 
> I used same method for many other QPKG requiring an Higher libc to be started

I am by no means as skilled or experienced as you are. I can outline that the updater used to work. Stephane is working on a fix that may help overcome the issue.
I am unaware if there is anything you can possibly to do help him out.

In any case, I am closely monitoring both Discord channel and this issue to stay updated.

Thank you and regards.

**Comment by Gaudi111** [comment] 2024-07-14 21:23
I have tested manually updating the package by downloading the appropriate file (v0.22.328 as of today; Jackett.Binaries.LinuxAMDx64.tar.gz, storring), stoping the program, replacing Jacket folder in my NAS and restarting it.
It went flawlessly, no more libc error starting Jackett. Probably because QNAP_Stephane has packaged the right libraries into the .qpkg package (compiled + symlinks to the right libraries).
I will still need to wait for the next release to check if auto updates work.

Will keep posted here, as probably it is something that can be fixed.

**Comment by ilike2burnthing** [comment] 2024-07-15 00:39
What I understood from the Discord chat was that Stephane was now running their own update script every half hour, so Jackett's auto-update should be disabled. Double-check with them and let us know. Also let us know if their update script works for you tomorrow.

As the issue is unrelated to Jackett itself, I'll close this issue.

**Closed by ilike2burnthing** 2024-07-15 00:39 UTC
