### ISSUE TITLE
[cpasbienclone] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by ncouronne** [Jackett/Jackett#5106] opened 2019-04-20 22:17 UTC
Hi,

I have this error since i start using Jackett for several weeks and i can't find why.
I've juste udpated to the latest version of jackett and i can access to the site directly with no password.
Here the log provided through the interface :

> System.Exception: Found no results while trying to browse this tracker
>   at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x000e8] in <f61b92b4a56a4c268ee2a157571ce6a9>:0 
>   at Jackett.Server.Controllers.IndexerApiController.Test () [0x000e1] in <90da798c06414014bf9a0a70602b0f9c>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
>   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 
>   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 
>   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 
>   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <90da798c06414014bf9a0a70602b0f9c>:0 

I'm not sure this kind of log could help. So ask me if you need other info.

Thanks in advance

**Jackett version**:  Version 0.11.232.0
**Mono version**: Mono JIT compiler version **5.18.0.225**

-------------------------------

**Comment by garfield69** [comment] 2019-04-20 22:55
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by ncouronne** [comment] 2019-04-20 23:06
Hi,
thanks for your response, here the latest logs

[log.txt](https://github.com/Jackett/Jackett/files/3100684/log.txt)

**Comment by garfield69** [comment] 2019-04-20 23:15
Hmmm. is your site link set to `https://cpasbiens.cm/` for this indexer?

**Comment by ncouronne** [comment] 2019-04-20 23:17
exactly, it's not the default config for this indexer ?

**Comment by garfield69** [comment] 2019-04-20 23:20
yes its the default. just double checking you were not using an alternate.
But I cant replicate your problem, so I shall have to look at the HTML you provided a little closer and see what is different about it that prevents the parser from picking up the torrent results.

**Comment by garfield69** [comment] 2019-04-20 23:37
I don't understand. 
your HTML is the exact duplicate of mine (identical), yet I get `105 results found` and you get `0 results found` ?!?
how is this possible? 
@kaso17  @flightlevel  I'm bumping this one up to you, as I don't understand what is going on here.

**Comment by garfield69** [comment] 2019-04-21 02:40
Ok. The only way this makes sense is if you are not using the latest cpasbeinclone.yml
About 17 days ago there was a change to fix this indexer to pick up changes to the row selector, and if your jackett is still unchanged then you would be getting 0 results as you are now.

There was a period a while back where we were publishing updates with a broken updater and you may have fallen fowl of one of those releases, so you may not have been getting updates since then.

I suggest you uninstall jackett and manually install the latest version instead.

**Comment by ncouronne** [comment] 2019-04-21 07:55
How can i help you investigate ?

**Comment by garfield69** [comment] 2019-04-21 08:02
how have you been updating jackett up to now, letting Jackett update itself, or using the check-for-updates, or using docker or fetching the latest version from https://github.com/Jackett/Jackett/releases or some other method?

**Comment by ncouronne** [comment] 2019-04-21 08:08
You're right ! My last installation was broken and Definition directory was not up to date. Sorry for this basic error.
Now cpasbienclone is working.
I've update all the *.yml files and restart test. I'm still have other errors. Do i post it there or i create other issue ?

**Comment by garfield69** [comment] 2019-04-21 08:11
best raise a ticket for each indexer's unique error, so that we've a history of the solution for others to reference.

**Closed by garfield69** 2019-04-21 08:11 UTC
