### ISSUE TITLE
Separate indexer definition updates (yml files) from code updates?

### ISSUE THREAD

**Issue by rrrevin** [Jackett/Jackett#5332] opened 2019-05-25 18:00 UTC
Everytime there is an indexer definition (yml file) update, there is a new complete release of jackett. Unfortunately, as seen in recent threads, the Linux Core version is suffering from failed updates and writing zero byte files, when the system tries to update the entire distribution.

Seeing as how yml definition updates are needed and are updated much more often than code updates, would it be possible to separate the two?

This would reduce the frustration of end users when jacket crashes during updates that really only need 1 or 2 yml definition files updated.

Thoughts?

**Comment by ngosang** [comment] 2020-01-12 21:02
Duplicate of #6357

**Closed by ngosang** 2020-01-12 21:02 UTC
