### ISSUE TITLE
[rptscene] (testing) Exception (rptscene): No route to host: No route to host (rptscene.xyz:443)

### ISSUE THREAD

**Issue by slrslr** [Jackett/Jackett#15694] opened 2024-11-07 06:06 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
-
```

### Description

The uptime service https://www.uptrends.com/tools/uptime reports down from everywhere.

### Logged Error Messages

```text
-
```

**Comment by garfield69** [comment] 2024-11-07 06:08
duplicate of https://github.com/Jackett/Jackett/issues/5368#issuecomment-2442142849

**Closed by garfield69** 2024-11-07 06:08 UTC
