### ISSUE TITLE
[nyaasi] Exception (nyaasi): The socket is not connected: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by Theogermal** [Jackett/Jackett#3711] opened 2018-08-29 20:37 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.7.1609
**Mono version** (if not using Windows):  5.8.1.0.r9

-------------------------------
Jackett.Common.IndexerException: Exception (nyaasi): The socket is not connected ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: Error while sending TLS Alert (Fatal:InternalError): System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
  at System.Net.Sockets.Socket.EndReceive (System.IAsyncResult asyncResult) [0x00012] in <5032a36c32c24210a090820d54144dbc>:0 
  at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x00057] in <5032a36c32c24210a090820d54144dbc>:0 
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x00037] in <21ece1e520e7400b8ede004aedf7b10d>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in <21ece1e520e7400b8ede004aedf7b10d>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in <21ece1e520e7400b8ede004aedf7b10d>:0 
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult result) [0x00032] in <21ece1e520e7400b8ede004aedf7b10d>:0 
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult asyncResult) [0x0000c] in <21ece1e520e7400b8ede004aedf7b10d>:0  ---> System.IO.IOException: Unable to write data to the transport connection: The socket is not connected. ---> System.Net.Sockets.SocketException: The socket is not connected
  at System.Net.Sockets.Socket.BeginSend (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags, System.AsyncCallback callback, System.Object state) [0x00022] in <5032a36c32c24210a090820d54144dbc>:0 
  at System.Net.Sockets.NetworkStream.BeginWrite (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.AsyncCallback callback, System.Object state) [0x0009b] in <5032a36c32c24210a090820d54144dbc>:0 
   --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.BeginWrite (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.AsyncCallback callback, System.Object state) [0x000e6] in <5032a36c32c24210a090820d54144dbc>:0 
  at Mono.Security.Protocol.Tls.RecordProtocol.BeginSendRecord (Mono.Security.Protocol.Tls.ContentType contentType, System.Byte[] recordData, System.AsyncCallback callback, System.Object state) [0x00023] in <21ece1e520e7400b8ede004aedf7b10d>:0 
  at Mono.Security.Protocol.Tls.RecordProtocol.SendRecord (Mono.Security.Protocol.Tls.ContentType contentType, System.Byte[] recordData) [0x00000] in <21ece1e520e7400b8ede004aedf7b10d>:0 
  at Mono.Security.Protocol.Tls.RecordProtocol.SendAlert (Mono.Security.Protocol.Tls.Alert alert) [0x00021] in <21ece1e520e7400b8ede004aedf7b10d>:0 
  at Mono.Security.Protocol.Tls.RecordProtocol.SendAlert (System.Exception& ex) [0x0001b] in <21ece1e520e7400b8ede004aedf7b10d>:0 
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.EndRead (System.IAsyncResult asyncResult) [0x0004b] in <21ece1e520e7400b8ede004aedf7b10d>:0 
  at Mono.Net.Security.Private.LegacySslStream.EndAuthenticateAsClient (System.IAsyncResult asyncResult) [0x0000e] in <5032a36c32c24210a090820d54144dbc>:0 
  at Mono.Net.Security.Private.LegacySslStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x0000e] in <5032a36c32c24210a090820d54144dbc>:0 
  at Mono.Net.Security.MonoTlsStream.CreateStream (System.Byte[] buffer) [0x0007b] in <5032a36c32c24210a090820d54144dbc>:0 
  at System.Net.WebConnection.CreateStream (System.Net.HttpWebRequest request) [0x00073] in <5032a36c32c24210a090820d54144dbc>:0 
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00058] in <5032a36c32c24210a090820d54144dbc>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <5f3086ab89df4a068b9d0065e880bddc>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0041d] in <5586c7b269ae420e927fec81f4a46e60>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <5586c7b269ae420e927fec81f4a46e60>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at CloudFlareUtilities.ClearanceHandler+<SendAsync>d__20.MoveNext () [0x0010c] in <d0213015414e4bf286b46bc1ee77bd72>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <5586c7b269ae420e927fec81f4a46e60>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Jackett.Common.Utils.Clients.HttpWebClient+<Run>d__7.MoveNext () [0x00458] in <3196b723abe34936a1795211b11d2a59>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Jackett.Common.Utils.Clients.WebClient+<GetString>d__18.MoveNext () [0x0010b] in <3196b723abe34936a1795211b11d2a59>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Jackett.Common.Indexers.BaseWebIndexer+<RequestStringWithCookies>d__5.MoveNext () [0x000cb] in <3196b723abe34936a1795211b11d2a59>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__29.MoveNext () [0x00827] in <3196b723abe34936a1795211b11d2a59>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x00091] in <3196b723abe34936a1795211b11d2a59>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x000ee] in <3196b723abe34936a1795211b11d2a59>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x0006b] in <3196b723abe34936a1795211b11d2a59>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x000a3] in <3196b723abe34936a1795211b11d2a59>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Jackett.Server.Controllers.IndexerApiController+<Test>d__15.MoveNext () [0x000e1] in <d6819775d910452ca544bd4b70d063ba>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <51f5e57c3b1641ff921c58f55f777af6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <5f3086ab89df4a068b9d0065e880bddc>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x0008a] in <d6819775d910452ca544bd4b70d063ba>:0

**Comment by garfield69** [comment] 2018-08-30 03:39
jackett 0.7.1609 is quite out of date. recommend upgrading to the latest, currently v0.10.134

**Comment by Theogermal** [comment] 2018-08-30 06:45
I'm unable to update it for some reason, I had this issue on the latest version, so I reinstalled everything and nothing changed.

**Comment by kaso17** [comment] 2018-08-30 16:40
On which platform are you running jackett?

**Comment by Theogermal** [comment] 2018-08-30 16:42
I'm running it on an Asustor NAS it worked fine until a few days ago

**Comment by kaso17** [comment] 2018-08-30 16:43
ok, then it's a dupe of #3489

**Closed by kaso17** 2018-08-30 16:43 UTC
