### ISSUE TITLE
jackettconsole.exe.mdb doesn't match image jackettconsole.ese

### ISSUE THREAD

**Issue by allywilson** [Jackett/Jackett#2661] opened 2018-03-02 18:07 UTC
Just noticed Jackett isn't working. I have auto updates enabled, no idea which version unfortunately...

Linux Mint 17.3
Mono: 5.10.0.140

Get this error when attempting to run jackett:

```
Symbol file /opt/jackett/JackettConsole.exe.mdb doesn't match image /opt/jackett/JackettConsole.exe
Symbol file /opt/jackett/Jackett.dll.mdb doesn't match image /opt/jackett/Jackett.dll

Unhandled Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: context
  at Autofac.ResolutionExtensions.ResolveService (Autofac.IComponentContext context, Autofac.Core.Service service, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00003] in <6b74cc51e42041dba63ed788f99f0cbb>:0 
  at Autofac.ResolutionExtensions.Resolve (Autofac.IComponentContext context, System.Type serviceType, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00007] in <6b74cc51e42041dba63ed788f99f0cbb>:0 
  at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <6b74cc51e42041dba63ed788f99f0cbb>:0 
  at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context) [0x00000] in <6b74cc51e42041dba63ed788f99f0cbb>:0 
  at Jackett.Engine.get_Logger () [0x00000] in C:\projects\jackett\src\Jackett.Common\Engine.cs:166 
  at JackettConsole.Program+<>c.<Main>b__0_1 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00330] in <1ff49239ca8c4e438ca9e858f1a41115>:0 
  at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <450057026f344cf3b18fc8978bc1a7a3>:0 
  at JackettConsole.Program.Main (System.String[] args) [0x0002f] in <1ff49239ca8c4e438ca9e858f1a41115>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null.
Parameter name: context
  at Autofac.ResolutionExtensions.ResolveService (Autofac.IComponentContext context, Autofac.Core.Service service, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00003] in <6b74cc51e42041dba63ed788f99f0cbb>:0 
  at Autofac.ResolutionExtensions.Resolve (Autofac.IComponentContext context, System.Type serviceType, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00007] in <6b74cc51e42041dba63ed788f99f0cbb>:0 
  at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <6b74cc51e42041dba63ed788f99f0cbb>:0 
  at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context) [0x00000] in <6b74cc51e42041dba63ed788f99f0cbb>:0 
  at Jackett.Engine.get_Logger () [0x00000] in C:\projects\jackett\src\Jackett.Common\Engine.cs:166 
  at JackettConsole.Program+<>c.<Main>b__0_1 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00330] in <1ff49239ca8c4e438ca9e858f1a41115>:0 
  at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <450057026f344cf3b18fc8978bc1a7a3>:0 
  at JackettConsole.Program.Main (System.String[] args) [0x0002f] in <1ff49239ca8c4e438ca9e858f1a41115>:0 
```

The 2 MDB, and DLL and EXE listed at the beginning all exist.

**Comment by garfield69** [comment] 2018-03-02 19:51
Duplicate of #2636 
upgrade jackett to 0.8.737 to resolve the `[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null.` which is the cause of your Jackett not working.

I believe you can delete any of the *.mdb files, they are used for debugging and should not be required to run Jackett, based on what I've read in #2135

**Closed by garfield69** 2018-03-02 19:51 UTC
