### ISSUE TITLE
EZTV Indexer not working

### ISSUE THREAD

**Issue by chrisjc76** [Jackett/Jackett#9301] opened 2020-08-05 14:40 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Win dows

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** Yes

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

EZTV Indexer not working

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment] 2020-08-05 19:21
this indexer is working for me which suggests the problem is at your end.
if you want help resolving this then provide a **full enhanced** log with debug and HTML and we may be able to determine your problem. 
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by chrisjc76** [comment] 2020-08-05 19:31
When I test it on Jacket, its not working either

**Comment by garfield69** [comment] 2020-08-05 20:02
this indexer is working for me which suggests the problem is at your end.
if you want help resolving this then provide a full enhanced log with debug and HTML and we may be able to determine your problem.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

if you do not provide a full enhanced log then we cannot help and we will close the ticket.

**Closed** 2020-08-13 02:58 UTC
Labels: Full logs needed
