### ISSUE TITLE
Replace OMDB API by TheMovieDB.org API.

### ISSUE THREAD

**Issue by alex-ikse** [Jackett/Jackett#1617] opened 2017-08-05 00:19 UTC
Please remove the (not Free) OMDB API and replace it by TheMovieDB.org (Free API).

**Comment by chibidev** [comment] 2017-08-06 15:17
There's also http://www.tvmaze.com/api. Probably should run multiple of them simultaneously to check which one gives the best (and most up-to-date) results.

**Comment by JigSawFr** [comment] 2017-08-14 10:14
@chibidev I agree implementing TMDB could be great as OMDB is not free. I don't know TvMaze, but why not use multiple API

**Comment by chibidev** [comment] 2017-08-14 12:31
@JigSawFr I intend to do that exactly, however I want to add proper analytics to see the results. Stay tuned!
(OMDB is not free, however that 5 bucks a month is really cheap for someone to provide a stable and fast API, and I think we should appreciate that. And with Jackett v0.8+ using OMDB is not mandatory.)

**Comment by mueslo** [comment] 2017-08-15 10:25
Is anyone working on this already?

**Comment by chibidev** [comment] 2017-08-16 23:30
@mueslo I don't think so, I at least am not treating it with a very high priority.

**Comment by kaso17** [comment] 2017-08-17 07:00
I'm not working on it either.

**Comment by flightlevel** [comment] 2017-08-17 11:15
Instead of looking at adding another provider, I think we should instead look at if can remove OMDB completely.
You'd think as of 99%+ aren't using an OMDB key today

The reason the OMDB lookup was added was for torrentpotato. Originally torrentpotato requests ONLY emitted the imdb_id. But, now that torrentpotato requests supply both movie name and imdb_id, do we really need to convert any imdb_id's to movie names ourselves any more?

**Comment by chibidev** [comment] 2017-08-17 16:28
@flightlevel well TP is not the only one the fallback is there right now. You can provide fallback mechanism for MetaIndexers that will generate additional results.
The problem with metas is that once a member supports IMDB queries, the metaindexer will support IMDB query, however upon posting IMDB query it will only ask those that are capable of providing a result from that query. This means that if you have an indexer group that has 1 indexer supporting IMDB queries, whenever there's an IMDB query coming to that group only that single indexer will provide a result. The problem is that when using Radarr, it does the discovery for this capability, and if the indexer supports IMDB queries, it will post the imdb id instead of the title. There are multiple solutions to this problem:
- Let the metaindexers support IMDB query only if all its members. This way Radarr will not post imdb id either.
- Let the metas support IMDB query as of today, but only search those members supporting it.
- Search those supporting imdb query by imdbid, search those that do not by doing a fallback mechanism.
Since the 3rd option is providing the largest number of results with probably the best accuracy (and having an IMDB API opens up other opportunities as well), I'd argue not to remove this feature.

**Comment by flightlevel** [comment] 2018-03-25 03:39
Now that OMDB is free http://www.omdbapi.com/apikey.aspx can't see the logic in replacing it or adding the complexity of having two, closing

**Closed by flightlevel** 2018-03-25 03:39 UTC
Labels: Core, Enhancement
