### ISSUE TITLE
[New Tracker] sharewood.tv

### ISSUE THREAD

**Issue by xfouloux** [Jackett/Jackett#4914] opened 2019-03-19 23:35 UTC
Hi,

New french tracker, semi-private.

https://www.sharewood.tv/

I will try to add basic stuff when I can before end of week.

search of torrents cat be donne like this : 
https://www.sharewood.tv/torrents?recherche={SEARCH TERM}

I can do the basic search with yaml file I think, but it will need C# for affined search I think, but I can't see why C# would be helpfull @garfield69 like on all dynamic pages unless there are methods to simulate clicks on fields and such ?

**Comment by garfield69** [comment] 2019-03-20 00:23
Duplicate of #4898

**Closed by garfield69** 2019-03-20 00:23 UTC
