### ISSUE TITLE
All tests are KO since 0.7.1990

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#1142] opened 2017-03-05 21:05 UTC
All tests are KO except T411 and ABN... and based on the log, it sounds like a SSL issue.

2017-03-05 22:04:21.1482 Error Exception in test_indexer System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.

**Comment by kaso17** [comment] 2017-03-06 11:01
Please check if this is a dupe of #1123

**Closed** 2017-03-07 20:55 UTC
