### ISSUE TITLE
[torrentcore] (testing) Exception (torrentcore): Error: [Anti-DDoS]Please wait 10 seconds for each request.: Parse error

### ISSUE THREAD

**Issue by yzeng1314** [Jackett/Jackett#15439] opened 2024-06-24 01:22 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-06-23 21:13:00	Info	Using FlareSolverr: http://localhost:8191
2024-06-23 21:13:00	Info	Using proxy: Disabled
2024-06-23 21:13:00	Info	App config/log directory: /config/Jackett
2024-06-23 21:13:00	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-06-23 21:13:00	Info	Running in Docker: Yes (image build: v0.22.200-ls442)
2024-06-23 21:13:00	Info	File /etc/issue: Welcome to Alpine Linux 3.20
2024-06-23 21:13:00	Info	Jackett variant: CoreLinuxMuslAmdx64
2024-06-23 21:13:00	Info	OS version: Unix 5.15.0.101 (64bit OS) (64bit process)
2024-06-23 21:13:00	Info	Environment version: 8.0.6 (/app/Jackett/)
2024-06-23 21:13:00	Info	Starting Jackett v0.22.200
```

### Description

Testing the Torrent[CORE] will give the error. Have FlareSolverr 3.3.20 running and configured properly. No errors. Only info log from FlareSoverr:

2024-06-23 21:15:46 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://torrentcore.xyz/index'}
2024-06-23 21:15:47 INFO     Challenge not detected!
2024-06-23 21:15:47 INFO     Response in 0.9 s
2024-06-23 21:15:47 INFO     127.0.0.1 POST http://localhost:8191/v1 200 OK

### Logged Error Messages

```text
2024-06-23 21:13:22	Error	
Jackett.Common.IndexerException: Exception (torrentcore): Error: [Anti-DDoS]
Please wait 10 seconds for each request.

[v0.22.200.0] Jackett.Common.IndexerException: Exception (torrentcore): Error: [Anti-DDoS]
Please wait 10 seconds for each request.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Error: [Anti-DDoS]
Please wait 10 seconds for each request.
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 553
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1764
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 804
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1905
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 366
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 387
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 778
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 323
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2024-06-23 21:13:22	Error	
Error on 20240623211322 for Torrent[CORE].txtJackett.Common.ExceptionWithConfigData: Error: [Anti-DDoS]
Please wait 10 seconds for each request.
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 553
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1764




[Anti-DDoS]
Please wait 10 seconds for each request.
```

**Comment by garfield69** [comment] 2024-06-24 01:49
https://github.com/Jackett/Jackett/issues/15284#issuecomment-2084716503

closing as a duplicate of #15284

**Closed by garfield69** 2024-06-24 01:49 UTC
