### ISSUE TITLE
linuxtracker: Error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13587] opened 2022-09-24 18:37 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett: v0.20.1951
Arch Linux
Docker: Yes
```

### Description

Empty query
"query": "iso"

### Logged Error Messages

```text
CardigannIndexer (linuxtracker): Error while parsing row '
<tr>
	<td width="125" class="lista" align="center">
		<center>
			<a href="index.php?page=torrents&amp;category=2296">Mabox Linux</a>
		</center>
		<p>
			<a href="/torrentimg/noimage.jpg" title="view image" rel="lightbox">
				<img src="thumbnail.php?size=150&amp;path=torrentimg/noimage.jpg">
			</a>
			<br>
			<a href="index.php?page=torrent-details&amp;id=4d6b87d5e5077f3e8660d58f44f98253588bbf61">
				<img src="/images/more_details_icon.png">
			</a>
		</p>
	</td>
	<td class="lista">
		<font size="4">
			<strong>
				<a href="index.php?page=torrent-details&amp;id=4d6b87d5e5077f3e8660d58f44f98253588bbf61" title="View details: mabox-linux-22.09-Herbolth-220923-linux515.iso">mabox linux 22 09 Herbolth 220923 linux515 iso</a>
			</strong>
		</font>
		<br>
		Mabox is a Manjaro-based rolling release distribution. Mabox Linux features the Openbox window manager as its default interface and provides a welcome screen with access to utilities which add additional software to the operating system.<br>
		<hr>
		<table width="100%">
			<tbody>
				<tr>
					<td>
						<strong>Added On:</strong>
						23/09/2022</td>
					<td>
					</td>
				</tr>
				<tr>
					<td>
						<strong>Size:</strong>
						2.13 GB
					</td>
					<td></td>
				</tr>
				<tr>
					<td>
						<strong>
							<a href="/index.php?page=torrents&amp;active=1&amp;order=5&amp;by=2">Seeds</a>
						</strong>
						<a href="index.php?page=peers&amp;id=4d6b87d5e5077f3e8660d58f44f98253588bbf61" title="Click here to view peers details">12</a>
					</td>
					<td></td>
				</tr>
				<tr>
					<td>
						<strong>
							<a href="/index.php?page=torrents&amp;active=1&amp;order=6&amp;by=2">Leechers</a>
						</strong>
						<a href="index.php?page=peers&amp;id=4d6b87d5e5077f3e8660d58f44f98253588bbf61" title="Click here to view peers details">0</a>
					</td>
					<td></td>
				</tr>
				<tr>
					<td width="90%">
						<strong>
							<a href="/index.php?page=torrents&amp;active=1&amp;order=7&amp;by=1">Completed</a>
						</strong>
						<a href="index.php?page=torrent_history&amp;id=4d6b87d5e5077f3e8660d58f44f98253588bbf61" title="History - mabox-linux-22.09-Herbolth-220923-linux515.iso">26</a>
					</td>
					<td align="right">
						<a href="magnet:?xt=urn:btih:JVVYPVPFA57T5BTA2WHUJ6MCKNMIXP3B">
							<img src="images/azureus.gif" border="0" alt="Magnet Link">
						</a>
						<a href="index.php?page=downloadcheck&amp;id=4d6b87d5e5077f3e8660d58f44f98253588bbf61">
							<img src="images/download.gif" border="0" alt="torrent">
						</a>
					</td>
				</tr>
			</tbody>
		</table>
		<hr>
		<table width="100%">
			<tbody>
				<tr>
					<td>
						---</td>
					<td>
						<a href="index.php?page=userdetails&amp;id=9892">
							<span style="color:#FF8000">DEMONLORD</span>
						</a>
					</td>
					<td>
						N/A
					</td>
					<td>
						100%<br>
						<img src="images/health/health_10.gif">
					</td>
					<td align="center" width="20" class="lista" style="text-align: center;">---</td>
					<td>
						<tag:torrents[].recommended></tag:torrents[].recommended>
					</td>
					<td>
						<strong>
						</strong>
					</td>
				</tr>
			</tbody>
		</table>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a[href^="index.php?page=torrents&category="], value=2296: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630
```

**Comment by mikeoscar2006** [comment] 2022-09-24 20:24
Can't Reproduce. Works fine for both empty query and "iso" text.

**Comment by ngosang** [comment] 2022-09-24 20:26
Maybe it was temporary... If the other collaborators can not reproduce the issue you can close.

**Comment by garfield69** [comment] 2022-09-24 20:47
cannot reproduce. closing.

**Comment by garfield69** [comment] 2022-09-24 20:48
OH, but i do get the cat error. ill update the categories.

**Closed** 2022-09-24 21:07 UTC
