### ISSUE TITLE
An error occurred while trying to encrypt the provided data. 

### ISSUE THREAD

**Issue by ca-cabotage** [Jackett/Jackett#8532] opened 2020-05-04 15:11 UTC
### Environment

**OS**: Lubuntu 18.04

**.Net Runtime**: unk

**.Net Version**:unk

**Jackett Version**: Linux AMD64 v0.16.284

**Last Working Jackett Version**: unknown (it's been months)

**Are you using a proxy or VPN?** [yes/no] - whole network VPN (no client on Jackett server)

### Description

navigate to Dashboard

### Logged Error Messages

{
  "result": "error",
  "error": "An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.: Root element is missing.",
  "stacktrace": "   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)\n   at Microsoft.AspNetCore.Authentication.SecureDataFormat`1.Protect(TData data, String purpose)\n   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleSignInAsync(ClaimsPrincipal user, AuthenticationProperties properties)\n   at Microsoft.AspNetCore.Authentication.AuthenticationService.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal, AuthenticationProperties properties)\n   at Jackett.Server.Controllers.WebUIController.MakeUserAuthenticated() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/UIController.cs:line 95\n   at Jackett.Server.Controllers.WebUIController.Login() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/UIController.cs:line 42\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70",
  "innerstacktrace": "   at System.Xml.XmlTextReaderImpl.Throw(Exception e)\n   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()\n   at System.Xml.XmlReader.MoveToContent()\n   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)\n   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)\n   at System.Xml.Linq.XElement.Load(Stream stream)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.ReadElementFromFile(String fullPath)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext()\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)"
}

**Comment by garfield69** [comment] 2020-05-05 00:04
duplicate of #6217

sounds like you have run into an old updater issue, the fix for which involves running the systemd install script so that the launcher is updated to not allow the service to run at the same time as the updater.
right now your jackett is broken and you will need to manually install to replace missing modules.

so follow the install steps described at https://github.com/Jackett/Jackett#install-as-service, and in particular, don't forget to run the systemd install script to ensure the startup script is upgraded.

let us know how you go.

**Comment by ca-cabotage** [comment] 2020-05-05 01:25
So i searched github and found references to the old updater issue you mentioned. 

I've done that several times.

I completely removed jackett, downloaded several new version - currently the latest version. Installed and ran the systemd install script. 
I've even tried doing it with both the mono version and the linux standalone version - I've tried running it explicitly and as a service. 

So in short, I've already done that and it doesn't fix anything.

**Comment by garfield69** [comment] 2020-05-05 01:59
ok. so as long as you are on 0.16.284 using the AMDx64 package and you have that systemd script installed, then the next step is to check that your OS has the required supporting libraries.
I don't see Lubuntu listed in the https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md#linux
@ngosang  @cadatoiva  guys your assistance please?

**Comment by ngosang** [comment] 2020-05-05 06:18
Lubuntu and *untu distributions share all libraries packages, etc... the only difference is the desktop environment (GUI).
This error is caused by a race condition in .net core and Microsoft doesn't seem to know how to fix it. => https://github.com/dotnet/aspnetcore/issues/6942
The weird thing is you are having the same issue in .netcore and mono versions that are totally different. They only share the configuration. Maybe it's corrupted? Could you delete all the files in the configuration folder and reinstall Jackett AMDx64?
The folder you have to delete is `/home/<your user>/.config/Jackett/`(at least in my system)

**Comment by ca-cabotage** [comment] 2020-05-05 13:47
> ...
> ...
> ...They only share the configuration. Maybe it's corrupted? Could you delete all the files in the configuration folder and reinstall Jackett AMDx64?
> The folder you have to delete is `/home/<your user>/.config/Jackett/`(at least in my system)

Perfect! this fixed everything, thanks very much.

**Closed** 2020-05-05 13:47 UTC
