### ISSUE TITLE
[newpct] Cant download any release

### ISSUE THREAD

**Issue by pelagrellas** [Jackett/Jackett#12910] opened 2022-02-01 16:50 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-02-01 17:44:52	Info	
Using HTTP Client: HttpWebClient2
2022-02-01 17:44:52	Info	
Using FlareSolverr: No
2022-02-01 17:44:52	Info	
Using proxy: Disabled
2022-02-01 17:44:52	Info	
App config/log directory: /config/Jackett
2022-02-01 17:44:52	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-02-01 17:44:52	Info	
Running in Docker: Yes (image build: v0.19.147-ls49)
2022-02-01 17:44:52	Info	
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2022-02-01 17:44:52	Info	
Jackett variant: CoreLinuxAmdx64
2022-02-01 17:44:52	Info	
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
2022-02-01 17:44:52	Info	
Environment version: 6.0.1 (/app/Jackett/)
2022-02-01 17:44:51	Info	
Starting Jackett v0.20.494
```

### Description

Since a few days ago newpct indexer appears with error until last update, error has dissapear but cant download anything with page not found error

### Logged Error Messages

```text
Error downloading. indexer: newpct path: https://atomixhq.top/descargar/serie-en-hd/chucky/temporada-1/capitulo-05/
System.Exception: Download link not found!
   at Jackett.Common.Indexers.NewPCT.Download(Uri linkParam) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 195
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 56
```

### Screenshots

<img width="358" alt="image" src="https://user-images.githubusercontent.com/85077900/152012585-84620446-ff87-4baa-9218-3b9bc517bdc3.png">

**Comment by garfield69** [comment] 2022-02-01 16:56
duplicate of #12909

**Closed by garfield69** 2022-02-01 16:56 UTC

**Comment by pelagrellas** [comment] 2022-02-03 11:47
same issue today, yesterday was workin but not now

**Comment by egrueda** [comment] 2022-02-04 16:55
Same problem here, parsing error:

```
2022-02-04 17:52:01.0512 Error Error downloading. indexer: newpct path: https://atomixhq.art/descargar/serie-en-hd/reacher/[...]/
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97 

```
