### ISSUE TITLE
[elitetracker] Exception (elitetracker): String was not recognized as a valid DateTime.: Parse error (Config)

### ISSUE THREAD

**Issue by JuGuSm** [Jackett/Jackett#5426] opened 2019-06-07 23:19 UTC
An error occured while testing this indexer
Exception (elitetracker): String was not recognized as a valid DateTime.: Parse error

Jackett Version 0.10.198.0

-------------------------------

**Comment by garfield69** [comment] 2019-06-08 02:47
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by garfield69** [comment] 2019-06-08 23:35
duplicate of #5436

**Closed by garfield69** 2019-06-08 23:35 UTC
Labels: Full logs needed

**Comment by garfield69** [comment] 2019-06-09 03:33
try out jackett pre-release v0.11.399
