### ISSUE TITLE
Exception was thrown. Not able to start Jackett on Debian.

### ISSUE THREAD

**Issue by supremacy2k** [Jackett/Jackett#546] opened 2016-10-12 02:45 UTC
At 1am, my Jackett installation that have been running rock solid for months, stopped working.

when i run `mono /opt/jackett/JackettConsole.exe` i get the following wall of error code.

```
`10-12 04:43:19 Error Top level exception Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Logger)' on type 'UnixLibCurlWebClient'. ---> Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=*Removed*' or one of its dependencies. (See inner exception for details.) ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=*Removed*' or one of its dependencies.
File name: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=*Removed*'
  at (wrapper managed-to-native) System.Reflection.Assembly:InternalGetType (System.Reflection.Assembly,System.Reflection.Module,string,bool,bool)
  at System.Reflection.MonoAssembly.GetType (System.String name, Boolean throwOnError, Boolean ignoreCase) <0x7fb84f1a85d0 + 0x00048> in <filename unknown>:0
  at System.Reflection.Assembly.GetType (System.String name) <0x7fb84f1a1240 + 0x0001d> in <filename unknown>:0
  at Jackett.Utils.Clients.UnixLibCurlWebClient..ctor (NLog.Logger l) <0x40344370 + 0x000ec> in <filename unknown>:0
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object[])
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () <0x40330960 + 0x0016e> in <filename unknown>:0
--- End of inner exception stack trace ---

  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () <0x40330960 + 0x00417> in <filename unknown>:0
  at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance (IComponentContext context, IEnumerable`1 parameters) <0x4032f240 + 0x0013b> in <filename unknown>:0
  at Autofac.Core.Resolving.InstanceLookup.Activate (IEnumerable`1 parameters) <0x4032ef10 + 0x00068> in <filename unknown>:0
  at Autofac.Core.Resolving.InstanceLookup.Execute () <0x4032e7d0 + 0x0004b> in <filename unknown>:0
  at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance (ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) <0x4032d970 + 0x000fb> in <filename unknown>:0
  at Autofac.Core.Resolving.InstanceLookup.ResolveComponent (IComponentRegistration registration, IEnumerable`1 parameters) <0x40330e40 + 0x00038> in <filename unknown>:0
  at Autofac.Core.Activators.Reflection.AutowiringParameter+<>c__DisplayClass2.<CanSupplyValue>b__0 () <0x40330df0 + 0x00043> in <filename unknown>:0
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () <0x40330960 + 0x000bb> in <filename unknown>:0
  at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance (IComponentContext context, IEnumerable`1 parameters) <0x4032f240 + 0x0013b> in <filename unknown>:0
  at Autofac.Core.Resolving.InstanceLookup.Activate (IEnumerable`1 parameters) <0x4032ef10 + 0x00068> in <filename unknown>:0
  at Autofac.Core.Resolving.InstanceLookup.<Execute>b__0 () <0x4032eee0 + 0x00017> in <filename unknown>:0
  at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare (Guid id, System.Func`1 creator) <0x4032ea60 + 0x00088> in <filename unknown>:0
  at Autofac.Core.Resolving.InstanceLookup.Execute () <0x4032e7d0 + 0x00114> in <filename unknown>:0
  at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance (ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) <0x4032d970 + 0x000fb> in <filename unknown>:0
  at Autofac.Core.Resolving.ResolveOperation.ResolveComponent (IComponentRegistration registration, IEnumerable`1 parameters) <0x4032d930 + 0x0002b> in <filename unknown>:0
  at Autofac.Core.Resolving.ResolveOperation.Execute (IComponentRegistration registration, IEnumerable`1 parameters) <0x4032d830 + 0x00037> in <filename unknown>:0`


Version 0.7.418.0 as shown below.

root@Plex:~# mono /opt/jackett/JackettConsole.exe -v
Jackett v0.7.418.0
```

**Comment by kaso17** [comment] 2016-10-12 05:19
Does your Jackett directory contain CloudFlareUtilities.dll ?

**Comment by supremacy2k** [comment] 2016-10-12 05:23
I JUST turned my PC when you replied.

Yes, i have CloudFlareUtilities.dll in /opt/jackett

**Comment by kaso17** [comment] 2016-10-12 05:30
What do you mean with "not an executable"?
Please try to manually reinstall the v0.7.418

**Comment by supremacy2k** [comment] 2016-10-12 05:34
The executable thing, was not a thing anyways, thats why i removed the edit. :)
Gimme a sec, and i'll try.

**Comment by kaso17** [comment] 2016-10-12 05:47
Please try using the latest version with this modified dll:
https://ufile.io/ab38

**Comment by supremacy2k** [comment] 2016-10-12 05:49
the downloaded dll is called ab38-jackett.dll, what is it's intended dll name?
CloudFlareUtilities.dll ?

**Comment by kaso17** [comment] 2016-10-12 05:50
just jackett.dll

**Comment by supremacy2k** [comment] 2016-10-12 05:52
wauw.. even bigger wall of errors, but it does start, and seems to be working.
You want a dump of the error text?

**Comment by kaso17** [comment] 2016-10-12 05:53
yes please :)

**Comment by supremacy2k** [comment] 2016-10-12 05:56
Wall of Errors!

[http://pastebin.com/E3BHSPwp](http://pastebin.com/E3BHSPwp)

**Comment by kaso17** [comment] 2016-10-12 06:23
looks like some mono incompatibility.
Which mono version are you running (mono -V)

**Comment by supremacy2k** [comment] 2016-10-12 06:24
4.2.3

**Comment by kaso17** [comment] 2016-10-12 06:29
any chance you can try updating it?

**Comment by supremacy2k** [comment] 2016-10-12 06:49
It's the latest version in their Beta channel :/

**Comment by kaso17** [comment] 2016-10-12 06:55
and did the error go away?

**Comment by supremacy2k** [comment] 2016-10-12 06:57
Nope, I'm back to the errors from the first post. (swapped the modified dll to a normal one)

**Comment by supremacy2k** [comment] 2016-10-12 07:00
With modified dll, It's the same wall of errors, as in the pastebin paste i posted earlier.
Working though.

**Comment by kaso17** [comment] 2016-10-12 07:01
ok, I guess I'll try to reproduce it myself with debian once I've time.
For now with the updated dll/pull request you should be fine unless you want to use xspeeds.eu
Thank you for your support

**Comment by supremacy2k** [comment] 2016-10-12 07:03
I can live, with the errors.
As long as Jackett is running, my other software is happy (PlexRequests/Sonarr/Couch)

But thank you for your help. :)

**Comment by Lusiphur** [comment] 2016-10-12 08:40
Same thing on Ubuntu 14.10
Latest version (which I have re-installed from scratch)
lusiphur@Tenth:~$ mono /opt/jackett/JackettConsole.exe -v
Jackett v0.7.418.0

Throws this exception on startup
lusiphur@Tenth:~$ mono /opt/jackett/JackettConsole.exe
10-12 09:29:41 Error Top level exception Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Logger)' on type 'UnixLibCurlWebClient'. ---> Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. (See inner exception for details.) ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at (wrapper managed-to-native) System.Reflection.Assembly.InternalGetType (System.Reflection.Assembly,System.Reflection.Module,string,bool,bool) <0x00072>
at System.Reflection.MonoAssembly.GetType (string,bool,bool) <0x0004b>
at System.Reflection.Assembly.GetType (string) <0x0001c>
at Jackett.Utils.Clients.UnixLibCurlWebClient..ctor (NLog.Logger) <0x000ce>
at (wrapper dynamic-method) object.lambda_method (System.Runtime.CompilerServices.Closure,object[]) <0x00062>
at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () <0x0016e>

  --- End of inner exception stack trace ---
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () [0x00000] in <filename unknown>:0 
  at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance (IComponentContext context, IEnumerable`1 parameters) [0x00000] in <filename unknown>:0 
  at Autofac.Core.Resolving.InstanceLookup.Activate (IEnumerable`1 parameters) [0x00000] in <filename unknown>:0 
  at Autofac.Core.Resolving.InstanceLookup.Execute () [0x00000] in <filename unknown>:0 
  at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance (ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) [0x00000] in <filename unknown>:0 
  at Autofac.Core.Resolving.InstanceLookup.ResolveComponent (IComponentRegistration registration, IEnumerable`1 parameters) [0x00000] in <filename unknown>:0 
  at Autofac.Core.Activators.Reflection.AutowiringParameter+<>c__DisplayClass2.<CanSupplyValue>b__0 () [0x00000] in <filename unknown>:0 
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () [0x00000] in <filename unknown>:0 
  at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance (IComponentContext context, IEnumerable`1 parameters) [0x00000] in <filename unknown>:0 
  at Autofac.Core.Resolving.InstanceLookup.Activate (IEnumerable`1 parameters) [0x00000] in <filename unknown>:0 
  at Autofac.Core.Resolving.InstanceLookup.<Execute>b__0 () [0x00000] in <filename unknown>:0 
  at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare (Guid id, System.Func`1 creator) [0x00000] in <filename unknown>:0 
  at Autofac.Core.Resolving.InstanceLookup.Execute () [0x00000] in <filename unknown>:0 
  at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance (ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) [0x00000] in <filename unknown>:0 
  at Autofac.Core.Resolving.ResolveOperation.ResolveComponent (IComponentRegistration registration, IEnumerable`1 parameters) [0x00000] in <filename unknown>:0 
  at Autofac.Core.Resolving.ResolveOperation.Execute (IComponentRegistration registration, IEnumerable`1 parameters) [0x00000] in <filename unknown>:0

Tried the dll in issue 535 and it starts the web server but still throws errors.

**Comment by critaL** [comment] 2016-10-12 14:56
Im as well getting errors after updating my ubuntu server system, some of the files in the update was mono.

sudo mono /opt/jackett/JackettConsole.exe
10-12 16:55:49 Error Top level exception Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Logger)' on type 'UnixLibCurlWebClient'. ---> Could not load file or assembly or one of its dependencies. (See inner exception for details.) ---> System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
  at (wrapper managed-to-native) System.Reflection.Assembly:InternalGetType (System.Reflection.Assembly,System.Reflection.Module,string,bool,bool)
  at System.Reflection.MonoAssembly.GetType (System.String name, System.Boolean throwOnError, System.Boolean ignoreCase) [0x00028] in <dca3b561b8ad4f9fb10141d81b39ff45>:0
  at System.Reflection.Assembly.GetType (System.String name) [0x00000] in <dca3b561b8ad4f9fb10141d81b39ff45>:0
  at Jackett.Utils.Clients.UnixLibCurlWebClient..ctor (NLog.Logger l) [0x00031] in <b44bf1bae93c4220b8bfb71f12d58544>:0
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object[])
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () [0x00075] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
   --- End of inner exception stack trace ---
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () [0x00107] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance (Autofac.IComponentContext context, System.Collections.Generic.IEnumerable`1[T] parameters) [0x000b8] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Resolving.InstanceLookup.Activate (System.Collections.Generic.IEnumerable`1[T] parameters) [0x0001a] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Resolving.InstanceLookup.Execute () [0x0002e] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance (Autofac.Core.ISharingLifetimeScope currentOperationScope, Autofac.Core.IComponentRegistration registration, System.Collections.Generic.IEnumerable`1[T] parameters) [0x0005e] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Resolving.InstanceLookup.ResolveComponent (Autofac.Core.IComponentRegistration registration, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Activators.Reflection.AutowiringParameter+<>c__DisplayClass2.<CanSupplyValue>b__0 () [0x00011] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () [0x00025] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance (Autofac.IComponentContext context, System.Collections.Generic.IEnumerable`1[T] parameters) [0x000b8] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Resolving.InstanceLookup.Activate (System.Collections.Generic.IEnumerable`1[T] parameters) [0x0001a] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Resolving.InstanceLookup.<Execute>b__0 () [0x00007] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare (System.Guid id, System.Func`1[TResult] creator) [0x0002f] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Resolving.InstanceLookup.Execute () [0x00047] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance (Autofac.Core.ISharingLifetimeScope currentOperationScope, Autofac.Core.IComponentRegistration registration, System.Collections.Generic.IEnumerable`1[T] parameters) [0x0005e] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Resolving.ResolveOperation.ResolveComponent (Autofac.Core.IComponentRegistration registration, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0
  at Autofac.Core.Resolving.ResolveOperation.Execute (Autofac.Core.IComponentRegistration registration, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <ca1ca41f44e0487e9a15b2f64e38c7de>:0

**Comment by JigSawFr** [comment] 2016-10-12 19:39
Please update to latest version :)

**Comment by critaL** [comment] 2016-10-12 19:47
It seems to be working after the new update, Thanks!

**Comment by Lusiphur** [comment] 2016-10-12 19:58
Oct 12, 2016 08:56:53 PM	Info	
Checked for a updated release but none was found.

Clicking check for updated releases on the UI and that's what shows in the log. Am I missing something about applying an update on Ubuntu? Note I can see the new version on 
https://github.com/Jackett/Jackett/releases

**Comment by supremacy2k** [comment] 2016-10-12 20:33
After newest update, i get these errors:

10-12 22:35:39 Error System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at (wrapper managed-to-native) System.Reflection.Assembly:InternalGetType (System.Reflection.Assembly,System.Reflection.Module,string,bool,bool)
  at System.Reflection.MonoAssembly.GetType (System.String name, System.Boolean throwOnError, System.Boolean ignoreCase) [0x00028] in <dca3b561b8ad4f9fb10141d81b39ff45>:0
  at System.Reflection.Assembly.GetType (System.String name) [0x00000] in <dca3b561b8ad4f9fb10141d81b39ff45>:0
  at Jackett.Utils.Clients.UnixLibCurlWebClient..ctor (NLog.Logger l) [0x0003a] in <d6e74e4a841246608fb665094d4db2b9>:0
10-12 22:35:39 Error UnixLibCurlWebClient: Error while loading CloudFlareUtilities.dll from /opt/jackett

It's a lot better than the massive wall of errors i got before. :D

**Closed** 2016-10-16 14:09 UTC
Labels: Core, Fix
