### ISSUE TITLE
[rarbg] Could not find releases from this URL (Config)

### ISSUE THREAD

**Issue by jprokos** [Jackett/Jackett#13122] opened 2022-04-07 20:08 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-04-07 13:45:33	Info	
Using HTTP Client: HttpWebClient2
2022-04-07 13:45:33	Info	
Using FlareSolverr: http://127.0.0.1:8191
2022-04-07 13:45:33	Info	
Using proxy: Disabled
2022-04-07 13:45:33	Info	
App config/log directory: /Users/john/.config/Jackett
2022-04-07 13:45:33	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-04-07 13:45:33	Info	
Running in Docker: No
2022-04-07 13:45:33	Info	
Jackett variant: CoreMacOs
2022-04-07 13:45:33	Info	
OS version: Unix 10.15.7 (64bit OS) (64bit process)
2022-04-07 13:45:33	Info	
Environment version: 6.0.3 (/Users/john/GitHub/Jackett/)
2022-04-07 13:45:31	Info	
Starting Jackett v0.20.807
```

### Description

Consistently having issues with the RARBG indexer, whether accessing directly from the jackett dashboard or via qBittorrent.

I can find the series I am looking for when using the RARBG website, but consistently get no results from jackett.

I have set the options in jackett's RARBG settings to 2 tries 1 second delay and 3 tries 2 second delay, but this does not help.

### Logged Error Messages

```text
System.Exception: Could not find releases from this URL
   at Jackett.Common.Indexers.RarBG.<>c.<ApplyConfiguration>b__11_0() in /Users/runner/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 128
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 258
   at Jackett.Common.Indexers.RarBG.ApplyConfiguration(JToken configJson) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 127
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /Users/runner/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment] 2022-04-07 20:18
Absolutely nothing we can do about it.
As you may know, RarBG sysop forbids us using HTML scraping to process pages off the main site.
Instead RarBG provides an API service at https://torrentapi.org/ which we are obliged to use.
However, over the last 12 months or more, the API server is intermittently failing to return results.
We added a retry but sometimes that also does not succeed.
I often have to repeat the search two to four times to get results.
closing as a duplicate of #12723

**Closed by garfield69** 2022-04-07 20:18 UTC

**Comment by jprokos** [comment] 2022-04-09 21:47
@garfield69 Thank you for the response. I failed to find this when doing a search, sorry for the duplicate.
