### ISSUE TITLE
[yggtorrent] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by Eldoc62** [Jackett/Jackett#2213] opened 2017-12-01 07:39 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

Hi :)

I'm sure and i test my login ...

Is good but not with jackett

**Comment by Eldoc62** [comment] 2017-12-01 07:43
May be theadress but not ok here :/

https://ww1.yggtorrent.com/

https://yggtorrent.com/

**Comment by garfield69** [comment] 2017-12-01 07:43
Duplicate of #2211

**Closed by garfield69** 2017-12-01 07:43 UTC
Labels: Duplicate
