### ISSUE TITLE
Please add https://tamilrockers.ws to the list of trackers

### ISSUE THREAD

**Issue by jkailasam** [Jackett/Jackett#1831] opened 2017-09-15 06:19 UTC
Is it possible to add "http://tamilrockers.nz/index.php?" to the list of trackers? This tracker is for mainly Indian movies. 

thanks

**Comment by kaso17** [comment] 2017-09-15 06:28
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by garfield69** [comment] 2019-02-11 06:26
site is not suitable for cardigann processing, requires native c# indexer.

**Comment by garfield69** [comment] 2019-07-01 00:11
domain gone.

**Comment by anburocky3** [comment] 2019-08-10 17:07
Domain renamed: https://tamilrockers.ws/

**Comment by nero12** [comment] 2020-04-25 16:20
hi, whats the status on this ? was it possible to add it to jackett ?

**Comment by garfield69** [comment] 2020-04-25 19:51
waiting on a c# volunteer to write an indexer for this site.

**Comment by ngosang** [comment] 2020-05-16 07:26
Duplicate of #5570

**Closed by ngosang** 2020-05-16 07:26 UTC
Labels: Help wanted, Needs C#, New Private Tracker, Returns one-title-many-torrents
