### ISSUE TITLE
High CPU usage when using Sock5 Proxy

### ISSUE THREAD

**Issue by tradenet** [Jackett/Jackett#4639] opened 2019-02-11 00:11 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by tradenet** [comment] 2019-02-11 00:13
Version 0.10.724.0
and docker version 18.09.1
Similar to #2602
Removing proxy Sock5 causes the issue to go away.

**Comment by BanditBanditBandit** [comment] 2019-02-14 00:32
I have had a similar experience and came to get information. I turned on Sock5 proxy today and it caused cpu usage to go up to 99% twice, each time I had to terminate the service and restart. 

 Current: v0.10.759 Latest: v0.10.759

**Comment by flightlevel** [comment] 2019-02-14 08:57
Duplicate of https://github.com/Jackett/Jackett/issues/2602

**Closed by flightlevel** 2019-02-14 08:57 UTC

**Comment by BanditBanditBandit** [comment] 2019-02-15 04:51
it spiked again just now, had to restart it. so didnt fix it
