### ISSUE TITLE
[rarbg] Exception (rarbg): Request to https://torrentapi.org/pubapi_v2.php?get_token=get_token

### ISSUE THREAD

**Issue by fxckingham** [Jackett/Jackett#12616] opened 2021-11-30 00:26 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
.
```

### Description

.

### Logged Error Messages

Unable to connect to indexer: Torznab error detected: Jackett.Common.IndexerException: Exception (rarbg): Request to https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=jackett_v0.20.71 failed (Error 521) - The tracker seems to be down.
 ---> System.Exception: Request to https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=jackett_v0.20.71 failed (Error 521) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown(WebResult response) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 638
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 594
   at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass11_0.<<RequestWithCookiesAndRetryAsync>b__0>d.MoveNext() in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 567
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 569
   at Jackett.Common.Indexers.RarBG.RenewalTokenAsync(Boolean force) in D:\a\1\s\src\Jackett.Common\Indexers\RarBG.cs:line 302
   at Jackett.Common.Indexers.RarBG.PerformQueryWithRetry(TorznabQuery query, Boolean retry) in D:\a\1\s\src\Jackett.Common\Indexers\RarBG.cs:line 141
   at Jackett.Common.Indexers.RarBG.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\RarBG.cs:line 134
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 758
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 432

### Screenshots

![image](https://user-images.githubusercontent.com/95258948/143963362-01e6cc0f-3c40-44ef-83a5-fa810b4bbe6e.png)
![image](https://user-images.githubusercontent.com/95258948/143963402-e41f5fab-ff9b-43e0-84e4-514421d7eec2.png)

**Comment by garfield69** [comment] 2021-11-30 00:27
duplicate of #12612

**Closed by garfield69** 2021-11-30 00:27 UTC

**Comment by fxckingham** [comment] 2021-11-30 00:31
> duplicate of #12612

sorry I missed that, thanks for letting me know!
