### ISSUE TITLE
[privatehd] Verification required (Config)

### ISSUE THREAD

**Issue by Bre77** [Jackett/Jackett#8738] opened 2020-05-22 04:37 UTC
### Environment

**OS**: Docker

**.Net Runtime**:

**.Net Version**:

**Jackett Version**: 0.16.515.0

**Last Working Jackett Version**: n/a

**Are you using a proxy or VPN?** no

### Description

privatehd now has a captcha preventing login by Jackett

### Logged Error Messages

An error occurred while testing this indexer
Exception (privatehd): Verification required: Verification required
Click here to open an issue on GitHub for this indexer.
[log.txt](https://github.com/Jackett/Jackett/files/4666094/log.txt)

**Comment by Bre77** [comment] 2020-05-22 04:39
[Cleaner Enhanced Log](https://github.com/Jackett/Jackett/files/4666098/log.1.txt)

**Comment by garfield69** [comment] 2020-05-22 04:49
you are referring to this?
![image](https://user-images.githubusercontent.com/6933240/82632359-1612cd80-9c4c-11ea-8c3c-4aa82da2020f.png)
we are going to have to switch to using a cookie method :-(
i'll code up the indexer.

**Comment by garfield69** [comment] 2020-05-22 04:50
oh, its not yaml, but C#. assigning to the c# dev.

**Comment by Bre77** [comment] 2020-05-22 05:51
Duplicate of 8727, not sure how I didnt find that in my search.

**Comment by garfield69** [comment] 2020-05-22 06:17
closing as duplicate of #8727

**Closed by garfield69** 2020-05-22 06:17 UTC
Labels: Duplicate
