### ISSUE TITLE
[req]: watchsomuchproxy.com

### ISSUE THREAD

**Issue by hbednar** [Jackett/Jackett#14409] opened 2023-06-01 09:43 UTC
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Watch So Much
- URL: https://watchsomuchproxy.com/
- Description: TV Shows and Movies Both, Streaming and Torrents
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment] 2023-06-01 09:49
duplicate of #9876 https://github.com/Jackett/Jackett/issues/9876#issuecomment-1120585592

**Closed by garfield69** 2023-06-01 09:49 UTC
