### ISSUE TITLE
[tvchaosuk] Exception (tvchaosuk): Login failed: No form found on https://tvchaosuk.com/login using form selector form: Parse error (Test)

### ISSUE THREAD

**Issue by bmn001** [Jackett/Jackett#7615] opened 2020-03-10 16:10 UTC
### Environment

**OS**: Raspbian

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
n/a
**.Net Version**:
n/a
**Jackett Version**:
0.13.560.0

**Last Working Jackett Version**:
same

**Are you using a proxy or VPN?** [yes/no]
yes

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
TVChaosUK fails the Jackett test.  Based on error log, it can't find the login form.

### Logged Error Messages
```
Jackett.Common.IndexerException: Exception (tvchaosuk): Login failed: No form found on https://tvchaosuk.com/login using form selector form
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://tvchaosuk.com/login using form selector form
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 555
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1339
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1665
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 220
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```
### Screenshots
n/a

**Comment by bmn001** [comment] 2020-03-10 16:13
Not a duplicate.  This is new behavior, and I've included a full error log.

**Comment by garfield69** [comment] 2020-03-10 20:35
this kind of error is usually the result of a login that has good credentials, but is prevented by the site from accessing the torrent search page.

Please access the site with your browser directly, to confirm your credentials are still good, and check that you do not have any outstanding alerts, notices or unread PM. 
Also check you have a good ratio.

If you have changed you password recently, make sure to logoff the site first before trying Jackett. Some sites so not save the password until logout.

does any of the above apply to you?

**Comment by bmn001** [comment] 2020-03-15 02:30
Thank you for the tips!

Unfortunately, none of that seems to be the case here.  I've logged out/in, no errors.  Credentials still good, no alerts, ratio's good, etc.

I was able to search for and download a .torrent  just now from this tracker manually, but Jackett isn't able to do the same.

**Comment by garfield69** [comment] 2020-03-15 02:40
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by rrrevin** [comment] 2020-03-18 13:45
Heads up.. this might be an issue with the OP's system.
I use this site daily via Jackett, and do not have this issue at all.

**Comment by cadatoiva** [comment] 2020-03-18 16:01
Thanks for the heads up 😀

There can be a number of reasons for the error, which is why we've asked for the full logs from OP to make a better determination as to the root cause and help resolve the issue. Once we have the logs, if it's something we can fix in Jackett, even if for a special edge case, we will. If it's something completely outside our control, then we close the issue with a recommendation of who to go to or what OP can do to resolve it themselves.

**Closed** 2020-03-22 10:38 UTC
Labels: Full logs needed
