### ISSUE TITLE
[eztv] Exception (eztv): Connection reset by peer: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by LarsaSolidor** [Jackett/Jackett#6236] opened 2019-10-22 21:40 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by LarsaSolidor** [comment] 2019-10-23 08:02
Using traefik as a reverse proxy. Some trackers successfully connect. Many give me this SSL error

**Comment by garfield69** [comment] 2019-10-23 23:34
Please provide the **full enhanced log** file and I can take a look and see if there are any clues why you are having issues. But I doubt very much this has anything to so with jackett, it sounds like a certificate protocol mismatching issues to me.

1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by emorytaylor** [comment] 2019-10-25 16:41
[log.txt](https://github.com/Jackett/Jackett/files/3772967/log.txt)
Here's a log attachment for what I think is the same error. I'm using a wireguard proxy on a current version of fedora

**Comment by garfield69** [comment] 2019-10-25 20:08
@emorytaylor  thanks for the log you provided.
so your log shows that the critical error is `Exception (1337x): error:1408F10B:SSL routines:ssl3_get_record:wrong version number`
which according to the google search I just did, is the type of error that can occur when the versions in client/server SSL records do not agree.
Now, your log shows you are on:
```
Jackett v0.12.866.0
Environment version: 3.0.0 (/opt/Jackett/) 
OS version: Unix 5.3.7.301 (64bit OS) (64bit process) 
Jackett variant: CoreLinuxAmdx64 
```
I started my ubuntu18 desktop and used my Jackett (without a proxy since I don't have one)
```
Jackett v0.12.866.0 
Environment version: 4.0.30319.42000 (/home/garfield69/Downloads/Jackett/) 
OS version: Unix 4.15.0.65 (64bit OS) (64bit process) 
Jackett variant: CoreLinuxAmdx64 
```
and assuming your 1337x indexer site link is set to `https://1337x.to` like mine is, then I have no problem accessing 1337x via jackett.

So given that we are on the same code version for jackett and using the same coreLinuxAmdx64 variant, we can eliminate Jackett as a suspect, which suggests that the proxy may be part of the problem, or perhaps your computer's certificate store (not sure about the latter).

unfortunately, this is where my lack of experience comes to the fore: I have no idea what can be done about this for your case. I don't use proxies and haven't the first clue about how they work, and there is no similar ticket in this Jackett GitHub that has dealt with this before which I can use as a reference.

ping to any one what can help with this ticket?

**Comment by LarsaSolidor** [comment] 2019-10-29 12:55
[log.txt](https://github.com/Jackett/Jackett/files/3783589/log.txt)

Here's my log, the error occurs when trying to test EZTV.

**Comment by garfield69** [comment] 2019-10-29 18:04
@LarsaSolidor  thanks for your logs, which show the critical error as:
```
Unable to read data from the transport connection: Connection reset by peer.,
System.Net.Sockets.SocketException (104): Connection reset by peer,
```
looking back through other tickets where reset-by-peer errors were reported, they all were caused by something outside jackett control and not a single one had a simple explanation as to the reason why :-(
most likely something to do with a mismatch of certificate info between client and server, with traefik  in the middle most likely the culprit, but this is beyond my meagre skills to solve, sorry.
I've assgined this to a more experienced dev.

**Comment by bezzpezz** [comment] 2019-11-13 10:44
The fix for this in my case was to use a proxy. The EZTV site was being blocked at the ISP level.
Try to configure a working proxy in Jackett and then test again.

**Comment by ngosang** [comment] 2020-01-11 10:47
@LarsaSolidor eztv is working fine for me in Linux .Net Core. This kind of problems are usually related to network: proxy, vpn or isp blocks. You can try alternative domains.

**Closed by ngosang** 2020-01-11 10:47 UTC
Labels: Help wanted
