### ISSUE TITLE
[New Tracker REQ] hdtorrents.it

### ISSUE THREAD

**Issue by memnos** [Jackett/Jackett#1043] opened 2017-02-08 15:38 UTC
Indexer Name
hdtorrents.it

Type
Movies, TV, Anime, Books, Games, Software

Is the indexer private or public? If private, can you provide an invite?
Private, don't have invitation, but can give access

Indexer URL
hdtorrents.it

Indexer language
Italian

**Comment by kaso17** [comment] 2017-02-08 17:03
Already requested in #492
Very low priority for me as they're using geo blocking

**Comment by RoloSoze** [comment] 2017-03-13 22:33
@rafuz Mentioned in #1153 that he can provide an invite if required.

**Comment by kaso17** [comment] 2017-03-14 10:35
```This site can’t be reached

The connection was reset.```

Still appears to be geoblocked.

**Comment by rafuz** [comment] 2017-03-14 11:52
It is just offline this morning... I don't know why, even the tracker is offline now.
I will check later and let you know

**Comment by rafuz** [comment] 2017-03-15 17:53
Reverted to geoblocking, I am sad :'(

**Comment by kaso17** [comment] 2017-03-15 18:56
@bonny1992: with your recent addition of some italian trackers: I assume you're from italy?
Maybe you can help with this one?

**Comment by bonny1992** [comment] 2017-03-15 19:56
Yep, I'm italian :D You assumed correctly haha.
Sure, in the next days I'll see what can I do with this tracker.
If @rafuz could provide me an invite or access I'd be able to do that.

Related: Is it still geolocked? What kind of error it gives when you try to enter from a non-italian IP?

**Comment by RoloSoze** [comment] 2017-03-16 03:55
@bonny1992 The error I get when trying to access it from a non-Italian IP:
404 Not Found

**Comment by bonny1992** [comment] 2017-03-16 07:52
@RoloSoze 
From where is your IP? 
Because I have some non Italian ips and I can't reproduce the error. 
It may be locked outside Europe.

**Comment by rafuz** [comment] 2017-03-16 08:19
@bonny1992  Actually you can freely register an account [http://hdtorrents.it/signup.php](url)
The geoblocking has changed someway, but not completely removed.

**Comment by kaso17** [comment] 2017-03-16 10:26
I tried it from 3 different IPs (2 European, 1 US). 
On both links (http://hdtorrents.it/ and http://hdtorrents.it/signup.php) I'm getting the 404 error.

**Comment by bonny1992** [comment] 2017-03-16 10:44
@rafuz 
Oh, neat. I just registered.

@kaso17 
I don't understand properly which country is blocked and which is unlocked.

Also they handle categories in a very weird way.
![Releases](https://i.imgbox.com/C0hX7aMl.png)

As you can see, "Chicago Fire" is marked as the same category of "Dio esiste e vive a Bruxelles".
There is no direct way to get the correct categories from the list, the releases are listed only as 
![Categories](https://i.imgbox.com/CDBUAAnV.png)

(So no "TV Series" or "Movie", it's only "cat=1" for 1080p rips for example).

How can I handle this?

**Comment by kaso17** [comment] 2017-03-16 12:10
The only way would be to match on certain strings in e.g. the title

In that case add some dummy categories:
```yaml
      - {id: 2040, cat: Movies/HD}
      - {id: 5040, cat: TV/HD}
```

And then use a case to map it to a category based on a matching selector
```yaml
      category:
        case:
          "a[href^=\"details.php\"]:contains(\"Stagione\")": 5040 # TV/HD
          "a[href^=\"details.php\"]:matches(\"S\\d{2}E\\d{2}\")": 5040 # TV/HD
          "*": 2040 # default to Movies/HD
```

**Comment by rafuz** [comment] 2017-03-16 14:50
I don't know if ti could be useful but there is a CP provider for hdtorrents.it too: [https://github.com/neothematrix/hdtorrentsit-cp-provider](url)

**Comment by rafuz** [comment] 2017-03-21 11:31
![image](https://cloud.githubusercontent.com/assets/22271829/24145592/23fbf512-0e32-11e7-9519-dc199bc823a6.png)

Seems strange but when creating an RSS link you can choose categories.
So somewhere in the release should be a category set.

**Comment by RoloSoze** [comment] 2017-03-23 04:44
Closed through #1180

**Comment by kaso17** [comment] 2017-03-23 04:49
Thank you @bonny1992 for adding it. Please test it. It might need some keywordsfilters like shareisland to work for TV series.

**Comment by bonny1992** [comment] 2017-03-23 18:43
@kaso17
Sure, no problem.
I need to know how Sonarr/Sickrage searches for season packs, though.
Like S01E01-10 or S01E02-E10?

**Comment by kaso17** [comment] 2017-03-23 18:56
AFAIK Sonarr will just search for the specific season (episode ranges are not used)

**Comment by rafuz** [comment] 2017-03-27 11:50
Seems that the plugin does not handle year correctly when searching from Couchpotato.
This is what happens:

![image](https://cloud.githubusercontent.com/assets/22271829/24354910/0b090e70-12f4-11e7-8858-9f83d2abd493.png)

When I search the movie title with year without brackets I can't find it. Couchpotato searches without brackets so  I see that it can't match any movies.

**Comment by rafuz** [comment] 2017-03-29 09:38
There is a problem with torrents name/info too.
Couchpotato could not find any details from the torrent (quality, language) as the query comes back with only title and year.

**Comment by bonny1992** [comment] 2017-03-31 06:39
Oh, I can see this definition has some problems. 

Sadly right now I'm quite busy with work, but I'll have a look at it as soon as possible. 

Thank you all in the meanwhile for reporting the issues!

**Comment by JigSawFr** [comment] 2017-03-31 07:36
@rafuz please create a new issue for problems with providers ;)

**Comment by ilike2burnthing** [comment] 2021-10-12 22:36
https://hdtorrents.xyz/ 404 Not Found (nginx)

**Closed** 2021-10-13 08:57 UTC
