### ISSUE TITLE
[hdtorrents] Exception (hdtorrents): String '02=

### ISSUE THREAD

**Issue by thedreamfinder** [Jackett/Jackett#7453] opened 2020-03-02 13:27 UTC
### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.13.378.0

**Last Working Jackett Version**: same

**Are you using a proxy or VPN?** no

### Description
Just went to test the indexer. This indexer was working until today.

### Logged Error Messages

An error occured while testing this indexer
Exception (hdtorrents): String '02="" mar="" 2020="" 07:59:27="" +0200=""' was not recognized as a valid DateTime.: Parse error

### Screenshots
![image](https://user-images.githubusercontent.com/13840067/75680416-920a0480-5c5f-11ea-9b71-b4f78cdb445e.png)

**Comment by cadatoiva** [comment] 2020-03-02 14:59
Duplicate of #7426

**Closed by cadatoiva** 2020-03-02 14:59 UTC
