### ISSUE TITLE
[hdspain] Object reference not set to an instance of an object. (Test)

### ISSUE THREAD

**Issue by auribef** [Jackett/Jackett#7873] opened 2020-03-27 07:58 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Unraid

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.14.297.0

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** [yes/no] no

### Description

Click on test connection, then the pop up with the error appears. This happens with all my indexers.

An error occured while testing this indexer
Object reference not set to an instance of an object.
Click here to open an issue on GitHub for this indexer.

### Logged Error Messages

2020-03-27 08:54:08 | Error | System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Services.CacheService.<>c__DisplayClass3_1.<CacheRssResults>b__2(CachedResult i) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 35    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)    at Jackett.Common.Services.CacheService.CacheRssResults(IIndexer indexer, IEnumerable`1 releases) in /home/vsts/work/1/s/src/Jackett.Common/Services/CacheService.cs:line 35    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 228    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
-- | -- | --

### Screenshots

![error](https://user-images.githubusercontent.com/11899178/77734286-b19b0f80-7008-11ea-825c-b7e8d93922b2.PNG)
![indexers](https://user-images.githubusercontent.com/11899178/77734289-b233a600-7008-11ea-8bd4-424603734175.PNG)

**Comment by cadatoiva** [comment] 2020-03-27 08:10
Duplicate of #7870 fix is already in the pipeline

**Closed by cadatoiva** 2020-03-27 08:10 UTC

**Comment by garfield69** [comment] 2020-03-27 09:01
Jackett 0.14.299
