### ISSUE TITLE
Add Spacetorrent.pw ! {FRENCHTRACKER}

### ISSUE THREAD

**Issue by NBSDEVApp** [Jackett/Jackett#2901] opened 2018-04-05 19:46 UTC
Hi,
My request is to add www.spacetorrent.pw to Jackett.
Its a great french tracker
Thanks for this

**Comment by Christelle06** [comment] 2018-04-05 23:34
Hello, Could you sponsorship me for this privateTracker...  Im tired with this t411 and yggtorrent im looking for something stable for me and my family

**Comment by kaso17** [comment] 2018-04-06 10:48
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by alaunay** [comment] 2018-05-05 18:12
The tracker is in open mode and has a new domain:
https://www.spacetorrent.nl/

**Comment by pipopop** [comment] 2018-10-24 15:37
Open mode.
Here is the headers and cap section:
`Header
Each definition must start with a header like this:

---
  site: spacetorrent # Internal name of the indexer (all lower case, typically the
                     # display name without any special characters, same as filename)
  name: Space Torrent # Display name (The full name of the tracker)
  description: "Space Torrent est un tracker intergalactique"
  language: fr-fr # Langauge code of the main language used on the tracker
                  # See http://www.lingoes.net/en/translator/langcode.htm for possible
                  # options
  type: private # Indexer type, possible options:
               #   public: no registration required
               #   semi-private: registration required, but always open
               #   private: registration required (invite/application needed)
  encoding: UTF-8 # Website encoding used by the tracker
  links: # List of known domains (the first one is the default, must end with /)
    - https://www.spacetorrent.cloud/
  legacylinks: # List of old domains which no longer work. If one of these URLs is
               # configured it will be automatically replaced with the default one.
    - https://spacetorrent.nl/
  certificates: # If the tracker uses untrusted HTTPS certificates (self signed, expired,
                # ...) you can specify a list of
                # thumbprint hashes which should be accepted as valid anyway.
                # This shouldn't be needed in most cases.
  
 Caps
Next you've to specify the capabilities of the indexer.

  caps: # Capabilities of the indexer
    categorymappings: # Mapping between the tracker categories and the
                      # Newznab categories.
                      # Not supported by Cardigann.
                      # - id:      The tracker specific category ID.
                      #            Can be a string too.
                      # - cat:     The corresponding newznab predefined category.
                      #            See this list for valid options:
                      #            https://github.com/nZEDb/nZEDb/blob/dev/docs/newznab_api_specification.txt#L608-L695
                      # - desc:    The tracker category name.
                      #            Optional.
                      #            If provided it will be used for a 1:1 mapping between
                      #            tracker and newznab categories.
                      # - default: default flag, can be true or false (default is false)
                      #            Optional.
                      #            Specify if this category should be used as default (if the search query doesn't
                      #            contain any categories).
      - {id: 0, cat: Custom, desc: "Toutes les catégories", default: true}
      - {id: 41, cat: PC/Phone-Android, desc: "Applications / Android", default: false}
      - {id: 42, cat: PC/Phone-IOS, desc: "Applications / iOSr", default: false}
      - {id: 57, cat: PC/Mac, desc: "Ebooks / Bandes dessinées", default: false}
      - {id: 58, cat: Books/Unknown, desc: "Ebooks / Bandes dessinées X", default: false}
      - {id: 902, cat: XXX/x264, desc: "Porn HD", default: false}
      - {id: 31, cat: Books/Magazines, desc: "Ebooks / Journaux", default: false}
      - {id: 32, cat: Books/Ebook , desc: "Ebooks / Livres", default: false}
      - {id: 59, cat: Books/Comics  , desc: "Ebooks / Manga", default: false}
      - {id: 77, cat: Movies/HD , desc: "Films / 4K rip", default: false}
      - {id: 23, cat: Movies/Other, desc: "Films / Animés", default: false}
      - {id: 49, cat: Movies/Other, desc: "Films / BDrip", default: false}
      - {id: 51, cat: Movies/BluRay, desc: "Films / BluRay 1080", default: false}
      - {id: 52, cat: Movies/BluRay, desc: "Films / BluRay 4K", default: false}
      - {id: 50, cat: Movies/BluRay, desc: "Films / BluRay 720", default: false}
      - {id: 19, cat: Movies/BluRay, desc: "Films / BRrip", default: false}
      - {id: 74, cat: Movies/Other, desc: "Films / Documentaires", default: false}
      - {id: 20, cat: Movies/DVD , desc: "Films / DVD-R 5", default: false}
      - {id: 48, cat: Movies/DVD , desc: "Films / DVD-R 9", default: false}
      - {id: 53, cat: Movies/DVD , desc: "Films / DVDrip", default: false}
      - {id: 64, cat: Movies/HD, desc: "Films / HDLight 1080", default: false}
      - {id: 63, cat: Movies/HD, desc: "Films / HDLight 720", default: false}
      - {id: 55, cat: Movies/HD, desc: "Films / HDrip 1080", default: false}
      - {id: 54, cat: Movies/HD, desc: "Films / HDrip 720", default: false}
      - {id: 60, cat: Movies/HD, desc: "Films / HDTV", default: false}
      - {id: 62, cat: Movies/HD, desc: "Films / HDTV 1080", default: false}
      - {id: 61, cat: Movies/HD, desc: "Films / HDTV 720", default: false}
      - {id: 75, cat: Movies/Other, desc: "Films / VHSrip", default: false}
      - {id: 65, cat: Movies/WEBDL, desc: "Films / Web-DL", default: false}
      - {id: 67, cat: Movies/WEBDL, desc: "Films / Web-DL 1080", default: false}
      - {id: 68, cat: Movies/WEBDL, desc: "Films / Web-DL 4K", default: false}
      - {id: 69, cat: Movies/WEBDL, desc: "Films / Web-DL 4K", default: false}
      - {id: 66, cat: Movies/WEBDL, desc: "Films / Web-DL 720", default: false}
      - {id: 70, cat: Movies/WEBDL, desc: "Films / WEBrip", default: false}
      - {id: 72, cat: Movies/WEBDL, desc: "Films / WEBrip 1080", default: false}
      - {id: 73, cat: Movies/WEBDL, desc: "Films / WEBrip 4K", default: false}
      - {id: 71, cat: Movies/WEBDL, desc: "Films / WEBrip 720", default: false}
      - {id: 9, cat: XXX, desc: "Films X", default: false}
      - {id: 76, cat: Console/3DS, desc: "Jeux / 3DS", default: false}
      - {id: 29, cat: PC/Phone-Android, desc: "Jeux / Android", default: false}
      - {id: 12, cat: Console/Other, desc: "Jeux / GameBoy", default: false}
      - {id: 45, cat: Console/Other, desc: "Jeux / GameBoy Advance", default: false}
      - {id: 30, cat: PC/Phone-IOS, desc: "Jeux / iOS", default: false}
      - {id: 46, cat: PC/Mac, desc: "Jeux / Mac", default: false}
      - {id: 4, cat: PC/ISO, desc: "Jeux / PC", default: false}
      - {id: 36, cat: Console/Other, desc: "Jeux / PS1", default: false}
      - {id: 37, cat: Console/Other, desc: "Jeux / PS2", default: false}
      - {id: 33, cat: Console/PS3, desc: "Jeux / PS3", default: false}
      - {id: 34, cat: Console/PS4, desc: "Jeux / PS4", default: false}
      - {id: 78, cat: Console/Wii , desc: "Jeux / Wii", default: false}
      - {id: 38, cat: Console/Xbox, desc: "Jeux / Xbox", default: false}
      - {id: 40, cat: Console/Xbox One, desc: "Jeux / Xbox One", default: false}
      - {id: 39, cat: Console/Xbox 360, desc: "Jeux / Xbox360", default: false}
      - {id: 28, cat: PC/Mac, desc: "Logiciels / Apple", default: false}
      - {id: 26, cat: PC, desc: "Logiciels / Linux", default: false}
      - {id: 27, cat: PC/ISO, desc: "Logiciels / Windows", default: false}
      - {id: 56, cat: Audio, desc: "Musiques / FLAC", default: false}
      - {id: 6, cat: Audio/MP3, desc: "Musiques / MP3", default: false}
      - {id: 7, cat: TV, desc: "Séries", default: false}
      - {id: 44, cat: XXX, desc: "Séries  X", default: false}
      - {id: 47, cat: TV/Anime, desc: "Séries animées", default: false}
      - {id: 43, cat: TV/HD, desc: "Séries HD", default: false}
    modes: # Specify which torznab search modes and attributes are supported by the
           # indexers.
           # Implementation note: Jackett doesn't care very much about this but you
           # still should specify the correct modes.
           # Especially don't include imdbid if the tracker doesn't support
           # searching by imdbid.
      # I think no for all :
      #tv-search: [q, season, ep, imdbid]
      #movie-search: [q, imdbid]
      #music-search: [q, album, artist, label, year]`

**Comment by pipopop** [comment] 2019-02-08 09:31
Hi Garlfield ! Here is the invitation

**Comment by garfield69** [comment] 2019-02-08 17:57
registration and login successful. Thank you.

**Comment by garfield69** [comment] 2019-02-08 21:09
try Jackett 0.10.724
had to resort to using cookie for login, could not make the other methods work.

**Comment by garfield69** [comment] 2019-02-09 08:07
Hmm. only works if you are already signed in via the browser, i.e. you have not actively logged out.
Otherwise Jackett gets a login redirect that breaks the session.
i'll look into this when I can, but it may turn out that this site will require a native c# indexer to work properly.

**Comment by pipopop** [comment] 2019-02-09 09:49
Ok thanks. I will add other french Tracker. Did the work done by nikogaug help you ?

**Comment by pipopop** [comment] 2019-02-09 13:14
SpaceTorrent have an API : [https://www.spacetorrent.cloud/api/](https://www.spacetorrent.cloud/api/)
Can't that help ?

**Comment by garfield69** [comment] 2019-02-09 17:43
>Did the work done by nikogaug help you ?

where is the work by nikogaug  that you are referring to?

>SpaceTorrent have an API : https://www.spacetorrent.cloud/api/ Can't that help ?

SpaceTorrent's API doc states the API is a work in progress, only returning general data for now, no download links.
here is a sample search result from `https://www.spacetorrent.cloud/api_get.php?torrent=Star%20Wars%20The%20Clone%20Wars.S06`
```jason
[{"name":" Star Wars The Clone Wars.S06.TRUEFRENCH.720p.BluRay.x264-FTMVHD","category":"0","id":"5003","tags":"Catherine Taber, James Arnold Taylor, Ashley Eckstein, Matt Lanter, Tom Kane, Tom Kenny, Dee Bradley Baker, Corey Burton, Phil LaMarr, Stephen Stanton, Nika Futterman, Matthew Wood,ewan,star wars,clone wars s06,clone wars saison 6"}]

**Comment by garfield69** [comment] 2019-02-10 06:55
I have figured out how to login the spacetorrent indexer using the username and password with a7928ea4a8aabe1b72fd6b5993d24992133b4a94 in Jackett pre-release 0.10.733  \o/

**Comment by pipopop** [comment] 2019-02-10 11:12
> I have figured out how to login the spacetorrent indexer using the username and password with [a7928ea](https://github.com/Jackett/Jackett/commit/a7928ea4a8aabe1b72fd6b5993d24992133b4a94) in Jackett pre-release 0.10.733 \o/

Great job ! works great.

> where is the work by nikogaug that you are referring to?
Sorry. It's a mistake. Did the work I did help you (headers, caps, settings) ?

**Comment by garfield69** [comment] 2019-02-10 15:20
> Did the work I did help you (headers, caps, settings)

yes, it was a useful starting point,  thank you.

**Comment by garfield69** [comment] 2019-08-20 06:28
https://www.spacetorrent.cloud/ currently returning cloudflare 525 SSL handshake failed

**Comment by garfield69** [comment] 2019-10-31 07:10
https://www.spacetorrent.cloud/ returning cloudflare 522 Connection timed out 
just me, or is the site broken, gone or moved to a new domain?

**Comment by pipopop** [comment] 2019-10-31 09:12
They have to find some € to pay for the server. They will come back in a few days.

**Comment by garfield69** [comment] 2019-11-04 05:09
spacetorrent back online, for now.

**Comment by garfield69** [comment] 2019-11-25 04:38
https://www.spacetorrent.cloud/ returning `Cloudflare 525 SSL handshake failed` and http is returning `Cloudflare 520 Web server is returning an unknown error`.

**Comment by garfield69** [comment] 2019-12-01 05:28
back online.

**Comment by garfield69** [comment] 2019-12-28 04:23
https://www.spacetorrent.cloud/ offline, returning cloudflare 522 Connection timed out

**Comment by garfield69** [comment] 2020-03-27 19:28
https://www.spacetorrent.cloud/ currently offline, returning cloudflare 522 Connection timed out

**Comment by garfield69** [comment] 2020-03-28 17:56
back online.

**Comment by garfield69** [comment] 2020-04-22 23:08
SpaceTorrent have turned on Cloudflare DDoS check and swithing to cookie method with user-agent does not work.

**Comment by garfield69** [comment] 2020-04-23 00:35
resolved with Jackett 0.16.105

**Comment by garfield69** [comment] 2020-08-31 07:43
https://www.spacetorrent.cloud/ returning Error 522 Connection timed out

**Comment by pipopop** [comment] 2020-08-31 08:25
I think it's an CloudWare error. They have some problem since Sunday

**Comment by ilike2burnthing** [comment] 2020-09-03 17:17
back up

**Closed by ilike2burnthing** 2020-09-03 17:17 UTC
Labels: Removed

**Comment by pipopop** [comment] 2020-11-30 17:26
SpaceTorrent is Dead.
Message form the Team:
"Hello,
Lately it's not a good life to be a tracker and this is confirmed with SpaceTorrent. SpaceTorrent is not and will not be anymore."

**Comment by garfield69** [comment] 2020-12-01 06:05
Jackett 0.16.2274
