### ISSUE TITLE
[torrentz2] Exception (torrentz2): Specified argument was out of the range of valid values.Parameter name: Unknown operator: : Specified argument was out of the range of valid values.Parameter name: Unknown operator:  (Test)

### ISSUE THREAD

**Issue by msalem23** [Jackett/Jackett#5514] opened 2019-06-20 07:47 UTC
When Testing the Torrentz2 tracker, I get " An error occured while testing this indexer
Exception (torrentz2): Specified argument was out of the range of valid values. Parameter name: Unknown operator: : Specified argument was out of the range of valid values. Parameter name: Unknown operator: 
Click here to open an issue on GitHub for this indexer.", even though the tracker is up and running, and I'm able to access it and search from it when navigating to torrentz2.eu from my web browser.

(At the bottom of your Jackett Dashboard page) **0.11.434.0
[log.txt](https://github.com/Jackett/Jackett/files/3309308/log.txt)
[updater.txt](https://github.com/Jackett/Jackett/files/3309309/updater.txt)

-------------------------------

**Comment by garfield69** [comment] 2019-06-20 08:23
this is a duplicate of #4982

**Comment by sn33ky** [comment] 2019-07-05 07:04
I have the same issue

**Comment by garfield69** [comment] 2019-07-05 07:07
duh!

**Comment by manderss99** [comment] 2019-07-05 13:19
same issue for me too

**Comment by Imparium** [comment] 2019-07-06 12:09
same issue

**Comment by HeyRobb** [comment] 2019-07-07 15:38
Same, thank you!

**Comment by garfield69** [comment] 2019-08-22 19:48
solved with Jackett 0.11.635

**Closed by garfield69** 2019-08-22 19:48 UTC
Labels: Duplicate
