### ISSUE TITLE
Manual Search Window (Webpage)

### ISSUE THREAD

**Issue by DaemonPhoenix42** [Jackett/Jackett#3838] opened 2018-09-20 06:15 UTC
#### Minor issue:
It's God Damn annoying clicking outside the foreground box to bring my browser back into focus, only to have to reinitialize my search again.

#### Visual Represenation:
![jackett tissue](https://user-images.githubusercontent.com/36192863/45799214-91df9a00-bc61-11e8-835f-5f4a6d76f280.jpg)
Anywhere outside the red box is volatile!

#### Solutions:
<b>Either retain last search info/query </b> or <b>Don't close it on me like that!</b>

#### Dial it down Jimmy:
Love the software, this is simply a minor gripe I've run into a couple times cause my own disjointed workflow. Thank you for your time <3

**Comment by garfield69** [comment] 2018-09-20 06:51
while the following in no way reduces your mouse mismanagement problem, you might find it useful to know that the **view cached releases** button near the top right of the main Jackett Dashboard contains the last 300 hits for each tracker used.
Which means you don't have to initiate a completely fresh search, just filter the history to include the tracker you were last using.

**Comment by DaemonPhoenix42** [comment] 2018-09-20 16:20
@garfield69 appreciate it, thanks

**Comment by flightlevel** [comment] 2018-09-24 09:31
Duplicate of https://github.com/Jackett/Jackett/issues/3453

**Closed by flightlevel** 2018-09-24 09:31 UTC
