### ISSUE TITLE
Search Results Returned on Season and Episode only (IPT)

### ISSUE THREAD

**Issue by ozoak** [Jackett/Jackett#1181] opened 2017-03-23 01:38 UTC
When a search (for IPT) is passed to Jackett from Sonarr the results appear to be for all shows, matching only on the Season and Episode numbers passed.

Appears to be a recent occurrence, however I couldn't pin down when it began. I updated to 0.7.116 to attempt to correct it, so the behaviour started before that. I would _guess_ at it being in the 0.7.11## range, and I'll start rolling back versions to see if I can work out where (if it's Jackett at all, that is - whilst Sonarr was updated prior to the Jackett upgrade (s) perhaps I didn't notice the aberrant behaviour.

I'm trying to work out what should be happening, based on what I can see in past issues on both (and even then I guess I can't rule out the tracker itself having changed), so I'm not certain in any way where the issue sits.

Log proved difficult to capture - Jackett is creating it and destroying it (clumsily in shell I was able to capture lines, but I think non-printing clear characters are being dropped on the log, so I found that a bit awkward). Rapid fire ls -la in the ~.config/Jackett folder shows the log.txt file goes from 0 bytes (emptied the log before starting) up to 174kb then balloons to about 347kb during the search before dumping back to 174kb post-search. So below is captured from my inelegant bash script to clear non-printing chars to a temp log file and grepping just the relevant log lines back (to avoid dumping the full returned web page logged).

`2017-03-23 12:11:23.4113 Info http://192.168.1.8:9117/torznab/iptorrents/api?t=tvsearch&cat=5010,5030,5040&extended=1&apikey=cac31aulf8si2x5ag4lttoejxpsuo53k&offset=300&limit=100&rid=40717&season=3&ep=20`

^ that's clearly what's being received by Jackett from Sonarr.
Try as I might, I couldn't catch the search URL being pulled, but the page content being returned shows that the next/last page URL's on the page are referencing ONLY S03E20, eg:
`<a href="?4;5;99;22;66;25;79;24;23;78;q=S03E20;p=2#torrents">`

So it _looks_ like it's only searching on the season/episode string. Initially it's passed the TVRage ID (rid=) but it is beyond me at that point, I'm left with only the questions "Can jackett take the rid? Can IPT take the rid? Should Sonarr be sending the show name instead?".

ed: seems to be similar to experienced with https://github.com/Jackett/Jackett/issues/1091 which was closed as resolved by an update in Sonarr (which I've ensured is up to date). 

Jackett version:  0.7.1176
Mono version (if not using Windows):  Stable 4.8.0.495

-------------------------------

**Comment by ozoak** [comment] 2017-03-23 03:23
I'm guessing this is Sonarr. I've gone back as far as 7.841, tried 7.902 and 7.1176 as well - same result. Will try rolling back Sonarr.

Spose this can be closed now. Will do so once I can confirm a Sonarr rollback corrects :)

**Comment by kaso17** [comment] 2017-03-23 04:33
looks like a dupe of #526 and #1132 (sonarr issue)

**Closed by kaso17** 2017-03-23 04:33 UTC

**Comment by ozoak** [comment] 2017-03-23 04:43
Yeah, correct. Missed the reference to opening up the API to see the capabilities being reported. And if I read it right, RID has never been supported. I already created a post on Sonarr forums, I'll keep following up there. Wish I'd caught some earlier logs in Sonarr to be able to demonstrate it not behaving the same. C'est la vie.

Cheers

**Comment by ozoak** [comment] 2017-03-23 04:55
FYI for anyone finding this - looks like something is a bit off with the restart process once a Sonarr update has been applied (guessing). Restarting Sonarr via the web UI didn't make a difference, however restarting Sonarr through shell (service nzbdrone restart) kicked it back to not using 'rid=' element for search requests.
