### ISSUE TITLE
YGGCookie: Downloading torrent file for movie 'xxx' failed since it no longer exists

### ISSUE THREAD

**Issue by alxdca** [Jackett/Jackett#10655] opened 2020-12-29 09:51 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**Jackett Version**: v0.17.159

**Are you using a proxy or VPN?** no

### Description

Using YGGCookie, I can search for content in Radarr and get the correct results. However, when triggering a download, it fails immediately with message "Downloading torrent file for movie 'xxx' failed since it no longer exists"

Tried with a new cookie as well as deleting the YGGCookie entry in jackett and creating it again -> Same result.

### Logged Error Messages

Downloading torrent file for movie 'xxx' failed since it no longer exists (https://xxx/dl/yggcookie/?jackett_apikey=xxx&path=xxx): HTTP request failed: [404:NotFound] [GET] at [https://xxx/dl/yggcookie/?jackett_apikey=xxx&path=xxx]

**Comment by ilike2burnthing** [comment] 2020-12-29 19:29
Are you able to download the torrent if you login to YGG in browser?

**Comment by alxdc9** [comment] 2020-12-29 19:55
Yes, using the web UI it works just fine.

**Comment by ilike2burnthing** [comment] 2020-12-29 22:21
Seems like I can't get yggtorrent/cookie to work either, not sure if it's a Jackett issue or FlareSolverr.

yggcookie is letting me search, but can't download because it isn't actually logged in (and all the results are duplicated, which I can't figure out either).

**Comment by alxdc9** [comment] 2020-12-31 13:38
Just had a look at the jackett logs and here is what I get:

``Error Error downloading. indexer: yggcookie path: https://www2.yggtorrent.si/engine/download_torrent?id=xxxxxx
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found 'V' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97``

**Comment by ilike2burnthing** [comment] 2020-12-31 13:51
Yea, rather than a .torrent file, Jackett is getting back `Vous devez vous connecter pour télécharger un torrent` (English - You must log in to download a torrent), the same as if you open the link in browser when you're not logged in, e.g. https://www2.yggtorrent.si/engine/download_torrent?id=705348

**Comment by saitoh183** [comment] 2020-12-31 17:50
Yeah getting same problem. I even redid the cookie config and still same result

 Jackett Version v0.17.166

**Comment by ngosang** [comment] 2021-01-08 17:24
YGG requires the user is logged in to download torrents. There is not a problem with FlareSolverr.
We have to change the definition to semi-private and the user has to fill user+password. Than should work.

**Comment by ilike2burnthing** [comment] 2021-01-08 19:20
I can search with both, but can only download when using yggtorrent, not yggcookie (same account, and tried a new cookie).

**Comment by saitoh183** [comment] 2021-01-08 22:06
> I can search with both, but can only download when using yggtorrent, not yggcookie (same account, and tried a new cookie).

Im experiencing the same. Also i use jackett on a headless  Ubuntu server in docker and i needed to do a tunnel and login on ygg via browser on Firefox to get the test to work.

**Comment by ilike2burnthing** [comment] 2021-01-23 05:09
The site has dropped Cloudflare DDoS protection for now and yggcookie is working again, downloads and all.

Issue not resolved, but some hopefully useful information to point towards Cloudflare being the cause.

**Comment by garfield69** [comment] 2021-11-03 05:00
v0.19.138

**Comment by ilike2burnthing** [comment] 2021-12-15 20:26
Not resolved by https://github.com/Jackett/Jackett/commit/b7247ec944345d8f33a3df1286342396bbad5631 for when Cloudflare DDoS Protection is enabled on the site.

**Comment by OpenPrunus** [comment] 2023-01-01 16:54
Hi. I've the same issue on this site when CF is enabled

**Comment by ilike2burnthing** [comment] 2023-01-01 17:00
Cloudflare issue, nothing to resolve on Jackett's end.
https://github.com/Jackett/Jackett/issues/13794
https://github.com/FlareSolverr/FlareSolverr/issues/596

**Closed by ilike2burnthing** 2023-01-01 17:00 UTC
Labels: PR Welcome!, Confirmed
