### ISSUE TITLE
[anidex] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by darkcloud784** [Jackett/Jackett#1879] opened 2017-09-21 22:12 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
------------------------------------------------------------------------------------------------
Anidex tracker doesn't seem to be working, test fails from jackett. Tracker is up, and be accessed by the machine jackett is using.

Error Output:
An error occured while testing this indexer
Found no results while trying to browse this tracker

Log output:

Sep 21, 2017 05:11:46 PM | Error | {0}

Jackett version:  
Jackett Version 0.8.216.0

Mono version (if not using Windows):  
Mono JIT compiler version 5.2.0.215 (tarball Mon Aug 14 15:46:12 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
-------------------------------

**Comment by garfield69** [comment] 2017-09-22 01:06
duplicate of #1817

**Comment by garfield69** [comment] 2017-09-23 18:42
this ticket can be closed, fixed by db9fb73

**Closed** 2017-10-03 12:53 UTC
