### ISSUE TITLE
[gktorrent] Exception (gktorrent): Specified argument was out of the range of valid values.Parameter name: Unknown operator: : Specified argument was out of the range of valid values.Parameter name: Unknown operator:  (Test)

### ISSUE THREAD

**Issue by barto95100** [Jackett/Jackett#5323] opened 2019-05-24 14:17 UTC
Hello All,

I have the jackett Version 0.11.364.0 and the site torrent9 or GKtorrent with cloudflare don't work

Do you have a Idea how to resolve the pb ?

**Comment by garfield69** [comment] 2019-05-24 20:19
duplicate of #5054. see #4982 for updates on progress

**Closed by garfield69** 2019-05-24 20:19 UTC
Labels: Duplicate
