### ISSUE TITLE
(LimeTorrents) An error occured while testing this indexer

### ISSUE THREAD

**Issue by newgithubuser2019** [Jackett/Jackett#5864] opened 2019-08-17 05:50 UTC
Exception (limetorrents): certificate validation failed: [Subject] O=Internet Widgits Pty Ltd, S=Some-State, C=AU [Issuer] O=Internet Widgits Pty Ltd, S=Some-State, C=AU [Serial Number] 00F5BA2E609C91DBB4 [Not Before] 10/13/2014 4:46:03 PM [Not After] 11/12/2014 3:46:03 PM [Thumbprint] 5D8A25EB8B9C46981F007D105007113B97CA9BE6 : An error occurred while sending the request.
___________________________________________________________________________________________________
 Jackett Version 0.11.608.0 
[log.txt](https://github.com/Jackett/Jackett/files/3511675/log.txt)

**Comment by garfield69** [comment] 2019-08-17 06:04
duplicate of #5863

**Closed by garfield69** 2019-08-17 06:04 UTC
