### ISSUE TITLE
ARM32 build crashes with segmentation fault since v0.20.10

### ISSUE THREAD

**Issue by tamas-boczan** [Jackett/Jackett#12648] opened 2021-12-06 21:20 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /volume1/@appstore/jackett/var/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreLinuxArm32
OS version: Unix 3.2.40.0
Environment version: 5.0.12 (/volume1/@appstore/jackett/share/)
Starting Jackett v0.19.275
```

### Description

I'm running Jackett on a Synology NAS with ARMv7 (no docker support), using the native CoreLinuxArm32 builds. The approach on this platform is to install the very outdated Jackett version from SynoCommunity (v0.17.668), then let the built-in updater of Jackett regularly update to the latest version.

This doesn't work anymore, because since v0.20.10 both the updater and the jacket binary crash with segmentation fault. Manual install doesn't work either.

More details below.

The currently installed version (v0.19.275 or older) can successfully download the latest version, and launches the updater in it, as seen in jacket.log:
```
12-06 21:53:01 Info Checking for updates... Jackett variant: CoreLinuxArm32
12-06 21:53:04 Info New release found. Current version: v0.19.275 New version: v0.20.95
12-06 21:53:04 Info Downloading release v0.20.95 It could take a while...
12-06 21:53:31 Info Starting updater: /tmp/JackettUpdate-v0.20.95-637744243884594789/Jackett/JackettUpdater --Path "/volume1/@appstore/jackett/share" --Type "Console" --Args " --PIDFile /volume1/@appstore/jackett/var/jackett.pid" --KillPids "29336"
12-06 21:53:31 Info Updater started process id: 3455
12-06 21:53:31 Info Exiting Jackett..
Deleting PID file /volume1/@appstore/jackett/var/jackett.pid
Application is shutting down...
```
It calls the JackettUpdate binary found in the downloaded archive. However the updater does not produce a log file, and does not restart the jackett process. When I manually restart the process, the old version loads, and then deletes the archive of the failed update.
```
12-06 21:58:06 Info Starting Jackett v0.19.275
[...]
12-06 21:58:43 Info Deleting JackettUpdate temp files from /tmp/JackettUpdate-v0.20.95-637744243884594789
12-06 21:58:44 Error An error occurred during the last update. If this error occurs again, you need to reinstall Jackett following the documentation. If the problem continues after reinstalling, report the issue and attach the Jackett and Updater logs.
```

When running the JacketUpdater binary manually instead of from the Web UI, the reason becomes clearer: JacketUpdater crashes with a segmentation fault before getting a chance to create a log file.
I also tried doing manually what JacketUpdater does automatically: copying over the files to the directory defined by the "Path" variable, removing the files from the hardcoded list, then starting the new jackett binary. The new jackett binary also crashes instantly with a segmentation fault.

By calling JacketUpdater manually, I could narrow it down to which update is causing the issue. Jackett [v0.19.275](https://github.com/Jackett/Jackett/releases/tag/v0.19.275) is the last version that installs successfully, and the next version [v0.20.10](https://github.com/Jackett/Jackett/releases/tag/v0.20.10) is the first version that crashes. Between the two there was a .NET version bump to .NET 6 in 03c9e3036c03078e457b03ec16a73fd3155f9256 , which I suspect caused the issue. 

### Logged Error Messages

```
12-06 21:58:43 Info Deleting JackettUpdate temp files from /tmp/JackettUpdate-v0.20.95-637744243884594789
12-06 21:58:44 Error An error occurred during the last update. If this error occurs again, you need to reinstall Jackett following the documentation. If the problem continues after reinstalling, report the issue and attach the Jackett and Updater logs.
```

**Comment by ilike2burnthing** [comment] 2021-12-06 23:57
@ngosang can you take a look at this next time you're free?

**Comment by ngosang** [comment] 2021-12-07 21:00
I have a RaspberryPi with ARM32 chipset and I can not reproduce the issue. Furthermore, ARM32 downloads remain unchanged in the last 3 months.
![image](https://user-images.githubusercontent.com/10577978/145104574-f44703a1-2fc8-4693-8283-1dc37728491d.png)
I'm not saying the problem does not exists but it looks like it only affects really old hardware.
The jump to .Net6 bring support for new Apple processors and some performance improvements. We are not going back.
1. You can try to install the latest release from scratch (deleting old Jackett folder and old configuration in `.config/Jackett`)
2. If that does not work, you can install the last working version for you and disable updates. You can update the definitions manually overwriting the `Definitions` folder from time to time.

**Comment by vanThijs** [comment] 2021-12-08 18:50
I am facing exactly the same issues on a Synology NAS with an ARMv7 processor. I will look into the Mono release, but last time i tried it, this release was not compatible with this older platform.

**Comment by ilazgo** [comment] 2021-12-21 14:48
I am facing the same problem with a Synology DS215j with DSM 6.2.

**Comment by ilazgo** [comment] 2021-12-21 16:35
Maybe @tamas-boczan can write here the steps to manually update to the v0.19.275.

**Comment by tamas-boczan** [comment] 2021-12-22 11:41
@ilazgo:
Below is a script that updates jackett to v0.19.275.

1. If necessary, modify the install directory variable at the start of the script to match your configuration.
2. Place the script file into a folder that the jacket user can access, such as /tmp
3. Make the script executable: `chmod +x <script path>`
4. Execute it with the jackett user and group `sudo -g jackett -u sc-jackett <script path>`
5. Disable auto update on the Jackett UI

```
#!/bin/sh

INSTALLDIR=/volume1/@appstore/jackett
JACKETTUSER="sc-jackett"
JACKETTGROUP="jackett"

URL=https://github.com/Jackett/Jackett/releases/download/v0.19.275/Jackett.Binaries.LinuxARM32.tar.gz
HASH="0bd1ef03f9b88de4e285efb3863ee3f67031285b84af0a4e264a89a6b4250291"

# Check if we're using the expected user and group
if [[ $(id -gn) != *"$JACKETTGROUP"* ]]; then
    echo "Unexpected group. Run this script with the jackett user and group: sudo -g $JACKETTGROUP -u $JACKETTUSER <script path>" >&2
    return 1
fi

if [ $(id -un) != "$JACKETTUSER" ]; then
    echo "Unexpected user. Run this script with the jackett user and group: sudo -g $JACKETTGROUP -u $JACKETTUSER <script path>" >&2
    return 1
fi

# Download update
updatedir=$(mktemp -d)
wget $URL -O $updatedir/update.tar.gz
# Verify update
if ! echo "$HASH $updatedir/update.tar.gz" | sha256sum -c -; then
    echo "The downloaded file does not have the expected contents" >&2
    return 1
fi
# Extract update
tar -xf $updatedir/update.tar.gz -C $updatedir

# Call installer with same parameters as the auto updater plus NoRestart so we can clean up after it finishes
# Should be executed with the sc-jackett user and jackett group
env HOME=$INSTALLDIR/var PATH=$INSTALLDIR/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin LD_LIBRARY_PATH=$INSTALLDIR/lib $updatedir/Jackett/JackettUpdater --Path "$INSTALLDIR/share" --Type "Console" --Args " --PIDFile $INSTALLDIR/var/jackett.pid --NoRestart"

# Clean up
rm -rf $updatedir

```

**Comment by tamas-boczan** [comment] 2021-12-22 12:21
@ngosang:
Installing the latest release from scratch does not work. Manually updating the definitions should work.

I haven't looked into the Mono release.

The ARM32 download count is interesting. The issue does not cause the download to fail, the update process crashes _after_ the download. However the failed update does stop the jackett process too, so that should affect the download count somehow, depending on how the system is handling the crashed process. If the system doesn't restart the jackett service automatically, then there should be fewer downloads because until manual restart jackett can't run again, but if the system restarts the service immediately after it crashes then there should be more downloads because it would keep crashing and restarting.

Based on some other github issues .NET 6 does not (fully?) support 32-bit ARMv7, so that seems to be the root cause. See:
- https://github.com/dotnet/runtime/issues/56706
- https://github.com/SynoCommunity/spksrc/pull/4976

**Comment by mreid-tt** [comment] 2023-02-10 13:38
> Based on some other github issues .NET 6 does not (fully?) support 32-bit ARMv7, so that seems to be the root cause

@tamas-boczan, I've also been looking into this and you are correct that dotNET 6 does not fully support 32-bit ARMv7 CPUs. Based on some testing (https://github.com/SynoCommunity/spksrc/issues/5574), it seems that dotNET 6 is not supported on `armada370` CPUs or any ARMv7 arch running on DSM6 (due to an older `glibc` in the OS).

I've been testing a new Jackett build under this [PR](https://github.com/SynoCommunity/spksrc/pull/5597) which would correctly build the dotNET or mono version to match the compatible CPU and OS. You can perhaps test the package for your CPU from the included [Artifacts](https://github.com/SynoCommunity/spksrc/actions/runs/4144000902).

**Comment by mreid-tt** [comment] 2023-02-10 13:45
> I am facing the same problem with a Synology DS215j with DSM 6.2 and Mono 5.20.1.34.

@ilazgo, can you elaborate on the problem you are facing? Is this from the SynoCommunity package? If so, perhaps you can test the package I'm working on (see https://github.com/Jackett/Jackett/issues/12648#issuecomment-1425824789 above).

**Comment by mreid-tt** [comment] 2023-03-15 01:46
Hey folks, I'm pleased to say that an updated build of Jackett v0.20.3521 has been [published](https://synocommunity.com/package/jackett) and is downloadable from the Package Center or via direct download. Looking forward to your feedback on whether we can close this issue.

**Comment by ilike2burnthing** [comment] 2023-03-15 02:51
@tamas-boczan / @ilazgo / @vanThijs is this updated build working for you?

**Closed** 2023-03-22 18:42 UTC
Labels: More information needed, OS Linux / Mono / *nix
