### ISSUE TITLE
Yggtorrent indexer doesn't works with Radarr

### ISSUE THREAD

**Issue by fluxtendu** [Jackett/Jackett#2158] opened 2017-11-17 12:33 UTC
Hello,

As the title says, YGGtorrent indexer doesn't works with Radarr. Could someone fix this?

[The same issue on Radarr repository](https://github.com/Radarr/Radarr/issues/2269) report the following:

- All other jackett (0.8.402.0) indexers tested works with Radarr (0.2.0.870) and YGGtorrent indexer works with sonarr (2.0.0.5054)

- Log when we try to add the indexer with search enabled:
```
17-11-16 14:51:17.8|Warn|Torznab|Unable to connect to indexer

[v0.2.0.870] System.InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable1[T] source) [0x00010] in <26aedeede9534b948c539f8734c8492d>:0 at NzbDrone.Core.Indexers.HttpIndexerBase1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:325

17-11-16 14:51:17.8|Warn|NzbDroneErrorPipeline|Invalid request Validation failed:
-- Unable to connect to indexer, check the log for more details
17-11-16 14:51:17.8|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (164 ms)
```

- galli-leo (owner of Radarr repo):
> This is the case when the indexer does not support searching by imdbid. Either tell the maintainer of the Indexer to fix it or Disable Searching, Add the indexer, then enable searching.

- If we try the disable/enable workaround, we get this error when searching:
```
HTTP Error - Res: [GET] https://(removed)/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=amityville%20horror%20lost%20tapes%202017: 400.BadRequest
yggtorrent does not support the requested query.
```

Thanks

**Comment by kaso17** [comment] 2017-11-17 13:16
caused by missing/incorrect Movies category mapping.
fixed via dda27ef45f00356d632cc578f23b288cec817bd6

Can be also fixed by adding 102183 to the categories list (radarr advanced options) e.g. http://127.0.0.1:9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060,102183&extended=1&apikey=(removed)&offset=0&limit=100&q=amityville%20horror%20lost%20tapes%202017

**Closed by kaso17** 2017-11-17 13:16 UTC

**Comment by fluxtendu** [comment] 2017-11-18 08:27
I have added the category 102183 and effectively Radarr doesn't throw error anymore but I still don't get search result...
I have try all options I found that could help: 
"Try to normalize releases names by moving year after the title" and "category: all" in jackett
"Parser Leniency", "Remove year from search string" and "Search by Title" in Radarr
(Multiple release of the movie are findable on the tracker and on the Jackett interface)
So, I don't think it's fixed...

**Comment by kaso17** [comment] 2017-11-20 16:05
searching for `amityville horror lost tapes 2017` directly on YGG doesn't return any results.
Please provide the exact search string examples you're using.

**Comment by fluxtendu** [comment] 2017-11-20 17:27
I have made my tests with "fantastic beasts and where to find them 2016"

**Comment by kaso17** [comment] 2017-11-22 11:15
http://127.0.0.1:9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060,102183&extended=1&apikey=(removed)&offset=0&limit=100&q=fantastic%20beasts%20and%20where%20to%20find%20them%202016
returns several results for me, can't reproduce your issue

**Comment by fluxtendu** [comment] 2017-11-22 12:09
The issue is specificaly related to Radarr, yggtorrent indexer works perfectly with jackett and sonarr interfaces. 

An issue was already open on the Radarr repository, but the owner (galli-leo) closed it with this comment:
> This is the case when the indexer does not support searching by imdbid. Either tell the maintainer of the Indexer to fix it or Disable Searching, Add the indexer, then enable searching.

And neither the disabling/enabling search trick nor the 102183 category allow to get search results within Radarr.

I don't know if it's simpler to fix it with the indexer or Radarr code, but the issue is not resolved and all other jackett (0.8.402.0) indexers tested works within Radarr (0.2.0.870).

**Comment by kaso17** [comment] 2017-11-22 13:44
please update to jackett v0.8.450 and provide the torznab URL from your "fantastic beasts and where to find them 2016" example from the sonarr logs then.

**Comment by fluxtendu** [comment] 2017-11-23 08:14
I should have try with another movie, it works with most of the others...

I have updated Jackett and the torznab URL generated by Radarr are:
```
17-11-23 08:51:36.6|Debug|Torznab|Downloading Feed http://(removed):9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060,102183&extended=1&apikey=(removed)&offset=0&limit=100&q=fantastic%20beasts%20where%20to%20find%20them%201%202016
17-11-23 08:51:37.9|Debug|Torznab|Downloading Feed http://(removed):9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060,102183&extended=1&apikey=(removed)&offset=0&limit=100&q=fantastic%20beasts%20where%20to%20find%20them%202016
```
I think the issue is caused by Radarr removing the word "and" from the url

**Comment by lilp69** [comment] 2017-11-29 14:09
So YGG works with jackett? now?

**Comment by kaso17** [comment] 2017-11-29 18:06
@fluxtendu 
http://127.0.0.1:9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060,102183&extended=1&apikey=(removed)&offset=0&limit=100&q=fantastic%20beasts%20where%20to%20find%20them%202016 works fine for me, getting plenty of results.

please check the following radarr logs why the releases don't show up.

**Comment by lilp69** [comment] 2017-11-30 07:17
My mistake, I forget to say YGG with Jackett on Radarr.

**Comment by fluxtendu** [comment] 2017-11-30 07:43
@kaso17 I can't reproduce the problem anymore.
Still with Radarr 0.2.0.870 & Jackett v0.8.450, so I hope something has changed with the ygg website api or I will need to worry for my sanity...

**Comment by kaso17** [comment] 2017-11-30 08:00
@lilp69 apparently it does

**Comment by lilp69** [comment] 2017-11-30 08:22
I've : Unable to connect to indexer, check the log for more details
I test with Torznab custom I use, API key from Jackett and Torznab feed for the URL.
