### ISSUE TITLE
Feature Request - Search trackers by user defined group or tag

### ISSUE THREAD

**Issue by Goob00000** [Jackett/Jackett#7172] opened 2020-02-09 20:13 UTC
### Description

Please add the ability to establish groups of trackers for searching. This would be extremely useful as some trackers are highly responsive whereas others are not. 

This would be useful for "automated" vs manual/interactive searches for content.

**Comment by cadatoiva** [comment] 2020-02-09 20:37
Duplicate of #2185

**Closed by cadatoiva** 2020-02-09 20:37 UTC
