### ISSUE TITLE
torrentdownloads: returns 0 results with empty search

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13593] opened 2022-09-24 18:58 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett: v0.20.1951
Arch Linux
Docker: Yes
```

### Description

torrentdownloads: returns 0 results with empty search
with "text search" it's working

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment] 2022-09-24 19:00
closing as a duplicate of #13291
see https://github.com/Jackett/Jackett/issues/13291#issuecomment-1256721576

**Closed by garfield69** 2022-09-24 19:00 UTC
