### ISSUE TITLE
Error class=" FB_FW_ext eidReader" Error message

### ISSUE THREAD

**Issue by kenosama** [Jackett/Jackett#2959] opened 2018-04-11 22:22 UTC
**Jackett version**: 08.815  
**Mono version** (if not using Windows):  Installed on QNAP Qmono V5.10.0.160
-------------------------------

Hello i just installed Jackett on my Qnap nas with Qmono, when i start the software and try to access it it shows me this.

`This XML file does not appear to have any style information associated with it. The document tree is shown below.`
`<Error class=" FB_FW_ext eidReader">`
`<Message>An error has occurred.</Message>`
`</Error>`

i tried to unistall re-install it worked once but when i restarted i got this error everytime (even after trying re-install). 

what can i do to give you more info to try to fix the situation? 

Thanks in advance for your patience and advices :) 

keno

**Comment by kaso17** [comment] 2018-04-12 10:51
There is an unresolved issue affecting the qnap mono 5.10 version.
Duplicate of #2704

**Closed** 2018-08-30 06:06 UTC
Labels: Duplicate
