### ISSUE TITLE
[Downloadville] Bad Size of files searched

### ISSUE THREAD

**Issue by Thornin** [Jackett/Jackett#7123] opened 2020-02-06 20:27 UTC
### Environment

**OS**: Ubuntu 19.10 server

**.Net Runtime**: [Mono]

**.Net Version**: 6.6.0.161

**Jackett Version**:0.12.1701.0

**Last Working Jackett Version**: i dont know

### Description

Hello,

(sorry for my english i do my best)
there is a bug when you search for an episode, the size for downlodville isn't good, you can see in the attached image for the same files on two tracker the size for downlodville is bad.

This is for all type of files i search

### Logged Error Messages

There is no error in the logs

### Screenshots

![BugSize](https://user-images.githubusercontent.com/44228843/73975285-4dbc6a80-4926-11ea-92c5-a371207f5aaa.png)

**Comment by cadatoiva** [comment] 2020-02-06 21:01
Duplicate of #7121. Fixed in an update from earlier today.

**Closed by cadatoiva** 2020-02-06 21:01 UTC
