### ISSUE TITLE
[Ygg Indexer Issue] (Saison) parsing in api calls is not working. 

### ISSUE THREAD

**Issue by ruCyberPoison** [Jackett/Jackett#6207] opened 2019-10-18 21:14 UTC
Hello Dev's i have an issue with the torznab api from yggtorrent the semi-private torrent, i found 
many series with the name 'Saison' and the api upstream doesn't appear on the sonarr v3/v2, so this is why i opening this ticket because sonarr have received a commit with the 'saison' parser on the name of season, but now the api call are replacing the saison to a 's' 

[https://github.com/Sonarr/Sonarr/commit/ceaaec5378aa6a0eae4fa614abaab69deb7175bb](https://github.com/Sonarr/Sonarr/commit/ceaaec5378aa6a0eae4fa614abaab69deb7175bb)

```
 - name: re_replace
            args: ["([Ss]aison|[Ss]aison )(\\d{1,4})", "S$2"]
          - name: re_replace
            args: ["S(\\d+)E(\\d+)(\\D+)", "S$1E$2 $3"]
          - name: re_replace
            args: ["([Mm][Uu][Ll][Tt][Ii])", "MULTi"]
          # End tidy up for sonarrv3 season search
```
but if you takes a better look in ygg to easily way you find Seasons packs with the name seasons 

![image](https://user-images.githubusercontent.com/26681688/67128632-8fe96100-f1fc-11e9-81d7-01b127b04d98.png)
[https://www2.yggtorrent.pe/engine/search?name=the+good+wife&do=search](https://www2.yggtorrent.pe/engine/search?name=the+good+wife&do=search)

but the jackett api call is returning only 
![image](https://user-images.githubusercontent.com/26681688/67128660-a2fc3100-f1fc-11e9-801b-bf9474274636.png)

can you do a edit please and update your docker image after that

**Comment by ruCyberPoison** [comment] 2019-10-19 09:00
i have tried without 
```
- name: re_replace
            args: ["([Ss]aison|[Ss]aison )(\\d{1,4})", "S$2"]
          - name: re_replace
            args: ["S(\\d+)E(\\d+)(\\D+)", "S$1E$2 $3"]
          - name: re_replace
            args: ["([Mm][Uu][Ll][Tt][Ii])", "MULTi"]
          # End tidy up for sonarrv3 season 
```
this doesn't work for me. this need a fix

**Comment by ngosang** [comment] 2020-01-11 10:06
@garfield69 ping

**Comment by garfield69** [comment] 2020-01-11 21:13
@xfouloux you've been maintaining this indexer recently, care to look at this ticket?

**Comment by xfouloux** [comment] 2020-01-13 03:58
I will look into it, but last time i scratched my head with this
Problem is YGG tracker and their search engine that is bad.

Sonarr will search like this for a season :
"The Good Wife S1" and that will not match or return any result in YGG search

If you search for "The Good Wife" from jackett, it will return the results.

The problem is that we need to transform the Sonarr queryWord into something that would match in YGG, but if we convert the "S1" to "Saison 1" then it will not work for other results that are Scene named correctly.

I might try to add a second query search then but i don't know know to transform the QueryWord into a variable that can be then used into a second search

I think that we need C# for this....

**Comment by garfield69** [comment] 2020-01-13 04:37
veto the second query search, do not want to go down that path.
I'll take a look at the current yggtorrent (shudder, I detest this shitty web site) and see if I can improve the pre-and post processing of the titles 

so to recap we need to handle
```
Good Wife S06
Good Wife saison 6
Good Wife season 6
Good Wife S06E01
```
is that every combo?

**Comment by xfouloux** [comment] 2020-01-13 04:44
Well Sonarr will send for 
- Season Search : "The Good Wife Sx"
- Episode Search : "The Good Wife SxEy"

Not sure about the "The", 

But what we want to search in YGG is :
- Season Search : "Good Wife Sx" or "Good Wife saison x" or "Good Wife season x" or "Good Wife S0x" or "Good Wife saison 0x" or "Good Wife season 0x"
- Episode Search : "The Good Wife SxEy" or "Good Wife saison xx episode y"

i think ygg does not return result for something that is like that "Good Wife S06" if you don't put the 0 and search like "Good Wife S6" ==> need to try and see

that should match pretty much everything

**Comment by RoloSoze** [comment] 2020-04-11 16:40
@xfouloux @garfield69 Verdict on this issue?

**Comment by garfield69** [comment] 2020-04-12 00:07
i'ts on my queue, but at the bottom, because I hate this site. I will take a look at it eventually once I clear my queue, which by the way, is currently 62 emails deep and counting.

**Comment by xfouloux** [comment] 2020-04-12 06:26
The best thing would be to make it in C# and use the url to make it look for a season in particular using the select box ids but that will be a pain in the ass too

**Comment by xfouloux** [comment] 2020-07-07 04:47
can we have like a pre-release with this for people to try out ?

**Comment by xfouloux** [comment] 2020-07-07 07:11
What it does now, is :

When Sonarr send : The Good Wife S1
It search for "The Good Wife S01" & "The Good Wife Saison.1" & "The Good Wife Saison.01"

It then displays result by tidying everything in the format sonarr wants which is "The Good Wife S01" even if the result what was found was "The Good Wife Saison.01" or  "The Good Wife Saison 01"

It should solve most of the issues.

I still encounter some issue with stuff like "Dawson's Creek" for example, sonarr search for "Dawsons Creek S1" but then title of the torrent in YGG is : "DAWSON SAISON 1 1998 DVDRIP MULTI + ST H264 AAC DAWSON'S CREEK" so because the search engine is strict it doesn't find it

So it may happen for other TV shows

Fix for this is to use the beta search engine, it's returning way too much results to be let on by default, or have a path search with the beta engine to complete the other search. So just activate the beta search in jackett at your own risk, or only sometimes manually when searching.

**Closed** 2020-07-08 05:00 UTC

**Comment by garfield69** [comment] 2020-07-08 07:01
Jackett 0.16.814
