### ISSUE TITLE
Italian indexer MIRCrew have a problem

### ISSUE THREAD

**Issue by mtguido87** [Jackett/Jackett#15034] opened 2024-02-02 17:58 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using Prowlarr version: 1.13.0.4217
```

### Description

Good evening,
I expose here this problem with Prowlarr and one of the best known Italian indexer: MIRCrew.

This indexer is already on prowlarr and it would seem to work but actually in 80% of the cases if you try to download one of its results an error comes up and the download does not start.

Together with a friend we have studied the yml and we may have figured out what the problem depends on.

Basically we noticed that the prowlarr system proceeds first by clicking thank you on the page, then opens the discussion quote.

[![image.png](https://i.postimg.cc/Pr4KC1CJ/image.png)](https://postimg.cc/tYsFfZtG)
[![image-1.png](https://i.postimg.cc/qqHQ3Lch/image-1.png)](https://postimg.cc/LYvzdjb2)

At that point it pulls out the magnet. The problem is that we noticed that in some releases the magnet goes after the [magnet] code.

[![image-2.png](https://i.postimg.cc/057VqTxp/image-2.png)](https://postimg.cc/238QQX16)
[![image-3.png](https://i.postimg.cc/fTZBW8T1/image-3.png)](https://postimg.cc/z3tn0Shk)

Where there is the "carriage return" prowlarr goes wrong, because it uses precisely the ASCII character of the carriage return. Where there is not all right, it launches the link and the download starts.

Would there be any way to fix this problem on the prowlarr side by preventing it from going into error when it finds links that wrap?

I then report another known problem with this indexer. Namely the fact that by default in the yml is set 512mb as the size of all results. Is there any way to solve this problem?

It would be most useful for us Italians to solve this problem as MIRCrew is one of the best trackers on our territory.

Thanks to those who will intervene

### Logged Error Messages

```text
Getting release from the indexer failed
```

**Comment by garfield69** [comment] 2024-02-02 18:54
I don't know exactly how prowlarr does things, but I do know that it imports the mircrew indexer code that we wrote for Jackett, and for Jackett the flow is:
- perform a search on the mircrew we site, example `https://mircrew-releases.org/search.php?keywords=%2Ble+%2Bali+%2Bdella+%2Bliberta&terms=all&sc=0&sf=titleonly&sr=topics&sk=t&sd=d&st=0&ch=300&t=0&submit=Cerca&fid[]=25&fid[]=26&fid[]=51&fid[]=52&fid[]=29&fid[]=30&fid[]=31&fid[]=33&fid[]=34&fid[]=35&fid[]=36&fid[]=37&fid[]=39&fid[]=40&fid[]=41&fid[]=42&fid[]=43&fid[]=45&fid[]=46&fid[]=47`
-  and process the results page HTML by listing the names of the posts and providing default values for the seed, leech and size.
- when a user clicks on the download link, then perform the thank you, but doing a http GET, example: `https://mircrew-releases.org/viewtopic.php?f=26&p=309816&thanks=309816&to_id=197&from_id=3950`
- then when the post page is refreshed, fetch the new page with another http GET, example: `https://mircrew-releases.org/viewtopic.php?f=26&p=309816`
- The we process this page with the HTML handler, looking for the first magnet link
```YAML
  selectors:
    - selector: a[href^="magnet:?xt="]
      attribute: href
```

Note that this is not an **edit** of the post page, its a browser HTML view, so there is no ASCII carriage return to process
So your theory does not apply to Jackett, and I expect it does not apply to Prowlarr either, but I would want one of the Prowlarr team to confirm this.
So what ever issue is routinely preventing your prowlarr indexer to return the magnet, it is something other problem
.
I note that the mircrew website is recently always under performance pressure, for example I often see a `you cannot perform a search at this time, the load is to high` messages that cause the search to return no results.
Its possible that the same applies to fetching the details page after the thank you is done, and its simply this that prevents the magnet link from being found. (This is my theory only, not based on any actual research / testing).

As for the size, when the indexer performs a search, mircrew returns a list of post links in the search results page, but with no other details other than the name. So the indexer has hardcoded the size, seed and leech values, 510MB, 1 seed, 1 leech.
And while the seed and leech numbers are present on the post page once you have clicked thank you, I cannot find the size in the post page.
But even if the size and updated seed and leech values were present in the post page, the indexer is not going to go fetch every post from the results page in order to provide those values, that is not practical.

**Comment by mtguido87** [comment] 2024-02-02 19:04
> * https://mircrew-releases.org/viewtopic.php?f=26&p=309816

I thank you for your interest and response.
The thing is that we noticed that this thing happens exactly with some types of results and we noticed that those results have the magnet going to the head. 
That's why we convinced ourselves of this thing. 

On the other hand, regarding the size, how come it is not possible to extract the size from the page?

**Comment by garfield69** [comment] 2024-02-02 19:27
so what is really happening is that the issue is that once a user has performed a thank you, then the post page does not have the thank you link anymore.
so if you perform a search the second time, and click on the indexer download link, the indexer performs a thank you with `https://mircrew-releases.org/viewtopic.php?f=26&p=309816&thanks=309816&to_id=197&from_id=3950` but does not get the refreshed post page with a magnet, instead it gets an error message `Invalid thank`

this is the cause of the error.

the only way forward would be to recode the indexer in C# so that code can be added to check for the presence of the thank you link and only use it if found. 
if the thank you link is not found look for the magnet.
if the thank you is found, do the thank you, then find the magnet.

>regarding the size, how come it is not possible to extract the size from the page

because it is not there ;-) I don't see a size on the first post of `https://mircrew-releases.org/viewtopic.php?f=26&p=309816` do you?

**Comment by garfield69** [comment] 2024-02-02 19:34
>regarding the size, how come it is not possible to extract the size from the page

found the size on the post, sorry, missed it the first dozen times :-D

so we don't fetch the size from the post page, because its not practical. 
the indexer does a GET to perform the search, which may return up to 100 results.
then the indexer would have to do another 100 GET, one for each post, and read the size.

no website is going to want anyone to perform 101 GET requests every time some one does a search, the traffic would push a web site into overload. IT may even block your IP as a DDoS generator.

**Comment by ilike2burnthing** [comment] 2024-02-02 23:44
MIRCrew was changed from looking specifically for the thanks button a while ago - https://github.com/Jackett/Jackett/commit/259d98c140854122045a6dba2aa23c814510286e. This is why on already thanked torrents it's selecting the quote button. This is working fine in both Jackett and Prowlarr for me. ilDraGoNeRo2 is also working using the same method (I've just updated the selector).

@garfield69 are you getting an error in Jackett?

**Comment by garfield69** [comment] 2024-02-02 23:50
@ilike2burnthing  I believe the first time you search for a post that you have not already tried to download before, then the indexer works fine.
But if you search for it again and try to download it a second time then that is when you get the error.

**Comment by ilike2burnthing** [comment] 2024-02-02 23:51
Yea, for me first, second, and all subsequent download attempts work fine.

**Comment by garfield69** [comment] 2024-02-02 23:52
Same here for me on Jackett. Is it something peculiar to prowlarr then, have you tried it there?

**Comment by ilike2burnthing** [comment] 2024-02-02 23:54
Working on Prowlarr too. I think your original theory about it just coinciding with the site being up and down might be the likely culprit.

**Comment by garfield69** [comment] 2024-02-03 00:04
try searching for `le ali della libert` and see if you can download that once or twice

**Comment by ilike2burnthing** [comment] 2024-02-03 00:18
Oh waoh, yea I can't even download it the first time. Looks like a formatting issue on their part. Change `a[href^="magnet:?xt="]` to `a[href*="magnet:?xt="]`?

**Comment by garfield69** [comment] 2024-02-03 00:32
that partly helps, in that the logs show the selector was picked up, but then it error out with a bencode.
I'm having a bad day diagnosing stuff, I'm going to take a break ;-b

**Comment by ilike2burnthing** [comment] 2024-02-03 00:33
Yea, seeing that as well. Playing around with things and will come back in a bit.

**Comment by mtguido87** [comment] 2024-02-03 00:53
As I have written since the first post, the problem occurs with releases where the thank you button is not present.
In that case the system quotes the message (I don't know why it does that) and then takes the magnet. 
The problem occurs in these cases when the magnet goes to the head. I also put some explanatory pictures in the first post.

If you want to look for such a release that does not work look for this one: The Green Mile 2160p Licdom and you will see that the download fails.

https://i.postimg.cc/G3zfSnm2/image.png

Do you have any idea how to fix it?

**Comment by garfield69** [comment] 2024-02-03 01:00
>Do you have any idea how to fix it?

I think we are finally understanding the scope of the problem, (BTW thank you for persevering and remaining calm throughout my ramblings), and now that we can reproduce the problem for ourselves we will try to work out a solve, if possible, within the yaml construct.
But it may be that the solution may be with a re-write of the indexer to C#.

**Comment by ilike2burnthing** [comment] 2024-02-03 01:01
Might be as simple as this:

```yml
  selectors:
    - selector: a[href*="magnet:?xt="]
      attribute: href
      filters:
        - name: re_replace
          args: ["\n", ""]
```

Currently just trying to work out if `htmldecode` is also needed.

**Comment by mtguido87** [comment] 2024-02-03 01:02
This is the thread reguarding the image of "The green mile" that not work, as you can see the magnet go to the head:

https://i.postimg.cc/PJYfMf1S/image.png

**Comment by mtguido87** [comment] 2024-02-03 01:05
> Potrebbe essere semplice come questo:
> 
> ```yaml
>   selectors:
>     - selector: a[href*="magnet:?xt="]
>       attribute: href
>       filters:
>         - name: re_replace
>           args: ["\n", ""]
> ```
> 
> Al momento sto solo cercando di capire se `htmldecode`è necessario.

Thank you so much to investigate and try to fix the problem.
If you want also to solve the problem of the fixed "512mb" i will offer you a sweetie cappuccino!!

**Comment by ilike2burnthing** [comment] 2024-02-03 01:05
https://github.com/Jackett/Jackett/issues/15034#issuecomment-1924556482

**Comment by garfield69** [comment] 2024-02-03 01:08
\o/

**Comment by garfield69** [comment] 2024-02-03 01:12
So ilike2burnthing has found a solve for the magnet issue, and it will be available in the Jackett app with the next release due out in about 5 hours or so.
When the Prowlarr team import the updated indexer from our source (anytime they please from now) then this should be available on that app too.

**Comment by mtguido87** [comment] 2024-02-03 01:25
> So ilike2burnthing has found a solve for the magnet issue, and it will be available in the Jackett app with the next release due out in about 5 hours or so. When the Prowlarr team import the updated indexer from our source (anytime they please from now) then this should be available on that app too.

You guys are awesome!!! THANK YOU! On behalf of myself and others in the MIRCrew community who will benefit!
Will Prowlarr automatically transpose this fix or do you have to report it to someone somehow?

Since you explained to me that from your side there is no way to solve the file size problem right?
Would there perhaps be a way by which the forum releasers can specify the size and have jackett be able to read it easily? I could then flag it and solve that problem as well.
Let me know!

Thanks

**Comment by ilike2burnthing** [comment] 2024-02-03 01:44
> When the Prowlarr team import the updated indexer from our source (anytime they please from now) then this should be available on that app too.

Unless the file size of each release is in the search results page (which they can't/aren't going to do because the site is just a forum), this can't be fixed by them.

**Comment by garfield69** [comment] 2024-02-03 01:46
>Would there perhaps be a way by which the forum releasers can specify the size and have jackett be able to read it easily?

Probably a way forward would be for the releasers to include the size in their topic title within {}, for example:
`title movie (2024) 1080p x265 {2.6 GB} ita eng AAC Sub ita eng-group` or
`title series 2024 - Stagione 01 (2024) [COMPLETA] 480p x264 {920 MB} ita eng AAC Sub ita eng-group`

The indexer when processing the search results, could then look for the {} in the title and extract the size, and if not present default to 512MB

**Comment by mtguido87** [comment] 2024-02-03 01:51
> > Ci sarebbe forse un modo in cui i releaser del forum possano specificare la dimensione e fare in modo che Jackett sia in grado di leggerla facilmente?
> 
> Probabilmente una soluzione sarebbe che i rilasci includessero la dimensione nel titolo dell'argomento all'interno di {}, ad esempio: `title movie (2024) 1080p x265 {2.6 GB} ita eng AAC Sub ita eng-group`or `title series 2024 - Stagione 01 (2024) [COMPLETA] 480p x264 {920 MB} ita eng AAC Sub ita eng-group`
> 
> L'indicizzatore durante l'elaborazione dei risultati della ricerca, potrebbe quindi cercare {} nel titolo ed estrarre la dimensione e, se non presente, impostare automaticamente 512 MB

This would be a very good solution. 
If you give me confirmation that you could update jackett with this feature I will immediately try to notify the releasers to include the size between {} in the title, hopefully they will accept this proposal.

Do they just have to put the size between {}? Is it preferable to use a period or comma for the two decimals? Should GB also be written after the numbers?

Which of the following?
{3,60}
{3.60}
{3.60GB}
{3.60GB}
{3.60gb}
{3.60gb}

THANK YOU

**Comment by garfield69** [comment] 2024-02-03 02:04
I chose braces because its not usually part of the title, so it would be easy for the indexer to detect and attempt to parse the content as a size value. 

The Jackett size parse tool is fairly flexible in its attempts to recognise a size value, as shown in this code snippet
```C#
        // ex: " 3.5  gb   " -> "3758096384" , "3,5GB" -> "3758096384" ,  "296,98 MB" -> "311406100.48" , "1.018,29 MB" -> "1067754455.04"
        // ex:  "1.018.29mb" -> "1067754455.04" , "-" -> "0" , "---" -> "0"
        public static long GetBytes(string str)
        {
            var valStr = new string(str.Where(c => char.IsDigit(c) || c == '.' || c == ',').ToArray());
            valStr = (valStr.Length == 0) ? "0" : valStr.Replace(",", ".");
            if (valStr.Count(c => c == '.') > 1)
            {
                var lastOcc = valStr.LastIndexOf('.');
                valStr = valStr.Substring(0, lastOcc).Replace(".", string.Empty) + valStr.Substring(lastOcc);
            }
            var unit = new string(str.Where(char.IsLetter).ToArray());
            var val = CoerceFloat(valStr);
            return GetBytes(unit, val);
        }

        public static long GetBytes(string unit, float value)
        {
            unit = unit.Replace("i", "").ToLowerInvariant();
            if (unit.Contains("kb"))
                return BytesFromKB(value);
            if (unit.Contains("mb"))
                return BytesFromMB(value);
            if (unit.Contains("gb"))
                return BytesFromGB(value);
            if (unit.Contains("tb"))
                return BytesFromTB(value);
            return (long)value;
        }
```
But for clarity and simplicity, `{2 TB}` or `{6.9 GB}` or `{20 MB}` or `{400 KB}` would most reliably get recognised.

**Comment by garfield69** [comment] 2024-02-03 02:32
size extractor from title added to indexer.

**Comment by garfield69** [comment] 2024-02-03 05:57
v0.21.1672

**Comment by mtguido87** [comment] 2024-02-03 12:48
Again, thank you for the very quick action. 

I am preparing a thread on the MIRCrew forum to ask the releasers to use this formatting in the titles for size.

On the other hand, regarding the failure to report seeders and leechers, couldn't this be solved with the same method they use in the forum to report them? Basically the system contacts the first tracker in the magnet trackerlist and gets the related information from there, couldn't jackett do that too?

**Comment by ilike2burnthing** [comment] 2024-02-03 12:51
Again, we're not going to do 100 additional requests for every search to return this data.

**Comment by mtguido87** [comment] 2024-02-03 13:12
> Ancora una volta, non eseguiremo 100 richieste aggiuntive per ogni ricerca per restituire questi dati.

Sorry, I don't know the operation so I'm probably saying something stupid. 
But jackett can now pick up the magnet without any problems, especially after the fix you made yesterday.
Once picked up, wouldn't it be able to pick up seeders and leechers directly from the magnet trackerlist without having to make 100 calls?

**Comment by mtguido87** [comment] 2024-02-03 14:01
Okay, I tried that. So I think the seeders and leechers we should definitely do without.

Thank you all the same!

**Comment by mtguido87** [comment] 2024-02-04 22:19
Good evening,
I proposed on mircrew to start putting the size of releases in curly brackets and they seem to have welcomed it, at least for future releases.
However, there is a releaser who asked if it would be possible, instead of looking for the size between the brackets, to look for it through a regex of this type:

(\d+[\•,]?\d+?\s*[KkMmGgTtBb][bB]?)

This is because so many existing releases have the dimension in square brackets. So we would gain the dimension not only on the future but also on the past!!!
Moreover, with such a regex the dimension would be obtained in all ways, even if it were not in brackets practically.

Is this a feasible thing for you?


Thanks!!!

**Comment by ilike2burnthing** [comment] 2024-02-04 23:43
We can make it case insensitive and then use the following to reduce any false positives to a minimum:

`\[(1?\d{1,3}(?:[\.,]\d{1,2})?\s*[KMGTP]?B)\]`

This would mean that `[1009,11 GB]` and `[57kb]` would be detected, but something like `2024b` would not.

**Comment by EmilioSalgari** [comment] 2024-02-04 23:59
I suggest `(1?\d{1,3}(?:[\.,]\d{1,2})?\s*[KMGTP]?i?B)[^\w]` so that `[1009,11 GiB]` `[57kb]` `(43Kb)` `6.9Tb` would be detected but `320kbps` would not.

**Comment by ilike2burnthing** [comment] 2024-02-05 00:17
I'd prefer to have some requirement for brackets, just to keep false positives to a minimum (e.g. `2B (2009) 1080p` would show a size of 2 bytes). How about the following?

`[\[\({](1?\d{1,3}(?:[\.,]\d{1,2})?\s*[KMGTP]?i?B)[\]\)}]`

**Comment by mtguido87** [comment] 2024-02-05 15:23
Good morning and thank you also for this update with Regex. We have communicated on the MIRCrew forum that they can now use brackets as so many were doing previously.

The TV series issue has come up now. This however on the Forum it often happens that within the thread a magnet is posted for each episode of the season. 
Therefore, would it be possible (for Sonarr only) to make it so that when the download button is clicked, not only the first [magnet] in the thread is picked up but all the ones there? Would it create some kind of problem? I read on your tracker information that this is possible but would have to be coded in C#. Could you take care of this?
Thank you

**Comment by ilike2burnthing** [comment] 2024-02-05 19:21
Not possible, in YAML or C#, without creating the aforementioned massive amount of additional traffic - https://github.com/Jackett/Jackett/issues/14543#issuecomment-1625710716

**Comment by mtguido87** [comment] 2024-02-05 19:26
> Not possible, in YAML or C#, without creating the aforementioned massive amount of additional traffic - [#14543 (comment)](https://github.com/Jackett/Jackett/issues/14543#issuecomment-1625710716)

Why should it generate massive traffic? I just ask that when you click download it doesn't just take the first magnet but all the ones in the thread. The action would be triggered only when the download is pressed so not for every search done.

**Comment by garfield69** [comment] 2024-02-05 23:34
The reason this is not possible, is because, as you may know, Jackett abides by the Torznab specifications with regards to the format of the queries and the responses.
The specs allow only for a single download link for every title returned from a query request.
So to provide a title with multiple download links would contravene the standards, and we are not going down that rabbit hole.

**Comment by mtguido87** [comment] 2024-02-05 23:39
> The reason this is not possible, is because, as you may know, Jackett abides by the Torznab specifications with regards to the format of the queries and the responses. The specs allow only for a single download link for every title returned from a query request. So to provide a title with multiple download links would contravene the standards, and we are not going down that rabbit hole.

Ok now the reason is more clear. Thank you for the explanation.

**Comment by boz96** [comment] 2024-02-06 14:05
Hi guys, first of all thanks for all the work you are doing.
I take this opportunity to ask another thing: is it possible to bypass the "unknown movie" error?
Because on MIRCrew many releases have the double title [ITA_NAME - ENG_NAME (YYYY)] which is not recognized by Radarr. As a result, a good 50% of releases would not be taken into consideration.
Thanks a lot
![Radarr - MIRCrew](https://github.com/Jackett/Jackett/assets/6417689/2e5c1ff2-17df-47b6-bd09-5602c376bd3a)

**Comment by garfield69** [comment] 2024-02-06 19:10
>is it possible to bypass the "unknown movie" error?

This is a limitation of Radarr which wants to match the full title.
 Unfortunately I don't see a way around this, because the mircrew web site does not support tmdbid or imdbid searching, which is the usual way to bypass the title and work off the id.
Some multi-lingual web sites have a title in the primary language and an alternate title with the other language.
But since mircrew only provides the topic title in search results, there is no practical way for the indexer to edit out the English title (or the Italian title for that matter) out of the title to thus return a shortened single language title which Radarr could match.

**Comment by garfield69** [comment] 2024-02-06 19:25
However, if the releasers were to add the year to the Italian side of the title then Sonarr would probably match.
eg. `il miglio verde (1999) - the green mile (1999) 1080p x265 ITA ENG {4.0GB} -group`

**Comment by ilike2burnthing** [comment] 2024-02-06 20:00
We could add an indexer setting that would strip out the first part of the title. A re_replace along the lines of:

`^.+ - (?!Stagion(e|i) \d|Special \((?:19|20)\d{2}|Miniserie)(.+? \((?:19|20)\d{2})`

It would definitely need to be disabled by default, as no matter how much I tweak that it's going to have false positives.

**Comment by garfield69** [comment] 2024-02-06 20:45
Hmm. would tagging if its a movie or not reduce the candidates an thus the false hits?
something like:
```yaml
    _is_movie:
      selector: a[href^="./viewforum.php?f="]
      attribute: href
      case:
        a[href*="f=25"]: yes
        a[href*="f=26"]: yes
        a[href*="f=34"]: yes
        a[href*="f=36"]: yes
        "*": no
```
?

**Comment by ilike2burnthing** [comment] 2024-02-06 21:39
Yea, that would definitely help if we only want to do it for movies. There were some examples of TV series with dual language titles (e.g. His Dark Materials, Percy Jackson and the Olympians, Servant of the People); they were few and far between, but are there. 

I ended up with this:
`^(.+ )- (?!Stagion[ei] \d|Special \((?:19|20)\d{2}|Miniserie).+? ((?:- Stagion[ei] \d+(?:-\d+)? )?\((?:19|20)\d{2}|\[COMPLETA|\[IN CORSO|\[IN PAUSA|\[INCOMPLETA)`
but even that had false positives, and it breaks a lot of stuff outside of Film and Serie TV categories (though I suppose we could also add `_is_serie_tv`).

I'd lean towards just movies for now, and if we get reports of issues with 'unknown series' in Sonarr then we can revisit. What do you think?

**Comment by garfield69** [comment] 2024-02-06 21:45
Given that the original query was for Radarr dual title unknown-movie flagging, I would just do movies to reduce the collateral, and definitely as a config optional. then strip out the 2nd title from the names.

**Closed** 2024-02-06 23:46 UTC
Labels: Needs Investigations

**Comment by garfield69** [comment] 2024-02-07 05:54
v0.21.1700

**Comment by TheDestr0yer** [comment] 2024-02-07 09:33
> v0.21.1700

Hello everyone , thank you for the work you are doing , I tested the new release but unfortunately the error is still there.

![Screenshot 2024-02-07 103013](https://github.com/Jackett/Jackett/assets/53081713/ed5fe2f0-eca8-4c60-b95b-fbcbc9840616)
