### ISSUE TITLE
[nyaasi] Exception (nyaasi): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED  at /build/mono-5.14.0.177/external/boringssl/ssl/handshake_client.c:1132: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by seesykescode** [Jackett/Jackett#3730] opened 2018-08-31 22:21 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  Version 0.10.134.0
**Mono version** (if not using Windows):  mono-5.14.0.177

-------------------------------

Just started happening within the last 3 days, after updating Ubuntu. I can't test any tracker nor can anything that uses the jackett links.    The same error happens on every tracker I have set up.  I've uninstalled and reinstalled Jackett. I also can't seem to check for updates either.

**Comment by garfield69** [comment] 2018-08-31 22:26
Have you tried re-importing the certificates:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
and reboot after the imports are completed.

**Comment by seesykescode** [comment] 2018-08-31 22:27
I'll give it a shot now. Thanks for the quick reply!

**Comment by hepherino** [comment] 2018-09-01 08:32
Tried the above mentioned fix.
Rebooted my server.
Same problem as @seesykescode.

Jackett version: 0.10.134.0
Mono version:  5.14.0.177

All trackers now fail to operate, no tests complete.
Was there an upstream package from Canonical/Ubuntu that auto-installed and possibly broke Jackett?

**Comment by gipasoft** [comment] 2018-09-01 09:56
Same problem on QNAP TS-469 PRO (firmware 4.3.4.0675)

Jackett version: 0.10.134.0
Mono version: 5.12.0.266
Indexer: Corsaro Nero

**Comment by flightlevel** [comment] 2018-09-03 09:42
@gipasoft Your issue is different, related to Il Corsaro Nero, which is fixed in the latest version of Jackett

@seesykescode @hepherino 

What's the output (run as root) of `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
What's the output of `csharp -e 'Console.WriteLine (new System.Net.WebClient ().DownloadString ("https://www.howsmyssl.com/").IndexOf ("1.2"))'`

**Comment by hepherino** [comment] 2018-09-06 03:50
Output, as requested:

`root@poseidon:~# wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin
--2018-09-06 03:49:37--  https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se (curl.haxx.se)... Mono Certificate Store Sync - version 5.14.0.177
Populate Mono certificate store from a concatenated list of certificates.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

151.101.54.49, 2a04:4e42:d::561
Connecting to curl.haxx.se (curl.haxx.se)|151.101.54.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 213947 (209K) [application/x-pem-file]
Saving to: ‘STDOUT’

-                                                           100%[========================================================================================================================================>] 208.93K  --.-KB/s    in 0.06s

2018-09-06 03:49:37 (3.42 MB/s) - written to stdout [213947/213947]

Importing into legacy system store:
I already trust 132, your new list has 132
Import process completed.

Importing into BTLS system store:
I already trust 132, your new list has 132
Import process completed.
root@poseidon:~# csharp -e 'Console.WriteLine (new System.Net.WebClient ().DownloadString ("https://www.howsmyssl.com/").IndexOf ("1.2"))'
3636
`

**Comment by hepherino** [comment] 2018-09-09 23:44
any updates on this? @flightlevel

**Comment by garfield69** [comment] 2018-09-09 23:56
@hepherino 

Please post the output of `openssl s_client -connect nyaa.si:443`

**Comment by hepherino** [comment] 2018-09-11 08:47
```root@poseidon:~# openssl s_client -connect nyaa.si:443
CONNECTED(00000003)
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN                                                                                                                                                              = COMODO RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN                                                                                                                                                              = COMODO RSA Domain Validation Secure Server CA
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL Wildcard, CN = *.sucuri.                                                                                                                                                             net
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.sucuri.net
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Dom                                                                                                                                                             ain Validation Secure Server CA
 1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Dom                                                                                                                                                             ain Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Cer                                                                                                                                                             tification Authority
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Cer                                                                                                                                                             tification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External C                                                                                                                                                             A Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFTDCCBDSgAwIBAgIRAKYx9XcNj3oL/kVOEkhrBAMwDQYJKoZIhvcNAQELBQAw
gZAxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTYwNAYD
VQQDEy1DT01PRE8gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIg
Q0EwHhcNMTUwMTMwMDAwMDAwWhcNMjAwMTI5MjM1OTU5WjBZMSEwHwYDVQQLExhE
b21haW4gQ29udHJvbCBWYWxpZGF0ZWQxHTAbBgNVBAsTFFBvc2l0aXZlU1NMIFdp
bGRjYXJkMRUwEwYDVQQDFAwqLnN1Y3VyaS5uZXQwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDUsvrSTTGS+k1yXgrl+PloFr1ny6j4DNnyN5mr2SeNC8Sd
T0dQWY/SFGTzVl4Q6Op/zsbMfxELIar6WfF/BWHxU3adT+aTnmQ9EzfkdPD8sYN3
VLN/wY6IUTD/YEOhJ0e2iZF3m56Kyx4MLXAmd50Fsn9zkJ1vKcznuxAxfLcOsqj5
JSdjXO15kcBk6D0rkNR4M5P+Kddl9CJj3LKrOYXHbOOiXIPzSblHDzw9Z1yywnf3
yMbpbMqPOx03Ou0TXe8Y9APudJH363dyNCq/Q9xDNfwsBTS7hFCLQI1eUH6eHLEx
Fzp15lSiEa7v1maPmQ8+lH+aRwsIvibGs9j/cCB5AgMBAAGjggHVMIIB0TAfBgNV
HSMEGDAWgBSQr2o6lFoL2JDqElZz30O0Oija5zAdBgNVHQ4EFgQU8TFxqifizWWz
d7W3H53lYlmpa2MwDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCME8GA1UdIARIMEYwOgYLKwYBBAGyMQEC
AgcwKzApBggrBgEFBQcCARYdaHR0cHM6Ly9zZWN1cmUuY29tb2RvLmNvbS9DUFMw
CAYGZ4EMAQIBMFQGA1UdHwRNMEswSaBHoEWGQ2h0dHA6Ly9jcmwuY29tb2RvY2Eu
Y29tL0NPTU9ET1JTQURvbWFpblZhbGlkYXRpb25TZWN1cmVTZXJ2ZXJDQS5jcmww
gYUGCCsGAQUFBwEBBHkwdzBPBggrBgEFBQcwAoZDaHR0cDovL2NydC5jb21vZG9j
YS5jb20vQ09NT0RPUlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNy
dDAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuY29tb2RvY2EuY29tMCMGA1UdEQQc
MBqCDCouc3VjdXJpLm5ldIIKc3VjdXJpLm5ldDANBgkqhkiG9w0BAQsFAAOCAQEA
QR/ITTaQlSIJzUvCdJ76Nu+P8IAU4fZcSDldjddaFvPlU8rh4ySd1PSO+jWc503H
UYZMwH5oHVOkuvP8eWvhMAKPlj0F4DOnT1sM14+VEipJbZH26s5mKsnKM8PNIoIG
jKxIrxa+HzeIb7hZGaqeVtW/czjY5BWpXZehnHJmWJqPo28zAEIrGtHqHHTtcmZX
4UCg/M67JuIdtVQcP3Ny9dqAWqPwoJSVSgaGyzxs37lKHhewj9BJPMGyPpZtMqgh
fgxQrh1UqrKuApIH3GH2byJngRUldlf1phq+ObTPQuyvOIE7gYToPtjOY7Nyt24q
NYv8vaLhzNr+8oB9gfthjg==
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.sucuri.net
issuer=/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA D                                                                                                                                                             omain Validation Secure Server CA
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4984 bytes and written 302 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: ADB0F6AD8417364BDA7352CA5EBE7BA4A7E1FDEF6941CA8CE4601B3FAA4351DD
    Session-ID-ctx:
    Master-Key: B70F323C873D4C6E5FA34FFFCCA794FBA3AE35C04003E160CA63E52E3C022154                                                                                                                                                             348367E381687D79C274DCD842C975DF
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 5f 49 bc cd d5 db 57 00-2f ab 58 ae a8 f2 ef ad   _I....W./.X.....
    0010 - 91 c0 b6 9b 3e 42 c6 1f-ee 0e 77 85 98 f8 c8 1a   ....>B....w.....
    0020 - 90 94 6e 78 12 d2 6a e8-ed d7 43 a8 8d 0c cd a7   ..nx..j...C.....
    0030 - a6 6f cc 6d d0 03 46 30-58 79 af ac 4c 86 44 8d   .o.m..F0Xy..L.D.
    0040 - e3 61 4e 75 99 16 41 a1-ca 85 53 62 10 6e f1 00   .aNu..A...Sb.n..
    0050 - 48 2f 22 41 22 1d cc a3-46 b7 04 d1 de a9 ed b4   H/"A"...F.......
    0060 - 92 9f fe 62 2c c3 b1 c2-63 58 d2 48 24 db 3d 0a   ...b,...cX.H$.=.
    0070 - 74 89 b1 fd 87 25 66 d6-2a 6c 15 94 c6 1b cf 4a   t....%f.*l.....J
    0080 - 7c 67 9b 36 28 aa ab 51-e9 ca fe ed aa 3a 00 97   |g.6(..Q.....:..
    0090 - b6 77 73 24 17 1e 04 05-b6 fa 67 2f fe 8b c3 b8   .ws$......g/....
    00a0 - a0 35 1e 9b 54 80 bb 69-81 47 dd 83 47 66 05 46   .5..T..i.G..Gf.F

    Start Time: 1536655616
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
closed
```

**Comment by m47een** [comment] 2018-09-11 08:49
root@Amazon:~# openssl s_client -connect nyaa.si:443
CONNECTED(00000003)
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify return:1
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Domain Validation Secure Server CA
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL Wildcard, CN = *.sucuri.net
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.sucuri.net
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
 1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFTDCCBDSgAwIBAgIRAKYx9XcNj3oL/kVOEkhrBAMwDQYJKoZIhvcNAQELBQAw
gZAxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTYwNAYD
VQQDEy1DT01PRE8gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIg
Q0EwHhcNMTUwMTMwMDAwMDAwWhcNMjAwMTI5MjM1OTU5WjBZMSEwHwYDVQQLExhE
b21haW4gQ29udHJvbCBWYWxpZGF0ZWQxHTAbBgNVBAsTFFBvc2l0aXZlU1NMIFdp
bGRjYXJkMRUwEwYDVQQDFAwqLnN1Y3VyaS5uZXQwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDUsvrSTTGS+k1yXgrl+PloFr1ny6j4DNnyN5mr2SeNC8Sd
T0dQWY/SFGTzVl4Q6Op/zsbMfxELIar6WfF/BWHxU3adT+aTnmQ9EzfkdPD8sYN3
VLN/wY6IUTD/YEOhJ0e2iZF3m56Kyx4MLXAmd50Fsn9zkJ1vKcznuxAxfLcOsqj5
JSdjXO15kcBk6D0rkNR4M5P+Kddl9CJj3LKrOYXHbOOiXIPzSblHDzw9Z1yywnf3
yMbpbMqPOx03Ou0TXe8Y9APudJH363dyNCq/Q9xDNfwsBTS7hFCLQI1eUH6eHLEx
Fzp15lSiEa7v1maPmQ8+lH+aRwsIvibGs9j/cCB5AgMBAAGjggHVMIIB0TAfBgNV
HSMEGDAWgBSQr2o6lFoL2JDqElZz30O0Oija5zAdBgNVHQ4EFgQU8TFxqifizWWz
d7W3H53lYlmpa2MwDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCME8GA1UdIARIMEYwOgYLKwYBBAGyMQEC
AgcwKzApBggrBgEFBQcCARYdaHR0cHM6Ly9zZWN1cmUuY29tb2RvLmNvbS9DUFMw
CAYGZ4EMAQIBMFQGA1UdHwRNMEswSaBHoEWGQ2h0dHA6Ly9jcmwuY29tb2RvY2Eu
Y29tL0NPTU9ET1JTQURvbWFpblZhbGlkYXRpb25TZWN1cmVTZXJ2ZXJDQS5jcmww
gYUGCCsGAQUFBwEBBHkwdzBPBggrBgEFBQcwAoZDaHR0cDovL2NydC5jb21vZG9j
YS5jb20vQ09NT0RPUlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNy
dDAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuY29tb2RvY2EuY29tMCMGA1UdEQQc
MBqCDCouc3VjdXJpLm5ldIIKc3VjdXJpLm5ldDANBgkqhkiG9w0BAQsFAAOCAQEA
QR/ITTaQlSIJzUvCdJ76Nu+P8IAU4fZcSDldjddaFvPlU8rh4ySd1PSO+jWc503H
UYZMwH5oHVOkuvP8eWvhMAKPlj0F4DOnT1sM14+VEipJbZH26s5mKsnKM8PNIoIG
jKxIrxa+HzeIb7hZGaqeVtW/czjY5BWpXZehnHJmWJqPo28zAEIrGtHqHHTtcmZX
4UCg/M67JuIdtVQcP3Ny9dqAWqPwoJSVSgaGyzxs37lKHhewj9BJPMGyPpZtMqgh
fgxQrh1UqrKuApIH3GH2byJngRUldlf1phq+ObTPQuyvOIE7gYToPtjOY7Nyt24q
NYv8vaLhzNr+8oB9gfthjg==
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.sucuri.net
issuer=/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4989 bytes and written 419 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: A6E7A917A171DE1F237E092E4745EB42D5FA0464E064882F948541F366EE52D2
    Session-ID-ctx:
    Master-Key: 0FE83C70CED34D8158BE1B4F76307C6147C67D895D032901C707F90957D2240EF2DC5C6D509F54977ABA6270BEF557B8
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 96 57 c6 28 3b 6d 7d 07-44 5e 86 3a d8 6f 8d b0   .W.(;m}.D^.:.o..
    0010 - 63 6a 22 fe 5f 61 f1 93-df 16 ba 7d bb 42 b2 ef   cj"._a.....}.B..
    0020 - e6 fe 13 f0 6a b5 2b 5c-6b 7f 48 39 79 d3 a1 49   ....j.+\k.H9y..I
    0030 - 48 04 39 d4 77 69 1a ff-97 45 8e 9d 44 9c 11 5f   H.9.wi...E..D.._
    0040 - ed da 61 77 fd a3 52 01-2a 69 6c d6 12 11 07 63   ..aw..R.*il....c
    0050 - 90 e3 27 12 d0 5a 7e 08-bd a3 f2 26 01 d4 0b 24   ..'..Z~....&...$
    0060 - 3a b4 0d 28 df 47 1c a6-a7 4b 6c 33 dd 33 e4 b8   :..(.G...Kl3.3..
    0070 - 21 d8 2a 0a 61 c2 9e fc-e1 4c cd 1e b9 29 a7 7e   !.*.a....L...).~
    0080 - cd 85 42 cc df 14 c4 d3-20 27 a2 52 07 98 78 81   ..B..... '.R..x.
    0090 - 74 7d 56 03 52 5d e8 45-9a 71 cd c0 82 9c 92 68   t}V.R].E.q.....h
    00a0 - 08 ac cb 0a db e0 9d 70-36 14 c0 7d 88 20 46 55   .......p6..}. FU

    Start Time: 1536655674
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
closed

**Comment by m47een** [comment] 2018-09-13 08:48
any updates on this? The issue is still showing closed even though the information requested has now been provided.

**Comment by garfield69** [comment] 2018-09-15 02:45
try using your dashboard to edit the nyaa.si indexer's config's site link, and change the *https* to *http* and see if that works. 
on my win10 chrome im seeing a ERR_SSL_PROTOCOL_ERROR when accessing nyaa.si via https.

**Comment by garfield69** [comment] 2018-09-15 20:48
my win10 is accessing nyaa.si fine again now, but I see that they are using a CA from the *let's encrypt* CA provider, which on ilcorsaronero causes problems on some systems with incomplete CA chain errors. 
So I've added a CA ignore on nyaa.si, let's see if this helps when the next (pre)release is published.

**Comment by flightlevel** [comment] 2018-09-16 02:49
@m47een  try latest version of Jackett

**Comment by m47een** [comment] 2018-09-16 11:36
@flightlevel I'm running Jackett in a docker container on my Synology any idea how I can get it to run the latest version, I've tried click the Check for Updates button but that just returns 'Error checking for updates.' in the log.

**Comment by kaso17** [comment] 2018-09-17 14:13
@hepherino based on your openssl output something is blocking the connection, most likely a security product from sucuri.net

The CA chain of https://nyaa.si/ is complete, if the latest version fixes the certificate verify failed error then your local CA store is missing let's encrypt.

@garfield69 Yes, we should throw an error message when updates are disabled.

**Closed** 2018-10-16 06:46 UTC
