### ISSUE TITLE
[cpasbien] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by seb972** [Jackett/Jackett#1953] opened 2017-10-10 21:37 UTC
Hi everybody,

i had an issue with this tracker, jackett can't reach the host http://cpabien.org/
Can you check where is the problem please?

Jackett version:
Mono version

**Comment by garfield69** [comment] 2017-10-10 22:42
Please check your *cpasbien* entry on your Jackett dashboard with the wrench icon, and confirm or replace the Sitelink if it is not set to `http://cpabien.org/`, and test again.
![image](https://user-images.githubusercontent.com/6933240/31311880-3229967a-ac12-11e7-96f6-b77dfc73463a.png)
If you still cannot test successfully, then please check by using your Chrome Browser that you can access  `http://cpabien.org/` from there.
If you cannot access with your Browser, then the problem is with your service provider DNS or perhaps there is blocking going on?
But if you can access it with your Browser then please provide a full Jackett log. Instructions, should  you need them, can be found at [trobleshooting](https://github.com/Jackett/Jackett#troubleshooting).

**Comment by jokoast** [comment] 2017-10-19 13:41
Or maybe it's the wrong domain extension ? http://cpabien.la , http://cpabien.cx . Don't know which is the good one but definitely not cpabien.org, it redirects me to http://cpabien.la .

**Comment by kaso17** [comment] 2017-10-19 14:27
Yes, seems like .la is the new primary domain. With .org it won't work.
fixed via d4ff5d30225816ae82bf969abf3133bd33a267fa

**Closed by kaso17** 2017-10-19 14:27 UTC
