### ISSUE TITLE
[req]: xbytesv2

### ISSUE THREAD

**Issue by vinanrra** [Jackett/Jackett#15339] opened 2024-05-24 21:03 UTC
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Xbytesv2
- URL: https://xbytesv2.li/
- Description: Spanish Tracker for Movies and TV Shows
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 72h in 14 days
- Additional Comments: This tracker was updated (web changed) and now have enabled RSS, they aren't against automations, like they were on the old version due to poor performance.
```

**Comment by garfield69** [comment] 2024-05-24 21:06
duplicate of #15338

**Closed by garfield69** 2024-05-24 21:06 UTC
Labels: Duplicate
