### ISSUE TITLE
Error loading indexers, request to Jackett server failed, is server running ?

### ISSUE THREAD

**Issue by justinasfour04** [Jackett/Jackett#14516] opened 2023-06-29 02:30 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient
Mono version: 6.8.0.123 (tarball Fri Jun 23 05:36:59 UTC 2023)
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /mnt/config
ThreadPool MaxThreads: 400 workerThreads, 200 completionPortThreads
Running in Docker: No	
Jackett variant: Mono
OS version: Unix 13.1.7.0 (64bit OS) (64bit process)
Environment version: 4.0.30319.42000 (/usr/local/lib/mono/4.5)
Jackett Data will be stored in: /mnt/config
Running Jackett in a TrueNAS jail
```

### Description

Installed Jackett in a trueNAS jail using pkg install jackett. Set all the necessary system variables in order for jacket to boot when jail starts. Whenever I try to access the WebUI I get 

Error loading indexers, request to Jackett server failed, is server running ?

### Logged Error Messages

```text
GET http://192.168.1.123:9117/api/v2.0/indexers?_=1688005732329 net::ERR_INVALID_CHUNKED_ENCODING 200 (OK)
```

### Screenshots

<img width="929" alt="image" src="https://github.com/Jackett/Jackett/assets/6599551/e3fe9827-908b-4e41-9439-1016d00358df">

<img width="1680" alt="image" src="https://github.com/Jackett/Jackett/assets/6599551/9c965734-462d-429b-8ea9-2a3ff6609be7">

<img width="1680" alt="image" src="https://github.com/Jackett/Jackett/assets/6599551/644584b2-5851-4863-820f-f3921e78c27f">

**Comment by ilike2burnthing** [comment] 2023-06-29 18:22
If you open in a private/incognito window, does the webUI even load?

**Comment by justinasfour04** [comment] 2023-06-30 02:56
> If you open in a private/incognito window, does the webUI even load?

webUI loads but same error happens

**Comment by ilike2burnthing** [comment] 2023-06-30 03:13
How are you accessing Jackett in browser, local IP or reverse proxy? If the latter, try the former.

Are you using a VPN? If so, try disabling it.

See the responses to https://github.com/Jackett/Jackett/issues/8872.

**Comment by justinasfour04** [comment] 2023-06-30 13:44
I am acessing jackett via local IP where it is running in a TrueNAS jail

**Comment by ilike2burnthing** [comment] 2023-06-30 14:01
No VPN?

For one person in https://github.com/Jackett/Jackett/issues/8872 it ended up being a rights issue.

**Comment by justinasfour04** [comment] 2023-06-30 15:18
No VPN, Just jackett running in a 13.2-RELEASE jail

**Comment by ilike2burnthing** [comment] 2023-07-01 11:16
Did you try resolving any potential rights issue as in the linked issue above?

**Comment by justinasfour04** [comment] 2023-07-02 02:52
it's tough to try resolving issues like in the one above because I am not using a reverse proxy

**Comment by justinasfour04** [comment] 2023-07-02 02:52
also the OS is freeBSD

**Comment by ilike2burnthing** [comment] 2023-07-02 12:57
The rights solution doesn't have anything to do with a reverse proxy - https://github.com/Jackett/Jackett/issues/8872#issuecomment-817256514

**Comment by juxe** [comment] 2023-07-06 00:50
I have the same error message on a new install on TrueNAS using TrueCharts. The API request to get the indexers returns a 500 error with this message:
`{
    "result": "error",
    "error": "Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space.",
    "stacktrace": "   at System.Runtime.CompilerServices.RuntimeHelpers.EnsureSufficientExecutionStack()\n   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)\n   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel, Object container)\n   at Microsoft.AspNetCore.Mvc.ModelBinding.ObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model, ModelMetadata metadata, Object container)\n   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.EnforceBindRequiredAndValidate(ObjectModelValidator baseObjectValidator, ActionContext actionContext, ParameterDescriptor parameter, ModelMetadata metadata, ModelBindingContext modelBindingContext, ModelBindingResult modelBindingResult, Object container)\n   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)\n   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61"
}`

**Comment by ilike2burnthing** [comment] 2023-07-06 01:03
https://github.com/truecharts/charts/issues/8885

**Closed by ilike2burnthing** 2023-07-06 01:03 UTC
Labels: More information needed, OS Linux / Mono / *nix

**Comment by justinasfour04** [comment] 2023-07-13 18:43
why did you change the label to Wontfix, what if there actually is an underlying issue

**Comment by ilike2burnthing** [comment] 2023-07-14 00:36
Because the issue isn't on our end, so we won't/can't fix it.
