### ISSUE TITLE
[yts] Name or service not known (yts.mx:443): Name or service not known (Config)

### ISSUE THREAD

**Issue by Chappy202** [Jackett/Jackett#12081] opened 2021-07-27 08:37 UTC
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Ubuntu

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
Mono

**.Net Version**:
Version=v5.0/linux-x64

**Jackett Version**:
0.18.475

**Last Working Jackett Version**:
Unsure

**Are you using a proxy or VPN?** [yes/no]
No

### Description
YTS indexer not working, their website link changed to [https://yts.lt/](https://yts.lt/) instead of the current [https://yts.mx/](https://yts.mx/)

[List steps to reproduce the error and details on what happens and what you expected to happen]

- When the YTS indexer is added, it should add the same way all others would instead of displaying the below error message

### Logged Error Messages
Name or service not known (yts.mx:443): Name or service not known

**Comment by garfield69** [comment] 2021-07-27 08:39
duplicate of #1145
yts.mx domain is broken.
edit your yts config and switch sitelink to the unblockit alternate, which is still working for now.

**Closed by garfield69** 2021-07-27 08:39 UTC

**Comment by garfield69** [comment] 2021-07-27 19:44
yts.mx appears to be back online.
