### ISSUE TITLE
[New Tracker REQ] TorrenTech (TTH)

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#779] opened 2016-12-01 15:55 UTC
A GREAT tracker for EDM! I joined a while back through their reddit recruitment thread. 
https://www.torrentech.org/

If you PM tT-Kolor with 2 good ratio proofs **AND** 2 of your private tracker profile links, you'll receive an invite within a couple of days.
https://www.reddit.com/r/trackers/wiki/reddit_offers

**Comment by kaso17** [comment] 2016-12-02 08:26
application sent

**Comment by armani316** [comment] 2016-12-07 20:08
Did they ever reply to your application? @kaso17

**Comment by kaso17** [comment] 2016-12-07 20:36
tT-Kolor asked me for my email as I forgot to include it in the initial request. sent it 2 days ago, waiting since then.

**Comment by armani316** [comment] 2016-12-07 20:43
@kaso17 I guess they get swamped with applications! You might want to remind him in a day or two.

**Comment by kaso17** [comment] 2016-12-08 07:32
got the invite.

**Comment by kaso17** [comment] 2016-12-08 07:43
definitely will be a jackett native tracker

**Comment by armani316** [comment] 2016-12-26 00:28
@kaso17 Any plans to add support for TTH in an upcoming update?

**Comment by kaso17** [comment] 2016-12-26 14:44
I've little time these days, I'm trying to squeeze it in. It has been a little lower on my priority list as it's much work (due to the forum structure) to add than other trackers.

**Comment by armani316** [comment] 2016-12-26 14:48
No problem, sir. Take your time :)

**Comment by kaso17** [comment] 2016-12-29 18:57
Fixed with 440d59a30e870005c0ccca3be55d9d3bef8faf05

**Closed by kaso17** 2016-12-29 18:57 UTC
Labels: New tracker

**Comment by armani316** [comment] 2016-12-29 20:10
@kaso17 Thank you for adding TorrenTech. However, I can't seem to configure it - I get a configuration failed message. Enhanced log attached.
[log.txt](https://github.com/Jackett/Jackett/files/677806/log.txt)

**Comment by kaso17** [comment] 2016-12-30 12:41
Caused by your theme. If you change it to "TT graphite" it should work.
8e8f143b02db447dcb45edfa183cabb751d38e00 adds support for all themes

**Comment by AdeHub** [comment] 2016-12-31 06:57
Thanks for adding this, any chance of including the torrent size ('length'?) in the returned data?

**Comment by kaso17** [comment] 2016-12-31 10:15
If you convince the staff to show the torrent size in the search results topics list we can add it. Otherwise we would have to make a http request for each search result which would slow down the search and put a lot of extra load on the tracker.

**Comment by AdeHub** [comment] 2017-01-01 00:56
Have sent a request to add size to the search results, in the meantime maybe you could add an optional config option to return the size?

Also, could you allow AAC as well as MP3, i.e. ```if (format.Contains("MP3")||format.Contains("AAC"))```

**Comment by kaso17** [comment] 2017-01-02 06:04
Did you start a discussion about the size anywhere?
I'll only add an option if I get a OK for it from the staff (Due to the extra load)

**Comment by kaso17** [comment] 2017-01-02 20:50
AAC mapping to Audio/Other was added in pre-release v0.7.841, please try it

**Comment by AdeHub** [comment] 2017-01-03 08:06
Looks good 👍
