### ISSUE TITLE
[REQ] Tracker Request: Trackeros

### ISSUE THREAD

**Issue by Shutruk** [Jackett/Jackett#12046] opened 2021-07-17 20:57 UTC
https://trackeros.tk/

Private.

Made on UNIT3D.

**Comment by garfield69** [comment] 2021-07-17 21:29
duplicate of #10862

this indexer was defined on Jackett back in January.

**Closed by garfield69** 2021-07-17 21:29 UTC

**Comment by garfield69** [comment] 2021-07-17 21:34
however it is possible that the indexer is out of date, as it was written for unit3d 4.x and the login atm indicates the site is on unit3d 5.x so if the indexer is not working let us know (I don't have an account so I cannot test). thanks.

**Comment by Shutruk** [comment] 2021-07-17 21:54
My bad! Just tested it on the latest version and it works perfectly.
