### ISSUE TITLE
torrentseeds: Missing quotes or + in search

### ISSUE THREAD

**Issue by KyleSanderson** [Jackett/Jackett#14254] opened 2023-04-15 05:05 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
v0.20.3903
```

### Description

When you search TorrentSeeds, it returns *every* result related to any keyword passed. They changed this in February https://torrentseeds.org/forums/topics/203

Two options, one is to wrap the user query in quotes, the other is to add a + for each to require "each" item to be present.

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment] 2023-04-15 05:16
Thanks for the info. I will implement the plus suffix method.

**Comment by KyleSanderson** [comment] 2023-04-15 05:22
> Thanks for the info. I will implement the plus suffix method.

Do you have access? the syntax seems pretty nuts.

**Comment by garfield69** [comment] 2023-04-15 05:32
yes I have an a/c.
I have tested the indexer pre and post update to confirm it works as intended.
the fix will be released when Jackett next gets published, which is due in about half an hour ;-)

**Comment by garfield69** [comment] 2023-04-15 06:00
v0.20.3906

**Comment by KyleSanderson** [comment] 2023-04-15 06:47
hmm. I'm not getting anything back for `Jimmy Kimmel 2023 04 13` on the new query.

**Comment by garfield69** [comment] 2023-04-15 07:02
you right. but I'm not getting anything on the web site using `+jimmy +kimmel +2023 +04 +13` either so that matches what the indexer would build out of `Jimmy Kimmel 2023 04 13`
but searching `mandalorian s03e07` with the indexer returns the same results as `+mandalorian +s03e07` on the web site.
so it must be that the date string is an issue on the web site.
do you want to get onto the web site and experiment to see what would work for tv series that use the date format?

**Comment by KyleSanderson** [comment] 2023-04-15 07:18
I really doubt it's Jackett and quirks of the site. Quoting the whole thing `"Jimmy Kimmel 2023 04 13"` gives the right result. Technically the + is superior to what a user would expect (searching by hand, as opposed to a program), but the quotes seem to be the most correct with their current (odd) implementation.

**Comment by garfield69** [comment] 2023-04-15 07:19
it looks like on the web site `+jimmy +kimmel +"2023.04.13"` works
@ilike2burnthing or @mynameisbogdan  you are both better at regexp than I
how would you code the keywords filter so that a plus is added to the front of keywords, except when the keyword is a date string in which case its needs double quotes?

**Comment by garfield69** [comment] 2023-04-15 07:28
> Quoting the whole thing gives the right result

yeah, but that works best only for *arr app queries, but handicaps freeform keyword searches, such as for instance  `jimmy 2023.04.13` using the search console, which is why I leaned towards using the plus prefix.

**Comment by garfield69** [comment] 2023-04-15 07:33
I suppose double quoting each keyword and prefixing a plus works too
`+"jimmy" +"2023.04.13"`  and `+"jimmy" +"kimmel" +"2023 04 13"` work

**Comment by KyleSanderson** [comment] 2023-04-15 08:08
Feels a bit insane:
It looks like strings of numbers need to be quoted, until they're separated by a word character (the character set below doesn't break the match).
"720" as an example matches nothing, and "720p" matches again so it needs the full token until a separator (which is likely [-._ ] but unconfirmed).
Then there's `FHC0397` which does not match `"*0397*"` and gives a different result than `*0397*`
Same with `"720*"` vs `720*`.

I still think quoting the whole thing may be the right way, but maybe I'm missing the key here. Date strings may also cover most real cases as well.

**Comment by garfield69** [comment] 2023-04-15 08:16
useful feedback, thanks.
I'm going to let the other team members (both of whom have a/c for the site) mull this over and pick the best method to cover the majority of cases. I'm too tired to give this any more attention ;-b

**Comment by ilike2burnthing** [comment] 2023-04-15 09:26
The issue seems to be that prepending `+` to 1 or 2 characters breaks the search. 

They also don't allow partial word matching, e.g. `0397` does not match `FHC0397`.

Putting the whole search term in quotes will only work if all keywords are in the same order as the titles, e.g. `"kimmel jimmy"` will not match `Jimmy Kimmel` whereas searching `+kimmel +jimmy` would (see also https://github.com/Jackett/Jackett/issues/14254#issuecomment-1509609523).

**Closed** 2023-04-15 09:25 UTC

**Comment by garfield69** [comment] 2023-04-16 06:00
v0.20.3917

**Comment by KyleSanderson** [comment] 2023-04-16 06:42
Nice one guys, just tried it now and working much better. thank you both for your help
