### ISSUE TITLE
[req]: HUDBT（蝴蝶）

### ISSUE THREAD

**Issue by Aicnal** [Jackett/Jackett#15306] opened 2024-05-12 01:22 UTC
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: HUDBT（蝴蝶）
- URL: https://hudbt.hust.edu.cn/
- Description: HUDBT is a CHINESE Private Torrent Tracker for HD MOVIES / TV
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): TBD
- Additional Comments: The code of the pt has been located in https://github.com/zuohaocheng/hudbt/
```

**Comment by garfield69** [comment] 2024-05-12 01:25
closing as a duplicate of #15305

**Closed by garfield69** 2024-05-12 01:25 UTC
