### ISSUE TITLE
[chdbits] (updating) Login failed: No form found on https://ptchdbits.co/login.php using form selector form[action="takelogin.php"]

### ISSUE THREAD

**Issue by lingqi606** [Jackett/Jackett#15653] opened 2024-10-16 01:19 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: https://www.qq.com:8191
Using proxy: Http
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.22.43-ls421)
File /etc/issue: Welcome to Alpine Linux 3.20
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.1.79.0 (64bit OS) (64bit process)
Environment version: 8.0.10 (/app/Jackett/)
Starting Jackett v0.22.800
```

### Description

add indexer → [CHDBits]The wrench icon on the right → Enter account password → Okay
Error occurred, unable to add。

### Logged Error Messages

```text
2024-10-16 09:11:19	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://ptchdbits.co/login.php using form selector form[action="takelogin.php"]

[v0.22.800.0] Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://ptchdbits.co/login.php using form selector form[action="takelogin.php"]
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 618
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1078
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2024-10-16 09:11:08	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://ptchdbits.co/login.php using form selector form[action="takelogin.php"]

[v0.22.800.0] Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://ptchdbits.co/login.php using form selector form[action="takelogin.php"]
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 618
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1078
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment] 2024-10-16 02:24
Given that I can confirm that the chdbits login page does indeed have a form[action="takelogin.php"] selector, then something is preventing you from accessing that page via your docker Jackett.
Please see if https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-no-form-found-on-url can guide you into resolving the issue for yourself.
If all fails then please provide a **full enhanced** log, perhaps the additional debug and HTML included in an enhanced log will provide the clue needed to solve the problem.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Thanks.

**Comment by lingqi606** [comment] 2024-10-16 06:16
I tried troubleshooting, but it didn't work. Below is my enhanced log.
[log.txt](https://github.com/user-attachments/files/17390282/log.txt)

**Comment by garfield69** [comment] 2024-10-16 06:22
Urg. Looks like your IP is not being accepted by chdbits because you exceeded the maximum number of attempts.

here is the message from the login page:
```
Login 锁定！(认证的最大错误尝试次数Login次已到)
我们怀疑你在欺骗系统，因此禁用了你的IP地址！
```
google translated
```
Login locked! (The maximum number of incorrect authentication attempts Login has been reached)
We suspect you are cheating the system, so we have disabled your IP address!
```

can you still access the site with your browser?

**Comment by garfield69** [comment] 2024-10-16 06:45
Also, the log prior to the lockout shows that download attempts were failing because you are a first time downloader so are being presented with a how-to-guide to download.
Before you can download with Jackett you will need to first access the site with your browser, visit a torrent you intend to download, click on a download link, which will present the help page, tick the don't-show-this-again and then click the download.
After that you should be able to download with Jackett.
IT seems you tried over 60 times to download and perhaps chdbits triggered a suspicious activity flag as a rusult.

**Comment by lingqi606** [comment] 2024-10-16 06:46
I can use the built-in browser on this server to log in to the website, and their IP addresses are the same.
I think the problem is that there was no validation image when adding "chdbits" (for example, "52pt" has a validation image). On October 10th, I accidentally refreshed the validation image for "chdbits" and successfully added it (see attached image).
![6c62864fbe828f93b378fbd21d280ec](https://github.com/user-attachments/assets/6d39204d-1403-4b9c-888b-d074ff39c8fd)
![b2b70bf911b37b67d78edcc11beeb62](https://github.com/user-attachments/assets/102f3888-284a-40f7-b50e-ac259dea023c)
![76902ad59736a8256901f33ffdbba71](https://github.com/user-attachments/assets/8f410742-9307-4afc-9eea-53ce749c9ae8)
![60f7dd09cd75aa3c705413e9e3023a8](https://github.com/user-attachments/assets/4a572a4e-a722-4c43-9f47-072eec9de850)

**Comment by garfield69** [comment] 2024-10-16 06:57
Well right now when you use the config edit on the chdbits indexer, you will not see the captcha because the site is presenting that IP locked out page to Jackett instead of the regular login page.
I see you are using the alternate domain https://ptchdbits.co/ with the indexer. Is that the same domain you use with the browser or are you using https://chdbits.co/ with your browser?

**Comment by lingqi606** [comment] 2024-10-16 07:06
“ https://chdbits.co ”This website often cannot be accessed on any network or device, so I am using it on my browser“ https://ptchdbits.co/  ”

**Comment by garfield69** [comment] 2024-10-16 07:09
sorry your last post does not make it clear to me which domain you are using.
are you saying that for both the indexer and the browser you are using the same domain ptchdbits?

**Comment by lingqi606** [comment] 2024-10-16 07:10
yes

**Comment by garfield69** [comment] 2024-10-16 07:15
So on your browser, have you logged into chdbits since Jackett started getting the IP locked error?
If you have not logged in recently, then do NOT logout of your browser, you do not want to be locked out ;-)

**Comment by lingqi606** [comment] 2024-10-16 07:19
I just logged in and logged out using a browser, and then logged in again without any problems.

**Comment by garfield69** [comment] 2024-10-16 07:22
And yet, if you use the Jackett dashboard to edit the chdbits config, you do not see the captcha image?
Close the config if you don't have a captcha, you do not want to bump the failed login count on the site and extend the lockout period. Also, do not use the chdbits indexer, until you sort out the login, as this will also aggravate the lockout.

**Comment by garfield69** [comment] 2024-10-16 07:36
The web site locks out the IP after 10 failed login attempts, but the page does not say how long the ban will last.
It makes not sense to me that you can use your browser to access chdbits on the same IP address as Jackett when Jackett cannot.

For now, I suggest you wait a day, and then use the Jackett dashboard to edit the chdbits config and see if the captcha appears.
In the mean time, perhaps you can search the chdbits forum for any info on the duration on a IP lockout after 10 failed attempts, or ask the support staff or the forum.

**Closed** 2024-10-24 01:38 UTC
Labels: More information needed, Docker
