### ISSUE TITLE
[torrentgalaxy] (testing) Test search in TorrentGalaxy => Found no results while trying to browse this tracker. 

### ISSUE THREAD

**Issue by Sliposis** [Jackett/Jackett#15430] opened 2024-06-18 19:49 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
32 bit win 10
```

### Description

Cant get torrentgalaxy to work anymore 

### Logged Error Messages

```text
An error occurred while testing this indexer
Test search in TorrentGalaxy => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```

**Comment by garfield69** [comment] 2024-06-18 19:52
closing as a duplicate of #15358

**Closed by garfield69** 2024-06-18 19:52 UTC
