### ISSUE TITLE
[torrentday] Your cookie did not work: Your cookie did not work (Config)

### ISSUE THREAD

**Issue by Dosk3n** [Jackett/Jackett#2496] opened 2018-01-28 17:56 UTC
Jacket was saying that it was not logged in so I got the cookie again and it keeps saying "Your cookie did not work"

Jackett version:  
0.8.629.0

-------------------------------

**Comment by garfield69** [comment] 2018-01-28 18:38
Duplicate of #2493

**Closed by garfield69** 2018-01-28 18:38 UTC
Labels: Duplicate
