### ISSUE TITLE
[req]: 1tamilmv

### ISSUE THREAD

**Issue by Craze477** [Jackett/Jackett#15303] opened 2024-05-11 08:44 UTC
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: 1tamilmv
- URL: https://1tamilmv.eu
- Description: 1tamilmv or tamilmv is a public torrent tracker for movies and tv shows.
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments: it's is a public tracker and url will be changing constantly now it's 1tamilmv.eu
```

**Comment by Craze477** [comment] 2024-05-11 08:45
Please add this tracker I cannot find this tracker in jackett

**Comment by garfield69** [comment] 2024-05-11 08:49
Closing as a duplicate of #2421

**Closed by garfield69** 2024-05-11 08:49 UTC
