### ISSUE TITLE
[blutopia] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by tgunz249** [Jackett/Jackett#11197] opened 2021-03-01 20:38 UTC
### Environment

**OS**: chrome

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.605

**Last Working Jackett Version**: no idea, I update the apps in my seedbox weekly

**Are you using a proxy or VPN?** [yes/no] no

### Description

Blutopia stopped working, I go to the site and everything is good, but nothing is populating on sonarr/radarr, come here and run a test and it says "Found no results while trying to browse this tracker", my other trackers are good.

**Comment by garfield69** [comment] 2021-03-01 20:44
closing as a duplicate of #11196 see its last comment for news.

**Closed by garfield69** 2021-03-01 20:44 UTC
