### ISSUE TITLE
No results from Hon3y HD 

### ISSUE THREAD

**Issue by kamikazechaser** [Jackett/Jackett#1125] opened 2017-03-01 14:22 UTC
jackett is unable to query and fetch results from the said private tracker. It can successfully authenticate, but not fetch results.

**Comment by armani316** [comment] 2017-03-01 14:29
@kamikazechaser Please post an enhanced log showing this error.

**Comment by kamikazechaser** [comment] 2017-03-01 17:10
**Example Search**

```
2017-03-01 19:52:25.4967 Info Manual search for "kaabil" on LimeTorrents with 41 results. 
2017-03-01 19:52:48.9736 Info Manual search for "kaabil" on Hon3y HD with 0 results. 
2017-03-01 22:38:01.0481 Info redirecting to /Admin/Dashboard 
2017-03-01 22:38:45.8898 Info Manual search for "kaabil" on Hon3y HD with 0 results.
```

**Comment by armani316** [comment] 2017-03-01 21:52
Not entirely sure whether this would be helpful for the developer. 

@kamikazechaser An enhanced error log is usually better to debug such issues. Please have a look at a few similar examples and how enhanced logs look like:

https://github.com/Jackett/Jackett/issues?utf8=%E2%9C%93&q=is%3Aissue%20author%3Aarmani316%20found%20no%20results

Make sure 'Enhanced logging' in Jackett it ticked, reproduce the issue, and post the log's output here.

**Comment by RoloSoze** [comment] 2017-03-09 15:01
@kamikazechaser Any luck posting an enhanced log to show this issue?

**Comment by kamikazechaser** [comment] 2017-03-09 15:13
Will get back to you.

**Comment by RoloSoze** [comment] 2017-03-14 22:31
@kamikazechaser I'm closing this due to non-response. When you get the chance to post an enhanced log showing the issue, please feel free to post it.

**Closed by RoloSoze** 2017-03-14 22:31 UTC

**Comment by kdizzay** [comment] 2017-04-05 22:11
I am also facing this exact issue on 0.7.1242.0 for hon3yhd. Here are my logs: 


Observations from logs : 


Query that Jackett makes : IWebClient.GetString(Url:https://hon3yhd.com/browse.php?search=Akira&incldead=1)

Result from query : 

IWebClient: Returning OK => <html>
<head>
<title>MySQL Error</title>

<style>P,BODY{ font-family:arial,sans-serif; font-size:11px; }</style>
</head>
<body>

<blockquote>
<h1>MySQL Error</h1><b>There appears to be an error with the database.</b><br />
You can try to refresh the page by clicking <a href="javascript:window.location=window.location;">here</a>.
<br /><br /><b>Error Returned</b><br />
<form name='mysql'><textarea rows="15" cols="60">
SQL error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;)&#039; at line 1
SQL error code: 1064
Date: Wednesday 05th of April 2017 11:00:07 PM</textarea></form><br>We apologise for any inconvenience</blockquote></body></html>

Now if I try the same query (https://hon3yhd.com/browse.php?search=Akira&incldead=1) from browser I get the same syntax error message as above. 

Now when I do a manual search on the website itself here is what the query looks like : 

https://hon3yhd.com/browse.php?search=Akira&searchin=all&incldead=1  (with 'all')
https://hon3yhd.com/browse.php?search=Akira&searchin=title&incldead=1 (with 'name')
https://hon3yhd.com/browse.php?search=Akira&searchin=descr&incldead=1 (with 'description')


Seems like they have changed the search function where a mandatory additional parameter 'Name' 'Description' or 'All' is added to all searches which is the &searchin= part of  the call. So if I plug in the new link now in the browser I get proper results. 

Looks like the code in Jackett for Hon3yHD has to be changed to modify to the new call. 

Again, I am not a tech heavy user, this was just my observations so hope it helps in fixing this issue. 

Thanks.

**Comment by kamikazechaser** [comment] 2017-06-08 07:31
Hi, this issue seems to have been fixed.
