### ISSUE TITLE
IPtorrents cannot add tracker

### ISSUE THREAD

**Issue by screwfaze** [Jackett/Jackett#875] opened 2016-12-19 21:18 UTC
Hi,

I have just installed Jackett on raspbian and having an issue with iptorrents tracker, when I try to add it it get the error "Configuration failed: Mapping types: WebClientByteResult -> WebClientStringResult Jackett.Utils.Clients.WebClientByteResult -> Jackett.Utils.Clients.WebClientStringResult Destination path: WebClientStringResult Source value: Jackett.Utils.Clients.WebClientByteResult"

I have added another tracker without any problem "PrivateHD"
Can anyone please advice and Im new to this please be gentle. 

Thanks

**Comment by kaso17** [comment] 2016-12-20 08:11
Please check if it's an duplicate of #873

**Comment by screwfaze** [comment] 2016-12-20 09:59
Hi,

I have tried entering the alternate address https://iptorrents.com but get the same error. 

Thanks

**Comment by screwfaze** [comment] 2016-12-20 10:04
I think there is a problem with the website now, I am in the UK and finding it hard to browser to the site using chrome.

Thanks

**Comment by kaso17** [comment] 2016-12-20 11:42
Make sure you've a tailing / in the URL (https://iptorrents.com/).
If you're in the UK I believe the website is supposed to be blocked.

**Comment by screwfaze** [comment] 2016-12-20 11:52
Yes I have tried as you said but same error. If the site is blocked what can I do can I use a proxy or something in jackett?

**Comment by kaso17** [comment] 2016-12-20 16:01
There's the --ProxyConnection command line option which might work

**Comment by screwfaze** [comment] 2016-12-20 16:28
Hi,

Please explain how I do this, noob at this.

Thanks

**Comment by screwfaze** [comment] 2016-12-21 12:17
Hi,

I now think the problem is jacket as I have setup a vpn connection which I have tested and can browse the site just fine but still getting the same error from jackett. Any assistance welcome

Thanks

**Comment by kaso17** [comment] 2016-12-21 15:14
Please post a log (with enhanced logging enabled)

**Comment by screwfaze** [comment] 2016-12-21 15:46
Sorry but where is the log located ? All i found is this but im not sure if this is what you need.

[log.txt](https://github.com/Jackett/Jackett/files/666758/log.txt)

**Comment by kaso17** [comment] 2016-12-21 16:35
Try running the following command:
curl -v https://iptorrents.com

**Comment by screwfaze** [comment] 2016-12-21 16:37
This is what i get when i run that;

 curl -v https://iptorrents.com
* Rebuilt URL to: https://iptorrents.com/
* Hostname was NOT found in DNS cache
*   Trying 193.113.9.167...
* connect to 193.113.9.167 port 443 failed: Connection refused
* Failed to connect to iptorrents.com port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to iptorrents.com port 443: Connection refused

**Comment by screwfaze** [comment] 2016-12-22 18:59
Hi,

You can close this I have resolved thanks for all your help.

Cheers

**Closed** 2016-12-23 06:26 UTC
