### ISSUE TITLE
[zooqle] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by SteffanCline** [Jackett/Jackett#2331] opened 2017-12-27 18:04 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.527.0
Mono version (if not using Windows): latest

-------------------------------

[log.txt](https://github.com/Jackett/Jackett/files/1589597/log.txt)

**Comment by kaso17** [comment] 2017-12-27 18:11
the log file doesn't contain any failed searches for zooqle

**Comment by SteffanCline** [comment] 2017-12-27 18:15
I'm pressing the test button repeatedly. What else can I do to capture this?

**Comment by kaso17** [comment] 2017-12-27 18:17
then it should be in the log file, if you've a lot of queries the log might have been renamed already (there should be some other log.* files)

**Comment by SteffanCline** [comment] 2017-12-27 19:58
[log.txt](https://github.com/Jackett/Jackett/files/1589759/log.txt)

**Comment by SteffanCline** [comment] 2017-12-28 02:46
Try that one.

**Comment by garfield69** [comment] 2017-12-28 18:51
Duplicate of #2328

**Closed by garfield69** 2017-12-28 18:51 UTC
Labels: Full logs needed
