### ISSUE TITLE
SubsPlease:  hardcoded fixed file sizes mess things up

### ISSUE THREAD

**Issue by Atario** [Jackett/Jackett#13860] opened 2023-01-07 11:56 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2

Using FlareSolverr: No

Using proxy: Disabled

App config/log directory: C:\ProgramData\Jackett

ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads

Running in Docker: No

Jackett variant: CoreWindows

OS version: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit OS)

Environment version: 6.0.12 (C:\ProgramData\Jackett\)

Starting Jackett v0.20.2495
```

### Description

Fix mentioned in #10857 causes problems for shorts:  Sonarr thinks file is way too big for its runtime.

Example:  https://subsplease.org/shows/nijiyon-animation/

Trying 720p release:

>Release Rejected
>700.0 MB is larger than maximum allowed 400.0 MB (for 4min)

Even though the release is actually ~107MB.

Thought of replacing the SubsPlease indexer with a second Nyaa indexer that has a user filter added, but neither of those things is possible in Jackett, as far as I can tell.

### Logged Error Messages

```text
[Error is downstream]
```

**Comment by ilike2burnthing** [comment] 2023-01-07 17:45
SubsPlease's API doesn't provide file size unfortunately, just resolution, and any size we hardcode will be wrong, so these rough averages were the best option. I'm not sure there's really an alternative solution.

---

As for creating permanent duplicate or custom indexers, it works fine on Docker, and I'm sure works on Linux too - you just change the filename, indexer name and ID and put them in a particular directory. However, on Windows I can't get this to work.

@garfield69, when starting Jackett my log shows:

> Loading Cardigann indexers from: C:\Windows\system32\config\systemprofile\AppData\Roaming\cardigann\definitions\, C:\Windows\system32\config\systemprofile\AppData\Local\cardigann\definitions\, C:\ProgramData\Jackett\Definitions

I assume we shouldn't actually be using System32, and rather `%AppData%` and `%LocalAppData%`. Are you seeing this as well, or is there an issue with Jackett?

As far as my google-fu goes, [this](https://github.com/Jackett/Jackett/blob/8442a7980f61a60225732c8e306f0e2f8655a0b4/src/Jackett.Common/Services/ConfigurationService.cs#L211-L212) should be using `%AppData%` and `%LocalAppData%`.

Placing indexers in the above directories or in `%AppData%` and `%LocalAppData%` doesn't result in new indexers being added on restart, so at a guess the above directories are actually being used (it's not just a logging issue), but Jackett doesn't have permission to access them.

@ngosang just in case you're still around and have a few minutes ^

**Comment by ngosang** [comment] 2023-01-07 18:24
Maybe he is running Jackkett as Administrator or with a Service with no Home path.

**Comment by garfield69** [comment] 2023-01-07 18:57
>I assume we shouldn't actually be using System32, and rather %AppData% and %LocalAppData%. Are you seeing this as well, or is there an issue with Jackett?

I see this too.
Loading Cardigann indexers from: C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\cardigann\definitions\, C:\WINDOWS\system32\config\systemprofile\AppData\Local\cardigann\definitions\, C:\ProgramData\Jackett\Definitions
definitely a Jackett windows issue.

**Comment by ilike2burnthing** [comment] 2023-01-07 20:25
So because we're running Jackett as a service, it runs as `Local System`, hence the files being under System32.

To get around that, you can either launch `JackettConsole` manually, or change the 'log on as' user to your own, but to be able to do that you have to [enable through Local Security Policy](https://learn.microsoft.com/en-us/system-center/scsm/enable-service-log-on-sm?view=sc-sm-2022#enable-service-log-on-through-a-local-group-policy), which is only available in Windows Pro editions and above (it might be possible to enable/install it, but I can't test that).

All of that seems a bit convoluted, so I suggest we just move it to ProgramData with the rest of Jackett - #13875

**Comment by ilike2burnthing** [comment] 2023-01-07 21:31
@Atario new release will be out in ~8.5hrs.

When you've installed it (or now if you want), within the `Jackett` folder create a `cardigann` folder, and within that a `definitions` folder:

```text
C:\ProgramData\Jackett\cardigann\definitions
```

Place any custom indexers in the new `definitions` folder, changing the `id` and `name` if a duplicate of an existing indexer (changing the filename isn't necessary, but is useful for easy identification).

Any time you add or edit an indexer, restart Jackett's service.

Let us know if that solves your issue, considering there's nothing we can really do about SubPlease's lack of information.

**Comment by Atario** [comment] 2023-01-08 02:33
I'm not sure I understand what you mean about SubsPlease not providing the size; looking at the API's results, the magnet link contains the correct size in the usual "xl" parameter for it:

{
  "Nijiyon Animation - 01": {
    "time": "01/06/23",
    "release_date": "Fri, 06 Jan 2023 14:25:53 +0000",
    "show": "Nijiyon Animation",
    "episode": "01",
    "downloads": [
      {
        "res": "480",
        "magnet": "magnet:?xt=urn:btih:TQ54SPMEXBEQBTFQJEEWPBU3SGZ7RHBW&dn=%5BSubsPlease%5D%20Nijiyon%20Animation%20-%2001%20%28480p%29%20%5BBCC67016%5D.mkv&**_xl=60820463_**&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fretracker.lanta-net.ru%3A2710%2Fannounce&tr=http%3A%2F%2Fopen.acgnxtracker.com%3A80%2Fannounce&tr=wss%3A%2F%2Ftracker.openwebtorrent.com"
      },
      {
        "res": "720",
        "magnet": "magnet:?xt=urn:btih:WBBVJPZ5HZGGNOVLXE7GSP45LFL7XWAV&dn=%5BSubsPlease%5D%20Nijiyon%20Animation%20-%2001%20%28720p%29%20%5BF715C02A%5D.mkv&**_xl=113032710_**&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fretracker.lanta-net.ru%3A2710%2Fannounce&tr=http%3A%2F%2Fopen.acgnxtracker.com%3A80%2Fannounce&tr=wss%3A%2F%2Ftracker.openwebtorrent.com"
      },
      {
        "res": "1080",
        "magnet": "magnet:?xt=urn:btih:QUNY5BDYDNIZ326CQIHPVILEZOYRIJUL&dn=%5BSubsPlease%5D%20Nijiyon%20Animation%20-%2001%20%281080p%29%20%5B82D0C660%5D.mkv&**_xl=214209376_**&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fretracker.lanta-net.ru%3A2710%2Fannounce&tr=http%3A%2F%2Fopen.acgnxtracker.com%3A80%2Fannounce&tr=wss%3A%2F%2Ftracker.openwebtorrent.com"
      }
    ],
    "xdcc": "%22%5BSubsPlease%5D+Nijiyon+Animation+-+01%22",
    "image_url": "/wp-content/uploads/2023/01/131434.jpg",
    "page": "nijiyon-animation"
  }
}

**Comment by garfield69** [comment] 2023-01-08 02:41
>looking at the API's results, the magnet link contains the correct size in the usual "xl" parameter for it:

That's a good find.  👍 
Most other sites don't provide an &xl on the magnet link so no one went looking for it.
I'll have a go and see if I can make use of in in the indexer.

**Closed** 2023-01-08 03:16 UTC

**Comment by garfield69** [comment] 2023-01-08 06:06
v0.20.2593
