### ISSUE TITLE
[demonoid] Clearance failed after 30 attempt(s). (Config)

### ISSUE THREAD

**Issue by klaypigeon** [Jackett/Jackett#8376] opened 2020-04-26 17:12 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

**Jackett Version**: v0.16.137

**Last Working Jackett Version**: v0.16.137

No for 80/443

### Description

Add indexer to Jackett

### Logged Error Messages

2020-04-26 13:09:33 | Error | CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in d:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2NetCore.cs:line 229    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in d:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 114    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 438    at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 793    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 982    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
-- | -- | --

**Comment by klaypigeon** [comment] 2020-04-26 17:18
I have most current release, it still does not work.

**Comment by klaypigeon** [comment] 2020-04-26 17:19
Also chaining issues is messy. Pick a master issue and relate them all to that. You just related mine to another issue that is closed that is related to yet another issue. messy messy.

**Comment by cadatoiva** [comment] 2020-04-26 18:43
@klaypigeon our issue tracker only checks the previous 30 days and selects the oldest issue when checking for duplicates. Sometimes, this means that you get issue chaining, but only for specific and fairly rare use cases in our issue tracker. (specifically, an ongoing or intermittent issue lasting longer than 30 days with duplicate issue reporting being more frequent than 30 days)

This has been deemed preferable to closing issues as duplicates for unrelated issues from very old versions, leading to comments of "it's back" when it's actually a completely different cause.

**Comment by MammothJerk** [comment] 2020-04-26 19:37
Jackett Version 0.16.127.0 

still getting the issue, from #8153 if you get the cookie from your user page this issue disappears.
thing is you can no longer sign up for a demonoid account

**Comment by cadatoiva** [comment] 2020-04-26 20:11
Looking back at the old ticket conversation, this is a duplicate of that one, and was the master issue for the cookie bug. Your pooh poohing was not justified in this instance, as it wasn't an issue chain, but a false duplicate claim by the bot. 

Please see the fix in https://github.com/Jackett/Jackett/issues/8153#issuecomment-612702113 to resolve the issue.

**Closed by cadatoiva** 2020-04-26 20:11 UTC
Labels: Duplicate
