### ISSUE TITLE
[anidex] Found no results while trying to browse

### ISSUE THREAD

**Issue by T0MM-git** [Jackett/Jackett#6868] opened 2020-01-08 08:42 UTC
anidex is not working. can access manually. added to sonarr and cannot browse
[log.txt](https://github.com/Jackett/Jackett/files/4034257/log.txt)

**Comment by garfield69** [comment] 2020-01-08 19:24
duplicate of #6834
Anidex have enabled DDoS protection. there is no current solve for this.

**Closed by garfield69** 2020-01-08 19:24 UTC
