### ISSUE TITLE
[rarbg] Exception (rarbg): Error parsing Infinity value.

### ISSUE THREAD

**Issue by ceejayz711** [Jackett/Jackett#2761] opened 2018-03-21 07:03 UTC
Path '', line 1, position 2.: Error parsing Infinity value. Path '', line 1, position 2. (Test)

**Jackett version**:  0.8.770.0
**Mono version** (if not using Windows):  5.10.0.160

-------------------------------

**Comment by garfield69** [comment] 2018-03-21 07:11
Duplicate of #2753

**Closed by garfield69** 2018-03-21 07:11 UTC
