### ISSUE TITLE
[tvchaosuk] Exception (tvchaosuk): String was not recognized as a valid DateTime.: Parse error (Test)

### ISSUE THREAD

**Issue by antigravity83** [Jackett/Jackett#2963] opened 2018-04-12 05:28 UTC
Jackett Version 0.8.870.0
Mono Version 5.10.1.20

Can't connect to TVChaosUK anymore

Logs: https://gist.github.com/antigravity83/e7bdb60ec5b2b4c31a69251ca63c2dc1

**Comment by garfield69** [comment] 2018-04-12 06:01
Duplicate of #2961
There was a fix for tvchaosuk in v0.8.881 so upgrade.

**Closed by garfield69** 2018-04-12 06:01 UTC
Labels: Duplicate

**Comment by antigravity83** [comment] 2018-04-12 07:14
Thanks- upgrade in GUI mustn't have been working. Manually upgraded and working now. Thanks!
