### ISSUE TITLE
[req]: Add possibility to remove category from search on indexer

### ISSUE THREAD

**Issue by razeNFR** [Jackett/Jackett#15561] opened 2024-08-28 13:30 UTC
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Sorry my english is very bad, so i will use Google Translate : 

I would like to know if it is possible to add an option to remove certain categories from the search in the indexers.

Because I noticed that when I do a search on an indexer I have results in the Console/Audio/Books category, and I would like to know if it is possible to remove these categories from the search, I have already searched but found nothing conclusive.

### Describe the solution you'd like

If possible, add an option in the indexer configuration to remove certain categories from the search

### Describe alternatives you've considered

The only alternatives i considered is using Prowlarr, but i prefer Jackett

**Comment by garfield69** [comment] 2024-08-28 19:30
I am not sure if I have understood your question.
If you are using the Jackett dashboard to do a manual search with an indexer, simply select only the categories that you _do want_ to see results for. The category pull down on the right hand side defaults to any, but you can select however many cats you wan to use.
if you are using an *arr app then edit that apps indexer and select only those categories you want to see from the list provided by that *arr app.

Choose the cats you want to see is the same as choosing the cats you do not want to see, so there is little point providing both options.

**Comment by razeNFR** [comment] 2024-08-28 23:45
> I am not sure if I have understood your question. If you are using the Jackett dashboard to do a manual search with an indexer, simply select only the categories that you _do want_ to see results for. The category pull down on the right hand side defaults to any, but you can select however many cats you want to use. if you are using an *arr app then edit that apps indexer and select only those categories you want to see from the list provided by that *arr app.
> 
> Choose the cats you want to see is the same as choosing the cats you do not want to see, so there is little point providing both options.

I use addon like Jackettio or Comet on Stremio and sometimes Jackettio found Audio file from movie, because he search in audio category, and i dont know if i can disable in jackett the possibility to search in audio category

Sorry my english is very bad i hope you understand me

**Comment by ilike2burnthing** [comment] 2024-08-28 23:51
If the issue is not with a dashboard search, then it sounds like a request you need to make for devs of those addons, if it's not something they already provide. We won't be adding a setting to remove specific categories from all search results.

**Closed by ilike2burnthing** 2024-08-28 23:51 UTC
