### ISSUE TITLE
torrentz2: got redirected to another domain

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11364] opened 2021-03-20 18:54 UTC
Configure: https://torrentz.unblockit.buzz/
I redirects to a bad domain.
Got redirected to another domain. Try changing the indexer URL to https://unblockit.buzz/

**Comment by garfield69** [comment] 2021-03-20 22:07
closed as a duplicate of #1040
site is offline

**Closed by garfield69** 2021-03-20 22:07 UTC
