### ISSUE TITLE
Jackett stops working after 2 days

### ISSUE THREAD

**Issue by maxtheking** [Jackett/Jackett#4279] opened 2018-12-05 00:08 UTC
I'm running Jackett version 0.10.475.0 with Mono version 5.16.0.220 on a Linux Debian 9 x64 VM. It all works fine, except for the fact that Jackett stops responding after about 2 days (Can't access the web UI, doesn't process requests), and refuses to come back online until i restart the entire VM. The logs don't list anything unusual, see the image below.
![logs1](https://user-images.githubusercontent.com/43993269/49481176-f30f1680-f829-11e8-887a-813ae9b15d73.JPG)

23:12:02 is the time Jackett became unresponsive, 00:44:10 is the time i manually rebooted the VM to get Jackett working again. Any ideas about what could cause this behaviour? Other services running on the same VM (Sonarr/Radarr, which also use Mono) continue working fine when Jackett crashes.

**Comment by garfield69** [comment] 2018-12-05 01:08
looking at open issues there is an ongoing problem with users of the mejortorrent indexer, do you use this site?

**Comment by maxtheking** [comment] 2018-12-05 13:40
@garfield69 Nope, don’t use that indexer

**Comment by samip5** [comment] 2018-12-05 16:22
I can confirm this problem. Same problem for me.

**Comment by garfield69** [comment] 2018-12-05 16:41
@kaso17  @flightlevel  any ideas what might be going on with this issue?

**Comment by kaso17** [comment] 2018-12-05 16:56
Please run jackett with the -t and -l command line options:
`mono --debug JackettConsole.exe -tl`
Make sure you're capturing the stderr output (e.g. via systemd/journalctl)
Once it get's stuck please send a QUIT signal to the mono process (`killall -QUIT mono`) that will dump the stack traces to stderr (not the log file) and post them.

There haven't been any major changes at the jackett core code which would explain this.
I currently would suspect an issue with mono 5.16.0.220.

**Comment by samip5** [comment] 2018-12-05 19:16
> Please run jackett with the -t and -l command line options:
> `mono --debug JackettConsole.exe -tl`
> Make sure you're capturing the stderr output (e.g. via systemd/journalctl)
> Once it get's stuck please send a QUIT signal to the mono process (`killall -QUIT mono`) that will dump the stack traces to stderr (not the log file) and post them.
> 
> There haven't been any major changes at the jackett core code which would explain this.
> I currently would suspect an issue with mono 5.16.0.220.
> 
> If you can downgrade mono to a previous version I would suggest to try that.

How would I capture the stderr output on Docker?

**Comment by maxtheking** [comment] 2018-12-11 17:49
Just created a cronjob which restarts jacket every day, works for now...

**Comment by pkmetski** [comment] 2018-12-15 12:01
I had a similar issue recently.The problem for me was that Sonarr's category list was too long and it was crashing Jackett. The issue was resolved after I removed some categories.

**Comment by kaso17** [comment] 2018-12-15 13:56
@pkmetski can you share the query URL generated by sonarr which crashed jackett?

**Comment by pkmetski** [comment] 2018-12-15 14:14
@kaso17 Sure, here you go:
`http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab?t=tvsearch&cat=5000,5030,5040,5050,5060,5070,5080,7000,7010,100001,100004,100005,100006,100007,100008,100009,100014,100015,100018,100019,100020,100024,100029,100041,100049,100050,100072,100077,100108,100109,100110,100111,100112,100113,100114,100115,100116,100117,100118,100119,100120,100121,100122,100123,100124,100125,100127,100128,100129,100130,100131,100132,100133,100134,100135,100137,100138,100139,100140,100141,100144,100147,100148,100152,100153,100155,100157,100159,100163,100165,100166,100167,100168,100169,100170,100171,100172,100173,100174,100175,100176,100177,100178,100179,100180,100181,100182,100183,100184,100185,100186,100187,100188,100189,100190,100191,100192,100193,100194,100196,100197,100198,100199,100200,100201,100202,100203,100204,100205,100206,100207,100208,100209,100210,100211,100212,100213,100214,100215,100216,100217,100218,100219,100220,100221,100222,100223,100224,100225,100226,100227,100228,100229,100234,100235,100236,100237,100238,100239,100240,100241,100242,100243,100244,100245,100246,100247,100248,100249,100250,100251,100252,100253,100254,100255,100256,100257,100258,100259,100260,100261,100262,100263,100264,100265,100266,100268,100269,100270,100271,100272,100273,100274,100275,100276,100277,100278,100279,100280,100281,100282,100283,100284,100285,100286,100287,100288,100289,100290,100291,100292,100293,100294,100295,100296,100297,100298,100299,100300,100301,100302,100303,100304,100308,100309,100310,100311,100312,100313,100314,100315,100316,100317,100319,100320,100321,100322,100323,100324,100325,100326,100327,100328,100329,100330,100331,100332,100333,100334,100335,100336,100337,100338,100339,100340,100341,100342,100343,100344,100345,100346,100347,100348,100349,100350,100351,100353,100354,100355,100356,100357,100358,100359,100361,100362,100363,100364,100365,100366,100368,100369,100370,100372,100373,100375,100376,100378,100379,100380,100381,100382,100383,100384,100386,100387,100388,100390,100392,100393,100394,100396,100398,100399,100400,100401,100402,100404,100405,100406,100408,100409,100410,100411,100412,100414,100423,100424,100425,100427,100435,100460,100503,100504,100510,100528,100555,100556,100559,100560,100561,100562,100563,100565,100566,100567,100568,100569,100570,100571,100572,100573,100574,100575,100576,100577,100578,100579,100580,100581,100582,100583,100584,100585,100586,100587,100588,100590,100591,100593,100594,100595,100596,100597,100598,100599,100604,100605,100606,100607,100608,100609,100610,100611,100612,100613,100614,100615,100616,100617,100618,100619,100629,100630,100631,100632,100633,100634,100635,100636,100637,100638,100639,100640,100642,100643,100644,100645,100646,100647,100648,100649,100650,100651,100652,100654,100655,100656,100657,100658,100659,100661,100662,100663,100664,100665,100666,100667,100668,100669,100670,100672,100673,100674,100675,100676,100677,100678,100679,100680,100681,100682,100683,100684,100685,100686,100687,100688,100689,100690,100691,100692,100693,100694,100695,100696,100697,100698,100699,100702,100703,100704,100705,100706,100707,100708,100709,100710,100711,100712,100713,100714,100715,100716,100717,100718,100719,100720,100721,100722,100723,100725,100726,100727,100728,100729,100730,100731,100732,100733,100734,100735,100736,100737,100738,100739,100740,100741,100753,100754,100755,100756,100757,100758,100759,100760,100761,100762,100763,100764,100765,100766,100767,100768,100769,100770,100771,100772,100773,100774,100775,100776,100777,100778,100781,100782,100783,100784,100785,100786,100787,100788,100789,100790,100791,100792,100793,100794,100795,100796,100797,100798,100799,100800,100801,100802,100803,100807,100808,100810,100812,100813,100814,100815,100816,100817,100818,100819,100820,100821,100822,100823,100824,100825,100826,100827,100828,100829,100830,100831,100832,100833,100834,100835,100836,100837,100838,100839,100840,100841,100842,100843,100844,100845,100846,100847,100849,100853,100854,100855,100856,100857,100858,100859,100860,100861,100862,100863,100864,100865,100866,100867,100868,100869,100870,100871,100872,100873,100875,100876,100877,100878,100879,100880,100881,100882,100883,100884,100885,100886,100887,100888,100889,100890,100891,100892,100893,100894,100895,100896,100897,100898,100899,100900,100901,100902,100903,100904,100905,100906,100907,100908,100909,100910,100911,100912,100913,100914,100915,100916,100917,100918,100919,100920,100921,100922,100923,100924,100925,100926,100927,100928,100929,100930,100931,100932,100933,100934,100935,100936,100937,100938,100939,100940,100941,100942,100944,100945,100946,100954,100955,100956,100957,100965,100966,100967,100968,100969,100973,100979,100980,100981,100982,100983,100984,100985,100986,100987,100988,100989,100991,100992,100993,100994,100995,100996,100998,100999,101001,101025,101026,101027,101028,101029&extended=1&apikey=(removed)&offset=0&limit=1000&q=(removed)&season=(removed)`

**Comment by pkmetski** [comment] 2018-12-15 15:41
@kaso17 Might be a combination of the categories and trackers configured.
This query always crashes Jackett (at lest on Sonarr end - the indexer has to be "re-tested" in order to be functional again):

`http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab?t=tvsearch&cat=5000,5030,5040,5050,5060,5070,5080,7000,7010,100001,100004,100005,100006,100007,100008,100009,100014,100015,100018,100019,100020,100024,100029,100041,100049,100050,100072,100077,100108,100109,100110,100111,100112,100113,100114,100115,100116,100117,100118,100119,100120,100121,100122,100123,100124,100125,100127,100128,100129,100130,100131,100132,100133,100134,100135,100137,100138,100139,100140,100141,100144,100147,100148,100152,100153,100155,100157,100159,100163,100165,100166,100167,100168,100169,100170,100171,100172,100173,100174,100175,100176,100177,100178,100179,100180,100181,100182,100183,100184,100185,100186,100187,100188,100189,100190,100191,100192,100193,100194,100196,100197,100198,100199,100200,100201,100202,100203,100204,100205&extended=1&apikey=(removed)&offset=0&limit=1000&q=Its%20Always%20Sunny%20in%20Philadelphia&season=9`

**Comment by samip5** [comment] 2018-12-30 22:54
How do I get the Sonarr's long query with all the categories? @pkmetski

**Comment by pkmetski** [comment] 2018-12-31 10:40
@samip5 I've compiled the list manually from my configured indexers at the time. Not all categories are valid for all indexers.

**Comment by jryburn** [comment] 2019-04-04 14:29
I have a somewhat similar issue where Jackett will stop accepting API calls after about 24-48 hours. The timing seems to very. Below is what is in the logs:

`Jackett.Common.IndexerException: Exception (kickasstorrent): The operation was canceled. ---> System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClientNetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs:line 214
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1229
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 367`

**Comment by maxtheking** [comment] 2019-04-04 16:43
@jryburn I managed to get it working again by manually downgrading to Mono version 5.14.0.177.

**Comment by jryburn** [comment] 2019-04-04 20:59
Hmm. I am running this in a pre-built docker container so that might be hard to do. I will give it a shot though.

**Comment by weikinhuang** [comment] 2019-04-07 18:45
I am also experiencing this issue with https://github.com/linuxserver/docker-jackett ever since they switched to .net core from mono. Sonarr would say:
```
All search-capable indexers are temporarily unavailable due to recent indexer error
```

log of error:
```
04-07 13:46:49 Error Jackett.Common.IndexerException: Exception (nyaasi): Operation canceled ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudFlareUtilities.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClientNetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs:line 222
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1229
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 367 Jackett.Common.IndexerException: Exception (nyaasi): Operation canceled ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudFlareUtilities.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClientNetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs:line 222
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1229
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 367
```

**Comment by ngosang** [comment] 2020-01-20 23:27
@ all I need more info to work in this issue. I can't reproduce.
Did you manage to fix the problem? Can you try the latest version?

**Comment by samip5** [comment] 2020-01-20 23:29
I haven't had this problem in a while anymore.

Running Jackett version 0.12.1590.0.

**Comment by ngosang** [comment] 2020-01-21 21:07
It's working for at least 3 users. I'm closing.
If someone else is having this problem, please open a new issue and link to this one.

**Closed by ngosang** 2020-01-21 21:07 UTC
Labels: Linux / Mono, More information needed
