### ISSUE TITLE
Jackett Grabbing old RSS feed

### ISSUE THREAD

**Issue by Coax88** [Jackett/Jackett#5715] opened 2019-07-23 15:36 UTC
Hi
i have an issues with jackett grabbing old content in the RSS feed. i'm using 0.11.507.0 with Danishbits as indexer

**Comment by garfield69** [comment] 2019-07-23 23:11
this is a duplicate of #2657
its to do with the danishbits site which forces us to use their couchpotato API which is nbg.
follow that ticket for progress, of which there isn't any :-(

**Closed by garfield69** 2019-07-23 23:11 UTC
