### ISSUE TITLE
Jackett crashes after some time [Docker]

### ISSUE THREAD

**Issue by samip5** [Jackett/Jackett#4283] opened 2018-12-05 16:43 UTC
**Jackett version**:  0.10.479.0
**Mono version** (if not using Windows):  5.16.0.220

1. Start jackett container.
2. Use it normally.
3. After a 12 or 24 hours try to use it again and it wont work.

**Comment by kaso17** [comment] 2018-12-05 16:58
I assume it's a dupe of #4279

**Closed by kaso17** 2018-12-05 16:58 UTC
