### ISSUE TITLE
[1337x] Exception (1337x): The remote certificate is invalid according to the validation procedure.: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by korn360** [Jackett/Jackett#2294] opened 2017-12-16 20:06 UTC
error when adding 1337x as indexer. No other indexers setup.

**Comment by garfield69** [comment] 2017-12-17 01:24
I don't have any problems adding 1337x to my win7 Jackett Dashboard.
If you ar enot in windows, the this is often caused by missing/outdated CA certificates.
  Try reimporting the certificates in this case:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
    or `sudo wget -O - https://curl.haxx.se/ca/cacert.pem | sudo cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`
  - On QNAP refer to #2111

and reboot (or just restart all Jackett services) after the imports are completed.

**Comment by garfield69** [comment] 2018-01-25 04:25
no reply, presumably resolved. Closing.

**Closed by garfield69** 2018-01-25 04:25 UTC
