### ISSUE TITLE
[lostfilm] Exception (lostfilm): Object reference not set to an instance of an object.: Parse error (Test)

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#9054] opened 2020-06-26 04:31 UTC
### Environment

**OS**: Docker container for linuxserver

**Jackett Version**: 0.16.767.0

**Are you using a proxy or VPN?**: VPN

### Description

This error happens when I'm trying to make a test for lostfilm: [lostfilm] Exception (lostfilm): Object reference not set to an instance of an object.: Parse error (Test). Tracker itself works fine. Not a network issue.

### Logged Error Messages
`{0} Jackett.Common.IndexerException: Exception (lostfilm): Object reference not set to an instance of an object.
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.LostFilm.FollowTrackerRedirection(String url, TrackerUrlDetails details) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 669
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 831
   at Jackett.Common.Indexers.LostFilm.FollowTrackerRedirection(String url, TrackerUrlDetails details) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 755
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 644
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 831
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 648
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 447
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 831
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 459
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 406
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 831
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 412
   at Jackett.Common.Indexers.LostFilm.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 203
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 347
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 347
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 808
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 274
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70`

**Comment by Un1QExit** [comment] 2020-06-26 05:24
Have a same problem

**Comment by garfield69** [comment] 2020-06-26 05:47
This occurs because lostfilm is blocking your IP.
Use a VPN to allocate an IP address outside of your region.
I find Canadian IP addresses work currently for me for this indexer.

**Comment by SuberSeb** [comment] 2020-06-26 05:49
> Use a VPN to allocate an IP address outside of your region.

I'm using VPN and if I execute wget from container console it works fine. Problem only in Jackett.

**Comment by garfield69** [comment] 2020-06-26 06:01
the indexer works for me which suggests the issue is at your end.
turn on **full enhanced** logging, maybe the extra debug and HTML in the log will provide additional info to explain your issue.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment] 2020-06-26 06:09
seeing this now too. getting parse error.
[ParseError.txt](https://github.com/Jackett/Jackett/files/4835336/ParseError.txt)

**Comment by SuberSeb** [comment] 2020-06-26 06:10
@garfield69 but if I execute "wget lostfilm.tv" from container console I will get lostfilm page which means that tracker is accessible. I will provide logs soon

**Comment by ngosang** [comment] 2020-07-06 21:41
@garfield69 I can't reproduce the issue.

**Comment by garfield69** [comment] 2020-07-07 00:34
yeah well it was 11 days ago and the keywordless search is working for me too now.
all we have go to work with is the debug log I snapped at the time.
up to you if you just want to close it and wait for another hit.

**Comment by ngosang** [comment] 2020-10-15 18:50
I think this bug is already fixed. I just tested the indexer and the html attached by @garfield69 and its working.

**Closed by ngosang** 2020-10-15 18:50 UTC
Labels: Confirmed, Needs C#
