### ISSUE TITLE
OpenSSL 1 still in use. Upgrade to OpenSSL 3 ?

### ISSUE THREAD

**Issue by Locutus64** [Jackett/Jackett#13811] opened 2022-12-26 19:37 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
N/A
```

### Description

I was just in the Manjaro forums and was wondering why Jackett is still on OpenSSL 1 instead of 3?

https://forum.manjaro.org/t/openssl-build-problem/130167/2

### Logged Error Messages

```text
N/A
```

**Comment by ilike2burnthing** [comment] 2022-12-27 06:50
Pretty sure it doesn't, as stated in that thread - https://forum.manjaro.org/t/openssl-build-problem/130167/7

**Comment by Locutus64** [comment] 2022-12-27 11:20
Are you saying Jackett isn't 1.0 as stated in the thread on Manjaro's forums? If so you are wrong. Read the out put from Konsole I posted and tell me that again.

**Comment by bakerboy448** [comment] 2022-12-27 13:00
https://forum.manjaro.org/t/openssl-build-problem/130167/11

the AUR pkg does not use nor require OpenSSL-1.0 there's no issue for Jackett to resolve here
https://aur.archlinux.org/cgit/aur.git/commit/?h=jackett&id=e7a785240682700e8a7d34cb9e8e2b746dfffd0d

**Comment by garfield69** [comment] 2022-12-27 17:54
Closing. The issue is unrelated to the Jackett that is maintained by this group.

**Closed by garfield69** 2022-12-27 17:54 UTC
Labels: Question
