### ISSUE TITLE
[blutopia] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by yllanos** [Jackett/Jackett#4271] opened 2018-12-03 23:00 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.9.41.0
**Mono version** (if not using Windows):  

-------------------------------

**Comment by bwirt** [comment] 2018-12-04 02:43
+1

**Comment by garfield69** [comment] 2018-12-04 05:06
seriously guys, you cannot expect us to support 0.8 or 0.9 versions of jackett.
the blutopia indexer has had multiple updates since your releases came out.
please try to upgrade to the latest version 0.10.492.
then if blutopia still does not work for you, provide an enhanced log as described in the template above so we can take a closer look.
thanks.

**Comment by bwirt** [comment] 2018-12-05 01:45
I agree of course.  Apologies, for some reason I thought that was very recent version.

Confirmed this is now working once I did the update.  I feel you can close this issue.

Appreciate this project!

**Closed** 2018-12-05 16:17 UTC
Labels: More information needed
