### ISSUE TITLE
[passthepopcorn] Not downloading .torrent files and getting temporary ip ban after trying | Release URL links to movie's homepage, not actual release

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#8927] opened 2020-06-09 08:22 UTC
Idk if the problem is with Jackett or with ptp..
Can download them from the site normally

2020-06-09 10:48:52 | Error | Failed download response: Your popcorn quota has been reached, come back later!
-- | -- | --
2020-06-09 10:48:52 | Error | Failed download cookies: __cfduid=removed; PHPSESSID=removed
2020-06-09 10:48:52 | Error | Error downloading passthepopcorn https://passthepopcorn.me/torrents.php?action=download&id=190202&authkey=&torrent_pass=
2020-06-09 10:48:51 | Error | On attempt 3 downloading from PassThePopcorn: Clearance failed after 10 attempt(s).
2020-06-09 10:48:45 | Error | On attempt 2 downloading from PassThePopcorn: Clearance failed after 10 attempt(s).
2020-06-09 10:48:37 | Error | On attempt 1 downloading from PassThePopcorn: Clearance failed after 10 attempt(s).

Jackett Version 0.16.650.0
Not using proxy or VPN

Also maybe there's no need to make so many attempts. That likely causes ip ban. Maybe just 1 or 2 would be enough instead of 30

**Comment by RoloSoze** [comment] 2020-06-09 14:29
I can also confirm that this is a problem I have been facing for a while. @cadatoiva Since you're a PTP member, are you able to download a torrent via Jackett? I suspect you cannot like me & @janot.

**Comment by RoloSoze** [comment] 2020-06-09 21:36
@janot I also added the fact that the URL for any given release you find on PTP via Jackett takes you to the movie's homepage instead of the release's Permalink (PL).

@cadatoiva Can this also be fixed?

**Comment by cadatoiva** [comment] 2020-06-11 20:45
They likely made some changes to their API. I'm busy being elbows deep in a different project before I can work on this. I did notice this is about a month old because I haven't been able to download anything from PTP for a while with it always resulting in a soft IP ban every attempt.

**Comment by RoloSoze** [comment] 2020-06-11 21:15
@cadatoiva That, and the issue of not linking straight to the selected release's Permalink. You're the only C# developer who's a member of PTP, so we'll just have to wait.

**Comment by cadatoiva** [comment] 2020-06-12 02:30
Should be able to have it fixed this weekend.

**Comment by RoloSoze** [comment] 2020-06-12 02:32
> 
> 
> Should be able to have it fixed this weekend.

@cadatoiva Thank you. Any progress on #7923?

**Comment by ngosang** [comment] 2020-06-21 10:17
If someone invites me I can take a look. If not we have to wait for @cadatoiva

**Comment by RoloSoze** [comment] 2020-07-06 21:03
> 
> 
> Should be able to have it fixed this weekend.

Any chance you got around to working on this, @cadatoiva?

**Comment by cadatoiva** [comment] 2020-07-14 00:42
Sorry, nothing yet @RoloSoze. Still having trouble finding enough free time to dive in deep for Jackett on the whole.

**Comment by seeyabye** [comment] 2020-09-12 00:43
@RoloSoze Is this problem still occurring? 

Tested on my end and it seems to be working fine.

**Comment by RoloSoze** [comment] 2020-09-12 08:58
@seeyabye Yes, both problems still exist for me.

**Comment by RoloSoze** [comment] 2020-09-12 08:59
> 
> 
> Should be able to have it fixed this weekend.

@cadatovia Any chance you'll ever have time to work on this?

**Comment by seeyabye** [comment] 2020-09-12 09:26
I would like to help, but I can't replicate this problem.

**Comment by RoloSoze** [comment] 2020-09-12 09:48
> 
> 
> @cadatoiva That, and the issue of not linking straight to the selected release's Permalink. You're the only C# developer who's a member of PTP, so we'll just have to wait.

@seeyabye Maybe you could solve this other issue then?

**Comment by RoloSoze** [comment] 2020-09-12 09:49
> 
> 
> @janot I also added the fact that the URL for any given release you find on PTP via Jackett takes you to the movie's homepage instead of the release's Permalink (PL).
> 
> @cadatoiva Can this also be fixed?

@seeyabye Maybe you could solve this other issue then?

**Comment by seeyabye** [comment] 2020-09-12 10:17
@RoloSoze done.

**Comment by ngosang** [comment] 2020-09-13 17:16
The next release (tomorrow) will include a fix for this. Could someone confirm that it works?

**Comment by garfield69** [comment] 2020-09-14 07:02
Jackett 0.16.1204

**Comment by RoloSoze** [comment] 2020-09-14 09:17
Thanks, guys! One part of the problem has now been resolved, which is linking straight to the Permalink. However, the other problem still exists, which is the fact that trying to download the .torrent file via Jackett causes an IP ban. 

You can't visit PTP's website for a while after that. If you do, you get the following message, 
`"Your popcorn quota has been reached, come back later!`

Therefore, I need to reopen this ticket until the issue is resolved.

**Comment by seeyabye** [comment] 2020-09-14 09:43
@RoloSoze I may have a fix, but I can't test it as I can't replicate this problem.

Are you able to test it if I submit it as a PR? You will need to compile it by yourself.

Otherwise, I can build a docker binary for you to pull and test it.

**Comment by RoloSoze** [comment] 2020-09-14 09:51
The only way I know how to test PRs is by downloading the .exe of the draft release from the Azure Pipelines. If I can do that, I can test your fix.

**Comment by seeyabye** [comment] 2020-09-14 10:03
In that case, please give this binary a try.

https://drive.google.com/file/d/1gO0mbBz-p3YIfm5uV7wQ6suj08gIb2Ix/view?usp=sharing

I recommend making a backup of `C:\ProgramData\Jackett` beforehand.

**Comment by ngosang** [comment] 2020-09-14 10:12
@seeyabye please, don't distribute executables in hosting services. We can download the compiled binaries from the PRs. Go to https://dev.azure.com/Jackett/Jackett/_build?definitionId=1&_a=summary
Find your PR, click in "1 artifact" and download the "drop" artifact.
![imagen](https://user-images.githubusercontent.com/10577978/93073598-71494f80-f683-11ea-9130-2e1339a24292.png)
![imagen](https://user-images.githubusercontent.com/10577978/93073627-7c03e480-f683-11ea-9869-9fa91e7cab84.png)

**Comment by seeyabye** [comment] 2020-09-14 10:13
@ngosang sorry. I've removed the link. I will submit it as a PR as per your suggestion.

**Comment by RoloSoze** [comment] 2020-09-14 10:22
I will test the fix one my IP ban is lifted; I still cannot access PTP. It'll take a few hours. Thank you for your work, @seeyabye!

**Comment by RoloSoze** [comment] 2020-09-14 14:24
@seeyabye OK so I tried your fix. I'm still unable to download the .torrent file via Jackett, but at least I'm not getting a temporary ban now. Here's the enhanced log in case it's helpful. @ngosang You might want to look at this, too. It seems like it's a Cloudflare issue?

[log.txt](https://github.com/Jackett/Jackett/files/5219051/log.txt)

**Comment by ngosang** [comment] 2020-09-14 17:47
> https://passthepopcorn.me/torrents.php?action=download&id=749704&authkey=&torrent_pass= 

did you remove the authkey and torrent_pass ?

**Comment by RoloSoze** [comment] 2020-09-14 17:57
@ngosang Are you talking to me or @seeyabye?

**Comment by garfield69** [comment] 2020-09-14 18:52
@RoloSoze  to clarify, usually when redacting you replace existing info with a dummy filler (and nor remove the value completely), so the question was:
in the string in the log you provided `https://passthepopcorn.me/torrents.php?action=download&id=749704&authkey=&torrent_pass=` did the authkey and torrentpass have values or did you remove them from the log during redacting?

because if the string looked something like `https://passthepopcorn.me/torrents.php?action=download&id=749704&authkey=***authkeyredacted**&torrent_pass=**passredacted**`  then we know they were present, but if it really did looked like `https://passthepopcorn.me/torrents.php?action=download&id=749704&authkey=&torrent_pass=`  then either the indexer config has not had these filled in (meaning your config needs updating), or the indexer code is not loading these values before posting the query, indicating an issue with coding (assuming they are supposed to be present ;-).

**Comment by seeyabye** [comment] 2020-09-15 00:08
@RoloSoze I agree with what @ngosang and @garfield69 said.

Can you be certain that at least `torrent_pass` is not empty?

I have rechecked the download request. 
Strangely, I did not need `authkey`, and I could download the torrent file without any problems (using vanilla curl without any cookies and authorization header).

However, `authkey`'s value was missing in the original code and I've corrected it in the updated PR (https://github.com/Jackett/Jackett/pull/9532). If you don't mind, could you please test this out again? In this update, user's input for `passkey` is no longer required since PTP provides it.

**Comment by RoloSoze** [comment] 2020-09-30 16:03
I'll test the PR tonight, and will get back to you guys on this issue. Thanks again!

**Comment by RoloSoze** [comment] 2020-09-30 22:19
PR works fine for me! Once merged, this can be closed! Thank you all once again!

**Closed** 2020-10-01 00:34 UTC
Labels: Confirmed, Help wanted, Invite needed, Needs C#

**Comment by garfield69** [comment] 2020-10-01 06:02
Jackett 0.16.1472

**Comment by Quiksmage** [comment] 2022-01-11 05:03
Hi, I appear to be having this issue with Jackett Version v0.20.280

Searching gives results, but as soon as I try to download, I'm quota banned.
It's possible that the search itself got me banned, but I can't tell. I'll test when my quota resets.


'''
Error on 20220111044816 for PassThePopcorn.txtNewtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: M. Path '', line 0, position 0.    at Newtonsoft.Json.JsonTextReader.ParseValue()    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 130     Malformed Api Credentials
--
'''

'''
Jackett.Common.IndexerException: Exception (passthepopcorn): Unexpected character encountered while parsing value: M. Path '', line 0, position 0.  ---> System.Exception: Parse error  ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: M. Path '', line 0, position 0.    at Newtonsoft.Json.JsonTextReader.ParseValue()    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 130    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 781    at Jackett.Common.Indexers.PassThePopcorn.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/PassThePopcorn.cs:line 265    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 758    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 432
--
'''
