### ISSUE TITLE
[thepiratebay] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by cocokola** [Jackett/Jackett#1714] opened 2017-08-24 01:38 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------
seems to have a problem?

**Comment by thebluepotato** [comment] 2017-08-24 16:33
Since it's working fine on my side, I'm guessing you're not using the latest pre-release version of Jackett. Would you be so kind and tell us the version you're using?

**Comment by RubidiumBlade** [comment] 2017-08-30 06:56
I'm also having this issue, I'm on 0.8.128.0

**Comment by kaso17** [comment] 2017-08-30 07:38
TPB is down.
Probably a dupe of #1733

**Closed by kaso17** 2017-08-30 07:38 UTC
Labels: Can't Reproduce, Full logs needed, Invalid
