### ISSUE TITLE
HDCity

### ISSUE THREAD

**Issue by vinanrra** [Jackett/Jackett#8429] opened 2020-04-30 12:27 UTC
Since this commit:

https://github.com/Jackett/Jackett/commit/c18c0d574f4144c5a72ab38bef07c5e925c36556#diff-8ee4a70f1611eb92110a45dc66e2611e

HDCity is flagged as English language with Sonarr always, the problem here it is that it is true that the file contains English and Spanish.

So the files will never download unless you have both activated English and Spanish, because if Sonarr see [English] will be marked as only english.

I think this change should be reverted until it is fixed.

**Comment by ngosang** [comment] 2020-04-30 15:41
@rubasace you did the last change. Could you help us?
None of the Jackett developers have access to this site.

**Comment by rubasace** [comment] 2020-04-30 16:13
@ngosang having a look. I'll come back to you ASAP

**Comment by rubasace** [comment] 2020-04-30 17:18
So, main issue is lack of support for multi-language on Sonarr atm. Comparing  [Radarr parser](https://github.com/Radarr/Radarr/blob/f02fa629ccbd79b1ee9489370f112a89f70fe830/src/NzbDrone.Core/Parser/LanguageParser.cs#L27) to [Sonarr parser](https://github.com/Sonarr/Sonarr/blob/fcdd0f21c7a06de2f144c649fceea5401e941c9a/src/NzbDrone.Core/Parser/LanguageParser.cs#L39) it's obvious that multi-language isn't quite there yet.

The problem with undoing my change is that it will totally break Dual support on Radarr, so it also comes with a price. An intermediate solution, as discussed with @vinanrra, would be to add English to the language profile in Sonarr and add a flag to only allow releases with `Spanish` on the title, via a flag, as suggested on [this Reddit thread](https://www.reddit.com/r/sonarr/comments/fvhbtp/custom_formats_yet_again_multilanguage/). 

Filter for tag Spanish:

![Screenshot 2020-04-30 at 17 56 03](https://user-images.githubusercontent.com/9888880/80739515-82e3ed80-8b0e-11ea-8d0e-fa0e0ee687ab.png)

Add English to profile:
![Screenshot 2020-04-30 at 18 02 23](https://user-images.githubusercontent.com/9888880/80739537-8b3c2880-8b0e-11ea-8201-656d70366ce6.png)

Release will be accepted now.

![Screenshot 2020-04-30 at 17 58 32](https://user-images.githubusercontent.com/9888880/80739607-a870f700-8b0e-11ea-9c46-8b9893845159.png)

**Comment by garfield69** [comment] 2020-05-02 03:12
so if I read this right, the problem was solved within the Sonarr settings and we can close this ticket?

**Comment by rubasace** [comment] 2020-05-02 16:01
AFAIK, that's the case. I'd prefer @vinanrra to close the issue if it's solved though :)

**Comment by vinanrra** [comment] 2020-05-03 13:32
It is okay for me, not the best solution but it is easy to do it.

**Comment by vinanrra** [comment] 2020-06-28 11:32
I am reopening this issue, because unless you use DUAL this set up it is a pain in the ass, i think this should be reverted, because only spanish people are allow on this tracker, and everything here is Spanish unless VOSE that are correctly marked as English.

**Comment by ngosang** [comment] 2020-07-06 21:46
@rubasace None of the Jackett developers have account in this site. You have to agree with @vinanrra

**Comment by rubasace** [comment] 2020-07-07 12:50
@ngosang @vinanrra I've been on holidays, so didn't check anything at all. 

I still don't see the problem with what I suggested. Whoever uses Jackett is into automation and most likely will use it both with Sonarr and Radarr. If they potentially download original versions too, that usually are available on other trackers faster, then they'll have an issue with what @vinanrra  is asking for, as they will lose full control on Dual releases for Radarr.

> I am reopening this issue, because unless you use DUAL this set up it **is a pain in the ass**, i think this should be reverted

That's completely opinionated and not even justified: it's just a one-time configuration when setting up Sonarr, and works seamlessly with Radarr, as opposed to simply not working at all in Radarr if you need Dual support.

>  everything here is Spanish unless VOSE that are correctly marked as English

That's simply not true. VOSE is only English, but whatever isn't flagged is DUAL, as the tracker rules state (and there aren't even Spanish movies or Series, so there's very few content with just Spanish audio).

That being said, I'm fine if you want to revert the change instead of pushing for a fix where the issue is. I'll override the definition on my side and problem solved, so yeah, green flag to revert the change

**Comment by vinanrra** [comment] 2020-07-07 14:24
> 
> 
> @ngosang @vinanrra I've been on holidays, so didn't check anything at all.
> 
> I still don't see the problem with what I suggested. Whoever uses Jackett is into automation and most likely will use it both with Sonarr and Radarr. If they potentially download original versions too, that usually are available on other trackers faster, then they'll have an issue with what @vinanrra is asking for, as they will lose full control on Dual releases for Radarr.
> 
> > I am reopening this issue, because unless you use DUAL this set up it **is a pain in the ass**, i think this should be reverted
> 
> That's completely opinionated and not even justified: it's just a one-time configuration when setting up Sonarr, and works seamlessly with Radarr, as opposed to simply not working at all in Radarr if you need Dual support.
> 
> > everything here is Spanish unless VOSE that are correctly marked as English
> 
> That's simply not true. VOSE is only English, but whatever isn't flagged is DUAL, as the tracker rules state (and there aren't even Spanish movies or Series, so there's very few content with just Spanish audio).
> 
> That being said, I'm fine if you want to revert the change instead of pushing for a fix where the issue is. I'll override the definition on my side and problem solved, so yeah, green flag to revert the change

I dont want just to revert the changes, i want to know if there is a possibility to add some "hacks", because every new user is gonna have problems, unless search at Github your fix, and they will think that Jackett isnt working properly.

**Comment by rubasace** [comment] 2020-07-07 15:12
The main problem here is that Sonarr doesn't support multi-language. I'm not sure about possible hacks (Jackett devs can help here). But anyway, I've already changed my k8s deployment to use a custom `hdcity.yml` so if it works for you, just revert and let's keep an eye on the Sonarr issue till they finally fix their side.

**Comment by ngosang** [comment] 2020-12-21 19:08
Can we close?

**Comment by rubasace** [comment] 2020-12-21 19:16
@ngosang fine for me

**Closed** 2020-12-21 20:02 UTC
