### ISSUE TITLE
xbytes not working well

### ISSUE THREAD

**Issue by Sergiomg86** [Jackett/Jackett#15239] opened 2024-04-12 12:24 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
The client is radarr or sonarr
With Flaresolverr
No proxy
Running in docker? yes
Last version of Jackett
OS: OpenMediaVault 7
```

### Description

I am using the latest version of Jackett in Docker and I have noticed from the beginning that xbytes is not offering the results well, this error is also occurring with prowlarr, I think it is due to the current website or similar 

### Logged Error Messages

```text
I think there is no log in this case
```

**Comment by ilike2burnthing** [comment] 2024-04-12 12:44
None of the active maintainers have an account, so you're going to need to be more descriptive than 'not working well'. Feel free to use Google Translate or DeepL.com if English isn't your first language.

Please provide the actual version number of Jackett (available at the bottom of the webUI), as 'latest' is meaningless, especially when dealing with Docker.

If you have an invite, please send it to `jacketttest [at] gmail [dot] com`

If not, please provide and enhanced log of a test search with xbytes - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ilike2burnthing** [comment] 2024-04-13 00:29
Based on your post on the Prowlarr repo (https://github.com/Prowlarr/Indexers/issues/436), the issue is that irrelevant results are being returned.

From the logs it appears that you've enabled searching for freeleech torrents only. Try disabling that and see if it resolves the issue.

If not, you can try searching for `star wars` on the site itself, with both dead and alive results returned, and sorted by time descending. Does that match what you see in Jackett?

If not, post an enhanced log (link above) and the URL of that search on the site in browser.

**Comment by garfield69** [comment] 2024-04-13 06:30
IF you have already looked at the web sites torrents search page, and if on each of the torrent rows there is no freeleech flag of any kind, then there is nothing the indexer can use to indicate a freeleech in its processed results.
If however you can see such a flag on the torrent rows, let us know by providing an HTML dump of the page, and we can add that detection to the indexer. See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

I will raise an enhancement ticket to see if we can implement global freeleech detection, because this is a common issue across many sites running different engines, and I believe it should be possible to support this with cardigann.

Closing this ticket.

**Comment by garfield69** [comment] 2024-04-13 06:53
Yes, I see that the indexer is out of date, only looking for gold, silver and bronze flags.
I'll update the indexer with the info you have provided.
I've also raised enhancement request #15242 for global freeleech detection on the torrent search page

**Comment by ilike2burnthing** [comment] 2024-04-14 00:13
@Sergiomg86 provide the HTML dump for:

https://xbytesv2.li/index.php?page=torrents&category=&active=0&options=5&search=star+wars&order=3&by=2

**Comment by garfield69** [comment] 2024-04-14 06:13
OK. I think i understand what you are saying.
So I will change the indexer so that it always uses the search for name, and I will change the config `Search for freeleech` option into a `Filter for freeleech` option, so that a search on the web site always uses the search in the name option, and once results are returned, the indexer will drop any results that are not gold if you have chosen to use the config filter freeleech option.

**Closed** 2024-04-14 06:33 UTC

**Comment by garfield69** [comment] 2024-04-15 05:52
v0.21.2387

**Comment by davidosdr** [comment] 2024-04-18 15:51
Xbytes admins might have blocked on purpose the use of Jackett or Prowlarr, or at least it's what I've read in some telegram groups about spanish trackers.

**Comment by ilike2burnthing** [comment] 2024-04-18 15:52
https://github.com/Jackett/Jackett/issues/15253
