### ISSUE TITLE
[cache] 0 results should not be cached, but ignored so that retries can succeed before cache expiry

### ISSUE THREAD

**Issue by cnstephen** [Jackett/Jackett#11410] opened 2021-03-25 03:47 UTC
rarbg

&cat=100044,100045,100042,100046,100047,100050,100051,100052
It doesn't seem to work
It used to be
If you are free to answer, thank you

**Comment by garfield69** [comment] 2021-03-25 04:37
works for me.
`http://127.0.0.1:9117/UI/Dashboard#search=&tracker=rarbg&category=100014,100017,100042,100044,100045,100046,100047,100048,100050,100051,100052,100054`
generated 100 results

if it does not work for you, recall that the RarBG indexer is required to use their API server at https://torrentapi.org (the Sysop does not allow web scraping the main sites HTML from https://rarbg.to/)
However the API server fails intermittently to return results, and you do regularly need to retry. Nothing Jackett can do about that.

If however you are seeing a consistent error when you try the categories you reported, then provide a full **enhanced** log so we can examine.  See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for how to.

**Comment by cnstephen** [comment] 2021-03-25 12:10
I'm very sorry, I didn't express it clearly
I use cat parameter in rss feed
I use multiple parameters on the url. If I visit the same url multiple times, there will be no data. The values of multiple parameters will come out after changing the data
As shown：
![QQ-20210325160106](https://user-images.githubusercontent.com/81022834/112470792-0b622100-8da6-11eb-92a7-2a02c065866d.png)
![QQ-20210325160143](https://user-images.githubusercontent.com/81022834/112470795-0bfab780-8da6-11eb-9d9f-50d9a14037b3.png)
![QQ-20210325160029](https://user-images.githubusercontent.com/81022834/112470785-0a30f400-8da6-11eb-8148-e8b199f7598b.png)

**Comment by garfield69** [comment] 2021-03-25 17:45
@ilike2burnthing  can you make sense of what the OP is reporting? Something to do with cache maybe?

**Comment by ilike2burnthing** [comment] 2021-03-25 19:56
Yea, I can recreate this by disabling the cache in Jackett and refreshing the RSS link a few times until RARBG's API fails (as per always), then refreshing again and it works.

If the RSS search fails with the cache enabled, no amount of refreshing helps until the cache expires.

@ngosang this 0 results failure seems to be being saved in the cache rather than being ignored.

**Comment by cnstephen** [comment] 2021-03-26 01:52
> @ilike2burnthing can you make sense of what the OP is reporting? Something to do with cache maybe?

ha,I use Google Translate, don’t know if I clearly express what I mean

**Comment by cnstephen** [comment] 2021-03-26 01:53
> Yea, I can recreate this by disabling the cache in Jackett and refreshing the RSS link a few times until RARBG's API fails (as per always), then refreshing again and it works.
> 
> If the RSS search fails with the cache enabled, no amount of refreshing helps until the cache expires.
> 
> @ngosang this 0 results failure seems to be being saved in the cache rather than being ignored.
thank you!
I don’t have to do anything, just download the updated version?

**Comment by ilike2burnthing** [comment] 2021-03-26 07:28
> I don’t have to do anything, just download the updated version?
Updates are automatic (unless you've disabled them in Jackett's settings), so when a fix is released you will receive the update. There's no timeline for when that will be though.

**Comment by cnstephen** [comment] 2021-03-26 10:32
> > I don’t have to do anything, just download the updated version?
> 
> Updates are automatic (unless you've disabled them in Jackett's settings), so when a fix is released you will receive the update. There's no timeline for when that will be though.

ok,I'll wait for you to fix it
Thank you everyone for your update, great program, I wish you all happiness

**Comment by cnstephen** [comment] 2021-03-30 08:30
> > I don’t have to do anything, just download the updated version?
> 
> Updates are automatic (unless you've disabled them in Jackett's settings), so when a fix is released you will receive the update. There's no timeline for when that will be though.

hi,The problem I reported has not been resolved yet. I don’t know when it can be resolved.

**Comment by garfield69** [comment] 2021-03-30 08:47
if and when the problem is resolved you will see an update here by us. until then, you can assume that there has been no progress resolving this issue. Mainly due to the C# dev volunteers being available to work on the issue.

**Comment by cnstephen** [comment] 2021-03-31 11:01
> If and when the problem is resolved you will see an update here by us.
> Until then, you can assume that there has been no progress resolving this issue.
> Mainly due to the C# dev volunteers **NOT** being available to work on the issue.

ok,
think u.

**Comment by ngosang** [comment] 2021-04-05 18:47
>  this 0 results failure seems to be being saved in the cache rather than being ignored.

Yes, responses with 0 results without errors are saved in the cache. I think this is the right thing to do for all trackers. Some programs keep searching the same movie title until they grab it.

There is a known issue in RarBG API. It sometimes returns 0 results without error and I can distinguish a real response with 0 results from a bad response. I tried to solve the issue doing retries but it can fail too and I don't want to make infinite retries.

I think we can't do better and I don't want to change the cache just for this particular issue. Maybe someone can contact with the site admin to fix the API.

If someone wants to make a hack for RarBG, you can raise an exception when there are 0 results. The result won't be cached but there will be an error trace in the logs. It could be configurable too...

**Comment by cnstephen** [comment] 2021-05-04 06:31
If I use Linux to install. Can this problem be avoided?

**Comment by ilike2burnthing** [comment] 2021-05-04 15:14
No, the issue is with RARBG's API, nothing you or we can do.

**Comment by ngosang** [comment] 2022-01-16 13:04
I'm closing this. We can not fix the RarBG issue and the cache is fine as it is.

**Closed by ngosang** 2022-01-16 13:04 UTC
Labels: Core, Confirmed

**Comment by programatix** [comment] 2023-02-10 14:11
@ngosang is closing this because it is logical to cache 0 result if no error. However, the issue now is, when error (Warn), the 0 result is also cached.

For example,
```
2023-02-10 20:xx:xx | Torznab search in RARBG for Dragon Prince S01 => Found 0 releases (from cache)
2023-02-10 20:09:45 | Info | Torznab search in RARBG for Dragon Prince S01 => Found 0 releases
2023-02-10 20:09:45 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded.
2023-02-10 20:09:40 | Warn | torrentapi.org returned code 20 with Rate Limit exceeded. Retrying after 5 secs.
```

It would be great if when there is a "Warn" or "Error", then the result is not cached.
