### ISSUE TITLE
[yggtorrent] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by drloser123** [Jackett/Jackett#2212] opened 2017-12-01 07:01 UTC
I think it was working fine last week, but now I have this error:

An error occured while updating this indexer
Login Failed, got redirected

**Comment by garfield69** [comment] 2017-12-01 07:07
Duplicate of #2211

**Closed by garfield69** 2017-12-01 07:07 UTC
Labels: Duplicate

**Comment by drloser123** [comment] 2017-12-01 07:13
Thanks, and sorry for the duplicate.
