### ISSUE TITLE
[hdtorrents] Exception (hdtorrents): Object reference not set to an instance of an object.: Object reference not set to an instance of an object. (Test)

### ISSUE THREAD

**Issue by escservices** [Jackett/Jackett#1776] opened 2017-09-04 15:25 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

[hdtorrents] Exception (hdtorrents): Object reference not set to an instance of an object.: Object reference not set to an instance of an object. 

Issues connecting/parsing data from HDtorrents

Jackett version:  0.8.147.0
Mono version (if not using Windows):  

-------------------------------

**Comment by escservices** [comment] 2017-09-04 15:29
[log.20170904.00001.txt](https://github.com/Jackett/Jackett/files/1275077/log.20170904.00001.txt)
[log.txt](https://github.com/Jackett/Jackett/files/1275078/log.txt)
[updater.txt](https://github.com/Jackett/Jackett/files/1275076/updater.txt)

**Comment by Fiala06** [comment] 2017-09-04 15:40
Was just going to post this also. Having the same issue.

**Comment by tigger29900** [comment] 2017-09-04 23:15
im also having this issue

**Comment by SaskiFX** [comment] 2017-09-05 02:35
Same here, just updated to a new version, but mine is a slightly different error:


  | Error on 20170904223145 for HD-Torrents.txtSystem.InvalidOperationException: Accessing InnerText is not valid for this element type.   at CsQuery.Implementation.DomObject.get_InnerText () [0x00000] in <62a5a4c07a2848abb6ae212eb3d8e283>:0    at Jackett.Indexers.HDTorrents+<PerformQuery>c__async1.MoveNext () [0x00357] in <7425b8f236434ca8bac210128c65206c>:0
-- | --

**Comment by breakthestatic** [comment] 2017-09-05 03:14
I'm seeing this as well.  Not sure if this should actually be a Jackett issue though... I grabbed the URL that Sonarr tried to fetch and see the error text, and that part is controlled by Jackett.  What's weird though is that if I just do a search of HDT within the Jackett UI, that part works  Just grabbing results via the Jackett API is what fails.

**Comment by kaso17** [comment] 2017-09-05 16:39
fixed via e7b9f8c
caused by a missing uploader column for some releases

**Closed by kaso17** 2017-09-05 16:39 UTC
