### ISSUE TITLE
[privatehd & Cinemaz] (updating) Unknown error: <!doctype html>

### ISSUE THREAD

**Issue by Beersteddy** [Jackett/Jackett#14473] opened 2023-06-18 18:42 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-06-18 19:42:05	Info	
Using HTTP Client: HttpWebClient2
2023-06-18 19:42:05	Info	
Using FlareSolverr: http://flaresolverr:8191
2023-06-18 19:42:05	Info	
Using proxy: Disabled
2023-06-18 19:42:05	Info	
App config/log directory: /config/Jackett
2023-06-18 19:42:05	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-06-18 19:42:05	Info	
Running in Docker: Yes (image build: v0.21.245-ls111)
2023-06-18 19:42:05	Info	
File /etc/issue: Welcome to Alpine Linux 3.17
2023-06-18 19:42:05	Info	
Jackett variant: CoreLinuxMuslAmdx64
2023-06-18 19:42:05	Info	
OS version: Unix 6.1.33.0 (64bit OS) (64bit process)
2023-06-18 19:42:05	Info	
Environment version: 6.0.18 (/app/Jackett/)
2023-06-18 19:42:04	Info	
Starting Jackett v0.21.245
```

### Description

[privatehd & Cinemaz] (updating) Unknown error: <!doctype html><html class="no-js" lang=""><head>    <meta charset="utf-8">    <meta http-equiv="x-ua-compatible" content="ie=edge">    <title>Error 503: Down for Maintenance</title>        <meta name="viewport" content="width=device-width, initial-scale=1">    <meta name="_token" content="">    <meta name="_base_url" content="https://privatehd.to">    <link rel="shortcut icon" href="https://privatehd.to/images/privatehd-favicon.png">    <link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400,700|Roboto+Mono:300,400|Roboto:300,400,500,700" rel="stylesheet">    <link href="https://privatehd.to/css/style.css?v=1682496363" rel="stylesheet">    </head><body>    <header>        <nav class="navbar navbar-default navbar-fixed-top">    <div class="container">        <div class="navbar-header">            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span>                <span class="icon-bar"></span>            </button>            <a class="navbar-brand hidden-md" href="/"><img src="https://privatehd.to/images/privatehd-logo-dark.png" alt="PrivateHD"></a>        </div>        <div id="navbar" class="navbar-collapse collapse">            <ul class="nav navbar-nav ">                <li class="" title="Home">                    <a href="https://privatehd.to">Home</a>                </li>                                    <li class="dropdown">                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse            

### Logged Error Messages

```text
[privatehd & Cinemaz] (updating) Unknown error: <!doctype html><html class="no-js" lang=""><head>    <meta charset="utf-8">    <meta http-equiv="x-ua-compatible" content="ie=edge">    <title>Error 503: Down for Maintenance</title>        <meta name="viewport" content="width=device-width, initial-scale=1">    <meta name="_token" content="">    <meta name="_base_url" content="https://privatehd.to">    <link rel="shortcut icon" href="https://privatehd.to/images/privatehd-favicon.png">    <link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400,700|Roboto+Mono:300,400|Roboto:300,400,500,700" rel="stylesheet">    <link href="https://privatehd.to/css/style.css?v=1682496363" rel="stylesheet">    <!--[if lte IE 8]>    <script src="https://privatehd.to/js/html5shiv.respond.min.js"></script><![endif]--></head><body>    <header>        <nav class="navbar navbar-default navbar-fixed-top">    <div class="container">        <div class="navbar-header">            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span>                <span class="icon-bar"></span>            </button>            <a class="navbar-brand hidden-md" href="/"><img src="https://privatehd.to/images/privatehd-logo-dark.png" alt="PrivateHD"></a>        </div>        <div id="navbar" class="navbar-collapse collapse">            <ul class="nav navbar-nav ">                <li class="" title="Home">                    <a href="https://privatehd.to">Home</a>                </li>                                    <li class="dropdown">                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse
```

**Comment by garfield69** [comment] 2023-06-18 18:49
duplicate of #13817 and #13573

**Closed by garfield69** 2023-06-18 18:49 UTC
