### ISSUE TITLE
Error when trying to add IPT

### ISSUE THREAD

**Issue by schn0052** [Jackett/Jackett#1041] opened 2017-02-07 19:31 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.7.993.0
Mono version (if not using Windows): Mono JIT compiler version 4.2.3  

-------------------------------
When trying to add IPT i get the below errors

Configuration failed: Mapping types: WebClientByteResult -> WebClientStringResult Jackett.Utils.Clients.WebClientByteResult -> Jackett.Utils.Clients.WebClientStringResult Destination path: WebClientStringResult Source value: Jackett.Utils.Clients.WebClientByteResult

Feb 07, 2017 12:05:51 PM 	Error 	Exception in Configure

Feb 07 12:05:51 SCH-LAN-NAS1 mono[7443]:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f44383ff7b0 + 0x0003a> in <filename unknown>:0
Feb 07 12:05:51 SCH-LAN-NAS1 mono[7443]:   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7f44383ff790 + 0x00012> in <filename unknown>:0
Feb 07 12:05:51 SCH-LAN-NAS1 mono[7443]:   at Jackett.Indexers.IPTorrents+<ApplyConfiguration>c__async1.MoveNext () [0x002a9] in C:\projects\jackett\src\Jackett\Indexers\IPTorrents.cs:193
Feb 07 12:05:51 SCH-LAN-NAS1 mono[7443]: --- End of stack trace from previous location where exception was thrown ---
Feb 07 12:05:51 SCH-LAN-NAS1 mono[7443]:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f44384018a0 + 0x00029> in <filename unknown>:0
Feb 07 12:05:51 SCH-LAN-NAS1 mono[7443]:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f44383ff880 + 0x000a7> in <filename unknown>:0
Feb 07 12:05:51 SCH-LAN-NAS1 mono[7443]:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f44383ff800 + 0x0006b> in <filename unknown>:0
Feb 07 12:05:51 SCH-LAN-NAS1 mono[7443]:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f44383ff7b0 + 0x0003a> in <filename unknown>:0
Feb 07 12:05:51 SCH-LAN-NAS1 mono[7443]:   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40cddd80 + 0x0001a> in <filename unknown>:0
Feb 07 12:05:51 SCH-LAN-NAS1 mono[7443]:   at Jackett.Controllers.AdminController+<Configure>c__async4.MoveNext () [0x00111] in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:188

**Comment by kaso17** [comment] 2017-02-08 05:58
Please provide a full log from start to error with enhanced logging enabled.
Most likely this is caused by Jackett not being able to connect to https://iptorrents.com/ is it blocked from your connection?

**Comment by Pixa1** [comment] 2017-02-15 19:04
I also have the problem with IPTorrents. I can upload the logs if you need. Thanks.

**Comment by kaso17** [comment] 2017-02-15 20:01
please provide the log

**Comment by Pixa1** [comment] 2017-02-15 20:15
[log.txt](https://github.com/Jackett/Jackett/files/778274/log.txt)

**Comment by kaso17** [comment] 2017-02-16 10:42
The HTML response in your log file contains invalid/broken HTML resulting in the error. Is this still a problem? For me it's working fine, maybe they messed up their code temporarily?

**Comment by Pixa1** [comment] 2017-02-16 10:44
i will try to remove it and add it again later today when i'll get back home, and post the result.
Thanks.

**Comment by Pixa1** [comment] 2017-02-16 16:54
Hi, unfortunately it does not work for me. if i change the url to ipt.rocks then i'm prompted to enter cookie (this also does not work, it says that cookie is not ok.)
Do i have to configure anything else, or enter some other custom link ?
thanks for all your efforts btw.

**Comment by Pixa1** [comment] 2017-02-17 22:46
Hi,
so i tried a little further to try to solve this. I have installed brand new jackett installation, this time on Windows 10, and i got the same result. here is the log file:
[log.txt](https://github.com/Jackett/Jackett/files/784505/log.txt)

**Comment by kaso17** [comment] 2017-02-17 22:59
same incorrect html.
Can you please post the HTML code and a screenshot when of the torrent search results table (https://iptorrents.com/t) when using a normal browser?

**Comment by Pixa1** [comment] 2017-02-18 06:36
![image](https://cloud.githubusercontent.com/assets/22279931/23091007/2298f466-f5ac-11e6-8a7e-1bb6fa65ef7f.png)

i have copied the source of the page to pastebin
[](http://pastebin.com/8s0qrTSa)

**Comment by kaso17** [comment] 2017-02-19 16:01
ok, it's due to your profile settings.
Please change the "Torrents - Category column" in your Settings to "Icons" to fix it.
Will add a check for that in the code.

**Comment by gasde1** [comment] 2017-02-19 16:07
@kaso17 just tried this and it worked, thanks!

**Comment by Pixa1** [comment] 2017-02-19 16:54
@kaso17 Yes, it works now ! (i had to logoff and logon to the site again).
Thank you very much :)

**Comment by armani316** [comment] 2017-02-19 22:03
@schn0052 I'm closing this issue for now. Feel free to reopen it if you're still having the same problem.

**Closed by armani316** 2017-02-19 22:03 UTC
