### ISSUE TITLE
Changing settings doesn't work. Value null error is shown.

### ISSUE THREAD

**Issue by bighi** [Jackett/Jackett#1290] opened 2017-04-16 16:25 UTC
I recently installed Jackett in my Arch Linux PC.

Problem: Changing settings doesn't work. It doesn't matter what I put in the input fields, whenever I try to save settings it shows this message: `Error: Value cannot be null. Parameter name: value`.

(Also nothing else works, but let's fix one thing at a time. If I go back to a 0.5.xxx version, things work)

Jackett Version 0.7.1207.0
Mono JIT compiler version 4.8.0

**Comment by JigSawFr** [comment] 2017-04-16 16:53
Seems to be duplicate of https://github.com/Jackett/Jackett/issues/1288

**Comment by bighi** [comment] 2017-04-18 20:14
Not exactly. The message shows up on the web page, not in a debug log. And it's not while trying to use Torznab or any other service.

I am completely unable to save any changes to the settings.

**Comment by kaso17** [comment] 2017-04-20 11:30
@bighi please make sure to clear your browser cache after the update, that's usually the problem.

**Comment by fryfrog** [comment] 2017-04-21 18:31
Did you install by hand or w/ the [AUR package](https://aur.archlinux.org/packages/jackett/)?

**Comment by bighi** [comment] 2017-04-25 20:50
I used the AUR package.

**Comment by kaso17** [comment] 2017-09-19 16:20
is this still a problem?

**Comment by bighi** [comment] 2017-09-29 20:25
I gave up on Jackett. But I'll try again in a few hours.

**Comment by flightlevel** [comment] 2017-11-07 01:42
Re-open if still an issue, no one else seems to be getting this error, so likely re-install and cache clear should fix it

**Closed by flightlevel** 2017-11-07 01:42 UTC
Labels: Core, Needs Investigations
