### ISSUE TITLE
[morethantv] torrent groups cause incorrect info to be returned

### ISSUE THREAD

**Issue by Styloy** [Jackett/Jackett#13004] opened 2022-02-27 08:22 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19043.0 (64bit OS)
Environment version: 6.0.2 (C:\ProgramData\Jackett\)
```

### Description

When searching on MoreThanTV via Jackett, any torrent that is part of a group will return the total size of the group and returns all results of that group instead (for example if you search for an certain group release you get everything from that group on MTV all with the same combined filesize and same combined amount of seeds)

this messes up scripts like [https://github.com/mmgoodnow/cross-seed](url) due to the size mismatch. 

### Logged Error Messages

```text
n\a
```

### Screenshots

![mtv](https://user-images.githubusercontent.com/100509373/155874538-7e5ce5f2-f417-4d9d-b869-a7b61bd4084e.png)

**Comment by garfield69** [comment] 2022-02-27 17:27
This is a duplicate of #12977 
Here is the relevant summary https://github.com/Jackett/Jackett/issues/12977#issuecomment-1053242504
It would appear that you will not be able to use your cross-seed script with this indexer for now.

**Closed by garfield69** 2022-02-27 17:27 UTC
