### ISSUE TITLE
French-Adn found nothing

### ISSUE THREAD

**Issue by maxcore** [Jackett/Jackett#292] opened 2016-04-01 19:19 UTC
````

When	Level	Message
Apr 01, 2016 03:16:15 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Apr 01, 2016 03:16:15 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Apr 01, 2016 03:16:15 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Apr 01, 2016 03:16:15 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Apr 01, 2016 03:16:15 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Apr 01, 2016 03:16:15 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Apr 01, 2016 03:16:15 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Apr 01, 2016 03:16:15 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Apr 01, 2016 03:16:15 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Apr 01, 2016 03:16:15 PM	Info	
ApiControllerActionSelector SelectAction 
Apr 01, 2016 03:16:15 PM	Info	
AdminController ExecuteAsync 
Apr 01, 2016 03:16:15 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Apr 01, 2016 03:16:15 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Apr 01, 2016 03:16:15 PM	Info	
DefaultHttpControllerActivator Create 
Apr 01, 2016 03:16:15 PM	Info	
HttpControllerDescriptor CreateController 
Apr 01, 2016 03:16:15 PM	Info	
DefaultHttpControllerSelector SelectController Admin
Apr 01, 2016 03:16:15 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Apr 01, 2016 03:16:15 PM	Info	
  http://192.168.2.125:9117/Admin/GetLogs?_=1459538126829
Apr 01, 2016 03:16:10 PM	Info	
  Content-type='application/json; charset=utf-8', content-length=unknown
Apr 01, 2016 03:16:10 PM	Info	
DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8'
Apr 01, 2016 03:16:10 PM	Info	
JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter
Apr 01, 2016 03:16:10 PM	Info	
JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='HttpError', mediaType='application/json; charset=utf-8'
Apr 01, 2016 03:16:10 PM	Info	
DefaultContentNegotiator Negotiate Type='HttpError', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer]
Apr 01, 2016 03:16:10 PM	Info	
  http://192.168.2.125:9117/images/sort_both.png
Apr 01, 2016 03:16:10 PM	Info	
AdminController Dispose 
Apr 01, 2016 03:16:10 PM	Info	
AdminController Dispose 
Apr 01, 2016 03:16:10 PM	Info	
JsonMediaTypeFormatter WriteToStreamAsync 
Apr 01, 2016 03:16:10 PM	Info	
JsonMediaTypeFormatter WriteToStreamAsync Value='Jackett.ManualSearchResult', type='ManualSearchResult', content-type='application/json; charset=utf-8'
Apr 01, 2016 03:16:10 PM	Info	
  Content-type='application/json; charset=utf-8', content-length=unknown
Apr 01, 2016 03:16:10 PM	Info	
AdminController ExecuteAsync 
Apr 01, 2016 03:16:10 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Apr 01, 2016 03:16:10 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Search(AdminSearch value)'
Apr 01, 2016 03:16:10 PM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Apr 01, 2016 03:16:10 PM	Info	
DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8'
Apr 01, 2016 03:16:10 PM	Info	
JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter
Apr 01, 2016 03:16:10 PM	Info	
JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='ManualSearchResult', mediaType='application/json; charset=utf-8'
Apr 01, 2016 03:16:10 PM	Info	
DefaultContentNegotiator Negotiate Type='ManualSearchResult', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer]
Apr 01, 2016 03:16:10 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'Jackett.ManualSearchResult'
Apr 01, 2016 03:16:10 PM	Info	
Manual search for "a Walk in the Woods" on French-ADN with 0 results.
Apr 01, 2016 03:16:10 PM	Error	
Error on 20160401151610 for French-ADN.txtSystem.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (IEnumerable`1 source) <0x40fb2890 + 0x0013f> in <filename unknown>:0 
  at Jackett.Indexers.FrenchADN+<PerformQuery>c__async1.MoveNext () <0x41394000 + 0x00dcf> in <filename unknown>:0 




Error, unable to parse result 
  at System.Linq.Enumerable.First[TSource] (IEnumerable`1 source) <0x40fb2890 + 0x0013f> in <filename unknown>:0 
  at Jackett.Indexers.FrenchADN+<PerformQuery>c__async1.MoveNext () <0x41394000 + 0x00dcf> in <filename unknown>:0 
Apr 01, 2016 03:16:10 PM	Debug	
UnixLibCurlWebClient:GetString Returning Redirect => 
Apr 01, 2016 03:16:10 PM	Debug	
UnixLibCurlWebClient:GetString(Url:https://french-adn.com/browse.php?do=search&keywords=a.Walk.in.the.Woods&category=&search_type=t_name)
Apr 01, 2016 03:16:07 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Search(value=Jackett.Models.AdminSearch)'
Apr 01, 2016 03:16:07 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='Search(value=Jackett.Models.AdminSearch)'
Apr 01, 2016 03:16:07 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Apr 01, 2016 03:16:07 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Search(AdminSearch value)'
Apr 01, 2016 03:16:07 PM	Info	
HttpActionBinding ExecuteBindingAsync Model state is invalid. value.Category: A value is required.
Apr 01, 2016 03:16:07 PM	Info	
FormatterParameterBinding ExecuteBindingAsync Parameter 'value' bound to the value 'Jackett.Models.AdminSearch'
Apr 01, 2016 03:16:07 PM	Info	
JQueryMvcFormUrlEncodedFormatter ReadFromStreamAsync Value read='Jackett.Models.AdminSearch'
Apr 01, 2016 03:16:07 PM	Error	
JQueryMvcFormUrlEncodedFormatter ReadFromStreamAsync A value is required.

````

Movies found on the site but nothing in jackett

**Comment by JigSawFr** [comment] 2016-04-03 19:14
Duplicate of ISS https://github.com/Jackett/Jackett/issues/286

**Closed by JigSawFr** 2016-04-03 19:14 UTC
Labels: Duplicate, Invalid, Provider
