### ISSUE TITLE
Update fail

### ISSUE THREAD

**Issue by maxcore** [Jackett/Jackett#81] opened 2015-11-21 03:18 UTC
When i check for update : 
````
Nov 20, 2015 10:16:46 PM	Error	
Error checking for updates.

````
?

**Comment by maxcore** [comment] 2015-11-21 14:26
@WhatFox the update wont work on my jacket i have the Jackett Version 0.7.29.0

**Comment by WhatFox** [comment] 2015-11-21 18:05
Turn logs on and see what its doing

**Comment by maxcore** [comment] 2015-11-21 20:14
@WhatFox 
````
Nov 21, 2015 03:13:38 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetLogs()'
Nov 21, 2015 03:13:38 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='GetLogs()'
Nov 21, 2015 03:13:38 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Nov 21, 2015 03:13:38 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetLogs()'
Nov 21, 2015 03:13:38 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Nov 21, 2015 03:13:38 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Nov 21, 2015 03:13:38 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Nov 21, 2015 03:13:38 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Nov 21, 2015 03:13:38 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'GetLogs()'
Nov 21, 2015 03:13:38 PM	Info	
ApiControllerActionSelector SelectAction 
Nov 21, 2015 03:13:38 PM	Info	
AdminController ExecuteAsync 
Nov 21, 2015 03:13:38 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Nov 21, 2015 03:13:38 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Nov 21, 2015 03:13:38 PM	Info	
DefaultHttpControllerActivator Create 
Nov 21, 2015 03:13:38 PM	Info	
HttpControllerDescriptor CreateController 
Nov 21, 2015 03:13:38 PM	Info	
DefaultHttpControllerSelector SelectController Admin
Nov 21, 2015 03:13:38 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Nov 21, 2015 03:13:38 PM	Info	
  http://192.168.2.125:9117/admin/GetLogs?_=1448136809038
Nov 21, 2015 03:13:35 PM	Error	
Error checking for updates.
Nov 21, 2015 03:13:35 PM	Info	
AdminController Dispose 
Nov 21, 2015 03:13:35 PM	Info	
AdminController Dispose 
Nov 21, 2015 03:13:35 PM	Info	
  Content-type='application/json; charset=utf-8', content-length=2
Nov 21, 2015 03:13:35 PM	Info	
AdminController ExecuteAsync 
Nov 21, 2015 03:13:35 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync 
Nov 21, 2015 03:13:35 PM	Info	
JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'TriggerUpdates()'
Nov 21, 2015 03:13:35 PM	Info	
ApiControllerActionInvoker InvokeActionAsync 
Nov 21, 2015 03:13:35 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]'
Nov 21, 2015 03:13:35 PM	Info	
ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'TriggerUpdates()'
Nov 21, 2015 03:13:35 PM	Info	
ApiControllerActionInvoker InvokeActionAsync Action='TriggerUpdates()'
Nov 21, 2015 03:13:35 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync 
Nov 21, 2015 03:13:35 PM	Info	
JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'TriggerUpdates()'
Nov 21, 2015 03:13:35 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Nov 21, 2015 03:13:35 PM	Info	
HttpActionBinding ExecuteBindingAsync 
Nov 21, 2015 03:13:35 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Nov 21, 2015 03:13:35 PM	Info	
JackettAuthorizedAttribute OnAuthorizationAsync 
Nov 21, 2015 03:13:35 PM	Info	
ApiControllerActionSelector SelectAction Selected action 'TriggerUpdates()'
Nov 21, 2015 03:13:35 PM	Info	
ApiControllerActionSelector SelectAction 
Nov 21, 2015 03:13:35 PM	Info	
AdminController ExecuteAsync 
Nov 21, 2015 03:13:35 PM	Info	
HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
Nov 21, 2015 03:13:35 PM	Info	
DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
Nov 21, 2015 03:13:35 PM	Info	
DefaultHttpControllerActivator Create 
Nov 21, 2015 03:13:35 PM	Info	
HttpControllerDescriptor CreateController 
Nov 21, 2015 03:13:35 PM	Info	
DefaultHttpControllerSelector SelectController Admin
Nov 21, 2015 03:13:35 PM	Info	
DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
Nov 21, 2015 03:13:35 PM	Info	
  http://192.168.2.125:9117/admin/trigger_update?_=1448136809037
`````

**Comment by raspdealer** [comment] 2015-12-21 20:55
I have issues too... this feature doesnt look very stable.

**Comment by Azerelat** [comment] 2015-12-27 21:55
Duplicate of #110 comment there if you still have issues.

**Closed by Azerelat** 2015-12-27 21:55 UTC
