### ISSUE TITLE
Missing Corsaro Nero

### ISSUE THREAD

**Issue by salerno-cesare** [Jackett/Jackett#15649] opened 2024-10-14 19:42 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Missing Corsaro Nero Definition
```

### Description

Missing Corsaro Nero Definition

### Logged Error Messages

```text
Missing Corsaro Nero Definition
```

**Comment by garfield69** [comment] 2024-10-14 19:50
the indexer was removed on Sep 28 after it was offline for over a month beginning Aug 26
It seems the site is back up again, what a PITA
Closing as a duplicate of #986, see that ticket for updates.

**Closed by garfield69** 2024-10-14 19:50 UTC
