### ISSUE TITLE
speed.cd not working after a day, need to be re added to work.

### ISSUE THREAD

**Issue by zorvalth** [Jackett/Jackett#330] opened 2016-05-06 05:56 UTC
When I add speed.cd everything is fine and working with results. But after a day or so it stop and need to be removed like source and added again. 

This is what it says when it stops 
https://vgy.me/N2yeta.png

**Comment by smarshallsay** [comment] 2016-05-09 17:01
Probably because the cookies or similar are IP based and your VPN / internet connection IP has changed. Same thing happens with TorrentLeech and others at the moment.

**Comment by zorvalth** [comment] 2016-05-09 17:09
I dont know about cookies but my ip is static and real. My browser stays logged in the speed.cd account without any problems. hd-torrents works just fine.

**Comment by JigSawFr** [comment] 2016-05-09 21:06
As @smarshallsay said, if you need to re-apply config of the provider, the problem is your tracker is checking your IP or your cookie, if you login with your browser, session on racker owned by jackett may be invalidated by tracker.

**Comment by subzero79** [comment] 2016-05-14 00:38
jackett configuration can be reapplied using the API. I usually do this for some trackers that loose configuration from time to time. So i add curl cron jobs for some of the trackers let's say every 12 hours.

Now for speed.cd I just tested and is just simply not working anymore. Guess they changed something.

This is the log

```
05-14 00:37:02 Info AdminController Dispose  
05-14 00:37:15 Info   http://10.10.10.12:9117/Admin/configure_indexer 
05-14 00:37:15 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
05-14 00:37:15 Info DefaultHttpControllerSelector SelectController Admin 
05-14 00:37:15 Info HttpControllerDescriptor CreateController  
05-14 00:37:15 Info DefaultHttpControllerActivator Create  
05-14 00:37:15 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
05-14 00:37:15 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
05-14 00:37:15 Info AdminController ExecuteAsync  
05-14 00:37:15 Info ApiControllerActionSelector SelectAction  
05-14 00:37:15 Info ApiControllerActionSelector SelectAction Selected action 'Configure()' 
05-14 00:37:15 Info JackettAuthorizedAttribute OnAuthorizationAsync  
05-14 00:37:15 Info JackettAuthorizedAttribute OnAuthorizationAsync  
05-14 00:37:15 Info HttpActionBinding ExecuteBindingAsync  
05-14 00:37:15 Info HttpActionBinding ExecuteBindingAsync  
05-14 00:37:15 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Configure()' 
05-14 00:37:15 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
05-14 00:37:15 Info ApiControllerActionInvoker InvokeActionAsync Action='Configure()' 
05-14 00:37:15 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Configure()' 
05-14 00:37:15 Debug UnixLibCurlWebClient:GetString(Url:https://speed.cd/take.login.php) 
05-14 00:37:15 Debug UnixLibCurlWebClient: Posting username=username&password=password 
05-14 00:37:15 Debug UnixLibCurlWebClient:GetString Returning InternalServerError =>  
05-14 00:37:15 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]' 
05-14 00:37:15 Info ApiControllerActionInvoker InvokeActionAsync  
05-14 00:37:15 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()' 
05-14 00:37:15 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
05-14 00:37:15 Info AdminController ExecuteAsync  
05-14 00:37:15 Info   Content-type='application/json; charset=utf-8', content-length=341 
05-14 00:37:15 Info AdminController Dispose  
05-14 00:37:15 Info AdminController Dispose 
```

**Comment by maxcore** [comment] 2016-05-14 04:01
samething from xthor,bluetiger and french-adn

**Comment by flightlevel** [comment] 2016-05-14 13:16
@maxcore  @subzero79  Latest release fix should fix https://github.com/Jackett/Jackett/releases/tag/v0.7.251
The autoupdater won't work from version 247, so you will have to download manually

@subzero79 @zorvalth  Yep, loosing the config is annoying, This will be fixed in the next major version of Jackett. Currently we just assume that we are logged in. In future we'll just login on every request

**Comment by maxcore** [comment] 2016-05-14 13:20
@flightlevel i confirm back on the track thx !!!!

**Comment by subzero79** [comment] 2016-05-15 08:37
Working ok. Also reconfiguration using the api also works.

**Comment by JigSawFr** [comment] 2016-05-15 14:27
As @flightlevel said, we assume that we are logged in, some providers are processing loging (or check login) for every requests. In this version, they must be rewrited to be able to do this.

**Closed** 2016-05-15 14:27 UTC
Labels: Confirmed, Provider

**Comment by flightlevel** [comment] 2016-05-28 10:04
@subzero79 @maxcore @zorvalth 
This should be fixed now in the latest release. It should update the cookie each time now
