### ISSUE TITLE
demonoid: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13850] opened 2023-01-06 18:52 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.20.2495
Linux / Docker
```

### Description

Torrents:
* Jailyn Matthews - Pilates + Resistance Bands Workout
* Elephorm : Technique image webdesigner
* Cybrary - Preventing Data Breaches with A1Logic
* Code With Mosh | The Ultimate Data Structures 
* [VW] Volkswagen BUG JAM / VW NATIONALS

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment] 2023-01-06 20:58
The site is offline ATM for maintenance. I will check later.
It is very likely this is a duplicate of #13168
See https://github.com/Jackett/Jackett/issues/13168#issuecomment-1100816823 for more details.

**Comment by ilike2burnthing** [comment] 2023-01-07 14:49
Yea, they're all miscellaneous. Do we add a dummy `0` category? `c0` just returns everything.

**Closed** 2023-01-07 19:29 UTC
