### ISSUE TITLE
[xwtorrents] Error: Username or password incorrect (Config)

### ISSUE THREAD

**Issue by vavavr00m** [Jackett/Jackett#6370] opened 2019-11-15 07:17 UTC
Entering the password with char × on the website works while Jackett fails. Changing the password to letter x allowed me to sign in to XWT using Jackett.

**Comment by garfield69** [comment] 2019-11-15 07:36
I think this applies to all Jackett cardigann indexers not just xwtorrents.
I suspect that the cardigann processor does not handle or pass-through certain characters during the login process.
for example, I am aware that some Russian users have trouble using their Cyrillic alphabet.

this is however beyond my skills to investigate or repair as its a c# developers activity.
we are going to need a c# dev to volunteer to code a solution.

**Comment by vavavr00m** [comment] 2019-11-15 07:48
I had trouble with Ice Torrent regarding password too. Is it also in C#? Ice Torrent only accepts 18 chars.

**Comment by garfield69** [comment] 2019-11-15 07:59
both icetorrent and xwtorrents are indexers written in yaml.
these are processed by the jackett Cardigann processor, which is written in c#
its the cardigann processor that read the yaml indexer code and implements the config settings, and http requests to the web sites, and scrapes the returned html etc.

the cardigann processor does not support defining a length limit to username or passwords currently in its yaml login block, so if you wanted to have that option supported you should raise an enhancement request, and hopefully someone with c# knowledge and willingness to code the option into the cardigann processor will volunteer their time and skills to implement.

**Comment by vavavr00m** [comment] 2019-11-15 08:22
Thank you. Submitted a separate issue.

**Comment by ngosang** [comment] 2020-01-09 21:57
I can't reproduce this issue... I changed the password in one of my accounts (4thD) to `Перево×д` and it works in the website and in Jackett. I also checked the code and I can't see anything wrong... everything is utf-8.
Did you see the error when you configure the tracker or in search?

**Comment by ngosang** [comment] 2020-02-08 14:11
I think this is fixed in #6994 Could you download the latest version and test it again?

**Comment by vavavr00m** [comment] 2020-02-09 08:29
It's a 32-char long password with 1 char being ×. I'm getting this error:
![chrome_tXfvJW6GCX](https://user-images.githubusercontent.com/4675132/74098952-0b2ea400-4b59-11ea-939c-e593913a0f3a.png)

**Comment by garfield69** [comment] 2020-02-09 08:58
Please confirm the version of jackett you are using, also, which build (amdx64, arm32, arm64, mobo, macos, windows)?

**Comment by vavavr00m** [comment] 2020-02-09 09:00
Jackett Version: 0.12.1765.0
Build: Windows

**Comment by garfield69** [comment] 2020-02-09 09:07
@ngosang xwtorrents uses the utf8 encoding.

**Comment by vavavr00m** [comment] 2020-02-09 09:16
@ngosang I see the error when I configure the tracker. Using your password gives me this:
![chrome_ZkLxew7UnE](https://user-images.githubusercontent.com/4675132/74099537-da9e3880-4b5f-11ea-8c46-1ed3d31755fb.png)

**Comment by ngosang** [comment] 2020-02-09 15:22
I think we are mixing 2 things here.

**The encoding is not UTF-8**
* In Jackett is defined as UTF-8
* The source code of the page is broken and the encoding is not defined => https://xtremewrestlingtorrents.net
* Firefox says the encoding is `windows-1252`
![image](https://user-images.githubusercontent.com/10577978/74104707-a4f55180-4b57-11ea-8c3b-4b7ac6f5ae1f.png)

@garfield69 could you change the encoding and test the login (with Russian chars) and the search results to be sure we are not breaking things.

**The password length**
* We are not validating this in Jackett. The password you write will be send to the site.

**Comment by vavavr00m** [comment] 2020-02-09 16:02
I was trying to say that changing my password to `Перево×д` on the website gives me an error.

**Comment by garfield69** [comment] 2020-02-09 18:55
changing the encoding to windows-1252 allows me to login with a 32 char pswd that contains Latin-1 Supplement chars. 
and does not appear to alter search requests. I will update the indexer shortly.

**Closed** 2020-02-09 18:57 UTC
Labels: Help wanted, Needs C#

**Comment by garfield69** [comment] 2020-02-10 06:29
jackett 0.12.1779

**Comment by vavavr00m** [comment] 2020-02-10 11:17
Confirming the fix works.
