### ISSUE TITLE
[gktorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by seb972** [Jackett/Jackett#1954] opened 2017-10-10 21:38 UTC
Hi everybody,

i had an issue with this tracker, jackett can't reach the host https://www.gktorrent.com/
Can you check where is the problem please?

Jackett version:
Mono version

**Comment by garfield69** [comment] 2017-10-10 22:45
duplicate of #1941 
the next release of Jackett should fix this with 49a7c8df7a2be652cb8a96ba2dd2aa42ef118761.

**Closed by garfield69** 2017-10-10 22:45 UTC
Labels: Duplicate
