### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: Selector

### ISSUE THREAD

**Issue by Mazus** [Jackett/Jackett#2569] opened 2018-02-10 09:14 UTC
Error on 20180210100723 for YGGtorrent.txtJackett.ExceptionWithConfigData: Login failed: Selector "a[href$="user/logout"]" didn't match    à Jackett.Indexers.CardigannIndexer.<TestLogin>d__19.MoveNext() dans C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:ligne 689 --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    à Jackett.Indexers.CardigannIndexer.<PerformQuery>d__28.MoveNext() dans C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:ligne 1196
--

I think this comes from new field labels in the login page. They changed it to renew users passwords but also regular login page.

In https://yggtorrent.com/user/login:

```
> <form>
>  <class="form-horizontal" action="https://yggtorrent.com/user/login" method="post">
> <fieldset>
> <!-- Login input-->
> <div class="form-group">
>  <label class="col-md-4 control-label" for="piNewPass">Pseudo</label>
> <div class="col-md-4">
> <input id="piNewPass" name="id" type="text" placeholder="Pseudo" class="form-control input-md" required="">
>    </div>
>   </div>
>  <!-- Password input--><div class="form-group"><label class="col-md-4 control-label" for="**piNewPassRepeat**">Mot de passe</label>
>   <div class="col-md-4">
>  <input id="**piNewPassRepeat**" name="pass" type="password" placeholder="" class="form-control input-md" required="">
> </div>
> </div>
```

**Jackett version**:  0.8.676.0

-------------------------------

**Comment by garfield69** [comment] 2018-02-10 18:12
Duplicate of #2561
the most likely reason for this is that you have saved the wrong username or password in your Jackett yggtorrent indexer config.
Also, yggtorrent have been expiring user's account passwords lately, so login directly with you browser and make sure you do not have any outstanding alerts.
Then update your Jackett yggtorrent config by using the wrench icon on the dashboard and try again.

**Closed by garfield69** 2018-02-10 18:12 UTC
Labels: Duplicate

**Comment by Mazus** [comment] 2018-02-11 10:39
Ok sorry, pretty sure I tried this earlier but didn't work.
Now it does!
Thanks
