### ISSUE TITLE
[nexttorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by seb972** [Jackett/Jackett#1955] opened 2017-10-10 21:39 UTC
Hi everybody,

i had an issue with this tracker, jackett can't reach the host https://www.nextorrent.cc/
Can you check where is the problem please?

Jackett version:
Mono version

**Comment by garfield69** [comment] 2017-10-10 22:49
duplicate of #1847
Please provide full enhanced logs to the #1847 ticket. 
Instructions, should  you need them, can be found at [trobleshooting](https://github.com/Jackett/Jackett#troubleshooting).

**Closed by garfield69** 2017-10-10 22:49 UTC
Labels: Duplicate

**Comment by garfield69** [comment] 2017-10-11 00:04
Resolved with 8aa82a22f43949683fa3f5eac0de3c2f50908e85 available in the next release of Jackett.
