### ISSUE TITLE
Setting Admin Password programmatically or through the API

### ISSUE THREAD

**Issue by liaralabs** [Jackett/Jackett#2920] opened 2018-04-07 02:49 UTC
Hey guys,

I've been bashing my head against this problem for a while now and have tried to contact you through Discord, but never received a response. Sorry if this isn't the right place!

I'm attempting to set the admin password for users automatically and have attempted to use both the API and also to hash it myself and insert into ServerConfig.json. However, I can't seem to figure out either way to do it.

I've attempted to curl straight to the api locally with the following command:
`curl -X POST http://127.0.0.1:12925/jackett/api/v2.0/server/adminpassword -H "Content-Type: application/json" --data "password"`
I've also tried `--data '{"AdminPassword":"password"}` to no avail. I can see from chrome debug logs, that the only data being passed is indeed "password" and I'm wondering if I'm missing some sort of crucial piece of header data or otherwise.

Alternatively, I have tried hashing the password myself. I can see from the source that you seem to be using SHA512 for this task and that the password itself is salted with the API key; however, when I compare my own generated hash with the hash that resides in ServerConfig, they are quite different.

I know I must be missing something, would greatly appreciate if you guys have any tips that might set me in the right direction.

Thanks!

**Comment by garfield69** [comment] 2018-04-07 03:32
Duplicate of #2690 ;-)

**Closed by garfield69** 2018-04-07 03:32 UTC
Labels: Duplicate

**Comment by liaralabs** [comment] 2018-04-07 05:12
Crud! Thanks -- I swear I searched high and low for someone to already post something similar :blush:
