### ISSUE TITLE
[kickasstorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by hirezl** [Jackett/Jackett#2506] opened 2018-01-29 23:33 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

Kickass indexer returns "Found no results while trying to browse this tracker"  Configured URL 'https://katcr.co/' is up and I am able to browse and search it in a browser.  All other indexers work, but this one never has.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
[log.txt](https://github.com/Jackett/Jackett/files/1675662/log.txt)

Jackett version:  0.8.618.0
Mono version (if not using Windows):  root@REZ:~# mono --version
Mono JIT compiler version 5.4.1.7 (tarball Wed Jan 17 20:08:37 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

-------------------------------

**Comment by garfield69** [comment] 2018-01-30 01:41
Duplicate of #2280

**Closed by garfield69** 2018-01-30 01:41 UTC
Labels: Duplicate
