### ISSUE TITLE
Torrent-Syndikat tracker in latest update has broken Jackett?

### ISSUE THREAD

**Issue by Speaktomenow** [Jackett/Jackett#506] opened 2016-09-12 06:29 UTC
I have reverted to v0.7.370 as I am now getting constant errors when trying to launch that seem to mention Torrent-Syndicat.

My error on trying to launch was:

Error Top level exception Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(IIndexerManagerService, Logger, IWebClient, IProtectionService)' on type 'TorrentSyndikat'. ---> Exception of type 'System.TimeZoneNotFoundException' was thrown. (See inner exception for details.)

**Comment by kaso17** [comment] 2016-09-12 08:41
duplicate of #496
This was fixed with version .380 3 days ago you weren't running the most recent version (The broken version isn't available any more).

**Comment by Speaktomenow** [comment] 2016-09-12 09:46
Oh thanks. I have mine set to auto update. I only noticed it was broken today, so not sure when it occurred.

Hopefully when I next run updates it will sort itself out and go to .380

Cheers!

**Closed** 2016-10-11 10:34 UTC
Labels: Can't Reproduce
