### ISSUE TITLE
[archetorrent] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by seb972** [Jackett/Jackett#1952] opened 2017-10-10 20:54 UTC
Hi everybody,

i had an issue with this tracker, jackett can't reach the host https://www.archetorrent.com/index.php
Can you check where is the problem please?

Jackett version:  
Mono version

-------------------------------

**Comment by garfield69** [comment] 2017-10-11 04:15
duplicate of #1939

**Closed by garfield69** 2017-10-11 04:15 UTC
Labels: Duplicate
