### ISSUE TITLE
Nebulance giving me error when I try to login

### ISSUE THREAD

**Issue by mouzzampk2014** [Jackett/Jackett#5529] opened 2019-06-22 13:38 UTC
Hi,
I am getting transmitthenet: String 33 mins ago was not recognized as a valid Date Time.
Could you please look into this for me. 
Thank you

0.11.420.0

![2019-06-22](https://user-images.githubusercontent.com/44548525/59964666-61cc6c80-94fb-11e9-9284-b5bb92f1064b.png)

**Comment by garfield69** [comment] 2019-06-22 19:18
please try out jackett pre-release v0.11.428
duplicate of #5524

**Closed** 2019-06-22 19:34 UTC
Labels: Duplicate
