### ISSUE TITLE
[yggtorrent] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by JoeSophia** [Jackett/Jackett#2392] opened 2018-01-09 15:37 UTC
Jackett version:  0.8.500 on qnap
Mono version (if not using Windows):  Qmono 4.6.2.7

-------------------------------

Hi,

I have this error when i try to connect to yggtorrent, I see all the related issue and normaly it fix in this version. My login and psw are verified before opening this issue.
Can you help me.

Regards,
Jonathan

  
![image](https://user-images.githubusercontent.com/35266902/34728933-9449afa6-f55b-11e7-90ec-435bcedcd135.png)

**Comment by Drix32** [comment] 2018-01-09 16:51
Hello,

Having the same problem here with yggtorrent. Same error message in the logs aka {0}.

When trying to add the indexer, i get a login issue with a redirection message :

![capture d ecran 2018-01-09 a 13 46 08](https://user-images.githubusercontent.com/35269029/34732282-95a514e8-f543-11e7-9df4-1b7754fe85c3.png)

I verified the account and it pose no problem on the website. Tried with another account working perfectly with jackett on synology. Same issue.

I also have jackett 0.8.500 and Qmono 4.6.2.7 installed on my TS-251+.

If you guys have any idea where that comes from. I tried changing the URL with anything i could come up with in my mind (with ww1, no www, only www, http/https). Nothing works.

Thanks for your support

**Comment by kaso17** [comment] 2018-01-09 18:15
please update to the latest jackett version

**Comment by Drix32** [comment] 2018-01-09 18:42
Thank you for your rapid answer.

I managed to upgrade jackett. When trying before i had and error saying that the upgrade failed. Now i'm in version 0.8.578.0 and everything works just fine.

Thank you for your help. Have a good day :)

**Comment by Zhoth** [comment] 2018-01-09 19:08
@Drix32 how do you update Jackett? I have a QNap TS219P but if I click the "Check for update button" in the Jackett UI nothing happens.. :-(

**Comment by Drix32** [comment] 2018-01-09 19:55
@Zhoth I did press the "check for update" button located next to the "log" button on the homepage of Jackett.

![capture d ecran 2018-01-09 a 16 53 52](https://user-images.githubusercontent.com/35269029/34740372-ed56c9f6-f55d-11e7-9421-e2a87782059b.png)


Then i went into the logs and saw that jackett was automaticaly installing the update. I got my version of jacket by configuring the QNAP club in my application center then searching for the app. Maybe it could affect the update... I don't know.

**Comment by Zhoth** [comment] 2018-01-09 20:45
@Drix32 unfortunately if I press that button it doesn't work and I see an exeption in the log file. I install Jackett in the same way.. :-(

**Comment by garfield69** [comment] 2018-01-09 21:47
navigate to the `~/.config/Jackett/` direcory and drag/drop the updater.txt log file here. There may be additional information there that could be useful.

**Comment by Zhoth** [comment] 2018-01-09 21:53
There isn't any updater.txt file:
![immagine](https://user-images.githubusercontent.com/35234113/34745166-dbdf0436-f58f-11e7-91cf-afe89d3b25cf.png)

**Comment by JoeSophia** [comment] 2018-01-10 09:40
Hi,
I do the update and that's work .
So thank you for your help.
I do the update with click on "Check for updates" then "Apply server setting"
![image](https://user-images.githubusercontent.com/35266902/34765758-a49e9d84-f5f2-11e7-82b5-acc309f84666.png)

**Comment by kaso17** [comment] 2018-01-10 10:50
@Zhoth what's the exception?

**Comment by Zhoth** [comment] 2018-01-10 18:45
@kaso17 this is the exception:

2018-01-10 19:45:18.6369 Error got NotImplemented/InternalServerError
2018-01-10 19:45:18.7155 Error request.Method: GET
2018-01-10 19:45:18.7176 Error request.Url: https://api.github.com/repos/Jackett/Jackett/releases
2018-01-10 19:45:18.7196 Error request.Cookies:
2018-01-10 19:45:18.7214 Error request.Referer:
2018-01-10 19:45:18.7239 Error request.RawPOSTDdata:
2018-01-10 19:45:18.7264 Error cookies:
2018-01-10 19:45:18.7287 Error headerString:

2018-01-10 19:45:18.8204 Error Failed to get the release list: NotImplemented
2018-01-10 19:45:18.8240 Error Error checking for updates. System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.Enumerable.Where[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult]
 predicate) [0x00060] in /SRC/mono-5.4.1.6/external/corefx/src/System.Linq/src/System/Linq/Where.cs:45
  at Jackett.Services.UpdateService+<CheckForUpdates>d__12.MoveNext () [0x0015c] in C:\projects\jackett\src\Jackett.Comm
on\Services\UpdateService.cs:112

**Comment by kaso17** [comment] 2018-01-13 16:53
Please post the output of `curl -v https://api.github.com/repos/Jackett/Jackett/releases`.
It looks like you've updated to mono 5.4 without BTLS support. Where did you get it from? Which exact platform are you using?

**Comment by Zhoth** [comment] 2018-01-13 18:23
Here the output of the curl:
[output.txt](https://github.com/Jackett/Jackett/files/1628614/output.txt)

I've a QNap NAS with an ARM CPU. I download Mono from this site: https://qnapclub.eu/it/qpkg/343

**Comment by kaso17** [comment] 2018-01-16 10:18
See my post at https://www.forum-nas.fr/viewtopic.php?f=21&t=1523&p=58251#p58251
It's most likely caused by an ancient gcc version used for your QNAT device.
Additionally there is probably some problem with the libcurl integration on the platform too.
Please try using jackett with the safecurl client (`-c safecurl` command line option).

**Comment by Zhoth** [comment] 2018-01-16 20:51
@kaso17  thanks. When a new build of QMono will be released I'll test again and let you know!

**Comment by kriegalex** [comment] 2018-02-11 00:02
They changed their password encryption so all users must change their password, check that before continuing investigating

**Closed** 2018-02-12 15:20 UTC
