### ISSUE TITLE
[torrent9clone] Exception (torrent9clone): Specified argument was out of the range of valid values.Parameter name: Unknown operator: : Specified argument was out of the range of valid values.Parameter name: Unknown operator:  (Test)

### ISSUE THREAD

**Issue by Oz246** [Jackett/Jackett#5305] opened 2019-05-20 13:41 UTC
Hello,

I encounter the same problem on all indexers.

Jackett.Common.IndexerException: Exception (torrent9clone): Specified argument was out of the range of valid values.
Parameter name: Unknown operator: ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Unknown operator:

Current: v0.11.356 
Mono : Yes

**Comment by garfield69** [comment] 2019-05-20 19:33
duplicate of #5052 which is a duplicate of ticket #4982 which tracks the progress of waiting for the 3rd party cloudflareutilities library to get updated.

**Closed by garfield69** 2019-05-20 19:33 UTC
