### ISSUE TITLE
Exception (shareisland-api): Error while parsing field=downloadvolumefactor

### ISSUE THREAD

**Issue by gipasoft** [Jackett/Jackett#12937] opened 2022-02-10 21:26 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://localhost:8191/
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.17.638-ls23)
File /etc/issue: Ubuntu 18.04.5 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.60.0 (64bit OS) (64bit process)
Environment version: 6.0.2 (/app/Jackett/)
Starting Jackett v0.20.539
```

### Description

When i try to test `ShareIsland (API)` indexer i obtain the error below.
In attachment enhanced log

[log.txt](https://github.com/Jackett/Jackett/files/8044362/log.txt)

### Logged Error Messages

```text
Exception (shareisland-api): Error while parsing field=downloadvolumefactor, selector=freeleech, value=0%: Input string was not in a correct format.: Error while parsing field=downloadvolumefactor, selector=freeleech, value=0%: Input string was not in a correct format.
```

**Comment by garfield69** [comment] 2022-02-10 21:28
duplicate of #12936

**Closed by garfield69** 2022-02-10 21:28 UTC
Labels: Duplicate
