### ISSUE TITLE
[torrent9clone] Exception (torrent9clone): Specified argument was out of the range of valid values.Parameter name: Unknown operator: : Specified argument was out of the range of valid values.Parameter name: Unknown operator:  (Test)

### ISSUE THREAD

**Issue by Jamyz** [Jackett/Jackett#5052] opened 2019-04-10 07:30 UTC
**Jackett version**:  Jackett Version 0.11.205.0 Docker
**Mono version**: Jackett Version 0.11.205.0 Docker

**Comment by garfield69** [comment] 2019-04-10 07:59
duplicate of #4982

**Comment by garfield69** [comment] 2019-08-22 19:50
solved with Jackett 0.11.635

**Closed** 2019-08-22 19:53 UTC
Labels: Duplicate
