### ISSUE TITLE
[yggtorrent] Login failed: No form found

### ISSUE THREAD

**Issue by mushuthecat** [Jackett/Jackett#12543] opened 2021-11-12 16:58 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-11-12 17:52:55 	Info 	

Loading Native indexers ...

2021-11-12 17:52:55 	Info 	

Using HTTP Client: HttpWebClient2

2021-11-12 17:52:55 	Info 	

Using FlareSolverr: http://192.168.1.213:8191

2021-11-12 17:52:55 	Info 	

Using proxy: Disabled

2021-11-12 17:52:55 	Info 	

App config/log directory: /config/Jackett

2021-11-12 17:52:55 	Info 	

ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads

2021-11-12 17:52:55 	Info 	

Running in Docker: Yes (image build: v0.19.228-ls50)

2021-11-12 17:52:55 	Info 	

File /etc/issue: Ubuntu 18.04.6 LTS \n \l

2021-11-12 17:52:55 	Info 	

Jackett variant: CoreLinuxArm32

2021-11-12 17:52:55 	Info 	

OS version: Unix 5.10.63.7

2021-11-12 17:52:55 	Info 	

Environment version: 5.0.12 (/app/Jackett/)

2021-11-12 17:52:48 	Info 	

Starting Jackett v0.19.228

-------FLARESOLVER------

-- | --
msg | "FlareSolverr is ready!"
version | "v2.0.2"
userAgent | "Mozilla/5.0 (X11; Linux …o/20100101 Firefox/89.0"

```

### Description

Sometimes my Sonarr and Radarr are not able to use my YGG indexer returning the message:
[yggtorrent] Login failed: No form found

To Solve this issue i have to edit my YGG indexer configuration (without performing any modification) from jackett and try again to test my YGG indexer from radarr and sonarr and it works.

### Logged Error Messages

[yggtorrent] Login failed: No form found

**Comment by garfield69** [comment] 2021-11-12 18:05
duplicate of #12168
follow that ticket for any progress on this issue.
In the mean time just continue doing what you are doing to restore the indexer's access to web site.

**Closed by garfield69** 2021-11-12 18:05 UTC
