### ISSUE TITLE
[fouducinema] Exception (fouducinema): Login failed: No form found on https://fou-du-cinema.net/login.php

### ISSUE THREAD

**Issue by tingisinfo** [Jackett/Jackett#13142] opened 2022-04-14 03:01 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
build_version	Linuxserver.io version:- v0.20.723-ls58 Build-date:- 2022-03-17T00:23:28-05:00
com.docker.compose.config-hash	041d2e410f5bf759d47ec9dc39f8286b028631fbed3368cc1de7714f9d77721f
com.docker.compose.container-number	1
com.docker.compose.oneoff	False
com.docker.compose.project	jackett
com.docker.compose.project.config_files	/data/compose/29/docker-compose.yml
com.docker.compose.project.working_dir	/data/compose/29
com.docker.compose.service	jackett
com.docker.compose.version	1.27.4
deunhealth.restart.on.unhealthy	true
diun.enable	true
maintainer	thelamer
org.opencontainers.image.authors	linuxserver.io
org.opencontainers.image.created	2022-03-17T00:23:28-05:00
org.opencontainers.image.description	[Jackett](https://github.com/Jackett/Jackett) works as a proxy server: it translates queries from apps (Sonarr, SickRage, CouchPotato, Mylar, etc) into tracker-site-specific http queries, parses the html response, then sends results back to the requesting software. This allows for getting recent uploads (like RSS) and performing searches. Jackett is a single repository of maintained indexer scraping & translation logic - removing the burden from other apps.
org.opencontainers.image.documentation	https://docs.linuxserver.io/images/docker-jackett
org.opencontainers.image.licenses	GPL-3.0-only
org.opencontainers.image.ref.name	416aa6a8ac6b530de48c6d5d4e8143ddc147c63c
org.opencontainers.image.revision	416aa6a8ac6b530de48c6d5d4e8143ddc147c63c
org.opencontainers.image.source	https://github.com/linuxserver/docker-jackett
org.opencontainers.image.title	Jackett
org.opencontainers.image.url	https://github.com/linuxserver/docker-jackett/packages
org.opencontainers.image.vendor	linuxserver.io
org.opencontainers.image.version	v0.20.723-ls58
```

### Description

Login failed: No form found on https://fou-du-cinema.net/login.php
the page https://fou-du-cinema.net/login.php migrate to https://fou-du-cinema.net/account-login.php

### Logged Error Messages

```text
Exception (fouducinema): Login failed: No form found on https://fou-du-cinema.net/login.php using form selector form[action="/login.php"]: Parse error
```

**Comment by garfield69** [comment] 2022-04-14 03:27
Closing this as a duplicate of #13129 
We will be releasing the revised indexer for the web site's new TT3.0 engine shortly in about 2.5 hours.

**Closed by garfield69** 2022-04-14 03:27 UTC
