### ISSUE TITLE
[yourbittorrent] (testing) Exception (yourbittorrent): error:140943E8:SSL routines:ssl3_read_bytes:reason(1000): The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by khalith** [Jackett/Jackett#13701] opened 2022-11-08 10:41 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while testing this indexer
Exception (yourbittorrent): error:140943E8:SSL routines:ssl3_read_bytes:reason(1000): The SSL connection could not be established, see inner exception.
```

### Description

An error occurred while testing this indexer
Exception (yourbittorrent): error:140943E8:SSL routines:ssl3_read_bytes:reason(1000): The SSL connection could not be established, see inner exception.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (yourbittorrent): error:140943E8:SSL routines:ssl3_read_bytes:reason(1000): The SSL connection could not be established, see inner exception.
```

**Comment by garfield69** [comment] 2022-11-08 18:52
closing as a duplicate of #13700

**Closed by garfield69** 2022-11-08 18:52 UTC
