### ISSUE TITLE
[Diablo Torrent] - Configuration failed: Login failed: No form found using form selector form

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#1201] opened 2017-03-26 16:04 UTC
I'm getting the following error when I try to configure Diablo Torrent:

Configuration failed: Login failed: No form found on https://diablotorrent.net/login.php using form selector form. Strangely, the enhanced log shows nothing related to this error so I'm not sure that including it here would be helpful.

Did Diablo Torrent change something recently? Is anyone else having this issue?

Jackett version:  0.7.1197.0
Mono version (if not using Windows):  N/A

**Comment by kaso17** [comment] 2017-03-28 18:51
they made some bigger changes, will fix it later

**Comment by RoloSoze** [comment] 2017-03-28 19:51
@JigSawFr What does the 'Provider' label mean?

**Comment by JigSawFr** [comment] 2017-03-28 20:04
@RoloSoze 'Provider' label is for every issue in relationship of an existing indexer (except for a new tracker, we use 'New Tracker' label).
Until an issue is confirmed or we take time to take a look, we use 'Needs Investigation' (aka something to do - backlog), after that, this label is dropped and replaced by 'Confirmed' (if problem exist), 'Won't fix' (if it's intended behavior or team decision), or 'Can't reproduce'
'Question' for discussions about a feature / proposition
'Help wanted' if we need help from 3rd party or someone
'Core' for everything not related to indexers/trackers
'Enhancement' & 'Invite needed' for what you know ;)

**Comment by RoloSoze** [comment] 2017-03-28 20:11
@JigSawFr Thanks a lot for the explanation! I was familiar with all the labels except 'Provider' :)

**Comment by kaso17** [comment] 2017-10-25 15:49
fixed some time ago

**Closed by kaso17** 2017-10-25 15:49 UTC
Labels: Confirmed, Provider
