### ISSUE TITLE
Jacket Install Bug Password

### ISSUE THREAD

**Issue by Tpsw242** [Jackett/Jackett#4024] opened 2018-10-18 12:26 UTC
Hello everyone, I tried to install jackett but he ask an admin password every time. I rm the config file ServerConfig.json, fill with “Password”= null, I uninstalled and installed again, but always the same thing.

Someone has an idea ?

**Comment by garfield69** [comment] 2018-10-18 18:16
duplicate of #2335
stop jackett, 
edit the ~/.config/Jackett/ServerConfig.json file and change the AdminPassword line to this:
`"AdminPassword": null,`
Start Jackett again and there should be no password.

**Closed by garfield69** 2018-10-18 18:16 UTC
