### ISSUE TITLE
[Req] Add support for purovicio.pw

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#5624] opened 2019-07-09 18:59 UTC
It's a private tracker with content in Spanish language. The layout is really similar to Blutopia.
You can request an invitation in this Discord channel => https://discordapp.com/channels/441435547882487810/441435547882487812
https://purovicio.pw

**Comment by tkdrob** [comment] 2019-07-09 22:40
Duplicate of #5573

**Closed** 2019-07-28 05:52 UTC
Labels: Duplicate
