### ISSUE TITLE
Update Jackett fails with timeout across versions for at least a month

### ISSUE THREAD

**Issue by porter9992** [Jackett/Jackett#15309] opened 2024-05-14 15:51 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.0.13:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Starting Jackett v0.21.2592
DNS:  DNSCrypt
```

### Description

For at least the last months, manually clicking 'check for updates' results with an error trying to update.

I have tried many manual updates & uninstall/reinstalls, re-setting-up through the Web UI, but no change.

### Logged Error Messages

```text
2024-05-14 10:36:04.1534 Info Request finished HTTP/1.1 GET http://localhost:9117/api/v2.0/server/logs?_=1715700699421 - - - 200 - application/json;+charset=utf-8 833.3744ms
2024-05-14 10:36:56.0160 Error Error performing update.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 300 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Services.UpdateService.DownloadRelease(List`1 assets, Boolean isWindows, String version) in ./Jackett.Common/Services/UpdateService.cs:line 238
   at Jackett.Common.Services.UpdateService.CheckForUpdates() in ./Jackett.Common/Services/UpdateService.cs:line 133
```

### Screenshots

[log - Copy (2).txt](https://github.com/Jackett/Jackett/files/15310917/log.-.Copy.2.txt)

**Comment by ilike2burnthing** [comment] 2024-05-14 16:11
Do you have an extremely slow connection?

How long does it take to download the following file in browser from the same device and IP?

https://github.com/Jackett/Jackett/releases/download/v0.21.2597/Jackett.Binaries.Windows.zip

**Comment by porter9992** [comment] 2024-05-14 16:47
It seems I do @ ~100-350Kbps from Github (Line is 100Mbps).  Multiple streams accumulate to high speeds fine. 
My VPN provider & I have been working on why the limitation is occurring.

**Comment by ilike2burnthing** [comment] 2024-05-14 16:52
Normal timeout is 100s, this was previously increased for update downloads to 300s - https://github.com/Jackett/Jackett/commit/4a6d630076abeeb2fce1f0d6795a3548a8a3499a

Closing as the issue is external to Jackett.

**Closed by ilike2burnthing** 2024-05-14 16:52 UTC
