### ISSUE TITLE
[yggtorrent] Login failed: Selector

### ISSUE THREAD

**Issue by darkpisto** [Jackett/Jackett#2219] opened 2017-12-01 19:24 UTC
Hello,

Sorry i don't speak english very well ;)

I can't connect to yggtorrent because the url was https://yggtorrent.com and become https://ww1.yggtorrent.com

The "ww1" cause an error : 

>  An error occured while updating this indexer
> Login failed: Selector "a[href="https://yggtorrent.com/user/logout"]" didn't match

And use https://yggtorrent.com or https://www.yggtorrent.com dosen't work because it cause an error : 

>  An error occured while updating this indexer
> Login Failed, got redirected

Thanks in advance.

Bests regards.

**Comment by garfield69** [comment] 2017-12-01 19:27
Please upgrade to the latest Jackett v0.8.485 and try again. 
Duplicate of #2211

**Closed by garfield69** 2017-12-01 19:27 UTC
