### ISSUE TITLE
[empornium] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Issam220405** [Jackett/Jackett#8967] opened 2020-06-13 09:58 UTC
### Environment

**OS**: Ubuntu 20.04 server ARM64

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.704

**Last Working Jackett Version**: 0.16.571

**Are you using a proxy or VPN?** [yes/no] no

### Logged Error Messages

System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 277
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

**Comment by garfield69** [comment] 2020-06-13 19:15
No one on the team has an account on this web site, so we cannot research this independently.
If you have an invite you could sent  to garfieldsixtynine -at- gmail.com it would probably help make investigating and resolving this easier.
Otherwise, we are going to need to see what the web site is sending the indexer, so please provide a **full enhanced** log file which will include debug and HTML.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Issam220405** [comment] 2020-06-20 15:11
Thanks for the reply. I sent you an invite.

**Comment by garfield69** [comment] 2020-06-20 19:43
Registration and login successful, Thank you.

**Comment by garfield69** [comment] 2020-06-20 20:00
The indexer appears to be working for me which suggest the problem is at your end.
I suggest starting by logging to the site with your browser and confirming that you have a good ratio, and that there are not outstanding alerts, notices or PM that could block your access to the torrent search page.
If you can access the torrent search page with your browser, then let me know and we move on to the next step.

**Closed** 2020-06-22 19:21 UTC
Labels: Full logs needed, More information needed
