### ISSUE TITLE
Unable to configure MyAnonamouse

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#794] opened 2016-12-04 00:48 UTC
Even though I'm using my email, instead of username, to login, as instructed. 

2016-12-04 03:47:10.5550 Info Found 0 releases from Myanonamouse 
2016-12-04 03:47:10.5550 Error Exception in Configure System.Exception: Found no results while trying to browse this tracker
   at Jackett.Services.IndexerManagerService.<TestIndexer>d__11.MoveNext() in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Configure>d__16.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 190

**Comment by kaso17** [comment] 2016-12-04 14:47
looks like a duplicate of #375
I need an invite (kaso1717 -at- gmail.com) to fix it.

**Closed by kaso17** 2016-12-04 14:47 UTC

**Comment by armani316** [comment] 2016-12-04 15:18
@kaso17 I've arranged for one to be sent. Check your Gmail soon, and confirm once you receive it. Thanks.

**Comment by kaso17** [comment] 2016-12-04 18:32
got it, thank you
