### ISSUE TITLE
Polishsource dont like Jackett.

### ISSUE THREAD

**Issue by FloydKulis** [Jackett/Jackett#10163] opened 2020-11-10 13:56 UTC
### Environment

**OS**: Qnap NAS

Version 0.16.2124.0 Qmono

Polishsource doesn't like Jackett, unfortunately their terms and conditions prohibit scripting through php. The only possibility is rss. Hence, for example, I got a ban because of too many connections via the website. Probably the fault is not Jackett itself, but also Radarr who was checking the next items.

**Comment by garfield69** [comment] 2020-11-10 20:30
Are you suggesting (requesting) that we remove the indexer from Jackett?
OR requesting a rewrite of the indexer to use their RSS feed?
@ngosang  can you look to see if that is feasible as you have an a/c on the site.

**Comment by ngosang** [comment] 2020-11-11 19:57
The RSS only supports recent torrents. I have been using this tracker with Jackett for months without bans. I think the user is not using Jackett well, we are just a tool.

**Comment by piotrpachalko** [comment] 2020-11-12 12:30
@garfield69 @ngosang I can confirm that Polishsource is recently giving out bans for hitting browse.php from a script (It's part of their ToS). It's possible that more users will be affected in the coming days. 
ATM I see no workaround - their RSS feed, although configurable, only provides max 100 of recent items.
Continuing to use this indexer might hurt user's accounts, especially when combined with something like Radarr.

**Comment by ngosang** [comment] 2020-11-12 14:57
Could you PM the staff to see if they can add API support or another alternative? If not we will have to remove the tracker from Jackett.

**Comment by ilike2burnthing** [comment] 2020-11-26 15:17
@piotrpachalko @FloydKulis ping

**Comment by dolohow** [comment] 2020-11-26 15:45
I use it, and I am yet to receive a ban. I remember asking stuff member about using jackett 6 months ago, and they were ok with that as long it is not a seed box ip.  Perhaps things changed since then. Anyway from time to time I need to relogin manually because there is a captcha.  Frankly it's quite annoying.

**Comment by piotrpachalko** [comment] 2020-11-26 15:51
Using scrips/automation is forbidden, according to their ToS. So you might got lucky by not drawing too much attention.
> as long it is not a seed box ip
That's the problem, seedboxes with Radarr/Sonnar are perhaps too aggressive with searches and that raises red flag with Polishsource admins.

**Comment by ilike2burnthing** [comment] 2020-11-27 13:59
Current forum thread - https://polishsource.cz/forums.php?action=viewtopic&topicid=12058

Previously they had said that use through Radarr and Sonarr (and therefore Jackett) was fine if it wasn't abused, "It is allowed, although users often use it unreasonably - too frequent refresh, which results in sending a large number of queries to the PS and for which we ban [...] Refresh let it not be more than 5 minutes." - https://polishsource.cz/forums.php?action=viewtopic&topicid=12271

**Comment by chaostheory22** [comment] 2020-12-10 09:04
Confirming I got banned for using Jackett on PolishSource. I had my Radarr/Sonarr setup to refresh RSS every 120 minutes. 

They're certainly cracking down on this. 

@garfield69

**Comment by garfield69** [comment] 2020-12-10 09:29
#10382 may help once completed.

**Comment by piotrpachalko** [comment] 2020-12-10 10:30
@garfield69 I wouldn't get my hopes up with that ticket. The reason for ban is not because of high frequency of Jackett searches. It's rather the fact that: 
(a) it searches by submitting to browse.php url (breach of T&C) and 
(b) it's often done from seedbox's IP address (another prohibited action)

**Comment by chaostheory22** [comment] 2020-12-11 11:45
@piotrpachalko In my case it wasn't from seedbox: radarr/sonarr is on my home network.
@garfield69 I'm not a developer myself, but is it possible to rewrite Jackett for PolishSource with the current state of tracker? Admins are quiet about any API access.

**Comment by ngosang** [comment] 2020-12-11 22:16
1. New Jackett cache is merged and will be released tomorrow. It will help to reduce the number of queries to the site.
2. As I said before Jackett is just a tool and we are not responsible for the bans. 1 request to Jackett = 1 request to Polishsource.
3. If the site admin request us to remove the support for this site because we are causing high load, we will comply.

**Comment by ilike2burnthing** [comment] 2020-12-28 12:16
There's been no reply from PS admins to any of the open forum posts about the use of Jackett, so they can't be that concerned. I've had PS in Jackett since before this issue was opened, no issues, so I'm closing this for now. If any clarification is provided, feel free to reopen and we can take any necessary steps.

**Closed by ilike2burnthing** 2020-12-28 12:16 UTC
Labels: Down / Waiting for removal

**Comment by Zeuskk** [comment] 2021-01-09 21:44
How can I reduce number of requests by Jacket to Polishsource? Should I increase Cache TTL (seconds)?

**Comment by ilike2burnthing** [comment] 2021-01-09 22:03
That and/or increase the sync intervals for Sonarr/Radarr/*arr.

**Comment by Zeuskk** [comment] 2021-01-09 22:24
You mean RSS Sync Interval? Now this RSS Sync is confusing me because I made Polishsource indexer in Sonarr/Radarr using Torznab Custom and pasted Torznab Feed from Jackett. Should I add it with Torrent RSS Feed?

**Comment by ilike2burnthing** [comment] 2021-01-10 00:18
RSS Sync Interval, yes, and Torznab Custom is correct.
