### ISSUE TITLE
Horrible Subs - Cannot Change Site Link

### ISSUE THREAD

**Issue by Gingey231** [Jackett/Jackett#3421] opened 2018-07-18 23:40 UTC
**Jackett version**:  0.9.6.0
**OS** - Windows Server 2016

-------------------------------
Hey guys, seem to get this issue every now and again, but seems to stop after a while. I seem to be having a problem amending the site link for HorribleSubs. I amend the link to what I want it to be, hit save, but it just does not save the modifications at all. Re-open the configuration for the tracker and still shows the old site link. Only seems to be happening for HorribleSubs constantly.

**Please find the log here:** https://pastebin.com/K1MtaG3k

I know there is a current open ticket (#3318 ) however thats just saying that its presenting the error that it doesn't like the `http://`, BUT my site link wont change so putting in another link just flat out wont save 😛

**Comment by flightlevel** [comment] 2018-07-19 10:57
Duplicate of #3318

**Closed by flightlevel** 2018-07-19 10:57 UTC
