### ISSUE TITLE
No Results Found

### ISSUE THREAD

**Issue by darkspadez** [Jackett/Jackett#1407] opened 2017-05-23 02:12 UTC
Currently receiving no results found for all my trackers.

Jackett version:  0.7.1437.0
Mono version (if not using Windows):  5.0.0

```
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info   http://10.1.0.17:5002/Admin/test_indexer
May 22 22:05:22 nexus mono: System.Web.Http.Request:   http://10.1.0.17:5002/Admin/test_indexer
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info WebAPIRequestLogger SendAsync
May 22 22:05:22 nexus mono: System.Web.Http.MessageHandlers: WebAPIRequestLogger SendAsync
May 22 22:05:22 nexus mono: {"indexer":"iptorrents"}
May 22 22:05:22 nexus mono: 05-22 22:05:22 Debug POST: http://10.1.0.17:5002/Admin/test_indexer
May 22 22:05:22 nexus mono: 05-22 22:05:22 Debug Body: {"indexer":"iptorrents"}
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
May 22 22:05:22 nexus mono: System.Web.Http.Controllers: DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]'
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info DefaultHttpControllerSelector SelectController Admin
May 22 22:05:22 nexus mono: System.Web.Http.Controllers: DefaultHttpControllerSelector SelectController Admin
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info HttpControllerDescriptor CreateController
May 22 22:05:22 nexus mono: System.Web.Http.Controllers: HttpControllerDescriptor CreateController
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info DefaultHttpControllerActivator Create
May 22 22:05:22 nexus mono: System.Web.Http.Controllers: DefaultHttpControllerActivator Create
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
May 22 22:05:22 nexus mono: System.Web.Http.Controllers: DefaultHttpControllerActivator Create Jackett.Controllers.AdminController
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
May 22 22:05:22 nexus mono: System.Web.Http.Controllers: HttpControllerDescriptor CreateController Jackett.Controllers.AdminController
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info AdminController ExecuteAsync
May 22 22:05:22 nexus mono: System.Web.Http.Controllers: AdminController ExecuteAsync
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info ApiControllerActionSelector SelectAction
May 22 22:05:22 nexus mono: System.Web.Http.Action: ApiControllerActionSelector SelectAction
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info ApiControllerActionSelector SelectAction Selected action 'Test()'
May 22 22:05:22 nexus mono: System.Web.Http.Action: ApiControllerActionSelector SelectAction Selected action 'Test()'
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info JackettAuthorizedAttribute OnAuthorizationAsync
May 22 22:05:22 nexus mono: System.Web.Http.Filters: JackettAuthorizedAttribute OnAuthorizationAsync
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info JackettAuthorizedAttribute OnAuthorizationAsync
May 22 22:05:22 nexus mono: System.Web.Http.Filters: JackettAuthorizedAttribute OnAuthorizationAsync
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info HttpActionBinding ExecuteBindingAsync
May 22 22:05:22 nexus mono: System.Web.Http.ModelBinding: HttpActionBinding ExecuteBindingAsync
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info HttpActionBinding ExecuteBindingAsync
May 22 22:05:22 nexus mono: System.Web.Http.ModelBinding: HttpActionBinding ExecuteBindingAsync
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
May 22 22:05:22 nexus mono: System.Web.Http.Filters: JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()'
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info JackettAPINoCacheAttribute OnActionExecutingAsync
May 22 22:05:22 nexus mono: System.Web.Http.Filters: JackettAPINoCacheAttribute OnActionExecutingAsync
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info ApiControllerActionInvoker InvokeActionAsync Action='Test()'
May 22 22:05:22 nexus mono: System.Web.Http.Action: ApiControllerActionInvoker InvokeActionAsync Action='Test()'
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
May 22 22:05:22 nexus mono: System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
May 22 22:05:22 nexus mono: 05-22 22:05:22 Debug IWebClient.GetString(Url:https://iptorrents.com/t)
May 22 22:05:22 nexus mono: 05-22 22:05:22 Error got NotImplemented/InternalServerError
May 22 22:05:22 nexus mono: 05-22 22:05:22 Error request.Method: GET
May 22 22:05:22 nexus mono: 05-22 22:05:22 Error request.Url: https://iptorrents.com/t
May 22 22:05:22 nexus mono: 05-22 22:05:22 Error request.Cookies: 
May 22 22:05:22 nexus mono: 05-22 22:05:22 Error request.Referer: https://iptorrents.com/t
May 22 22:05:22 nexus mono: 05-22 22:05:22 Error request.RawPOSTDdata:
May 22 22:05:22 nexus mono: 05-22 22:05:22 Error cookies:
May 22 22:05:22 nexus mono: 05-22 22:05:22 Error headerString:
May 22 22:05:22 nexus mono:
May 22 22:05:22 nexus mono: 05-22 22:05:22 Debug IWebClient: Returning NotImplemented =>
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info Found 0 releases from IPTorrents
May 22 22:05:22 nexus mono: 05-22 22:05:22 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
May 22 22:05:22 nexus mono:  at Jackett.Services.IndexerManagerService+<TestIndexer>c__async0.MoveNext () [0x00106] in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:171
May 22 22:05:22 nexus mono: --- End of stack trace from previous location where exception was thrown ---
May 22 22:05:22 nexus mono:  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /builddir/build/BUILD/mono-5.0.0/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151
May 22 22:05:22 nexus mono:  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /builddir/build/BUILD/mono-5.0.0/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
May 22 22:05:22 nexus mono:  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /builddir/build/BUILD/mono-5.0.0/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
May 22 22:05:22 nexus mono:  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /builddir/build/BUILD/mono-5.0.0/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
May 22 22:05:22 nexus mono:  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /builddir/build/BUILD/mono-5.0.0/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113
May 22 22:05:22 nexus mono:  at Jackett.Controllers.AdminController+<Test>c__async5.MoveNext () [0x000da] in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:269
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]'
May 22 22:05:22 nexus mono: System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]'
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info ApiControllerActionInvoker InvokeActionAsync
May 22 22:05:22 nexus mono: System.Web.Http.Action: ApiControllerActionInvoker InvokeActionAsync
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
May 22 22:05:22 nexus mono: System.Web.Http.Filters: JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info JackettAPINoCacheAttribute OnActionExecutedAsync
May 22 22:05:22 nexus mono: System.Web.Http.Filters: JackettAPINoCacheAttribute OnActionExecutedAsync
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info AdminController ExecuteAsync
May 22 22:05:22 nexus mono: System.Web.Http.Controllers: AdminController ExecuteAsync
May 22 22:05:22 nexus mono: {"result":"error","error":"Found no results while trying to browse this tracker"}
May 22 22:05:22 nexus mono: 05-22 22:05:22 Debug Response: {"result":"error","error":"Found no results while trying to browse this tracker"}
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info WebAPIRequestLogger SendAsync
May 22 22:05:22 nexus mono: System.Web.Http.MessageHandlers: WebAPIRequestLogger SendAsync
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info   Content-type='application/json; charset=utf-8', content-length=81
May 22 22:05:22 nexus mono: System.Web.Http.Request:   Content-type='application/json; charset=utf-8', content-length=81
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info AdminController Dispose
May 22 22:05:22 nexus mono: System.Web.Http.Controllers: AdminController Dispose
May 22 22:05:22 nexus mono: 05-22 22:05:22 Info AdminController Dispose
May 22 22:05:22 nexus mono: System.Web.Http.Controllers: AdminController Dispose
```

**Comment by fryfrog** [comment] 2017-05-24 05:30
If you're using a systemd unit file, try
```
# /etc/systemd/system/jackett.service.d/override.conf
[Service]
Environment=MONO_TLS_PROVIDER=legacy
```

If you're not, get `MONO_TLS_PROVIDER=legacy` into your start command.

The new default TLS provider has issues. I've seen it in Arch and someone on CentOS using the Mono rpm repositories.

**Comment by darkspadez** [comment] 2017-05-24 23:21
Even by adding that no luck. All my trackers still report `"May 24 19:20:07 nexus mono[1278]: {"result":"error","error":"Found no results while trying to browse this tracker"}"`

**Comment by darkspadez** [comment] 2017-05-24 23:31
Cant even add new Trackers either.

**Comment by BoKKeR** [comment] 2017-06-03 16:08
same issue here.

**Comment by kaso17** [comment] 2017-06-03 16:41
Please try running jackett with `-c httpclient` (remove the `MONO_TLS_PROVIDER=legacy` part before).
And post the output of `curl -v https://iptorrents.com/t`

**Comment by kaso17** [comment] 2017-06-03 20:15
never mind, please try updating to jackett v0.7.1469

**Comment by maxenced** [comment] 2017-06-08 11:58
same issue here, jacket 0.7.1477.0 and mono 4.2.3 . A search works correctly when ran from configured indexer section, but test does not work, and adding torznab url to my radarr setup fail with "no result".

**Comment by maxenced** [comment] 2017-06-08 13:11
just tested with mono 4.6.2, same issue (testing with t411).

**Comment by OppieTV** [comment] 2017-06-08 13:15
Hi,

See few posts about T411 but i'm confused : yesterday, everything alright on my jackett.
Today, fresh install of new server and jackett
T411 on indexer's list with right url but when i try to add T411, i have this :

" Configuration failed: Found no results while trying to browse this tracker"

Jackett version : 0.7.1477.0

Any idea ?

**Comment by maxenced** [comment] 2017-06-08 15:45
Not sure it's related, but when I reproduce with trace I get : 
```
06-08 17:41:16 Debug IWebClient.GetString(Url:https://api.t411.al/torrents/search/?offset=0&limit=200&cat=0&subcat=0)
06-08 17:41:17 Debug IWebClient: Returning OK => <div class="errorMessage">Missing argument 1 for App\Api\Controllers\TorrentsController::searchAction()</div>
<div class="errorMessage">Undefined variable: query</div>
```

**Comment by kaso17** [comment] 2017-06-08 18:56
the Missing argument error is normal. Currently they have > 200 pending torrent releases which are skipped because they contain no details. This hopefully is just a temporary issue.

**Comment by maxenced** [comment] 2017-06-08 18:58
ok, so it doesn't explain where the initial issue comes from

**Comment by kaso17** [comment] 2017-06-08 19:11
@maxenced The initial issue was caused by a mono version detection bug and should be fixed.
In your case you should upgrade to mono 5 first.

**Comment by maxenced** [comment] 2017-06-08 19:29
Mhh, just tried it : 

```
$ mono --version
Mono JIT compiler version 5.5.0.21 (master/0526617 Wed Jun  7 09:36:04 UTC 2017)
```

However when I test the T411 indexer : 
```
 Test failed for t411: Found no results while trying to browse this tracker
```

and in log : 

```
juin 08 21:26:47 server mono[17465]: 06-08 21:26:47 Info Found 0 releases from T411
juin 08 21:26:47 server mono[17465]: 06-08 21:26:47 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
juin 08 21:26:47 server mono[17465]:   at Jackett.Services.IndexerManagerService+<TestIndexer>c__async0.MoveNext () [0x00106] in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:171
juin 08 21:26:47 server mono[17465]: --- End of stack trace from previous location where exception was thrown ---
juin 08 21:26:47 server mono[17465]:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <05eb0e187f3b41be8b0a86c3c35749fb>:0
juin 08 21:26:47 server mono[17465]:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <05eb0e187f3b41be8b0a86c3c35749fb>:0
juin 08 21:26:47 server mono[17465]:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <05eb0e187f3b41be8b0a86c3c35749fb>:0
juin 08 21:26:47 server mono[17465]:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <05eb0e187f3b41be8b0a86c3c35749fb>:0
juin 08 21:26:47 server mono[17465]:   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <05eb0e187f3b41be8b0a86c3c35749fb>:0
juin 08 21:26:47 server mono[17465]:   at Jackett.Controllers.AdminController+<Test>c__async5.MoveNext () [0x000da] in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:269
```

**Comment by maxenced** [comment] 2017-06-10 09:12
Just retested it today, and the test works fine. I changed nothing so I guess there was smthg wrong on t411 side.

Maxence

**Closed** 2017-07-09 15:09 UTC
