### ISSUE TITLE
[REQ] New Tracker Request: Nostalgic.is

### ISSUE THREAD

**Issue by deecypher** [Jackett/Jackett#4033] opened 2018-10-19 15:24 UTC
I would like to add Nostalgic.is as a tracker with Jackett. It is a private tracker but I can provide one of your devs an invite code, so please provide me with an email address.

As for the mapping, I am not personally involved with the site but they have provided the following page as a reference: https://github.com/Empornium/Luminance/

I am not a dev nor do I work for the website, just an avid fan. I can be a go-between if necessary.

Please let me know if you require any more details to get this site attached.

Many thanks

**Comment by garfield69** [comment] 2018-10-19 17:40
I'm closing this as a duplicate of #3795 
I've copied your post across to 3795.

**Closed by garfield69** 2018-10-19 17:40 UTC
Labels: Duplicate
