### ISSUE TITLE
Windows Defender flags JacketConsole.dll as a Trojan

### ISSUE THREAD

**Issue by taximes** [Jackett/Jackett#14562] opened 2023-07-14 05:12 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2 
Using FlareSolverr: No 
Using proxy: Disabled 
App config/log directory: C:\ProgramData\Jackett 
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
Running in Docker: No 
Jackett variant: CoreWindows 
OS version: Microsoft Windows NT 10.0.22621.0 (64bit OS) 
Environment version: 6.0.16 (C:\ProgramData\Jackett\)
```

### Description

Jackett had been working fine, but on 7/13/2023 was flagged by Windows Defender as a threat (specifically, Trojan:Win32/Randet.A!plock). The affected file is JackettConsole.dll

### Logged Error Messages

```text
No Jackett error message because JacketConsole.dll is flagged/quarantined by Windows Defender. 

Detected: Trojan:Win32/Randet.A!plock
Status: Quarantined
File: C:\ProgramData\Jackett\JackettConsole.dll
```

**Comment by garfield69** [comment] 2023-07-14 05:47
closing as a duplicate of https://github.com/Jackett/Jackett/issues/14556

**Closed by garfield69** 2023-07-14 05:47 UTC
