### ISSUE TITLE
[HD-Torrents] Date & time parsing issue

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7450] opened 2020-03-02 10:54 UTC
### Environment

**OS**: Windows 10 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.13.405.0

**Last Working Jackett Version**: Not sure

**Are you using a proxy or VPN?** No

### Description

I'm unable to configure HD-Torrents in Jackett anymore.

### Logged Error Messages

Exception (hdtorrents): String '02="" mar="" 2020="" 13:30:18="" +0200=""' was not recognized as a valid DateTime.: Parse error

### Screenshots

N/A

### Enhanced Log
[log.txt](https://github.com/Jackett/Jackett/files/4274967/log.txt)

**Comment by cadatoiva** [comment] 2020-03-02 16:25
Duplicate of #7426

**Closed by cadatoiva** 2020-03-02 16:25 UTC
