### ISSUE TITLE
[Request] New Tracker Bluetopia

### ISSUE THREAD

**Issue by daddydeadpool** [Jackett/Jackett#1428] opened 2017-05-28 22:32 UTC
Indexer Name
Bluetopia

Type
Movies, TV Shows

URL
https://blutopia.xyz/

Indexer Language
English

Invite only

**Comment by adamwinn** [comment] 2017-05-29 00:52
Duplicate of #1348.  Please search before submitting.

**Closed by adamwinn** 2017-05-29 00:52 UTC

**Comment by daddydeadpool** [comment] 2017-05-29 01:10
odd I did search bluetopia with no results
