### ISSUE TITLE
[uniotaku] Get error and no results on version 0.16.1023.0 (Test)

### ISSUE THREAD

**Issue by samucamg** [Jackett/Jackett#9386] opened 2020-08-24 14:00 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Centos 7

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.1023.0

**Last Working Jackett Version**: 0.14

**Are you using a proxy or VPN?** [yes/no] No

### Description

I get error on testing this tracker.  I test it in two different vpss with two differents users

### Logged Error Messages

 An error occurred while testing this indexer
Found no results while trying to browse this tracker

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by samucamg** [comment] 2020-08-24 14:06
This is not duplicated.  There's no open insue for this problem, and it is not fixed

**Comment by garfield69** [comment] 2020-08-24 19:29
duplicate of #8340 
back in Mid June the site switched the search results presentation from purely HTML based, to a combo of HTML and JS.
The indexer will need to be re-written from yaml to C# in order to process this new presentation.
The ticket is pending a volunteer to code the C# indexer.

**Closed by garfield69** 2020-08-24 19:29 UTC
Labels: Duplicate
