### ISSUE TITLE
[yggtorrent] Line 62: Illegal return statement (Config)

### ISSUE THREAD

**Issue by pace6666** [Jackett/Jackett#8785] opened 2020-05-27 13:35 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.535.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

Tested the indexer and returned error 62

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by RoloSoze** [comment] 2020-05-27 13:37
Duplicate of https://github.com/Jackett/Jackett/issues/8770 - Update to the latest Jackett version to resolve this issue.

**Closed by RoloSoze** 2020-05-27 13:37 UTC
Labels: Duplicate
