### ISSUE TITLE
YGGTorrent Indexer failed

### ISSUE THREAD

**Issue by CerfontaineMathieu** [Jackett/Jackett#3524] opened 2018-08-03 19:11 UTC
Hi, 

I received this error two times in one week : "[yggtorrent] Login failed: No form found on https://ww3.yggtorrent.is/ using form selector form[action$=..."

YGGTorrent have changed their hostname recently. Is there an solution for this error ? I got it every time they have to change the hostname of the website.

THank you

**Comment by stephane-r** [comment] 2018-08-03 19:48
Same result. The cause is the selector `form[action$="/user/login"]` is empty and must be replace by `form[action$="https://ww3.yggtorrent.is/user/login"]`

I think is a very bad idea to add domain name on form action ...

**Comment by stephane-r** [comment] 2018-08-03 19:50
Same result. Yet the selector `form[action$="/user/login"]` is find :/

**Comment by flightlevel** [comment] 2018-08-04 06:59
Duplicate of #3519

**Closed by flightlevel** 2018-08-04 06:59 UTC
