### ISSUE TITLE
HTTP error 310 in uTorrent and unsuccessful downloads in qBittorrent.

### ISSUE THREAD

**Issue by jollemannen** [Jackett/Jackett#5875] opened 2019-08-17 13:34 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

Hi i have been using Jackett with qbit for some time now and recently I have been getting some issues. Specifically that it can't download some RSS articles that are magnet links or redirects to magnet like 1337x that has a secondary page for the torrent details. I tried to see if it is a client issue by switching to uTorrent/Bittorrent/Transmission and I got a 310 Too many redirects on uTorrent/Bittorret and on Transmission it also wouldn't get added. The weird thing is that the provided redirection link works via the browser.

I think the issue is related to the redirect to magnet links that jackett does on indexers with a torrent details page.

Have a nice day:)

OS: Windows 10 x64
Jackett version: latest as of this moment.

**Comment by ngosang** [comment] 2020-01-14 18:27
Confirmed in qBittorrent 4.2.1.
Reported => https://github.com/qbittorrent/qBittorrent/issues/11877
I don't think we can fix that. Has to be fixed in third party apps. Other apps like Sonarr works well.

**Comment by ngosang** [comment] 2020-01-14 18:39
Related to => #5835

**Comment by ngosang** [comment] 2020-03-29 17:55
Fixed in qBittorrent v4.2.2 => https://github.com/qbittorrent/qBittorrent/issues/11877

**Comment by garfield69** [comment] 2020-04-13 07:49
possibly fixed with Jackett 0.15.36

**Comment by RoloSoze** [comment] 2020-04-23 03:00
@jollemannen Did updating to version 0.15.36, or later, fix this issue for you?

**Comment by garfield69** [comment] 2021-09-16 01:28
no reply by OP since Apr 2020. Presumed fixed. May report if we get confirmation it is unresolved.

**Closed by garfield69** 2021-09-16 01:28 UTC
Labels: Confirmed
