### ISSUE TITLE
[req]: Wolf4kMAX Spanish Uploader

### ISSUE THREAD

**Issue by Crosus97** [Jackett/Jackett#14895] opened 2023-12-08 21:54 UTC
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Wolf4KMAX
- URL: https://wolfmax4k.com/
- Description: NEW Best Spanish public Tracker
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments: Im from spain i usually use DonTorrent Tracker to download the movies, and im very sure that recently DonTorrent, re-upload the wolf4kmax Content, there is anykind of way to use this in jackett?
TY
```

**Comment by garfield69** [comment] 2023-12-09 01:52
duplicate of #14511

**Closed by garfield69** 2023-12-09 01:52 UTC
