### ISSUE TITLE
RARBG not grabbing torrents from RSS

### ISSUE THREAD

**Issue by samsepiol59** [Jackett/Jackett#4689] opened 2019-02-15 01:40 UTC
**Jackett version**:  0.10.739.0
**Mono version** (if not using Windows):  latest one

-------------------------------

Files from RARBG are not grabbed by RSS - they are seen, but grabbing fails. Automatic search grabs them.

HTTP Error - Res: [GET] http://lw704.ultraseedbox.com:32279/dl/rarbg/?jackett_apikey=(removed)&path=Q2ZESjhIQXhmRkFfdFg5Rm1vYzI5eUlFRHJfMERnZGNycWFxOUVqWGYzazlWR1JqTFlFOWMyOXdWUDRWTy12Um54aF9SX1M1YmtMZVdEN0lPN20tZGNBSlhFQk1UcUNrc0dmSnJqNjdiTzdrLVpWc0U3NWFleFlRUzdaVjVZRmlQdTlyN3EtTnR1RXhOaFUyU2JxQWJjSkFMdzBZenExSHU4cVNjQ2pMcnJXdE5OU01ZOVptWTEtYmtuZUdWSE1wZGhYN2xQa2FaRjNKOEdnVTVWMVFQTUFHRFZfc1dpRnlsdVlwZWtZQ0d5NGRBYVlv&file=At.Eternitys.Gate.2018.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT: 404.NotFound

**Comment by garfield69** [comment] 2019-02-15 01:54
duplicate of #4584.

**Closed by garfield69** 2019-02-15 01:54 UTC
Labels: Duplicate
