### ISSUE TITLE
[noname-clubl] The SSL connection could not be established, see inner exception.: Authentication failed, see inner exception. (Config)

### ISSUE THREAD

**Issue by Napalmcold** [Jackett/Jackett#11933] opened 2021-06-18 11:17 UTC
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Synology/Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 

**Jackett Version**: v0.18.354

**Last Working Jackett Version**: unknown

**Are you using a proxy or VPN?**: yes

### Description

Indexer "NoNaMe club"  stopped working. 

![image](https://user-images.githubusercontent.com/32687587/122553045-c44f9900-d03f-11eb-8505-ed6414cd9b1b.png)

Also cannot add "NoNaMe ClubL"
![image](https://user-images.githubusercontent.com/32687587/122552911-9407fa80-d03f-11eb-9882-e259f976aa9f.png)

### Logged Error Messages

2021-06-18 14:08:13 | Error | Jackett.Common.IndexerException: Exception (noname-club): error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure  ---&gt; System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.  ---&gt; System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.  ---&gt; Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.  ---&gt; Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure    --- End of inner exception stack trace ---    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]&amp; sendBuf, Int32&amp; sendCount)    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext&amp; context, ReadOnlySpan`1 inputBuffer, Byte[]&amp; outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)    --- End of inner exception stack trace ---    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 574    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1327    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 395    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 395    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 738    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 307    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeActionMethodAsync&gt;g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeNextActionFilterAsync&gt;g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeInnerFilterAsync&gt;g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeFilterPipelineAsync&gt;g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeAsync&gt;g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.&lt;Invoke&gt;g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
-- | -- | --

2021-06-18 14:14:42 | Error | Exception in GetConfigurationForSetup (noname-clubl): System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.  ---&gt; System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.  ---&gt; Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.  ---&gt; Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure    --- End of inner exception stack trace ---    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]&amp; sendBuf, Int32&amp; sendCount)    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext&amp; context, ReadOnlySpan`1 inputBuffer, Byte[]&amp; outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)    --- End of inner exception stack trace ---    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 574    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 889    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 868
-- | -- | --

**Comment by ilike2burnthing** [comment] 2021-06-18 13:04
I can replicate this on my Docker install (v0.18.345) but not in Windows Sandbox (and no issue accessing the site in browser).

curl output from within container:
```
root@b536a74fa762:/# curl -s -o /dev/null -v https://nnmclub.to/forum/tracker.php
*   Trying 179.43.141.93...
* TCP_NODELAY set
* Connected to nnmclub.to (179.43.141.93) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [108 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2928 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [518 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / AES256-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=nnmclub.to
*  start date: Apr 23 23:02:11 2021 GMT
*  expire date: Jul 22 23:02:11 2021 GMT
*  subjectAltName: host "nnmclub.to" matched cert's "nnmclub.to"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
} [5 bytes data]
> GET /forum/tracker.php HTTP/1.1
> Host: nnmclub.to
> User-Agent: curl/7.58.0
> Accept: */*
> 
{ [5 bytes data]
< HTTP/1.1 200 OK
< Server: nginx
< Date: Fri, 18 Jun 2021 04:46:53 GMT
< Content-Type: text/html; charset=windows-1251
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: private, pre-check=0, post-check=0, max-age=0
< Expires: 0
< Pragma: no-cache
< X-Frame-Options: SAMEORIGIN
< 
{ [16093 bytes data]
* Connection #0 to host nnmclub.to left intact
```
curl output specifying cipher:
```
root@b536a74fa762:/# curl -iv --ciphers TLS_RSA_WITH_AES_256_CBC_SHA256 -o /dev/null https://nnmclub.to
* Rebuilt URL to: https://nnmclub.to/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 179.43.141.93...
* TCP_NODELAY set
* Connected to nnmclub.to (179.43.141.93) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: TLS_RSA_WITH_AES_256_CBC_SHA256
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS alert, Server hello (2):
{ [2 bytes data]
* error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
* stopped the pause stream!
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```
SSL Labs analysis:
https://www.ssllabs.com/ssltest/analyze.html?d=nnmclub.to&s=179.43.141.93

@ngosang any ideas?

**Comment by PeterVoronov** [comment] 2021-06-18 13:46
I can confirm too.

Tried to change `/etc/ssl/openssl.conf` in docker, with adding the 
```
[default_conf]

ssl_conf = ssl_sect

[ssl_sect]

system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT:@SECLEVEL=2
```
But with no lucky...
SECLEVEL=1 didn't help too

**Comment by kekal** [comment] 2021-06-18 22:52
@ilike2burnthing I have the same issue.
No problem with curl from the Linux host and Jackett container.
But cannot curl from windows.
```
> curl -iv https://nnmclub.to
* Uses proxy env variable no_proxy == '192.168.99.100,192.168.99.101'
*   Trying 179.43.141.93:443...
* TCP_NODELAY set
* Connected to nnmclub.to (179.43.141.93) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```


When I trying to export with openssl on Windows it uses another cipher AES256-SHA256:
```
>echo | openssl.exe  s_client -connect nnmclub.to:443
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = nnmclub.to
verify return:1
---
Certificate chain
 0 s:/CN=nnmclub.to
   i:/C=US/O=Let's Encrypt/CN=R3
 1 s:/C=US/O=Let's Encrypt/CN=R3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIG9jCCBd6gAwIBAgISBMmn/accFQ4dxinSnsx1a1IFMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMTA0MjMyMzAyMTFaFw0yMTA3MjIyMzAyMTFaMBUxEzARBgNVBAMT
Cm5ubWNsdWIudG8wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDjfXrV
Yn/6cGGvuV7nB+J5+eT34ugH6k2Y6afKbTVnds118H6tCK0QGZq851Ipm6XeEhrI
9W5sy23i7ykgV+0kG1KJX8nSZBsmzoXAMFjTH2smCzjoub6CzmxcAKx3c90fLAH6
33jAmXHt8jvaKIdRf1aCQ+bs2cWARvG4auki+zL5O2GQsMn+lUzy/2+rbFe6M/xF
gBwehNn3Hws/0p2nRd53wg9BNw2radUwAlI3fEST5fZx/DUFz7E5Mk4PQTMy50sF
oESoSngpNMS8Qpn5SWTHCWuW4Ru5ndKkCYGQfGQsC4EP6pUie+dvhY1uC0pNT58o
7AAobfTBNQYMu1L+d4ozJijp7d3XUHlDNlQP+KvEIXUyDNsHj7iFl1qXO8iRVC0p
yACOxdOgA3/tK+dHyV6q4NxZ2HgNyMgY+NYgkcuMCt/qulGaz6wn7GMON7Tsqxhb
OInZQvX9lee5oIxf2lXR6yH+fV0Ygq1VkT2Gg8ia7erJSsODdv9qg6rk+R4klCE3
/kaiEvDckLgzK1IkcBnMjtZ+7DwcnMgFeYytd4I9CvDAk2g7OPsu+vXS0csWwPnH
abRKlzi/iN5KoHi4DVw8Szu1rTn9PcAdfJDqBypF53dqTGFgaPmxPh/DVNmRtYbJ
2NLioiCCv0t1XdIatFOGxEu9wwP+WWOazcIt5QIDAQABo4IDITCCAx0wDgYDVR0P
AQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMB
Af8EAjAAMB0GA1UdDgQWBBRE7qmweWSAkwKBzYRJZT3p6mIWOzAfBgNVHSMEGDAW
gBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQUH
MAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3Iz
LmkubGVuY3Iub3JnLzCB7wYDVR0RBIHnMIHkgg9hcGkubm5tLWNsdWIud3OCF2Fz
c2V0cy5pcHY2Lm5ubS1jbHViLndzgg9pcHY0Lm5ubWNsdWIudG+CEGlwdjYubm5t
LWNsdWIubWWCEGlwdjYubm5tLWNsdWIud3OCD2lwdjYubm5tY2x1Yi5yb4IPaXB2
Ni5ubm1jbHViLnRvggtubm0tY2x1Yi5tZYILbm5tLWNsdWIud3OCCm5ubWNsdWIu
cm+CCm5ubWNsdWIudG+CD3d3dy5ubm0tY2x1Yi5tZYIOd3d3Lm5ubWNsdWIucm+C
Dnd3dy5ubm1jbHViLnRvMEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8T
AQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIB
BQYKKwYBBAHWeQIEAgSB9gSB8wDxAHYA9lyUL9F3MCIUVBgIMJRWjuNNExkzv98M
LyALzE7xZOMAAAF5AS8OKQAABAMARzBFAiEAiuIzDSeULsOu4ygp7G5vSqQ//Ko2
8pzOQ1NQWyAmlLYCIBiAojqDftJxcrZ8OHJ7RxDXhZcBWz6sx9jSimXMonJgAHcA
RJRlLrDuzq/EQAfYqP4owNrmgr7YyzG1P9MzlrW2gagAAAF5AS8OWgAABAMASDBG
AiEA+kcZxWbB5eCaZhEHisdDzuSqqnvVp3JSMmjPmZ8csTQCIQDvSH3av4eM/g/E
OvLA+FGXQNjsJ1KltJQl2t+xa5g81TANBgkqhkiG9w0BAQsFAAOCAQEAEl1ucdlG
OoMgKODGNkXptuG9ztjUJufilVekwmCU3EfSs9On9nSKI0r5M8n/fZ/utaTgEfRV
kADOZFpPilTNJBDx1pcIKY7lHYFdlEqymsqeh0oXfbuufsjVMpTaGDuhr6bDWRLs
79v8d/S3VCvLzuczQARdegeb7vnu4kjHD+JxvnNfx2jATc7Tsgg+KsLNUsaN8X+H
QdngynTgcb4Gez0l7etr8Y4O7fPoARcU3fgV1HIO0NC5mdzhtKBhBzprpZ79kZhd
CnGN6oGRLnT7+zrEyb4v/ITOsbLYR0cIWYVy7TmHUi+8oT1rUHytR0CqhYNyxFQ8
1aIByuBEln/gkg==
-----END CERTIFICATE-----
subject=/CN=nnmclub.to
issuer=/C=US/O=Let's Encrypt/CN=R3
---
No client certificate CA names sent
---
SSL handshake has read 3282 bytes and written 920 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-SHA256
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-SHA256
    Session-ID: 2F736F0A32EEA3A9E66392DE25210F66DAA9F92D54D62976405FEEB9A247A261
    Session-ID-ctx:
    Master-Key: D5023CF6D35ECDD50F52152D05F88E781763AB746082DE733913DE0E6F6CB1A21B680C19A9166DBD7558B83509C9BD18
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 84 6b bf 49 ca 40 aa de-ed 45 d5 9f e0 07 f2 bf   .k.I.@...E......
    0010 - 0c 95 c3 e6 56 39 8c 18-40 e0 b0 81 a8 c3 6b 39   ....V9..@.....k9
    0020 - 7b 07 fd af 63 df 68 40-0e 92 87 a7 11 a1 38 a5   {...c.h@......8.
    0030 - 67 17 1d ff 74 cb d9 46-dc 75 a6 62 8c c1 13 c0   g...t..F.u.b....
    0040 - 7e 19 c3 99 74 9e 0a bc-99 92 ea 72 c1 d2 3b 4a   ~...t......r..;J
    0050 - 8a 45 fd 9d 66 a4 dd 06-c5 46 a4 c3 28 3f 70 5f   .E..f....F..(?p_
    0060 - d1 cf 90 21 8f 8d 45 45-78 0b 70 f8 fd 32 ab 67   ...!..EEx.p..2.g
    0070 - f4 68 bf ea 2e 7c c4 48-c1 fc e2 d7 c4 65 05 11   .h...|.H.....e..
    0080 - 0b 1d 4f 7f 20 f7 2f 96-ae e6 9d 58 57 66 2c c6   ..O. ./....XWf,.
    0090 - 10 52 9c bd 73 67 da 77-52 3c 69 fa bd e7 c1 c3   .R..sg.wR<i.....
    00a0 - 23 a3 42 f6 63 82 a9 1f-55 09 83 e7 e2 2e fc a0   #.B.c...U.......

    Start Time: 1624056467
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
DONE
```

**Comment by scarry1992** [comment] 2021-07-01 12:17
same issue, docker image is from linuxserver.io

**Comment by Anzic23** [comment] 2021-07-09 23:54
same. docker, Synology

**Comment by beastlordalex** [comment] 2021-07-16 10:11
Have the same problem.
docker image is from linuxserver.io (linux x64)

**Comment by uchuu-me** [comment] 2021-07-17 11:22
Solution for docker images [https://stackoverflow.com/questions/66885550/interop-crypto-opensslcryptographicexception-error14094410ssl-routinesssl3-r](url)

**/etc/ssl/openssl.cnf**
```
# Add this in the head of the file
openssl_conf = openssl_init

#
# skip
#

# And the following in the end of the file
[openssl_init]
ssl_conf = ssl_config

[ssl_config]
system_default = tls_defaults

[tls_defaults]
CipherString = @SECLEVEL=2:kEECDH:kRSA:kEDH:kPSK:kDHEPSK:kECDHEPSK:-aDSS:-3DES:!DES:!RC4:!RC2:!IDEA:-SEED:!eNULL:!aNULL:!MD5:-SHA384:-CAMELLIA:-ARIA:-AESCCM8
Ciphersuites = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256
MinProtocol = TLSv1.2
```
Add mount path to the patched version of /etc/ssl/openssl.cnf and restart docker

**Comment by PeterVoronov** [comment] 2021-07-17 12:06
> Solution for docker images [https://stackoverflow.com/questions/66885550/interop-crypto-opensslcryptographicexception-error14094410ssl-routinesssl3-r](url)
> 
> Edit **/etc/ssl/openssl.cnf** inside container and save it outside
> 
> ```
> # Add this in the head of the file
> openssl_conf = openssl_init
> 
> #
> # skip
> #
> 
> # And the following in the end of the file
> [openssl_init]
> ssl_conf = ssl_config
> 
> [ssl_config]
> system_default = tls_defaults
> 
> [tls_defaults]
> CipherString = @SECLEVEL=2:kEECDH:kRSA:kEDH:kPSK:kDHEPSK:kECDHEPSK:-aDSS:-3DES:!DES:!RC4:!RC2:!IDEA:-SEED:!eNULL:!aNULL:!MD5:-SHA384:-CAMELLIA:-ARIA:-AESCCM8
> Ciphersuites = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256
> MinProtocol = TLSv1.2
> ```
> 
> Add mount path to the patched version of /etc/ssl/openssl.cnf and restart container

Many thanks. It working now!

**Comment by ilike2burnthing** [comment] 2021-07-17 13:01
@uchuu-me something similar was suggested in https://github.com/Jackett/Jackett/issues/10578#issuecomment-753300521 but was ultimately rejected by LS.io in https://github.com/linuxserver/docker-jackett/issues/114 as being, "[...] really insecure and not safe for the users."

**Comment by Drun555** [comment] 2021-08-09 08:28
Created a [issue](https://nnmclub.to/forum/viewtopic.php?p=11247986#11247986) in nnmclub.to forum. Hope they'll reply soon.

**Comment by kmeaw** [comment] 2021-08-09 22:17
Seems to be fixed now: https://www.ssllabs.com/ssltest/analyze.html?d=nnmclub.to&s=179.43.141.93

**Comment by ilike2burnthing** [comment] 2021-08-09 23:55
Yep, working fine now.

**Closed by ilike2burnthing** 2021-08-09 23:55 UTC
Labels: Confirmed, Needs Investigations, Docker
