### ISSUE TITLE
[rarbg] Exception (rarbg): The authentication or decryption has failed.: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by testarea1** [Jackett/Jackett#3624] opened 2018-08-17 02:14 UTC
**Jackett version**:  0.10.54.0
**Mono version** (if not using Windows):  5.14.0.177

-------------------------------
```
2018-08-16 19:10:55.5536 Info Executing action method Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) - Validation state: Valid 
2018-08-16 19:10:55.5536 Debug WebClient(HttpWebClient).GetString(Url:https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=jackett_v0.10.54.0) 
2018-08-16 19:10:55.5956 Error On attempt 1 checking for results from RARBG: An error occurred while sending the request 
2018-08-16 19:10:56.0960 Debug WebClient(HttpWebClient).GetString(Url:https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=jackett_v0.10.54.0) 
2018-08-16 19:10:56.1229 Error On attempt 2 checking for results from RARBG: An error occurred while sending the request 
2018-08-16 19:10:56.6232 Debug WebClient(HttpWebClient).GetString(Url:https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=jackett_v0.10.54.0) 
2018-08-16 19:10:56.6561 Error On attempt 3 checking for results from RARBG: An error occurred while sending the request 
2018-08-16 19:10:57.1596 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 1606.7425ms 
2018-08-16 19:10:57.1596 Error Jackett.Common.IndexerException: Exception (rarbg): The authentication or decryption has failed. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x00037] in <c793f351b66f4138a5b67168e0949a18>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in <c793f351b66f4138a5b67168e0949a18>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in <c793f351b66f4138a5b67168e0949a18>:0 
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult result) [0x00032] in <c793f351b66f4138a5b67168e0949a18>:0 
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult asyncResult) [0x0000c] in <c793f351b66f4138a5b67168e0949a18>:0 
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.EndRead (System.IAsyncResult asyncResult) [0x0004b] in <c793f351b66f4138a5b67168e0949a18>:0 
  at Mono.Net.Security.Private.LegacySslStream.EndAuthenticateAsClient (System.IAsyncResult asyncResult) [0x0000e] in <b3d41b23de534128a4f18a6e1312f79c>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in <2943701620b54f86b436d3ffad010412>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Mono.Net.Security.MonoTlsStream+<CreateStream>d__17.MoveNext () [0x00126] in <b3d41b23de534128a4f18a6e1312f79c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebConnection+<CreateStream>d__18.MoveNext () [0x001ba] in <b3d41b23de534128a4f18a6e1312f79c>:0 
   --- End of inner exception stack trace ---
  at System.Net.WebConnection+<CreateStream>d__18.MoveNext () [0x0021a] in <b3d41b23de534128a4f18a6e1312f79c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebConnection+<InitConnection>d__19.MoveNext () [0x00141] in <b3d41b23de534128a4f18a6e1312f79c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebOperation+<Run>d__57.MoveNext () [0x0009a] in <b3d41b23de534128a4f18a6e1312f79c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebCompletionSource`1+<WaitForCompletion>d__15[T].MoveNext () [0x00094] in <b3d41b23de534128a4f18a6e1312f79c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__244`1[T].MoveNext () [0x000c5] in <b3d41b23de534128a4f18a6e1312f79c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <b3d41b23de534128a4f18a6e1312f79c>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <2943701620b54f86b436d3ffad010412>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0041d] in <7b15dfce33e34fd8b515d1a954c2d042>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <7b15dfce33e34fd8b515d1a954c2d042>:0 
--- End of stack trace from previous location where exception was thrown ---
  at CloudFlareUtilities.ClearanceHandler+<SendAsync>d__20.MoveNext () [0x0010c] in <d0213015414e4bf286b46bc1ee77bd72>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <7b15dfce33e34fd8b515d1a954c2d042>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Utils.Clients.HttpWebClient+<Run>d__7.MoveNext () [0x0040e] in C:\projects\jackett\src\Jackett.Common\Utils\Clients\HttpWebClient.cs:211 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Utils.Clients.WebClient+<GetString>d__18.MoveNext () [0x000c1] in C:\projects\jackett\src\Jackett.Common\Utils\Clients\WebClient.cs:114 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.BaseWebIndexer+<RequestStringWithCookies>d__5.MoveNext () [0x00084] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:454 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.BaseWebIndexer+<RequestStringWithCookiesAndRetry>d__6.MoveNext () [0x00160] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:477 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.Rarbg+<CheckToken>d__16.MoveNext () [0x0006f] in C:\projects\jackett\src\Jackett.Common\Indexers\Rarbg.cs:103 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.Rarbg+<PerformQuery>d__19.MoveNext () [0x0002d] in C:\projects\jackett\src\Jackett.Common\Indexers\Rarbg.cs:130 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.Rarbg+<PerformQuery>d__18.MoveNext () [0x00024] in C:\projects\jackett\src\Jackett.Common\Indexers\Rarbg.cs:125 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x00047] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:340 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x000e6] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:360 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x00024] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:819 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x00059] in C:\projects\jackett\src\Jackett.Common\Services\IndexerManagerService.cs:222 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Server.Controllers.IndexerApiController+<Test>d__15.MoveNext () [0x000e1] in C:\projects\jackett\src\Jackett.Server\Controllers\IndexerApiController.cs:141 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <51f5e57c3b1641ff921c58f55f777af6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x00042] in C:\projects\jackett\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:29  Jackett.Common.IndexerException: Exception (rarbg): The authentication or decryption has failed. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x00037] in <c793f351b66f4138a5b67168e0949a18>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in <c793f351b66f4138a5b67168e0949a18>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in <c793f351b66f4138a5b67168e0949a18>:0 
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult result) [0x00032] in <c793f351b66f4138a5b67168e0949a18>:0 
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult asyncResult) [0x0000c] in <c793f351b66f4138a5b67168e0949a18>:0 
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.EndRead (System.IAsyncResult asyncResult) [0x0004b] in <c793f351b66f4138a5b67168e0949a18>:0 
  at Mono.Net.Security.Private.LegacySslStream.EndAuthenticateAsClient (System.IAsyncResult asyncResult) [0x0000e] in <b3d41b23de534128a4f18a6e1312f79c>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in <2943701620b54f86b436d3ffad010412>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Mono.Net.Security.MonoTlsStream+<CreateStream>d__17.MoveNext () [0x00126] in <b3d41b23de534128a4f18a6e1312f79c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebConnection+<CreateStream>d__18.MoveNext () [0x001ba] in <b3d41b23de534128a4f18a6e1312f79c>:0 
   --- End of inner exception stack trace ---
  at System.Net.WebConnection+<CreateStream>d__18.MoveNext () [0x0021a] in <b3d41b23de534128a4f18a6e1312f79c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebConnection+<InitConnection>d__19.MoveNext () [0x00141] in <b3d41b23de534128a4f18a6e1312f79c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebOperation+<Run>d__57.MoveNext () [0x0009a] in <b3d41b23de534128a4f18a6e1312f79c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.WebCompletionSource`1+<WaitForCompletion>d__15[T].MoveNext () [0x00094] in <b3d41b23de534128a4f18a6e1312f79c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__244`1[T].MoveNext () [0x000c5] in <b3d41b23de534128a4f18a6e1312f79c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <b3d41b23de534128a4f18a6e1312f79c>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <2943701620b54f86b436d3ffad010412>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0041d] in <7b15dfce33e34fd8b515d1a954c2d042>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <7b15dfce33e34fd8b515d1a954c2d042>:0 
--- End of stack trace from previous location where exception was thrown ---
  at CloudFlareUtilities.ClearanceHandler+<SendAsync>d__20.MoveNext () [0x0010c] in <d0213015414e4bf286b46bc1ee77bd72>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <7b15dfce33e34fd8b515d1a954c2d042>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Utils.Clients.HttpWebClient+<Run>d__7.MoveNext () [0x0040e] in C:\projects\jackett\src\Jackett.Common\Utils\Clients\HttpWebClient.cs:211 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Utils.Clients.WebClient+<GetString>d__18.MoveNext () [0x000c1] in C:\projects\jackett\src\Jackett.Common\Utils\Clients\WebClient.cs:114 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.BaseWebIndexer+<RequestStringWithCookies>d__5.MoveNext () [0x00084] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:454 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.BaseWebIndexer+<RequestStringWithCookiesAndRetry>d__6.MoveNext () [0x00160] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:477 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.Rarbg+<CheckToken>d__16.MoveNext () [0x0006f] in C:\projects\jackett\src\Jackett.Common\Indexers\Rarbg.cs:103 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.Rarbg+<PerformQuery>d__19.MoveNext () [0x0002d] in C:\projects\jackett\src\Jackett.Common\Indexers\Rarbg.cs:130 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.Rarbg+<PerformQuery>d__18.MoveNext () [0x00024] in C:\projects\jackett\src\Jackett.Common\Indexers\Rarbg.cs:125 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x00047] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:340 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer+<ResultsForQuery>d__69.MoveNext () [0x000e6] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:360 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x00024] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:819 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x00059] in C:\projects\jackett\src\Jackett.Common\Services\IndexerManagerService.cs:222 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Server.Controllers.IndexerApiController+<Test>d__15.MoveNext () [0x000e1] in C:\projects\jackett\src\Jackett.Server\Controllers\IndexerApiController.cs:141 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <ed07561af00f49668ebc547ea3e7ce17>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <ed07561af00f49668ebc547ea3e7ce17>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <51f5e57c3b1641ff921c58f55f777af6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x00042] in C:\projects\jackett\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:29 
2018-08-16 19:10:57.1699 Info Request finished in 1618.5007ms 500 application/json 
```

**Comment by flightlevel** [comment] 2018-08-17 12:00
Duplicate of #3623

**Closed by flightlevel** 2018-08-17 12:00 UTC
