### ISSUE TITLE
[zooqle] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by cocokola** [Jackett/Jackett#3369] opened 2018-07-10 03:41 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  0.8.1158.0
**Mono version** (if not using Windows):  
captcha issue?  ii can browse to it but fails to test.

-------------------------------

**Comment by cocokola** [comment] 2018-07-10 14:49
I see this was reported twice before, however, the request for logs passed and was closed.   updated to the new jacket, as my jacket kept crashing hard as well.   I have two other trackers that are not working now, and further, there is a problem with one show query that causes the service to stop. 
some serious issues.   i did some digging but could not find where the log files are stored.

**Comment by kaso17** [comment] 2018-07-10 15:57
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by cocokola** [comment] 2018-07-10 19:39
I had to rebuild my server recently, so only the last log where I did a manual test for zoogle and others has the additional logging.  thanks all

[log.20180703.00001.txt](https://github.com/Jackett/Jackett/files/2181884/log.20180703.00001.txt)
[log.20180704.00000.txt](https://github.com/Jackett/Jackett/files/2181885/log.20180704.00000.txt)
[log.20180705.00000.txt](https://github.com/Jackett/Jackett/files/2181886/log.20180705.00000.txt)
[log.20180706.00000.txt](https://github.com/Jackett/Jackett/files/2181887/log.20180706.00000.txt)
[log.20180710.00000.txt](https://github.com/Jackett/Jackett/files/2181888/log.20180710.00000.txt)
[log.txt](https://github.com/Jackett/Jackett/files/2181889/log.txt)





, so enhanced logging was not enabled.   Below are the logs I have.

**Comment by flightlevel** [comment] 2018-07-14 05:18
Is this still happening @cocokola 
If it is, please reproduce it while enhance logging is turned on

**Comment by cocokola** [comment] 2018-07-16 18:06
Yes, it is still happening.   
[log.txt](https://github.com/Jackett/Jackett/files/2198795/log.txt)

Here is the log after doing a test search.  When clicking on zoogle, it asks for a bot check.

**Comment by cocokola** [comment] 2018-07-17 03:54
I have to 'touch' sonarr and radarr frequently still.   See below for this portion of the problem.  Note: this was AFTER removing zoogle, and all other indexers listed above!

Sonarr is still getting the 'all indexers unavailable" with the following from its log:
All HTTP request failed: [500:InternalServerError] [GET] at [http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=1000]

HTTP Error - Res: [GET] http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=1000: 500.InternalServerError
{
  "result": "error",
  "error": "'\u0003', hexadecimal value 0x03, is an invalid character.",
  "stacktrace": "   at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(Int32 ch, Char* pDst, Boolean entitize)\r\n   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)\r\n   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)\r\n   at System.Xml.XmlEncodedRawTextWriterIndent.WriteString(String text)\r\n   at System.Xml.XmlWellFormedWriter.WriteString(String text)\r\n   at System.Xml.Linq.ElementWriter.WriteStartElement(XElement e)\r\n   at System.Xml.Linq.ElementWriter.WriteElement(XElement e)\r\n   at System.Xml.Linq.XElement.WriteTo(XmlWriter writer)\r\n   at System.Xml.Linq.XContainer.WriteContentTo(XmlWriter writer)\r\n   at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)\r\n   at System.Xml.Linq.XNode.ToString()\r\n   at System.String.Concat(Object arg0, Object arg1, Object arg2)\r\n   at Jackett.Server.Controllers.ResultsController.CreateErrorXML(Int32 code, String description)\r\n   at Jackett.Server.Controllers.ResultsController.GetErrorXML(Int32 code, String description)\r\n   at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Jackett.Server.Middleware.CustomExceptionHandler.<Invoke>d__3.MoveNext()"
}
[log.txt](https://github.com/Jackett/Jackett/files/2200097/log.txt)

**Comment by cocokola** [comment] 2018-07-17 20:01
For some reason, I have had to click on 'enhanced logging' then save server settings about three times before it would STICK.    I am starting over, so just ignore everything above and I will repost the logs.

**Comment by cocokola** [comment] 2018-07-18 19:10
What gives?  Enhanced logging is showing as disabled, AGAIN.  I checked it, clicked apply server settings, and I get a " request to jackett server failed" 
Refreshed the webpage, and now it applies.   BTW, I am running version Jackett Version 0.9.6.0 currently.

**Comment by flightlevel** [comment] 2018-07-21 12:36
Thank you @cocokola that's an enhanced log. Unfortunately it doesn't have anything about Zoogle. You got an error for Nyaa Pantsu. The reason for the error is that there web server was down. So nothing to do with Jackett
`2018-07-17 15:13:37.6875 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 61051.162ms 
2018-07-17 15:13:37.7666 Error Jackett.Common.IndexerException: Exception (nyoo): Request to https://nyoo.moe/search?page=search&q= failed (Error GatewayTimeout) - The tracker seems to be down. ---> System.Exception: Request to https://nyoo.moe/search?page=search&q= failed (Error GatewayTimeout) - The tracker seems to be down. `

In regards to Zoogle
Stop Jackett windows service
Start Jackett via the command line with `JackettConsole.exe -t -l` which will turn on enhanced logging (it automatically turns off when Jackett restarts due to the file size) . Click on test for Zoogle and post the log

In regards to enhancements, I think issues https://github.com/Jackett/Jackett/issues/3292 and  https://github.com/Jackett/Jackett/issues/661 cover your request. Your pull requests are welcome.
I still strongly recommend not to use the aggregate indexer. Like you say, you don't know which tracker will be flakey. It takes a couple of extra minutes to add 10 indexers to Sonarr and be done with it. That way if 1 out of 10 indexer has an issue, Sonarr will still get good results on the other nine

**Comment by cocokola** [comment] 2018-07-21 15:09
Normally I use the GUI for everything, but this keeps being reset: 
![image](https://user-images.githubusercontent.com/9909697/43036548-a0ddf7b2-8cc9-11e8-894a-b6ed236ead1d.png)
![image](https://user-images.githubusercontent.com/9909697/43036557-b9420a32-8cc9-11e8-90f0-0fbe73ae25cb.png)
![image](https://user-images.githubusercontent.com/9909697/43036562-c58a7932-8cc9-11e8-8080-6b46df3f41b9.png)

I use all these trackers currently.  When zoogle is working, it is there as well.   

Since this is supposed to be a 2nd tier service.  Setting up EACH of these in radarr defeats the purpose of having a 2nd tier service, no?   It won't be a couple extra minutes to set of all these in radar, sonarr, lidarr, and DuckieTV, right?     When one fails, it moves on to the next.  It is MUCH easier to just delete problematic trackers and not touch 4 apps each time to manage a single tracker when it fails.   Enterprise thinking..  

Zoogle WAS in the list and I ran a test.   I will do it again.. 
![image](https://user-images.githubusercontent.com/9909697/43036599-70935f1a-8cca-11e8-8e54-55bc5c7380e7.png)
It showed as working, but when I clicked ' test" it failed:
All on one screenshot (enhanced logged enabled, zoogle shown in tracker list, the error is shown in the console window): 
![image](https://user-images.githubusercontent.com/9909697/43036620-c2811948-8cca-11e8-835b-7f548bd14a83.png)
and the corresponding log file: 
[log.txt](https://github.com/Jackett/Jackett/files/2216236/log.txt)

I searched the text file.. Guess what?  no zoogle is listed!   ok so this time I followed your instructions.  Actually, no I tried to.  I had to open a command prompt, change working directory to : C:\ProgramData\Jackett
then launch the command.  the window seemed to be the output (instead of the log.txt?) and the default buffer size for the command window is 300 lines, so I had to modify it to 3000 lines, shut down and restart jacket a second time.  checked the GUI,  AH, NOW it shows enhanced logging! 
![image](https://user-images.githubusercontent.com/9909697/43036706-00a204e8-8ccc-11e8-8d29-09138708b841.png)
ran the test again.  still fails.  nothing in the log.txt.   I copied the text in the console window, just in case it was not being copied to the log file (forgotten switch perhaps?)  and here it is: 
[console.txt](https://github.com/Jackett/Jackett/files/2216245/console.txt)
Still no zoogle!

so what gives my friend?

browsing to https://zoogle.com works
rss works:
torznab works?: This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error code="100" description="Invalid API Key"/>
manual search = 0 results , no error.


NOW the console2.txt output shows zoogle! after the manual search!?!?  
[console2.txt](https://github.com/Jackett/Jackett/files/2216261/console2.txt)

um, wait.  I was copying and pasting the console output into a text file, saving.  then using SEARCH in notepad to search for zoogle. "0 found" it says..  BUT I can clearly see ZOOGLE shown..   tried forward and back.  So we have a unicode or hidden characters issue?   I am so lost, but now I return this back to you . I can't think of anything else to try at this time.

**Comment by flightlevel** [comment] 2018-07-22 12:18
First log
This may explain some of strange behaviour with enhanced logs
```
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Jackett\In
dexers\yts.json.bak' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
```
The user that is running Jackett doesn't have permission to the folder, you need to investigate the permissions on that folder. Jackett needs read and write access to the folder.

Second log
```
             Returning Forbidden => <!DOCTYPE html>
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>

            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to t
he web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>


            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-vir
us scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administr
ator to run a scan across the network looking for misconfigured or infected devices.</p>
```
Cloudflare has blacklisted your IP, which explains why others aren't having issues but you are

3rd log
Same issue with Zoogle as above -> Forbidden
Limetorrents url already got updated yesterday

**Comment by cocokola** [comment] 2018-07-22 20:08
Permissions are correct, I verified:
[Document.docx](https://github.com/Jackett/Jackett/files/2217339/Document.docx)

I went ahead and replaced permissions to ensure the acls are correct.. Perhaps this is an erroneous error. 

question: what is the default installation directory for jacket?

as far as blacklisted:  the captua challenge/response  is nothing new.. That was there before. I am NOT blacklisted, that would imply I can not connect at all.  When I browse manually, I am able to connect, but have to do a captua.    Again, if I run a manual search in jackett, it gets a different error.. the one that you mentioned above.     Why no error normally?

**Comment by flightlevel** [comment] 2018-07-23 11:17
`C:\ProgramData\Jackett`

Blacklisted is different from banned. Blacklisted means you are under suspicion http://www.dictionary.com/browse/blacklist
Because Cloudflare has flagged you as suspicious, Cloudflare make you jump through hoops with a captcha to prove you are genuine. Requests in both logs return Forbidden. Jackett can't jump through these hoops. Suggest using another indexer. Ask yourself why you're the only one having a problem with Zooqle in the two weeks since this issue was created? It works perfectly here. If I used my PC on your IP address I'd get the same result as you

Issue has more than run its course, closing

**Closed by flightlevel** 2018-07-23 11:17 UTC

**Comment by cocokola** [comment] 2018-07-23 15:45
Please scroll up:  Duplicate of #3283 and #3283.  It is not just me.  I am using a VPN, so this is likely the VPN IP.  

BTW   - that file that is denied is a cookie.  Perhaps that is why zoogle is failing? 

 one the less, why isn't this being listed in the log UNLESS I USE MANUAL SEARCH? 

What about the other issues, please review the last 4 emails I sent and please reply to all my questions,  or shall I start a new request?  examples  - where is the local install directory?    

I just need some guidance/help and seems we are getting tunnel vision. thanks for your help.
