### ISSUE TITLE
[avistaz] Exception (avistaz): Verification required: Verification required (Test)

### ISSUE THREAD

**Issue by andrep182** [Jackett/Jackett#8729] opened 2020-05-21 18:22 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu

**Jackett Version**:  0.16.511.0

**Are you using a proxy or VPN?** [yes]

### Description

I noticed that Avistaz was no longer working today. When I went to Jackett to test, I received the verification required error.

**Comment by RoloSoze** [comment] 2020-05-21 18:31
Duplicate of #8727 - It'll be resolved there.

**Closed by RoloSoze** 2020-05-21 18:31 UTC
Labels: Duplicate
