### ISSUE TITLE
Jackett returns empty torrents

### ISSUE THREAD

**Issue by littlejeem** [Jackett/Jackett#4694] opened 2019-02-15 19:45 UTC
OS: Linux-4.14.92-v7+-armv7l-with-debian-9.6
Browser: Chrome
What you did: Linked Sickchill to Jackett
What happened: Search returns results but doesn't grab downloads
What you expected: Prior behavior has been that search results are grabbed and sent to a blackhole and picked up by download client. Here Jackett appears to be sending empty torrents to Sickchill. I don't know how to resolve. Any help much appreciated

**Jackett version**: 
0.10.743.0

**Mono version** (if not using Windows):  
Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:28:29 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       preemptive
	GC:            sgen (concurrent by default)
-------------------------------

Logs:
Jackett = here
https://pastebin.com/fnyYWijV

SickChill = here
https://pastebin.com/uPXwPBaw

**Comment by garfield69** [comment] 2019-02-15 20:16
this is a duplicate of the #4584 issue.

**Closed by garfield69** 2019-02-15 20:16 UTC
