### ISSUE TITLE
Save the default search sorting and number of entries

### ISSUE THREAD

**Issue by 07416** [Jackett/Jackett#4558] opened 2019-01-27 12:35 UTC
**Jackett version**: 0.13.135.0

In search the "show entries" setting always defaults to 20 and the sorting setting (categories are below) resets as well.
`
Published	Tracker	Name	Size	Files	Category	Grabs	Seeds	Leechers	DL Factor	UL Factor	Download`

**Comment by 07416** [comment] 2020-02-18 14:53
Can someone confirm if at least saving the default value of "Show entries" in `Dashboard#search` is possible or not? The value always resets to 20 for me and I'm not sure if this is by design or a cookie issue for instance.

**Comment by garfield69** [comment] 2020-02-18 18:32
it's by design. jackett does not save this dashboard setting.

**Comment by ngosang** [comment] 2020-03-15 22:53
This is working for me.
1. I open the search modal and I change the number of results and the sort column.
2. I close the modal
3. I close the tab in the browser and reopen
4. The configuration i set in point 1. is there.

The configuration is saved in the local storage of the web browser, not in the server. So the config persist if you always use the same browser.
@garfield69 can you replicate?

**Comment by cadatoiva** [comment] 2020-03-15 23:03
This only works for same session. When you close the entire browser it resets, but it remembers it for as long as the browser stays open.

**Comment by ngosang** [comment] 2020-03-15 23:44
> This only works for same session.

Nop, 2 hours. But that gave me the hint. Fixed in #7686

**Comment by garfield69** [comment] 2020-03-15 23:56
>The configuration is saved in the local storage of the web browser, not in the server. So the config persist if you always use the same browser.  can you replicate?

the Dashboard search show-entries and sort column options last for as long as the local storage elements do, so whenever that dataspace is deleted those dashboard options to be reset to the defaults.
![image](https://user-images.githubusercontent.com/6933240/76713299-7dac2880-6784-11ea-979a-52b6b7fb88d3.png)

Some Chrome Browser events can reset that dataspace, as I have seen my Jackett dashboard with reset options before, although I cannot recall how long ago since the last time that happened, or what were the circumstances. Its not something that I have been paying much attention to.

**Closed** 2020-03-15 23:59 UTC
Labels: Enhancement, Web UI

**Comment by garfield69** [comment] 2020-03-16 06:08
Jackett 0.14.79

**Comment by 07416** [comment] 2020-08-24 08:49
Can this option be set manually in a configuration file?

**Comment by ngosang** [comment] 2020-09-14 08:24
No, this is saved in the local storage, in the web browser. You can edit the values in Dev Tools but I think it's better to not touch that.
