### ISSUE TITLE
[yggtorrent] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by gabo77** [Jackett/Jackett#2287] opened 2017-12-15 22:26 UTC
I see similar issues were resolved in the last days, but it seems something changed again on their end as we still get redirected using https://ww1.yggtorrent.com/

Jackett version: 0.8.509.0
Mono version: 5.2.0.215

-------------------------------
`Error on 20171215171444 for YGGtorrent.txtJackett.ExceptionWithConfigData: Login Failed, got redirected
  at Jackett.Indexers.CardigannIndexer+<TestLogin>d__16.MoveNext () [0x000db] in <977915a7641e4a899a15326545aea979>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter 1[TResult].GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at Jackett.Indexers.CardigannIndexer+<PerformQuery>d__25.MoveNext () [0x00969] in <977915a7641e4a899a15326545aea979>:0 
`

**Comment by garfield69** [comment] 2017-12-15 23:00
Duplicate of #2283

**Closed by garfield69** 2017-12-15 23:00 UTC
