### ISSUE TITLE
[rapidzona] (testing) Exception (rapidzona): Error: MySQL Error!		MySQL error in file: /engine/classes/mysql.php at line 52		Error Number: 1		The Error returned was: No such file or directory		SQL query:: Parse error

### ISSUE THREAD

**Issue by DogancanYr** [Jackett/Jackett#15332] opened 2024-05-22 11:24 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22635.0 (64bit OS)
Environment version: 6.0.30 (C:\ProgramData\Jackett\)
```

### Description

.

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment] 2024-05-22 17:55
A genuine error at the web site.
closing as a duplicate of #7561

**Closed by garfield69** 2024-05-22 17:55 UTC
Labels: Duplicate
