### ISSUE TITLE
Jackett in a failure state

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#536] opened 2016-10-05 05:27 UTC
Hi guys,

Just noticed few times that my Jackett was out, not reachable any more but back after a restart of the rpi.

I didn't investigate more but is there any one with the same issue ?
This is totally breaking my remote system as this major part of the system queue...

I will try to get more info in logs...

**Comment by mrjack711** [comment] 2016-10-09 20:54
I get a similar issue on Ubuntu server 14.04.5.
Jackett will run fine for a day or 2 and then will be unreachable. Restarting it brings it back. 

I'm using mono 3.10.

Will also find some logs and attach them. 

Thanks

**Comment by raspdealer** [comment] 2016-10-10 16:42
On my side, I've enabled a cron start to restart it on a daily basis to reduce the impact ... 
waiting for a fix.
Have you something in your logs ?

**Comment by JigSawFr** [comment] 2016-10-11 10:31
Please update Jackett to latest version and post logs here or on a GIST
Thanks you

**Comment by mattberther** [comment] 2016-10-18 15:47
Ive found that this appears to be related to an update check. Im running mine in a docker container (linuxserver/jackett).

Relevant portion of the logs:

```
jackett_1      | 10-17 18:01:57 Info Updater started process id: 936 
jackett_1      | 10-17 18:01:57 Info Exiting Jackett.. 
jackett_1      | 10-17 18:01:57 Info Jackett Updater v0.7.425 
jackett_1      | 10-17 18:01:57 Info Options --Path /app/Jackett --Type mono --Args jackettconsole.exe  
jackett_1      | 10-17 18:01:57 Info Waiting for Jackett to close.. 
jackett_1      | 10-17 18:01:58 Info Starting Jackett 0.7.423.0 
jackett_1      | 10-17 18:01:58 Info Using HTTP Client: UnixLibCurlWebClient 
jackett_1      | 10-17 18:01:58 Info LibCurl init Ok 
jackett_1      | 10-17 18:01:58 Info LibCurl version libcurl/7.50.3 OpenSSL/1.0.2i zlib/1.2.8 libssh2/1.7.0 
jackett_1      | 10-17 18:01:58 Info Starting web server at http://*:9117/ 
jackett_1      | 10-17 18:01:59 Info Finding files in: /tmp/JackettUpdate-v0.7.425-636123241171416820/Jackett/ 
jackett_1      | 10-17 18:02:00 Info Copying anglesharp.dll 
jackett_1      | 10-17 18:02:00 Info Copying automapper.dll 
jackett_1      | 10-17 18:02:00 Info Copying autofac.integration.owin.dll 
jackett_1      | 10-17 18:02:00 Info Copying autofac.integration.webapi.owin.dll 
jackett_1      | 10-17 18:02:00 Info Copying autofac.integration.webapi.dll 
jackett_1      | 10-17 18:02:00 Info Copying autofac.dll 
jackett_1      | 10-17 18:02:00 Info Copying cloudflareutilities.dll 
jackett_1      | 10-17 18:02:00 Info Copying commandline.dll 
jackett_1      | 10-17 18:02:00 Info Copying csquery.dll 
jackett_1      | 10-17 18:02:00 Info Copying curlsharp.dll 
jackett_1      | 10-17 18:02:00 Info Copying curlsharp.dll.config 
jackett_1      | 10-17 18:02:00 Info Copying curlsharp.dll.mdb 
jackett_1      | 10-17 18:02:00 Info Copying icsharpcode.sharpziplib.dll 
jackett_1      | 10-17 18:02:00 Info Copying jackett.dll 
jackett_1      | 10-17 18:02:00 Info Copying jackett.dll.mdb 
jackett_1      | 10-17 18:02:00 Info Copying jackettconsole.exe 
jackett_1      | 10-17 18:02:00 Info Copying jackettconsole.exe.config 
jackett_1      | 10-17 18:02:00 Info Copying jackettconsole.exe.mdb 
jackett_1      | 10-17 18:02:00 Info Copying jackettservice.exe 
jackett_1      | 10-17 18:02:00 Info Copying jackettservice.exe.config 
jackett_1      | 10-17 18:02:00 Info Copying jackettservice.exe.mdb 
jackett_1      | 10-17 18:02:00 Info Copying jacketttray.exe 
jackett_1      | 10-17 18:02:00 Info Copying jacketttray.exe.config 
jackett_1      | 10-17 18:02:00 Info Copying jacketttray.exe.mdb 
jackett_1      | 10-17 18:02:00 Info Copying jackettupdater.exe 
jackett_1      | 10-17 18:02:00 Info Copying jackettupdater.exe.config 
jackett_1      | 10-17 18:02:00 Info Copying jackettupdater.exe.mdb 
jackett_1      | 10-17 18:02:00 Info Copying license 
jackett_1      | 10-17 18:02:00 Info Copying microsoft.aspnet.identity.core.dll 
jackett_1      | 10-17 18:02:00 Info Copying microsoft.owin.filesystems.dll 
jackett_1      | 10-17 18:02:00 Info Copying microsoft.owin.host.httplistener.dll 
jackett_1      | 10-17 18:02:00 Info Copying microsoft.owin.host.systemweb.dll 
jackett_1      | 10-17 18:02:00 Info Copying microsoft.owin.hosting.dll 
jackett_1      | 10-17 18:02:00 Info Copying microsoft.owin.staticfiles.dll 
jackett_1      | 10-17 18:02:00 Info Copying microsoft.owin.dll 
jackett_1      | 10-17 18:02:00 Info Copying monotorrent.dll 
jackett_1      | 10-17 18:02:00 Info Copying nlog.dll 
jackett_1      | 10-17 18:02:00 Info Copying newtonsoft.json.dll 
jackett_1      | 10-17 18:02:00 Info Copying owin.dll 
jackett_1      | 10-17 18:02:00 Info Copying readme.md 
jackett_1      | 10-17 18:02:00 Info Copying system.net.http.extensions.dll 
jackett_1      | 10-17 18:02:00 Info Copying system.net.http.formatting.dll 
jackett_1      | 10-17 18:02:00 Info Copying system.net.http.primitives.dll 
jackett_1      | 10-17 18:02:00 Info Copying system.web.http.owin.dll 
jackett_1      | 10-17 18:02:00 Info Copying system.web.http.tracing.dll 
jackett_1      | 10-17 18:02:00 Info Copying system.web.http.dll 
jackett_1      | 10-17 18:02:00 Info Copying upstart.config 
jackett_1      | 10-17 18:02:00 Info Copying animate.css 
jackett_1      | 10-17 18:02:00 Info Copying binding_dark.png 
jackett_1      | 10-17 18:02:00 Info Copying common.js 
jackett_1      | 10-17 18:02:00 Info Copying congruent_outline.png 
jackett_1      | 10-17 18:02:00 Info Copying crissxcross.png 
jackett_1      | 10-17 18:02:00 Info Copying custom.css 
jackett_1      | 10-17 18:02:00 Info Copying custom.js 
jackett_1      | 10-17 18:02:00 Info Copying favicon.ico 
jackett_1      | 10-17 18:02:00 Info Copying index.html 
jackett_1      | 10-17 18:02:00 Info Copying jacket_medium.png 
jackett_1      | 10-17 18:02:00 Info Copying login.html 
jackett_1      | 10-17 18:02:00 Info Copying setup_indexer.html 
jackett_1      | 10-17 18:02:00 Info Copying bootstrap.min.css 
jackett_1      | 10-17 18:02:00 Info Copying bootstrap.min.js 
jackett_1      | 10-17 18:02:00 Info Copying font-awesome.min.css 
jackett_1      | 10-17 18:02:00 Info Copying jquery.datatables.css 
jackett_1      | 10-17 18:02:00 Info Copying jquery.datatables.min.css 
jackett_1      | 10-17 18:02:00 Info Copying jquery.datatables_themeroller.css 
jackett_1      | 10-17 18:02:00 Info Copying fontawesome.otf 
jackett_1      | 10-17 18:02:00 Info Copying fontawesome-webfont.eot 
jackett_1      | 10-17 18:02:00 Info Copying fontawesome-webfont.svg 
jackett_1      | 10-17 18:02:00 Info Copying fontawesome-webfont.ttf 
jackett_1      | 10-17 18:02:00 Info Copying fontawesome-webfont.woff 
jackett_1      | 10-17 18:02:00 Info Copying fontawesome-webfont.woff2 
jackett_1      | 10-17 18:02:00 Info Copying glyphicons-halflings-regular.eot 
jackett_1      | 10-17 18:02:00 Info Copying glyphicons-halflings-regular.svg 
jackett_1      | 10-17 18:02:00 Info Copying glyphicons-halflings-regular.ttf 
jackett_1      | 10-17 18:02:00 Info Copying glyphicons-halflings-regular.woff 
jackett_1      | 10-17 18:02:00 Info Copying glyphicons-halflings-regular.woff2 
jackett_1      | 10-17 18:02:00 Info Copying sort_asc.png 
jackett_1      | 10-17 18:02:00 Info Copying sort_asc_disabled.png 
jackett_1      | 10-17 18:02:00 Info Copying sort_both.png 
jackett_1      | 10-17 18:02:00 Info Copying sort_desc.png 
jackett_1      | 10-17 18:02:00 Info Copying sort_desc_disabled.png 
jackett_1      | 10-17 18:02:00 Info Copying bootstrap-notify.js 
jackett_1      | 10-17 18:02:00 Info Copying filesize.min.js 
jackett_1      | 10-17 18:02:00 Info Copying handlebars.min.js 
jackett_1      | 10-17 18:02:00 Info Copying handlebarsmoment.js 
jackett_1      | 10-17 18:02:00 Info Copying jquery.datatables.min.js 
jackett_1      | 10-17 18:02:00 Info Copying jquery.min.js 
jackett_1      | 10-17 18:02:00 Info Copying moment.min.js 
jackett_1      | 10-17 18:02:00 Info Copying abnormal.png 
jackett_1      | 10-17 18:02:00 Info Copying alpharatio.png 
<< numerous similar statements snipped >>
jackett_1      | 10-17 18:02:00 Info Copying xspeeds.png 
jackett_1      | 10-17 18:02:00 Info Copying xthor.png 
jackett_1      | 10-17 18:02:00 Info Starting Jackett: mono /app/Jackett/JackettConsole.exe jackettconsole.exe  
jackett_1      | 10-17 18:02:00 Info Starting Jackett 0.7.425.0 
jackett_1      | 10-17 18:02:00 Info Using HTTP Client: UnixLibCurlWebClient 
jackett_1      | 10-17 18:02:00 Info LibCurl init Ok 
jackett_1      | 10-17 18:02:00 Info LibCurl version libcurl/7.50.3 OpenSSL/1.0.2i zlib/1.2.8 libssh2/1.7.0 
jackett_1      | 10-17 18:02:00 Info Starting web server at http://*:9117/ 
jackett_1      | 10-17 18:02:00 Error Top level exception System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.Sockets.SocketException: Address already in use
jackett_1      |   at System.Net.Sockets.Socket.Bind (System.Net.EndPoint local_end) <0x406296f0 + 0x000f7> in <filename unknown>:0 
jackett_1      |   at System.Net.EndPointListener..ctor (System.Net.IPAddress addr, Int32 port, Boolean secure) <0x406265d0 + 0x0014f> in <filename unknown>:0 
jackett_1      |   at System.Net.EndPointManager.GetEPListener (System.String host, Int32 port, System.Net.HttpListener listener, Boolean secure) <0x406260e0 + 0x00313> in <filename unknown>:0 
jackett_1      |   at System.Net.EndPointManager.AddPrefixInternal (System.String p, System.Net.HttpListener listener) <0x40624360 + 0x000c7> in <filename unknown>:0 
jackett_1      |   at System.Net.EndPointManager.AddListener (System.Net.HttpListener listener) <0x40623e30 + 0x0015b> in <filename unknown>:0 
jackett_1      |   --- End of inner exception stack trace ---
jackett_1      |   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x7f0e1dbf48c0 + 0x000f1> in <filename unknown>:0 
jackett_1      |   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) <0x7f0e1da2bec0 + 0x0002a> in <filename unknown>:0 
jackett_1      |   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create (IAppBuilder builder) <0x4061fc90 + 0x00203> in <filename unknown>:0 
jackett_1      |   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer (Microsoft.Owin.Hosting.Engine.StartContext context) <0x4061fc50 + 0x0002d> in <filename unknown>:0 
jackett_1      |   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start (Microsoft.Owin.Hosting.Engine.StartContext context) <0x405eef00 + 0x0015f> in <filename unknown>:0 
jackett_1      |   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start (Microsoft.Owin.Hosting.StartOptions options) <0x405ee160 + 0x00064> in <filename unknown>:0 
jackett_1      |   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start (Microsoft.Owin.Hosting.StartOptions options) <0x405eca40 + 0x00087> in <filename unknown>:0 
jackett_1      |   at Microsoft.Owin.Hosting.WebApp.StartImplementation (IServiceProvider services, Microsoft.Owin.Hosting.StartOptions options) <0x405ec3a0 + 0x00066> in <filename unknown>:0 
jackett_1      |   at Microsoft.Owin.Hosting.WebApp.Start (Microsoft.Owin.Hosting.StartOptions options) <0x405eae70 + 0x00027> in <filename unknown>:0 
jackett_1      |   at Microsoft.Owin.Hosting.WebApp.Start[TStartup] (Microsoft.Owin.Hosting.StartOptions options) <0x405ead60 + 0x00047> in <filename unknown>:0 
jackett_1      |   at Jackett.Services.ServerService.Start () <0x405ea170 + 0x00237> in <filename unknown>:0 
jackett_1      |   at JackettConsole.Program.Main (System.String[] args) <0x404b3d90 + 0x00eba> in <filename unknown>:0 
```

It appears as though its trying to start twice -- and as above, a restart of the docker container always fixes it.

Frustrating, though. :)

**Comment by JigSawFr** [comment] 2016-10-19 07:01
Confirmed with this docker image, Maybe related to this docker image, need to investigate.

**Comment by raspdealer** [comment] 2016-11-06 09:30
Still the issue here... any updates? :)

**Comment by raspdealer** [comment] 2016-11-06 09:40
It happend right now.
I've rebooted, here are the logs and after it failed again.

This is the log between two crashes:

```
2016-11-06 10:25:38.9594 Info Curl will ignore SSL certificate errors. 
2016-11-06 10:25:40.7773 Info Starting Jackett 0.7.539.0 
2016-11-06 10:25:40.7926 Info Using HTTP Client: UnixLibCurlWebClient 
2016-11-06 10:25:43.7879 Info Loading Cardigann definitions from: /home/osmc/.config/cardigann/definitions/ 
2016-11-06 10:25:43.7936 Info Loading Cardigann definitions from: /etc/xdg/cardigan/definitions/ 
2016-11-06 10:25:43.8069 Info Loading Cardigann definitions from: /opt/Jackett/Definitions 
2016-11-06 10:25:43.8378 Info Loading Cardigann definition /opt/Jackett/Definitions/hdme.yml 
2016-11-06 10:25:44.8205 Info Loading Cardigann definition /opt/Jackett/Definitions/shareisland.yml 
2016-11-06 10:25:44.9374 Info Loading Cardigann definition /opt/Jackett/Definitions/uhdbits.yml 
2016-11-06 10:25:45.0291 Info Loading Cardigann definition /opt/Jackett/Definitions/worldofp2p.yml 
2016-11-06 10:25:45.2508 Info LibCurl init Ok 
2016-11-06 10:25:45.2611 Info LibCurl version libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3 
2016-11-06 10:25:45.2726 Info Starting web server at http://*:9118/ 
2016-11-06 10:26:13.4117 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]' 
2016-11-06 10:26:13.4352 Info ApiControllerActionInvoker InvokeActionAsync  
2016-11-06 10:26:13.4422 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'SetConfig()' 
2016-11-06 10:26:13.4458 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2016-11-06 10:26:13.4480 Info AdminController ExecuteAsync  
2016-11-06 10:26:13.4541 Info   Content-type='application/json; charset=utf-8', content-length=48 
2016-11-06 10:26:13.4590 Info AdminController Dispose  
2016-11-06 10:26:13.4618 Info AdminController Dispose  
2016-11-06 10:26:31.7890 Info   http://192.168.1.116:9118/Admin/Dashboard 
2016-11-06 10:26:31.8040 Info DefaultHttpControllerSelector SelectController Route='action:Dashboard,controller:Admin' 
2016-11-06 10:26:31.8068 Info DefaultHttpControllerSelector SelectController Admin 
2016-11-06 10:26:31.8085 Info HttpControllerDescriptor CreateController  
2016-11-06 10:26:31.8100 Info DefaultHttpControllerActivator Create  
2016-11-06 10:26:31.8130 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2016-11-06 10:26:31.8161 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2016-11-06 10:26:31.8178 Info AdminController ExecuteAsync  
2016-11-06 10:26:31.8194 Info ApiControllerActionSelector SelectAction  
2016-11-06 10:26:31.8244 Info ApiControllerActionSelector SelectAction Selected action 'Dashboard()' 
2016-11-06 10:26:31.8299 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-11-06 10:26:31.8329 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-11-06 10:26:31.8347 Info HttpActionBinding ExecuteBindingAsync  
2016-11-06 10:26:31.8413 Info HttpActionBinding ExecuteBindingAsync  
2016-11-06 10:26:31.8449 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Dashboard()' 
2016-11-06 10:26:31.8476 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2016-11-06 10:26:31.8572 Info ApiControllerActionInvoker InvokeActionAsync Action='Dashboard()' 
2016-11-06 10:26:31.8604 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Dashboard()' 
2016-11-06 10:26:31.8678 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
Content-Type: text/html
}' 
2016-11-06 10:26:31.8694 Info ApiControllerActionInvoker InvokeActionAsync  
2016-11-06 10:26:31.8711 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Dashboard()' 
2016-11-06 10:26:31.8728 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2016-11-06 10:26:31.8757 Info AdminController ExecuteAsync  
2016-11-06 10:26:31.8802 Info   Content-type='text/html', content-length=26224 
2016-11-06 10:26:31.8868 Info AdminController Dispose  
2016-11-06 10:26:31.8883 Info AdminController Dispose  
2016-11-06 10:26:33.1197 Info   http://192.168.1.116:9118/Admin/get_jackett_config?_=1478424392606 
2016-11-06 10:26:33.1221 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
2016-11-06 10:26:33.1243 Info DefaultHttpControllerSelector SelectController Admin 
2016-11-06 10:26:33.1283 Info HttpControllerDescriptor CreateController  
2016-11-06 10:26:33.1300 Info DefaultHttpControllerActivator Create  
2016-11-06 10:26:33.1320 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2016-11-06 10:26:33.1336 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2016-11-06 10:26:33.1356 Info AdminController ExecuteAsync  
2016-11-06 10:26:33.1376 Info ApiControllerActionSelector SelectAction  
2016-11-06 10:26:33.1407 Info ApiControllerActionSelector SelectAction Selected action 'GetConfig()' 
2016-11-06 10:26:33.1428 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-11-06 10:26:33.1450 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-11-06 10:26:33.1466 Info HttpActionBinding ExecuteBindingAsync  
2016-11-06 10:26:33.1481 Info HttpActionBinding ExecuteBindingAsync  
2016-11-06 10:26:33.1496 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'GetConfig()' 
2016-11-06 10:26:33.1511 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2016-11-06 10:26:33.1526 Info ApiControllerActionInvoker InvokeActionAsync Action='GetConfig()' 
2016-11-06 10:26:33.1543 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'GetConfig()' 
2016-11-06 10:26:33.1568 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]' 
2016-11-06 10:26:33.1590 Info ApiControllerActionInvoker InvokeActionAsync  
2016-11-06 10:26:33.1611 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'GetConfig()' 
2016-11-06 10:26:33.1634 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2016-11-06 10:26:33.1655 Info AdminController ExecuteAsync  
2016-11-06 10:26:33.1676 Info   Content-type='application/json; charset=utf-8', content-length=250 
2016-11-06 10:26:33.1713 Info AdminController Dispose  
2016-11-06 10:26:33.1728 Info AdminController Dispose  
2016-11-06 10:26:33.5570 Info   http://192.168.1.116:9118/Admin/get_indexers?_=1478424392607 
2016-11-06 10:26:33.5591 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
2016-11-06 10:26:33.5609 Info DefaultHttpControllerSelector SelectController Admin 
2016-11-06 10:26:33.5625 Info HttpControllerDescriptor CreateController  
2016-11-06 10:26:33.5640 Info DefaultHttpControllerActivator Create  
2016-11-06 10:26:33.5664 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2016-11-06 10:26:33.5682 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2016-11-06 10:26:33.5700 Info AdminController ExecuteAsync  
2016-11-06 10:26:33.5714 Info ApiControllerActionSelector SelectAction  
2016-11-06 10:26:33.5735 Info ApiControllerActionSelector SelectAction Selected action 'Indexers()' 
2016-11-06 10:26:33.5754 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-11-06 10:26:33.5946 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-11-06 10:26:33.5961 Info HttpActionBinding ExecuteBindingAsync  
2016-11-06 10:26:33.5975 Info HttpActionBinding ExecuteBindingAsync  
2016-11-06 10:26:33.5995 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Indexers()' 
2016-11-06 10:26:33.6013 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2016-11-06 10:26:33.6030 Info ApiControllerActionInvoker InvokeActionAsync Action='Indexers()' 
2016-11-06 10:26:33.6047 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Indexers()' 
2016-11-06 10:26:33.6448 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JObject]' 
2016-11-06 10:26:33.6542 Info ApiControllerActionInvoker InvokeActionAsync  
2016-11-06 10:26:33.6562 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Indexers()' 
2016-11-06 10:26:33.6576 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2016-11-06 10:26:33.6591 Info AdminController ExecuteAsync  
2016-11-06 10:26:33.6607 Info   Content-type='application/json; charset=utf-8', content-length=32512 
2016-11-06 10:26:33.6680 Info AdminController Dispose  
2016-11-06 10:26:33.6694 Info AdminController Dispose  
2016-11-06 10:32:52.6886 Info   http://192.168.1.116:9118/Admin/Dashboard 
2016-11-06 10:32:52.6931 Info DefaultHttpControllerSelector SelectController Route='action:Dashboard,controller:Admin' 
2016-11-06 10:32:52.6959 Info DefaultHttpControllerSelector SelectController Admin 
2016-11-06 10:32:52.6982 Info HttpControllerDescriptor CreateController  
2016-11-06 10:32:52.7006 Info DefaultHttpControllerActivator Create  
2016-11-06 10:32:52.7060 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2016-11-06 10:32:52.7124 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2016-11-06 10:32:52.7179 Info AdminController ExecuteAsync  
2016-11-06 10:32:52.7250 Info ApiControllerActionSelector SelectAction  
2016-11-06 10:32:52.7282 Info ApiControllerActionSelector SelectAction Selected action 'Dashboard()' 
2016-11-06 10:32:52.7328 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-11-06 10:32:52.7493 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-11-06 10:32:52.7521 Info HttpActionBinding ExecuteBindingAsync  
2016-11-06 10:32:52.7550 Info HttpActionBinding ExecuteBindingAsync  
2016-11-06 10:32:52.7824 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Dashboard()' 
2016-11-06 10:32:52.7850 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2016-11-06 10:32:52.7878 Info ApiControllerActionInvoker InvokeActionAsync Action='Dashboard()' 
2016-11-06 10:32:52.7902 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Dashboard()' 
2016-11-06 10:32:52.7939 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
Content-Type: text/html
}' 
2016-11-06 10:32:52.7970 Info ApiControllerActionInvoker InvokeActionAsync  
2016-11-06 10:32:52.8003 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Dashboard()' 
2016-11-06 10:32:52.8031 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2016-11-06 10:32:52.8094 Info AdminController ExecuteAsync  
2016-11-06 10:32:52.8135 Info   Content-type='text/html', content-length=26224 
2016-11-06 10:32:52.8247 Info AdminController Dispose  
2016-11-06 10:32:52.8339 Info AdminController Dispose  
```

**Comment by mrjack711** [comment] 2016-11-06 10:49
Hi, sorry I haven't replied to this.
Just to say, I upgraded to mono 4.6 and I no longer have the issue.

**Comment by raspdealer** [comment] 2016-11-09 18:27
On my side, here are more infos:

sudo service jackett status
* jackett.service - Jackett Daemon
   Loaded: loaded (/etc/systemd/system/jackett.service; enabled)
   Active: active (exited) (Result: exit-code) since Sun 2016-11-06 10:43:11 CET; 3 days ago
  Process: 18292 ExecStart=/usr/bin/mono --debug /opt/Jackett/JackettConsole.exe --IgnoreSslErrors true **(code=exited, status=255)**
 Main PID: 18292 **(code=exited, status=255)**
   CGroup: /system.slice/jackett.service

Nov 08 06:08:29 osmc mono[18292]: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[Jackett.CurlHelper+CurlResponse].SetResult (Jacket...unknown>:0
Nov 08 06:08:29 osmc mono[18292]: at Jackett.CurlHelper+<PerformCurlAsync>c__async2.MoveNext () [0x000bb] in C:\projects\jackett\src\Jackett\CurlHelper.cs:74
Nov 08 06:08:29 osmc mono[18292]: at (wrapper unbox) Jackett.CurlHelper/<PerformCurlAsync>c__async2:MoveNext ()
Nov 08 06:08:29 osmc mono[18292]: at System.Threading.Tasks.AwaiterActionContinuation.Execute () [0x00000] in <filename unknown>:0
Nov 08 06:08:29 osmc mono[18292]: at System.Threading.Tasks.Task.ProcessCompleteDelegates () [0x00000] in <filename unknown>:0
Nov 08 06:08:29 osmc mono[18292]: at System.Threading.Tasks.Task.Finish () [0x00000] in <filename unknown>:0
Nov 08 06:08:29 osmc mono[18292]: at System.Threading.Tasks.Task.ThreadStart () [0x00000] in <filename unknown>:0
Nov 08 06:08:29 osmc mono[18292]: at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0
Nov 08 06:08:29 osmc mono[18292]: at System.Threading.Tasks.TpScheduler.TaskExecuterCallback (System.Object obj) [0x00000] in <filename unknown>:0
Nov 08 06:08:30 osmc systemd[1]: jackett.service: main process exited, code=exited, status=255/n/a
Hint: Some lines were ellipsized, use -l to show in full.
osmc@osmc:~$

**Comment by kaso17** [comment] 2016-11-10 06:05
Please post some more log lines before the already posted lines

**Comment by armani316** [comment] 2017-01-26 21:51
@kaso17 Might be a good idea to close this issue since it hasn't had any activity in a while.

**Closed** 2017-01-27 07:53 UTC
Labels: Confirmed, Core
