### ISSUE TITLE
xbytesv2: missing the year on searches

### ISSUE THREAD

**Issue by RicardoVelaC** [Jackett/Jackett#7790] opened 2020-03-21 21:17 UTC
### Environment

**OS**: [Docker] linuxserver/jackett
**Jackett Version**: 0.14.164.0
**Are you using a proxy or VPN?** NO

### Description
Search on xbytesv2 definition
http://xbytesv2.li/

### Logged Error Messages

No errors

### Fix
Jackett removes the year from the title e.g.:
- Website format: `Intemperie (2019/BDRIP/1080P/AC3 5.1/ESP/DTS/ESP/SUBS)`
- Jackett result: `Intemperie BDRIP 1080P AC3 5 1 Spanish DTS Spanish SUBS`

**Comment by garfield69** [comment] 2020-03-22 04:42
Apparently this was deliberate. See this comment for details 
 https://github.com/Jackett/Jackett/pull/3068#issue-185954215
https://github.com/Jackett/Jackett/blob/00cd1bd81c9914cc9aa31e7a380ff498b718d1fe/src/Jackett.Common/Definitions/xbytes2.yml#L108-L138

**Comment by cadatoiva** [comment] 2020-03-22 05:58
This is also a duplicate of #3290 which never seemed to be resolved, maybe we should revisit that conversation and see what can be done?

**Closed** 2020-03-22 21:50 UTC

**Comment by garfield69** [comment] 2020-03-23 06:02
Jackett 0.14.243
