### ISSUE TITLE
[Fuzer] Error when trying fetch from Fuzer tracker using Radarr client

### ISSUE THREAD

**Issue by BuSHari** [Jackett/Jackett#2415] opened 2018-01-13 17:08 UTC
Hello,

Since the last updates (it worked fine 10 days ago) i'm getting an error UriException, When using the Radarr client i'm getting error when i try to fetch from Fuzer tracker, but when testing trough Jackett everything seems to be fine, please see log...

part of the error:
```
Error Jackett.IndexerException: Exception (fuzer): Invalid URI: The format of the URI could not be determined. ---> System.Exception: Parse error ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.
  at System.Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind) [0x0007b] in <50d80b08c1a5449282b22aedf03ce925>:0 
  at System.Uri..ctor (System.String uriString) [0x00014] in <50d80b08c1a5449282b22aedf03ce925>:0 
  at Jackett.Indexers.Fuzer+<performRegularQuery>d__12.MoveNext () [0x003e4] in <8fa686a911e6429b91b3ce9ab4a4a7e8>:0 
```

Jackett version:  0.8.588.0 (docker-synology)
Mono version (if not using Windows): 4.6.2
Log: [log-jackett.txt](https://github.com/Jackett/Jackett/files/1628531/log-jackett.txt)
 

-------------------------------

**Comment by BuSHari** [comment] 2018-01-13 19:58
It happen only for the Movies and not for TV-Shows when trying to query trough the api

**Comment by BuSHari** [comment] 2018-01-15 09:31
@kaso17 I think there is a problem with the category mapping

**Comment by kaso17** [comment] 2018-01-15 18:09
fixed via f25719fd9eb032ceafb3c95be7735682039df317
Caused by invalid banner images, e.g. for the After the Ball 2015 720p WEB-​DL XviD AC3-​RARBG release.

**Closed by kaso17** 2018-01-15 18:09 UTC

**Comment by BuSHari** [comment] 2018-01-15 19:30
Thank you for the quick fix...
I don`t see any problem with the image in that movie, I've searched in some other movies the tag 'imgsrc' and all of them seems to be the same.
Maybe there is another fix need to be done to catch all the banner images?

**Comment by kaso17** [comment] 2018-01-15 19:35
`<a href="/showthread.php?t=100174" id="eng-l-title_65933" rel="imgtip[65933]" class="threadlink" imgsrc="asdasda">After the Ball 2015 720p WEB-DL XviD AC3-RARBG</a>`
the imgsrc attribute is garbage (It's supposed to be a full URL).
Please try v0.8.602

**Comment by BuSHari** [comment] 2018-01-15 19:42
Ohhh now i understand... thank you very much!
