### ISSUE TITLE
Gimmepeers - Configuration failed: Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by TheDogg** [Jackett/Jackett#1019] opened 2017-02-01 23:52 UTC
When trying to add Gimmepeers as an indexer, I get the following message:
Configuration failed: Found no results while trying to browse this tracker

in the log it shows:
`
2017-02-01 18:37:42.0308 Info Found 0 releases from GimmePeers 
2017-02-01 18:37:42.0418 Error Exception in Configure System.Exception: Found no results while trying to browse this tracker
   at Jackett.Services.IndexerManagerService.<TestIndexer>d__12.MoveNext() in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 156
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Configure>d__16.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 191
2017-02-01 18:37:42.0528 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult` `1[Newtonsoft.Json.Linq.JObject]' 
2017-02-01 18:37:42.0658 Info ApiControllerActionInvoker InvokeActionAsync  
2017-02-01 18:37:42.0658 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Configure()' 
2017-02-01 18:37:42.0918 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2017-02-01 18:37:42.1068 Info AdminController ExecuteAsync  
2017-02-01 18:37:42.1238 Info   Content-type='application/json; charset=utf-8', content-length=101 
2017-02-01 18:37:42.1429 Info AdminController Dispose  
2017-02-01 18:37:42.1619 Info AdminController Dispose  `

Jackett Version 0.7.969.0 on windows

-------------------------------

**Comment by kaso17** [comment] 2017-02-02 07:44
@TheDogg please post a log with "enhanced loggin" enabled.
@jamesb2147 can you help?

**Comment by TheDogg** [comment] 2017-02-02 13:17
@kaso17 this is the "enhanced logging" log, the only other log entry is the full html dump of the page, do you need that aswell?

**Comment by kaso17** [comment] 2017-02-02 14:18
that looks fine, jamesb2147 should be able to reproduce the error with that HTML code.

**Comment by TheDogg** [comment] 2017-02-06 21:11
any updates on this?  still having the same issue with Jackett Version 0.7.983.0
@kaso17 @jamesb2147

**Comment by jamesb2147** [comment] 2017-02-07 03:54
I'm able to reproduce it and am working on it. Programming isn't something I do every day, much less parsing HTML. It'll take some time to get this wrapped up properly.

I'll post again when I've made some progress, or you'll see the issue closed when the fixed code is merged into Jackett.

**Comment by TheDogg** [comment] 2017-02-07 14:51
thanks a lot for the update, I appreciate the work.  I will keep monitoring the issue

**Comment by armani316** [comment] 2017-02-28 15:10
@TheDogg @jamesb2147 Just wanted to double check whether this is still an active issue?

**Comment by jamesb2147** [comment] 2017-02-28 19:26
Yes this is still an active issue.

**Comment by albertsj1** [comment] 2017-03-09 07:11
Having the same issue.  Wish I could do something to help out, but I don't even know where to get started with C#.

**Comment by RoloSoze** [comment] 2017-03-09 19:23
If anyone wants to join this tracker and debug the issue, they're currently open for registration.

Signup link:
https://www.gimmepeers.com/guestentry.php

Invite code:
JusHy6F23i7GyeZ

**Comment by kaso17** [comment] 2017-03-09 21:30
I assume it's still a pay for access tracker? I won't touch it n that case.

**Comment by RoloSoze** [comment] 2017-03-09 21:38
@kaso17 Yes, it's still a paid tracker.

**Comment by jamesb2147** [comment] 2017-03-10 04:02
I don't think it's especially relevant to C# specifically... I suspect the issue is in the parser. Anyone in this thread should be able to post a debug output from above the error. There's a ton of HTML tags, which is exactly what the parser needs, but then it errors out saying it "can't find anything."

My hunch is that the tag parsing is off; the code looks for particular HTML tags and has logic built around encountering a certain number of those in a certain order. If they were at all off, say, because the site owners added another link at the top of every page (or kept making banners appear on login), it might cause the whole parser to choke.

Just my $0.02. If anyone has the free time, take a look at your own debug output, or post it here, and somebody might step up to step through the parsing code and compare it to your example output.

**Comment by RoloSoze** [comment] 2017-03-10 13:55
Joined for the sake of reproducing the error, no plans to become a member. Here's an enhanced log of the error.
[log.txt](https://github.com/Jackett/Jackett/files/834090/log.txt)

**Comment by gregoryduckworth** [comment] 2017-04-13 08:33
I've been getting the same issue as this when using demonoid, with enhanced logging showing the same log as @RoloSoze

**Comment by gregoryduckworth** [comment] 2017-04-13 08:36
I've been experiencing the same issue but with Demonoid and my logs show the same issue as @RoloSoze

**Comment by kaso17** [comment] 2017-04-20 12:09
The log file 
@gregoryduckworth please open a new issue for Demonoid.
It's most likely unrelated.
based on the log from RoloSoze it looks like the rows selector is simply wrong (changed) or there's some profile setting, etc. causing a different style to be used. I won't fix this.

**Comment by TheDogg** [comment] 2017-04-22 01:43
@kaso17 @jamesb2147 

I know a little programming and HTML, can you point me in the right direction to debug this on my own?  I'd really like to get this tracker working

**Comment by flightlevel** [comment] 2017-04-22 01:56
Download and install Visual studio community https://www.visualstudio.com/downloads/
Clone the Jackett repo to your PC
Open the Jackett.sln file in Visual Studio
Right click on Jackett.Console and click set as startup project
Hit F5 to debug
Open Jackett Dashboard from your web browser, reproduce the error ie. Adding tracker
and Visual Studio will stop where the error is and it should be pretty obvious whats happening from the line of code in GimmePeers it stops at where its going wrong

**Comment by BenJaminBMorin** [comment] 2017-05-20 03:26
I'm not good with github, so here's the fix:
/ Jackett/indexers/GimmePeers.cs
#line 134
var rows = dom[".browsetable tr"]; //the class for the table changed
#line 162
var added = row.Cq().Find("td:eq(6)").First().Text().Trim(); //column changed from 7 to 6
#line 164
var time = added.Substring(11, 8); //date layout wasn't quite right
#line 168
var sizeStr = row.Cq().Find("td:eq(5)").First().Text().Trim(); //size column moved from 8 to 5.
[GimmePeers.txt](https://github.com/Jackett/Jackett/files/1015856/GimmePeers.txt)

**Comment by TheDogg** [comment] 2017-05-20 13:28
woah, thanks @BenJaminBMorin 

I created a pull request for those changes

**Comment by kaso17** [comment] 2017-05-20 14:18
Thank you @BenJaminBMorin and @TheDogg

**Closed** 2017-05-20 14:17 UTC
Labels: Confirmed, Needs Investigations

**Comment by jamesb2147** [comment] 2017-06-01 19:18
Anybody else seeing this on the latest release?

'''
06-01 14:13:58 Error Exception in Configure System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
  at Jackett.Indexers.BaseIndexer.OnParseError (System.String results, System.Exception ex) [0x00059] in C:\projects\jackett\src\Jackett\Indexers\BaseIndexer.cs:203 
  at Jackett.Indexers.GimmePeers+<ProcessPage>c__async2.MoveNext () [0x00346] in C:\projects\jackett\src\Jackett\Indexers\GimmePeers.cs:179 
--- End of stack trace from previous location where exception was thrown ---
'''

**Comment by albertsj1** [comment] 2017-07-03 16:49
@jamesb2147 Yep. I'm getting the same error too.  I've still never gotten this tracker working.  I just figured I'd give the latest Jackett a try and got this error when hitting the test button.

**Comment by albertsj1** [comment] 2017-07-03 16:54
@jamesb2147 I actually just got this to work.  On the gimmepeers site, I went to my profile and turned off 'View Top20'.  Clicking the test button in Jackett now shows successful.

**Comment by TheDogg** [comment] 2018-01-03 03:33
@BenJaminBMorin Would you be able to make it work with the Top20 enabled on the page?  I tried to look into the code but I cannot figure out how to have it ignore the first table with class "browsetable".

I'd really like to get it to work with the top20 enabled since I find that feature usefull when manually browsing the site.

thanks

**Comment by kaso17** [comment] 2018-01-03 18:58
the top20 issue should be fixed via #2360.
Thank you @BenJaminBMorin
