### ISSUE TITLE
[cpasbien] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by valounours** [Jackett/Jackett#1950] opened 2017-10-10 15:30 UTC
Hello,

On several providers (CpasBien, Torrent9, NextTorrent, GkTorrent) there is an error that appears when I look at the logs here is the only line of error:

"{0}"

Jackett's version: 0.8.249.0
Installed via QuickBox

**Comment by garfield69** [comment] 2017-10-11 00:02
### cpasbien: 
duplicate of #1933, resolved with 34780f91be72505c2f127df14fb793992b066018 available with the next release of Jackett. 
Or you can fix this yourself by replacing the SiteLink on the Jackett Dashboard in the cpasbien entry to `http://cpabien.org/`        
### gktorrent: 
duplicate of #1941 resolved with 49a7c8df7a2be652cb8a96ba2dd2aa42ef118761 available in the next release of Jackett      
### torrent9: 
resolved with 91817a10ffc3ef0e38e9947b90dd784269d958d4 available in the next release of Jackett. 
Or you can fix this yourself by replacing the Sitelink on the Jackett Dashboard in the Torrent9 entry to `http://www.torrents9.pe/`     
### nexttorrent: 
resolved with 8aa82a22f43949683fa3f5eac0de3c2f50908e85 available in the next release of Jackett. 
Or you can fix this yourself by replacing the Sitelink on the Jackett Dashboard in the NextTorrent entry to `https://www.nextorrent.cc/`

**Closed by garfield69** 2017-10-11 00:02 UTC
Labels: Confirmed, Fix
