### ISSUE TITLE
[mejortorrent] (configuring) Could not find releases from this URL

### ISSUE THREAD

**Issue by assjdksbak** [Jackett/Jackett#13177] opened 2022-04-18 19:29 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.17763.0 (64bit OS)
Environment version: 6.0.4 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.912
```

### Description

1. Go to "Add Indexer"
2. Add "MejorTorrent"

### Logged Error Messages

```text
System.Exception: Could not find releases from this URL
   at Jackett.Common.Indexers.MejorTorrent.<>c.<ApplyConfiguration>b__12_0() in D:\a\1\s\src\Jackett.Common\Indexers\MejorTorrent.cs:line 121
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 258
   at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\MejorTorrent.cs:line 120
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment] 2022-04-18 19:35
this web site has not had any new torrents since February 17th.
the indexer uses the [Últimos Torrents](https://www.mejortorrentes.org/secciones.php?sec=ultimos_torrents) page for the TEST during configuration, and this page has been empty since ages.
Closing this ticket as a duplicate of #12559 follow that ticket for further news.

**Closed by garfield69** 2022-04-18 19:35 UTC
