### ISSUE TITLE
[torrent9] [digbt] [torrent9clone] [cpasbien] Exception (name of indexer): The argument specified is outside the range of valid values. Parameter name: Unknown operator: Parameter name: Unknown operator: (Test)

### ISSUE THREAD

**Issue by angelss197200** [Jackett/Jackett#4935] opened 2019-03-21 20:42 UTC
hi, im trying to add new public indexers, but when i test all [torrent9] [digbt] [torrent9clone] [cpasbien] get the same error(is in spanish);
Exception (torrent9): El argumento especificado está fuera del intervalo de valores válidos.Nombre del parámetro: Unknown operator: : El argumento especificado está fuera del intervalo de valores válidos.Nombre del parámetro: Unknown operator:  (Test)

i can enter the websites without problem
pd; do you know how to change the language, only the log are in spanish

 Jackett Version 0.11.102.0

**Comment by garfield69** [comment] 2019-03-21 23:37
duplicate of #4930
follow that ticket for developments.

**Closed by garfield69** 2019-03-21 23:37 UTC
