### ISSUE TITLE
[hdtorrents] time error

### ISSUE THREAD

**Issue by baldygeraldy** [Jackett/Jackett#7455] opened 2020-03-02 15:25 UTC
Exception (hdtorrents): String '02="" mar="" 2020="" 07:21:16="" +0200=""' was not recognized as a valid DateTime.: Parse error

### Environment

**OS**: ubuntu 18.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: newest

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

Try adding hd-torrents to jackett and gets this error:

Exception (hdtorrents): String '02="" mar="" 2020="" 07:21:16="" +0200=""' was not recognized as a valid DateTime.: Parse error

**Comment by garfield69** [comment] 2020-03-02 16:15
Duplicate of #7450

**Closed by garfield69** 2020-03-02 16:15 UTC
