### ISSUE TITLE
@ngosang From indexer you can download any file

### ISSUE THREAD

**Issue by rovik0** [Jackett/Jackett#6605] opened 2019-12-13 22:02 UTC
@ngosang The indexer is working correctly for me. You're searching for _mp3_, but if you see the indexer capabilities it's compatible with Movies and TV Shows, not music or anything else.

The test button is working because the indexer it's working (image below), if you aren't able to get it working with movies or shows, then maybe something is wrong on your end.

![image](https://user-images.githubusercontent.com/10326536/70308116-e17c9800-180a-11ea-927e-bd9d89d41e46.png)

_Originally posted by @ivanbeldad in https://github.com/Jackett/Jackett/issues/6449#issuecomment-562481033_

**Comment by rovik0** [comment] 2019-12-13 22:03
No download is available

**Comment by garfield69** [comment] 2019-12-13 22:17
duplicate of #6449 
there is no need to carry forward a conversation in a new ticket,  6449 is still open and you can contribute there.

**Closed by garfield69** 2019-12-13 22:17 UTC
