### ISSUE TITLE
[rarbg] Exception (rarbg): Error parsing Infinity value. Path '', line 1, position 2.: Error parsing Infinity value. Path '', line 1, position 2. (Test)

### ISSUE THREAD

**Issue by Protektor-Desura** [Jackett/Jackett#2779] opened 2018-03-22 22:25 UTC
Getting this new error on RARGB when I do a search or test.

**Comment by garfield69** [comment] 2018-03-22 22:53
Duplicate of #2753
upgrade to Jackett v0.8.784 to pick up the fix

**Closed by garfield69** 2018-03-22 22:53 UTC
