### ISSUE TITLE
Search seems to be broken

### ISSUE THREAD

**Issue by agneevX** [Jackett/Jackett#10251] opened 2020-11-20 08:10 UTC
### Environment

**OS**: `LinuxARM32`
**.Net Runtime**: `Mono`
**.Net Version**: N/A
**Jackett Version**: `0.16.2207.0`, `0.16.2148.0` (tried both)
**Last Working Jackett Version**: ??
**Are you using a proxy or VPN?**: No

### Description

Search seems buggy.

### Steps to reproduce

- Open up manual search
- Search for something like `1080p`
- In my observation, the last result is from 41hrs ago. 
  - If I remove the search query, I can see recent results matching the query.

### Logged Error Messages
N/A

### Screenshots

When searching:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/19761269/99775410-4113a680-2b35-11eb-8715-dca07724a97c.png">

No search:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/19761269/99775725-c0a17580-2b35-11eb-8ecb-7563410a7781.png">

**Comment by garfield69** [comment] 2020-11-20 08:16
This is not something that Jackett can correct.
It is a problem with the RarBG API server, which has over the last month or so been failing 3 out of 4 times to return results.
Closing as a duplicate of #10247

**Comment by agneevX** [comment] 2020-11-20 08:17
Shouldn't the search be done from the data Jackett already has?

**Comment by garfield69** [comment] 2020-11-20 08:20
Technical question.... @ngosang can you contribute?

**Comment by ngosang** [comment] 2020-11-22 19:40
The issue is not in Jackett.
We are using a 3rd party API to search in RarBG. They provide cached results and we can't fix it. You can so some manual tests using the API. https://torrentapi.org/apidocs_v2.txt?&app_id=rarbg-rubygem

**Closed by ngosang** 2020-11-22 19:40 UTC

**Comment by agneevX** [comment] 2020-11-23 05:33
@ngosang again, that's not the point. 

The data is there and Jackett queries the API instead of querying itself when the API is having issues.

**Comment by ngosang** [comment] 2020-11-23 06:22
Jackett is far more complex than doing a string search in the cache. We support categories, imdb search, tvdb search...
You're knocking on the wrong door. Contact torrentapi  sys admin.

**Comment by agneevX** [comment] 2020-11-23 06:35
Huh? You're not making much sense. All those complexity you talk about doesn't seem to help me if can't do a _simple string search from the cache_.
