### ISSUE TITLE
Indexer ETTV has been down for roughly two weeks now.

### ISSUE THREAD

**Issue by ukharley** [Jackett/Jackett#12918] opened 2022-02-06 05:38 UTC
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows 10, Edge, Jackett Version v0.20.514
```

### Description

Try using ETTV.

### Logged Error Messages

```text
Cloudflare error with site not responding.
According to TorrentFreak it probably wont be back
```

### Screenshots

![ettv](https://user-images.githubusercontent.com/6772644/152668972-49834b67-fbc0-4bae-934c-0eb9ee203804.png)

**Comment by garfield69** [comment] 2022-02-06 05:42
duplicate of #2052
we usually wait about 30 days before removing an indexer, to allow time to confirm a site is gone, unless we get conclusive proof beforehand (such as a post from a reputable source on a forum or web).

**Closed by garfield69** 2022-02-06 05:42 UTC
