### ISSUE TITLE
[iptorrents]  Request to Jackett server failed

### ISSUE THREAD

**Issue by olli460** [Jackett/Jackett#6440] opened 2019-11-28 17:23 UTC
I installed Sonarr and Radarr a few weeks back and then quickly realised i needed Jackett for IPTorrents, got it all setup and was working fine. I had some OS updates on my server so did a reboot, now i just can't connect to IPTorrents in jackett.

I've gone through the several other support threads on here regarding the same issue and haven't found anyway of fixing the issue. Really would love to get it working again

I can access IPTorrents fine in my browser, server can access it fine too. I've tried Shift+F5.

Does someone have a default iptorrents.json file i can try manually adding it?

This is the log.txt

> Nov 28, 2019 05:19:24 PM | Error | System.Exception: Error parsing JS challenge html    at CloudflareSolverRe.Types.Javascript.JsChallenge.Parse(String html, Uri siteUrl)    at CloudflareSolverRe.Solvers.JsChallengeSolver.SolveChallenge(String html)    at CloudflareSolverRe.Solvers.JsChallengeSolver.Solve()    at CloudflareSolverRe.CloudflareSolver.SolveJavascriptChallenge(Nullable`1 jsDetectResult)    at CloudflareSolverRe.CloudflareSolver.SolveWithJavascript(Int32 tries)    at CloudflareSolverRe.CloudflareSolver.Solve()    at CloudflareSolverRe.CloudflareSolver.Solve(HttpClient httpClient, CloudflareHandler cloudflareHandler, Uri siteUrl, CancellationToken cancellationToken)    at CloudflareSolverRe.CloudflareSolver.<>c__DisplayClass30_0.<<Solve>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at CloudflareSolverRe.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)    at CloudflareSolverRe.CloudflareSolver.Solve(HttpClient httpClient, HttpClientHandler httpClientHandler, Uri siteUrl, CancellationToken cancellationToken, Boolean randomUserAgent)    at CloudflareSolverRe.ClearanceHandler.GetClearance(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 241    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445    at Jackett.Common.Indexers.IPTorrents.GetConfigurationForSetup() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/IPTorrents.cs:line 147    at Jackett.Server.Controllers.IndexerApiController.Config() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
> -- | -- | --

**Comment by Corjaantje** [comment] 2019-11-28 17:31
Glad to hear I am not the only one experiencing this issue! Exact same issue, exact same error.

**Comment by cbryson84** [comment] 2019-11-28 17:53
I believe this is part of #6432 I’m also experiencing this problem.

**Comment by garfield69** [comment] 2019-11-28 17:59
this is a duplicate of issue #6432 so I am closing it. 
Follow 6432 for updates on resolution.

**Closed by garfield69** 2019-11-28 17:59 UTC
