### ISSUE TITLE
[1337x] Exception (1337x): The method or operation is not implemented.: The method or operation is not implemented. (Test)

### ISSUE THREAD

**Issue by Wouldster** [Jackett/Jackett#9583] opened 2020-09-21 11:52 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Jackett and Sonarr are running on Synology
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
0.14.485-10

**Last Working Jackett Version**:
0.14.485-10

**Are you using a proxy or VPN?** [yes/no]
Yes
### Description
Hi,

So since this morning all the indexers where coming up withe error above. Ive changed nothing and nonupdates have happened. Anyone have a clue what the problem might be? ive tried without VPN, rebooted router and server.

Ive run Jackett in a browser and all Indexers come up with the same error

![Screenshot 2020-09-21 at 7 50 06 PM](https://user-images.githubusercontent.com/38676698/93763297-c7019700-fc43-11ea-8e36-d259ec9bb96d.png)

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by TheOnlyMunk** [comment] 2020-09-21 12:01
Same [issue ](https://github.com/Jackett/Jackett/issues/9584)I think.

**Comment by ilike2burnthing** [comment] 2020-09-21 13:23
Update to v0.16.1269

**Comment by ngosang** [comment] 2020-09-21 16:42
Duplicate of https://github.com/Jackett/Jackett/issues/9569#issuecomment-696153357

**Closed by ngosang** 2020-09-21 16:42 UTC
