### ISSUE TITLE
[Enhancement] Autodownload new indexers and definitons

### ISSUE THREAD

**Issue by edalex86** [Jackett/Jackett#2888] opened 2018-04-05 08:50 UTC
Hi there,
what about updating Jackett only if some core features had changed and if some site changes just let client download new definition from server? Indexers could be distributed as csscript files for example.
Thanks.

**Jackett version**:  any

-------------------------------

**Comment by flightlevel** [comment] 2018-04-06 10:29
This is not as simple as it sounds, but you are welcome to create a pull request if you can achieve it

**Comment by kaso17** [comment] 2018-04-06 10:39
Just wondering: what's wrong with the current update mechanism?

**Comment by edalex86** [comment] 2018-04-06 10:53
I just thought such approach could be less invasive.  I didn't investigate current update procedure but it couldn't avoid replacing exe, start-stop service.

**Comment by ngosang** [comment] 2020-01-20 23:57
Duplicate of #6357

**Closed by ngosang** 2020-01-20 23:57 UTC
Labels: Enhancement
