### ISSUE TITLE
PSARips indexer (using new VIP tag)

### ISSUE THREAD

**Issue by GOvEy1nw** [Jackett/Jackett#5127] opened 2019-04-25 19:47 UTC
Hi, so I know you've been asked to do a PSArips indexer before, however this was before they offered the option to bypass redirects and captcha's if you donate, which I think makes creating an indexer more possible.

It'd be great if you could look into this again. I'd be happy to give you my login to have a poke around.

**Comment by garfield69** [comment] 2020-01-13 03:26
duplicate of #1216 .
I've added your request to the comments in that ticket.

**Closed by garfield69** 2020-01-13 03:26 UTC
