### ISSUE TITLE
rss load with rtorrent

### ISSUE THREAD

**Issue by a33max** [Jackett/Jackett#5267] opened 2019-05-14 00:40 UTC
I'm not sure if this is an acceptable way to use Jackett, but I thought I ask.
Jackett Version 0.11.327.0 (no password, port 10210)
rTorrent: 0.9.6/0.13.6
Both are on the same seedbox.

I setup Jackett to an Indexer for 1337x.
I copied the RSS Feed and added it to rtorrent.
So rtorrent loads 50 torrents in my RSS feed with every RSS update.
When I try to load the torrent, I get an error, here is an example of the error.

[12.05.2019 22:07:54] Error loading torrent. (http://myktek.soul.seedhost.eu/myktek/jackett/dl/1337x/?jackett_apikey=aopoo00mpiys5ppoprxke9pxp8th8i37&path=Q2ZESjhQakluTGQ3dTJSS2h1T2lKQXdIdW9sYjZsSVgzVGhJSHd1b3pSQjNPX1hvdWxpTHVQZGpmdVdPYnVHZGEzLUZ5cm1YX1RfWjdDcXVJTHlrTDdxWWJzblNwNWVNSl9rdHBKZzdYVFZ5NG9LSDRlak1aWnpIVkYySFhhN1I3ekFGVzhMWmlSZ005QmtwODVzbWNlcHpIdnRha25sOXp1MGdNMGVuQkcwejg5RUE1YXFycmZTSHUxM24zY0NSTTJXQS1BLUJXSjBBMXBULU1nVlJFVXdXUjhR&file=333+Science+Tricks+and+Experiments)

I know this probably doesn't help, but I took that URL and pasted into a browser and nothing happened.
So I'm wondering if there is something else that is needed, authentication for Jackett? (but I didn't set a password, so maybe a port is required?)

Maybe it wasn't designed to be used in this fashion? or rTorrent doesn't know how to handle it properly?

**Comment by recse** [comment] 2019-05-17 15:41
I have the same problem. It seems that Jackett does not work since 5 data ago

**Comment by victor141516** [comment] 2019-06-19 00:18
I'm having this same error. I was using qBittorrent  andd Jackett works flawlessly but today I gave a try to rtorrent and this happened.

**Comment by whalehub** [comment] 2019-12-18 13:50
@a33max @recse @victor141516 A workaround that you can use for now is to click on the wrench icon in Jackett next to the 1337x.to indexer, change "magnet" to "iTorrents.org" in the "Download link" drop-down menu and click "Okay".

**Comment by ngosang** [comment] 2020-01-14 19:05
Duplicate of #5835

**Comment by garfield69** [comment] 2020-04-13 07:49
possibly fixed with Jackett 0.15.36

**Comment by RoloSoze** [comment] 2020-04-23 02:59
@a33max @recse @victor141516 Did updating to version 0.15.36, or later, fix this issue for you guys?

**Comment by garfield69** [comment] 2022-07-20 20:53
closing as stale. open a new ticket if problem persists.

**Closed by garfield69** 2022-07-20 20:53 UTC
Labels: Confirmed
