### ISSUE TITLE
[torrentsyndikat] Exception (torrentsyndikat): String '' was not recognized as a valid DateTime.: Parse error (Test)

### ISSUE THREAD

**Issue by xorsss** [Jackett/Jackett#7481] opened 2020-03-03 18:52 UTC
Jackett.Common.IndexerException: Exception (torrentsyndikat): String '' was not recognized as a valid DateTime.
 ---> System.Exception: Parse error
 ---> System.FormatException: String '' was not recognized as a valid DateTime.
   at Jackett.Common.Indexers.TorrentSyndikat.PerformQuery(TorznabQuery query)

**Comment by ngosang** [comment] 2020-03-03 19:14
Caused by #7386

@xorsss Could you upload the HTML source code? That will help a lot.

    Please, open torrentsyndikat in your browser and go to the list of torrents
    Right click, save page as HTML
    Remove personal information from the HTML file (without breaking the code)
    Upload the html file here.

**Comment by xorsss** [comment] 2020-03-03 19:26
Sorry, i'm not familiar enough to do this, maybe another user can help. :(

**Comment by ngosang** [comment] 2020-03-03 19:31
I will try to fix it blind, but no guarantees.

**Comment by tr1ckert** [comment] 2020-03-03 19:37
Here is the html thing.
Rename to .htm
[asdf.txt](https://github.com/Jackett/Jackett/files/4283230/asdf.txt)

**Comment by ngosang** [comment] 2020-03-03 20:16
Thank you. It will be fixed in the next release.

**Closed** 2020-03-03 20:35 UTC

**Comment by garfield69** [comment] 2020-03-04 06:33
Jackett 0.13.446
