### ISSUE TITLE
Jackett not working error log

### ISSUE THREAD

**Issue by lordraiden** [Jackett/Jackett#5342] opened 2019-05-26 15:16 UTC
Whever I try to test any site I get this error
Any idea what is this and how to fix it?

> Jackett.Common.IndexerException: Exception (limetorrents): The operation was canceled. ---> System.OperationCanceledException: The operation was canceled.
>    at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
>    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 241
>    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
>    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445
>    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1230
>    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
>    --- End of inner exception stack trace ---
>    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
>    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
>    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
>    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
>    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

**Comment by garfield69** [comment] 2019-05-26 18:31
the stack trace just shows that jackett did not get a response back from limetorrents before the timeout caused the attempt to be cancelled.
what version of jackett are you on, and on what platform?

**Comment by lordraiden** [comment] 2019-05-26 18:41
I am on unraid (slackware) using dockers
 Jackett Version 0.11.375.0 

THe same happens with other trackers, with IPtorrents which is the one I am most interested in configure when I click on configure (blue button) nothing happens

**Comment by garfield69** [comment] 2019-05-26 18:57
lots of people have issues with iptorrents #5164 #4624 #4596 and I cant help with that as I don't have an account there.
bu if you are saying that all your indexers are timing out the the problem is more to do with docker than with jackett.
try setting up a Shell access whilst the container is running:
`docker exec -it jackett /bin/bash` (replace jackett with whatever you called the container)
and then please post the output of 
`curl -vvv https://www.limetorrents.info/` 
and 
`openssl s_client -connect www.limetorrents.info:443`

**Comment by lordraiden** [comment] 2019-05-26 20:06
I have invites to Iptorrents if you want one
This is the ouput

> # curl -vvv https://www.limetorrents.info/
*   Trying 104.27.209.30...
* TCP_NODELAY set
*   Trying 2606:4700:20::681b:d11e...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:20::681b:d11e: Cannot assign requested address
*   Trying 2606:4700:20::681b:d01e...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:20::681b:d01e: Cannot assign requested address
*   Trying 2606:4700:20::681b:d11e...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:20::681b:d11e: Cannot assign requested address
*   Trying 2606:4700:20::681b:d01e...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:20::681b:d01e: Cannot assign requested address
*   Trying 2606:4700:20::681b:d11e...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:20::681b:d11e: Cannot assign requested address
*   Trying 2606:4700:20::681b:d01e...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700:20::681b:d01e: Cannot assign requested address
^C

THis on doesn't return anything after a while 
openssl s_client -connect www.limetorrents.info:443

**Comment by garfield69** [comment] 2019-05-26 20:09
If you send an invite to garfieldsixtynine @ gmail.com for iptorrents that would be useful thanks.
now, back to your main issue. I am seeing ipv6 addresses... are you set up for ipv6?

**Comment by lordraiden** [comment] 2019-05-26 20:14
I am not using ipv6, not in my network or in the docker

**Comment by garfield69** [comment] 2019-05-26 20:22
@flightlevel  @kaso17  any ideas about this docker ticket? seems after the first attempt at binding an ivp4 address, the curl then just tries ipv6 addresses...

**Comment by lordraiden** [comment] 2019-05-26 20:34
Finally it gave some output

> 
> #  openssl s_client -connect www.limetorrents.info:443
> 22515903832512:error:0200206E:system library:connect:Connection timed out:../crypto/bio/b_sock2.c:108:
> 22515903832512:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:109:
> 22515903832512:error:0200206E:system library:connect:Connection timed out:../crypto/bio/b_sock2.c:108:
> 22515903832512:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:109:
> 22515903832512:error:02002063:system library:connect:Cannot assign requested address:../crypto/bio/b_sock2.c:108:
> 22515903832512:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:109:
> 22515903832512:error:02002063:system library:connect:Cannot assign requested address:../crypto/bio/b_sock2.c:108:
> 22515903832512:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:109:
> connect:errno=99
> #

**Comment by sljdhl** [comment] 2019-05-30 12:10
Hello, im getting the same error but with superbits..
`curl -vvv https://www.superbits.org/
*   Trying 85.17.12.184...
* TCP_NODELAY set
* connect to 85.17.12.184 port 443 failed: Connection timed out
* Failed to connect to www.superbits.org port 443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to www.superbits.org port 443: Connection timed out`
and
`openssl s_client -connect www.superbits.org:443
139904072090048:error:0200206E:system library:connect:Connection timed out:../crypto/bio/b_sock2.c:108:
139904072090048:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:109:
connect:errno=110`
If I restart Jackett it works sometimes, even testing may work for a little while. But then im back to the same error message as Lordraiden

**Comment by jeanfrancoislarente** [comment] 2019-07-30 14:17
@garfield69 any update on iptorrent fix after getting an invite?

**Comment by jeanfrancoislarente** [comment] 2019-07-30 14:24
Installed pre-release (0.11.546.0) and used cookie approach - resolved the issue for me.

**Comment by ngosang** [comment] 2019-12-02 17:29
@garfield69 I think you can close. This is too generic...

**Closed** 2019-12-02 17:35 UTC
