### ISSUE TITLE
[torrent9] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by elamotte** [Jackett/Jackett#2429] opened 2018-01-15 20:06 UTC
Found no results while trying to browse this tracker (Test)

-------------------------------

**Comment by garfield69** [comment] 2018-01-15 20:42
I have no problems accessing torrent9 from my win7 Jackett Dashboard.
Since you have provided absolutely none of the requested details listed in this ticket when you first opened it, your are not helping us  to help you. :-(
So, upgrade to the latest Jackett v0.8.602 and try again.
If it is still not working then please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by garfield69** [comment] 2018-01-24 18:51
Duplicate of #2414

**Closed by garfield69** 2018-01-24 18:51 UTC
Labels: Full logs needed
