### ISSUE TITLE
[nyaasi] Exception (nyaasi): error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by Webatron11** [Jackett/Jackett#11954] opened 2021-06-24 11:49 UTC
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux, Gentoo

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Not sure

**.Net Version**: Not sure

**Jackett Version**: v0.18.15

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Add tracker Nyaa.si
Attempt to test tracker Nyaa.si

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

`Exception (nyaasi): error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure: The SSL connection could not be established, see inner exception.`

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment] 2021-06-25 05:54
closing as  a duplicate of #11933
is a linux openssl tls1.3 cypher handshake miss-match something or rather.

**Closed by garfield69** 2021-06-25 05:54 UTC
