### ISSUE TITLE
[abnormal] Exception (abnormal): An error occurred while sending the request: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by jaydee99** [Jackett/Jackett#1966] opened 2017-10-14 21:12 UTC
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
Abnormal not working anymore here...

When trying to add it again, it says : "An error occurred while sending the request: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /build/mono-5.2.0.224/external/boringssl/ssl/handshake_client.c:1132)"

Thanx guys !

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment] 2017-10-17 09:37
This is often caused by missing CA certificates.
Try reimporting the certificates:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`

**Comment by kaso17** [comment] 2017-10-25 15:52
no reply, closing

**Closed by kaso17** 2017-10-25 15:52 UTC
