### ISSUE TITLE
[req]: javbus

### ISSUE THREAD

**Issue by vsin123** [Jackett/Jackett#13450] opened 2022-08-04 19:03 UTC
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: javbus
- URL: https://javbus.com
- Description: Online JAV Magnet Links Sharing Website, JAV ID Search and Sharing JAV Magnet Links
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment] 2022-08-04 19:07
duplicate of ##10479

**Closed by garfield69** 2022-08-04 19:07 UTC
