### ISSUE TITLE
Unable to add IPTorrents

### ISSUE THREAD

**Issue by amgreenwalt** [Jackett/Jackett#4075] opened 2018-10-26 16:52 UTC
CentOS Linux release 7.5.1804 (Core)
Mono version 5.16.0.187
Jackett Version 0.10.380.0

I have just installed Jackett and keep getting an error when trying to add IPTorrents as an indexer.

----------------------------------------
Oct 26, 2018 02:32:28 AM	Info	
Request finished in 1230.8413ms 500 application/json
Oct 26, 2018 02:32:28 AM	Error	
Jackett.Common.ExceptionWithConfigData: HomeUploadRequestSettingsInvitesTop 10RulesMirrorsFAQIPT BrowserStaffHelpamgreenwalt1(0)BookmarksChatTorrent SubsTopic SubsNew PostsMy Topics - 1.9 GB 0 B 0  0 0.0 2018-10-26 16:33 UTC			Browse		Movies				TV shows		Forums		RSS	TV Guide	Donate
  at Jackett.Common.Indexers.IPTorrents+<>c__DisplayClass15_0.<ApplyConfiguration>b__0 () [0x00029] in C:\projects\jackett\src\Jackett.Common\Indexers\IPTorrents.cs:217 
  at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK (System.String cookies, System.Boolean isLoggedin, System.Func`1[TResult] onError) [0x00034] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:267 
  at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration (Newtonsoft.Json.Linq.JToken configJson) [0x00306] in C:\projects\jackett\src\Jackett.Common\Indexers\IPTorrents.cs:212 
  at Jackett.Server.Controllers.IndexerApiController.UpdateConfig (Jackett.Common.Models.DTO.ConfigItem[] config) [0x0012d] in C:\projects\jackett\src\Jackett.Server\Controllers\IndexerApiController.cs:108 
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <703e2bb4fd86407aa6c8a21fddb328a9>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <0c4aed80d53349aab59d38ff83ba08f0>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <f5622e7f79be469e83d9e2bde9addd07>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <6ec74abaae414d0a97ef0613561299ae>:0 
  at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x001c8] in <560d56f8376d4258a59ad5478913c777>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x00042] in C:\projects\jackett\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:29 
Oct 26, 2018 02:32:28 AM	Info	
Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) in 1209.6976ms
Oct 26, 2018 02:32:28 AM	Debug	
WebClient(HttpWebClient): Returning OK => 64064 bytes
Oct 26, 2018 02:32:27 AM	Debug	
WebClient(HttpWebClient).GetBytes(Url:https://iptorrents.com/t)
Oct 26, 2018 02:32:27 AM	Debug	
WebClient(HttpWebClient): Returning Redirect => https://iptorrents.com/t 0 bytes
Oct 26, 2018 02:32:27 AM	Debug	
WebClient(HttpWebClient).GetBytes(Url:https://iptorrents.com/)
Oct 26, 2018 02:32:27 AM	Debug	
WebClient(HttpWebClient): Returning Redirect => https://iptorrents.com/ 
Oct 26, 2018 02:32:27 AM	Debug	
WebClient(HttpWebClient).GetString(Url:https://iptorrents.com/take_login.php)
Oct 26, 2018 02:32:27 AM	Info	
Executing action method Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) with arguments (Jackett.Common.Models.DTO.ConfigItem[]) - Validation state: Valid
Oct 26, 2018 02:32:27 AM	Info	
Authorization was successful.
Oct 26, 2018 02:32:27 AM	Info	
Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole)
Oct 26, 2018 02:32:27 AM	Info	
Request starting HTTP/1.1 POST http://64.38.234.47:9117/api/v2.0/indexers/iptorrents/config application/json 261
----------------------------------------

**Comment by garfield69** [comment] 2018-10-26 20:43
duplicate of #4073

**Closed by garfield69** 2018-10-26 20:43 UTC
